### ISSUE TITLE
rules for membership and voting

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1]
I assume we'll want to establish some sort of governance structure for the project. Let's determine rules for membership and voting.

For now I left the rules for voting in the [README](https://github.com/coreos/fedora-coreos-tracker/blob/6a94a33120d31d0b9dcfdedd1a65b4ffee4010af/README.md#voting) that we used in the atomic working group. We can start with those and modify.

**Comment by dustymabe** [comment]
discussed during [today's meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/BGGRMVVU7KLKLSFXJRDURTQFMEEFEPSG/) will wait for input from @sanjabonic

**Comment by sanjabonic** [comment]
For the issue tracking record, I think we've long and wide discussed the rules for the Project Atomic WG, they're in line with a good voting structure and I think we should keep it - if it comes up as a problem in the coming months or years, we can then change it if applicable.

From my part, I'd say we can close this issue and use the rules set out in the README.

**Comment by bgilbert** [comment]
@dustymabe I think we can close this out for now?

**Comment by dustymabe** [comment]
👍
