### ISSUE TITLE
Why there is login message not coming from /etc/issue and /etc/motd?

### ISSUE THREAD

**Issue by shiraiyui** [coreos/fedora-coreos-tracker#100]
I've checked and edited these two files /etc/issue and /etc/motd, but it still shows the message (not from /etc/issue or /etc/motd) below after i successfully login(no matter from the console or SSH or something else):

Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-117-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
New release '18.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
-------------------------------------------------
I really wonder why. Where does it come from?

**Comment by bgilbert** [comment]
Hi @shiraiyui, this issue tracker is for Fedora CoreOS.  Please see the [Ubuntu community support page](https://www.ubuntu.com/support/community-support) for help with Ubuntu.
