### ISSUE TITLE
Platform Request: Nutanix AOS with AHV

### ISSUE THREAD

**Issue by sohankunkerkar** [coreos/fedora-coreos-tracker#1007]
In order to implement support for a new cloud platform in Fedora CoreOS, we need to know several things about the platform.  Please try to answer as many questions as you can.

- [x] Why is the platform important?  Who uses it?

   To deliver and support open hybrid multi-cloud solution driven by Red Hat’s Openshift and Nutanix Cloud platform.
- [x] What is the official name of the platform?  Is there a short name that's commonly used in client API implementations?

   Nutanix AHV (nutanix)
- [x] How can the OS retrieve instance userdata?  What happens if no userdata is provided?

   ` userdata` is provided through config drive v2 similar to Openstack.
- [x] Does the platform provide a way to configure SSH keys for the instance?  How can the OS retrieve them?  What happens if none are provided?
 
     No
- [x] How can the OS retrieve network configuration?  Is DHCP sufficient, or is there some other network-accessible metadata service?

     DHCP (via Nutanix IPAM)
- [x] In particular, how can the OS retrieve the system hostname?

     DHCP (via Nutanix IPAM)
- [x] Does the platform require the OS to have a specific console configuration?

     No
- [x] Is there a mechanism for the OS to report to the platform that it has successfully booted?  Is the mechanism required?

     No
- [x] Does the platform have an agent that runs inside the instance?  Is it required?  What does it do?  What language is it implemented in, and where is the source code repository?

     No
- [x] How are VM images uploaded to the platform and published to other users?  Is there an API?  What disk image format is expected?

   API (qcow2 image format)
- [x] Are there any other platform quirks we should know about?

   cloud-init config drive v2 (similar to Openstack), but in this case, meta_data.json functionality is not implemented

**Comment by lucab** [comment]
I'm having some troubles putting the following points together:
 >  - userdata is provided through config drive v2 similar to Openstack.
 >  - meta_data.json functionality is not implemented
 >  - hostname will be fetched from the metadata in cloud-init user_data

If there is not metadata JSON, and the userdata is storing the Ignition config, then how is the hostname provided to the VM?
Similar question for SSH keys: if the userdata holds an Ignition config (and not a cloud-init config), how are cloud-keys provided to the VM?

**Comment by sohankunkerkar** [comment]
Thanks for your questions. PFB my inline response:

> I'm having some troubles putting the following points together:
> 
> > * userdata is provided through config drive v2 similar to Openstack.
> > * meta_data.json functionality is not implemented
> > * hostname will be fetched from the metadata in cloud-init user_data
> 
> If there is no metadata JSON, and the userdata is storing the Ignition config, then how is the cloud-hostname provided to the VM?

When a VM is created on a Nutanix managed subnet, their internal [IPAM](https://portal.nutanix.com/page/documents/details?targetId=AHV-Admin-Guide-v6_0:ahv-acr-host-ipam-r.html) mechanism offers the hostname and IP address using DHCP

> Similar question for SSH keys: if the userdata holds an Ignition config (and not a cloud-init config), how are cloud-keys provided to the VM?

I have updated the details about ssh-keys in the above questionnaire to address your concern.

**Comment by dustymabe** [comment]
One other thing to flesh out that doesn't block adding this platform:

- Does Nutanix offer this platform as a cloud service?
    - And... Could we get an unbilled account to execute tests for our images

**Comment by cverna** [comment]
> One other thing to flesh out that doesn't block adding this platform:
> 
>     * Does Nutanix offer this platform as a cloud service?       
>       * And... Could we get an unbilled account to execute tests for our images

I pitched the idea to @vnephologist a couple months ago.  Andy is sponsoring a environment for Fedora CoreOS to run our CI tests, something that would be interesting ?

**Comment by jlebon** [comment]
This was discussed in [last week's community meeting](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2021-11-10-16.31.html):

```
16:54:24 <jlebon> #agreed we will add FCOS support for Nutanix AHV after fleshing out the few remaining questions
```

**Comment by dustymabe** [comment]
The `Nutanix` artifacts are now on the [download page](https://getfedora.org/en/coreos/download?tab=cloud_operators&stream=stable&arch=x86_64) for all streams!

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `35.20211119.3.0`.
