### ISSUE TITLE
Platform Request: VirtualBox

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#1008]
In order to implement support for a new cloud platform in Fedora CoreOS, we need to know several things about the platform.  Please try to answer as many questions as you can.

- [x] Why is the platform important?  Who uses it?

VirtualBox is a user-friendly, OSS desktop virtualization package that runs on Linux, Windows, and macOS.  It provides a free, cross-platform alternative to VMware.

- [x] What is the official name of the platform?  Is there a short name that's commonly used in client API implementations?

VirtualBox.  It's sometimes shortened to VBox.  Ignition already uses the `virtualbox` platform ID.

- [x] How can the OS retrieve instance userdata?  What happens if no userdata is provided?

There's a "guest property" mechanism, added to Ignition in https://github.com/coreos/ignition/pull/1269.  The host-guest interface allows detecting that a property is absent.

- [x] Does the platform provide a way to configure SSH keys for the instance?  How can the OS retrieve them?  What happens if none are provided?

There's no special platform support for SSH keys.

- [x] How can the OS retrieve network configuration?  Is DHCP sufficient, or is there some other network-accessible metadata service?

DHCP.

- [x] In particular, how can the OS retrieve the system hostname?

No special support.

- [x] Does the platform require the OS to have a specific console configuration?

No.  Graphical console is the default.  Serial ports can be configured but the output is not accessible via the GUI.

- [x] Is there a mechanism for the OS to report to the platform that it has successfully booted?  Is the mechanism required?

It's possible to report status to the host via guest properties, but not required.

- [x] Does the platform have an agent that runs inside the instance?  Is it required?  What does it do?  What language is it implemented in, and where is the source code repository?

VirtualBox Guest Additions are implemented in C++ and [included in the VirtualBox source tree](https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Additions).  They provide [several optional features](https://www.virtualbox.org/manual/ch04.html#guestadd-intro).

- [x] How are VM images uploaded to the platform and published to other users?  Is there an API?  What disk image format is expected?

VirtualBox can import existing disk images in a variety of formats, including its native VDI format.  However, this requires manually creating a VM afterward.  It also supports creating VMs from OVF and OVA packages containing VMDK disk images.  OVA seems like the best image format for publication.

- [x] Are there any other platform quirks we should know about?

The primary user interface for setting guest properties is to include the new value inline in a `VBoxManage` command.  With this approach, Ignition configs are constrained by [OS-specific limits](https://github.com/coreos/ignition/pull/1269#issue-754429117) on command line length.

**Comment by bgilbert** [comment]
This would be a good project for someone who wants to get experience adding a platform to the OS.  There's a WIP coreos-assembler PR in https://github.com/coreos/coreos-assembler/pull/2489.  I think the remaining items are:

- [ ] Optimize the hardware declared in the OVF template
- [ ] Plumb the new image into the pipeline, website, build browser, etc.
- [ ] While you're here, https://github.com/coreos/fedora-coreos-tracker/issues/675

**Comment by cgwalters** [comment]
One thing that seems specifically useful about this platform is for testing changes (specifically Ignition) locally, particularly on non-Linux (e.g. MacOS and Windows).  Basically if we documented to people how to have a `Vagrantfile` that runs some Ignition code on `vagrant up` it'd feel familiar to Vagrant users.

I know nowadays particularly on Windows there's WSL, and there's even an effort to have something like FCOS in WSL but part of the idea of Vagrant is that it's cross-platform.

**Comment by dustymabe** [comment]
We discussed this at the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/OEG52ICGOZYMJJWVCS7AENKKS54EXPKK/). There didn't seem to be any objects to adding a platform for VirtualBox. Only some concerns from Neal about the OVA image format. He's going to followup with @bgilbert on that.

**Comment by bgilbert** [comment]
A few followups to the meeting discussion:

- From a quick test, it appears that VirtualBox's DHCP server in NAT mode does not send a DHCP hostname.
- It seems that all of the VBox kernel modules are now included in `kernel-core`.
- The current plan is to use a VirtualBox-specific OVF template that accounts for VirtualBox's hardware support and quirks, wrapped into an OVA with a VMDK disk image.  @Conan-Kudo, does that address your concerns?

**Comment by Conan-Kudo** [comment]
@bgilbert Works for me, yeah!

**Comment by jmarrero** [comment]
working on other issues, I don't think I will get to this any time soon. Someone else can feel free to pick it up.

**Comment by bgilbert** [comment]
This functionality went into `stable` release 35.20220327.3.0, `testing` release 35.20220410.2.1, and `next` release 36.20220410.1.1.  Please try it out and report any issues.

**Comment by dustymabe** [comment]
With updated documentation to use these new images at https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-virtualbox/
