### ISSUE TITLE
How can i make ISO is not LIVE

### ISSUE THREAD

**Issue by Rtoax** [coreos/fedora-coreos-tracker#1013]
when i create a new GuestOS with `fedora-coreos-34.20211016.3.0-live.x86_64.iso`, every time reboot, qcow2 is invalide. how can i turn, how should  i do. modify `EFI/fedora/grub.cfg`?

**Comment by bgilbert** [comment]
If you're looking for instructions on installing Fedora CoreOS to disk, see [this docs page](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/).

**Comment by dustymabe** [comment]
@Rtoax - can you give us any more information or confirm that the documentation @bgilbert linked to addresses your issue?

**Comment by dustymabe** [comment]
Closing this since there is a lack of response. @Rtoax if you have more information about the issue please add it and re-open. Thanks!
