### ISSUE TITLE
iPXE booting on aarch64 does not work with compressed kernel

### ISSUE THREAD

**Issue by Prashanth684** [coreos/fedora-coreos-tracker#1019]
The aarch64 kernel is compressed and does not provide a default decompressor. iPXE booting using the compressed aarch64 kernel fails because iPXE [does not support](https://github.com/coreos/fedora-coreos-tracker/issues/258) compressed kernels. This is the error we get when trying it:

![image](https://user-images.githubusercontent.com/1717248/141185571-96803201-4ded-49d2-bf74-a27b08e546a7.png)

iPXE does have a fix upstream for this: https://github.com/ipxe/ipxe/commit/866fa1ce7 but it is not in any release yet.
Opening this issue to potentially  discuss whether we need an uncompressed kernel artifact for aarch64.

**Comment by bgilbert** [comment]
aarch64 compressed kernels are gzipped blobs; they're not prefixed with decompression code the way x86_64 kernels are.  aarch64 [considers](https://github.com/torvalds/linux/blob/master/Documentation/arm64/booting.rst#3-decompress-the-kernel-image) decompression to be the bootloader's responsibility.

I think the above commit adds the relevant decompression support to iPXE, but we'd need someone to test it.  Also, it seems the default build configs do not enable compression (the compile flag is `IMAGE_GZIP`).  If enabling that flag solves the problem, we'd probably want to talk to upstream about enabling it by default (at least on aarch64).

If we don't manage to get support enabled by default in iPXE, and we don't want to ship an uncompressed kernel for aarch64, we should at least update our iPXE docs.

**Comment by pamoedom** [comment]
Thanks @Prashanth684 for raising the ticket and @bgilbert for the follow up, much appreciated!

FWIW, [here](https://drive.google.com/file/d/1fhbWnZQEqQtNF-a-fg5LHn0M4hTxr0Wb/view?usp=sharing) you have also the whole boot logs from the latest test when using uncompressed kernel but default compressed initramfs, the boot successfuly worked on this manner.

Regards.

**Comment by aleskandro** [comment]
Refers ARMOCP-169

**Comment by mcb30** [comment]
Upstream iPXE fix merged as https://github.com/ipxe/ipxe/pull/586

**Comment by aleskandro** [comment]
Hello @dustymabe a release is already landed at https://boot.ipxe.org/ that includes the required flag for aarch64. Should we close now?

**Comment by dustymabe** [comment]
Hmm. I was hoping to get a new release here: https://github.com/ipxe/ipxe/tags

i.e. if the sources are picked up and rebuilt (i.e. in a distribution) they'd need a new release from https://github.com/ipxe/ipxe right?

**Comment by dustymabe** [comment]
@mcb30 - are there any plans to do a new upstream release/tag of ipxe?

**Comment by yselkowitz** [comment]
Fedora usually packages a git snapshot of ipxe which matches the version bundled in qemu, but there is an open request to rebase to a current git snapshot: https://bugzilla.redhat.com/show_bug.cgi?id=2063876

**Comment by aleskandro** [comment]
The bz linked above is now closed and the build linked in the errata includes the fix. Should we close this?

**Comment by dustymabe** [comment]
Thanks @aleskandro - I'll close this out.

It is interesting to note, however that in kernel 6.2 the format of the AARCH64 kernel changed. I wonder if iPXE still works with it or not.

**Comment by mcb30** [comment]
> It is interesting to note, however that in kernel 6.2 the format of the AARCH64 kernel changed. I wonder if iPXE still works with it or not.

It does - the AARCH64 kernel is now a standard (non-compressed) UEFI executable and so will work in iPXE even without the `IMAGE_GZIP` feature enabled.
