### ISSUE TITLE
During major version rebases, align FCOS `testing` stream with GA date

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1024]
**Describe the enhancement**

The [current policy](https://github.com/coreos/fedora-coreos-tracker/blob/main/Design.md#major-fedora-version-rebases) for major version rebases reads:

> * Fedora Beta Release
>     * The next stream is switched over to the new release.
> * Fedora Final Freeze
>     * The next stream switches to weekly releases to closely track the GA content set.
> * Fedora CoreOS re-orients its release schedule in the following way:
>     * Week 0 (GA release): triple release; `next` with latest Fedora N content
>     * Week 1: triple release; `testing` release promoted from previous `next`
>     * Week 3: triple release; `stable` release promoted from previous `testing`, now fully rebased to Fedora N. `next` and `testing` are now in sync.

Now that we've had two smooth releases with this cadence, it's time to take the next step and move the schedule back some more to be better in sync with the rest of Fedora (and maybe eventually we'd get to aligning `stable` with GA!).

For Fedora 36, let's aim to have the `testing` release on GA with the new content. This would mostly mean shifting back the "Week N" bits in the above by one week, though there are some details to iron out. Let's discuss those in follow-up comments.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/34ALCEWMKAK4ATLBKOYYNATJGBA74XWN/).

```
11:46:19*    dustymabe | #info we'll discuss this in january 2022 when the F35
                       | rebase has landed in our stable stream and any currently
                       | unknown issues have been fleshed out

```

**Comment by dustymabe** [comment]
Discuss again in the 2022-01-12 meeting.

**Comment by travier** [comment]
We discussed this in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/KWZOD327I54STWS2FCCNL6CN6IT7UA62/):

```
16:53:59 <travier> #agreed For the Fedora 36 rebase, we will aim to align the testing
                   release including the new content with the F36 GA date.
```

**Comment by travier** [comment]
@jlebon should I give that to you?

**Comment by jlebon** [comment]
Sure. Opened https://github.com/coreos/fedora-coreos-tracker/pull/1081 to codify it. We can discuss lower-level details and finalize it there.
