### ISSUE TITLE
Perl package for Fedora Release 32

### ISSUE THREAD

**Issue by balait4** [coreos/fedora-coreos-tracker#1026]
Not able to install perl package in Fedora Release 32. We not in plan to upgrade the OS. So is there any perl version supported for the Release 32? I need to run smartmontool which need perl package. 

**Reproduction steps**
1. Install Fedora Release 32
2. Try to Install perl package: rpm-ostree install perl

**System details**
 - Bare Metal/QEMU/AWS/GCP/etc.: Bare Metal
 - Fedora CoreOS version  : Fedora Release 32

[root ~]# cat /etc/redhat-release 
Fedora release 32 (Thirty Two)

[root@ ~]# uname -a
Linux xxxx 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[root ~]# rpm-ostree install perl
Checking out tree 8d5e042... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora
Updating metadata for 'fedora-cisco-openh264'... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2020-08-25T19:05:18Z
Updating metadata for 'updates'... done
rpm-md repo 'updates'; generated: 2021-05-25T01:50:03Z
Updating metadata for 'fedora'... done
rpm-md repo 'fedora'; generated: 2020-04-22T22:22:36Z
Importing rpm-md... done
⠁  
Forbidden base package replacements:
  libstdc++ 10.1.1-1.fc32 -> 10.0.1-0.11.fc32 (fedora)
  libxcrypt 4.4.16-3.fc32 -> 4.4.20-2.fc32 (updates)
  libgomp 10.1.1-1.fc32 -> 10.0.1-0.11.fc32 (fedora)
This likely means that some of your layered packages have requirements on newer or older versions of some base packages. Doing `rpm-ostree cleanup -m` and `rpm-ostree upgrade` first may help. For more details, sResolving dependencies... done
error: Some base packages would be replaced
[root@ ~]#

**Comment by jlebon** [comment]
Hi @balait4,

Fedora 32 is no longer supported (it has been EOL for almost 6 months now). Please use the latest version. Re. Perl and smartmontools, you should be able to run it inside a privileged container instead of layering on the host.

Tentatively closing.

**Comment by balait4** [comment]
I tried running via privileged container and getting this issue:
unable to open /run/sudo/ts/zabbix: Permission denied
# getsebool -a | grep zabbix
httpd_can_connect_zabbix --> on
zabbix_can_network --> on
zabbix_run_sudo --> on

===============Error====================
Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'sudo: unable to open /run/sudo/ts/zabbix: Permission denied

We trust you have received the usual lecture from the local System
Administrator. It usual

================================================== ============

**Comment by travier** [comment]
We would need a link to a Containerfile and the command line used to start it to help you here.
