### ISSUE TITLE
Make publicly accessible coreos-assembler builds for architectures != x86_64

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1027]
# Feature Request #

## Desired Feature ##

Some of us were discussing that for multi-arch, it's painful to use cosa because it requires either rebuilding it locally or using the VPN to pull from the internal builds we do (does that work?), which could be very slow.

One suggestion was that we could simply have the internally-built multi-arch images be pushed to [the coreos-assembler Quay.io repo](https://quay.io/repository/coreos-assembler/coreos-assembler). See e.g. https://quay.io/repository/fedora/fedora?tag=latest&tab=tags for an example of a multi-arch image.

## Example Usage ##

```
$ podman pull quay.io/coreos-assembler/coreos-assembler:latest-s390x
$ podman pull quay.io/coreos-assembler/coreos-assembler:rhcos-4.9-ppc64le
```

## Other Information ##

Another approach is to keep pursuing trying to [build cosa in Fedora's OSBS](https://bugzilla.redhat.com/show_bug.cgi?id=1733344), though that's a further distance from where we currently stand.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/JLLOIGTLVUQYCZSJ7LKG7CPOGBWMAR2I/):

```
11:50:24        dustymabe | #agreed We will use our existing multi-arch-builders to build COSA for
                          | all architectures and also find a way to push them to quay using
                          | archful manifests so that a single tag in quay can be pulled for any   
                          | architecture we support.

```

**Comment by ravanelli** [comment]
> We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/JLLOIGTLVUQYCZSJ7LKG7CPOGBWMAR2I/):
> 
> ```
> 11:50:24        dustymabe | #agreed We will use our existing multi-arch-builders to build COSA for
>                           | all architectures and also find a way to push them to quay using
>                           | archful manifests so that a single tag in quay can be pulled for any   
>                           | architecture we support.
> ```

I think it could be something  we may use gangplank to trigger a single build to all arches, using the same cosa commit.  I'm not familiar with  buildx or manifests. I willing to work in this task in case no one else is working on it. It would make my life easier with Brew.

**Comment by jcajka** [comment]
Sorry I have missed the initial ping. 

> > Why doesn't Fedora's OSBS support other architectures? Capacity?
> 
> I think it's hardware availability and team capacity.
> 
> > That's a problem that would be solved by unifying Koji to build RPMs as OpenShift pods.
> 

Not really you are back to the "I think it's hardware availability and team capacity." and more, basically making Fedora x86_64 only, at best x86_64 and aarch64 only distro.

I will be happy to help but my understanding has been that this has been HW and capacity issue on FCOS side. I would love to have all official 64bit Fedora arches covered in one go so I can drop my own unofficial builds of cosa(at [quay.io/jcajka/coresos-assembler](https://quay.io/repository/jcajka/coreos-assembler)) and move towards official builds of FCOS on non-intel and eventually drop the unofficial ones at [fedorapeople.org](https://fedorapeople.org/groups/fcos-images/builds/).
My understanding is that this will need relatively significant re-engineering of some parts of FCOS infrastructure/pipeline(if I'm not wrong all container builds are relying on quay.io builders atm). I don't feel I have enough support and resources to spearhead that effort. I will be happy to be proven wrong.

**Comment by cgwalters** [comment]
> Not really you are back to the "I think it's hardware availability and team capacity." and more, basically making Fedora x86_64 only, at best x86_64 and aarch64 only distro.

(Sorry I missed this earlier)

I don't understand; OCP is available for all architectures that Koji builds too; most notably s390x and ppc64le.

**Comment by cgwalters** [comment]
https://podman.io/blogs/2021/10/11/multiarch.html

**Comment by jcajka** [comment]
> > Not really you are back to the "I think it's hardware availability and team capacity." and more, basically making Fedora x86_64 only, at best x86_64 and aarch64 only distro.
> 
> (Sorry I missed this earlier)
> 
> I don't understand; OCP is available for all architectures that Koji builds too; most notably s390x and ppc64le.

Are there any new resource available for it? My general understanding for not having OCP/OKD clusters in Fedora (infra/koji) has been hardware availability and team capacity and I'm not aware that has changed.

**Comment by jlebon** [comment]
When implementing this, it might be helpful to keep in mind https://github.com/coreos/fedora-coreos-tracker/issues/1068. Ideally, we'd design the solution for both of those together, but we can still keep #1068 as a separate follow-on ticket for actually implementing it.

**Comment by dustymabe** [comment]
Nice work @ravanelli. I think what we'll want to do is make sure all builds for a commit pass and then push them up along with the manifest list. This is similar to how we build all artifacts for a FCOS pipeline run then push them (upload to s3) and update the meta.json/builds.json.

This means that if any build fails we won't push - but I'm sure we can architect things in such a way that in which we won't have to do all the work again if one fails on a flake.

**Comment by ravanelli** [comment]
> This means that if any build fails we won't push - but I'm sure we can architect things in such a way that in which we won't have to do all the work again if one fails on a flake.

Since it is a build done using the Docker file `podman --remote build --tag coreos-assembler:aarch64 -f coreos-assembler/Dockerfile` for each arch, we can trigger again only the arch that failed. Once all new images are present in quay, we can upate the manifest. We can double check it also by checking the sha in the tags to make sure they are pointing to the new ones before updating it.

**Comment by dustymabe** [comment]
Some more enablement work for this in https://github.com/coreos/coreos-assembler/pull/3015

**Comment by dustymabe** [comment]
The final bits for this should land in https://github.com/coreos/fedora-coreos-pipeline/pull/586
