### ISSUE TITLE
Ability to create user units via butane/ignition

### ISSUE THREAD

**Issue by Nemric** [coreos/fedora-coreos-tracker#1028]
**Describe the enhancement**
I'd like to create user units in systemd with butane/ignition.
with something like:
```YAML
systemd:
  units:
    - name: ssh-agent.service
      enabled: true
      contents: |
          [Unit]
          Description=SSH key agent
          
          [Service]
          Type=simple
          Environment=SSH_AUTH_SOCK=%t/ssh-agent.socket
          ExecStart=/usr/bin/ssh-agent -D -a $SSH_AUTH_SOCK
          
          [Install]
          WantedBy=default.target

      scope: --system, --user, --runtime, or --global (default to system, in /etc/systemd/user for --user and --global. does --runtime mean something ? )
```

**Comment by lucab** [comment]
Thanks for the report.
The current longer approach is documented at https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-user-systemd-unit-on-boot/.
A feature request to make this flow shorter via syntactic sugar in Butane is tracked at https://github.com/coreos/butane/issues/194.
