### ISSUE TITLE
New Package Request: cachefilesd

### ISSUE THREAD

**Issue by Nemric** [coreos/fedora-coreos-tracker#1029]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)
No additional dependencies
```SHELL
sudo rpm-ostree install --dry-run cachefilesd
[...]
Resolving dependencies... done
Installing 1 packages:
  cachefilesd-0.10.10-10.fc34.x86_64 (fedora)
Exiting because of '--dry-run' option
```

2. What is the size of the package and its dependencies?
[73.61 KB once installed](https://fedora.pkgs.org/35/fedora-x86_64/cachefilesd-0.10.10-12.fc35.x86_64.rpm.html)

3. What problem are you trying to solve with this package? Or what functionality does the package provide?
Allow to have some cache for remote filesystem like NFS

4. Can the software provided by the package be run from a container?  Explain why or why not.
Don't really know or try hard enough to do that but it seems that it's too low level to be used in a container

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?
no

6. Can the tool(s) provided by the package be helpful in debugging networking issues?
no

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.
I don't know what is day 2 operation, but it's possible to layer it via `rpm-ostree install cachefilesd`

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?
no relevant

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)
no

10. Does the software provided by the package have a history of CVEs?
Didn't find any, no

**Comment by travier** [comment]
> 4. Can the software provided by the package be run from a container?  Explain why or why not.
>    Don't really know or try hard enough to do that but it seems that it's too low level to be used in a container

According to the docs on https://github.com/jnsnow/cachefilesd & http://people.redhat.com/~dhowells/fscache/, I don't think this will work from inside a container, even a privileged one as this is closely tied to the host mount-points and the service units tries to load a kernel module.

> 7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.
>    I don't know what is day 2 operation, but it's possible to layer it via `rpm-ostree install cachefilesd`

Day-2 operation means a post installation step, thus after Ignition as run on first boot. In this case, it should be fine to overlay the package as needed (`rpm-ostree install --apply-live cachefilesd`) before setting up any NFS mount-points for example.

> 8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?
>    no relevant

We need the service here so this does not apply.

Overall, I would vote for overlaying the package on first boot.

**Comment by Nemric** [comment]
Do you mean that I should run `rpm-ostree install --apply-live cachefilesd` in a systemd unit (a oneshot service ?) with `ConditionFirstBoot=yes` parameter ?

What about mounts in ignition ? I'll have to create an `After=` condition :/ ?

That sounds good ... would be better if included in packege

I'll wait for up votes before closing ;)

**Comment by travier** [comment]
> Do you mean that I should run `rpm-ostree install --apply-live cachefilesd` in a systemd unit (a oneshot service ?) with `ConditionFirstBoot=yes` parameter ?

Yes, you can probably use the example from https://docs.fedoraproject.org/en-US/fedora-coreos/os-extensions/#_example_layering_nano_and_setting_it_as_the_default_editor as a base.

> What about mounts in ignition ? I'll have to create an `After=` condition :/ ?

Yes, mount points will have to be ordered after the unit mentioned above.

**Comment by cgwalters** [comment]
Weak +1 to just adding this, it is small, self contained and off by default.  Since we ship NFS userspace, it makes sense to ship cachefiles userspace too.  I think cachefiles is under heavy development in the kernel, but what it's doing really makes sense for network filesystems.

But, of course with every new package request like this, we should keep in mind that https://github.com/coreos/enhancements/blob/main/os/coreos-layering.md is in progress, and that will also be another option for users.

**Comment by cgwalters** [comment]
On the flip side, cachefiles is going through a big rewrite on the kernel side: https://listman.redhat.com/archives/linux-cachefs/2021-November/msg00058.html and it seems like this may move chunks of the functionality into the kernel too.

So perhaps that's an argument to not add by default, and have anyone who wants this today do via layering.

**Comment by jlebon** [comment]
This was dicussed in [today's meeting](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2021-12-01-16.31.log.txt):

```
17:01:36 <jlebon> #agreed we will not add cachefilesd to the host for now. we will wait for
                  feedback from the reporter as well as from the current upstream rewrite
                  before re-evaluating. meanwhile, package layering should work.
```

**Comment by Nemric** [comment]
Looks like fs-cache rewrite will land on Fcos36 : https://news.itsfoss.com/linux-kernel-5-17-release/
Can't wait to give it a try, check for stability that is a bit tricky for now ... it stops working and I can't figure out why :/
Hope the rewrite will add more reliability 🤞

**Comment by Nemric** [comment]
It looks like new fscache rewriting doesn't need cachefilesd service any more :|
So, let's go without it ! ;)
