### ISSUE TITLE
Have a mechanism for syncing release checklists across projects

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1035]
**Describe the enhancement**

Right now, we have very similar (but not exactly the same) release checklists for a lot of our upstream projects. Some (e.g. all the pure Rust ones) are more similar to each other than others. It's a pain to keep them in sync. Exhibit A: see all the PRs auto-linked to this PR: https://github.com/coreos/coreos-installer/pull/685.

Let's figure out a way to make it easier.

**Comment by jlebon** [comment]
We discussed this in [the community meeting today](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2021-12-01-16.31.log.txt). Some things that came up:
- We could keep it all in fedora-coreos-tracker or some other new repo, and have something that syncs it out to all the projects.
- We could keep it all in repo, and make that repo a submodule of other repos, which Dependabot can keep up to date. Not sure if that's compatible with GitHub though (e.g. creating cards from a template residing in a submodule).
- We could work on automating releases, and then we could have the automation scripts/configs be in a central location.

**Comment by bgilbert** [comment]
Another option mentioned in the meeting is to keep it all in some centralized repo, without any syncing.  IMO that's the easiest option to implement in the short term.  I'm not sure it's very important to keep the release checklists in the same repo as the code.

**Comment by travier** [comment]
> Another option mentioned in the meeting is to keep it all in some centralized repo, without any syncing. IMO that's the easiest option to implement in the short term. I'm not sure it's very important to keep the release checklists in the same repo as the code.

+1 from me for this one. Advantages: This keeps the release check lists in a central place, does not create churn on the tracker just for release work, enables progressive unification and simplifies changes in one PR for all of them.

I'm -1 for the submodule repo as it will still requires PRs to update each instance in all repos thus not getting us much.

**Comment by bgilbert** [comment]
We mostly have two checklists (one for Go and one for Rust) with some minor variations for different projects.  We could have two checklist templates with conditionals, and then a config file for each repo that enables the appropriate feature flags.

**Comment by bgilbert** [comment]
We now have checklist templates in https://github.com/coreos/repo-templates, with a GitHub Actions workflow that PRs changes back to the individual repos.  I'll close this out, and we can continue iterating in that repo.
