### ISSUE TITLE
`ConditionKernelCommandLine=ostree` failed

### ISSUE THREAD

**Issue by Rtoax** [coreos/fedora-coreos-tracker#1039]
In ignition-ostree-transposefs-detect.service, `ConditionKernelCommandLine=ostree` failed, maybe same as other service, which has `ConditionKernelCommandLine=ostree`.

**Comment by dustymabe** [comment]
Hey @Rtoax - We periodicially go through and close issues that are lacking enough information for us to take any action. For your various issues/PRs you have open please try to make sure you answer any open questions or requests for more information that exist.

When you open new issues or PRs in the future it will help to add as much information as you can to make sure we can glean all of the context on why an issue is an issue or why a change is needed.

**Comment by bgilbert** [comment]
Closing due to lack of response.  If you can provide the requested information, please feel free to reopen.
