### ISSUE TITLE
kola: ignition config sizes for tests can become too large to pass to instances

### ISSUE THREAD

**Issue by saqibali-2k** [coreos/fedora-coreos-tracker#1041]
Previously, `non-exclusive-test` config sizes had grown to a point where aws 
userdata limit was exceeded (as seen in https://github.com/coreos/fedora-coreos-tracker/issues/1030). Compressing the config
has solved the problem for now, but we will likely see down the road. Let's try to come 
up with a more robust solution.

**Comment by saqibali-2k** [comment]
One approach that was discussed earlier:
>For the long term solution, I was thinking that we could just go with jlebon's earlier 
suggestion of adapting coreos/coreos-assembler#2516 to further constrain buckets 
depending on config size. For any test that is exclusive and has a config size that is too large, we 
could add a remote config the way it was done in this PR: coreos/fedora-coreos-config#1232.

**Comment by dustymabe** [comment]
This should be fixed by coreos/coreos-assembler@ce03266 (part of https://github.com/coreos/coreos-assembler/pull/2516)
