### ISSUE TITLE
systemd-resolved overwrites symlink

### ISSUE THREAD

**Issue by BrentRose** [coreos/fedora-coreos-tracker#1047]
**Describe the bug**
systemd-resolved replaces file and removes symlink for /run/systemd/resolve/stub-resolv.conf

**Reproduction steps**
1. Upgrade from 34.20210821.3.0 to 35.20211119.3.0

**Expected behavior**
Leave symlink in tact

**Actual behavior**
systemd-resolved recreates the /run/systemd/resolve/stub-resolv.conf file which removes the symlink.  This causes the /etc/resolv.conf to use the 127.0.0.53 DNS server instead of our supplied nameservers. 

**System details**
 - vmware
 - Fedora CoreOS version 35.20211119.3.0

**Comment by BrentRose** [comment]
Here's what we see on a working host running 34.20210821.3.0  before the upgrade.

[root@xxxxxxxxxx ~]# cat /etc/resolv.conf
# This is /run/systemd/resolve/resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 10.x.x.x
nameserver 10.x.x.x
search xxxxxxx

[root@xxxxxxxxxx ~]# ls -l /etc/resolv.conf
lrwxrwxrwx. 1 root root 39 Nov 24 19:14 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf

[root@xxxxxxxxx ~]# ls -l /run/systemd/resolve/stub-resolv.conf
lrwxrwxrwx. 1 systemd-resolve systemd-resolve 11 Nov 24 19:16 /run/systemd/resolve/stub-resolv.conf -> resolv.conf

The contents are the same when you cat all 3
/etc/resolv.conf
/run/systemd/resolve/stub-resolv.conf
/run/systemd/resolve/resolv.conf (all end up pointing here)

**Comment by BrentRose** [comment]
Here is what it looks like after upgrading to 35.20211119.3.0

[root@xxxxxxxx ~]# cat /etc/resolv.conf
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
options edns0 trust-ad
search xxxxx

[root@xxxxxxx ~]# ls -l /etc/resolv.conf
lrwxrwxrwx. 1 root root 39 Dec 14 19:36 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf

[root@xxxxxxxx ~]# ls -l /run/systemd/resolve/stub-resolv.conf
-rw-r--r--. 1 systemd-resolve systemd-resolve 927 Dec 14 19:36 /run/systemd/resolve/stub-resolv.conf

You can see it removed the symlink for reslov.conf in the /run/systemd/resolve/ dir.

[root@xxxxxxxxx ~]# ls -l /run/systemd/resolve/
total 8
srw-rw-rw-. 1 systemd-resolve systemd-resolve   0 Dec 14 19:36 io.systemd.Resolve
drwx------. 2 systemd-resolve systemd-resolve  60 Dec 14 19:36 netif
-rw-r--r--. 1 systemd-resolve systemd-resolve 816 Dec 14 19:36 resolv.conf
-rw-r--r--. 1 systemd-resolve systemd-resolve 927 Dec 14 19:36 stub-resolv.conf

**Comment by dustymabe** [comment]
Hey @BrentRose - As part of the [switch to Fedora Linux 35 content](
https://discussion.fedoraproject.org/t/fedora-coreos-streams-rebasing-to-fedora-linux-35/34429) systemd-resolved is now [fully enabled](https://github.com/coreos/fedora-coreos-tracker/issues/834) in Fedora CoreOS. This was a [Fedora Change](https://fedoraproject.org/wiki/Changes/systemd-resolved) from Fedora 33 but we had some technical issues that caused the change to be delayed in Fedora CoreOS. 


If you want your F34 based FCOS systems to not pick up this change on upgrade you can can write a new configuration file and reboot:

```bash
sudo mkdir -p /etc/systemd/resolved.conf.d
sudo tee /etc/systemd/resolved.conf.d/fedora-coreos-stub-listener.conf <<'EOF'
[Resolve]
DNSStubListener=no
EOF
```

**Comment by dustymabe** [comment]
However, we do encourage you to keep the default configuration (as it's what we test). Perhaps we could understand more what problem this is causing. If you run the `resolvectl` command you can see what nameservers are configured in `systemd-resolved`. Your supplied nameservers should be there and any DNS queries to `127.0.0.53` should return what you would expect.

**Comment by BrentRose** [comment]
Thanks a lot for the suggestions so far.  You are correct that local resolution works correctly.  Where we run into an issue is when running coredns k8s pods that mount /etc/resolv.conf.  I'd certainly prefer keeping the default configuration so maybe I need to look at updating where my coredns pods get their name servers.

**Comment by dustymabe** [comment]
Indeed. Thanks for letting us know how you're using it and where the pain points are.

**Comment by BrentRose** [comment]
@dustymabe FYI

https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues

I haven't tested yet but this looks like any easy fix.
