### ISSUE TITLE
networking: consider the effects of `BOOTIF` kernel argument on `nm-initrd-generator`

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1048]
When booting via PXE syslinux will inject a `BOOTIF` kernel argument to let any interested parties know what interface was used to PXE boot the machine. We were previously unaware that `nm-initrd-generator` would pick up this argument and generate a network configuration file with a MAC address in it. This behavior throws off our [code](https://github.com/coreos/fedora-coreos-config/blob/752562a30e8f8b25ec4a74618ef98d0dc00dfe97/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-teardown-initramfs.sh#L25-L60) that attempts to determine if the user supplied any networking configuration or not.

This means a user may end up with an unexpected Network configuration with a MAC address in the configuration file. Currently they can explicitly tell the propagate network code to not propagate networking configuration (`coreos.no_persist_ip`). There also exists a `rd.bootif=0` flag we can use to tell `nm-initrd-generator` to ignore `BOOTIF`. Maybe we should consider making `rd.bootif=0` the default behavior on FCOS since that's what we were expecting anyway. Though changing the defaults should be considered carefully.

**Comment by dustymabe** [comment]
related BZ that sparked this discussion: https://bugzilla.redhat.com/show_bug.cgi?id=2032717

**Comment by jlebon** [comment]
The goal of our config forwarding special sauce is as a convenience to users so they avoid defining networking configuration multiple times for the initrd and the real root. Given that (1) `BOOTIF=` is AFAICT ignored in the real root, and (2) it's not something users necessarily specified themselves, I think it makes sense to default to ignoring it.

**Comment by cgwalters** [comment]
Really nice work digging into this!

**Comment by dustymabe** [comment]
We discussed this in the [community meeting yeseterday](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/Q2JPX6OUK4IN5KSNATMJCWYGOZEGBTFA/).

I'm going to gather more information and present alternative options here in the ticket for futher discussion down the road.

**Comment by dustymabe** [comment]
After thinking on this some more I think the most straightforward option is to try to update the [code](https://github.com/coreos/fedora-coreos-config/blob/752562a30e8f8b25ec4a74618ef98d0dc00dfe97/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-teardown-initramfs.sh#L25-L60) to properly detect when `BOOTIF` or `rd.bootif` kernel parameters exist and normalize the comparison that is made to determine if the user supplied netwkorking kernel arguments.

This means we won't propagate networking  to the real root if `BOOTIF` exists but no other networking kargs exist. Initramfs networking would still be limited to the `BOOTIF` interface by default. In that case the user can provide `rd.bootif=0` or (if possible) configure PXE to not configure that `BOOTIF` kernel argument. Unfortunately this means there is a case where people may have previously not been required to provide a kernel argument, but they do need to provide it now. Since this is PXE it shouldn't be hard to provide an extra kernel argument.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/E47SUSGIWAUP77HK2SOVDJQRT7HPAH4E/).

```
11:51:58  dustymabe | #agreed We will try to address the BOOTIF issue by updating our "was
                    | networking config provided" logic to handle BOOTIF rather than blanket
                    | applying rd.bootif=0 globally
```

**Comment by travier** [comment]
I think this one went into testing `35.20220313.2.0` & next `35.20220313.1.0`. @dustymabe?

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `35.20220313.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `35.20220313.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `35.20220313.3.1`.
