### ISSUE TITLE
Produce live PXE images

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#105]
Container Linux supports [PXE-booting to a live system](https://coreos.com/os/docs/latest/booting-with-pxe.html), which is often used to run Container Linux both on bare metal and in certain virtualization environments (e.g. VMware).  Users migrating from Container Linux, as well as users who could otherwise benefit from this deployment model, will need a way to netboot a live Fedora CoreOS system.

Container Linux's PXE support has the following properties:
1. initramfs
    1. The initramfs contains a squashfs with the `/usr` filesystem image (i.e., OS code).  There's a dracut module that detects the squashfs and mounts it instead of a permanent disk partition.
    1. The "normal" Container Linux initramfs is compiled into the kernel image, so from the kernel's perspective there are two initramfsen, but from the user's perspective there's only one.
1. Filesystems
    1. The root filesystem (i.e., configuration and user data) is a tmpfs by default, but can be a persistent filesystem if the user creates one with the proper label.
    1. Regardless of the existence of a persistent root, there is no `/boot` filesystem.
1. Lifecycle
    1. Ignition runs iff the PXE server requests it via a kernel command-line option.  If the machine has a persistent root filesystem, this means that Ignition may or may not run on every boot, depending on the configuration of the PXE server.
    1. Automatic updates are disabled in PXE mode, and thus reboot coordination is disabled as well.  To apply updates, users must update the OS image on their PXE server and then reboot nodes into the new image.
    1. The live PXE environment may be used to install Container Linux to disk using `coreos-install`, either manually or via a systemd oneshot service installed via an Ignition config.  A CL system installed to disk in this way is an ordinary system with no further dependence on network booting.

As a starting point, I'd propose continuing essentially the same model for Fedora CoreOS.  The main initramfs will not be compiled into the kernel image, but since PXE loaders (PXELINUX and iPXE) support passing multiple initramfsen to the kernel, it shouldn't be a problem to continue storing the root filesystem in a separate initramfs.  (It may provide confusing UX, however.)  We'll want to provide binaries and docs for PXE-booting on both BIOS and UEFI systems, including UEFI with Secure Boot enabled.

One other point: on Container Linux, PXE-booted systems are assigned the OEM ID `diskless` [sic] for some purposes.  (It's not passed on the kernel command line, but is used by `update_engine_stub` when checking into CoreUpdate.)  PXE booting is orthogonal to the platform ID (e.g., it's possible to netboot a VMware VM) so we should avoid conflating them in Fedora CoreOS.

**Comment by vielmetti** [comment]
This is great, we'd love to have PXE support at @packethost and we have infrastructure to help test this out - just let me know how we can help once you get to the point of wanting to try this.

A relevant KB article for reference is https://support.packet.com/kb/articles/custom-ipxe

**Comment by dustymabe** [comment]
> > The initramfs contains a squashfs with the /usr filesystem image (i.e., OS code)
> 
> If somebody wants to take it over, I started [coreos/coreos-assembler#261](https://github.com/coreos/coreos-assembler/pull/261) exactly for this reason, but there are a few things to polish that I'm not doing at the moment.

yep. i'm also looking at PXE as part of #91

**Comment by vielmetti** [comment]
One note to drop in re PXE, specifically iPXE - we are tracking this issue https://github.com/ipxe/ipxe/pull/90 which yields intermittent failures with iPXE as a result of a bug in OCSP certificate validation. Any eyes on this especially for test and validation cycles would be helpful.

**Comment by bgilbert** [comment]
Discussed OOB with @ajeddeloh and @jlebon.  If we allow both 1) a persistent `/etc` and 2) upgrading the OS by simply PXEing a new image, updates will bypass the rpm-ostree three-way merge of `/etc`.  There are ways to fix that, but since we don't know how many CL users even use PXE with a persistent root, we think we should defer support for persistent `/etc`.

We think live PXE on FCOS should initially:
- Allow persistent data filesystems, including persistent `/var`.
- Not allow persistent root or persistent `/etc`.  The root filesystem will be a r/o squashfs.
- Assume that the PXE config runs Ignition on every boot.  (Strictly speaking that's not a requirement, but there won't be a way to customize `/etc` without it.)
- Refuse to install updates.

**Comment by ajeddeloh** [comment]
> Not allow persistent root or persistent /etc. The root filesystem will be a r/o squashfs.

In the initramfs or when running? I'm assuming it's rw in the initramfs at least.

**Comment by bgilbert** [comment]
zstd compression would make sense for the squashfs.  It can compress well and it decompresses faster than xz.  The Fedora kernel includes support; [squashfs-tools doesn't yet](https://bugzilla.redhat.com/show_bug.cgi?id=1648490).

> In the initramfs or when running? I'm assuming it's rw in the initramfs at least.

squashfs is always r/o, so you're right that this won't work as stated.

**Comment by bgilbert** [comment]
Disabling Zincati in live PXE images: https://github.com/coreos/zincati/issues/63

**Comment by vielmetti** [comment]
attn @dustinmiller1337

**Comment by dustymabe** [comment]
@bgilbert - I know there has been a lot of work here. Where do we stand?

**Comment by vielmetti** [comment]
As  point of interest, we are at Packet also looking at netboot.xyz for an
Arm boot effort.

**Comment by vtolstov** [comment]
For workaround can i get full ostree system create squashfs and boot via dracut?

**Comment by cgwalters** [comment]
> For workaround can i get full ostree system create squashfs and boot via dracut?

We landed `buildextend-live` in coreos-assembler.

**Comment by vtolstov** [comment]
@cgwalters can you provide some draft howto to build live pxe image with ostree?
Two years ago i simply to like i say - install via anaconda ostree system in qemu and create squashfs from it.

**Comment by dustymabe** [comment]
If you can build using COSA (see [README](https://github.com/coreos/coreos-assembler#getting-started---prerequisites)) then `cosa fetch && cosa build ostree && buildextend-live` should give you a `live-kernel` and `live-initramfs` that you can then use to LIVE PXE boot.

**Comment by dustymabe** [comment]
> The latest release shipped live PXE images. There are no docs yet, and #281 should be fixed, but other than that it's done.

Should we close this and let remaining pieces be covered by #281 and maybe #159 (or create a separate docs ticket)

**Comment by bgilbert** [comment]
Yup, sounds good.  Closing.
