### ISSUE TITLE
rawhide: 20211220: authselect fails to set up nsswitch.conf in %posttrans scriptlet

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1051]
**Describe the bug**

`authselect` [now owns `/etc/nsswitch.conf`](https://fedoraproject.org/wiki/Changes/Make_Authselect_Mandatory), but the RPM scriptlets that set it up are failing to run. When trying to do a compose with the newer `glibc` that removes `nsswitch.conf` ownership and `authselect` added to the manifest list we see:

```
Initializing rootfs
Moving /usr to target
Copying toplevel compat symlinks
Recompiling policy
Migrating /usr/etc/passwd to /usr/lib/
Migrating /usr/etc/group to /usr/lib/
error: Finalizing rootfs: Adding altfiles to /etc/nsswitch.conf: No such file or directory (os error 2)
```

But there is no other output to indicate a problem. 

I edited the `%posttrans` in [the spec file](https://src.fedoraproject.org/rpms/authselect/blob/a470fda9c11e7c6d78b9bbf72fe10ee7b78e7f01/f/authselect.spec#_301) and was able to `set -x` and get rid of all the stdout/stderr redirection. With the new RPM build I could see what was actually going on. Here's the output:

```
⠙ Running posttrans scripts... librepo                                                                                                       
authselect-libs.posttrans: + /usr/bin/grep OSTREE_VERSION= /etc/os-release                                                                   
authselect-libs.posttrans: + '[' -f /var/lib/rpm-state/authselect.force ']'                                                                  
authselect-libs.posttrans: + /usr/bin/authselect select sssd with-silent-lastlog --force                                                     
authselect-libs.posttrans: [error] Unable to create backup directory [/var/lib/authselect/backups] [30]: Read-only file system               
authselect-libs.posttrans: [error] Unable to create backup [30]: Read-only file system                                                       
authselect-libs.posttrans: Unable to backup current configuration!                                                                           
authselect-libs.posttrans: + /usr/bin/rm -f /var/lib/rpm-state/authselect.force                                                              
authselect-libs.posttrans: + /usr/bin/authselect apply-changes                                                                               
authselect-libs.posttrans: No existing configuration detected.
```

There are actually two issues here:

- the `grep OSTREE_VERSION` check won't have the desired effect because `mutate-os-release` won't run until after the RPM transaction is complete.
- the ` /usr/bin/authselect select sssd with-silent-lastlog --force` is trying to access `/var/` which is marked readonly for scriptlets.

@jlebon gave me a patch to try to see if we could get around these issues:

```diff
diff --git a/authselect.spec b/authselect.spec
index 52bfdd4..2c4b3bf 100644
--- a/authselect.spec
+++ b/authselect.spec
@@ -309,7 +309,7 @@ fi
 
 # Keep nss-altfiles for all rpm-ostree based systems.
 # See https://github.com/authselect/authselect/issues/48
-if %__grep "OSTREE_VERSION=" /etc/os-release &> /dev/null; then
+if test -e /run/ostree-booted; then
     for PROFILE in `ls %{_datadir}/authselect/default`; do
         %{_bindir}/authselect create-profile $PROFILE --vendor --base-on $PROFILE --symlink-pam --symlink-dconf --symlink=REQUIREMENTS --symlink=README &> /dev/null
 %if %{with_user_nsswitch}
@@ -323,7 +323,11 @@ fi
 # If we are upgrading from pre authselect-1.3.0 or this is a new installation
 # select the default configuration.
 if [ -f %{forcefile} ]; then
-    %{_bindir}/authselect select %{default_profile} --force &> /dev/null
+    if [ -e /run/ostree-booted ]; then
+        %{_bindir}/authselect select --nobackup %{default_profile} --force &> /dev/null
+    else
+        %{_bindir}/authselect select %{default_profile} --force &> /dev/null
+    fi
     %__rm -f %{forcefile}
 fi

```

This still didn't work though, because `authselect` was still trying to access `/var/lib/authselect`. We need to investigate this problem further and work with the upstream towards a proper solution.

**Comment by cgwalters** [comment]
xref https://bugzilla.redhat.com/show_bug.cgi?id=2019052#c1

This doesn't apply to just FCOS but other editions too, and let's be sure we take this discussion to a place where the authselect developers will see it.  I suggest using the above bug.

**Comment by dustymabe** [comment]
Thanks @cgwalters for looking into this with upstream.

**Comment by cgwalters** [comment]
https://github.com/authselect/authselect/pull/289

**Comment by cgwalters** [comment]
Actually let's centralize discussion of this to https://bugzilla.redhat.com/show_bug.cgi?id=2034360 because it affects all rpm-ostree-using things, not just FCOS.

**Comment by dustymabe** [comment]
Should be fixed by https://github.com/coreos/fedora-coreos-config/pull/1492
