### ISSUE TITLE
RFE: generate chrony configuration on AzureStack

### ISSUE THREAD

**Issue by freedge** [coreos/fedora-coreos-tracker#1053]
**Describe the enhancement**
AzureStack could use /dev/ptp_hyperv hardware clock as on Azure (https://github.com/coreos/fedora-coreos-tracker/issues/1031)

**System details**
 - AzureStack (update 2108)
 - Fedora CoreOS next (35.20211215.1.0)

**Additional information**

**Comment by freedge** [comment]
looking good on fedora/x86_64/coreos/next 35.20220103.1.0

```
$ chronyc tracking
Reference ID    : 50484330 (PHC0)
Stratum         : 1
Ref time (UTC)  : Thu Jan 06 15:47:07 2022
```

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `35.20220103.3.0`.
