### ISSUE TITLE
Large and growing PXE RAM requirement

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#1055]
We document [here](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_installing_from_pxe) and [here](https://docs.fedoraproject.org/en-US/fedora-coreos/live-booting-ipxe/#_prerequisite) that PXE booting requires 2 GiB RAM for `coreos.live.rootfs_url` and 3 GiB for bootloader-fetched initrd+rootfs.  In recent tests, 2 GiB is still sufficient for `rootfs_url` but 3 GiB is no longer sufficient for bootloader-fetched rootfs.  (I'll call the latter case "concatenated rootfs", since that's how it appears to the kernel, whether the user manually concatenates the files or whether they're specified as separate initrds and concatenated by the bootloader.)

One issue is that the root filesystem in the initramfs is a tmpfs, and tmpfs instances are limited to 50% of RAM by default.  I don't think that's the only problem, though, since in the concatenated case, 1500 MiB should be sufficient even for the two memory-resident copies of the initramfs + rootfs.  It would be useful to fully track down the cause.

Some options for improving things:

1. Increase the tmpfs quota.  In the `rootfs_url` case, it might help to `mount -o remount,size=90% /` before extracting.  But in the concatenated case, we need to increase the quota before the kernel unpacks the initrd.  `rootflags=` _looks_ useful for this, but isn't; the argument [is ignored](https://github.com/torvalds/linux/blob/7a29b11da9651ef6a970e2f6bfd276f053aeb06a/fs/namespace.c#L4282) when mounting the tmpfs.  ([This patch](https://lore.kernel.org/all/20210630014744.88735-1-chenweilong@huawei.com/) should fix it, but apparently hasn't gotten any traction.)

   An alternative is to use `rootfstype=ramfs` to switch the rootfs to the old, simpler ramfs, which doesn't support quotas and which can successfully unpack in 2500 MiB RAM, but I'm not sure what side effects that might have.  If that's viable, we could recommend that karg in the concatenated case.

1. Discourage the concatenated case.  It takes nearly twice as much RAM during initialization, it's slower (because the firmware's network stack fetches the rootfs blob), and it seems to be less commonly used.  If we pursue this, we should probably [allowlist](https://github.com/coreos/fedora-coreos-config/blob/0eda5eb17adeff88a4ee60c3884c50c0d6a96a10/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-live/coreos-livepxe-rootfs.sh#L26) TFTP for `rootfs_url` so users don't need an HTTP server.

1. Error out if concatenated initrd unpack fails.  We report obscure failures in this case because we see a partially unpacked initramfs, but we could actually detect this case: `/root.squashfs` will exist, but some of the later files in the rootfs cpio won't.  The last member is currently an osmet file, but we could add a flag file or move `/etc/coreos-live-rootfs` to the end of the archive.

**Comment by bgilbert** [comment]
We discussed this at [today's meeting](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2022-01-12-16.31.log.html).

```
17:38:05 <bgilbert> #agreed We will update our docs for the apparent new RAM requirements
                    for PXE appended rootfs, and we'll improve OOM reporting for the appended
                    case.  We'll also pursue supporting TFTP in the rootfs_url karg, and have
                    the docs encourage people to prefer that karg when possible.
```

**Comment by bgilbert** [comment]
Docs updates in https://github.com/coreos/fedora-coreos-docs/pull/355.

**Comment by bgilbert** [comment]
https://github.com/coreos/fedora-coreos-config/pull/1526 adds TFTP support to `coreos.live.rootfs_url`.

**Comment by bgilbert** [comment]
https://github.com/coreos/fedora-coreos-config/pull/1684 adds clearer error reporting if initrd unpacking runs out of memory.  That should be the last implementation piece for https://github.com/coreos/fedora-coreos-tracker/issues/1055#issuecomment-1011785538.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `35.20220424.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `35.20220424.3.0`.
