### ISSUE TITLE
AuthorizedKeysCommand path is not absolute

### ISSUE THREAD

**Issue by hunter86bg** [coreos/fedora-coreos-tracker#1056]
**Describe the bug**
When /etc/ssh/sshd_config.d/10-disable-ssh-key-dir.conf" has "AuthorizedKeysCommand none" ssh-ing to the machine is not possible and an error is generated in the logs:
```
error: AuthorizedKeysCommand path is not absolute
```

Client is rejected via:
```console
$ ssh core@okd4-control-plane-1 'sudo -i -u root journalctl -xe '
core@okd4-control-plane-1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

**Reproduction steps**
1. Bootstrap the system with master.ign and image fedora-coreos-35.20211203.3.0-metal.x86_64.raw.xz
2. After the reboot try to ssh as user "core" and using the specified ssh key

**Expected behavior**
Either ssh-ing as core user to be possible or if the behaviour is intentional -> no errors to be reported in journald for the sshd.service

**Actual behavior**
No ssh session is possible and error is detected in the logs.

**System details**
 - QEMU
 - fedora-coreos-35.20211203.3.0-metal.x86_64.raw.xz

**Ignition config**
Generated via 
```openshift-install create ignition-configs ```:

```json
{
  "ignition": {
    "config": {
      "merge": [
        {
          "source": "https://api-int.okd4.localdomain:22623/config/master"
        }
      ]
    },
    "security": {
      "tls": {
        "certificateAuthorities": [
          {
            "source": "data:text/plain;charset=utf-8;base64,<data_removed>"
          }
        ]
      }
    },
    "version": "3.2.0"
  }
}
```

**Comment by hunter86bg** [comment]
Based on the comment -> the behaviour is to prevent ssh-ing, so I guess a more robust would work:
```
AuthorizedKeysCommand /usr/bin/false
```

**Comment by lucab** [comment]
Thanks for the report.
There is no `/etc/ssh/sshd_config.d/10-disable-ssh-key-dir.conf` in the base FCOS image.
The syntax for `AuthorizedKeysCommand` is documented in the `sshd_config(5)` manpage: https://linux.die.net/man/5/sshd_config

**Comment by lucab** [comment]
On the OKD side, this is https://github.com/openshift/machine-config-operator/pull/2355.
