### ISSUE TITLE
rawhide: 20211230: failing due to to unsupported lua script from authselect-libs

### ISSUE THREAD

**Issue by saqibali-2k** [coreos/fedora-coreos-tracker#1057]
Build: [3497](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/blue/organizations/jenkins/fedora-coreos%2Ffedora-coreos-fedora-coreos-pipeline/detail/fedora-coreos-fedora-coreos-pipeline/3497/pipeline) 

Error Message: `error: Package 'authselect-libs' has (currently) unsupported <lua> script in '%prein'`

Package: `authselect-libs-1.3.0-5.fc36.x86_64`

**Comment by dustymabe** [comment]
`%pre` scripts were converted to `lua` in https://src.fedoraproject.org/rpms/authselect/c/00f6a084f99e2a9ee9ceaaad3d4896e4bfc591dd?branch=rawhide

Let's pin for now because we really need to get a rawhide build: https://github.com/coreos/fedora-coreos-config/pull/1396

**Comment by cgwalters** [comment]
https://github.com/coreos/rpm-ostree/pull/3308

**Comment by dustymabe** [comment]
Thanks @cgwalters for looking into this upstream!

**Comment by dustymabe** [comment]
Fixed by https://github.com/coreos/fedora-coreos-config/pull/1492
