### ISSUE TITLE
New Package Request: nano (and explicit choice for default editor)

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1058]
The main goal here is to match the default with the one from Fedora as of Fedora 33: https://fedoraproject.org/wiki/Changes/UseNanoByDefault

Benefits (from the linked Change request):
> Users are exposed to the default editor when they use commands that call it. The main example here is something like git commit.
>
> Fedora does not currently have a default terminal text editor, because the $EDITOR environment variable is unset by default. But a common scenario where users wind up in a terminal text editor is when using 'git commit'. By default, git picks vi. You need to spend time learning how to use it, for even basic editing tasks. This increases the barrier to entry for those who are switching to Fedora and don't know how to use vi. It also makes things hard for those who don't particularly want to learn how to use vi. (These arguments would apply just as well if git picked Vim. vi is like hard mode for Vim, with fewer features, missing syntax highlighting, and no indication of what mode you are in. Even Vim users may feel lost and bewildered when using vi.)
>
> In contrast, Nano offers the kind of graphical text editing experience that people are used to, and therefore doesn't require specialist knowledge to use. It is already installed across most Fedora Editions and Spins. This proposal will make Nano the default editor, while continuing to install vim-minimal (which provides vi, but not Vim). People will still be able to call vi if they want to edit a file. It will also obviously be possible to change the default editor to vi or Vim, for those who want it.
>
> Why make Nano default and vi optional, rather than the other way round? Because Nano is the option that everyone can use.

----

Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

None

2. What is the size of the package and its dependencies?

From `dnf info`:

- nano: 709k
- nano-default-editor: 11k

3. What problem are you trying to solve with this package? Or what functionality does the package provide?

User friendly default editor

4. Can the software provided by the package be run from a container?  Explain why or why not.

No, the default editor must be pre-installed to be able to edit files outside of a container and before pulling containers.

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

Yes

6. Can the tool(s) provided by the package be helpful in debugging networking issues?

No

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

Yes

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

No service

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)

No

10. Does the software provided by the package have a history of CVEs?

Not relevant

**Comment by travier** [comment]
Tentative PR in https://github.com/coreos/fedora-coreos-config/pull/1394

**Comment by travier** [comment]
https://docs.fedoraproject.org/en-US/fedora-coreos/os-extensions/ > This doc package will also need an update

**Comment by jlebon** [comment]
Not strongly against. I think matching other Fedora editions is a good argument in favour, but also think it's OK to consciously deviate when it makes sense for FCOS (like keeping the base package set minimal).

**Comment by jlebon** [comment]
This was discussed in [today's community meeting](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2022-01-05-16.30.txt):

```
12:27:25 < jlebon> #agreed We will add nano to FCOS and make it the default editor.
```

**Comment by travier** [comment]
> Did we just miss this one because whoever was driving the change only did it in comps and forgot about FCOS's manifest?

I think we missed it as we were not tracking Fedora Changes as closely for F33 as we do now.

**Comment by dustymabe** [comment]
I forget if we discussed this or not. Do we need to communicate the change to users?

**Comment by travier** [comment]
We're not removing vi so this is not critical but I guess we could send a small heads up mail on coreos-status.

**Comment by travier** [comment]
Draft mail: https://hackmd.io/o5ZOvLVBTBKKEqOqKjMYXA. Feel free to edit. It might not be "big" enough to send to coreos-status. It will be included in the "release-notes" as it has a tracking issue.

**Comment by dustymabe** [comment]
Made some small edits. cc @jlebon @bgilbert

**Comment by travier** [comment]
LGTM

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `35.20220131.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into next stream release `35.20220131.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `35.20220131.3.0`.
