### ISSUE TITLE
rawhide: 20220103: selinux denial causing systemd-network-generator service failure

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1059]
Our tests that test networking configuration via kernel arguments are failing because of SELinux denials causing the systemd-network-generator service to fail in our `rawhide` stream.

```
[2022-01-04T16:33:48.933Z] --- FAIL: ext.config.networking.prefer-ignition-networking (555.33s)
[2022-01-04T16:33:48.933Z]         harness.go:1249: Cluster failed starting machines: machine "5bffd725-9683-47c4-b64c-1fb8eb91c341" failed basic checks: some systemd units failed:
[2022-01-04T16:33:48.933Z] systemd-network-generator.service


[2022-01-04T16:35:34.817Z] --- FAIL: ext.config.networking.force-persist-ip (388.76s)
[2022-01-04T16:35:34.817Z]         harness.go:1249: Cluster failed starting machines: machine "b5b0354e-e771-495c-aaab-36cc98e47c6e" failed basic checks: some systemd units failed:
[2022-01-04T16:35:34.817Z] systemd-network-generator.service
``` 

I opened [BZ#2037047](https://bugzilla.redhat.com/show_bug.cgi?id=2037047) against selinux-policy to track a fix for getting the systemd-network-generator.service working again.

**Comment by dustymabe** [comment]
We have a few options here that I see for a short term workaround:

- make the tests use `enforcing=0` temporarily.
- snooze these tests for a while in rawhide
- determine/decide that we absolutely don't need anything from `systemd-network-generator` and disable it.

**Comment by jlebon** [comment]
> determine/decide that we absolutely don't need anything from `systemd-network-generator` and disable it.

+1. I think for our own sanity we shouldn't have anything other than `nm-initrd-generator` generating things from network kargs.

**Comment by dustymabe** [comment]
> > determine/decide that we absolutely don't need anything from `systemd-network-generator` and disable it.
> 
> +1. I think for our own sanity we shouldn't have anything other than `nm-initrd-generator` generating things from network kargs.

I would mostly agree but there's some overlap where the `systemd-network-generator` does some things that are used even if we use NM. For example: https://github.com/systemd/systemd/pull/21766#issuecomment-994051719

**Comment by dustymabe** [comment]
proposal to go with snoozing for now: https://github.com/coreos/fedora-coreos-config/pull/1400

**Comment by dustymabe** [comment]
`bump-lockfile` started failing because of this so we are now hitting it on the `systemd 249.7-2.fc35 -> 249.9-1.fc35` in Fedora 35. Let's pin systemd in `testing`/`next` for now and get more involved in the BZ to see if we can push a fix.

**Comment by dustymabe** [comment]
I'm going to unfreeze systemd and workaround this for now: https://github.com/coreos/fedora-coreos-config/pull/1604

I'll continue to monitor [BZ#2037047](https://bugzilla.redhat.com/show_bug.cgi?id=2037047) for any updates there.

**Comment by dustymabe** [comment]
A fix has [been built for Fedora 36 for this](https://bodhi.fedoraproject.org/updates/FEDORA-2022-690770081a). I'm not sure the fix is going to go to F35, but we don't necesarily need that. Let's fast-track the package in our `next-devel` stream (one PR against `next-devel`) and split out our [masking](https://github.com/coreos/fedora-coreos-config/commit/f31dcec) to make it only apply to F35 (another PR to against the `testing-devel` branch). See https://github.com/coreos/fedora-coreos-config/pull/1660 for an example of how to do this.

**Comment by dustymabe** [comment]
Closing this out since it's fixed in F36 (`next-devel`) and Rawhide and will folow into our other streams.
