### ISSUE TITLE
GCP ops-agent support

### ISSUE THREAD

**Issue by remoe** [coreos/fedora-coreos-tracker#1073]
GCP supports the new ops-agent ( https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent ) on some Linux OS. Currently it's not possible to install it on FCOS. I've created a first experiment to show what's currently possible with current implementation of ops-agent:

https://github.com/GoogleCloudPlatform/ops-agent/issues/ 334

Does anyone interested in this? Does anyone can help to solve this runtime errors on the issue above? I'm not familiar with FCOS RPM build process. I've used Fedora OS to build a package.

**Comment by lucab** [comment]
Thanks for the report.
From the docs, this seems to be purely a metrics exporter and log forwarder. If it gets packaged in Fedora, then it will be possible to overlay-install on a FCOS node.
But an alternative route is to run this in a (privileged) container with the relevant permissions and bind-mounts.
For a conceptually similar monitoring-agent containerized deployment, see https://github.com/prometheus/node_exporter#docker.
Agent logic may or may not need some enhancements to work from within a container, but it's a path worth exploring as it allow decoupling agent lifecycle from OS updates/rollbacks.

**Comment by remoe** [comment]
Interesting, thanks for your feedback. My main concern is to allow the metrics export through the google API to use their UI. So this should be possible with Prometheus node exporter? When yes, I don't know the base requirements to run this:

- google service account configuration on the OS (JSON file?)
- need to run any additional "special" google service on systemd ? 

I like the Prometheus service, but it need to use a DB and it doesn't fit in a system with small resources (CPU/RAM)? Is it possible to forward metrics directly to google API without complicated caching system between? Or is this conceptional not possible or wrong?

When I found the path I can try and contribute here.

Thanks!

**Comment by lucab** [comment]
No sorry, you misread my answer.

The GCP monitoring agent is one thing, and I don't think we have any prior knowledge about it. It may or may not work in its current form from within a container, I don't know. Or somebody may be looking at packaging it in Fedora.

The Prometheus node-exporter is a completely different thing and unrelated to GCP. I'm absolutely not claiming it is a features-compatible replacement. I'm just pointing to a monitoring agent (that I know) and that runs in a container, with some caveats.

**Comment by remoe** [comment]
Ok. I found one of package one need to use is: google-compute-engine-guest-configs . But it tries to install the "65-gce-disk-naming.rules" file on a read-only file system:  /lib/udev/rules.d/65-gce-disk-naming.rules

**Comment by bgilbert** [comment]
We ship that rules file directly in FCOS, so installing it from a package produces a file conflict.

**Comment by remoe** [comment]
It doesn't help much to focus ops-agent. Because it's only a configuration tool for other services. First I try to find a way to run https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector on FCOS with GCP.
