### ISSUE TITLE
GCP OpenTelemetry Metrics with FCOS sample

### ISSUE THREAD

**Issue by remoe** [coreos/fedora-coreos-tracker#1074]
Here is a sample to integrate the OpenTelemetry Collector from Google ( https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector ) in Fedora CoreOS :

https://github.com/remoe/gcp-fcos-agent

For a first preview it has a working binary which one can integrate in FCOS. It is described in the Readme how one can integrate it. It should be possible to integrate fluentbit in FCOS to support the logging as well.

![image](https://user-images.githubusercontent.com/804941/150678148-8ec12a94-6fa6-4e4f-a540-18d71949a277.png)

![image](https://user-images.githubusercontent.com/804941/150678082-46c227e8-a37c-4790-ac45-c8d464fe79e4.png)

I've tested it on a GCP e2-small instance with Terraform:

```hcl
resource "google_compute_instance" "main" {
...
  metadata = {
    ...
    google-logging-enabled    = "true"
    google-monitoring-enabled = "true"
    ...
  }

  service_account {
    email  = "[your email]"
    scopes = ["logging-write","monitoring","service-management"]
  }
...
}

```

**Comment by lucab** [comment]
Thanks for the report. I'm going to close this ticket as it isn't a bug report. We do have a forum at https://discussion.fedoraproject.org/tag/coreos which is more relevant for posting or looking for deployment insights.

**Comment by remoe** [comment]
Sorry.
done: https://discussion.fedoraproject.org/t/gcp-opentelemetry-metrics-with-fcos-sample/36291
