### ISSUE TITLE
Import request: https://github.com/cgwalters/cap-std-ext

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1082]
I'd like to import https://github.com/cgwalters/cap-std-ext into the coreos/ GH organization, as we did with https://github.com/coreos/openat-ext/ (this project is the successor to that one).

**Comment by dustymabe** [comment]
I don't have an opinion here on this particular repo addition.

Only thing is I'd kind of like to keep our toplevel namespace cleaner. Wish we could subnamespace other smaller projects, but I don't know if that is possible.

**Comment by travier** [comment]
+1 to import the repo.

> Only thing is I'd kind of like to keep our toplevel namespace cleaner. Wish we could subnamespace other smaller projects, but I don't know if that is possible.

There is only one level in organizations on GitHub AFAIK (unlike GitLab). We could create a coreos-rs org and move Rust crates there. But what would be the benefit compared to having everything in a single place?

**Comment by cgwalters** [comment]
Who has the permissions to do this?  @ashcrow ?

**Comment by bgilbert** [comment]
@cgwalters You can transfer the repository yourself, and then an org admin will need to fix the permissions.

**Comment by travier** [comment]
> Who has the permissions to do this? @ashcrow ?
> You can transfer the repository yourself, and then an org admin will need to fix the permissions.

@ashcrow or @miabbott should be able to fix the permissions now.

**Comment by cgwalters** [comment]
LGTM, thank you!
