### ISSUE TITLE
New Package Request: qemu-user-static

### ISSUE THREAD

**Issue by jarrellmark** [coreos/fedora-coreos-tracker#1088]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

qemu

2. What is the size of the package and its dependencies?

Not sure

3. What problem are you trying to solve with this package? Or what functionality does the package provide?

This package allows running x86 programs on aarch64 for docker and podman. The use case is in podman's vm for Mac: https://github.com/containers/podman/discussions/12899#discussioncomment-2068854

4. Can the software provided by the package be run from a container?  Explain why or why not.

No. This software allows for running containers.

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

Not likely.

6. Can the tool(s) provided by the package be helpful in debugging networking issues?

Not likely.

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

Not sure

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

This is just binaries.

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)

Not sure

10. Does the software provided by the package have a history of CVEs?

Not sure. CVEs for QEMU itself are here: https://www.cvedetails.com/vulnerability-list/vendor_id-7506/Qemu.html

**Comment by bgilbert** [comment]
```
Added:
  ipxe-roms-qemu-20200823-7.git4bd064de.fc35.noarch
  libxcrypt-compat-4.4.27-2.fc35.x86_64
  mpdecimal-2.5.1-2.fc35.x86_64
  python-pip-wheel-21.2.3-4.fc35.noarch
  python-setuptools-wheel-57.4.0-1.fc35.noarch
  python-unversioned-command-3.10.2-1.fc35.noarch
  python3-3.10.2-1.fc35.x86_64
  python3-libs-3.10.2-1.fc35.x86_64
  qemu-common-2:6.1.0-10.fc35.x86_64
  qemu-user-static-2:6.1.0-10.fc35.x86_64
```

```
rpm -q --qf '%{SIZE} %{NAME}\n' $packages
2822621 ipxe-roms-qemu
202688 libxcrypt-compat
246955 mpdecimal
1220638 python-pip-wheel
596568 python-setuptools-wheel
23 python-unversioned-command
33090 python3
33109642 python3-libs
1732305 qemu-common
153871479 qemu-user-static
```

So it's 184 MiB in total, and brings in Python.  I like the idea in principle, but oof.

The size could possibly be reduced some; `qemu-user-static` contains emulators for 35 different architectures.

**Comment by jarrellmark** [comment]
Thanks for the info @bgilbert !

2 main use cases I can think of (just personal observations):

- Running x86 docker images on aarch64 machines (Mac M1 for example)
- Running aarch64 images on x86 machines (for images that will run in cloud aarch64 servers, but the developer has an x86 machine).

So maybe x86 and aarch64 could be the only included architectures.

Not sure about the python dependency, that's pretty heavy.

**Comment by dghubble** [comment]
> Is it possible to layer the package onto the base OS as a day 2 operation? Explain why or why not.

Yes, I used this one a bunch before arm64 images. Worked well.

```
rpm-ostree install qemu-user-static --reboot
```

**Comment by cgwalters** [comment]
Worth noting https://github.com/coreos/enhancements/blob/main/os/coreos-layering.md is going to be a thing too.

**Comment by travier** [comment]
Like @bgilbert, I like the idea but this needs work to split dependencies, architectures, etc. Layering should be fine until that happens.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/E47SUSGIWAUP77HK2SOVDJQRT7HPAH4E/).


```
12:04:05  dustymabe | #agreed There are obviously packaging enhancements that could be made
                    | here (removal of python dep, reduction of shipped emulators by
                    | splitting out into subpackages) that are worth making even if we don't
                    | include qemu-user-static by default. Once those packaging improvements
                    | land we'd need to further consider it for inclusion in FCOS. It's a 
                    | good idea, but maybe not necessary for the base layer.
```

**Comment by rhatdan** [comment]
@dustymabe Has someone opened a bugzilla or issue with the qemu-user-static package to break apart the dependencies?

**Comment by dustymabe** [comment]
@rhatdan I'm not aware of any action that has been taken there.

**Comment by rhatdan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2061584

**Comment by dustymabe** [comment]
Looks like builds are available now. I just tried this on a `testing-devel` instance:

```
sudo rpm-ostree install ./qemu-user-static-aarch64-6.2.0-11.fc36.x86_64.rpm
...
...
Added:
  qemu-user-static-aarch64-2:6.2.0-11.fc36.x86_64
reboot

```

```
rpm -ql qemu-user-static-aarch64 | xargs ls -lhd           
-rwxr-xr-x.   2 root root 5.9M Jan  1  1970 /usr/bin/qemu-aarch64-static
-rwxr-xr-x.   2 root root 5.9M Jan  1  1970 /usr/bin/qemu-aarch64_be-static
drwxr-xr-x. 257 root root 8.0K Jan  1  1970 /usr/lib/.build-id
drwxr-xr-x.   2 root root 4.0K Jan  1  1970 /usr/lib/.build-id/36
lrwxrwxrwx.   2 root root   39 Jun  8 20:32 /usr/lib/.build-id/36/d4958b1bb540486dfc59fbd4b52a562092e7ad -> ../../../../usr/bin/qemu-aarch64-static
drwxr-xr-x.   2 root root 4.0K Jan  1  1970 /usr/lib/.build-id/59
lrwxrwxrwx.   2 root root   42 Jun  8 20:32 /usr/lib/.build-id/59/3e9b251642bb79251444f8d2dca62248acb143 -> ../../../../usr/bin/qemu-aarch64_be-static
-rw-r--r--.   2 root root  200 Jan  1  1970 /usr/lib/binfmt.d/qemu-aarch64-static.conf
-rw-r--r--.   2 root root  206 Jan  1  1970 /usr/lib/binfmt.d/qemu-aarch64_be-static.conf
-rw-r--r--.   2 root root 649K Jan  1  1970 /usr/share/systemtap/tapset/qemu-aarch64.stp
-rw-r--r--.   2 root root  59K Jan  1  1970 /usr/share/systemtap/tapset/qemu-aarch64_be-static.stp
```

Not sure what the difference between `qemu-aarch64_be-static` and `qemu-aarch64-static` is?

It seems to work, though:

```
[core@cosa-devsh ~]$ podman run --rm -t arm64v8/fedora uname -m
✔ docker.io/arm64v8/fedora:latest
Trying to pull docker.io/arm64v8/fedora:latest...
Getting image source signatures
Copying blob 9d693e29d403 done  
Copying config 8847e9bf6d done  
Writing manifest to image destination
Storing signatures
aarch64
```

**Comment by cgwalters** [comment]
> reboot

(Tangentially related but remember `rpm-ostree install -A` is a thing, and probably what you want for quick testing)

**Comment by dustymabe** [comment]
> Not sure what the difference between `qemu-aarch64_be-static` and `qemu-aarch64-static` is?

I think the `_be` is for big endian.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/SGMUGRGYQ2E2IZSEMHYEQHKHRUAQF23R/).

```
13:08:29    dustymabe | #agreed For now we will include the qemu-user-static-x86
                      | package on non x86_64 FCOS images to allow "out of the box"
                      | access to the large inventory of containers only built for 
                      | x86_64. We may revisit this in the future once CoreOS  
                      | layering is more mature or if there comes a time when
                      | containers for other architectures are as ubiquitous.
```

**Comment by rhatdan** [comment]
I would have gone the other way also (M1) qemu-user-static-arm for x86 to be able to use images created by Mac X1 machines.

**Comment by bgilbert** [comment]
> I would have gone the other way also (M1) qemu-user-static-arm for x86 to be able to use images created by Mac X1 machines.

I'd support that also.

**Comment by travier** [comment]
Agree with the above. It makes sense to have support for both x86 on aarch64 for each architecture that we support.

**Comment by dustymabe** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2022-0142d562ca was just submitted for bodhi stable. I think the sentiment in the last 3 comment here is fair, but can be separated from the decision as it stands in https://github.com/coreos/fedora-coreos-tracker/issues/1088#issuecomment-1156816968. In order to move forward with and not delay any further the implementation of that decision could we open a separate issue for "installing `qemu-user-static-aarch64` on x86_64"? 

I'll open a PR tomorrow to add `qemu-user-static-x86` to `aarch64` and `s390x`.

**Comment by bgilbert** [comment]
@dustymabe If you're planning to open the PR tomorrow, does it make a difference?  The PR should be small and we don't have a scheduled release for two weeks.

**Comment by dustymabe** [comment]
It doesn't make a huge difference. I mostly wanted to keep the conversation separate and avoid rehashing the previous decision from last week. Adding to it is fair game.

**Comment by travier** [comment]
Do we want to discus that again in a meeting or should I remove the label?

**Comment by travier** [comment]
We've briefly discussed this topic in [today's FCOS community meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/B5CEEKKMBFCHCOWR4X6QSUXOYOT3FVEM/) and we agreed on shipping the x86_64 emulator on aarch64 and the aarch64 on x86_64.

**Comment by dustymabe** [comment]
Though it seems like we have 3 people here in ticket, +1 (myself), + jlebon from the meeting casually mentioning agreement. I'm happy with moving ahead with this if no one speaks up to object:

- on x86_64
    - install `qemu-user-static-aarch64`
- on non x86_64 (aarch64, s390x)
    - install `qemu-user-static-x86`

**Comment by bgilbert** [comment]
Are we assuming that s390x/ppc64le won't want to run aarch64 containers?

**Comment by dustymabe** [comment]
> Are we assuming that s390x/ppc64le won't want to run aarch64 containers?

... This open question implies to me we need more discussion. 

Let's just stick with what was [decided last week](https://github.com/coreos/fedora-coreos-tracker/issues/1088#issuecomment-1156816968) in order to get that content shipped and we'll hammer out the details of non-x86 emulators in next week's meeting: https://github.com/coreos/fedora-coreos-tracker/issues/1237

**Comment by travier** [comment]
My bad, let's do that at the next meeting.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `36.20220703.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220703.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `36.20220703.3.1`.
