### ISSUE TITLE
Public communication to socialize plans for collecting metrics

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#109]
From https://github.com/coreos/fedora-coreos-tracker/issues/86#issuecomment-446250781 we have identified the need to be very vocal about any plans to collect metrics. Let's develop a communication (most likely fedora magazine / CoreOS blog post) so that we can socialize the issue further.

**Comment by dustymabe** [comment]
This would be useful as a possible collaboration with @mattdm .

**Comment by bgilbert** [comment]
I don't think we have any plans on the horizon to collect additional metrics.  Should we close this out?

**Comment by dustymabe** [comment]
Agreed.
