### ISSUE TITLE
Kernel panic error - Solved

### ISSUE THREAD

**Issue by indacofilippo** [coreos/fedora-coreos-tracker#1091]
Hi,
I have a problem with installing a lab okd 4.7.

I'm following the guide https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee by Craig Robinson, but when I get to the "Starting the bootstrap node" I get a "kernel panic" error after entering the parameters indicated in the guide.
I am trying to install OKD 4.7 with Fedora CoreOS 34.20210529.3.0, but I also tried to use Fedora CoreOS 35.20220116.3.0 and got the same error.

The error "Cannot open root device (null)" and "please append a correct root" with no disks available "suggests a Fedora CoreOS problem with ESXi 7.03.

Do you have any suggestions? Has something similar happened to you?

Thanks in advance for your help.

![OKD-BOOTSTRAP-01](https://user-images.githubusercontent.com/7949159/152695855-83829bb4-aa41-4baa-be32-4c346ca40225.png)

![OKD-BOOTSTRAP-02](https://user-images.githubusercontent.com/7949159/152695854-3ec5c131-30e7-4b3a-9378-894af0d25614.png)

![OKD-BOOTSTRAP-03](https://user-images.githubusercontent.com/7949159/152695856-8a5f3663-92c6-4165-89ff-6bfd303bfe70.png)
.

**Comment by bgilbert** [comment]
Thanks for the clear screenshots.  The problem is that you're deleting the `initrd` line when adding the additional kernel arguments.  Without an initrd, the kernel tries to mount a root filesystem directly, fails, and gives up.

**Comment by indacofilippo** [comment]
Thank's @bgilbert.

This problem has been solved. I recreated the VM by lowering the hardware compatibility to version 6.5 and using Fedora CoreOS 34.20210529.3.0
