### ISSUE TITLE
Container Plumbing Days CFP 2022

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1093]
We should probably summit a talk about FCOS to CPD 2022.

Feel free to suggest a theme, topic, etc. we should talk about, even if you don't intend to work on it or present it.

From https://containerplumbing.org/speakers:
> **Deadlines**
> Please submit your proposal by February 15, 2022, at 23:59 UTC (7pm Eastern).
>
> We will chose which proposals get selected by February 23rd and inform all speakers.
>
> The conference will take place March 22 and 23, from 1400 UTC to 1900 UTC each day.
> 
> **Talk Formats**
> We’ll be hosting two kinds of sessions:
> 
> Presentation Sessions (25m): this will be your normal slides/demo talking session, with 15 minutes of presentation and demo, and 10 minutes of questions from the audience. Live demos, or even recorded video demos, are highly encouraged. Slides are not required if you have enough demo time or other visual interest.
> 
> Discussion Session (50m): these sessions will be for open discussion of topics of general technical interest, like improvements to Linux namespaces, new features for the CRI, etc. They will be 50 minutes long. As part of this session proposal, you will need to name at least three people who will be participating in the discussion. Discussions will also be open to audience members.
> 
> All talks should be presented live if possible. Container Plumbing is a “summit” type event, where the discussions are more important than the slides.

**Comment by travier** [comment]
Maybe we could do a "What's new and what's next in Fedora CoreOS for container users".

**Comment by miabbott** [comment]
Demo'ing the CoreOS Layering stuff would be great to see

**Comment by travier** [comment]
The CfP is now closed thus closing this one.

**Comment by jasonbrooks** [comment]
Looks like the deadline was extended to Feb 21. The layering stuff sounds like a good topic to me.

**Comment by travier** [comment]
CC @cgwalters @jmarrero

**Comment by jasonbrooks** [comment]
Colin submitted a talk on Fri

**Comment by bgilbert** [comment]
The CFP is now closed.  Thanks all!
