### ISSUE TITLE
New Package Request: NetworkManager-config-server

### ISSUE THREAD

**Issue by qinqon** [coreos/fedora-coreos-tracker#1094]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

None

2. What is the size of the package and its dependencies?

463 B

3. What problem are you trying to solve with this package? Or what functionality does the package provide?

Without this NetworkManager will automatically create profile for newly discovered interface
which has approved to be causing many problem in projects like RHV.

We are facing this problem also at [kubernetes-nmstate](https://bugzilla.redhat.com/show_bug.cgi?id=2048988).

4. Can the software provided by the package be run from a container?  Explain why or why not.

It cannot run as a container, since it's a configuration file for NetworkManager.

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

No

6. Can the tool(s) provided by the package be helpful in debugging networking issues?

No

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

The configuration providerd by the package has to run at NetworkManager form day one since it will affect the already created network interfaces.

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

No

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)

No

10. Does the software provided by the package have a history of CVEs?

No

**Comment by qinqon** [comment]
Have created a PR for the change at openshift/os https://github.com/openshift/os/pull/705

**Comment by travier** [comment]
If this is "just" a configuration file, it should probably be deployed via the MCO

**Comment by qinqon** [comment]
> If this is "just" a configuration file, it should probably be deployed via the MCO
> 
> Edit: Colin said the same thing in [openshift/os#705 (comment)](https://github.com/openshift/os/pull/705#issuecomment-1032714634)

Having to maintain it at MCO is not a problem ? If installed from the RPM it will get updated if there is any updates I suppose.

**Comment by travier** [comment]
Having it part of the base image means that this applies to everyone, not only to users of nmstate. If this only applies to nmstate users then I think that this should either be in the nmstate documentation or in a MachineConfig deployed by the nmstate operator.

**Comment by qinqon** [comment]
> Having it part of the base image means that this applies to everyone, not only to users of nmstate. If this only applies to nmstate users then I think that this should either be in the nmstate documentation or in a MachineConfig deployed by the nmstate operator.

Cool we will try to make it part of kubernetes-nmstate operator MachineConfig, thanks!
