### ISSUE TITLE
F36: CHANGE: golang 1.18

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#1096]
- Rebase of Golang package to upcoming version 1.18 in Fedora 36, including the rebuild of all dependent packages(the pre-release version of Go will be used for the rebuild if released version will not be available at the time of the mass rebuild).

Tracking bug: [#2037868](https://bugzilla.redhat.com/show_bug.cgi?id=2037868)

---

Discussed in the community meeting today (9-Feb-2022); we agreed on the following:

Once golang 1.18 is available, we should enable CI using that version on our upstream projects:
 - [x] [coreos/butane](https://github.com/coreos/butane)
 - [ ] [coreos/coreos-assembler (mantle)](https://github.com/coreos/coreos-assembler)
 - [x] [coreos/fedora-coreos-stream-generator](https://github.com/coreos/fedora-coreos-stream-generator)
 - [x] [coreos/go-json](https://github.com/coreos/go-json)
 - [x] [coreos/go-semver](https://github.com/coreos/go-semver)
 - [x] [coreos/go-systemd](https://github.com/coreos/go-systemd)
 - [x] [coreos/ignition](https://github.com/coreos/ignition)
 - [x] [coreos/ign-converter](https://github.com/coreos/ign-converter)
 - [x] [coreos/stream-metadata-go](https://github.com/coreos/stream-metadata-go)
 - [x] [coreos/vcontext](https://github.com/coreos/vcontext/)

**Comment by miabbott** [comment]
1.18 was released upstream yesterday (Mar 15, 2022) - https://go.dev/blog/go1.18

**Comment by miabbott** [comment]
https://github.com/coreos/butane/pull/331

**Comment by dustymabe** [comment]
> It's probably worth a quick sanity test that we can build `coreos-assembler` using F36 once the `golang-1.18` package [hits stable in Bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2022-c5cb0d8293)

We can tag that package into the `f36-coreos-continuous` so that F36 cosa builds could pick it up today if that would be useful.

**Comment by miabbott** [comment]
Dusty tagged the `golang-1.18` build  into the F36 continuous repo for me and I did some local tests with a F36 `cosa` container.

:heavy_check_mark: built F36 container with `golang-1.18` successfully
:heavy_check_mark: built FCOS + ran `kola run` successfully
:yellow_circle:  build RHCOS 4.11 + ran `kola run` mostly successfully (failed on `ext.config.shared.files.file-directory-permissions` but I don't believe it is related to go 1.18)

The Butane and Ignition PRs to enable testing with 1.18 merged, too

No major issues found in any of the investigation, so I think we are OK for F36 from the golang 1.18 perspective.

**Comment by dustymabe** [comment]
Thank you @miabbott

**Comment by miabbott** [comment]
Forgot about `stream-metadata-go` - https://github.com/coreos/stream-metadata-go/pull/43

**Comment by miabbott** [comment]
@bgilbert helpfully pointed out a number of Go libraries we maintain that could use the 1.18 treatment, too

- https://github.com/coreos/ign-converter/pull/31
- https://github.com/coreos/go-json/pull/10
- https://github.com/coreos/vcontext/pull/23
- https://github.com/coreos/go-semver/pull/38
- https://github.com/coreos/go-systemd/pull/400
- https://github.com/coreos/fedora-coreos-stream-generator/pull/43

**Comment by dustymabe** [comment]
Anything left for this PR? Just moving COSA over to Fedora 36 (probably happen shortly after 36 GA)?

**Comment by miabbott** [comment]
Yup, I think we are done here.
