### ISSUE TITLE
set up logging for #fedora-coreos IRC channel

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#11]
This started as a discussion on the mailing list before we had an issue tracker: https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/ETRBNRM5ZCUP7PN3SMB3YP6I36S4Y46M/

It was decided to set up logging so that people who don't sit in the channel at all times can review conversations and also so we can link to conversations that were had for context. I'll try to work with botbot.me to set up logging similar to [how it is set up for #coreos](https://botbot.me/freenode/coreos/)

**Comment by ipmb** [comment]
👋 https://botbot.me/freenode/fedora-coreos/msg/102035676/

**Comment by bgilbert** [comment]
Added a channel entry message with the BotBot link to comply with freenode policy.

**Comment by dustymabe** [comment]
also added to channel topic to satisfy freenode guidelines: *Welcome to Fedora CoreOS :: Find out more @ https://coreos.fedoraproject.org :: IRC logs https://botbot.me/freenode/fedora-coreos/*

**Comment by dustymabe** [comment]
marking as done!

**Comment by bgilbert** [comment]
@dustymabe My reading of the guidelines is that we need the announcement one place or the other but not both.  I picked the channel entry message to keep the topic cleaner, but if we want it in the topic I'd be inclined to drop the entry message.

**Comment by dustymabe** [comment]
@bgilbert +1 - I was mostly going off of the message from the botbot.me form:

![screenshot_2018-07-13 botbot me o__o](https://user-images.githubusercontent.com/4530030/42694305-ed5f7f48-867f-11e8-95c6-a732f6106da1.png)

**Comment by bgilbert** [comment]
OK, dropped the entry message.

**Comment by bgilbert** [comment]
[botbot.me is shutting down on November 5](https://lincolnloop.com/blog/saying-goodbye-botbotme/), so we'll need to find an alternate mechanism.

**Comment by dustymabe** [comment]
@nirik - what are the chances we could set up a botbot.me instance in fedora infra for use within the fedora ecosystem ?

**Comment by sayanchowdhury** [comment]
But we might need to think of GDPR compliance, due which botbot.me is shutting down.

**Comment by dustymabe** [comment]
ok asked legal about complying with the GPDR. They said that they do have the same concerns about the GPDR. In the [last meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/YRO4SZ7M3TX2ZFR3ZSWMHBXD2RNGF3N5/) we discussed and the question was raised about if we just stored things temporarily if that would alleviate concerns. Legal said this might help, but steering clear of hosting our own instance as part of the Fedora project is still the recommendation from legal.

**Comment by dustymabe** [comment]
Started [discussion on legal@ fedora mailing list](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/3F55G3GAFWAAAWSUVLTIC73MYCT72PSC/). It looks like we should be able to do this if we follow a few recommendations:

- limit logging to 2 weeks of time
- notify users clearly of "round the clock" logging (topic and welcome message)
- have a bot that reminds users frequently of channel logging 
- work with fedora infra to set the infrastructure up

I [opened a request](https://pagure.io/fedora-infrastructure/issue/7306) for fedora infra. They are busy right now with F29 so I don't expect anything before F29 release, but we shouldn't have too much lapse between EOL botbot.me and we can have something set up with infra.

**Comment by mskarbek** [comment]
Because we don't want to host our own then maybe this: https://echelog.com/

**Comment by dustymabe** [comment]
Talked about this in the meeting yesterday. @ajeddeloh has agreed to try to reach out to echelog and see if they'll log our channel.

**Comment by bgilbert** [comment]
The channel is now being [logged](https://echelog.com/logs/browse/fedora-coreos/) by echelog.

**Comment by bgilbert** [comment]
Echelog has a [note on its front page](https://echelog.com/) saying that it's shutting down, but with an addendum saying that they're now investigating handing over the project.

**Comment by bgilbert** [comment]
Echelog is no longer logging `#fedora-coreos`.

**Comment by bgilbert** [comment]
Any objections to enabling [LogBot](https://freenode.logbot.info/)?

**Comment by bgilbert** [comment]
Discussed in today's IRC meeting.

```
<dustymabe> #action bgilbert to enable LogBot
```

LogBot is now [enabled](https://freenode.logbot.info/fedora-coreos).

**Comment by bgilbert** [comment]
LogBot is [shutting down](https://freenode.logbot.info/_shutdown) at the end of June.

**Comment by bgilbert** [comment]
Here's [one possible replacement](https://freenode.irclog.whitequark.org/).

**Comment by dustymabe** [comment]
We discussed this in our [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/CEMDQMEWCYHG56RFW56O5565IAJGZXH2/).

```
13:05:59  dustymabe | #agreed We will not pursue a new IRC logger yet, pending 
                    | possible channel migration and more experience with Matrix.

```

**Comment by bgilbert** [comment]
The `#fedora-coreos` channel has now [moved](https://fedoramagazine.org/irc-announcement/) to Libera.Chat, and it appears from https://github.com/globau/logbot/issues/88#issuecomment-845013473 that LogBot will not follow it.  LogBot will continue to log the old Freenode channel until the bot is decommissioned next month (because that approach doesn't require us to do anything) and historical logs will remain available for some amount of time thereafter.

**Comment by dustymabe** [comment]
Logs now at https://libera.irclog.whitequark.org/fedora-coreos
