### ISSUE TITLE
Support cloud-specific grub fragments

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#110]
Some clouds need particular kernel command-line arguments and grub commands, usually for configuring the console.  On CL, this is used on AWS, Azure, GCP, and Packet.

**Comment by dustymabe** [comment]
Do you have examples of what these values are in CL?

**Comment by dustymabe** [comment]
For the console values.. would it help if the kernel supported something like [this](https://lkml.org/lkml/2018/11/5/80)?

**Comment by bgilbert** [comment]
According to the Packet folks, `gfxpayload` is not needed.

Each Packet machine generally has a randomized root password which is made available through the Packet API.  Container Linux uses `coreos.autologin` instead.  Fedora CoreOS could opt for the randomized password approach, if desired.

**Comment by bgilbert** [comment]
On Container Linux, the OEM partition has a `grub.cfg` fragment which is sourced by the main GRUB config at runtime.  Those are the files linked in https://github.com/coreos/fedora-coreos-tracker/issues/110#issuecomment-453801270.  The fragment is pretty much limited to setting or appending to variables used in the kernel command line, such as `$linux_console` or `$linux_append`.

We could do something similar here, but it may not be necessary, since (unlike in CL) the base image knows about all of the supported platforms.  We could have conditionals in the base config that set variables based on the platform ID, which GRUB already knows.

See also https://github.com/coreos/fedora-coreos-tracker/issues/47#issuecomment-455371075.

**Comment by bgilbert** [comment]
Per https://github.com/coreos/fedora-coreos-tracker/issues/114#issuecomment-457015273 we won't be enabling a `coreos.autologin`-like parameter on Packet.

**Comment by dustymabe** [comment]
I think this will be covered with the following work:

- https://github.com/coreos/coreos-assembler/pull/2400
- https://github.com/coreos/fedora-coreos-config/pull/1781

am I missing anything?

**Comment by bgilbert** [comment]
Yup, that should do it.

**Comment by dustymabe** [comment]
I'm going to close this out. The initial use of this was used to implement https://github.com/coreos/fedora-coreos-tracker/issues/567
