### ISSUE TITLE
kola: rawhide: 20220214: ext.config.toolbox fails; no F37 toolbox container exists

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1103]
There is no F37 toolbox container in the registry:

```
[core@cosa-devsh ~]$ toolbox create --assumeyes
Error: failed to pull image registry.fedoraproject.org/fedora-toolbox:37
If it was a private image, log in with: podman login registry.fedoraproject.org
Use 'toolbox --verbose ...' for further details.
```

We'll need to disable the test until that container is created.

**Comment by HarryMichal** [comment]
Yikes, this isn't good. :/

**Comment by dustymabe** [comment]
The snooze for `ext.config.toolbox` was extended in https://github.com/coreos/fedora-coreos-config/pull/1543.

**Comment by juhp** [comment]
fedora-toolbox:37 and fedora-toolbox:36 are in candidate-registry.fedoraproject.org now

**Comment by dustymabe** [comment]
The denial for this was dropped in https://github.com/coreos/fedora-coreos-config/pull/1602
