### ISSUE TITLE
F36: CHANGE: Podman 4.0

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1106]
In the [2022-02-16 community meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/JIXXRY4HMZQAHKY6UEXLQ3IB4EUB4X3M/) we decided to open a ticket for podman v4 in FCOS.

- [Podman 4.0](https://fedoraproject.org/wiki/Changes/Podman4.0)
     - Podman 4.0 will be released in Fedora 36 for the first time.
     - Tracking bug: [#2052692](https://bugzilla.redhat.com/show_bug.cgi?id=2052692)

**Comment by dustymabe** [comment]
Note this is related to the request to ship podman 4.0 in F35 as well: https://github.com/coreos/fedora-coreos-tracker/issues/1070

**Comment by dustymabe** [comment]
The current action item here is:

```
12:35:48       dustymabe | #action jlebon to send out an announcement about
                         | podmanv4 coming to F36 and the beta coming to next in
                         | the coming weeks
```


Basically we need to come up with a summary of the breaking changes so our users have notice before the F36 beta lands in `next`.

**Comment by travier** [comment]
Should I write a short guide using https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman4/ to let users try podman v4 on FCOS ahead of the f36 rebase?

**Comment by dustymabe** [comment]
Seems like it could be a good thing 👍

**Comment by jlebon** [comment]
Wrote up a draft email in https://hackmd.io/fw3O4MYgTECcuq1cYLeTMg. Feel free to edit/tweak.

**Comment by dustymabe** [comment]
`next` has been on a Fedora 36 base for a few weeks now. So far no issues reported. One test that will be telling is if we can still use `gangplank` to do builds (we might be using some of the APIs that have backwards incompatible changes).

**Comment by dustymabe** [comment]
I verified today that we can still use gangplank to do builds by spinning up our aarch64 builder against the `next` stream. Seems to be working great so far.

Considering we've seen no issues so far I'm going to close this one out.
