### ISSUE TITLE
tracker: This Month in Fedora CoreOS February 2022

### ISSUE THREAD

**Issue by cverna** [coreos/fedora-coreos-tracker#1107]
Please link or comment anything you would like to see in the next This Month in Fedora CoreOS edition

Link to the Feb HackMD --> https://hackmd.io/fITa6rtNTy6Ub1WO4nkdnw?edit

**Comment by bgilbert** [comment]
Documented new coreos-installer live image customization commands; reworked and extended live ISO/PXE documentation: https://github.com/coreos/fedora-coreos-docs/pull/355

Added support for TFTP URLs in `coreos.live.rootfs_url`: https://github.com/coreos/fedora-coreos-config/pull/1526

**Comment by dustymabe** [comment]
> I'd like to see a summary of first-time contributors to the CoreOS projects each month.

one of note:
- https://github.com/coreos/ignition/pull/1303 by @Nemric

**Comment by jlebon** [comment]
https://github.com/coreos/rpm-ostree/releases/tag/v2022.3

**Comment by cverna** [comment]
Closing in favour of the March tracker https://github.com/coreos/fedora-coreos-tracker/issues/1117

**Comment by cverna** [comment]
https://discussion.fedoraproject.org/t/this-month-in-fedora-coreos-february-2022/37477
