### ISSUE TITLE
 tracker: This Month in Fedora CoreOS March 2022

### ISSUE THREAD

**Issue by cverna** [coreos/fedora-coreos-tracker#1117]
Please link or comment anything you would like to see in the next This Month in Fedora CoreOS edition

Link to the HackMD --> https://hackmd.io/fITa6rtNTy6Ub1WO4nkdnw?edit

**Comment by jlebon** [comment]
Moved CoreOS CI (upstream CI infrastructure) from CentOS CI to the Fedora infra.

**Comment by bgilbert** [comment]
VMware OVA images are moving to UEFI by default, with Secure Boot enabled.

**Comment by dustymabe** [comment]
We should mention new contributor @WOnder93 and the [work they are doing](https://github.com/ostreedev/ostree/pull/2569) to [improve our SELinux story](https://github.com/coreos/fedora-coreos-tracker/issues/701). If we don't mention it this month (might be a little early) then let's carry it forward for next month.

**Comment by miabbott** [comment]
Updating VMware OVA to use UEFI + SecureBoot by default - https://github.com/coreos/fedora-coreos-tracker/issues/1140

**Comment by dustymabe** [comment]
Test Day/Week: https://testdays.fedoraproject.org/events/131

**Comment by cverna** [comment]
April edition --> https://github.com/coreos/fedora-coreos-tracker/issues/1157
