### ISSUE TITLE
Consider adding kernel command-line argument for automatically logging in on console

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#112]
Container Linux [supports](https://github.com/coreos/init/blob/63dbf7d8d755d51a80dd48837b54fc7199d7d084/systemd/system-generators/coreos-autologin-generator) the `coreos.autologin` kernel command-line argument, which automatically logs in on the specified console, or on all consoles if none is specified.  This is helpful for debugging, since most CL systems don't set passwords on any accounts.  It's also used on one platform (Packet) to ease debugging via the platform's console access mechanism.

Consider providing similar functionality in Fedora CoreOS.

**Comment by dustymabe** [comment]
I like the idea. Here are a few questions

- Is this a relative low priority if we decide not to enable by default (#114)
- If we have this feature would it be too easy for a cloud provider to modify the image we give them and enable it by default even though we chose not to?

**Comment by dustymabe** [comment]
one more

- if we implement something like this, is it specific to coreos? Should we try to implement it at another layer so it's valuable to the rest of fedora, or other distros?

**Comment by bgilbert** [comment]
Notes from the [meeting last week](https://meetbot.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2019-01-16-16.32.html):

- Instead of a kernel command-line parameter, we could have a file-based mechanism that could be enabled via Ignition.  There are several ways to do this:
  - Document an Ignition snippet for writing out the systemd drop-in.
  - Have CT sugar that creates the drop-in.
  - Have a systemd generator that checks for a flag file and creates the drop-in.  Document the flag file.
- None of that helps for debugging existing systems, where a dedicated kernel parameter is nice.  If the flag file is supported, there's `rd.break` + creating the file under `/sysroot`, but that's clunky.
  - `single` already exists, but doesn't work by default because of the lack of root password.  We could fix `single` and avoid defining a separate parameter.
- For developer/scratch/test systems where the user may not want to figure out how to pass an Ignition config, a kernel command-line parameter would still be useful.  AH had [developer mode](https://www.projectatomic.io/blog/2016/03/introducing-atomic-devmode/) for this case.
- We can always implement an autologin parameter later, but once it's there, it'll be difficult to remove.

**Comment by dustymabe** [comment]
We recently did some work around this for live PXE/ISO. @bgilbert any thoughts on making it more generic to apply to other use cases, [but only if the user asked for it](https://github.com/coreos/fedora-coreos-tracker/issues/114#issuecomment-457015273).

**Comment by bgilbert** [comment]
My current view is that we should proceed without it and see what sort of feedback we get.  We can always add the feature, but can never remove it.

**Comment by dustymabe** [comment]
Should we close this issue out or is there something left to do?

**Comment by bgilbert** [comment]
This isn't a priority for now, but let's leave the issue open to centralize discussion in case there's interest in pursuing it later.

**Comment by dshinton-qstart** [comment]
Given the announcement of EOL for CoreOS, it is driving folks like myself to FCOS. We absolutely need a password recovery process for FCOS and for CoreOS that used `coreos.autologin`.

I don't care how it is done, either via `coreos.autologin` or by allowing users to inject an ignition snippet via the bootloader, we just need a solution that someone who isn't an admin can follow to reset the password because I have had customers lose their CoreOS password and SSH keys before. I cannot switch to FCOS if something like this isn't nailed down because backdooring my customer's systems or hacking their password via rescue images are not viable options.

**Comment by jlebon** [comment]
I added some docs about access recovery at https://github.com/coreos/fedora-coreos-docs/pull/48.

**Comment by dustymabe** [comment]
We discussed this during the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/VBOT6FBEIRZI3KZ4YAVM3GJ6CXZAVQB6/). There are two use cases for something like this:

- making it easier for users to debug problems (ignition, bootup, credentials, etc)
- making tutorials/labs easier (don't have to fiddle with SSH keys)

The primary use is obviously the first one. The second use case is mostly a convenience and not necessary. Considering that, the outcome of the discussion today was:

```
  * we'll investigate allowing the use of `single` with a locked root
    account to see if that gives us the ergonomics we want for debugging
    user's issues  (dustymabe, 17:18:55)
```

@bgilbert is that something you might be able to investigate? If we do go with `single` then we should probably add it to the docs as well.

**Comment by dustymabe** [comment]
> There are two use cases for something like this:
>
> * making it easier for users to debug problems (ignition, bootup, credentials, etc)
> * making tutorials/labs easier (don't have to fiddle with SSH keys)

A 3rd use case I can think of: `development`. I often am crafting fcct/ignition configs for dev purposes and copying my SSH pubkey around everywhere is a pain. I guess I should use a platform that can take advantage of afterburn to get SSH keys that way.

**Comment by cgwalters** [comment]
xref https://github.com/coreos/fedora-coreos-config/pull/311

**Comment by dustymabe** [comment]
Considering the [outcome of the meeting on March 11th](https://github.com/coreos/fedora-coreos-tracker/issues/112#issuecomment-597895312) and the fact that `single` now works ([docs PR](https://github.com/coreos/fedora-coreos-docs/pull/68)). I think we can close this as WONTFIX.
