### ISSUE TITLE
F36: Fedora CoreOS Test Week

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1123]
It's time to schedule a CoreOS test day. The `next` stream release will be rebased to Fedora 36 the week that it goes Beta:

The focus of the test day will be:

    Bugs not caught by the CI
    File editors properly handling the new extensions
    Documentation
    Raise Awareness about Fedora CoreOS

The Fedora QA ticket is at: https://pagure.io/fedora-qa/issue/695

**Comment by sumantro93** [comment]
Hey Dusty,

First of all thanks a lot for getting the ball rolling!
What is the timeframe we are looking at ?
Also, what are the new test cases that need to be written for this test week?

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/LOOOQUFHILOCHPXA2O54NRF7BWPOZMFH/).

```
12:48:08    dustymabe | #action ravanelli and mnguyen and miabbott to work with  
                      | dustymabe to organize the test day for f36. miabbott will
                      | attempt to document the process for future iterations
```


Some rough notes that I wrote down during the meeting about steps involved:

- look at test cases from last time, identify any need for new test cases
- delegate out writing those new test cases
- update documentation with any missing/outdated pieces
- on test day - find people to run the tests and enter results
- collect info about who participated and get a new badge created a distrubuted
- try to collate some of the outcomes of the test day in an email to send out

**Comment by dustymabe** [comment]
@sumantro93 - I think we are going to try to target the week of 04/04/2022.

**Comment by sumantro93** [comment]
Thanks!! I will prepare the bits! :)

**Comment by sumantro93** [comment]
wiki  : https://fedoraproject.org/wiki/Test_Day:Fedora_36_CoreOS_2022-04-04
event : https://testdays.fedoraproject.org/events/131

**Comment by miabbott** [comment]
TODO list ahead of test day - https://github.com/coreos/fedora-coreos-tracker/issues/1147

**Comment by dustymabe** [comment]
It looks like the test day/week has been a huge success. We had reported results from 22 participants and found the following issues (either through test week or through general use of our `next` stream that's been rebased to Fedora 36 content):

- https://github.com/coreos/fedora-coreos-tracker/issues/1160
- https://github.com/coreos/fedora-coreos-tracker/issues/1153
- https://github.com/coreos/fedora-coreos-tracker/issues/1156
- https://github.com/coreos/fedora-coreos-tracker/issues/1150
- https://github.com/coreos/fedora-coreos-tracker/issues/1145
- https://github.com/coreos/fedora-coreos-tracker/issues/1149


We also had the following docs updates:

- https://github.com/coreos/fedora-coreos-docs/pull/392
- https://github.com/coreos/fedora-coreos-docs/pull/391
- https://github.com/coreos/fedora-coreos-docs/pull/390
- https://github.com/coreos/fedora-coreos-docs/pull/388
- https://github.com/coreos/fedora-coreos-docs/pull/387
- https://github.com/coreos/fedora-coreos-docs/pull/386
- https://github.com/coreos/fedora-coreos-docs/pull/385
- https://github.com/coreos/fedora-coreos-docs/pull/383

The full test day results page can be viewed at: https://testdays.fedoraproject.org/events/131

Thanks to everyone involved in making test day a success and helping us to find and fix issues in Fedora CoreOS and in our documentation!
