### ISSUE TITLE
Use MOTD to display Ignition warnings on the console 

### ISSUE THREAD

**Issue by sohankunkerkar** [coreos/fedora-coreos-tracker#1125]
**Describe the enhancement**
The motivation behind this enhancement: https://github.com/coreos/ignition/issues/1301
We're thinking of displaying a warning for the above issue on the serial console via a motd, however, after some discussion with @jlebon and @bgilbert, it seems like extending this feature to all Ignition warnings makes more sense here and would be a good UX improvement for FCOS users.

**System details**
 - Bare Metal/QEMU/AWS/GCP/etc.
 - Fedora CoreOS 35.20220227.3.0

**Comment by travier** [comment]
That sounds like a great idea

**Comment by sohankunkerkar** [comment]
I think we've enough upvotes here, so I will go ahead and start implementing this feature.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `35.20220410.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `35.20220410.3.1`.
