### ISSUE TITLE
Platform Request: kubevirt

### ISSUE THREAD

**Issue by rmohr** [coreos/fedora-coreos-tracker#1126]
In order to implement support for a new cloud platform in Fedora CoreOS, we need to know several things about the platform.  Please try to answer as many questions as you can.

- [x] Why is the platform important?  Who uses it?

[KubeVirt](https://github.com/kubevirt/kubevirt) is an extension to kubernetes which allows managing VMs side-by-side with container workloads. It just recently entered the CNCF incubation phase (https://www.cncf.io/projects/kubevirt/) and is used for various virtualizatin products based on kubernetes. A non-exhaustive list of the most famous vendors:

 * [OpenShift Virtualization](https://docs.openshift.com/container-platform/4.10/virt/about-virt.html?extIdCarryOver=true&intcmp=7013a0000025wzsAAA&sc_cid=7013a0000025vnsAAA)
 * [Google Anthos](https://cloud.google.com/anthos/clusters/docs/bare-metal/1.8/how-to/vm-workloads)
 * [Suse Harvester](https://www.suse.com/de-de/products/harvester/)

KubeVirt aims to be as feature-rich as solutions like OpenStack or oVirt, allowing to converge the whole infrastructure stack to pure k8s to have unfied API paradigms and simpler to manage stacks, when working with k8s based infrastructure.

- [x] What is the official name of the platform?  Is there a short name that's commonly used in client API implementations?

`KubeVirt` is the official name. Where needed lowercase `kubevirt` is used. In the kuberenetes api `KubeVirt` has its own `kubevirt.io` group name (`kubevirt.io/v1/namespaces/mynamespace/virtualmachineinstances/myvm`). From a technical perspective, in the kubernetes world `kubevirt.io`.

- [ ] How can the OS retrieve instance userdata?  What happens if no userdata is provided?

KubeVirt supports a [broad range of boot config sources](https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#startup-scripts):
* cloud-init: NoCloud (like e.g. oVirt) and ConfigDrive (like OpenStack)
* ignition: via ConfigDrive

If no user-data is present, the VM has to be configured manually via `ssh`, `VNC` or the like.

- [ ] Does the platform provide a way to configure SSH keys for the instance?  How can the OS retrieve them?  What happens if none are provided?

 * cloud-init (user-data or metadata)
 * ignition
 * qemu-guest-agent-exec

If no ssh keys are given, people can access the vms via `console` or `vnc` to do initial setup.

- [x] How can the OS retrieve network configuration?  Is DHCP sufficient, or is there some other network-accessible metadata service?

DHCP is sufficient. cloud-init network config v1 can be used (and is automatically populated if cloud-init is used for bringing in user-data).

- [x] In particular, how can the OS retrieve the system hostname?

 * DHCP options
 * cloud-init
 * ignition

- [x] Does the platform require the OS to have a specific console configuration?

 It is helpful if a console is provided on the first `virtio-serial` device. It is not mandatory to get a properly working VM, but it is very common that our users connect for various tasks via `kubectl virt console {myvm}` to this console to debug the VM. VNC consoles are also popular. We connect a small vga device to a qemu vnc server by default. Users can opt out of the vga device.

- [x] Is there a mechanism for the OS to report to the platform that it has successfully booted?  Is the mechanism required?

Ther exist a few ways to indicate readiness, all optional:
 * tcp probes
 * http probes
 * exec probes (based on qemu-guest-agent)

- [x] Does the platform have an agent that runs inside the instance?  Is it required?  What does it do?  What language is it implemented in, and where is the source code repository?

We support the qemu-guest-agent and recommend it (gives an overall better integration experience, also for services building on top, since there is first-class API support for retriving e.g. IP information of additional devices which can be used for routing, ...). We also support ssh-key injection and readiness probes based on the guest agent.

- [x] How are VM images uploaded to the platform and published to other users?  Is there an API?  What disk image format is expected?

We have [containerDisks](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk-workflow-example) which basically are qcow2 files wrapped in containers and pushed to arbitrary container registries.

A very simple example to create on would be such a Dockerfile:

```
FROM scratch
ADD --chown=107:107 my.qcow2 /disk/
``` 

which can be built and pushed like this:

```
podman build . -t quay.io/myorg/myimage
podman push quay.io/myorg/myimage
```

The containerDisks can the be imported and used in different KubeVirt-enabled clusters in various ways.
A non exclusive list is:

 * Importing into PVCs for mutable boot disks
 * Direct usage by referencing the container directly on VMIs for ephemeral boot disks (like on pods or containers in general)

ContainerDisks can be hosted on private and public registries and freely mirrored, while one can ensure integrity by referencing the container digests.

- [x] Are there any other platform quirks we should know about?

KubeVirt is to a certain degree bound to the network model of k8s. In k8s every pod gets a different IP/MAC on each pod start. Responsible for this are the CNIs (container network interface). For as long as the VMs are ephemeral, the IP assignment to the VM works perfect. It gets a little bit more tricky when we talk about persistent root disks. There the guests very often don't identify `eth0` after reboot again because of the changed MAC address and DHCP is not performed. We have ways to work around this with different network models, but if the guest can handle this, it gives the best user-experience.

- [ ] Relationship to the openstack platform

KubeVirt is compatible with the openstack images. For visibility and discoverability for technical processes and users it would be helpful to have a containerDisk for kubevirt published and documented, as well as having it listedn in the release and stream json files. Getting its own sections and platform entries. ~I would however prefer to keep the `openstack` ignition ID in the guest.~

A new `kubevirt` platform ID is introduced in the following PRs:
 * https://github.com/coreos/coreos-assembler/pull/2750
 * https://github.com/coreos/ignition/pull/1334
 * https://github.com/coreos/afterburn/pull/725
 * https://github.com/coreos/stream-metadata-rust/pull/24
 * https://github.com/coreos/stream-metadata-go/pull/41
 * https://github.com/coreos/fedora-coreos-tracker/pull/1144

**Comment by dustymabe** [comment]
> We have [containerDisks](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk-workflow-example) which basically are qcow2 files wrapped in containers and pushed to arbitrary container registries.

Is it really a requirement to wrap the qcow2 in a container? I can see how it would be useful in some cases, but most VM disk images are available as a qcow2 or raw disk image. Can Kubevirt not import a qcow2 directly (even if it then wrapped it in a container and stored it in a local registry)?

**Comment by rmohr** [comment]
> > We have [containerDisks](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk-workflow-example) which basically are qcow2 files wrapped in containers and pushed to arbitrary container registries.
> 
> Is it really a requirement to wrap the qcow2 in a container? I can see how it would be useful in some cases, but most VM disk images are available as a qcow2 or raw disk image. Can Kubevirt not import a qcow2 directly (even if it then wrapped it in a container and stored it in a local registry)?

Since it is fully k8s native, it is the preferred and general way on how to exchange images in kubevirt and make them available. Container registries in public and private clusters are the common denominator which allow us unified delivery, auditing, mirroring flows.

A sub-project in KubeVirt also supports importing various sources, including qcow2 over http. All are not optimal though and have their own downsides (like for http import, people would have to provide shasums directly to ensure integrity).

The most compatible ways are container registries accessible from a cluster. Think about it like the global AMI store. The kubevirt community also started creating a general containerdisk store in quay (https://quay.io/organization/containerdisks). It is backed by some tooling which is scraping release sites to pick up new released images and make them available in a unified way. I think this is a great example, where the superiority of the containerDisk is shown. Once I know where a disk is, it removes all variations on how to identify and verify them and how to detect and find updates.

**Comment by dustymabe** [comment]
In my opinion if a containerdisk is required then we at least need to create a new artifact for this (i.e. we can't just ship the openstack qcow2 like we do today and go on with life), so we probably need a new platform.

I guess an alternative is that we still just ship the openstack qcow2,  but we document how to create a containerdisk out of it and then interact with kubevirt to install it.

**Comment by rmohr** [comment]
> In my opinion if a containerdisk is required then we at least need to create a new artifact for this (i.e. we can't just ship the openstack qcow2 like we do today and go on with life), so we probably need a new platform.
> 
> I guess an alternative is that we still just ship the openstack qcow2, but we document how to create a containerdisk out of it and then interact with kubevirt to install it.

Yes, having a containerdisk is one of my top priorities. https://github.com/coreos/coreos-assembler/pull/2750 has the create and publish flow already (target locations and credentials to push there are of course not there).

**Comment by lucab** [comment]
I think there has been some mixups on some of those answers, but reading through it I think that the environment looks like this:
 * network is auto-configured via DHCP
 * hostname is provided by DHCP
 * there is no metadata service on a link-local endpoint
 * instance userdata is provided through a config-drive (openstack compatible)
 * the VM does not need to actively signal to the underlying infra upon boot

@rmohr is that a correct summary?

**Comment by rmohr** [comment]
> I think there has been some mixups on some of those answers, but reading through it I think that the environment looks like this:
> 
> * network is auto-configured via DHCP

Yes

> * hostname is provided by DHCP

Yes

> * there is no metadata service on a link-local endpoint

Yes
> * instance userdata is provided through a config-drive (openstack compatible)

Yes, but if you use cloud-init, the hostname will be provided by the platform metadata over these drives too (basically in addition to dhcp at the same time, therefore the overlap).

> * the VM does not need to actively signal to the underlying infra upon boot

Correct.
> 
> @rmohr is that a correct summary?

In principle yes. I think the mixup comes from the fact that we send in some scenario the infos on multiple channels at the same time :)

**Comment by rmohr** [comment]
> End users will ultimately be booting guest VMs in OpenStack

@miabbott just to clarify: kubevirt has nothing to to with OpenStack. It is 100% built on kubernetes. It is not an "abstraction-layer" based on k8s to e.g. openstack.

**Comment by bgilbert** [comment]
It sounds like this is really a new platform, which happens to provide OpenStack-compatible configuration mechanisms.  We already support other platforms that made a similar choice.  If so, I agree with @jlebon that we should define a new Ignition platform ID rather than trying to reuse `openstack`.  We could conceivably need to implement KubeVirt-specific behavior in the future, and it'd be good to avoid bolting that into the OpenStack providers.

We should not ship a `kubevirt` provider in stream metadata that uses the `openstack` platform ID internally.  That would be confusing and we don't do it on any other platforms.  If we don't want to add a new platform ID, it'd be better to add KubeVirt to stream metadata as an additional `openstack` artifact than to try to split the difference.  Adding a new provider to Ignition and Afterburn should be doable for 4.11, so I'd be inclined to avoid short-term workarounds as well.

**Comment by bgilbert** [comment]
> > If we don't want to add a new platform ID, it'd be better to add KubeVirt to stream metadata as an additional `openstack` artifact than to try to split the difference.
> 
> The main issue with that is probably that we then provide an image as part of the openstack platform which effectively can't be consumed by openstack :)

Yeah, that's fair.

> > Adding a new provider to Ignition and Afterburn should be doable for 4.11, so I'd be inclined to avoid short-term workarounds as well.
> 
> Could you point me roughly to the locations where these tools would need to be extended?

For Ignition, you can probably do something similar to https://github.com/coreos/ignition/commit/1f710f715666e535ce9b0fd48cac3ec089dbf71a (and also add docs in [supported-platforms.md](https://github.com/coreos/ignition/blob/main/docs/supported-platforms.md)).  For Afterburn, you can do something like https://github.com/coreos/afterburn/commit/542ee1b2974d66d5eb902db3d081349ee7512479.

**Comment by rmohr** [comment]
> For Ignition, you can probably do something similar to [coreos/ignition@1f710f7](https://github.com/coreos/ignition/commit/1f710f715666e535ce9b0fd48cac3ec089dbf71a) (and also add docs in [supported-platforms.md](https://github.com/coreos/ignition/blob/main/docs/supported-platforms.md)). For Afterburn, you can do something like [coreos/afterburn@542ee1b](https://github.com/coreos/afterburn/commit/542ee1b2974d66d5eb902db3d081349ee7512479).

Thanks I will check that out. One last question: If openstack adds new features which you pick up, it may have to be duplicated for kubevirt. Is this a concern?

**Comment by rmohr** [comment]
> For Ignition, you can probably do something similar to [coreos/ignition@1f710f7](https://github.com/coreos/ignition/commit/1f710f715666e535ce9b0fd48cac3ec089dbf71a) (and also add docs in [supported-platforms.md](https://github.com/coreos/ignition/blob/main/docs/supported-platforms.md)). For Afterburn, you can do something like [coreos/afterburn@542ee1b](https://github.com/coreos/afterburn/commit/542ee1b2974d66d5eb902db3d081349ee7512479).

@bgilbert done. Now I need to figure out how to test it all together :)

**Comment by rmohr** [comment]
> @bgilbert done. Now I need to figure out how to test it all together :)

Updated the PRs with test results.

**Comment by rmohr** [comment]
> > > End users will ultimately be booting guest VMs in OpenStack
> > 
> > 
> > @miabbott just to clarify: kubevirt has nothing to to with OpenStack. It is 100% built on kubernetes. It is **not** an "abstraction-layer" based on k8s to openstack.
> 
> Understood. So it's conceivable that we may want to produce multiple containerdisks for different virt platforms in the future?

@miabbott I am not sure I understand that question.

**Comment by miabbott** [comment]
> > Understood. So it's conceivable that we may want to produce multiple containerdisks for different virt platforms in the future?
> 
> @miabbott I am not sure I understand that question. Could you elaborate?

I think I was confusing myself by some of the details from the original RFE that specifically mentioned shipping the OpenStack qcow2 in the containerdisk format. So I was making the assumption we'd have different containerdisks for different hypervisors/virt platforms (i.e. vSphere, RHEV, OpenStack, etc).

Looking at the implementation in https://github.com/coreos/coreos-assembler/pull/2750 and the docs in https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk-workflow-example, it's more clear that the qcow2 shipped in the containerdisk is generic.

Regardless, I think you are getting the right information from others on this thread, so please continue to do the good work  :)

**Comment by bgilbert** [comment]
> If openstack adds new features which you pick up, it may have to be duplicated for kubevirt. Is this a concern?

Not for now.  We have some existing code duplication which this will make slightly worse, but that's a problem for another day.

**Comment by rmohr** [comment]
> @rmohr We'll also need to update [stream-metadata-rust](https://github.com/coreos/stream-metadata-rust/) to add the container-disk link.

Opened a PR: https://github.com/coreos/stream-metadata-rust/pull/24. Thanks.

**Comment by bgilbert** [comment]
And I just realized that [docs](https://github.com/coreos/fedora-coreos-tracker/tree/main/metadata) should be updated too, and in particular the [stream metadata rationale](https://github.com/coreos/fedora-coreos-tracker/blob/main/metadata/stream/rationale.yaml).

**Comment by dustymabe** [comment]
@gursewak1997 and I got together today to see what work is left to do here. Here is what we came up with:

- [ ] Verify existing work is valid
    - cosa buildextend-kubevirt
        - does it work?
        - can we use it and the pending docs to run a VM in kubernetes/openshift?
- [ ] Make any necessary updates since we are publishing an ociarchive
    - The current rationale is out of date:
        - https://github.com/coreos/fedora-coreos-tracker/blob/ff0056385c428c26359b5739ec2fdf8e1985d27f/metadata/stream/rationale.yaml#L95
    - May need to also update 
        - https://github.com/coreos/stream-metadata-rust/pull/24
        - https://github.com/coreos/stream-metadata-go/pull/41
- [ ] Add kubevirt to list of x86_64 artifacts to get built by the pipeline
    - update https://github.com/coreos/fedora-coreos-pipeline/blob/9251e20257b4ba300f7e61e461ff904d10507df1/config.yaml#L71
- [ ] Push Kubevirt container image to quay
    - When to push?
        - Probably in "cloud upload" step
        - However, maybe to a staging repo, then promote it in the release job.
    - Where to push?
        - For FCOS: `quay.io/fedora/fedora-coreos-kubevirt`?
        - For RHCOS: ?
- [ ] Add docs
    - Can mostly just use https://github.com/coreos/fedora-coreos-docs/pull/394
- [ ] Add pipeline testing (follow on work, not a requirement up front)
    - kola-kubevirt job that tests kubevirt image in a given openshift cluster
        - can we use our `fedora-coreos-pipeline` OpenShift cluster for this?
            - does it support CNV (which is the product name for kubevirt)

**Comment by dustymabe** [comment]
We discussed this in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/DYBQUURSUDPMX47YH2CYKYJGAANFKSDN/).

While trying to figure out the best place to push our kubevirt containerdisk image the following options were brought up:

- Something under `quay.io/fedora` like `quay.io/fedora/fedora-coreos-kubevirt`
- Something under `quay.io/containerdisks` (backed by https://github.com/kubevirt/containerdisks)

We decided to try to reach out to someone to try to figure out more about `quay.io/containerdisks` before making our decision. Will try to invite @fabiand to our next meeting.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/UWRTWP7XJ32CEDQBPKNX5P4ZHE5KSIF4/).

```
13:04:29 dustymabe | #agreed We'll target
                   | `quay.io/fedora/fedora-coreos-kubevirt` as the
                   | location for our kubevirt images for now. We
                   | may consider quay.io/containerdisks in the
                   | future if more information about that repo   
                   | comes to light.
```

**Comment by qinqon** [comment]
Is this going to be backported to 4.13 ?

**Comment by cverna** [comment]
Considering this is a new artefact, we are currently no planning to backport this in 4.13.

**Comment by dustymabe** [comment]
The kubevirt artifact was added to the FCOS pipeline to build in https://github.com/coreos/fedora-coreos-pipeline/pull/860

**Comment by qinqon** [comment]
> The kubevirt artifact was added to the FCOS pipeline to build in [coreos/fedora-coreos-pipeline#860](https://github.com/coreos/fedora-coreos-pipeline/pull/860)

@dustymabe this is the last step to have a kubevirt fcos at https://quay.io/repository/fedora/fedora-coreos-kubevirt ?

**Comment by dustymabe** [comment]
It's there! The images are getting pushed as new builds come in. For example, `quay.io/fedora/fedora-coreos-kubevirt:testing-devel` got pushed this morning, but that's the devel stream. The prod streams will exist when we do our next round of releases.

I'll comment here when that happens.

**Comment by dustymabe** [comment]
Docs landed in https://github.com/coreos/fedora-coreos-docs/pull/528

**Comment by qinqon** [comment]
> It's there! The images are getting pushed as new builds come in. For example, `quay.io/fedora/fedora-coreos-kubevirt:testing-devel` got pushed this morning, but that's the devel stream. The prod streams will exist when we do our next round of releases.
> 
> I'll comment here when that happens.

@dustymabe, have being testing the testing-devel and rawhide and looks like neither of them has the qemu guest agent with is quite useful for kubevirt, do you know if we can would them with it ?

**Comment by cgwalters** [comment]
In CoreOS we only have one image across all platforms, so adding the qemu guest agent would appear everywhere.  This has come up a few times, see https://github.com/coreos/fedora-coreos-tracker/issues/74 as well as https://github.com/coreos/afterburn/issues/458

You could probably comment on #74 with what specific functionality you see missing.

**Comment by qinqon** [comment]
> In CoreOS we only have one image across all platforms, so adding the qemu guest agent would appear everywhere. This has come up a few times, see #74 as well as [coreos/afterburn#458](https://github.com/coreos/afterburn/issues/458)
> 
> You could probably comment on #74 with what specific functionality you see missing.

But why qemu-guest-agent is present at https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20230303.3.0/x86_64/fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2.xz ?

**Comment by cgwalters** [comment]
> But why qemu-guest-agent is present at https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20230303.3.0/x86_64/fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2.xz ?

Well, you made me double check, but:

```
walters@toolbox /v/s/w/m/fcos> curl -L https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20230303.3.0/x86_64/fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2.xz | xz -d > fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  628M  100  628M    0     0  37.3M      0  0:00:16  0:00:16 --:--:-- 36.4M
fedora-coreos-38.20230414.3.0-qemu.x86_64.qcow2
walters@toolbox /v/s/w/m/fcos> cosa run --qemu-image fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2 
Fedora CoreOS 37.20230303.3.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/tag/coreos

Last login: Fri May  5 12:42:36 2023
[core@cosa-devsh ~]$ rpm -qa|grep -i qemu
[core@cosa-devsh ~]$ 
```

But again the thing that's really important to understand here is that for us what's in the disk images (qcow2, AMI) is 95% just a "shell" around the container image which is what we use for OS updates.  (Yes, today FCOS uses ostree native but it's helpful to still think of the OS content this way)

IOW you can do:

```
$ podman run --pull=always --rm -ti quay.io/fedora/fedora-coreos:stable
bash-5.2# rpm -qa|grep -i qemu
bash-5.2# 
```

And whatever you see there is *the same stuff exactly* that is in the disk image when you boot it.

**Comment by qinqon** [comment]
> > But why qemu-guest-agent is present at https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20230303.3.0/x86_64/fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2.xz ?
> 
> Well, you made me double check, but:
> 
> ```
> walters@toolbox /v/s/w/m/fcos> curl -L https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/37.20230303.3.0/x86_64/fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2.xz | xz -d > fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  628M  100  628M    0     0  37.3M      0  0:00:16  0:00:16 --:--:-- 36.4M
> fedora-coreos-38.20230414.3.0-qemu.x86_64.qcow2
> walters@toolbox /v/s/w/m/fcos> cosa run --qemu-image fedora-coreos-37.20230303.3.0-qemu.x86_64.qcow2 
> Fedora CoreOS 37.20230303.3.0
> Tracker: https://github.com/coreos/fedora-coreos-tracker
> Discuss: https://discussion.fedoraproject.org/tag/coreos
> 
> Last login: Fri May  5 12:42:36 2023
> [core@cosa-devsh ~]$ rpm -qa|grep -i qemu
> [core@cosa-devsh ~]$ 
> ```
> 
> But again the thing that's really important to understand here is that for us what's in the disk images (qcow2, AMI) is 95% just a "shell" around the container image which is what we use for OS updates. (Yes, today FCOS uses ostree native but it's helpful to still think of the OS content this way)
> 
> IOW you can do:
> 
> ```
> $ podman run --pull=always --rm -ti quay.io/fedora/fedora-coreos:stable
> bash-5.2# rpm -qa|grep -i qemu
> bash-5.2# 
> ```
> 
> And whatever you see there is _the same stuff exactly_ that is in the disk image when you boot it.

I think I cooked in the qemu-guest-agent, pushed to my quay.io/ellorent repo and forget about it, sorry about this.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230514.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230514.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230430.3.1`.
