### ISSUE TITLE
Drop `libvarlink-util` from package set

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1130]
This was [originally added](https://github.com/coreos/fedora-coreos-tracker/issues/231) for `podman-remote` functionality but the podman team ripped out varlink code in v3. We should be safe to remove it but there may be some users using it for other things. I feel like if there was ever an opportunity for us to actually remove a package, this would be it.

- [the current definition](https://github.com/coreos/fedora-coreos-config/blob/224be5d072125445633dfd509b9d6f28ba6fda5d/manifests/fedora-coreos-base.yaml#L124-L125)

**Comment by jlebon** [comment]
Notably, this removes `/usr/bin/varlink`.

**Comment by travier** [comment]
I don't see a lot of activity in https://github.com/varlink/ and I don't know of major projects using it anymore.
If nothing uses it anymore in our default installation then it should be safe to remove. It can still be overlayed as needed for those that require it.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/LOOOQUFHILOCHPXA2O54NRF7BWPOZMFH/).


```
12:58:29    dustymabe | #agreed We don't know of any other common uses of
                      | libvarlink-utils on FCOS right now. We'll try removing it
                      | from `next` and send an email about it to the list to see
                      | if that gives us any new information. After a period of
                      | time with no issues we'll promote that to `testing` and
                      | `stable`.

```

**Comment by dustymabe** [comment]
At this point we should:

- [ ] send an email to the mailing lists notifying of the change
- [ ] drop it from any branches other than `testing-devel`, `testing`, and `stable`.
- [ ] wait some time and then drop it from the rest

**Comment by gursewak1997** [comment]
`Draft email: Open to feedback`

Subject: Fedora CoreOS dropping libvarlink-utils from base OSTree

We have decided to remove the libvarlink-utils package from Fedora CoreOS. Podman was the primary consumer of this package and the use of it was removed in Podman v3.0 and later [1]. At the moment, we are not aware of any other consumers of libvarlink-utils on FCOS.

The package will initially be removed from the next stream. It will be followed by testing and stable after it has been removed from next for at least a month.

The Fedora CoreOS Team

[1] https://podman.io/blogs/2020/08/01/deprecate-and-remove-varlink-notice.html#podman-api-v10-deprecation-and-removal-notice

**Comment by dustymabe** [comment]
Let's drop it from the other branches any time after 05/12/2022.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220505.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `36.20220505.3.2`.
