### ISSUE TITLE
conmon permission denied when running podman

### ISSUE THREAD

**Issue by ljrk0** [coreos/fedora-coreos-tracker#1132]
**Describe the bug**
Very similar to https://github.com/coreos/fedora-coreos-tracker/issues/1089, running `podman` results in `"permission denied" by conmon.

**Reproduction steps**

If yo run an arbitrary container image you get:
```
$ podman run --rm docker.io/library/ubuntu
Error: fork/exec /usr/bin/conmon: permission denied
```

I also noticed that contrary to #1089 `podman images` does not produce an error.

**System details**
 - On QEMU-KVM
 - Fedora CoreOS version: 35.20220227.3.0

**Additional information**

Journal:
```
$ journalctl
Mar 18 09:54:15 earth systemd[6239]: Started podman-11855.scope.
Mar 18 09:54:15 earth podman[11855]: 
Mar 18 09:54:15 earth podman[11855]: 2022-03-18 09:54:15.867813985 +0000 UTC m=+0.108181471 container create 92a1a9871b7a7fb12f645ef5603ae823c8c0139002501fa3e4371a1c5ac7b74b (image=docker.io/library/ubuntu:latest, name=competent_dijkstra)
Mar 18 09:54:15 earth audit[11896]: AVC avc:  denied  { entrypoint } for  pid=11896 comm="podman" path="/usr/bin/conmon" dev="sda4" ino=2950748447 scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=0 trawcon="system_u:object_r:conmon_exec_t:s0"
Mar 18 09:54:15 earth audit[11896]: SYSCALL arch=c000003e syscall=59 success=no exit=-13 a0=c0004d8a40 a1=c000604500 a2=c000391600 a3=8 items=0 ppid=11855 pid=11896 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=pts3 ses=11 comm="podman" exe="/usr/bin/podman" subj=unconfined_u:system_r:container_runtime_t:s0-s0:c0.c1023 key=(null)
Mar 18 09:54:15 earth kernel: audit: type=1400 audit(1647597255.878:2354): avc:  denied  { entrypoint } for  pid=11896 comm="podman" path="/usr/bin/conmon" dev="sda4" ino=2950748447 scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=0 trawcon="system_u:object_r:conmon_exec_t:s0"
Mar 18 09:54:15 earth kernel: audit: type=1300 audit(1647597255.878:2354): arch=c000003e syscall=59 success=no exit=-13 a0=c0004d8a40 a1=c000604500 a2=c000391600 a3=8 items=0 ppid=11855 pid=11896 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=pts3 ses=11 comm="podman" exe="/usr/bin/podman" subj=unconfined_u:system_r:container_runtime_t:s0-s0:c0.c1023 key=(null)
Mar 18 09:54:15 earth podman[11855]: 2022-03-18 09:54:15.821572685 +0000 UTC m=+0.061940171 image pull  docker.io/library/ubuntu
Mar 18 09:54:15 earth audit: PROCTITLE proctitle=706F646D616E0072756E002D2D726D00646F636B65722E696F2F6C6962726172792F7562756E7475
Mar 18 09:54:15 earth kernel: audit: type=1327 audit(1647597255.878:2354): proctitle=706F646D616E0072756E002D2D726D00646F636B65722E696F2F6C6962726172792F7562756E7475
Mar 18 09:54:15 earth podman[11855]: 2022-03-18 09:54:15.919934528 +0000 UTC m=+0.160302024 container remove 92a1a9871b7a7fb12f645ef5603ae823c8c0139002501fa3e4371a1c5ac7b74b (image=docker.io/library/ubuntu:latest, name=competent_dijkstra)
```

Confirmed this can be "fixed" by rolling back to the previous release from the first of March (35.20220213.3.0):
```
$ rpm-ostree rollback -r
```

**Comment by dustymabe** [comment]
Can you give us any more details about your system and how it was set up?

Can you also show the output of this command?

```
sudo ostree admin config-diff | grep selinux/targeted/policy
```

**Comment by dustymabe** [comment]
Yes odd. If you didn't explicitly change the SELinux policy then maybe something else did? Either way you can get back to the defaults using the workaround at the bottom of https://github.com/coreos/fedora-coreos-tracker/issues/701#issue-769395273 and then re-attempt your upgrade. - you'd want to verify before and after that the `config-diff` shows no modification to you policy.

**Comment by ljrk0** [comment]
Hm, the Flatpak package definitely did but nothing too weird, these are diffs of the non-binary files:
```
# diff -a /usr/etc/selinux/targeted/active/commit_num /etc/selinux/targeted/active/commit_num
1c1
< 8
\ No newline at end of file
---
> 9
\ No newline at end of file
# diff -a /usr/etc/selinux/targeted/active/file_contexts /etc/selinux/targeted/active/file_contexts
6256a6257
> /usr/libexec/flatpak-system-helper	--	system_u:object_r:flatpak_helper_exec_t:s0
```
however this is odd in itself, since the currently active deployment doesn't layer `flatpak`...

I've now tried to search in vain -- how do I "unrollback", i.e., boot to the newer version in order to test the workaround?

**Comment by dustymabe** [comment]
hmm. If I install `flatpak` and `docker-compose` on `35.20220213.3.0` I don't see any "modified" selinux-policy.

The best option I can think of for now retrying the upgrade is:

- clean up the existing 2nd deployment - then let zincati upgrade you
    - `sudo rpm-ostree cleanup --rollback`
- manually run the upgrade
    - `sudo systemctl stop zincati.service && sudo rpm-ostree upgrade`

**Comment by ljrk0** [comment]
Hm, I've now simply removed all layered packages & upgraded to the latest version, still the same issue (but I didn't revert the selinux policies yet).  Interestingly, the `file_contexts` diff has now become *larger* instead of smaller, after removing the layered packages.  And they now contain references to conmon...

```diff
# diff -a /usr/etc/selinux/targeted/active/file_contexts /etc/selinux/targeted/active/file_contexts
1385a1386
> /var/lib/kublet(/.*)?	system_u:object_r:container_var_lib_t:s0
1619d1619
< /var/lib/kubelet(/.*)?	system_u:object_r:container_var_lib_t:s0
3973d3972
< /usr/bin/conmon	--	system_u:object_r:conmon_exec_t:s0
5040d5038
< /usr/local/bin/conmon	--	system_u:object_r:conmon_exec_t:s0
6258a6257
> /usr/libexec/flatpak-system-helper	--	system_u:object_r:flatpak_helper_exec_t:s0
```

After that I reverted the SE Linux policies as advised by you, rebooted, and indeed now everything seems to work again!

Thank you very much for your help and pointers, they were invaluable!  For me the issue is fixed but if you are interested in tracking down the root cause, I'll try to help as best I can.  Thanks a bunch!

**Comment by dustymabe** [comment]
Thanks for letting us know! I'll close this one out and look out if more people report the same.

**Comment by sedlund** [comment]
@dustymabe do you think this https://github.com/poseidon/typhoon/issues/1142 is related?

**Comment by dustymabe** [comment]
> @dustymabe do you think this [poseidon/typhoon#1142](https://github.com/poseidon/typhoon/issues/1142) is related?

Maybe more closer to https://github.com/coreos/fedora-coreos-tracker/issues/1138 ?

**Comment by heyakyra** [comment]
I'm on Silverblue 36 and can't enter `toolbox` containers due to:

```
audit[10207]: AVC avc:  denied  { entrypoint } for  pid=10207 comm="podman" path="/usr/bin/conmon" dev="dm-0" ino=1546509 scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:object_r:unlabeled_t:s0 tclass=file permissive=0 trawcon="system_u:object_r:conmon_exec_t:s0"
```

Although on a separate laptop with the same version of everything, `toolbox` work fine, presumably because the working machine was set up from a fresh install and on the non-working one I get

```
$ sudo ostree admin config-diff | grep selinux/targeted/policy
M    selinux/targeted/policy/policy.33
A    selinux/targeted/policy/policy.32
A    selinux/targeted/policy/policy.31
```

while the working one only shows:

```
$ sudo ostree admin config-diff | grep selinux/targeted/policy
M    selinux/targeted/policy/policy.33
```

@dustymabe 
> you can get back to the defaults using the workaround at the bottom of [#701 (comment)](https://github.com/coreos/fedora-coreos-tracker/issues/701#issue-769395273)

Do you mean running `sudo rsync -rclv /usr/etc/selinux/ /etc/selinux/`? I'm confused how to clear out modifications to SELinux config

**Comment by dustymabe** [comment]
> Do you mean running `sudo rsync -rclv /usr/etc/selinux/ /etc/selinux/`?

yes

**Comment by travier** [comment]
Reference doc for SELinux policy update issues (applies to all rpm-ostree based OS): https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_selinux_problems

**Comment by heyakyra** [comment]
So, foolishly when the `rsync` command didn't help, I went ahead and just purged `/etc/selinux` which somehow did resolve the podman issue, but has put me in a bit of a quagmire as chronicled in the forums: https://discussion.fedoraproject.org/t/silverblue-rawhide-2019-02-05-selinux-labels-missing/1080/12?u=kxra
