### ISSUE TITLE
rawhide: 20220322: builds failing hardlinking rpmdb

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1139]
https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/336/
failed with
`error: Finalizing rootfs: Hardlinking rpmdb to base location: Directory not empty (os error 39)`

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/rpm-ostree/pull/3535

**Comment by dustymabe** [comment]
This is no longer an issue because we built [`rpm-ostree-2022.5.80.gb7f91619-1.fc35`](https://koji.fedoraproject.org/koji/buildinfo?buildID=1938465) and got it into a COSA build.
