### ISSUE TITLE
Update the VMware OVA to use UEFI/SecureBoot by default, change OS type to `fedora64Guest`

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#1140]
(Split off of https://github.com/coreos/fedora-coreos-tracker/issues/1119; please see that issue for relevant discussion)

The use of UEFI firmware by guest VMs in VMware products is available to guest VMs that are using hardware version 13, which FCOS is already using by default.

Additionally the use of SecureBoot in guest VMs is available when using hardware version 13.

The change to using UEFI by default happened here - https://github.com/coreos/coreos-assembler/pull/2762/

The change to defaulting to Secure Boot happened here - https://github.com/coreos/coreos-assembler/pull/2767/

We also changed the OS type in the OVA to use `fedora64Guest` as part of https://github.com/coreos/coreos-assembler/pull/2762

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `36.20220325.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `35.20220327.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `35.20220327.3.0`.
