### ISSUE TITLE
rawhide: iproute-5.17.0-1.fc37 requires python3

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1142]
**Describe the bug**

Rawhide builds started failing with:

```
iproute-5.17.0-1.fc37.x86_64 requires /usr/bin/python3
```

https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/358/

Reported upstream in https://bugzilla.redhat.com/show_bug.cgi?id=2068118.

This is an indirect dependency from the new version bump and not an explicit addition. This thus requires more investigation.

**Reproduction steps**
1. Install iproute in a rawhide container

**Expected behavior**

Does not install python3

**Actual behavior**

Installs python3

**System details**
 - Fedora CoreOS version: rawhide

**Ignition config**
N/A

**Additional information**

**Comment by dustymabe** [comment]
Pinned old version of `iproute` in https://github.com/coreos/fedora-coreos-config/commit/d48c05e5f370daa58bea30328c6137590758b70e
