### ISSUE TITLE
supportability of non-EOL VMware platforms

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#1146]
**Describe the enhancement**
Clearly indicate that we support non-EOL VMware platforms.

**Additional information**
In the [discussion](https://github.com/coreos/fedora-coreos-docs/pull/376#discussion_r835829302) on the PR to add docs around changing the OVF metadata for the VMware OVA, it was suggested that we make a statement about supporting non-EOL VMware platforms.  The extent of the proposed statement is that we would not change the hardware version in the OVF metadata to exclude non-EOL platforms.

While I think this is an uncontroversial statement, I wanted to socialize it with the community before making any commitments.

**Comment by dustymabe** [comment]
We discussed this in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/72W3BPKTCILRLKLJ4GOXQO2S5WXQQZ34/).

```
13:03:27            jlebon | #agreed FCOS will not make any changes to the hardware
                           | version in the OVF metadata of the VMware OVA that would  
                           | exclude non-EOL platforms from being supported.
```

**Comment by dustymabe** [comment]
@miabbott - do you have enough information now to proceed?

**Comment by miabbott** [comment]
Yup.  Thanks for discussing it at the meeting.
