### ISSUE TITLE
Ignore SR-IOV interfaces on Azure

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#115]
Container Linux ships a [networkd unit](https://github.com/coreos/init/blob/63dbf7d8d755d51a80dd48837b54fc7199d7d084/systemd/network/yy-azure-sriov.network) to ignore SR-IOV interfaces on Azure.  This is a cosmetic issue; such interfaces won't actually return packets and will never finish configuring.

Implement this via a mechanism consistent with the outcome of https://github.com/coreos/fedora-coreos-tracker/issues/24.

**Comment by dustymabe** [comment]
> This is a cosmetic issue; such interfaces won't actually return packets and will never finish configuring.

is this a bug in the platform and we are just protecting our users?

**Comment by bgilbert** [comment]
The way SR-IOV is implemented on Azure, there's the base NIC functionality and then there's a high-performance mode that shows up as a separate NIC.  The latter is automatically bonded to the former by the kernel driver, but is still visible to userspace even though it doesn't function on its own.

**Comment by lucab** [comment]
@bgilbert I think this was addressed by https://github.com/coreos/fedora-coreos-config/pull/121 and can be closed.

**Comment by bgilbert** [comment]
@lucab Yup!
