### ISSUE TITLE
rawhide: recurring kernel circular locking depency warnings

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1152]
The kernel in rawhide is often built as a debug kernel and these kernels tend to have circular locking dependency warnings. According to Justin Forbes (our Fedora Kernel expert) we should really only dig into these warnings if we don't have anything else to do.

It would be nice if we could figure out how to ignore or not check for this on a particular stream but for now we'll need to pin whenever this comes up.

**Comment by bgilbert** [comment]
If we don't intend to pursue these, we should just drop the check.  Since lockdep isn't enabled on kernels we actually care about, I think that's reasonable.

https://github.com/coreos/coreos-assembler/pull/2796

**Comment by dustymabe** [comment]
> Since lockdep isn't enabled on kernels we actually care about, I think that's reasonable.

Ahh. I didn't realize it was only enabled in rawhide non-rc kernels. Makes sense since that's the only place we're seeing it. 👍
