### ISSUE TITLE
Fedora CoreOS talks for devconf.us 2022

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1154]
https://www.devconf.info/us/

Happening August 18-20, 2022 in Boston, MA USA. 

CFP closes April 15th 2022.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/L3VLJF5OIGUG5U2C74FTY56U5CF3OL2X/).

Several people were interested in giving talks or had ideas about topics:

- dustymabe
- travier
- jlebon
- skunkerk

ideas:

- What's new and what's next in Fedora CoreOS
    - Here's what we did last year at Nest [slides](https://siosm.fedorapeople.org/What_s_new_and_what_s_next_in_Fedora_CoreOS_-_Nest_with_Fedora_2021.pdf)
- CoreOS Layering introduction and demo
- Lab session for introducing people to FCOS (not sure if this is feasible at devconf.us)

**Comment by travier** [comment]
The CfP is closed thus closing this one. We will update here once we know which talks have been accepted.

**Comment by dustymabe** [comment]
Note the CFP got extended to 04/30 I believe (doesn't say on the website but submissions are still open). 

To recap on a recent session a few of us had: @mike-nguyen and I submitted a generic FCOS status & update talk and @sohankunkerkar submitted a lab session for people to learn and get some hands-on experience with FCOS.
