### ISSUE TITLE
F36: 36.20220325.1.0 NetworkManager not allowed to access NM dispatcher scripts

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1156]
**Describe the bug**
NetworkManager dispatcher scripts may stop working because of SELinux denials disallowing the distpatcher scripts to be accessed.

**Reproduction steps**

Simply boot `36.20220325.1.0` and look at the journal.

**Expected behavior**
No messages about permission being denied in the journal for NM dispatchers.

**Actual behavior**

Permission denied message in the journal:

```
Apr 06 19:28:12 cosa-devsh nm-dispatcher[1407]: req:1 'hostname': find-scripts: Failed to open dispatcher directory '/etc/NetworkManager/dispatcher.d': Error opening directory “/etc/NetworkManager/dispatcher.d”: Permission denied
Apr 06 19:28:12 cosa-devsh nm-dispatcher[1407]: req:2 'connectivity-change': find-scripts: Failed to open dispatcher directory '/etc/NetworkManager/dispatcher.d': Error opening directory “/etc/NetworkManager/dispatcher.d”: Permission denied
Apr 06 19:28:12 cosa-devsh nm-dispatcher[1407]: req:3 'hostname': find-scripts: Failed to open dispatcher directory '/etc/NetworkManager/dispatcher.d': Error opening directory “/etc/NetworkManager/dispatcher.d”: Permission denied
Apr 06 19:28:12 cosa-devsh nm-dispatcher[1407]: req:4 'dhcp4-change' [ens7]: find-scripts: Failed to open dispatcher directory '/etc/NetworkManager/dispatcher.d': Error opening directory “/etc/NetworkManager/dispatcher.d”: Permission denied
Apr 06 19:28:12 cosa-devsh nm-dispatcher[1407]: req:5 'pre-up' [ens7]: find-scripts: Failed to open dispatcher directory '/etc/NetworkManager/dispatcher.d/pre-up.d': Error opening directory “/etc/NetworkManager/dispatcher.d/pre-up.d”: Permission denied
Apr 06 19:28:12 cosa-devsh nm-dispatcher[1407]: req:6 'hostname': find-scripts: Failed to open dispatcher directory '/etc/NetworkManager/dispatcher.d': Error opening directory “/etc/NetworkManager/dispatcher.d”: Permission denied
Apr 06 19:28:12 cosa-devsh nm-dispatcher[1407]: req:7 'up' [ens7]: find-scripts: Failed to open dispatcher directory '/etc/NetworkManager/dispatcher.d': Error opening directory “/etc/NetworkManager/dispatcher.d”: Permission denied
Apr 06 19:28:12 cosa-devsh nm-dispatcher[1407]: req:8 'connectivity-change': find-scripts: Failed to open dispatcher directory '/etc/NetworkManager/dispatcher.d': Error opening directory “/etc/NetworkManager/dispatcher.d”: Permission denied
```

**System details**
 - Fedora CoreOS version: `36.20220325.1.0`

**Ignition config**

There is nothing Ignition specific about this.

**Additional information**

This is reported in:
- https://bugzilla.redhat.com/show_bug.cgi?id=2065940
- https://bugzilla.redhat.com/show_bug.cgi?id=2070042 (dup of 2065940)

**Comment by cgwalters** [comment]
Ah yeah, so https://github.com/coreos/coreos-assembler/pull/2067 would have caught this earlier.

**Comment by dustymabe** [comment]
> Ah yeah, so [coreos/coreos-assembler#2067](https://github.com/coreos/coreos-assembler/pull/2067) would have caught this earlier.

In theory, yes! We should try to push that PR forward.

Unfortunately this one case doesn't actually have any selinux denials in the logs. I think they're getting caught up in some dontaudit rules or something.

**Comment by dustymabe** [comment]
It looks like [a fix](https://github.com/fedora-selinux/selinux-policy/commit/f4febe421a8cd146a808718a8e4a4566f0368108) may be coming. Built for [rawhide](https://bodhi.fedoraproject.org/updates/FEDORA-2022-d58dd0841e), but not yet for Fedora 36.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `36.20220430.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
This never affected `testing` or `stable` streams.
