### ISSUE TITLE
tracker: This Month in Fedora CoreOS April 2022

### ISSUE THREAD

**Issue by cverna** [coreos/fedora-coreos-tracker#1157]
Please link or comment anything you would like to see in the next This Month in Fedora CoreOS edition

Link to the HackMD --> https://hackmd.io/fITa6rtNTy6Ub1WO4nkdnw?edit

**Comment by dustymabe** [comment]
removing varlink from next stream https://github.com/coreos/fedora-coreos-tracker/issues/1130

**Comment by prestist** [comment]
Making some last minute changes to pr for VirtualBox Documentation [here](https://github.com/coreos/fedora-coreos-docs/pull/377).

**Comment by cverna** [comment]
May tracker --> https://github.com/coreos/fedora-coreos-tracker/issues/1188

**Comment by cverna** [comment]
Pushed https://discussion.fedoraproject.org/t/this-month-in-fedora-coreos-april-2022/38809/2
