### ISSUE TITLE
exoscale: disk images fail to provision

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1160]
I'm doing some testing on `36.20220325.1.0` for the [Fedora CoreOS 36 Test Week](https://github.com/coreos/fedora-coreos-tracker/issues/1123). Trying to boot on Exoscale and it's not clear why initially. After grabbing the grub prompt and removing `console=ttyS0..` from the kernel arguments I'm able to see it thinks it's getting garbage back from the meta-data service.

It turns out the user-data is now gzip compressed.

Another wrinkle is that you can't boot the nodes without any config at all. The service replies to `http://169.254.169.254/1.0/user-data` with an empty file. We need to handle that in the code as well. I guess in the past if this was the case the metdata service wouldn't reply with not found or something.

----

Update in https://github.com/coreos/fedora-coreos-tracker/issues/1160#issuecomment-1097079722

**Comment by bgilbert** [comment]
> Another wrinkle is that you can't boot the nodes without any config at all. The service replies to `http://169.254.169.254/1.0/user-data` with an empty file. We need to handle that in the code as well. I guess in the past if this was the case the metdata service wouldn't reply with not found or something.

We do handle that in the code.  What error are you seeing in this case?

**Comment by dustymabe** [comment]
> > Another wrinkle is that you can't boot the nodes without any config at all. The service replies to `http://169.254.169.254/1.0/user-data` with an empty file. We need to handle that in the code as well. I guess in the past if this was the case the metdata service wouldn't reply with not found or something.
> 
> We do handle that in the code. What error are you seeing in this case?

More info over at https://github.com/coreos/ignition/pull/1345#discussion_r846548013

**Comment by bgilbert** [comment]
Okay, so you're saying we do handle this correctly now, but the gzip case adds additional complications?

**Comment by dustymabe** [comment]
> Okay, so you're saying we do handle empty configs correctly now, but the gzip case adds additional complications?

Maybe before they converted to compressed user-data it worked when there was an empty config. But certainly now it doesn't work. So I think the answer to your question is "yes".

I can do some more testing around this later and see if going back to non GZIP setting in FetchOptions allows it to work (If I remember correctly it still didn't work right).

**Comment by bgilbert** [comment]
As I understand it, you're seeing the metadata service provide compressed metadata if a config was provided, and provide zero-length metadata if no config was provided.  In that case, an unmodified FCOS image should correctly handle the no-config case, since no gzip is involved there.  If not, then our understanding is wrong, and we should track that down.  A console log would really help here.

**Comment by dustymabe** [comment]
> As I understand it, you're seeing the metadata service provide compressed metadata if a config was provided, and provide zero-length metadata if no config was provided. In that case, an unmodified FCOS image should correctly handle the no-config case, since no gzip is involved there.

Went back and tested. This is correct. With no config the current `next` image (`36.20220325.1.0`) comes up.

**Comment by dustymabe** [comment]
It turns out the compressed user-data only happens when using the `exo` CLI. When using the web UI the data isn't compressed.

**Comment by dustymabe** [comment]
For the record here is the error the user would see:

![Untitled](https://user-images.githubusercontent.com/4530030/163040961-c95b40d0-dda0-4471-bec2-42eb6b3b703f.png)

**Comment by dustymabe** [comment]
OK. The exoscale CLI has been updated to not compress by default https://github.com/exoscale/cli/pull/451 - Maybe we just update our docs to tell people not to use `--cloud-init-compress`.

**Comment by bgilbert** [comment]
Yes, and to use a suitable version of the CLI.

**Comment by dustymabe** [comment]
> The exoscale CLI has been updated to not compress by default [exoscale/cli#451](https://github.com/exoscale/cli/pull/451)

This landed in https://github.com/exoscale/cli/releases/tag/v1.54.0

**Comment by dustymabe** [comment]
docs update: https://github.com/coreos/fedora-coreos-docs/pull/401
