### ISSUE TITLE
develop strategy around organization and naming for our containers in quay.io

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1171]
We have a few:

Under [`coreos-assembler`](https://quay.io/organization/coreos-assembler) we have: 

- coreos-assembler/coreos-assembler
- coreos-assembler/fcos-buildroot
- coreos-assembler/fcos
- coreos-assembler/cosa-buildroot

Under [`coreos`](https://quay.io/organization/coreos) there are few we maintain:

- coreos/coreos-installer
- coreos/butane (and fcct)
- coreos/ignition-validate
- coreos/mkpasswd

And there is also the [`fedora`](https://quay.io/organization/fedora) organization.

We also have a new kubevirt container we're going to start uploading (see https://github.com/coreos/fedora-coreos-tracker/issues/1126).

Let's try to figure out what our desired strategy is for our organization and naming of our various container images related to Fedora CoreOS.

**Comment by bgilbert** [comment]
> coreos-assembler/fcos

I didn't realize that existed.  Yeah, that's awkward.  I think it makes sense to keep the upstream tools in `coreos`, but maybe move the FCOS distro repos to `fedora` or `fedora-coreos` if we can manage it.  `coreos` would also work (and we can get new repos easily) but might conflate things too much.

**Comment by bgilbert** [comment]
Actually, for the distro repos, registry.fedoraproject.org might make more sense.  We no longer use Quay's builders, so this wouldn't be a functionality loss.

**Comment by cgwalters** [comment]
> Actually, for the distro repos, registry.fedoraproject.org might make more sense.

I thought I saw some discussion of moving fedora stuff canonically to quay.io so...we should chat with the people who own that. 

xref https://pagure.io/releng/issue/10399

**Comment by jlebon** [comment]
> coreos-assembler/cosa-buildroot

We can delete this one. It's no longer used or updated after https://github.com/coreos/fedora-coreos-config/pull/740.

> coreos-assembler/fcos

This is pending ACLs to actually push to the `fedora` namespace instead (see https://github.com/coreos/fedora-coreos-pipeline/blob/600c1c185b9ea81b5e58c9d0951b6769ee628441/jobs/release.Jenkinsfile#L65).

> coreos-assembler/fcos-buildroot

Personally, I think this one would fit better under `coreos/` than under `fedora/`.

**Comment by travier** [comment]
From this week community meeting:

    AGREED: We have decided that we'll punt on long term strategy for
    coreos-assembler container location. We'll reach out to Fedora
    infra/releng to investigate long term strategy for what registry
    Fedora containers will be hosted in. For the kubevirt and ostree
    containers we'll host them wherever Fedora officially hosts its
    containers and name them `fedora-coreos-kubevirt` and  (dustymabe,
    17:17:08)

**Comment by travier** [comment]
ACTION: jaimelm and dustymabe to meet with the releng/infra team to
    talk about containers and where everything fits  (dustymabe,
    17:24:08)

@JaimeMagiera @dustymabe

**Comment by dustymabe** [comment]
@JaimeMagiera and I met with the relent team in [their meeting yesterday](https://meetbot.fedoraproject.org/teams/releng/releng.2022-04-26-15.00.log.html). We brought these data points back to our [FCOS meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/LC5Z32APYW5JRRXYSHNBWHOGCXP5AZAS/).

```
12:37:21  dustymabe    #info jaimelm and dustymabe met with Fedora releng/infra
                       to discuss forward strategy for Fedora container hosting.
                       The goal is to get off of their own infra and onto quay.io
                       (https://pagure.io/fedora-infrastructure/issue/10386), though
                       they have some open questions about if flatpaks can be hosted
                       there.


12:37:38  dustymabe    #info We are going to all work together over the next week to
                       try to chase down any open questions and then move forward with
                       putting our FCOS containers in quay.io if no blockers are found.


12:37:49  dustymabe    #info This will lead Fedora's transition to quay.io by some months,
                       but the releng/infra team feels it's best if we start there for new
                       containers rather than go to the old infra right before a transition.
```


This means that (pending some investigation about feasibility of flatpaks being hosted in quay.io) we should be able to use quay for our "fedora" containers:

- `quay.io/fedora/fedora-coreos-kubevirt`
- `quay.io/fedora/fedora-coreos`

This is the case even if the rest of Fedora hasn't moved there yet, as the plan is to get them over there in the coming cycle.

**Comment by JaimeMagiera** [comment]
Reached out to Owen Taylor for info on flatpak support in quay.io. Owen has responded...
https://pagure.io/fedora-infrastructure/issue/10386

**Comment by dustymabe** [comment]
We discussed this during the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/GZRSIQKCRYV4DC7YEO4H2CE3NFE44Z7W/).

```
12:50:32   dustymabe | #action dustymabe jaimelm to reach out to fedora infra about creds for
                     | pushing to `quay.io/fedora/fedora-coreos` and `quay.io/fedora/fedora-coreos-kubevirt`. 

```

**Comment by dustymabe** [comment]
Request for credentials to push to quay.io in https://pagure.io/fedora-infrastructure/issue/10702

**Comment by cverna** [comment]
I have created the repository and credentials, let me know if something else is needed.

**Comment by dustymabe** [comment]
This should get taken care of by https://github.com/coreos/fedora-coreos-pipeline/pull/630

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20220918.1.1`.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220918.2.2`.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `36.20220906.3.2`.
