### ISSUE TITLE
change group ownership of podman binary in base ostree

### ISSUE THREAD

**Issue by millerthegorilla** [coreos/fedora-coreos-tracker#1173]
**Describe the enhancement**
Currently the podman binary at ```/usr/bin/podman``` is owned by root, with group root and 0755 perms.  Following [this article](https://www.redhat.com/sysadmin/controlling-access-rootless-podman-users) I note that it is possible to change the ownership of the podman binary to allow it to be locked to specific users, ie those in the podman group.
On coreos it is very difficult/impossible to change the group/perms etc of the podman binary, so I wonder if it could be changed by the maintainers, such that the podman binary has the 'podman' group as per the article, and 'world' permissions are removed.

**System details**
 - Bare Metal  aarch64
 - Fedora CoreOS version  35

**Additional information**
Add any other information here.

**Comment by dustymabe** [comment]
> I wonder if it could be changed by the maintainers, such that the podman binary has the 'podman' group as per the article, and 'world' permissions are removed.

I doubt we'd be able to make this change because everyone relying on the current behavior would now be broken. In the article it does state:

> Running unprivileged containers is safe and can't really affect the system any more than just having a login on the system.

So really this change isn't improving your security.

They also state in the article: 

> Just realize that when Podman gets updated, you will need to do the chmod and chown commands again, and rpm -qV podman will report issues with the install.

Basically, this isn't a change the RPM maintainers are willing to make (because of the aforementioned breaking change), so we shouldn't really make that change by default in FCOS either.

In the future you might be able to use CoreOS layering for something like this to provide yourself a customized distro.

**Comment by travier** [comment]
You should be able to make an RPM with a dependency on podman with a post script doing that change and then overlay it.

But let's take a step back: What do you really want to achieve here? If a user wants to run the podman binary unprivileged, it can also just copy the binary into its home dir and run it.

**Comment by cgwalters** [comment]
> If a user wants to run the podman binary unprivileged, it can also just copy the binary into its home dir and run it.

Right, that blog entry is simply giving useless advise.  

The biggest change in Linux was the introduction of unprivileged user namespaces.  If you truly want to, you can use [these sysctls](https://www.kernel.org/doc/html/latest/admin-guide/sysctl/user.html) to restrict the namespaces that unprivileged code may use:

```
[root@cosa-devsh ~]# cat /proc/sys/user/max_user_namespaces 
3466
[root@cosa-devsh ~]# echo 0 > /proc/sys/user/max_user_namespaces 
[root@cosa-devsh ~]# su - core
Last login: Tue Apr 19 14:31:49 UTC 2022 from 10.0.2.2 on pts/0
[core@cosa-devsh ~]$ id
uid=1000(core) gid=1000(core) groups=1000(core),4(adm),10(wheel),16(sudo),190(systemd-journal) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[core@cosa-devsh ~]$ podman run --rm -ti busybox echo hello
cannot clone: No space left on device
user namespaces are not enabled in /proc/sys/user/max_user_namespaces
Error: cannot re-exec process
[core@cosa-devsh ~]$ 
```

However...be aware that some unprivileged code may actually use container features like namespaces for internal isolation, and doing this may actually break that.

**Comment by dustymabe** [comment]
> > If a user wants to run the podman binary unprivileged, it can also just copy the binary into its home dir and run it.
> 
> Right, that blog entry is simply giving useless advise.

yep. At least it did call it out as useless advice :) 

Would it be more useful to add your `max_user_namespaces` example to the blog (if we tracked down the author)?

**Comment by millerthegorilla** [comment]
I am using coreos, so I will have to learn how to overlay a customised package.
I am running a django site using containers, and I have a set of scripts that provision the site from a sudo enabled account, that use runuser to interface with the limited user account in order to create the podman containers and pod.
When I realised that the podman binary has world execution permissions, I realised there is little point in my scripts being in a super user account.
However, if I could lockdown the podman binary when I don't need to use it, then it would limit the possibility that someone might gain access to the limited account and do malicious things to my pod and containers.
The pod and containers have associated systemd units running in the user 'namespace', so I guess there is hardly any point in bothering about the podman binary, as systemctl --user stop/start/ etc can be used by the limited user.  I did try using a service account, but it had complications, from memory, it was some time ago.
I wonder if there is any way of securing a rootless podman install in the way that I wanted to.
I thought if the podman binary had a podman group, then you could simply add your user to the group.

**Comment by millerthegorilla** [comment]
I will have to look at kubernetes, if that offers a better mechanism such as rpc.
