### ISSUE TITLE
Migrate infra containers to new Fedora openshift cluster

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1174]
Fedora infra is moving to a new OCP 4 cluster. Our apps that need to be migrated are:

- [x] coreos-koji-tagger
    - https://pagure.io/fedora-infra/ansible/pull-request/1034
- [x] coreos-ostree-importer
    - https://pagure.io/fedora-infra/ansible/pull-request/1038
- [x] fedora-ostree-pruner
    - https://pagure.io/fedora-infra/ansible/pull-request/1038 
- [ ] ~~coreos-cincinnati~~ -> https://github.com/coreos/fedora-coreos-tracker/issues/1181

I can try to move the first 3. Maybe @lucab can help with the last one.

**Comment by lucab** [comment]
Yes I can help assisting with the Cincinnati move, but I haven't seen yet the details about this new cluster. In general from our side there is just a deployment to be duplicated there, but the rest of the infra (DNS, routers, certs, etc) needs to be set up for us beforehand.

**Comment by dustymabe** [comment]
The first three are migrated to the new cluster, brought down on the old cluster and the docs updated:

- https://pagure.io/fedora-infra/ansible/pull-request/1034
- https://pagure.io/fedora-infra/ansible/pull-request/1038
- https://github.com/coreos/fedora-coreos-releng-automation/pull/151

**Comment by dustymabe** [comment]
Broke out `coreos-cincinnati` into https://github.com/coreos/fedora-coreos-tracker/issues/1181
