### ISSUE TITLE
tracker: This Month in Fedora CoreOS May 2022

### ISSUE THREAD

**Issue by cverna** [coreos/fedora-coreos-tracker#1188]
Please link or comment anything you would like to see in the next This Month in Fedora CoreOS edition

Link to the HackMD --> https://hackmd.io/fITa6rtNTy6Ub1WO4nkdnw?edit

**Comment by dustymabe** [comment]
Looks like we're finally going to get around to fixing the selinux policy updates issue: https://github.com/coreos/fedora-coreos-tracker/issues/701

**Comment by dustymabe** [comment]
Some things we came up with in [the meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/GZRSIQKCRYV4DC7YEO4H2CE3NFE44Z7W/):

- New Ignition release [v2.14.0](https://github.com/coreos/ignition/releases/tag/v2.14.0)
    - Fixes an issue where some systemd units [couldn't be disabled](https://github.com/coreos/fedora-coreos-tracker/issues/392).#392
    - Delete userdata after provisioning on VirtualBox and VMware
- Added aarch64 support for `ignition-validate` container in quay.io
- Support for kubevirt (we need to push this over the finish line)
- `coreos-assembler` has been moved to F36
- All FCOS streams have been moved to Fedora 36 (will happen before the end of the month)
    - https://discussion.fedoraproject.org/t/fedora-coreos-streams-rebasing-to-fedora-linux-36/38955

**Comment by dustymabe** [comment]
@lucab had a few related to ostree/rpm-ostree he wanted to add too.

**Comment by lucab** [comment]
* rpm-ostree [v2022.9](https://github.com/coreos/rpm-ostree/releases/tag/v2022.9):
  * (compose) Add support for propagating RPM IMA signatures
  * (container) Support `yum install foo`
  * (container) Support `override replace` and `override remove`

**Comment by bgilbert** [comment]
- [Format change](https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/message/SZAD4FBCJFHDV3SSOLOXR4RUXRWGJN56/) for Nutanix artifact
- Added [Nutanix documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-nutanix/)
- Ignition configs are [now deleted](https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/message/M3EQHFIF2XXTZRVDDWHBZW3OHIHHP2GC/) from VMware and VirtualBox hypervisors after provisioning is complete

**Comment by cverna** [comment]
https://discussion.fedoraproject.org/t/this-month-in-fedora-coreos-may-2022/39942
