### ISSUE TITLE
use internal qcow2 compression for nutanix image

### ISSUE THREAD

**Issue by vnephologist** [coreos/fedora-coreos-tracker#1191]
# Feature Request #
support qemu-img "-c" option for compressing qcow2 images for nutanix platform
## Desired Feature ##
We would like to add functionality to natively compress Nutanix qcow2 using the "-c" compress option rather than gzip them. This functionality would support the ability of the OpenShift installer to orchestrate the Nutanix Image Service to directly download and import the qcow2 rather than having the installer locally unzip then upload an uncompressed image. 
## Example Usage ##
`coreos-assembler buildextend-nutanix --compress`
## Other Information ##
We need to coordinate this change with OpenShift installer functionality so it would be helpful to temporarily build both compressed qcow2 and gzip'd qcow2 artifacts.

**Comment by bgilbert** [comment]
I concur that we should verify there are no performance impacts.  Another alternative is simply to skip compressing the artifact altogether.

**Comment by vnephologist** [comment]
> I concur that we should verify there are no performance impacts. Another alternative is simply to skip compressing the artifact altogether.

I am confirming with our core virt/storage team on the performance aspect. 

We would definitely want to skip the gzip compression for the resulting artifact.

**Comment by thunderboltsid** [comment]
I think we should skip compressing the artifact with `gzip` for now and we can late-bind on the qcow2 compression once we've verified the performance aspects.

**Comment by bgilbert** [comment]
Note that we can't stop shipping the compressed artifact (at least without a deprecation period), since that would break anyone using it.  We'll need to add a new one.

**Comment by vnephologist** [comment]
> Note that we can't stop shipping the compressed artifact (at least without a deprecation period), since that would break anyone using it.  We'll need to add a new one.

That's fine. Just note that these images are not yet GA'd from OpenShift perspective anyway. We are planning GA in 4.11.

**Comment by bgilbert** [comment]
> Just note that these images are not yet GA'd from OpenShift perspective anyway. We are planning GA in 4.11.

They're shipping in Fedora CoreOS though.

**Comment by vnephologist** [comment]
I have confirmed that there is no performance impact with compression. Our image service converts all qcow2 images to raw for deployed VMs.

**Comment by thunderboltsid** [comment]
> Maybe the best place to make a change like this would be:
> 
> https://github.com/coreos/coreos-assembler/blob/0fd89554a1921ddc124c142daca83445e4699f05/src/cosalib/qemuvariants.py#L114-L117

Would something like this be sufficient here?
```
"nutanix": {
        "image_format": "qcow2",
        "platform": "nutanix",
        "convert_options": {
            '-c': ''
        }
    },
```

**Comment by thunderboltsid** [comment]
> I'm trying to figure out how do the images assembled from the assembler end up as an artifact in https://github.com/openshift/installer/blob/master/data/data/coreos/rhcos.json#L489-L500

Looking at the [past git commits](https://github.com/openshift/installer/commit/e9b2e1b8658cf415fd7004368fe3b40a07f5efa6), these changes to the contents of the `rhcos.json` file are generated using `plume`.

**Comment by miabbott** [comment]
> Looking at the [nutanix variant](https://github.com/coreos/coreos-assembler/blob/0fd89554a1921ddc124c142daca83445e4699f05/src/cosalib/qemuvariants.py#L102-L105), it doesn't specify compression anywhere. So, the actual compression of the artifact is happening elsewhere (explicit `--compress` flag when running the command?). If so, can you point me to the script?

We do the compression of the artifacts in the RHCOS build pipeline as a separate stage, where we just call `cosa compress`

https://github.com/coreos/coreos-assembler/blob/main/src/cmd-compress

**Comment by thunderboltsid** [comment]
> > Looking at the [nutanix variant](https://github.com/coreos/coreos-assembler/blob/0fd89554a1921ddc124c142daca83445e4699f05/src/cosalib/qemuvariants.py#L102-L105), it doesn't specify compression anywhere. So, the actual compression of the artifact is happening elsewhere (explicit `--compress` flag when running the command?). If so, can you point me to the script?
> 
> We do the compression of the artifacts in the RHCOS build pipeline as a separate stage, where we just call `cosa compress`
> 
> https://github.com/coreos/coreos-assembler/blob/main/src/cmd-compress

@miabbott Can we, as part of the RHCOS build pipeline, upload a non-gzipped variant along with the current gzipped variant.

**Comment by thunderboltsid** [comment]
> > @miabbott Can we, as part of the RHCOS build pipeline, upload a non-gzipped variant along with the current gzipped variant.
> 
> It's possible, though I think we'll need to define a new artifact as noted here [#1191 (comment)](https://github.com/coreos/fedora-coreos-tracker/issues/1191#issuecomment-1117814392)

Yeah, we're fine with a new artifact. So, what do we need to do to make that happen?

**Comment by miabbott** [comment]
> Yeah, we're fine with a new artifact. So, what do we need to do to make that happen?

There's a WIP checklist that covers some of it - https://github.com/coreos/fedora-coreos-tracker/pull/1170

Introducing a new artifact is not trivial, so I would be prepared for a lot of back and forth.

**Comment by bgilbert** [comment]
I think there might be a problem with introducing a new artifact in this case.  In stream metadata, we'd have both `qcow2.xz` and `qcow2` formats, which is okay.  In `meta.json`, we can have distinct lookup keys for the QCOWs with and without internal compression.  But in the filesystem itself, both images would have the same name, `fedora-coreos-$ver-nutanix.x86_64.qcow2`, until `cmd-compress` runs.

Considering this some more, I now think we shouldn't add a new artifact.  The technical hurdles to introducing one aren't trivial, and I'm guessing there aren't many FCOS users who've started using the existing one.  And if we carry a second artifact, there's the implication that we'll continue doing so for the long term.  So instead, I think we should announce a short deprecation period on coreos-status and just switch over.

**Comment by cgwalters** [comment]
Agree with :arrow_up: - being compatible where possible is important, but I think this case doesn't quite warrant it.

(I do think longer term though Nutanix and other platforms ideally learns how to accept e.g. kubevirt-style containerdisks natively instead)

**Comment by travier** [comment]
From this week's [meeting](https://meetbot.fedoraproject.org/fedora-meeting-1/2022-05-11/fedora_coreos_meeting.2022-05-11-16.32.html):

```
  * AGREED: We will switch the Nutanix artifacts to an internally
    compressed qcow2 image for the next cycle for testing & next and the
    following one for stable. This breaking change will be announced
    ASAP.  (travier, 17:33:45)
```

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220522.2.1`. Please try out the new release and report issues.
