### ISSUE TITLE
Keep/Remove Python dependent package: bind-utils

### ISSUE THREAD

**Issue by sinnykumari** [coreos/fedora-coreos-tracker#120]
FCOS community members are trying [not to ship Python]( https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#approach-towards-shipping-Python) in base system. In ticket https://github.com/coreos/fedora-coreos-tracker/issues/92, we have identified list of Python dependent packages which are currently installed in FCOS.

This ticket is to investigate that  do we really need `bind-utils` in FCOS base system? If yes, how can we provide `bind-utils` or equivalent functionalities without shipping Python.

**Comment by sinnykumari** [comment]
RFE to split python utilities to their own binary package - https://bugzilla.redhat.com/show_bug.cgi?id=1649398

**Comment by sinnykumari** [comment]
Latest bind-utils-9.11.5-8.P1.fc30 available in [Fedora 30](https://src.fedoraproject.org/rpms/bind/c/2830e00b88ea8bb956e0cdeb6f205fc72741b167?branch=master) doesn't contain Python dependent utilities.

With this change, all dnssec related utilities including Python utilites has been moved to a new sub-package `bind-dnssec-utils` .

As a result, `bind-utils-9.11.5-8.P1.fc30` (python independent ) contains now following utilities:
```
/etc/trusted-key.key (config)
/usr/bin/arpaname
/usr/bin/delv
/usr/bin/dig
/usr/bin/host
/usr/bin/nslookup
/usr/bin/nsupdate
```

And `bind-dnssec-utils-9.11.5-8.P1.fc30.x86_64.rpm` (Python dependent)
```
/usr/sbin/ddns-confgen
/usr/sbin/dnssec-checkds (Python utility)
/usr/sbin/dnssec-coverage ((Python utility))
/usr/sbin/dnssec-dsfromkey
/usr/sbin/dnssec-importkey
/usr/sbin/dnssec-keyfromlabel
/usr/sbin/dnssec-keygen
/usr/sbin/dnssec-keymgr (Python utility)
/usr/sbin/dnssec-revoke
/usr/sbin/dnssec-settime
/usr/sbin/dnssec-signzone
/usr/sbin/dnssec-verify
/usr/sbin/genrandom
/usr/sbin/isc-hmac-fixup
/usr/sbin/named-checkzone
/usr/sbin/named-compilezone
/usr/sbin/nsec3hash
/usr/sbin/tsig-keygen
```
Does utilities available in bind-utils-9.11.5-8.P1.fc30` looks sufficient for FCOS?

**Comment by sinnykumari** [comment]
Maybe we can get this discussed in today's FCOS community meeting.

**Comment by dustymabe** [comment]
Discussed in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/77ET7IPYB6IZ7ODF2GACID6DF4UEX46V/).

We agreed on the following statement:

```
AGREED: we will try to ship just bind-utils without 
bind-dnssec-utils (python deps) and see if we hit any roadblocks
```

**Comment by dustymabe** [comment]
@sinnykumari - what are the remaining items to do here?

**Comment by sinnykumari** [comment]
> @sinnykumari - what are the remaining items to do here?

Considering we all agreed to go with just bind-utils package and see how it goes, there is no remaining action item. bind-utils is already added in https://github.com/coreos/fedora-coreos-config/blob/master/fedora-coreos-base.yaml#L202. When we will start building FCOS based on F30 content, python dependencies from bind-utils should go away.

**Comment by sinnykumari** [comment]
If there is no objection, we can close this ticket.

**Comment by lucab** [comment]
@sinnykumari for my own knowledge, do we have to specify something in the treefile to opt-out from ` Suggests: bind-dnssec-utils` or is that happening by default?

**Comment by sinnykumari** [comment]
I don't think we need to specify anything additionally. Packages specified as suggest in rpm spec are not installed by default as package dependencies but considered as a hint providing additional functionalities. https://docs.fedoraproject.org/en-US/packaging-guidelines/WeakDependencies/ explains more .

**Comment by dustymabe** [comment]
related: https://github.com/projectatomic/rpm-ostree/commit/40be3fb1cf066389564bd99954ab45089d0bf884

we may need to add `recommends: false` to our treefile

**Comment by dustymabe** [comment]
actually i always get confused between recommends and suggests so maybe we don't need to do anything.

**Comment by sinnykumari** [comment]
Closing this as fixed.
