### ISSUE TITLE
KubeCon North America 2022 proposals

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#1203]
KubeCon North Americal is being held in Detroit, Michigan USA from Oct 24-28, 2022

https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/

The CFP for closes on Friday May 27

https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/cfp/

Please add a comment on this ticket for any talk proposals/ideas that you have for the conference.

We can utilize the help of the Open Source Program Office at Red Hat to help craft a compelling proposal, but we need to get them involved ASAP as time is running short.

**Comment by marrusl** [comment]
Submitting this one tomorrow, most likely (already run through the program office -- highly recommended, great feedback!):
https://docs.google.com/document/d/1lY-cnpBKgA_LFm7REeIiYcHfxdmptO4-oy-RGjiCXgA/edit

**Comment by miabbott** [comment]
If anyone submits a talk to KubeCon NA and it gets rejected, consider submitting it to the Rejekts conference - https://cloud-native.rejekts.io/

Cloud Native Rejekts NA - October 22-23, 2022 | Detroit, USA

**Comment by dustymabe** [comment]
CFP is closed now.
