### ISSUE TITLE
kola: s390x: multipath.day2 test fails

### ISSUE THREAD

**Issue by LakshmiRavichandran1** [coreos/fedora-coreos-tracker#1206]
# Bug Report #
on May 20 11:01:04 CEST 2022 with build fedora-coreos-36.20220518.dev.0-qemu.s390x.qcow2

```
$ cosa kola run --rerun --parallel 4 --output-dir tmp/kola
...
--- FAIL: multipath.day2 (39.20s)
```

## Environment ##

What operating system is being used to run coreos-assembler?

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
```

What operating system is being assembled?
fedora-coreos

Is coreos-assembler running in Podman or Docker?
podman

If Podman, is coreos-assembler running privileged or unprivileged?
as a non-root user

## Expected Behavior ##
multipath.day2 test should pass

## Actual Behavior ##
multipath.day2 test fails
## Reproduction Steps ##

  1. bring up a s390x KVM lpar, prepare a non-root user, do cosa fetch, cosa build as per docs
  2. run 'cosa kola run --rerun --parallel 4 --output-dir tmp/kola' and see the test fail

## Other Information ##
[console.txt](https://github.com/coreos/coreos-assembler/files/8738208/console.txt)
[journal.txt](https://github.com/coreos/coreos-assembler/files/8738215/journal.txt)

**Comment by jschintag** [comment]
Looking though the console log, i think the issue might be that rpm-ostree did not call zipl, since after the reboot the kernel arguments are not present, likely causing the problem.
However running it with the latest `testing-devel` build `37.20230205.20.0`, the test passes.
```
[coreos-assembler]$ cosa kola run --build 37.20230205.20.0 multipath.day2
kola -p qemu-unpriv --build 37.20230205.20.0 --output-dir tmp/kola run multipath.day2
_  Skipping kola test pattern "fcos.internet":
  __ https://github.com/coreos/coreos-assembler/pull/1478
_  Skipping kola test pattern "podman.workflow":
  __ https://github.com/coreos/coreos-assembler/pull/1478
_  Skipping kola test pattern "ext.config.ignition.resource.remote":
  __ https://github.com/coreos/fedora-coreos-tracker/issues/1215
_  Skipping kola test pattern "rpmostree.install-uninstall":
  __ https://github.com/coreos/fedora-coreos-tracker/issues/1215
__ Snoozing kola test pattern "ext.config.platforms.aws.nvme" until Feb 10 2023:
  __ https://github.com/coreos/fedora-coreos-tracker/issues/1306#issuecomment-1378864963
=== RUN   multipath.day2
--- PASS: multipath.day2 (47.54s)
PASS, output in tmp/kola
```
So i will test the streams and cautiously re-enable the test.

@nikita-dubrovskii I think we fixed/updated `rpm-ostree` at some point right? Likely that fixed the problem.

**Comment by nikita-dubrovskii** [comment]
yes, that's [fixed](https://github.com/ostreedev/ostree/pull/2614). Without SE-keys  non-SE s390x KVM guests used to fail:
```
May 20 07:59:38.335545 ostree[992]: error: ostree-finalize-staged.service failed on previous boot: Final bootloader swap: s390x SE: looking for SE keys: opendir(/etc/se-hostkeys/): No such file or directory
```
