### ISSUE TITLE
Keep/Remove Python dependent package: nfs-utils

### ISSUE THREAD

**Issue by sinnykumari** [coreos/fedora-coreos-tracker#121]
FCOS community members are trying [not to ship Python]( https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#approach-towards-shipping-Python) in base system. In ticket https://github.com/coreos/fedora-coreos-tracker/issues/92, we have identified list of Python dependent packages which are currently installed in FCOS.

This ticket is to investigate that  do we really need `nfs-utils` in FCOS base system? If yes, how can we provide `nfs-utils` or equivalent functionalities without shipping Python.

**Comment by bgilbert** [comment]
`nfs-utils-2.3.3-1.rc1.fc29.x86_64` contains two Python scripts: `/usr/sbin/mountstats` and `/usr/sbin/nfsiostat`.  Perhaps they could be broken out into a subpackage.

**Comment by bgilbert** [comment]
@sinnykumari You probably shouldn't wait for me.  :slightly_smiling_face:

**Comment by sinnykumari** [comment]
RFE bug to make separate sub-package for Python utilities - https://bugzilla.redhat.com/show_bug.cgi?id=1667889

**Comment by sinnykumari** [comment]
Latest nfs-utils package available in F30 includes a Python script [nfsconvert.py](https://fedoraproject.org/wiki/Changes/nfs.conf) which is required to convert deprecated  sysconfig/nfs configuration into /etc/nfs.conf .
From the related [nfs-utils bug](https://bugzilla.redhat.com/show_bug.cgi?id=1667889#c6), so far feasible option is to rewrite nfsconvert.py script into any compile language.
@dustymabe @cgwalters @bgilbert Have any better suggestion about [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1667889#c6) ? I am not sure that it is feasible to ship FCOS without nfs-utils.

**Comment by dustymabe** [comment]
thanks @sinnykumari - we can talk about this in the next meeting.

**Comment by dustymabe** [comment]
We chatted about this in the [community meeting yesterday](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2019-02-06-16.30.html) and we decided to accept the proposal to make a nfs-utils-coreos package.

There are still conversations going on in the BZ exploring possibilities, but in general a new package is acceptable.

**Comment by dustymabe** [comment]
Update from [BZ discussion](https://bugzilla.redhat.com/show_bug.cgi?id=1667889#c18):

The nfs team created a nfs-utils-coreos package for us that just contains the nfs client. My action item is to find out if FCOS needs to ship the server or is just the client OK?

Other open questions from the BZ: 

- if it is ok for FCOS to ship just the client would the package be
  useful to anyone else other than FCOS? If so then maybe renaming it
  to nfs-client-utils and splitting the server out to a separate package
  as well would be useful so that other people may use it

**Comment by dustymabe** [comment]
Discussed in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/77ET7IPYB6IZ7ODF2GACID6DF4UEX46V/).

We agreed on the following statement:

```
AGREED: we think shipping only the nfs client will suffice
    considering users can run nfs server in a container 
```

**Comment by dustymabe** [comment]
FYI f30 and f31 rpm builds with nfs-utils-coreos rpm in them:

> https://koji.fedoraproject.org/koji/taskinfo?taskID=32925998
> 
> https://koji.fedoraproject.org/koji/taskinfo?taskID=32926002

**Comment by ajeddeloh** [comment]
closed via https://github.com/coreos/fedora-coreos-config/pull/84

**Comment by remoe** [comment]
@dustymabe , the predecessor of FCOS has NFS server included :/ Does anyone know a "stable" NFS-server container for FCOS?

**Comment by dustymabe** [comment]
I don't know of one off hand. Anyone else?

**Comment by jlebon** [comment]
This might fall under #401.

**Comment by remoe** [comment]
Here is a nfs-server contribution :) I've tried https://github.com/ehough/docker-nfs-server . The fcct:

```yaml
variant: fcos
version: 1.0.0 
storage:
  files:
    - path: /etc/modules-load.d/nfs.conf
      mode: 0660
      contents:
        inline: |
          nfs
          nfsd
systemd:
  units: 
    - name: rpcbind.service
      enabled: true
    - name: rpc-statd.service
      enabled: true
    - name: nfs-server.service
      enabled: true
      contents: |
        [Unit]
        Description=NFS Server
        After=network-online.target
        Wants=network-online.target

        [Service]
        Environment=REGISTRY_AUTH_FILE=<your path>/.docker/config.json
        TimeoutStartSec=0
        ExecStartPre=-/bin/podman kill nfs-server
        ExecStartPre=-/bin/podman rm nfs-server
        ExecStartPre=/bin/podman pull <your repos>
        ExecStart=/bin/podman run --detach --rm --name nfs-server \
          --cap-add SYS_ADMIN --cap-add SYS_MODULE \
          -e NFS_LOG_LEVEL=DEBUG \
          ${data_volume_mounts} -v ${exports_file}:/etc/exports:Z -v /lib/modules:/lib/modules:ro --security-opt label=disable \
          <your repos>
        KillMode=none
        Type=simple
        [Install]
        WantedBy=multi-user.target
```
data_volume_mounts, exports_file, ```<your repos>``` and ```<your path>``` must be replaced with your settings.

**Comment by kai-uwe-rommel** [comment]
I think that FCOS should have a NFS server included in its base package.

**Comment by diabl0w** [comment]
> Here is a nfs-server contribution :) I've tried https://github.com/ehough/docker-nfs-server . The fcct for nfsv4:
> 
> ```yaml
> variant: fcos
> version: 1.0.0 
> storage:
>   files:
>     - path: /etc/modules-load.d/nfs.conf
>       mode: 0660
>       contents:
>         inline: |
>           nfs
>           nfsd
> systemd:
>   units: 
>     - name: nfs-server.service
>       enabled: true
>       contents: |
>         [Unit]
>         Description=NFS Server
>         After=network-online.target
>         Wants=network-online.target
> 
>         [Service]
>         Environment=REGISTRY_AUTH_FILE=<your path>/.docker/config.json
>         TimeoutStartSec=0
>         ExecStartPre=-/bin/podman kill nfs-server
>         ExecStartPre=-/bin/podman rm nfs-server
>         ExecStartPre=/bin/podman pull <your repos>
>         ExecStart=/bin/podman run --rm --name nfs-server \
>           --cap-add SYS_ADMIN --cap-add SYS_MODULE \
>           -e NFS_LOG_LEVEL=DEBUG \
>           -p 2049:2049 \
>           ${data_volume_mounts} -v ${exports_file}:/etc/exports:Z -v /lib/modules:/lib/modules:ro --security-opt label=disable \
>           <your repos>
>         KillMode=none
>         Type=simple
>         [Install]
>         WantedBy=multi-user.target
> ```
> 
> data_volume_mounts, exports_file, `<your repos>` and `<your path>` must be replaced with your settings.

this is going to be maintained by the FCOS team?

**Comment by LorbusChris** [comment]
@diabl0w I think this is a good candidate for inclusion in the docs. However we cannot support container images that are not built in the Fedora ecosystem. If you can come up with a working fedora-container based Dockerfile, I'm happy to help you get it into Fedora's container registry.

**Comment by diabl0w** [comment]
> @diabl0w I think this is a good candidate for inclusion in the docs. However we cannot support container images that are not built in the Fedora ecosystem. If you can come up with a working fedora-container based Dockerfile, I'm happy to help you get it into Fedora's container registry.

Thanks for the response, unfortunately I am not qualified to be doing that, haha. I've been just following the rabbit hole of a few issues being linked to running an nfs server inside coreos. It seems like the only solution for now is running a 3rd party container, until the nfs-server nfs-client rpms get sorted out.
