### ISSUE TITLE
SELinux prevents usage of NetworkManager dispatcher scripts

### ISSUE THREAD

**Issue by PhrozenByte** [coreos/fedora-coreos-tracker#1218]
**Describe the bug**
SELinux prevents me from using NetworkManager dispatcher scripts by blocking the execution of other binaries.

**Reproduction steps**
1. Create `/etc/NetworkManager/dispatcher.d/60-test.sh` with the following contents and make it executable (`chmod +x /etc/NetworkManager/dispatcher.d/60-test.sh`):
    ```sh
    #!/bin/bash
    if [ "$1" != "enp1s0" ] || [ "$2" != "up" ]; then exit 0; fi
    echo "Hello World" | /usr/bin/tee /home/core/nm-dispatcher-test
    ```
3. Reboot the system.
4. Check whether `/home/core/nm-dispatcher-test` was created. It was not. Check the audit logs and the logs of `NetworkManager-dispatcher.service`.

**Expected behavior**
NetworkManager dispatcher scripts should be able to call binaries in `/usr/bin` and `/usr/sbin` (and anything else one can expect from a NetworkManager dispatcher script), and therefore `/home/core/nm-dispatcher-test` should exist.

**Actual behavior**
SELinux prevents executing binaries in `/usr/bin` and `/usr/sbin`, and thus `/home/core/nm-dispatcher-test` doesn't exist.

```
Jun 04 18:27:47 CoreOS audit[1515]: AVC avc:  denied  { read } for  pid=1515 comm="tee" name="home" dev="sda4" ino=2117776 scontext=system_u:system_r:NetworkManager_dispatcher_t:s0 tcontext=system_u:object_r:home_root_t:s0 tclass=lnk_file permissive=0
Jun 04 18:27:47 CoreOS audit[1515]: SYSCALL arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=7fff0f76dcb4 a2=241 a3=1b6 items=0 ppid=1513 pid=1515 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="tee" exe="/usr/bin/tee" subj=system_u:system_r:NetworkManager_dispatcher_t:s0 key=(null)
Jun 04 18:27:47 CoreOS audit: PROCTITLE proctitle=2F7573722F62696E2F746565002F686F6D652F636F72652F6E6D2D646973706174636865722D74657374
Jun 04 18:27:47 CoreOS nm-dispatcher[1515]: /usr/bin/tee: /home/core/nm-dispatcher-test: Permission denied
Jun 04 18:27:47 CoreOS nm-dispatcher[1515]: Hello World
Jun 04 18:27:47 CoreOS nm-dispatcher[1050]: req:6 'up' [enp1s0], "/etc/NetworkManager/dispatcher.d/60-test.sh": complete: failed with Script '/etc/NetworkManager/dispatcher.d/60-test.sh' exited with status 1.
```

**System details**
 - Bare Metal
 - Fedora CoreOS 36.20220505.3.2

**Comment by dustymabe** [comment]
There were several issues with NM dispatcher scripts and SELinux in the move to Fedora 36 (see https://github.com/coreos/fedora-coreos-tracker/issues/1153). 

For user defined dispatchers it should be fixed in the next `testing` stream release in the coming week. See https://bugzilla.redhat.com/show_bug.cgi?id=2088944

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220605.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `36.20220605.3.0`.
