### ISSUE TITLE
Keep/Remove Python dependent package: authconfig

### ISSUE THREAD

**Issue by sinnykumari** [coreos/fedora-coreos-tracker#123]
FCOS community members are trying [not to ship Python]( https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#approach-towards-shipping-Python) in base system. In ticket https://github.com/coreos/fedora-coreos-tracker/issues/92, we have identified list of Python dependent packages which are currently installed in FCOS.

This ticket is to investigate that  do we really need `authconfig` in FCOS base system? If yes, how can we provide `authconfig` or equivalent functionalities without shipping Python.

**Comment by sinnykumari** [comment]
Related Comments from #92 

@LorbusChris 
> Again re: replacing authconfig with authselect: Seems authselect only needs Python for the authselect-compat pkg for compatibility with authconfig (https://src.fedoraproject.org/rpms/authselect/blob/master/f/authselect.spec#_176).
> 
> Has anybody here used authselect and has some experience with it?

@jlebon 
> 
> Yeah, there's some history there: [pbrezina/authselect#48](https://github.com/pbrezina/authselect/issues/48). Basically, we've held back migrating to authselect in FAH because of conflicts over `nsswitch.conf`.

**Comment by dustymabe** [comment]
Discussed in the [meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/SFZMGRJHFABUA7WFS4SWJMASHQFU3BLK/) this past wednesday:

```
AGREED: we will try to go without authconfig/authselect and also try
    to raise the awareness of this move to get feedback from potential
    users #123  (dustymabe, 16:54:53)
```

**Comment by ajeddeloh** [comment]
closed via https://github.com/coreos/fedora-coreos-config/pull/84
