### ISSUE TITLE
tracker: This Month in Fedora CoreOS June 2022

### ISSUE THREAD

**Issue by cverna** [coreos/fedora-coreos-tracker#1234]
Please link or comment anything you would like to see in the next This Month in Fedora CoreOS edition

Link to the HackMD --> https://hackmd.io/fITa6rtNTy6Ub1WO4nkdnw?edit

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-tracker/issues/1085
    - Shipped on `testing` and `next` streams!
