### ISSUE TITLE
extend grub boot prompt timeout on platforms with full console access

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1236]
This issue was broken out from an [old coreos-assembler PR](https://github.com/coreos/coreos-assembler/pull/1263) that attempted to change the grub timeout to 5 seconds.

A lot of work has happened since that PR so it's worth a reset of the landscape and fresh discussion of the issue. With https://github.com/coreos/coreos-assembler/pull/2400 and https://github.com/coreos/fedora-coreos-config/pull/1781 I think we should now have covered the feature request in https://github.com/coreos/fedora-coreos-tracker/issues/110 such that we can now set the timeout per platform (might require some tweaks, but theoretically possible).

The proposal here is to increase the grub console timeout on platforms where it is possible to have read/write access to a console from 1 second to something larger to improve the user experience of catching the console prompt if needed.

More context exists in https://github.com/coreos/coreos-assembler/pull/1263

**Comment by bgilbert** [comment]
If we have a tradeoff between a relatively uncommon debugging case and the boot time of every Fedora CoreOS system, I'd lean toward making debugging _possible_ but not necessarily easy.  After reading through https://github.com/coreos/coreos-assembler/pull/1263, I'd like to hear more about use cases where this would concretely help.  I frequently have to catch the FCOS boot menu on multiple platforms (add `rd.break`, remove `console=ttyS0,115200`) and the timeout hasn't generally been an issue.  I can think of two cases where it's impractically short: bare metal machines that take 20 minutes to POST, and clouds where you can't start the console until the machine has powered on.  In both cases, 5 seconds will probably not be enough.

**Comment by dustymabe** [comment]
Let's say I'm a user and my system won't boot. It hits the grub prompt and then an error shows on screen. At a 1 second timeout it's impossible for me to read the prompt to know what key to hit. Because of my experience I know I can just hit the arrow key to stop the timeout, but it's not discoverable.

I understand not wanting to increase the boot time for the common case. Maybe bumping to 2 seconds could be a reasonable compromise?

**Comment by bgilbert** [comment]
Actually it looks like almost any key stops the count, including Escape, Backspace, Delete, any F key, Tab, Space, Ctrl-C, and down arrow.

Also, if a user needs to fix a boot failure, hopefully they'd refer to our docs for troubleshooting steps.  Those can include detailed instructions on how to get into the boot menu.

**Comment by cgwalters** [comment]
Does holding down a key work when `timeout=0` too?  I think there's an argument that if so, we should go to zero and not have a tiny timeout at all.

**Comment by bgilbert** [comment]
@cgwalters I did a quick test with `timeout=0` in qemu and wasn't able to interrupt the boot at all.
