### ISSUE TITLE
FCOS check against the Fedora Basic Release Criteria

### ISSUE THREAD

**Issue by cverna** [coreos/fedora-coreos-tracker#1239]
In order for FCOS to graduate to an Edition we need to make sure that we comply with the Fedora Basic Release Criteria. We want to demonstrate that we have test for each Criteria or that a specific criteria does not apply to FCOS.

I copied the Fedora Basic Release Criteria in this HackMD https://hackmd.io/6dWCxrD9S7izaEb6n0yipQ for easier collaboration.

**Comment by travier** [comment]
Going through the list, it feels that we already meet most of those or they don't apply to FCOS.

**Comment by dustymabe** [comment]
I went through it as well. Thanks for putting this together.

**Comment by AdamWill** [comment]
hey folks! so what I told @cverna we need here is, we need some kind of mapping from the criteria to whatever test process confirms that FCOS meets them. If you look under `References` for each criterion on the original wiki page, there is a list of related test cases; that's kinda the 'mechanism' we have for regular Fedora validation testing to 'show' that we are validating the criteria. Criteria should have associated test cases, and those test cases should be in the validation matrices, and the validation matrices should be validated for release candidates.

That's the kinda chain we need for FCOS: a way we can 'see' that the criteria requirements are being checked. I don't seem to have access to the hackmd, so I'm not sure if that's what you're drawing up, but that's what the expectation is.

Thanks!

**Comment by cgwalters** [comment]
> regular Fedora

Sorry; I'm just going to zero in on this bit for a second; I've seen people use this term "regular" or "normal" Fedora to create a contrast - but I'd like to avoid it as it implies we're irregular or abnormal.  This also relates to https://discussion.fedoraproject.org/t/its-more-fedora-than-it-is-fedora-noun 

I think it'd be fair to say "validation for Fedora editions using Anaconda and traditional yum/dnf" there right?  (Of which we would be the first not using Anaconda at least right now?  Although maybe FIoT already did the switch to osbuild?  Haven't looked)

**Comment by AdamWill** [comment]
OK, I can access the hackmd now. I added some notes.

> 99% of our tests are run automatically for each Fedora CoreOS release, independently of their "type". Should we link to the tests for each section for the reference?

Yes, this is a key point here. I'd rather not just have a simple "the CI tests everything, trust us!" handwave, I'd much rather have more specific links from each applicable requirement to some publicly-viewable representation of the specific test that 'enforces' it.

**Comment by travier** [comment]
Indeed, we have to do the same for:
- https://fedoraproject.org/wiki/Fedora_37_Beta_Release_Criteria
- https://fedoraproject.org/wiki/Fedora_37_Final_Release_Criteria

from https://fedoraproject.org/wiki/Fedora_Release_Criteria

**Comment by dustymabe** [comment]
I had a meeting with @sumantro93 earlier this week. He is going to help us make sure we do everything needed here. We've got a weekly meeting set up to collaborate on the details and hopefully close out any issues before Fedora 37 GA.

**Comment by AdamWill** [comment]
Here's a [draft of revisions to the Basic criteria](https://fedoraproject.org/wiki/User:Adamwill/Draft_CoreOS_Basic_Release_Criteria). The [page history](https://fedoraproject.org/w/index.php?title=User:Adamwill/Draft_CoreOS_Basic_Release_Criteria&action=history) tracks each individual change (including the embarrassing one where I named the page wrong...)

**Comment by AdamWill** [comment]
On a quick check of the Beta and Final criteria, not much change will be needed and it'll be along the same lines as Basic. I'll draft those up on Monday. We still need to cross-check with tests, though.

**Comment by sumantro93** [comment]
Hey @AdamWill 

Me and Dusty already agreed on https://fedoraproject.org/wiki/User:Sumantrom/Draft/FCOS_Basic_Release_Criteria for some time. Do you want me to update the actual page?

**Comment by AdamWill** [comment]
Beta criteria draft: https://fedoraproject.org/wiki/User:Adamwill/Draft_CoreOS_Beta_Release_Criteria

**Comment by AdamWill** [comment]
Final draft: https://fedoraproject.org/wiki/User:Adamwill/Draft_CoreOS_Final_Release_Criteria

Those were both pretty straightforward.

One question occurs: what about keyboard layouts? I don't know if IoT addresses this, but ARM disk image installs address it by running initial-setup on first boot; one of the reasons to do that is to provide a way for you to configure a non-US keyboard layout if that's what you need. (I think you only need number keys and enter to set the desired layout, which are the same on almost all layouts). How is one expected to use CoreOS on bare metal a non-US English layout? Know how to type `loadkeys (whatever)` with the wrong layout? Is there a better way? On a quick look at the butane/ignition docs, they do not seem to cover this. I guess if you're going to ssh into the deployed CoreOS system from a typical desktop system it's not an issue, but we *do* support bare metal deployments...

Other question: do we want to apply any of the Beta/Final IoT requirements to CoreOS too? e.g. the requirement that podman be installed and working?

**Comment by AdamWill** [comment]
oh, forgot to mention, I did add some more notes/questions to the hackmd also.

**Comment by bgilbert** [comment]
Yeah, we should add keyboard layout documentation; I've filed https://github.com/coreos/fedora-coreos-docs/issues/454 for this.  It should just amount to creating `/etc/vconsole.conf` from a Butane config.

**Comment by AdamWill** [comment]
so, uh. nobody ever replied to my drafts, and we didn't set up the meeting. go/no-go is thursday. what's our story for Final?

**Comment by AdamWill** [comment]
also the hackmd seems to have turned into something completely different?

**Comment by bgilbert** [comment]
Not sure what happened with the hackmd, but I've reverted it.

**Comment by AdamWill** [comment]
@sumantro93 tells me everyone's fine with my drafts (linked earlier), so I'll put those into production soon.

**Comment by dustymabe** [comment]
Merge Away. I looked and the changes are fairly minimal. Thank you @AdamWill

**Comment by AdamWill** [comment]
Update: didn't manage to do this in the office and "rebasing" wiki changes is a pain on a laptop with a touchpad, so I'll do this when I'm back off PTO in my home office.

**Comment by AdamWill** [comment]
OK, I've gone ahead and put the changes into 'production' now. Apologies for the delay.

**Comment by dustymabe** [comment]
I'll close this out then. Thanks @AdamWill
