### ISSUE TITLE
Keep/Remove Python dependent package: xfsprogs

### ISSUE THREAD

**Issue by sinnykumari** [coreos/fedora-coreos-tracker#124]
FCOS community members are trying [not to ship Python]( https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#approach-towards-shipping-Python) in base system. In ticket https://github.com/coreos/fedora-coreos-tracker/issues/92, we have identified list of Python dependent packages which are currently installed in FCOS.

This ticket is to investigate that  do we really need `xfsprogs` in FCOS base system? If yes, how can we provide `xfsprogs` or equivalent functionalities without shipping Python.

**Comment by sinnykumari** [comment]
Adding related discussion from #92 

@sinnykumari 
> On FCOS system boot, xfs_growfs utility from xfsprogs package is needed to run coreos-growpart.service (it runs /usr/libexec/coreos-growpart ) successfully.
> 
> Only Python utility provided by xfsprogs is /usr/sbin/xfs_scrub_all . Maybe we can request to split xfsprogs to provide Python utility (xfs_scrub_all) in a separate package?

@dustymabe 
> yeah we can try that.. Maybe we could even see if they could convince upstream to make it a compiled language. It's not a complex script.

Filed a request to provide Python utilities in separate sub-packages - https://bugzilla.redhat.com/show_bug.cgi?id=1666839

**Comment by sinnykumari** [comment]
xfsprogs-5.0.0-2 package available in f31(rawhide) is Python free. Have sent a PR to make xfsprogs pacakge Python free in f30 https://src.fedoraproject.org/rpms/xfsprogs/pull-request/3

**Comment by sinnykumari** [comment]
We have xfsprogs-4.19.0-5.fc30 build available in updates-testing . Running cosa with this update included (enabled fedora-updates-testing repo in fedora-coreos-config) gives Python free FCOS image!

To get this update available sooner in f30-updates, test it and add karma at https://bodhi.fedoraproject.org/updates/FEDORA-2019-47ecc092f0

**Comment by dustymabe** [comment]
I added it to the coreos-pool distrepo so it should be in the next build of FCOS (and no python)!

**Comment by sinnykumari** [comment]
Closing this issue as we already have xfsprogs-4.19.0-5.fc30 available in latest FCOS build https://ci.centos.org/artifacts/fedora-coreos/prod/builds/latest/commitmeta.json
