### ISSUE TITLE
Keep/Remove Python dependent package: sssd

### ISSUE THREAD

**Issue by sinnykumari** [coreos/fedora-coreos-tracker#125]
FCOS community members are trying [not to ship Python]( https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#approach-towards-shipping-Python) in base system. In ticket https://github.com/coreos/fedora-coreos-tracker/issues/92, we have identified list of Python dependent packages which are currently installed in FCOS.

This ticket is to investigate that  do we really need `sssd` in FCOS base system? If yes, how can we provide `sssd` or equivalent functionalities without shipping Python.

**Comment by sinnykumari** [comment]
Filed a RFE to not have python3-sssdconfig sub-package as Requires while installing sssd meta sub-package - https://bugzilla.redhat.com/show_bug.cgi?id=1667444

**Comment by sinnykumari** [comment]
From sssd package maintainer [comment](https://bugzilla.redhat.com/show_bug.cgi?id=1667444#c1) , it seems we may change python3-sssdconfig as suggests because sssd it self does not need it. Sent a PR with change https://src.fedoraproject.org/rpms/sssd/pull-request/2

**Comment by sinnykumari** [comment]
Required changes are available in f30. waiting now on a new build of sssd - final action item to be done.

**Comment by ajeddeloh** [comment]
Looks like we're no longer pulling in these python deps, closing. Reopen if I'm mistaken.
