### ISSUE TITLE
s390x: fcos.filesystem/sgid fails because of liblockfile

### ISSUE THREAD

**Issue by jschintag** [coreos/fedora-coreos-tracker#1253]
**Describe the bug**
```
15:40:05      --- PASS: fcos.filesystem/suid (0.35s)
15:40:05  
15:40:05      --- FAIL: fcos.filesystem/sgid (0.24s)
15:40:05  
15:40:05              files.go:69: Unknown SUID or SGID files found: [/usr/bin/dotlockfile]
```
**Reproduction steps**
1.  Build fcos rawhide on s390x
2. Run kola
3. 

**Additional information**

Initially it was thought this came from adding s390utils-base, but reverting to s390utils-core again did not change the liblockfile dependency. We need to investigate where the dependency was added and if it was intentional.

[ext.config.files.setgid.txt](https://github.com/coreos/fedora-coreos-tracker/files/9102768/ext.config.files.setgid.txt)

**Comment by dustymabe** [comment]
Note that this fails two tests:

- `fcos.filesystem/sgid`
- `ext.config.files.setgid`

I think these tests do the same thing we should probably drop `fcos.filesystem/sgid`. For now we need to denylist both.

**Comment by jschintag** [comment]
I guess i forgot to to update the issue:
The new s390utils in rawhide has as a new dependency the liblockfile package. This in turn owns the file with the group id set.
The plan is to contact the upstream community to clarify wether or not it needs to be set. If it does not need to be set, change it upstrea, otherwise ignore it in the test.

https://github.com/miquels/liblockfile

**Comment by lucab** [comment]
I think the set-gid binary is coming from https://bugzilla.redhat.com/show_bug.cgi?id=2040522, which looks somehow legit.

I guess a good question would be: which portion of liblockfile is s390utils using? If they are not using any of the `maillock(3)` APIs, then we could safely avoid the binary coming from `liblockfile` (i.e. getting the package split and only installing the library part).

**Comment by LakshmiRavichandran1** [comment]
I think it is the `/usr/bin/dotlockfile` that the s390x utils need.

```
15:40:05      --- FAIL: fcos.filesystem/sgid (0.24s)
15:40:05  
15:40:05              files.go:69: Unknown SUID or SGID files found: [/usr/bin/dotlockfile]
```
https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-arch/458/consoleFull


[liblockfile --> dotlockfile](https://github.com/miquels/liblockfile/blob/master/Makefile.in#L80-L84)

**Comment by LakshmiRavichandran1** [comment]
feel free to add to https://github.com/miquels/liblockfile/issues/20

**Comment by travier** [comment]
Initial investigation in https://github.com/coreos/fedora-coreos-config/pull/1877#issuecomment-1202717852 and later

**Comment by lucab** [comment]
Some additional pointers from an out of band chat.

We believe this dependency is coming from `s390utils`, specifically from this locking logic: https://github.com/ibm-s390-linux/s390-tools/blob/v2.22.0/libap/ap.c#L704-L760.
According to that, only `lockfile_create` / `lockfile_remove` are used from the `liblockfile` library.

The `dotlockfile` binary instead is set-gid for `mail` in order to work with this kind of mail-handling logic: https://linux.die.net/man/3/maillock.
Following through the code in `liblockfile`, we see that `lockfile_create` only falls back to the set-gid binary in case that the caller is trying to do mailbox locking: https://github.com/miquels/liblockfile/blob/v1.17/lockfile.c#L269-L277.
That doesn't seem the case for `s390utils`: https://github.com/ibm-s390-linux/s390-tools/blob/v2.22.0/include/lib/ap.h#L22.

So overall, it seems safe to pursue some strategy where longer term we don't ship that.
That could be either by having the `liblockfile` package split, by removing the binary on FCOS side, or by scrubbing the set-gid file somehow.
Short term we can either snooze the test (but possibly miss other binaries sneaking in the meanwhile) or remove it through manifest directives (but possible adding more diverging bits in FCOS).

**Comment by lucab** [comment]
Side-note: I think we may be observing the effects of a small impedance mismatch. It looks like `s390utils` wants some basic generic locking primitives, while `liblockfile` is implementing a full suite of specialized solutions focused on mailbox locking.
It may be possible to avoid all these troubles by directly changing s390utils code (e.g. by directly implementing locking, or by using a more suitable locking library).

**Comment by dustymabe** [comment]
For the record:

```
[core@cosa-devsh ~]$ rpm -q s390utils-core liblockfile
s390utils-core-2.22.0-2.fc37.s390x
liblockfile-1.17-3.fc37.s390x

[core@cosa-devsh ~]$ rpm -ql s390utils-core | grep sbin | xargs ldd
/usr/sbin/chreipl:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003ffffafe000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ff9c100000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ff9c400000)
/usr/sbin/chzdev:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003fff59fe000)
        liblockfile.so.1 => /lib64/liblockfile.so.1 (0x000003ffa5e80000)
        libjson-c.so.5 => /lib64/libjson-c.so.5 (0x000003ffa5e00000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ffa5c00000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ffa6000000)
/usr/sbin/cio_ignore:
        not a dynamic executable
/usr/sbin/dasd_cio_free:
        not a dynamic executable
/usr/sbin/dasdconf.sh:
        not a dynamic executable
/usr/sbin/dasdfmt:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003ffdacb8000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ffa9d80000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ffaa080000)
/usr/sbin/dasdinfo:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003fffc3f6000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ffa0500000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ffa0800000)
/usr/sbin/device_cio_free:
        not a dynamic executable
/usr/sbin/fdasd:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003ffd15fe000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ff96180000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ff96480000)
/usr/sbin/lszdev:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003ffd66fe000)
        liblockfile.so.1 => /lib64/liblockfile.so.1 (0x000003ff91580000)
        libjson-c.so.5 => /lib64/libjson-c.so.5 (0x000003ff91500000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ff91300000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ff91700000)
/usr/sbin/normalize_dasd_arg:
        not a dynamic executable
/usr/sbin/vmcp:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003ffe3cfe000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ff89c80000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ff89f80000)
/usr/sbin/zfcp_cio_free:
        not a dynamic executable
/usr/sbin/zfcpconf.sh:
        not a dynamic executable
/usr/sbin/zipl:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003fff15fe000)
        librpmio.so.9 => /lib64/librpmio.so.9 (0x000003ff8a300000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ff8a100000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x000003ff8a080000)
        libz.so.1 => /lib64/libz.so.1 (0x000003ff8a000000)
        libpopt.so.0 => /lib64/libpopt.so.0 (0x000003ff89f80000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x000003ff89f00000)
        liblua-5.4.so => /lib64/liblua-5.4.so (0x000003ff89e80000)
        libm.so.6 => /lib64/libm.so.6 (0x000003ff89e00000)
        libzstd.so.1 => /lib64/libzstd.so.1 (0x000003ff89d00000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x000003ff89c80000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x000003ff89880000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ff8a480000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x000003ff89800000)
/usr/sbin/zipl-editenv:
        linux-vdso64.so.1 => linux-vdso64.so.1 (0x000003fff65fe000)
        libc.so.6 => /lib64/libc.so.6 (0x000003ff9cb00000)
        /lib/ld64.so.1 => /lib/ld64.so.1 (0x000003ff9ce00000)
/usr/sbin/znet_cio_free:
        not a dynamic executable
```

It looks like only `chzdev` and `lszdev` require `liblockfile.so.1`.

**Comment by dustymabe** [comment]
This appears to be fixed upstream by https://github.com/ibm-s390-linux/s390-tools/commit/25a70ac5a81ec0b3fa74715e30cc3675d2f018d8 which is in tag [`v2.24.0`](https://github.com/ibm-s390-linux/s390-tools/releases/tag/v2.24.0)

**Comment by lucab** [comment]
It looks like `s390utils-2.24.0-1` dropped the `liblockfile` dependency on `rawhide`. The package is on its way to F37 and F36.

**Comment by dustymabe** [comment]
This landed in `s390utils-2.24.0-1.fc37` in Fedora 37. It should be in the next `testing` release.

**Comment by dustymabe** [comment]
Since the new `s390utils` [made it into](https://github.com/coreos/fedora-coreos-config/commit/831bb1a06398f7d5224fbc38a7904f945df9e394) `testing-devel` we can drop the exceptions we had made for `dotlockfile`. PR for that in https://github.com/coreos/fedora-coreos-config/pull/2115

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20221211.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20221211.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20221211.3.0`.
