### ISSUE TITLE
move github.com/cgwalters/cargo-vendor-filterer into coreos/ org

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1256]
We are using https://github.com/cgwalters/cargo-vendor-filterer now - see https://github.com/coreos/fedora-coreos-tracker/issues/1240

I'd like to share maintenance of it more (should be very low maintenance now).

**Comment by travier** [comment]
+1 from me

**Comment by ashcrow** [comment]
Sounds good to me as well.

**Comment by cgwalters** [comment]
Moved in https://github.com/coreos/cargo-vendor-filterer - I think just pending permissions tweaks now.

**Comment by ashcrow** [comment]
Teams and settings have been updated for the repo.

**Comment by cgwalters** [comment]
OK cool, created https://github.com/coreos/cargo-vendor-filterer/pull/26 as a test but I think it's working, so closing.  Thanks all!

**Comment by bgilbert** [comment]
I've set the CI job to required in branch protection as well.
