### ISSUE TITLE
Kernel panic on PXE boot on Xen

### ISSUE THREAD

**Issue by adriangabura** [coreos/fedora-coreos-tracker#1257]
**Describe the bug**
Kernel panic on PXE boot on xen

![SharedScreenshotnew](https://user-images.githubusercontent.com/5729711/179097767-70445edb-83a8-401c-b203-cad1690aa166.jpg)

[Now I realize the screenshot is for F33... Sorry. But on F36 same thing]

**Reproduction steps**
1. Load via ipxe
2. #!ipxe
kernel /assets/fedora-coreos/fedora-coreos-36.20220618.3.1-live-kernel-x86_64 coreos.inst.install_dev=/dev/xvda coreos.inst.ignition_url=http://matchbox.lyr.ovh:8080/ignition.ign coreos.inst.image_url=http://matchbox.lyr.ovh:8080/assets/fedora-coreos/fedora-coreos-36.20220618.3.1-metal.x86_64.raw.xz console=tty0 console=ttyS0
boot

**Expected behavior**
Should boot

**Actual behavior**
Kernel panic

**System details**
 - Xen Hypervisor
 - Fedora CoreOS version 36.20220618.3.1

**Ignition config**
It doesn't even load the initramfs. The ignition is a way later step.

Now, what I don't understand is why the .iso works, but the fedora-coreos-36.20220618.3.1-live-kernel-x86_64 doesn't. Is there some difference in kernel? Clearly, if it works with the iso, it ought to work with ipxe, right?

Thanks!

**Comment by bgilbert** [comment]
Looks like you're passing only the kernel, but not the initramfs or the rootfs.  See [this sample iPXE config](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_installing_from_ipxe) for the correct parameters.

Also note that you should almost never need to pass `coreos.inst.image_url`.  The installer will install directly from the PXE image by default.

**Comment by adriangabura** [comment]
> Looks like you're passing only the kernel, but not the initramfs or the rootfs. See [this sample iPXE config](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_installing_from_ipxe) for the correct parameters.
> 
> Also note that you should almost never need to pass `coreos.inst.image_url`. The installer will install directly from the PXE image by default.

Thank you! I am starting to begin to understand, I think!

**Comment by adriangabura** [comment]
I think this is caused by the Poseidon Matchbox examples which I was following. And I didn't realize, fully, that ipxe and pxe in general is a bit of more of a hassle for the uninitiated.

**Comment by adriangabura** [comment]
Also the Matchbox is weird, I don't think it's supported? Although Typhoon uses it in its official docs...

**Comment by bgilbert** [comment]
The last release is in 2020 but the repository seems to be actively maintained.  I've submitted https://github.com/poseidon/matchbox/pull/972 to update the Fedora CoreOS examples.  Thanks for pointing this out!
