### ISSUE TITLE
rawhide: 20220718: send_ostree_import_request failing during ostree import

### ISSUE THREAD

**Issue by saqibali-2k** [coreos/fedora-coreos-tracker#1259]
We have hit this issue several times over the past couple days:
- [Thursday, July 14th](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/886/)
- [Friday, July 15th](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/891/)
- [Saturday, Jul 16th](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/895/)
- [Sunday, July 18th](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/897/)

The logs are always similar:
```
Waiting for a response to the sent request
Waiting for a response to the sent request
Traceback (most recent call last):
   File "/var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py", line 112, in <module>
    sys.exit(main())
   File "/var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py", line 108, in main
     send_ostree_import_request(args)
   File "/var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py", line 87, in send_ostree_import_request
     validate_response(response)
   File "/var/tmp/fcos-releng/coreos-ostree-importer/send-ostree-import-request.py", line 102, in validate_response
     raise Exception(f"Importing failed: {response['failure-message']}")
 Exception: Importing failed: Command '['rpm-ostree', 'ex-container', 'import', '--repo', '/tmp/tmpjlvfcxhx', 'ostree-unverified-image:oci-archive:/tmp/tmpjlvfcxhx/ostree-archive']' returned non-zero exit status 1.
```
`send_ostree_import_request ` is failing during `Ostree Import: Compose Repo`. Specifically we are getting the failure on `rpm-ostree ex-container import`.

**Comment by dustymabe** [comment]
It's just built as a buildconfig in openshift from https://github.com/coreos/fedora-coreos-releng-automation/blob/e85d22672ef8acb79ba22a4b11d0f529585d74b7/coreos-ostree-importer/Dockerfile

See https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/buildconfig.yml

**Comment by cgwalters** [comment]
Yeah rebuilding it to have it pick up the latest rpm-ostree would almost certainly fix this.

**Comment by dustymabe** [comment]
OK. The container has been rebuilt now with:

```
ostree-2022.4-2.fc36.x86_64
ostree-libs-2022.4-2.fc36.x86_64
rpm-ostree-2022.10-3.fc36.x86_64
rpm-ostree-libs-2022.10-3.fc36.x86_64
```

**Comment by jlebon** [comment]
Ahh, likely this was related to `oci-chunked` which is why it only affected rawhide (which is the only stream using it currently).

**Comment by cgwalters** [comment]
We actually need at least https://bodhi.fedoraproject.org/updates/FEDORA-2022-e3870e5c95

The reason for this is coreos-assembler is opting in to the very latest after https://github.com/coreos/coreos-assembler/pull/2970

**Comment by dustymabe** [comment]
> We'll see if the next rawhide build succeeds!

The [next rawhide x86_64 build](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/905/) did succeed. We can mark this as closed.

There is another issue with the multi-arch builds but it is separate from this issue.
