### ISSUE TITLE
Keep/Remove Python dependent package: policycoreutils-python

### ISSUE THREAD

**Issue by sinnykumari** [coreos/fedora-coreos-tracker#126]
FCOS community members are trying [not to ship Python]( https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#approach-towards-shipping-Python) in base system. In ticket https://github.com/coreos/fedora-coreos-tracker/issues/92, we have identified list of Python dependent packages which are currently installed in FCOS.

This ticket is to investigate that  do we really need `policycoreutils-python` in FCOS base system? If yes, how can we provide `policycoreutils-python` or equivalent functionalities without shipping Python.

**Comment by dustymabe** [comment]
This currently isn't in Fedora CoreOS but the `policycoreutils-python-utils` rpm (which requires `python3-policycoreutils`) maybe should be. It provides: 

```
[root@vanilla-f29-atomic ~]# rpm -ql policycoreutils-python-utils | head -n 6
/etc/dbus-1/system.d/org.selinux.conf
/usr/bin/audit2allow
/usr/bin/audit2why
/usr/bin/chcat
/usr/bin/sandbox
/usr/sbin/semanage
```

To me the biggest one of those is `semanage` IMHO. I don't know if we can get by without it as there is a lot that it does. 

cc @cgwalters @bgilbert @lucab

**Comment by sinnykumari** [comment]
@rhatdan We are trying to remove Python dependent packages from FCOS base system. Right now we have  policycoreutils-python-utils included in host providing utilities like semanage . Will it be possible to run it inside container and manage selinux policy of host from container? If not do we have any other alternative option?

**Comment by rhatdan** [comment]
I think you should be able to remove semanage from the system.

semodule for loading selinux policy modules, and setsebool for setting booleans should be all that is needed, and those are written in C.

**Comment by dustymabe** [comment]
what happens if someone needs to change file contexts ?

**Comment by rhatdan** [comment]
They have chcon and restorecon for that.  Issue would be if someone ran a restorecon on entire system.
semanage fcontext ... Modifies the file context database but not the labels on disk.  It is not ideal, but should work for the most part, and you could always add semanage via layering.

**Comment by dustymabe** [comment]
cool. thanks for the info @rhatdan 
only final question I have is how hard would it be to rewrite `semanage` in a compiled language :)

**Comment by rhatdan** [comment]
In general, very difficult.  I think writing something that manipulated the file contexts would be fairly simple.

**Comment by dustymabe** [comment]
Discussed in the [meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/SFZMGRJHFABUA7WFS4SWJMASHQFU3BLK/) this past wednesday:

We agreed to ask dan walsh for feedback, which he has conveniently already provided :)

**Comment by sinnykumari** [comment]
Adding this for information:
semodule, setsebool and restorecon are provided by policycoreutils package. chcon is provided by  coreutils (already included in FCOS)

**Comment by sinnykumari** [comment]
During FCOS [community meeting](https://meetbot.fedoraproject.org/fedora-meeting-1/2019-02-27/fedora_coreos_meeting.2019-02-27-16.30.log.html), we agreed to experiment with initially not shipping policycoreutils-python-utils in the FCOS base system.
