### ISSUE TITLE
Where is /proc/sys/kernel/core_pattern set to |/bin/false?

### ISSUE THREAD

**Issue by kgibm** [coreos/fedora-coreos-tracker#1262]
**Describe the bug**

In previous versions of coreos, I would run `ln -sf /dev/null /etc/sysctl.d/50-coredump.conf` to set `core_pattern` to `core`. In recent versions, the same command does not work and `/proc/sys/kernel/core_pattern` is set to `|/bin/false`. I can't find where this is set:

```
# find /etc -type f -print0 | xargs -0 grep -F "|/bin/false" 2>/dev/null
# 
```

How do I override the coreos `core_pattern` of `|/bin/false`?

**Expected behavior**

Ability to override coreos `core_pattern` configuration as per the [`systemd` documentation](https://www.freedesktop.org/software/systemd/man/environment.d.html):

> If the administrator wants to disable a configuration file supplied by the vendor, the recommended way is to place a symlink to /dev/null in the configuration directory in /etc/, with the same filename as the vendor configuration file.

**Actual behavior**

`ln -sf /dev/null /etc/sysctl.d/50-coredump.conf` doesn't work.

**System details**

Created through `podman machine init` on macOS x64.

```
# cat /etc/os-release 
NAME="Fedora Linux"
VERSION="36.20220703.2.1 (CoreOS)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora CoreOS 36.20220703.2.1"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='36.20220703.2.1'
DEFAULT_HOSTNAME=localhost
```

**Ignition config**

I think this is built at `podman`

**Comment by bgilbert** [comment]
I've tested Fedora CoreOS builds from each Fedora major version back to 33.20210201.2.1 and they all have this behavior.  It looks like it's a [systemd default](https://github.com/systemd/systemd/blob/7359e3d35a7f295d8f4108c296147358c5feff99/src/basic/util.c#L165-L174).

Have you tried writing a replacement `50-coredump.conf` rather than disabling the file?  This works for me:

```yaml
variant: fcos
version: 1.4.0
storage:
  files:
    - path: /etc/sysctl.d/50-coredump.conf
      contents:
        inline: |
          kernel.core_pattern=core
```

**Comment by kgibm** [comment]
@bgilbert Thanks!
