### ISSUE TITLE
removing `atomic` from our ostree repo URLs

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#127]
Let's work to remove the `atomic` keyword from our URLs and make it something more generic, like `ostree`. 

infra ticket: https://pagure.io/fedora-infrastructure/issue/7487

**Comment by sinnykumari** [comment]
@dustymabe This work need co-ordination and changes at multiple places. Was wondering if we should add priority tag (Medium?) to this item as well so that we know we are working on right issue?

**Comment by dustymabe** [comment]
added label

**Comment by sinnykumari** [comment]
ostree repo migration has been done successfully along with necessary changes at affected places mpacted by this change. See https://pagure.io/fedora-infrastructure/issue/7487#comment-552821 .

**Comment by dustymabe** [comment]
thanks sinny. should we close this?

**Comment by sinnykumari** [comment]
> thanks sinny. should we close this?

Yeah, let's close this. We can do any follow-up fixes if something comes up in effected places.
