### ISSUE TITLE
kola: basic: grub2 regression causes systems not to boot

### ISSUE THREAD

**Issue by gursewak1997** [coreos/fedora-coreos-tracker#1271]
kola basic tests aren't coming up and the machines aren't getting out of grub 
```
EFI stub: ERROR: Failed to allocate usable memory for kernel.
EFI stub: ERROR: efi_relocate_kernel() failed!
EFI stub: ERROR: efi_main() failed!
BdsDxe: failed to start Boot0002 "Fedora" from HD(2,GPT,A12C907C-0A24-4313-ACC4-50AF0472625C,0x1000,0x3F800)/\EFI\fedora\shimx64.efi: Not Found
```
```
[2022-08-04T12:47:42.669Z] === RUN   basic
[2022-08-04T12:57:49.177Z] --- FAIL: basic (601.59s)
[2022-08-04T12:57:49.177Z]         harness.go:104: TIMEOUT[10m0s]: SSH unsuccessful within allotted timeframe for 2351d793-cf09-44d4-94fe-fd80ef716d3d.
[2022-08-04T12:57:49.177Z] FAIL, output in tmp/kola
```
Failing runs
- [Rawhide](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/build/detail/build/2/pipeline)
- [Bump Lockfile testing-devel](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/2/pipeline/)

Console Logs
- [console.txt](https://github.com/coreos/fedora-coreos-tracker/files/9263294/console.txt)

**Comment by cgwalters** [comment]
It seems highly likely to relate to the recent grub changes, see e.g. https://bodhi.fedoraproject.org/updates/FEDORA-2022-8ffd58c713
that landed on both f36 and rawhide.

**Comment by travier** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2115202 > Apparently chain-loading is broken in the new GRUB thus why we're impacted.

**Comment by jlebon** [comment]
@gursewak1997 Can you confirm tests pass if we pin grub2 but upgrade everything else and if so add a pin for it until a fix is in?

**Comment by jlebon** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2022-d0c322d15a was submitted for f36 which may fix this. It'd be good to verify that this fixes our issue and provide feedback, but I'd prefer we don't drop our pin until it gets more karma and gets pushed to stable.

**Comment by dustymabe** [comment]
Let's find out: https://github.com/coreos/fedora-coreos-config/pull/1906

This will run CI. I marked it as draft so it won't merge.

**Comment by dustymabe** [comment]
Looks like the tests passed.
