### ISSUE TITLE
kola: rawhide: 20220729: filesystem.posttrans fails with unsupported lua script

### ISSUE THREAD

**Issue by gursewak1997** [coreos/fedora-coreos-tracker#1273]
Build fails with `unsupported lua script in '%posttrans'` from filesystem package
```
[2022-08-05T17:59:00.657Z] Checking out ostree layers...done
[2022-08-05T17:59:00.657Z] Running posttrans scripts...done
[2022-08-05T17:59:00.657Z] error: Package 'filesystem' has (currently) unsupported <lua> script in '%posttrans'
[2022-08-05T17:59:00.657Z] r/lib/systemd/system/lvm2-monitor.service.
[2022-08-05T17:59:00.657Z] lvm2.post: rpm-ostree-systemctl: Ignored non-preset command: enable lvm2-monitor.service

```
Rawhide [Build](https://jenkins-coreos-ci.apps.ocp.fedoraproject.org/blue/organizations/jenkins/fedora-coreos-config/detail/PR-1894/5/pipeline/)

**Comment by dustymabe** [comment]
This was introduced in:

- [filesystem-3.18-1.fc36](https://bodhi.fedoraproject.org/updates/FEDORA-2022-7ea518a8c7)
- [filesystem-3.18-1.fc37](https://bodhi.fedoraproject.org/updates/FEDORA-2022-5fd3ebac2e)

**Comment by jlebon** [comment]
The rpm-ostree fix for this has been [backported into f36](https://bodhi.fedoraproject.org/updates/FEDORA-2022-5e830ab868) and tagged into f36-coreos-continuous. So we should be able to revert the `filesystem` part of https://github.com/coreos/fedora-coreos-config/pull/1898. @gursewak1997 Would you be able to do that?

**Comment by gursewak1997** [comment]
@jlebon Since we have the changes for `grub2` and `filesystem` overrides in one commit, should I just add an additional commit to remove the filesystem override?

**Comment by jlebon** [comment]
Yeah, you can just revert it by hand and in the commit message you can include e.g. "Partially reverts ...".
