### ISSUE TITLE
Fedora CoreOS "37" builds are actually Rawhide

### ISSUE THREAD

**Issue by AdamWill** [coreos/fedora-coreos-tracker#1279]
openQA testing of the Fedora CoreOS "37" builds since Fedora-CoreOS-37.20220810.91.0 (that's first bad) show that they're not 37 (Branched), they're Rawhide (which is now on track for 38). `/etc/os-release` says "Fedora release 38 (Rawhide)". Various values in `/etc/os-release` also all match Rawhide, not Branched:

    VERSION should be 37.20220820.91.0 (CoreOS Prerelease) and is 38 (CoreOS Prerelease)
    VERSION_ID should be 37 and is 38
    PLATFORM_ID should be platform:f37 and is platform:f38
    PRETTY_NAME should be Fedora CoreOS 37.20220820.91.0 and is Fedora CoreOS 38
    REDHAT_BUGZILLA_PRODUCT_VERSION should be 37 and is rawhide
    REDHAT_SUPPORT_PRODUCT_VERSION should be 37 and is rawhide at fedora/tests/os_release.pm line 192.

it seems like FCOS just kinda...missed branching and still thinks Rawhide == 37.

**Comment by dustymabe** [comment]
Yep. That's expected. We have a [rebase SOP](https://github.com/coreos/fedora-coreos-tracker/issues/1223) that we're going to start on this week to re-enable the `branched` stream and get `rawhide` properly updated.

The past few weeks have been a bit crazy with some internal hardware migrations and conference travel.

**Comment by dustymabe** [comment]
This should be resolved now. We switched over rawhide in https://github.com/coreos/fedora-coreos-config/commit/2320603fb7efbb6b639660baa94aa36adeae7bea. Though it tooks us a while to resolve some issues and get a successful compose out. Happened today with `38.20220826.91.0`.

**Comment by AdamWill** [comment]
Yup, openQA is [happy with that build](https://openqa.fedoraproject.org/tests/overview?distri=fedora&version=38&build=Fedora-CoreOS-38.20220826.91.0&groupid=1).
