### ISSUE TITLE
Transfer github.com/cgwalters/rpmostree-client-go to this org

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1284]
I'd like to propose moving https://github.com/cgwalters/rpmostree-client-go into github.com/coreos.

A bit more rationale in e.g. https://github.com/openshift/machine-config-operator/pull/3302#issuecomment-1227536591 (above and below).

**Comment by ashcrow** [comment]
LGTM. Go ahead and move it into the CoreOS org and I'll go through the checklist.

**Comment by cgwalters** [comment]
Done!
