### ISSUE TITLE
Faulty DNS queries in musl-based containers due to "search ." in resolv.conf

### ISSUE THREAD

**Issue by dghubble** [coreos/fedora-coreos-tracker#1287]
**Describe the bug**

Could we pull in https://github.com/openshift/okd-machine-os/pull/159 to FCOS? Kubernetes v1.25.0 landed and the systemd behavior that adds "search ." on nodes with FQDNs now propagates into containers, which breaks musl-based DNS resolution apparently. I can see why OpenShift reverted it.

**Reproduction steps**

Originally I was preparing the Typhoon Kubernetes distro for v1.25.0 release and I did some sleuthing. The full write-up for Kubernetes is https://github.com/kubernetes/kubernetes/issues/112135. The original bug in Kubelet was added to fix a problem RedHat customers saw, but I imagine the side effect wasn't noticed since OpenShift has https://github.com/openshift/okd-machine-os/pull/159 to mitigate it.

Unfortunately, just starting a container with Podman (and mucking with `/etc/resolv.conf`) doesn't seem to demonstrate the issue. I'd like to try to get a single-node reproducer for you guys. But for now it seems to just be Typhoon and OpenShift

**Expected behavior**

Don't put "search ." at the end of `/etc/resolv.conf` on hosts.

**Actual behavior**

https://github.com/systemd/systemd/pull/17201/files adds "search ." to `/run/systemd/resolve/stub-resolv.conf`, which seems to confuse any musl-based DNS resolution when this propagates into Kubernetes containers. This didn't become apparent until Kubernetes v1.25.0, when Kubelet started propagating that "search ." directly into a container's `/etc/resolv.conf` in https://github.com/kubernetes/kubernetes/pull/109441

**System details**

Bare Metal

```
NAME="Fedora Linux"
VERSION="36.20220806.3.0 (CoreOS)"
```

**Ignition config**

As a workaround, I can apply the same unit OpenShift is using. Removing the "." fixes the musl DNS problems.

```yaml
variant: fcos
version: 1.4.0
systemd:
  units:
    - name: fix-resolv-conf-search.service
      enabled: true
      contents: |
        [Unit]
        Description=Remove search . from /etc/resolv.conf
        DefaultDependencies=no
        Requires=systemd-resolved.service
        After=systemd-resolved.service
        BindsTo=systemd-resolved.service
        [Service]
        Type=oneshot
        ExecStartPre=/usr/bin/sleep 5
        ExecStart=/usr/bin/sed -i -e "s/^search .$//" /run/systemd/resolve/resolv.conf
        [Install]
        WantedBy=multi-user.target
```

**Related**

Add any other information about the problem here.
* https://github.com/systemd/systemd/pull/17201
* https://github.com/coreos/fedora-coreos-tracker/issues/881#issuecomment-870924484 cc @LorbusChris 
* https://github.com/kubernetes/kubernetes/pull/109441 @Miciah
* https://github.com/kubernetes/kubernetes/issues/112135

**Comment by lucab** [comment]
Thanks for the report.

> "search ." on nodes with FQDNs now propagates into containers, which breaks musl-based DNS resolution apparently.

For reference, which `musl` version is in use there? I know there have been recent changes in the resolver logic, it would be good to confirm that we are speaking about the latest stable release (1.2.3).

Additionally I'd wait to see how the upstream kubernetes bug discussion goes, as the in-container DNS resolution is really owned by the orchestrator.

Overall I feel this may be a `musl` bug. If so, the best outcome would be to get a minimal reproducer and then fix the faulty behavior there.

**Comment by lucab** [comment]
I think I can see what's going wrong with musl DNS resolution. Even outside of FCOS or kubernetes, just running a plain container with the `docker.io/alpine:3.16.2` image:

```
# apk list | grep 'musl\|busybox'
musl-1.2.3-r0 x86_64 {musl} (MIT) [installed]
musl-utils-1.2.3-r0 x86_64 {musl} (MIT BSD GPL2+) [installed]
busybox-1.35.0-r17 x86_64 {busybox} (GPL-2.0-only) [installed]
ssl_client-1.35.0-r17 x86_64 {busybox} (GPL-2.0-only) [installed]

# cat /etc/resolv.conf 
search default.svc.cluster.local .
nameserver 8.8.8.8
options ndots:5

/ # wget google.foobarxyz
wget: bad address 'google.foobarxyz'
```

The interesting part is what happens under the hood.
I took a capture of the DNS flow (which I'm attaching [here](https://github.com/coreos/fedora-coreos-tracker/files/9460721/musl-resolution.pcap.gz)) and it looks like musl is failing to properly wire-encode the trailing `.` for the DNS query:
![wireshark](https://user-images.githubusercontent.com/98086/187658234-15dd1b19-934d-424d-9af2-6ea0a3b2bcdd.png)
In the screenshot, note the `0x2e` at the end of the `foobarxyz` DNS label.

**Comment by lucab** [comment]
An even smaller reproducer is:
```
# cat /etc/resolv.conf 
search . customtld
nameserver 8.8.8.8

# nslookup -type=a foorbarxyz
Server:         8.8.8.8
Address:        8.8.8.8:53

** server can't find foorbarxyz.customtld: NXDOMAIN
** server can't find foorbarxyz..: FORMERR
```

For some reason, the bug seems to only happen if there are multiple search domains configured.
That is, just a plain `search .` seems to work fine and properly gets a response back:
```
# cat /etc/resolv.conf 
search .
nameserver 8.8.8.8

# nslookup -type=a foorbarxyz
Server:         8.8.8.8
Address:        8.8.8.8:53

** server can't find foorbarxyz: NXDOMAIN
```

**Comment by lucab** [comment]
> Not at the OS level, forget my original ask.
> Hopefully Kubernetes can react or eventually musl has a fix.

I agree with this assessment.
Kubernetes can filter the trailing `.` search domain (it doesn't mean much in the container context) and musl should fix its search behavior.

Were you planning to report the musl bug to their ML too?

**Comment by dghubble** [comment]
I sent an email to musl at lists.openwall.com, which should hopefully show up soon https://www.openwall.com/lists/musl/

**Comment by LorbusChris** [comment]
fyi @vrutkovs

**Comment by dghubble** [comment]
Looks like Kubernetes will [stop propagating](https://github.com/kubernetes/kubernetes/pull/112157) `search .`, @lucab is cherry-picking to Kubernetes v1.25.1, and musl, CoreDNS, and systemd folks have been informed. I think we could close this

Thank you @lucab for the digging to help confirm and fix!

**Comment by dustymabe** [comment]
Thank all for the discussion!
