### ISSUE TITLE
manifest list `quay.io/coreos-assembler/fcos:stable`

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1289]
We've been shipping a container image for each stream like `quay.io/coreos-assembler/fcos:testing-devel` for a while.  But this is not manifest listed today: https://github.com/coreos/fedora-coreos-pipeline/blob/7420a953b907920cc58298b4953b47040cb3fc75/jobs/release.Jenkinsfile#L132

We added code in `cosa push-container-manifest` that's used for coreos-assembler today that I think can also cover this.

**Comment by cgwalters** [comment]
Hmmmm....looking at this a bit more, it seems to me that there's a high level of overlap between what's going on in `cosa push-container` and `cosa push-container-manifest`.

Now, they're not the same thing and for compat we need to keep both as is right now I think but...looking at this, I think what we want is a flow like:

```
$ cosa buildprep --arch=all
$ cosa push-container-manifestlisted
```

Basically this second command would parse all the `meta.json` for each architecture that we already have and invoke

```
    cosa push-container-manifest \\
        --repo quay.io/dustymabe/fedora-coreos --tag stable \\
        --image oci-archive://builds/36.20220716.3.1/x86_64/fedora-coreos-37.20220725.91.0-ostree.x86_64.ociarchive \\
        --image oci-archive://builds/36.20220716.3.1/aarch64/fedora-coreos-37.20220725.91.0-ostree.aarch64.ociarchive \\
        --image oci-archive://builds/36.20220716.3.1/s390x/fedora-coreos-37.20220725.91.0-ostree.s390x.ociarchive"""
```

This seems pretty easy to put together if I understand it all.

And if we do this *and* with the ongoing effort to rebase the rhcos pipeline on the fcos pipeline, then suddenly this approach can be used for https://issues.redhat.com/browse/ART-4352 which would be a big win.

**Comment by dustymabe** [comment]
yes. I've been trying to get back to the code recently to make everything better in this area (got a local stash with some work in it). My plan is to tackle these semi-independent goals at the same time:

- push for all architectures
- switch repo to quay.io/fedora/fedora-coreos
- increase code sharing between various container push code that we have

**Comment by cgwalters** [comment]
> switch repo to quay.io/fedora/fedora-coreos

This bit would be a *huge* milestone, anything I can do to help please let me know!

**Comment by dustymabe** [comment]
The manifest list bits landed in https://github.com/coreos/fedora-coreos-pipeline/pull/628

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220918.2.2`.
