### ISSUE TITLE
CT for Fedora CoreOS

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#129]
From #89:

> CL has the Container Linux Config Transpiler or ct for short. Since users should not be writing Ignition configs by hand, they write Container Linux Configs (CLCs) which ct then renders into an Ignition config. This scheme has a few advantages:
> - Forces users to validate their configs
> - Allows easy addition of sugar for common operations
> - Allows for adding OS specific bits without making the Ignition spec OS specific
> - Allows users to write configs in yaml but keeps the configs that Ignition ingests in json

Implement a config transpiler for Fedora CoreOS.
- [x] Select a name for the config language and the tool: FCCL is the language of FFCs which are processed by FCCT
- [x] Decide whether to support Red Hat CoreOS as well: no, but structure the project such that the core bits are easily included in other projects or distros
- [x] Implement config versioning (#89)
- [x] Decide on what case to use for keys (#176): `snake_case`
- [x] Create FCCT
  - [x] Barebones "just Ignition equivilents" parts
  - [ ] Sugar for parts of the distro
  - [x] Line and column information included in error messages

**Comment by dustymabe** [comment]
>     * Decide whether to support Red Hat CoreOS as well

To this point, we could build this tool with a plugin model to make it easy to support other distros. Each distro could pick/choose which modules it wanted to enable and/or override for their platform.

**Comment by arithx** [comment]
> Select a name for the config language and the tool. "FCOSC" and "FCOSCT" are slightly less than ideal.

I'm partial to `FCC` & `FCCT`. Keeps it a minimal acronym by just dropping the OS while still differentiating from what standard Fedora would/could use.

**Comment by bgilbert** [comment]
> To this point, we could build this tool with a plugin model to make it easy to support other distros. Each distro could pick/choose which modules it wanted to enable and/or override for their platform.

That's a good medium-term goal.  I think initially we should focus on making a CT available quickly, so was thinking we'd start with the existing CLCT codebase and defer refactoring where possible.

**Comment by ajeddeloh** [comment]
With regards to supporting multiple OSs, there's basically two parts to the CT spec: a distro-agnostic part that roughly mirrors Ignition's spec (with niceties for things like inlining files) and a part that's disto-specific bit that is sugar for things like setting up etcd, flannel, etc. The structure in CLCs looks like the top level Ignition fields merged with top level sugar fields. Basically:
```
storage: <stuff> # from Ignition
systemd: <stuff>  # from Ignition
etcd: <stuff> # from sugar
flannel: <stuff> # from sugar
```

Go supports struct embedding. Assuming the go-yaml library supports this (need to check this), we can have a top level struct that contains the versioning info and embeds both the Ignition and each distro's sugar. We could even have multiple top level structs, one for each distro, and switch them based on a flag. This allows us to cleanly separate the distro dependent and independent parts without having to deal with branches, forks, or a lot of code duplication.

**Comment by jasonbrooks** [comment]
How about a name that's connected to "ignition config" -- ignition config source or proto ignition config or something? It seems unnecessary to put "fedora" or "container linux" in there at all, and wouldn't this be something that people outside of fedora might want to use?

Feed ignition config language into the ignition config tool and get ignition configs.

**Comment by arithx** [comment]
@jasonbrooks the Fedora or Container Linux portions in the name is to imply that it has additional sugar for those specific distributions. The base level representations of the Ignition spec should be kept distro-agnostic naming wise in my opinion (and tying it directly to Ignition is a good idea).

**Comment by ajeddeloh** [comment]
From the community meeting today, we're going forward with `fcct`/`fcc`/`fccl`.

**Comment by ajeddeloh** [comment]
Closing this as FCCT 0.1.0 was just released. Doesn't have any distro-specific sugar yet, just it's enough for preview.

**Comment by lucab** [comment]
For reference, FCCT upstream project is at https://github.com/coreos/fcct.

**Comment by dghubble** [comment]
Looks great!
