### ISSUE TITLE
Timeout waiting for boot labeled disk

### ISSUE THREAD

**Issue by jess-sol** [coreos/fedora-coreos-tracker#1290]
**Describe the bug**

Attempting to install stable 36.20220806.3.0 on Bull Sequana Edge server. It installs fine on harddrive, but on boot times out waiting for boot labeled disk. If I boot to a live image the partition labeled boot exists and is mountable.

**Reproduction steps**
1. Install with iPXE script from documentation
2. Reboot, wait for boot on Bull Sequana Edge
3. See timeout waiting for disk in console

**Expected behavior**
Expect CoreOS to successfully boot after clean install.

**Actual behavior**
Hangs during ignition run waiting for boot disk.

**System details**
 - Bare Metal, iPXE snp, Bull Sequana Edge
 - Tried stable/36.20220618.3.1, stable/36.20220806.3.0, and next/36.20220820.1.0

**Ignition config**
Fails when passing skip to ignition config, or empty ignition config.

**Additional information**

[console.txt](https://github.com/coreos/fedora-coreos-tracker/files/9472874/console.txt)

iPXE script:
```
#!ipxe
dhcp
set INSTALLDEV /dev/sda
set CONFIGURL skip
set STREAM stable
set VERSION 36.20220806.3.0
set BASEURL https://builds.coreos.fedoraproject.org/prod/streams/${STREAM}/builds/${VERSION}/x86_64

kernel ${BASEURL}/fedora-coreos-${VERSION}-live-kernel-x86_64 initrd=main coreos.live.rootfs_url=${BASEURL}/fedora-coreos-${VERSION}-live-rootfs.x86_64.img coreos.inst.install_dev=${INSTALLDEV} coreos.inst.ignition_url=${CONFIGURL}
initrd --name main ${BASEURL}/fedora-coreos-${VERSION}-live-initramfs.x86_64.img

boot
```

**Comment by bgilbert** [comment]
This is odd:

```
systemd-sysusers[473]: Failed to check if group users already exists: Connection timed out
```

Also, there mostly aren't any userspace messages in that console log.  Could you check whether your `console=` kernel arguments are correct for your console?  The _last_ console argument should be the console you're capturing.

**Comment by lucab** [comment]
> wait for boot on Bull Sequana Edge

I had to debug this same issue on this same hardware in the past.
If you look at the timings from your console logs, you'll see that it takes an absurdly long time to proceed (after more than ten minutes it is still starting basic services in the initramfs).
This seems to be due to some faulty buffering in the serial console, which is slowing down the whole system and resulting in weird timeouts.

From what I've seen, just having the web console open when booting the node would sidestep the bug.

The proper fix is to tune the `console=` arguments as @bgilbert suggested.

**Comment by jess-sol** [comment]
Thanks everyone! Tuning console was definitely it. I did see that mentioned in the docs, but the timeout waiting for boot disk was throwing me off, I was convinced that was the root of the issue.

I was able to tune my iPXE install using a separate butane config, [documented here](https://coreos.github.io/coreos-installer/customizing-install/#example-manual-customization-via-installerd).

For anyone else who may have a similar issue, here's where my config ended up:


**install.yml**
```yml
---
variant: fcos
version: 1.4.0
storage:
  files:
  - path: /etc/coreos/installer.d/custom.yaml
    contents:
      inline: |
        delete-karg: ["console=ttyS0,115200n8"]
```
**first-boot.yml**
```yaml
---
variant: fcos
version: 1.4.0
# Normal ignition configs
```
**autoexec.ipxe**
```bash
#!ipxe
dhcp

set INSTALLDEV /dev/sda
set CONFIGURL_INSTALL http://192.168.10.1:8080/fcos/install.ign
set CONFIGURL_FIRSTBOOT http://192.168.10.1:8080/fcos/first-boot.ign
set STREAM stable
set VERSION 36.20220806.3.0

set BASEURL https://builds.coreos.fedoraproject.org/prod/streams/${STREAM}/builds/${VERSION}/x86_64

kernel ${BASEURL}/fedora-coreos-${VERSION}-live-kernel-x86_64 initrd=main coreos.live.rootfs_url=${BASEURL}/fedora-coreos-${VERSION}-live-rootfs.x86_64.img coreos.inst.install_dev=${INSTALLDEV} coreos.inst.ignition_url=${CONFIGURL_FIRSTBOOT} ignition.config.url=${CONFIGURL_INSTALL} ignition.firstboot ignition.platform.id=metal
initrd --name main ${BASEURL}/fedora-coreos-${VERSION}-live-initramfs.x86_64.img

boot
```
