### ISSUE TITLE
systemd-sysusers reporting it is creating `root` group with GID 999 in initramfs

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1297]
Noticed this over in https://github.com/systemd/systemd/issues/23745#issuecomment-1245580974 but it's not only in `rawhide` it's also in F36 (`stable`/`testing`):

```
Sep  6 20:42:52.320768 systemd-sysusers[267]: Creating group 'root' with GID 999.
```

Here is a log from `36.20220820.3.0` (`stable`): [journal.txt](https://github.com/coreos/fedora-coreos-tracker/files/9571544/journal.txt)

**Comment by lucab** [comment]
I think this may be a duplicate of https://github.com/systemd/systemd/issues/24066.
Looking at our initramfs content in `36.20220820.3.0`, I can see the following arrangement:
```
# grep root etc/passwd 
root::0:0::/root:/bin/sh

# grep root etc/group 

# grep -rn root usr/lib/sysusers.d/
usr/lib/sysusers.d/basic.conf:9:u root    0     "Super User" /root
```

So we do have a pre-existing `root` user (with UID `0`) but no pre-existing group (I think this is a mirrored side-effect of the nss-altfiles arrangment we have in the real root).
When systemd-sysusers runs, it creates the `root` group entry but it does not exactly respect the ID configured in the sysusers.d fragment.
If it is indeed the same bug, it should be covered by the patch in https://github.com/systemd/systemd/pull/24246 which will appear in systemd `v252`.

Unfortunately I don't have anymore at hand the custom FCOS image I had built with those systemd, so cannot quickly confirm/disprove this theory right now.

**Comment by lucab** [comment]
From an out of band chat, @travier was wondering whether this would be actually problematic for configurations like the following:
```
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/ownership-test
      user:
        name: "root"
      group:
        name: "root"
      contents:
        inline: |
          # Placeholder

```

But that seems to be fine:
```
$ stat /etc/ownership-test 
  File: /etc/ownership-test
  Size: 14              Blocks: 8          IO Block: 4096   regular file
Device: 252,4   Inode: 2866919     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
```

**Comment by lucab** [comment]
I did re-assemble an image with my systemd patches, and unfortunately it looks like my previous work won't address this.

Taking this to a minimal reproducer without all of FCOS complexity, the same behavior can be observed with a systemd-sysusers built from current git (`add0c9b8bf`):
```
$ cat etc/passwd 
root:x:0:0:root:/root:/bin/bash

$ cat etc/sysusers.d/testcase.conf 
u root    0     "Super User" /root

$ ../systemd-sysusers --root .
Creating group 'root' with GID 999.
```

**Comment by dustymabe** [comment]
Should we take this issue to systemd upstream?

**Comment by lucab** [comment]
A PR to address this behavior is up at https://github.com/systemd/systemd/pull/25107.

**Comment by dustymabe** [comment]
This landed upstream in https://github.com/systemd/systemd/commit/f10ad99ab07ca03b6190a500c49d3d76e35ab1f8

**Comment by dustymabe** [comment]
This landed in [`v253-rc1`](https://github.com/systemd/systemd/releases/tag/v253-rc1). And has made it into a `rawhide` build in [`systemd-253~rc1-1.fc38`](https://koji.fedoraproject.org/koji/search?terms=systemd-253~rc1-1.fc38&type=build&match=exact).

It should be in the next `rawhide` FCOS pipeline build.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230322.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230414.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230414.3.0`.
