### ISSUE TITLE
RUSTSEC-2021-0139: ansi_term is Unmaintained

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1299]
We've received a warning for https://rustsec.org/advisories/RUSTSEC-2021-0139.html. Not sure if we really need to act on it but let's track it here.

Links to advisories and references:
- https://github.com/advisories/GHSA-74w3-p89x-ffgh
- https://github.com/ogham/rust-ansi-term/issues/72
- https://rustsec.org/advisories/RUSTSEC-2021-0139.html

Impacted repos:
- https://github.com/coreos/fedora-coreos-cincinnati
- https://github.com/coreos/rpm-ostree
- https://github.com/coreos/zincati

Alternatives are listed in the RUSTSEC advisory.

**Comment by lucab** [comment]
All of those are transitive dependencies, mostly coming in through `structopt`:
```
$ cargo tree -i ansi_term
ansi_term v0.12.1
└── clap v2.34.0
    └── structopt v0.3.26
        └── zincati v0.0.24
```

To fix this advisory, we should port those projects from `structopt` to `clap` v3.

**Comment by travier** [comment]
Update: The GitHub advisory has been withdrawn, probably due to complains as the issue is low severity and there is no security bug here, just an unmaintained crate.

**Comment by travier** [comment]
Thanks!
