### ISSUE TITLE
AMI images description field stopped being populated

### ISSUE THREAD

**Issue by dghubble** [coreos/fedora-coreos-tracker#1300]
**Describe the bug**

On the stable stream, it looks like with `36.20220820.3.0` the AWS AMI `description` field is no longer populated with the channel name.

![Screenshot from 2022-09-19 13-53-26](https://user-images.githubusercontent.com/2253428/191114513-bcb0aa80-3ca5-4f8a-bd3c-11b032a92a6a.png)

In the past, it had a value that was very useful.

![Screenshot from 2022-09-19 13-55-29](https://user-images.githubusercontent.com/2253428/191114982-6131eef1-d032-4a90-9d9d-52902e39aecb.png)

In Terraform, we often filter AMIs to find the latest AMI in a particular channel and architecture.

**Expected behavior**

We just need some reliable way to filter FCOS AMI images in a particular channel. That used to be the `description` field. There does not seem to be an equivalent field that provides this information.

**Actual behavior**

I noticed this on systems that use Terraform to select the latest AMI, such as: https://github.com/poseidon/typhoon/blob/main/aws/fedora-coreos/kubernetes/ami.tf#L1

```tf
...
filter {
    name   = "description"
    values = ["Fedora CoreOS ${var.os_stream} *"]
}
```

New instances continue to use older AMIs because they find the latest release as `36.20220806.3.0`, although at the time of this writing the latest stable image is `36.20220820.3.0`

**System details**

- AWS
 - Fedora CoreOS version 36.20220820.3.0

**Comment by lucab** [comment]
Bisecting through our `rawhide` builds I ended up here:
```
# 38.20220901.91.0
$ curl -s https://builds.coreos.fedoraproject.org/prod/streams/rawhide/builds/38.20220901.91.0/x86_64/meta.json | jq .summary
"Fedora CoreOS rawhide"

# 38.20220902.91.0
$ curl -s https://builds.coreos.fedoraproject.org/prod/streams/rawhide/builds/38.20220902.91.0/x86_64/meta.json | jq .summary
"This field is unused"
```

So this regressed at the beginning of the month.
Looking back through coreos-assembler history, I think this is the PR that broke it: https://github.com/coreos/coreos-assembler/pull/3053

/cc @cgwalters @dustymabe

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/coreos-assembler/pull/3109

**Comment by dghubble** [comment]
Looks like these descriptions are available on the latest releases. Thanks all!

**Comment by cgwalters** [comment]
Sorry for the regression here, I am pretty embarrassed by it and will be more careful to avoid the possibility of things like this in the future.

**Comment by dghubble** [comment]
No worries!

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20220918.1.1`.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220918.2.2`.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `36.20220906.3.2`.
