### ISSUE TITLE
[rawhide] 38.20221007.91.0: `kdump.crash` test fails to enable kdump.service

### ISSUE THREAD

**Issue by gursewak1997** [coreos/fedora-coreos-tracker#1313]
The system fails to enable kdump.service.
```
Oct 06 21:37:11 cosa-devsh kdumpctl[1291]: grep: warning: stray \ before -
Oct 06 21:37:11 cosa-devsh kdumpctl[1322]: /lib/kdump/kdump-lib.sh: line 192: bad substitution: no closing `}' in ${_src#${_src_nofsroot}[}
Oct 06 21:37:11 cosa-devsh kdumpctl[1170]: kdump: mkdumprd: failed to make kdump initrd
Oct 06 21:37:11 cosa-devsh kdumpctl[1170]: kdump: Starting kdump: [FAILED]
Oct 06 21:37:11 cosa-devsh systemd[1]: kdump.service: Main process exited, code=exited, status=1/FAILURE
Oct 06 21:37:11 cosa-devsh systemd[1]: kdump.service: Failed with result 'exit-code'.
Oct 06 21:37:11 cosa-devsh systemd[1]: Failed to start kdump.service - Crash recovery kernel arming.
```

**Comment by gursewak1997** [comment]
Looks like there is a bug with `bash`. Pinning the bash package to version `5.1.16-3.fc36` seems to fix the problem for now.

**Comment by jlebon** [comment]
It'd be good here to find here which bash rawhide update broke it exactly. Looking at the actual failure, it may have been a conscious backwards compatibility breakage and the fix would need to happen in kdump. But we could start with a bug report against rawhide bash.

**Comment by gursewak1997** [comment]
Filed a BZ against bash: https://bugzilla.redhat.com/show_bug.cgi?id=2133097

**Comment by dustymabe** [comment]
I think the `bash` pin in `rawhide` got us past the initial failure of `kdump.service` not coming up, but the test still seems to be failing? @gursewak1997 Were you able to get the test to pass?

**Comment by dustymabe** [comment]
The problematic `bash` has landed in `F36` now too. PR to pin in https://github.com/coreos/fedora-coreos-config/pull/2007

**Comment by dustymabe** [comment]
now that https://bodhi.fedoraproject.org/updates/FEDORA-2022-a4c93461e4 is available let's replace the `bash` pin with a fast-track.

**Comment by gursewak1997** [comment]
Closing this since the kdump.service itself gets enabled without the `bash` substitution error
