### ISSUE TITLE
docker compose v2 installation

### ISSUE THREAD

**Issue by sgohl** [coreos/fedora-coreos-tracker#1316]
**Describe the bug**

Trying to follow the installation steps of https://github.com/docker/compose#linux

neither placing the `docker-compose` binary from the releases-page into `~/.docker/cli-plugins` nor `/usr/local/libexec/docker/cli-plugins` made `docker` realize the cli-plugin, like it does on Fedora Workstation 36, for example.

```
VERSION="36.20221001.2.0 (CoreOS)"

docker version
Client:
 Version:           20.10.18
 Git commit:        aa7e414
 OS/Arch:           linux/amd64
 Experimental:      true

Server:
 Engine:
  Version:          20.10.18
  Git commit:       f756502
  Experimental:     true
```

It seems, the mentioned paths, especially these which are writable, are not considered by the docker installation which is onboard with fedora coreos.

**Reproduction steps**

```
mkdir -p /usr/local/libexec/docker/cli-plugins
cd /usr/local/libexec/docker/cli-plugins
curl -Lo docker-compose https://github.com/docker/compose/releases/download/2.11.2/docker-compose-linux-x86_64
chmod +x docker-compose
```

results in
```
> docker compose

docker: 'compose' is not a docker command.
See 'docker --help'
```

**Expected behavior**

`docker` should consider the paths mentioned in the compose v2 repository

**Additional information**

Perhaps there is another way to get the `docker compose` v2 feature, I am not aware of?

**Comment by dustymabe** [comment]
Hi @sgohl - is there a version of Fedora CoreOS where this worked?

**Comment by sgohl** [comment]
No, I never tried this before. It's the first time I want to try compose v2 on coreos

**Comment by sgohl** [comment]
oh boy, thats embarrassing :sheep: 

I took the url from a script, replaced the version variable but forgot the prepending `v`
since the file downloaded I didn't check it was the actual binary
lets forget this ever happened :D
