### ISSUE TITLE
Conference: Kubernetes Community Days France 2023

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1319]
See https://community.cncf.io/events/details/cncf-kcd-france-presents-kubernetes-community-days-france-2023/

> We'd love to hear you! The CFP is now open and will close on the 31th of October. 
>
> You can submit your applications here: https://cfp.kcdfrance.fr
>
> For any CFP related question, please reach out to cfp@kcdfrance.fr
> 
> Schedule will be announced on the 17th of January 2023.

I'll likely attend and I'm planning on submitting a talk about Fedora CoreOS, OKD, SCOS (maybe) or maybe even mention Typhoon. Any ideas or suggestions for a talk are welcomed!

CC @LorbusChris

**Comment by vrutkovs** [comment]
Definitely worth mentioning Typhoon / MicroShift / Fedora IOT as related project (that'd highlight how FCOS spurs innovation). On distro side some things worth including are OperatorHub and SCOS definitely (as an example how rpm-ostree is flexible and you can build a new distro reusing OKD bits)

**Comment by LorbusChris** [comment]
Thank you, Timothée!
I'm interested, and others from the OKD/SCOS team might be too!
@sherine-k @aleskandro @lmzuccarelli

To add to the list of related projects, we joined the CentOS Cloud SIG recently with that effort.

**Comment by travier** [comment]
This has happened.
