### ISSUE TITLE
blkio cgroup leak

### ISSUE THREAD

**Issue by paulnivin** [coreos/fedora-coreos-tracker#1330]
### Describe the bug

blkio cgroups started leaking in stable release 36.20220906.3.0. For testing-devel, cgroups started leaking in 36.20220902.20.0.

The FCOS changeset between 36.20220831.20.0 (does not leak) and 36.20220902.20.0 (leaks) contains the kernel bump from 5.18 to 5.19 https://github.com/coreos/fedora-coreos-config/compare/50ee01a89075d8ef204f1f40c5d89ab060748aac...d982427cd012acaaa48310a73929e0112ddb167c

We run FCOS with Kubernetes 1.22 with cri-o for our production environment. The kubelet contains cAdvisor which continuously reads /sys/fs/cgroup stats, including blkio. As blkio cgroups leak, `blkio.throttle.io_service_bytes_recursive` files take longer and longer for cAdvisor to read, holding locks in the kernel, which results in kernel scheduling issues. We first observed this issue via a p99 latency increase across multiple services, where severity was correlated with system uptime. For heavily loaded systems, the end result of this bug is very similar to the widely publicized (and since fixed) memory cgroup leak.

### Reproduction steps

1. boot any FCOS image running a 5.19 kernel
2. login as core
3. run:
```bash
for x in {1..5}; do
    sudo podman run -it --rm docker.io/amazon/aws-cli:2.0.41 "--version"
    grep blkio /proc/cgroups
done
```
4. repeat runs of the shell script to observe blkio cgroups not being cleaned up

### Expected behavior

blkio num_cgroups count should not permanently increase.

For example on 36.20220831.20.0:
```
aws-cli/2.0.41 Python/3.7.3 Linux/5.18.19-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	94	1
aws-cli/2.0.41 Python/3.7.3 Linux/5.18.19-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	94	1
aws-cli/2.0.41 Python/3.7.3 Linux/5.18.19-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	94	1
aws-cli/2.0.41 Python/3.7.3 Linux/5.18.19-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	94	1
aws-cli/2.0.41 Python/3.7.3 Linux/5.18.19-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	94	1
```

### Actual behavior

blkio num_cgroups count permanently increases.

For example on 36.20220902.20.0:
```
aws-cli/2.0.41 Python/3.7.3 Linux/5.19.6-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	95	1
aws-cli/2.0.41 Python/3.7.3 Linux/5.19.6-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	96	1
aws-cli/2.0.41 Python/3.7.3 Linux/5.19.6-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	97	1
aws-cli/2.0.41 Python/3.7.3 Linux/5.19.6-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	98	1
aws-cli/2.0.41 Python/3.7.3 Linux/5.19.6-200.fc36.x86_64 docker/x86_64.amzn.2
blkio	0	99	1
```

### System details

Initially observed on AWS. Testing to narrow down the problematic changeset and simplify reproduction was performed on QEMU.

```
State: idle
BootedDeployment:
* fedora:fedora/x86_64/coreos/testing-devel
                  Version: 36.20220902.20.0 (2022-09-02T23:42:02Z)
                   Commit: 82840659972d810379c9ac66bf7605006c7dbc33a6c30177d90633e9c24d9dbd
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
```

### Ignition config

```yaml
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa ...
```

### Additional information

For the simple reproduction of the blkio leak provided above, podman needs to be run as root.

Even though userspace should not be capable of causing this issue, I also tried podman 4.3.0 via https://bodhi.fedoraproject.org/updates/FEDORA-2022-658b2dbea2 and was able to reproduce the issue in the same manner.

I was also able to reproduce this issue on rawhide 38.20221026.91.0 running a 6.1 kernel.

**Comment by travier** [comment]
From your description, this looks like an easily reproductible kernel bug. Can you file a bugzilla for the kernel in https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora ? Thanks

**Comment by travier** [comment]
And thanks for the detailed report and investigation!

**Comment by paulnivin** [comment]
Thanks. I've filed https://bugzilla.redhat.com/show_bug.cgi?id=2138418

**Comment by paulnivin** [comment]
We've deployed the following mitigation in prod for cgroupsV1, which allows our FCOS/podman/kubelet/cri-o environment w/ systemd-managed cgroups to function without leaking blkio cgroups:

```yaml
variant: fcos
version: 1.4.0
kernel_arguments:
  should_exist:
    - systemd.unified_cgroup_hierarchy=0
systemd:
  units:
    - name: -.slice
      contents: |
        [Slice]
        DisableControllers=blkio
```

**Comment by aneagoe** [comment]
@paulnivin does this affect cgroupsV1 exclusively? Unfortunately, there doesn't seem to be any traction to get this fixed...

**Comment by paulnivin** [comment]
This issue affects both cgroupsV1 and cgroupsV2. The mitigation, referenced above, only works for cgroupsV1.

**Comment by paulnivin** [comment]
We've been running with `blkio` disabled for multiple months. Re-tested this issue with the current stable release `37.20230122.3.0` running kernel `6.1.6-200.fc37.x86_64` and this bug is no longer present. Confirmed fixed for both cgroupsV1 and cgroupsV2.

**Comment by dustymabe** [comment]
Thank you @paulnivin for reporting back on this. I'm glad the issue is resolved now!
