### ISSUE TITLE
github overview links to old coreos.com site

### ISSUE THREAD

**Issue by osresearch** [coreos/fedora-coreos-tracker#1334]
### Describe the bug

![image](https://user-images.githubusercontent.com/3068843/199548145-1963f909-43ff-4365-868f-3f882b1dbfa5.png)

The link to http://coreos.com should probably be https://getfedora.org/coreos/ (or a redirect created at the old site if possible)

### Reproduction steps

1. Load the main github page https://github.com/coreos
2. Click the link to `http://coreos.com`
3. `DNS_PROBE_FINISHED_NXDOMAIN`

### Expected behavior

CoreOS overview loads.

### Actual behavior

`NXDOMAIN` error

### System details

Lynx Version 2.9.0dev.5

**Comment by bgilbert** [comment]
Good catch, and thanks for the report!  @ashcrow, can you handle this one?

**Comment by ashcrow** [comment]
Will do!

**Comment by ashcrow** [comment]
Link updated to https://getfedora.org/coreos
