### ISSUE TITLE
libxml2 update to 2.10.3 breaks ABI by removing 111 symbols

### ISSUE THREAD

**Issue by fifofonix** [coreos/fedora-coreos-tracker#1336]
### Describe the bug

Open-vm-tools vgauthd.service fails on the `next` FedoraCoreOS stream (37.20221031.1.0 (2022-11-02T09:38:17Z)) with an error in the journal referencing an undefined symbol 'xmlIOFTPRead'.

### Reproduction steps

On a FedoraCoreOS `next` VM steps to Reproduce:
1. rpm-ostree install open-vm-tools
2. reboot
3. login (systemd unit failure will show)

Also, reproducible by launching a FedoraCoreOS container `podman run -it quay.io/fedora/fedora-coreos:next-devel`:
1. rpm-ostree install open-vm-tools
2. /usr/bin/VGAuthService -s

### Expected behavior

No systemd unit failures

### Actual behavior

Systemd unit fails

### System details

● fedora:fedora/x86_64/coreos/next
                  Version: 37.20221031.1.0 (2022-11-02T09:38:17Z)
               BaseCommit: a153c4842ff66725f3fee4a2c6d77461a804c9dd49adffdbef7160b111ef66c1
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
          LayeredPackages: open-vm-tools

### Additional information

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2139849

Github: https://github.com/vmware/open-vm-tools/issues/621

**Comment by dustymabe** [comment]
Renaming to more appropriately reflect the problem package.

Tracked at https://bugzilla.redhat.com/show_bug.cgi?id=2139546

**Comment by dustymabe** [comment]
Fast track of the new fixed packages in:

- https://github.com/coreos/fedora-coreos-config/pull/2060
- https://github.com/coreos/fedora-coreos-config/pull/2061

**Comment by fifofonix** [comment]
Confirmed @dustymabe that `open-vm-tools` runs fine in the latest `next-devel` with upgraded packages.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20221106.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20221030.2.3`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The `stable` stream was never affected by this issue.
