### ISSUE TITLE
kola: scos: new NetworkManager 1.41.3 breaks network tests

### ISSUE THREAD

**Issue by HuijingHei** [coreos/fedora-coreos-tracker#1338]
The `ext.config.networking.default-network-behavior-change` and `ext.config.networking.mtu-on-bond-ignition` tests both fail with the new NetworkManager that got pulled in recently:

`NetworkManager 1:1.40.0-1.el9-> 1:1.41.3-1.el9`

Same reason with fcos, see https://github.com/coreos/fedora-coreos-tracker/issues/1325

**Comment by dustymabe** [comment]
Is there an action for Fedora CoreOS to take on this issue?

**Comment by HuijingHei** [comment]
Oh, sorry, seems this the wrong place, I will move it to os
