### ISSUE TITLE
How to install ZFS

### ISSUE THREAD

**Issue by sgohl** [coreos/fedora-coreos-tracker#1342]
### Describe the enhancement

I am trying, without success, to get ZFS anyhow working on coreos. 

I don't need it for root/boot, just for additional disks.

Is there any option I am just not aware of? I found and tested a gist which uses koji (but does not have the current kernel available), but I think then my systems break on the next zincati update.

I would also go with zfs-fuse if there's no other way, but that systemd-unit errors:
```
Nov 14 19:20:47 test zfs-fuse-helper[2284]: /usr/sbin/zfs-fuse-helper: line 4: /etc/rc.d/init.d/functions: No such file or directory
Nov 14 19:20:47 test zfs-fuse-helper[2286]: /usr/sbin/zfs-fuse-helper: line 22: pidofproc: command not found
Nov 14 19:20:47 test zfs-fuse-helper[2284]: Huh?
```

I guess that rpm-package is not compatible with coreos and I'd rather have it as kernel module, anyway.

Although I've not done it before, I would consider building a custom coreos via cosa, if that's the last option?

Thanks in advance for any help! 

### System details

bare metal / vmware esx

**Comment by travier** [comment]
How are you getting the ZFS source / pacakges? One option is to create a akmods package for the module so that it gets rebuilt on update. Another one is to build via a container before updates.

**Comment by sgohl** [comment]
I'm not sure if I should link the gist here, because it's from someone else. It downloads the source from https://github.com/openzfs/zfs/releases/download

But as said, that script does not work at all for me.

akmod sounds good, but I lack the complete knowledge how to put that into coreos systems

> Another one is to build via a container before updates.

that sounds like zincati has a pre-update hook?

**Comment by sgohl** [comment]
since you mentioned akmod - I found a related github issue: https://github.com/openzfs/zfs/issues/12641 where is stated that akmod is not available on coreos - did that change in the meantime?

**Comment by dustymabe** [comment]
@sgohl - there's not an easy answer to this problem.

I will point out that I think this use case (out of tree kernel modules) might be a good case for OSTree native containers (also known as CoreOS Layering). We should add an example of how to build an out of tree kernel module and use that to https://github.com/coreos/coreos-layering-examples

**Comment by jmarrero** [comment]
I created a issue a few days back: https://github.com/coreos/coreos-layering-examples/issues/40

I will try to get an example ready during this week.

**Comment by travier** [comment]
An example has been pushed in https://github.com/coreos/layering-examples/tree/main/build-zfs-module

**Comment by sgohl** [comment]
I just tried this and I am possibly missing a step or do it completely wrong 

I used an existing coreos machine to build the image (using docker)
```
coreos ~/layering-examples/build-zfs-module > docker build -t myregistry.acme.corp/pub/coreos:latest -f Containerfile  .
...
docker push myregistry.acme.corp/pub/coreos:latest
...
coreos ~ > rpm-ostree rebase ostree-unverified-registry:myregistry.acme.corp/pub/coreos:latest --experimental
Pulling manifest: ostree-unverified-image:docker://docker.unitedprint.rdb/pub/coreos:latest
error: remote error: getting username and password: 1 error occurred:
	* reading JSON file "/run/containers/62011/auth.json": open /run/containers/62011/auth.json: permission denied
```

what's the authentication it's talking about?

And what I don't understand: I always use the `quay.io/coreos/coreos-installer:release` image to install a bare-metal system or to get the vmware-ova to install on vsphere esx.

Is it even possible to produce an image that can be installed with `coreos-installer` ?

**Comment by jmarrero** [comment]
@sgohl try loging in to your private repository using `/etc/ostree/auth.json` as your auth file path. i.e.
```
podman login --authfile /etc/ostree/auth.json myregistry.acme.corp
```
This is a gap in our doc that will be addressed soon:  https://github.com/coreos/rpm-ostree/issues/4180

As for generating new images from layered images, this is another open enhancement/issue we are tracking here: https://github.com/coreos/fedora-coreos-tracker/issues/1151

**Comment by cgwalters** [comment]
> * reading JSON file "/run/containers/62011/auth.json": open /run/containers/62011/auth.json: permission denied

For unauthenticated images, this is [this issue](https://github.com/coreos/rpm-ostree/issues/4107) which is fixed in https://github.com/coreos/rpm-ostree/releases/tag/v2022.15

**Comment by sgohl** [comment]
in my case, the image is in the /pub space of the registry, so no auth is requested or required.

> perfect example of a bug that'd be caught by "real" systems testing

yeah, we all have been there :-D

for the records, though I think I'm very alone with this, I can not use podman because my registry uses an old certificate which can not yet be exchanged

Error: initializing source docker://registry.acme.corp/pub/coreos:latest: pinging container registry docker.unitedprint.rdb: Get "https://registry.acme.corp/v2/": x509: certificate relies on legacy Common Name field, use SANs instead


I wish you would consider including the zfs kernel module in the official coreos build - it wouldn't be very much disk space, i think. I know of some people who did not choose CoreOS because of missing ZFS, also ...

**Comment by dustymabe** [comment]
> I wish you would consider including the zfs kernel module in the official coreos build - it wouldn't be very much disk space, i think. I know of some people who did not choose CoreOS because of missing ZFS, also ...

That's a `Fedora` [issue](https://fedoraproject.org/wiki/ZFS), not a `Fedora CoreOS` one.

**Comment by sgohl** [comment]
> licensing issues

oh right, there was something with CDDL

But as I said initially, I would absolutely try to create my own coreos iso/ova/whatever, if I only knew how to do it. These tools like cosa are a book of seven seals to me, unfortunately. 

Docs seem to require that you already have base knowlege, but lack examples. 

An example how to do it on a coreos machine would be superior. I'm not sure if I like this container native ostree approach, but I still don't understand half of it yet since I was stuck at the first attempt, but I know, this is out of the scope of this issue :laughing:

**Comment by dustymabe** [comment]
Since there has been an [example pushed](https://github.com/coreos/fedora-coreos-tracker/issues/1342#issuecomment-1323994878) for this I don't see much else to do here. Closing.

**Comment by ItalyPaleAle** [comment]
I am struggling to get this to work, following the example. I can see the RPMs installed in the layer with `rpm -qa`. But when I try to use the commands I get an error such as:

```
$ sudo zfs list
The ZFS modules cannot be auto-loaded.
Try running 'modprobe zfs' as root to manually load them.
```

And modprobe:

```
$ sudo modprobe zfs
modprobe: FATAL: Module zfs not found in directory /lib/modules/6.5.11-300.fc39.x86_64
```

For reference:

```
$ uname -a
Linux atlas 6.5.11-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov  8 22:37:57 UTC 2023 x86_64 GNU/Linux

$ rpm -qa | grep zfs
zfs-debugsource-2.2.2-1.fc39.x86_64
zfs-debuginfo-2.2.2-1.fc39.x86_64
libzfs5-2.2.2-1.fc39.x86_64
zfs-kmod-debugsource-2.2.2-1.fc39.x86_64
kmod-zfs-6.5.11-300.fc39.x86_64-2.2.2-1.fc39.x86_64
zfs-2.2.2-1.fc39.x86_64
kmod-zfs-6.5.11-300.fc39.x86_64-debuginfo-2.2.2-1.fc39.x86_64
libzfs5-debuginfo-2.2.2-1.fc39.x86_64
```

**Comment by sgohl** [comment]
I wasn't happy with all the provided workarounds. 4 years later, I decided to switch to bootc and try again installing ZFS
This is how I did it now, not being sure this is optimal, but it works, i can create a zpool with 
```
zpool create -m /var/zpool zpool /dev/vdb
```

```Containerfile
FROM quay.io/fedora/fedora-coreos:44.20260621.3.1
RUN dnf install -y "https://zfsonlinux.org/fedora/zfs-release-3-1$(rpm --eval '%{dist}').noarch.rpm" && \
    KERNEL_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    KERNEL_PACKAGE_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}')" && \
    KERNEL_PACKAGE_RELEASE="$(rpm -q kernel-core --queryformat '%{RELEASE}')" && \
    KERNEL_ARCH="$(rpm -q kernel-core --queryformat '%{ARCH}')" && \
    dnf install -y "https://kojipkgs.fedoraproject.org/packages/kernel/${KERNEL_PACKAGE_VERSION}/${KERNEL_PACKAGE_RELEASE}/${KERNEL_ARCH}/kernel-devel-${KERNEL_VERSION}.rpm" && \
    dnf install -y zfs zfs-dkms && \
    ZFS_VERSION="$(rpm -q zfs-dkms --queryformat '%{VERSION}')" && \
    dkms install -m zfs -v "${ZFS_VERSION}" -k "${KERNEL_VERSION}"
```
