### ISSUE TITLE
Live environment only allocates 20% of RAM for ephemeral `/var`

### ISSUE THREAD

**Issue by UnconventionalMindset** [coreos/fedora-coreos-tracker#1344]
### Describe the bug

I am provisioning my Fedora Core OS from RAM. However when running I see the filesystem is of 683M only (iso size I suppose).

The docs do not explain if I am supposed to resize the filesystem or what and when using the OS I have no space left on device.

### Reproduction steps

1. Create iPXE install script: https://gist.github.com/UnconventionalMindset/f4ca2d66b943f916b5fecfad698b47ea
2. Create your installation Butane and generate an Ignition from it: https://github.com/UnconventionalMindset/coreos-setup/blob/main/coreos.bu
3. Embed it to iPXE: https://gist.github.com/UnconventionalMindset/9c9daa66727e7f45a85bad30a7844caa
4. Run it in Proxmox
5. Pull an image like the one from LinuxServer.io of homeassistant.

### Expected behavior

Filesystem should be as big as the size of the RAM and the image should be pulled successfully.

### Actual behavior

Filesystem is as big as the size of the ISO and the image cannot be saved due to not enough space left.

![image](https://user-images.githubusercontent.com/11658632/202981448-cf619071-288c-4fd1-bb1b-cf8a9f60190d.png)

### System details

- 36.20221001.3.0 stable
- Proxmox VE 7.2-11
- iPXE install script: https://gist.github.com/UnconventionalMindset/f4ca2d66b943f916b5fecfad698b47ea
- Script to embed to iPXE: https://gist.github.com/UnconventionalMindset/9c9daa66727e7f45a85bad30a7844caa

### Ignition config

Install butane: https://github.com/UnconventionalMindset/coreos-setup/blob/main/coreos.bu
Install ignition: https://github.com/UnconventionalMindset/coreos-setup/blob/main/coreos.ign

**Comment by UnconventionalMindset** [comment]
I am running from RAM: https://docs.fedoraproject.org/en-US/fedora-coreos/live-booting/
So I am not installing to disk but running the live. Also I am using iPXE not PXE.

![image](https://user-images.githubusercontent.com/11658632/203178042-833545f0-e458-4bd4-ab28-c8d9856c3ba1.png)

![image](https://user-images.githubusercontent.com/11658632/203178156-bf739949-c4d0-4e80-b3e9-d38b379bd32b.png)

![image](https://user-images.githubusercontent.com/11658632/203178247-932a376d-6892-462e-8b2a-f4750e73e3db.png)

**Comment by bgilbert** [comment]
> Filesystem should be as big as the size of the RAM

tmpfs filesystems are limited to half of RAM by default.  However, our PXE live image uses an ephemeral XFS, not a tmpfs, and it's [sized](https://github.com/coreos/fedora-coreos-config/blob/b04dc5eb6ae6a2019a2029628af501b7cb99481f/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-live/live-generator#L188) to be the same size as `/run` (minus filesystem overhead).  And `/run` is [sized](https://github.com/systemd/systemd/blob/41fca8686f694c38d7a1d5623d947ec1e7573aaa/src/basic/mountpoint-util.h#L25) to 20% of RAM, which seems small.  So we should probably increase the ephemeral XFS size.

**Comment by bgilbert** [comment]
Yup, I've added pending-action.  I think the fix should be uncontroversial.

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/fedora-coreos-config/pull/2188

**Comment by UnconventionalMindset** [comment]
That PR looks interesting, I wonder if I could also use 100% of RAM? Or would there be any reason why that would not be ok?
I am asking since I am also assembling my own coreos version with custom config right now.

**Comment by bgilbert** [comment]
You need to reserve enough RAM for the system to operate.  If the filesystem grows to consume all available RAM, the system will deadlock.

**Comment by bgilbert** [comment]
This also affects RHEL 9 RHCOS.

**Comment by mike-nguyen** [comment]
Fixed here: 
https://github.com/coreos/fedora-coreos-config/pull/2188
https://github.com/coreos/fedora-coreos-config/commit/7205d4152399141b246d3545fff9df5fd4757f58

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20230303.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20230303.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20230303.3.0`.
