### ISSUE TITLE
`amd-gpu-firmware`  no longer being installed between stable to testing

### ISSUE THREAD

**Issue by anthr76** [coreos/fedora-coreos-tracker#1345]
Greetings!

It appears `amd-gpu-firmware`  was present in `36.20221030.3.0` but no longer  in`37.20221106.2.1` . Doing a quick browse around I don't see this explicitly excluded so I assume it was a dependency of something and is no longer.

Are there any thoughts around this or more context known? At least for my usecase I use the https://github.com/RadeonOpenCompute/k8s-device-plugin for various workloads.

I'm happy to layer this in, but more or less wanted to bring awareness incase this package removal wasn't desired.

**Comment by dustymabe** [comment]
Hey @anthr76 - thanks for opening the issue.

Recently the GPU firmwares were [broken out into subpackages](https://src.fedoraproject.org/rpms/linux-firmware/c/6e605212ebbc6b5477dd397a4cb96a7bff5d4da0?branch=rawhide) and marked as [required for Fedora 36](https://src.fedoraproject.org/rpms/linux-firmware/c/f2089ed603bef42c788fe80c3fbdbfc38475df73?branch=rawhide), but only recommends for F37+. In FCOS we default to not install recommends, but this was clearly a case where functionality was included and later removed.

I suspect we should add back in these packages to get back to the status quo, but there may be a good argument for not adding them back. I'll try to bring it up at our community meeting on Wednesday.

**Comment by cgwalters** [comment]
Adding them back makes sense to me.

**Comment by travier** [comment]
For reference: Intel GPUs are made available via https://github.com/intel/intel-device-plugins-for-kubernetes

**Comment by dustymabe** [comment]
We discussed this at the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/2TQAH4J42SG6ZDM3KQ2PBLPESBXP64FT/).

```
11:57:08   dustymabe | #agreed we will add the amd-gpu-firmware  
                     | intel-gpu-firmware nvidia-gpu-firmware packages back
                     | to FCOS to restore the previous functionality we had
                     | and open a new ticket to discuss the merits of these
                     | packages and if we ever want to remove them in the
                     | future.
```

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20221127.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
This issue never affected our `stable` stream.
