### ISSUE TITLE
github/coreos: transfer two repos and crates to this organization

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-tracker#1347]
There are two Rust libraries that are currently living under my personal GH namespace and for which I'm the sole owner.
While I plan to keep looking at both of them, they are consumed by CoreOS projects so it would be good to move under this github organization and gain an additional owner (mostly for disaster recovery).
Those are:
 * https://github.com/lucab/vmw_backdoor-rs
 * https://github.com/lucab/envsubst-rs

I can take care of updating crates permission, but I think I'd need some organization admin to help me with moving the GH repos.

**Comment by travier** [comment]
CC @ashcrow

**Comment by lucab** [comment]
I've added https://crates.io/teams/github:coreos:fedora-coreos-crates-owners as an additional owner of both crates:
```
$ echo "envsubst vmw_backdoor" | xargs -n1 cargo owner --add github:coreos:fedora-coreos-crates-owners

       Owner team github:coreos:fedora-coreos-crates-owners has been added as an owner of crate envsubst

       Owner team github:coreos:fedora-coreos-crates-owners has been added as an owner of crate vmw_backdoor
```

**Comment by lucab** [comment]
Repositories moved today. Both crates now need to have a new version published to update URLs.

**Comment by bgilbert** [comment]
Repositories configured!
