### ISSUE TITLE
FOSDEM 2023: Image Based Linux dev room

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1348]
From  https://uapi-group.org/docs/conferences/2023-02-04__fosdem-devroom/:

> Image-Based Linux and Secure/Measured Boot Devroom @ FOSDEM 23
> The UAPI group, a community for people with an interest in innovating how we build, deploy, run, and update modern security-focused Linux operating systems, will host a devroom at FOSDEM 2023. A “devroom” (a FOSDEM term) is a co-located mini-conference with its own separate track.
>
> FOSDEM is a free event for software developers to meet, share ideas and collaborate. It takes place on February 4 and 5 at the ULB Solbosch Campus in Brussels, Belgium. Learn more at https://fosdem.org/2023/.
>
> Our half-day devroom will open on Saturday morning and close at noon. Drop in for talks on Image-based Linux and secure / attestable systems, and for a chat with UAPI folks.

> Call for Participation
> We are looking for your talk proposals!
> Talks are 20 minutes, on-site.
> CfP deadline is Saturday, Dec 10, 2022.
> Topics include:

> Image-based Linux distributions: intro, concepts, updates, differences with other distros
> OS and kernel image formats
> Cross-distro specifications and standards (e.g.: https://uapi-group.org/)
> Trustable boot, device attestation, TPM usage and tooling
> A/B update implementations
> as well as topics related to the above.

If you're planning on attending FOSDEM, giving a talk about FCOS there is a good opportunity.

**Comment by travier** [comment]
Tagging for the meeting just to mention it.

**Comment by dustymabe** [comment]
The call for papers has closed here.
