### ISSUE TITLE
evaluate inclusion of GPU firmware

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1350]
The GPU firmware for amd/intel/nvidia were [broken out into subpackages](https://src.fedoraproject.org/rpms/linux-firmware/c/6e605212ebbc6b5477dd397a4cb96a7bff5d4da0?branch=rawhide) recently. We should evaluate if we want to continue to include them in Fedora CoreOS or if we think the space savings would be worth the change and added documentation for our users.

We discussed this briefly in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/2TQAH4J42SG6ZDM3KQ2PBLPESBXP64FT/) when we were discussing https://github.com/coreos/fedora-coreos-tracker/issues/1345 but agreed to revisit in the future.

The total size is about about 30MiB:

```
rpm -q --queryformat='%{NAME} %{SIZE}\n' amd-gpu-firmware intel-gpu-firmware nvidia-gpu-firmware
amd-gpu-firmware 22563853
intel-gpu-firmware 8164427
nvidia-gpu-firmware 1262337
```

**Comment by dustymabe** [comment]
I'll put off this discussion in the meeting until after the new year since it's not time sensitive.

**Comment by jlebon** [comment]
We discussed this in [today's community meeting](https://meetbot-raw.fedoraproject.org//fedora-meeting-1/2023-03-01/fedora_coreos_meeting.2023-03-01-16.30.txt):

> * AGREED: we will keep the firmwares for now as users currently rely on them. we may in the future remove them as part of a larger space-savings initiative.  (jlebon, 17:21:49)

We also agreed to close this ticket. We can track any future space-savings initiative in a separate ticket where these packages may come up again.
