### ISSUE TITLE
include crun 1.7

### ISSUE THREAD

**Issue by M1cha** [coreos/fedora-coreos-tracker#1354]
### Describe the enhancement

crun 1.6 has a bug which prevents running certain containers in user namespaces:
https://github.com/containers/crun/issues/1019

Due to this I'd prefer crun 1.7 to be available in `stable`, but right now it's not even in `next`.

**Comment by dustymabe** [comment]
It was pulled in 9 days ago to `testing-devel`. Will be in this week's `testing` stream release.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20221127.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20221127.2.0`. Please try out the new release and report issues.

**Comment by M1cha** [comment]
works great, thx.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20221127.3.0`.
