### ISSUE TITLE
Is there a way to have coreos populate the first disk on s390x host?

### ISSUE THREAD

**Issue by skycastlelily** [coreos/fedora-coreos-tracker#1355]
### Describe the enhancement

if there are more than one disk ,coreos will  populate the first disk, ie,/dev/vda,which is wanted behavior, on x86_64 or aarch64 host,but on s390x,it will populate  a random disk,which will bring some inconvenience when I automate coreos testcases with three disks 
Here is the command I use:

```
 virt-install --connect="qemu:///system" \
    --name="${VM_NAME}" --vcpus="${VCPUS}" \
    --memory="${RAM_MB}" --os-variant="fedora-coreos-$STREAM" \
    --import --graphics=none --network bridge=virbr0 \
    --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${IGNITION_CONFIG}" \
    --disk="size=${DISK_GB},backing_store=${IMAGE}" \
    --disk="size=${DISK_GB},format=qcow2,path=/var/lib/libvirt/images/test.qcow2" \
    --disk="size=${DISK_GB},format=qcow2,path=/var/lib/libvirt/images/test2.qcow2"
```

### System details

fedora-coreos-37.20221127.1.0-qemu.s390x.qcow2

**Comment by dustymabe** [comment]
I'm trying to figure out what problem you are trying to describe here. I think you are saying that the `--disk="size=${DISK_GB},backing_store=${IMAGE}"` argument you are using consistently is associated with `/dev/vda` on `x86_64` and `aarch64`, but gets a seemingly random device name on `s390x`. Is that right?

**Comment by skycastlelily** [comment]
Yes,sorry for failing to describe it clearly,I can use /dev/disk/by-path/ to get the wanted disks,but I have to add more lines to my automate code.So I'm thinking it will be great if there is a way :)

**Comment by jlebon** [comment]
You can add a serial to the disk like this:

```
--disk="size=${DISK_GB},backing_store=${IMAGE}",serial=foobar
```

And it'll show up in the VM as `/dev/disk/by-id/virtio-foobar`.

**Comment by dustymabe** [comment]
@skycastlelily - does that work for you? Let's close out this issue if so.

**Comment by skycastlelily** [comment]
yes,thanks both of you^^
