### ISSUE TITLE
New Package Request: audit

### ISSUE THREAD

**Issue by c4rt0** [coreos/fedora-coreos-tracker#1362]
### What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

```
[root@cosa-devsh ~]# rpm-ostree install --dry-run audit
...
Installing 2 packages:
  audit-3.0.9-1.fc37.x86_64 (fedora)
  initscripts-service-10.17-1.fc37.noarch (fedora)
```

### What is the size of the package and its dependencies?

```
$ rpm -qi audit

Name        : audit
Version     : 3.0.9
Release     : 1.fc37
Architecture: x86_64
Install Date: Sat 05 Nov 2022 09:00:50
Group       : Unspecified
Size        : 684113
License     : GPLv2+
Signature   : RSA/SHA256, Tue 30 Aug 2022 00:18:08, Key ID f55ad3fb5323552a
Source RPM  : audit-3.0.9-1.fc37.src.rpm
Build Date  : Mon 29 Aug 2022 23:06:47
Build Host  : buildvm-x86-26.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://people.redhat.com/sgrubb/audit/
Bug URL     : https://bugz.fedoraproject.org/audit
Summary     : User space tools for kernel auditing
```
```
$  rpm -qi initscripts-service                                                                                                                                                                  1 err  11:39:35 
Name        : initscripts-service
Version     : 10.17
Release     : 1.fc37
Architecture: noarch
Install Date: Sat 05 Nov 2022 08:43:04
Group       : Unspecified
Size        : 5832
License     : GPLv2
Signature   : RSA/SHA256, Wed 24 Aug 2022 09:18:04, Key ID f55ad3fb5323552a
Source RPM  : initscripts-10.17-1.fc37.src.rpm
Build Date  : Wed 24 Aug 2022 09:13:16
Build Host  : buildvm-x86-14.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/fedora-sysv/initscripts
Bug URL     : https://bugz.fedoraproject.org/initscripts
Summary     : Support for service command
```

### What problem are you trying to solve with this package? Or what functionality does the package provide?

The audit package contains the user space utilities for storing and searching the audit records generated by the audit subsystem in the Linux 2.6 and later kernels.

### Can the software provided by the package be run from a container?  Explain why or why not.

Yes, in theory, but it's likely not supported and will probably not work well with host filesystem rules.

### Can the tool(s) provided by the package be helpful in debugging container runtime issues?

No

### Can the tool(s) provided by the package be helpful in debugging networking issues?

No

### Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

Yes

### In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

TODO: Fill in bugs tracking that from previous issue

### Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS?

N/A

### Does the software provided by the package have a history of CVEs?

No 

?? https://www.cvedetails.com/product/13730/Linux-Audit.html?vendor_id=33

**Comment by travier** [comment]
For the first question we need the output of `Paste here the output of rpm-ostree install --dry-run <package> from a fresh Fedora CoreOS node.` (see issue template text).

**Comment by travier** [comment]
See also https://github.com/coreos/fedora-coreos-tracker/issues/461

**Comment by c4rt0** [comment]
Updated comment regarding `rpm-ostree` output in the first question.

**Comment by travier** [comment]
For the second question, you should to give us the info for each package listed in the first question.

**Comment by travier** [comment]
Next steps (can be done in parallel):
- Make a PR adding audit to fedore-coreos-config
- Make a PR for https://bugzilla.redhat.com/show_bug.cgi?id=1827263

**Comment by c4rt0** [comment]
Updated comment referring to size of the `initscripts` package

**Comment by travier** [comment]
Hum, we need the info for the `initscripts-service` package, not the `initscripts` one :).

**Comment by c4rt0** [comment]
Off course  😶‍🌫️

**Comment by jlebon** [comment]
IMO, I don't think we should add `initscripts-service` to FCOS as is. It brings back `/usr/sbin/service` which is a legacy API. We discussed in the meeting maybe doing something in postprocessing as a last resort, but ideally we come to an agreement at the packaging level to e.g. lower it to a weak dep maybe and shipping `auditd-{condrestart,reload,restart,resume,rotate,state,stop}` scripts instead (those are the supported `service` actions that rely on direct signaling).

**Comment by travier** [comment]
Looking at https://bugzilla.redhat.com/show_bug.cgi?id=1827263 and the `auditd.service` unit again (https://github.com/linux-audit/audit-userspace/blob/master/init.d/auditd.service), it's not clear to me that we should remove either `auditctl` or `augenrules`.

**Comment by travier** [comment]
Context for service removal:
- https://bugzilla.redhat.com/show_bug.cgi?id=1768815

**Comment by travier** [comment]
The audit package already includes the following scripts (https://github.com/linux-audit/audit-userspace/tree/master/init.d):
```
$ rpm -ql audit-3.0.9-1.fc37.x86_64 | grep legacy
/usr/libexec/initscripts/legacy-actions/auditd
/usr/libexec/initscripts/legacy-actions/auditd/condrestart
/usr/libexec/initscripts/legacy-actions/auditd/reload
/usr/libexec/initscripts/legacy-actions/auditd/restart
/usr/libexec/initscripts/legacy-actions/auditd/resume
/usr/libexec/initscripts/legacy-actions/auditd/rotate
/usr/libexec/initscripts/legacy-actions/auditd/state
/usr/libexec/initscripts/legacy-actions/auditd/stop
```

**Comment by travier** [comment]
The short option is thus just to remove the `service` binary and man page in a post-script.
The long option is to rewrite those as a proper standalone script that is not correlated to the `service` binary.
Another option is to move the `service` binary somewhere else and include a wrapper script that only accepts `auditd` as an option for calls to `service auditd <stop|restart|...>` and rejects everything else.

**Comment by travier** [comment]
Flagging for meeting discussion but I won't be here this week so maybe next week.

**Comment by c4rt0** [comment]
Since I was on a full week course last week, I wonder if there were any debate related to this topic?

**Comment by travier** [comment]
Not yet. There will likely be this week.

**Comment by travier** [comment]
You can check the meeting logs (see the README in this repo) for each meeting.

**Comment by travier** [comment]
Links to existing docs about the `service` interface for audit:
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-starting_the_audit_service
- https://access.redhat.com/solutions/2664811

**Comment by travier** [comment]
Past discussion: https://bugzilla.redhat.com/show_bug.cgi?id=1768815

**Comment by travier** [comment]
We'll have to reach out to the audit maintainers to see which path they would prefer to ideally implement option B.

**Comment by dustymabe** [comment]
We discussed the options from https://github.com/coreos/fedora-coreos-tracker/issues/1362#issuecomment-1408501856 in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/LPN4YNVZSKY4STBZFEOQYNITAQBVSFM6/).

As @travier mentioned in https://github.com/coreos/fedora-coreos-tracker/issues/1362#issuecomment-1431696947 we'd really like to explore option B with the maintainers again before we make a decision here.

**Comment by c4rt0** [comment]
After the discussion had place in the community meeting I automatically assumed someone will contact the maintainers...
I am now wondering if a decision was made about who that contact person should be?

**Comment by dustymabe** [comment]
I think @travier was going to ask, but confirm that with him.

**Comment by travier** [comment]
I've written up https://bugzilla.redhat.com/show_bug.cgi?id=2172600

**Comment by travier** [comment]
https://github.com/linux-audit/audit-userspace/commit/39802bffbfc62501461c916d9ccf748afdff7d94

**Comment by c4rt0** [comment]
Rpm-ostree install results, after the latest `audit` update:

```
[root@cosa-devsh ~]# rpm-ostree install --dry-run audit
...
Installing 2 packages:
  audit-3.1-2.fc37.x86_64 (updates)
  initscripts-service-10.17-1.fc37.noarch (fedora)
```
```
$ rpm -qi audit

Name        : audit
Version     : 3.1
Release     : 2.fc37
Architecture: x86_64
Install Date: Wed 08 Mar 2023 08:55:00
Group       : Unspecified
Size        : 690047
License     : GPL-2.0-or-later AND LGPL-2.0-or-later
Signature   : RSA/SHA256, Thu 09 Feb 2023 17:22:51, Key ID f55ad3fb5323552a
Source RPM  : audit-3.1-2.fc37.src.rpm
```

**Comment by jlebon** [comment]
AFAICT, this still requires an upstream release with https://github.com/linux-audit/audit-userspace/commit/39802bffbfc62501461c916d9ccf748afdff7d94 and making `initscripts-service` a weak dep.

**Comment by c4rt0** [comment]
> > AFAICT, this still requires an upstream release with [linux-audit/audit-userspace@39802bf](https://github.com/linux-audit/audit-userspace/commit/39802bffbfc62501461c916d9ccf748afdff7d94) and making `initscripts-service` a weak dep.
> 
> +1 - We could see if the maintainer was willing to backport those to `rawhide`/`F38` builds to fast-track the change (wouldn't require an upstream release).

@travier - what do you feel about the above?

**Comment by travier** [comment]
Asking for a backport sounds good to me. We should also try to figure out where this is currently documented and add the new command as the prefered way to restart the service.

**Comment by travier** [comment]
Can we get this included in F39?

**Comment by travier** [comment]
To make that happen, we need to replace the calls to `service` with the new auditctl commands in:
- https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_152
- https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_157

Then move `initscripts-service` to a `Recommends`:
- https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_19

Then document in Fedora / FCOS how to manage audit with the new `auditctl` command from:
- https://github.com/linux-audit/audit-userspace/commit/39802bffbfc62501461c916d9ccf748afdff7d94

**Comment by prestist** [comment]
We talked about this in today's [meeting](https://discussion.fedoraproject.org/t/fedora-coreos-meeting-minutes-2023-08-23/87887). Removing meeting label.

AGREED: We'll fix the remaining issues in the audit package and we'll include it in Fedora CoreOS once ready ([spresti](https://meetbot.fedoraproject.org/fedora-meeting-1/2023-08-23/fedora_coreos_meeting.2023-08-23-16.30.log.html#l-174), 17:17:40)

**Comment by c4rt0** [comment]
Thank you for all the above @travier & @prestist - starting to work on it straight away.

**Comment by stevegrubb** [comment]
FYI, audit-4.0 is being targeted for F40. One of the main "features" is splitting auditctl/augenrules from the audit package. The audit package will Require this new package to continue to operate. But this will allow installing only a rules loading service. If that is done, events will be in the journald but there will be no search/reporting utilities available.

Is this split of any interest? Or will it complicate things?

**Comment by c4rt0** [comment]
> To make that happen, we need to replace the calls to `service` with the new auditctl commands in:
> 
> * https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_152
> * https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_157

Created this [PR](https://src.fedoraproject.org/rpms/audit/pull-request/9) to ask if this is what you meant?

> 
> Then move `initscripts-service` to a `Recommends`:

Since until this point I couldn't locate any schema/reference for the `audit.spec` I ask here directly, should I simply insert a line below stating:
```
Recommends: initscripts-service
```

**Comment by dustymabe** [comment]
> FYI, audit-4.0 is being targeted for F40. One of the main "features" is splitting auditctl/augenrules from the audit package. The audit package will Require this new package to continue to operate. But this will allow installing only a rules loading service. If that is done, events will be in the journald but there will be no search/reporting utilities available.

> 
> Is this split of any interest? Or will it complicate things?

I think it is interesting, but I imagine if we ship auditd we'd probably want to ship the search/reporting utilities. The only reason we wouldn't want to is if they were really large or brought in a lot of dependencies, which I don't think they do.

Am I understanding the change correctly?

Either way, thanks for bringing this up!

**Comment by travier** [comment]
> FYI, audit-4.0 is being targeted for F40. One of the main "features" is splitting auditctl/augenrules from the audit package. The audit package will Require this new package to continue to operate. But this will allow installing only a rules loading service. If that is done, events will be in the journald but there will be no search/reporting utilities available.
> 
> Is this split of any interest? Or will it complicate things?

Thanks for the info. I had taken a look at those tools in https://bugzilla.redhat.com/show_bug.cgi?id=1827263#c4. My conclusion was that it was not worth it to split them into distinct packages, at least specifically for Fedora CoreOS. If this planned for F40 as a Recommends, then we can re-consider it again.

**Comment by c4rt0** [comment]
> > Then move `initscripts-service` to a `Recommends`:
> 
> Since until this point I couldn't locate any schema/reference for the `audit.spec` I ask here directly, should I simply insert a line below stating:
> 
> ```
> Recommends: initscripts-service
> ```
Sorry for the noise, never mind - found the details in the packaging guide.

**Comment by c4rt0** [comment]
> To make that happen, we need to replace the calls to `service` with the new auditctl commands in:
> 
> * https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_152
> * https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_157
> 
> Then move `initscripts-service` to a `Recommends`:
> 
> * https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_19

[PR](https://src.fedoraproject.org/rpms/audit/pull-request/9) merged 🎊 
 
> Then document in Fedora / FCOS how to manage audit with the new `auditctl` command from:
> 
> * [linux-audit/audit-userspace@39802bf](https://github.com/linux-audit/audit-userspace/commit/39802bffbfc62501461c916d9ccf748afdff7d94)

Where exactly is the best place for this?
Is it [docs](https://docs.fedoraproject.org/en-US/fedora-coreos/) >System Configuration>Audit or do you maybe have a different location in mind?

**Comment by c4rt0** [comment]
Note: under [RHEL 7 Doccumentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-defining_audit_rules_and_controls#sec-Defining_Audit_Rules_with_auditctl) we have a section dedicated specifically to `defining audit rules`

**Comment by dustymabe** [comment]
Looks like we should be able to pick up [audit-3.1.2-3.fc39](https://koji.fedoraproject.org/koji/buildinfo?buildID=2282572)

**Comment by stevegrubb** [comment]
@travier @dustymabe The reason audit is splitting up the services is that some people want to do remote logging. In this case it has to wait for the network to be up before auditd can be started. By that time, some interesting things could have happened that should have been audited. So, the problem it's solving is to get the rules in place before auditd starts in case it starts later than normal. This has the side effect of allowing people to only log to journald if they wish.

**Comment by travier** [comment]
> > Then document in Fedora / FCOS how to manage audit with the new `auditctl` command from:
> > 
> > * [linux-audit/audit-userspace@39802bf](https://github.com/linux-audit/audit-userspace/commit/39802bffbfc62501461c916d9ccf748afdff7d94)
> 
> Where exactly is the best place for this? Is it [docs](https://docs.fedoraproject.org/en-US/fedora-coreos/) >System Configuration>Audit or do you maybe have a different location in mind?

This looks like a good start.

> Note: under [RHEL 7 Doccumentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-defining_audit_rules_and_controls#sec-Defining_Audit_Rules_with_auditctl) we have a section dedicated specifically to `defining audit rules`

We need something that detail the right commands to stop/restart the service in Fedora CoreOS without service. Kind of the updated version of https://access.redhat.com/solutions/2664811

**Comment by travier** [comment]
> @travier @dustymabe The reason audit is splitting up the services is that some people want to do remote logging. In this case it has to wait for the network to be up before auditd can be started. By that time, some interesting things could have happened that should have been audited. So, the problem it's solving is to get the rules in place before auditd starts in case it starts later than normal. This has the side effect of allowing people to only log to journald if they wish.

Do you mean that this will split the remote login functionality of auditd into a separated component?

I had no idea this even existed. I found https://man7.org/linux/man-pages/man8/audispd-zos-remote.8.html & https://man7.org/linux/man-pages/man5/zos-remote.conf.5.html.

From my perspective, auditd should be used to log to the journal and then the journal should be forwarded to a remote location.

**Comment by stevegrubb** [comment]
The zos-remote is used to forward logs to IBM System Z (s390) data collection systems. The one I'm talking about is [https://linux.die.net/man/8/audisp-remote](https://linux.die.net/man/8/audisp-remote). For Common Criteria, we did support a configuration where systemd-journald-audit.socket was masked and [audisp-syslog](https://www.mankier.com/8/audisp-syslog) was used to push events into rsyslog which was then forwarded to another rsyslog. Doing it this way gets the events into syslog in a better format. (Before forwarding the events, you have to resolve all local uid/gid mappings because the remote system's mapping will be different.)

**Comment by travier** [comment]
Neither RHCOS nor FCOS uses rsyslog anymore. I think we should make sure the "journal route" fits all needs and avoid shipping two "logging daemons" or two "forwarding logs" daemons.

**Comment by stevegrubb** [comment]
The audit project has a [mail list](https://listman.redhat.com/mailman/listinfo/linux-audit). You do not need to be subscribed to send an email to it. (I am the moderator.) Or we can open an issue at either the [audit project](https://github.com/linux-audit/audit-userspace) or CoreOS.

**Comment by travier** [comment]
> The audit project has a [mail list](https://listman.redhat.com/mailman/listinfo/linux-audit). You do not need to be subscribed to send an email to it. (I am the moderator.) Or we can open an issue at either the [audit project](https://github.com/linux-audit/audit-userspace) or CoreOS.

Thanks, posted a review of the RFC in https://github.com/linux-audit/audit-userspace/issues/323

**Comment by travier** [comment]
`audit-3.1.2-3.fc39` should have what we need on the packaging side from https://github.com/coreos/fedora-coreos-tracker/issues/1362#issuecomment-1690335372.

Now we need docs and we can include the package.

**Comment by travier** [comment]
Adding the package to the image should be enough to enable it for everybody:
- https://src.fedoraproject.org/rpms/audit/blob/rawhide/f/audit.spec#_148
- https://src.fedoraproject.org/rpms/fedora-release/blob/rawhide/f/90-default.preset#_41

**Comment by travier** [comment]
PR to add audit in https://github.com/coreos/fedora-coreos-config/pull/2590. Pending next-devel opening/merge from branched.

**Comment by travier** [comment]
Note for when we enable next-devel: we 'll have to confirm that `initscripts-service` is not pulled-in.

**Comment by jlebon** [comment]
> Note for when we enable next-devel: we 'll have to confirm that `initscripts-service` is not pulled-in.

Opened https://github.com/coreos/fedora-coreos-config/pull/2591 which will guarantee this. :)

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `39.20230916.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `39.20231101.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `39.20231101.3.0`.
