### ISSUE TITLE
Implement tooling for release streams

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#137]
Implement tooling to manage the [release streams](https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#release-streams).  Operations include:

- [ ] Creating snapshots for `testing`, `rawhide`, `bodhi-updates`, `bodhi-updates-testing`
- [ ] Updating a package in `testing` or `stable`
- [ ] Promoting `testing` releases to `stable`
- [ ] Managing source switching and kernel selection for `next`
  - This is probably not needed immediately; `next` can initially alias `testing`

Related design issues: #77, #79.

**Comment by sinnykumari** [comment]
Fedora releng ticket requesting tags and dist-repo which we can use to build FCOS for various streams - https://pagure.io/releng/issue/8294

**Comment by dustymabe** [comment]
a related component of this: https://github.com/coreos/fedora-coreos-tracker/issues/179

**Comment by dustymabe** [comment]
a related component of this: https://github.com/coreos/fedora-coreos-tracker/issues/180

**Comment by dustymabe** [comment]
>* [ ]  Creating snapshots for `testing`, `rawhide`, `bodhi-updates`, `bodhi-updates-testing`

seems to be covered by #180 and #100

>* [ ]  Updating a package in `testing` or `stable`

@bgilbert - would this just be a PR to the lockfile in the corresponding branch in https://github.com/coreos/fedora-coreos-config ?

>* [ ]  Promoting `testing` releases to `stable`

Right, need tooling to implement the funky git merge as described in https://github.com/coreos/fedora-coreos-tracker/blob/master/stream-tooling.md. Don't think we have a ticket for that specifically yet.
 
>* [ ]  Managing source switching and kernel selection for `next`

@bgilbert - Would this be PRs to lockfiles again to choose an rc kernel from rawhide?

---


Tooling for manipulating lockfiles in particular looks like it's covered by https://github.com/coreos/fedora-coreos-tracker/issues/77.

**Comment by bgilbert** [comment]
> @bgilbert - would this just be a PR to the lockfile in the corresponding branch in https://github.com/coreos/fedora-coreos-config ?

Should be.  We might want some tooling to make this easier, so we're not copying NEVRAs around by hand, but I don't think we need to start with it.

> @bgilbert - Would this be PRs to lockfiles again to choose an rc kernel from rawhide?

Eventually I think we should have lockfiles automatically PRed to pick late-rc kernels from rawhide and early-release kernels from updates-testing.  It'd also be nice if toggling `next` between `testing` and Fedora n+1 were straightforward, but that'll be infrequent so probably doesn't matter as much.  Again, all of this can be manual initially.

**Comment by jbtrystram** [comment]
Most of our processes are now well supported through tools and documentation so I'll close this. 
If a specific tool is missing we can open a more descriptive issue.
