### ISSUE TITLE
New Package Request: criu-libs

### ISSUE THREAD

**Issue by rhatdan** [coreos/fedora-coreos-tracker#1370]
### What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

 criu-libs is needed for podman to be able to subspend and resume a container.

### What is the size of the package and its dependencies?

dnf info criu shows
Size         : 1.5 M

### What problem are you trying to solve with this package? Or what functionality does the package provide?

Podman support for CRIU.
We moved this from a requires to a recommends, so it is no longer installed in coreos.

### Can the software provided by the package be run from a container?  Explain why or why not.

No, since it is needed for containers.

### Can the tool(s) provided by the package be helpful in debugging container runtime issues?

N/A

### Can the tool(s) provided by the package be helpful in debugging networking issues?

N/A

### Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

Yes, but not really worth it.

### In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

Just binaries.

### Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS?

No

### Does the software provided by the package have a history of CVEs?

Not that I know of.

**Comment by dustymabe** [comment]
Since this was previously included in FCOS and recently lost I'm going to propose that we just skip the process and add this back in and also fast track it so that the removal gets into the next stable release.

**Comment by dustymabe** [comment]
xref: https://github.com/containers/podman/issues/16995#issuecomment-1373742717

**Comment by jlebon** [comment]
Makes sense to me. Looks like it was lost in the most recent stable release so this seems like a regression.

(On that note, we should probably have CI somewhere that fails if a package is removed; maybe together with the downgrade detection check?)

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20230107.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20230107.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20221225.3.0`.
