### ISSUE TITLE
Test `iso-offline-install` on multipath on ppc64le and aarch64 failing `coreos-ignition-unique-boot.service` check

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1373]
```
[2023-01-07T14:56:33.035Z] kola -p qemu-unpriv --output-dir /home/jenkins/agent/workspace/build-arch/tmp/kolaTestIso-r5FDc/kola-testiso-multipath testiso -S --qemu-multipath --scenarios iso-offline-install
...
[2023-01-07T14:59:17.380Z] FAIL: iso-offline-install ( + metal + multipath) (2m41.811s)
[2023-01-07T14:59:17.380Z]     entered emergency.target in initramfs
[2023-01-07T14:59:17.380Z] Error: entered emergency.target in initramfs
```

coreos-installer runs successfully and reboots the machine, and then:

```
Error: System has 2 devices with a filesystem labeled 'boot': ["/dev/sdb3", "/dev/mapper/mpatha3"]
coreos-ignition-unique-boot.service: Main process exited, code=exited, status=1/FAILURE
coreos-ignition-unique-boot.service: Failed with result 'exit-code'.
Failed to start coreos-ignition-unique-boot.service - CoreOS Ensure Unique Boot Filesystem.
```

I suspect something is going wrong with `rdcore verify-unique-fs-label`'s multipath detection.

[iso-offline-install.zip](https://github.com/coreos/fedora-coreos-tracker/files/10373957/iso-offline-install.zip)

**Comment by jlebon** [comment]
```
15:57:00  Upgraded:
15:57:00    containers-common 4:1-73.fc37 -> 4:1-76.fc37
15:57:00    containers-common-extra 4:1-73.fc37 -> 4:1-76.fc37
15:57:00    kernel 6.0.16-300.fc37 -> 6.0.17-300.fc37
15:57:00    kernel-core 6.0.16-300.fc37 -> 6.0.17-300.fc37
15:57:00    kernel-modules 6.0.16-300.fc37 -> 6.0.17-300.fc37
```

**Comment by dustymabe** [comment]
This seems to have happened again in:

- [build-arch#394](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/build-arch/detail/build-arch/986/pipeline/394)
- [build-arch#983](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/build-arch/detail/build-arch/983/pipeline)

**Comment by dustymabe** [comment]
Just [saw this](https://jenkins-coreos-ci.apps.ocp.fedoraproject.org/blue/organizations/jenkins/fedora-coreos-config/detail/PR-2179/3/pipeline) on `x86_64` in CI for https://github.com/coreos/fedora-coreos-config/pull/2179.

[ignition-virtio-dump.txt](https://github.com/coreos/fedora-coreos-tracker/files/10449544/ignition-virtio-dump.txt)

**Comment by jlebon** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=2162151.
Workaround in https://github.com/coreos/fedora-coreos-config/pull/2181.
