### ISSUE TITLE
GCP:  add aarch64 image

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1377]
GCP has support for 64 bit ARM (aarch64) instances. We should try to produce and test an aarch64 image for Google Cloud.

**Comment by dustymabe** [comment]
Things we'd need to do here:

- we'd need to enable testing for these images
- we have image families in GCP. We'd need to think about the implications of this there.

**Comment by dustymabe** [comment]
> * we have image families in GCP. We'd need to think about the implications of this there.

According to @zmarano we have to create a new image family for the new architecture images. Our current production image families are:

- `fedora-coreos-stable`
- `fedora-coreos-testing`
- `fedora-coreos-next`

He suggested we add:

- `fedora-coreos-stable-arm64`...

I have two questions here:

1. Should we reorganize our existing image families to mention `x86_64`?
2. Should we use the convention that GCP other image families already have of using `arm64` rather than `aarch64` in the image family name?

**Comment by zmarano** [comment]
1) we have been avoiding this because existing users would break if they are depending on the family name in their automation. Therefore, we believe it is better to leave the existing family names as they are and just use the `-arm64` variant for the arm architecture.

2) We would prefer it just because it makes everything the same. Unfortunately, the architecture string is different in different distros (there are at least 3 variations). And we picked one to use everywhere so as not to confuse the UX.

**Comment by Prashanth684** [comment]
> According to @zmarano we have to create a new image family for the new architecture images
Is it a problem if we have arm64 images as part of the same families? what prevents us from doing that?

**Comment by zmarano** [comment]
Yes that is a problem. Families are references to the latest, non-deprecated, active image in given family. There can't be two different images references against the same family.

**Comment by AnnaZivkovic** [comment]
@zmarano Just checking in to see if there's been any progress on adding the `-arm64` variant?

**Comment by dustymabe** [comment]
> @zmarano 

@AnnaZivkovic, he works for Google, not actively on Fedora CoreOS so he's the wrong person to ask

> Just checking in to see if there's been any progress on adding the `-arm64` variant?

No. No work has been done here.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/PPCRDSWPCC2W4VYCFZPAJM5HZ7B3T6RC/).

```
13:17:50  dustymabe | #agreed we will leave the existing image families in place (for
                    | x86_64) and create new `-arm64` image families for the aarch64
                    | images.
```

**Comment by AnnaZivkovic** [comment]
@dustymabe  Thanks for letting me know

**Comment by dustymabe** [comment]
OK I think the remaining work here is:

- [ ] create new image families for ARM in GCP
- [ ] update mantle to be able to upload ARM images (COSA)
- [ ] update fedora-coreos-pipeline pipecfg to create GCP ARM images
    - add to [artifact list](https://github.com/coreos/fedora-coreos-pipeline/blob/724bf407e7819da1697284c993c4336549aeb37a/config.yaml#L61)
    - make image family in [pipecfg](https://github.com/coreos/fedora-coreos-pipeline/blob/724bf407e7819da1697284c993c4336549aeb37a/config.yaml#L100) [arch dependent](https://github.com/coreos/fedora-coreos-tracker/issues/1377#issuecomment-1533676681):
        - family: 
            - x86_64: "fedora-coreos-${STREAM}"
            - aarch64: "fedora-coreos-${STREAM}-arm64
- [ ] update fedora-coreos-pipeline to kick off GCP ARM tests
- [ ] update [release checklist](https://github.com/coreos/repo-templates/blob/main/fcos/release-checklist.md#sanity-check-the-build) to check results of GCP ARM tests
- [ ] make sure the GCP ARM image shows up on the website

**Comment by dustymabe** [comment]
The following PRs should cover the bulk of the work here:

- https://github.com/coreos/coreos-assembler/pull/3520
- https://github.com/coreos/fedora-coreos-pipeline/pull/879

**Comment by dustymabe** [comment]
This one should cover the release checklist:

- https://github.com/coreos/repo-templates/pull/148

**Comment by dustymabe** [comment]
This is now complete. The only remaining item is to make sure it shows up on the website when the next round of releases goes out.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230625.2.0`. Please try out the new release and report issues.
