### ISSUE TITLE
Linux v6.0.16 breaks CIFS mounts

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1379]
There have been reports of v6.0.16 breaking CIFS mounts:
- https://bugzilla.redhat.com/show_bug.cgi?id=215849
- https://bugzilla.kernel.org/show_bug.cgi?id=216895

That kernel is currently in the latest `testing` and `next` releases. We stopped update rollouts after @fifofonix reported hitting issues: https://github.com/coreos/fedora-coreos-streams/pull/635.

The issues appear to be fixed in v6.0.18, which is already in the stable repos (https://bodhi.fedoraproject.org/updates/FEDORA-2023-39b55235fc) and in `testing-devel`. But it's not clear whether the specific issue @fifofonix hit will also be fixed (the error mode is slightly different).

Consider respinning releases for `testing` and `next`.

**Comment by dustymabe** [comment]
The kernel that reportedly has the fix (`kernel-6.0.18-300.fc37`) is in the latest `next` and `testing` builds.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20230110.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
This issue never affected our `stable` stream.
