### ISSUE TITLE
kola: rawhide: `no-default-initramfs-net-propagation` test failures; unexpected `lo.nmconnection`

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1385]
The `ext.config.networking.no-default-initramfs-net-propagation` test started failing in our cloud tests:

```
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.no-default-initramfs-net-propagation.default
systemctl status kola-runext-40.service:
�� kola-runext-40.service
     Loaded: loaded (/etc/systemd/system/kola-runext-40.service; static)
     Active: failed (Result: exit-code) since Tue 2023-01-17 14:49:18 UTC; 1s ago
   Duration: 44ms
    Process: 1954 ExecStart=/usr/local/bin/kola-runext-default (code=exited, status=1/FAILURE)
   Main PID: 1954 (code=exited, status=1/FAILURE)
        CPU: 20ms

Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 systemd[1]: Started kola-runext-40.service.
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + . /var/opt/kola/extdata-40/commonlib.sh
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ cmdline=($(< /proc/cmdline))
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + . /var/opt/kola/extdata-40/test-net-propagation.sh
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1956]: ++ grep 'info: skipping propagation of default networking configs'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1955]: ++ journalctl -t coreos-teardown-initramfs
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ echo 'no log message claiming to skip initramfs network propagation'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: no log message claiming to skip initramfs network propagation
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ fail=1
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1957]: +++ ls -A /etc/NetworkManager/system-connections/
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ '[' -n 'default_connection.nmconnection
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: lo.nmconnection' ']'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ echo 'configs exist in /etc/NetworkManager/system-connections/, but shouldn'\''t'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: configs exist in /etc/NetworkManager/system-connections/, but shouldn't
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ fail=1
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1958]: +++ ls -A -I readme-ifcfg-rh.txt /etc/sysconfig/network-scripts/
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ '[' -n '' ']'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + '[' -z 1 ']'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + fatal 'fail: no initramfs network propagation for default configuration'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + echo 'fail: no initramfs network propagation for default configuration'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: fail: no initramfs network propagation for default configuration
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + exit 1
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 systemd[1]: kola-runext-40.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 systemd[1]: kola-runext-40.service: Failed with result 'exit-code'.
--- FAIL: non-exclusive-test-bucket-0 (73.77s)
    --- FAIL: non-exclusive-test-bucket-0/ext.config.networking.no-default-initramfs-net-propagation.default (4.37s)
```

There is an unexpected `lo.nmconnection` file that is throwing off our "default NM configuration" check and causing initramfs networking to get propagated into the real root.

This started happening with `38.20230117.91.0` on our `rawhide` stream that includes `NetworkManager-1.41.8-1.fc38`.

**Comment by dustymabe** [comment]
This is most likely due to [e8618f0](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/e8618f0) where NetworkManager will now manage the local loopback device.

What's happening here is that `nm-initrd-generator` is producing the output we expect (i.e. `nm-initrd-generator` hasn't changed here), but when NetworkManager starts up in the initramfs it will auto create a `lo.nmconnection` connection and that file will be in `/run/NetworkManager/system-connections/` too.

I imagine this was intentional so we just need to adapt our code to handle it.

**Comment by dustymabe** [comment]
- https://github.com/coreos/fedora-coreos-config/pull/2179

**Comment by thom311** [comment]
> I imagine this was intentional so we just need to adapt our code to handle it.

In `nmcli device` you would see "connected (external)" state, which means that this device is configured not by NetworkManager. The profile was generated, it's in-memory and exists to represent that external configuration. Inside the keyfile under `/run`, you'd also see
```
[.nmmeta]
nm-generated=true
volatile=true
external=true
```
You would not want to anything with such "external" profiles.

Too bad that the change broke something. But I don't see how that can be avoided. While I am sorry for that, please adjust your side -- if possible(?).

Well, you could also drop a NetworkManager config file `/run/NetworkManager/conf.d/80-device-unmanaged-loopback.conf` with
```
[device-unmanage-loopback]
match-device=type:loopback
managed=0
```
that probably would restore the previous behavior. But this might not be the best solution. Ignoring "external" profile seems more correct.

**Comment by dustymabe** [comment]
Thanks @thom311 for the explanation. 

For my future self: what this means is that the NM profile is just representing how the `lo` device is configured. NM itself didn't do any actual configuration of the device. We can safely ignore it.

I have a PR for this over in https://github.com/coreos/fedora-coreos-config/pull/2179

**Comment by cgwalters** [comment]
Wait is NM now writing a file into `/etc` by default for the loopback device?  That seems kind of broken.

**Comment by thom311** [comment]
> Wait is NM now writing a file into `/etc` by default for the loopback device? That seems kind of broken.

It's in `/run/NetworkManager/system-connections`.
