### ISSUE TITLE
Question: What is the quickest way to add a couple of files and directories to the live iso installer image?

### ISSUE THREAD

**Issue by dhaanpaa-lab0** [coreos/fedora-coreos-tracker#1386]
How do i add files and/or directories to the live installer iso image? This is to provide a menu driven interface to run the coreos-installer command to install to the hard drive.

**Comment by bgilbert** [comment]
There isn't really a good way to add files to the ISO filesystem itself, e.g. to customize the bootloader.  But you can use an Ignition config to add files and directories to the live **OS**.  Once you have the config, embed it in the ISO using `coreos-installer iso ignition embed` or `coreos-installer iso customize --live-ignition`.

Note that once you've done so, the ISO will automatically disable autologin.  If you still want that, you'll have to inject a drop-in to re-enable it.
