### ISSUE TITLE
Fedora CoreOS download page re-design

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1387]
The Fedora Websites team is working on a re-design of our download page ([link](https://stg.fedoraproject.org/coreos/download/#download_section) to prototype).

Let's gather feedback for this proposal during our next community meeting.

**Comment by dustymabe** [comment]
Here's a screenshot of the current download page:

![Screenshot 2023-01-20 at 11-56-21 Get Fedora](https://user-images.githubusercontent.com/4530030/213757595-c4c281e4-0d04-4d18-acd1-bb53f8ffc243.png)


And here's a screenshot of the prototype:

![Screenshot 2023-01-20 at 11-56-12 Download Fedora CoreOS The Fedora Project](https://user-images.githubusercontent.com/4530030/213757639-e971bfb3-db03-4bc6-9e68-f932e32a79f3.png)

**Comment by bgilbert** [comment]
[Websites tracking issue](https://gitlab.com/fedora/websites-apps/fedora-websites/fedora-websites-3.0/-/issues/89).

**Comment by dustymabe** [comment]
We discussed this during the [community meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/SX5MZGOOMP43W5QRKJDEQJLFDNJAS5W2/) last week.

We worked collaboratively during the meeting to gather feedback and make suggestions in a [HackMD doc](https://hackmd.io/BqKhPwwRRXGUqAtUc07_ig).

Here's what we gathered:

```
## Things missing or lost from old page that need to be resurrected

- Ability to link to download sub-sections
- Stream and arch selections update the page URL
- Ability to link to architecture specific page?
- GCP image family and associated details
- Stream metadata querying at page load time (client or server side)

## Suggestions About Design

- Viewing in narrow web browswer window doesn't look great
    - the download info rectangles extend all the way to the edges
    - maybe dyanmically re-organize so there is a single column versus two columns
      - this does happen if the page is narrow enough, but the margins are still broken
- Better visual hints about which arch is selected
- Style the JSON link differently so it's easier to tell it's a link

## Options We'd Like to Explore
- can we try with the gray background behind the stable/testing/next at the top?
- can we try with the green/orange colors from the old site (the new ones are different)
    - this is in the stable/testing/next section
```

**Comment by bgilbert** [comment]
There's a [new draft](https://fedora.gitlab.io/websites-apps/fedora-websites/fedora-websites-3.0/coreos/download/) posted.  Re-adding `meeting` label.

**Comment by travier** [comment]
Looks ok. The `We take security seriously` section is missing a left side margin.

**Comment by dustymabe** [comment]
We discussed this in [today's community meeting](https://meetbot-raw.fedoraproject.org//fedora-meeting-1/2023-02-08/fedora_coreos_meeting.2023-02-08-16.32.txt):

First off, this is looking really great! The remaining pieces of feedback we have are:

- Could we get some visual indicator in the middle section where you select architecture about which architecture is currently chosen.
- The colors of the buttons match the color of the currently selected stream. We like the stream colors at the top, but having that color (especially for the green/orange) then propagate throughout the page is a bit much (bright colors everywhere). Would it be an option to keep the current behavior and the current color at the top, but change the saturation on the blue/green/orange color that propagates throughout the rest of the page (i.e. like making a more gray version of each of the blue/green/orange) so that it's not quite as distracting.

**Comment by dustymabe** [comment]
and just something else I noticed after the meeting.. There is a Fedora CoreOS logo in the top left corner that isn't really visible at all in the light mode version of the web page.

**Comment by travier** [comment]
This is now the new page https://fedoraproject.org/coreos/ and the old one will soon be redirected.
