### ISSUE TITLE
qemu-x86_64-static cannot run el9 binaries

### ISSUE THREAD

**Issue by cfergeau** [coreos/fedora-coreos-tracker#1389]
### Describe the bug

Running a rhel9 x86_64 binary from a fcos aarch64 image currently fails because of https://bugzilla.redhat.com/show_bug.cgi?id=2121700
This bug is fixed in [qemu-7.0.0-13.fc37](https://bodhi.fedoraproject.org/updates/FEDORA-2023-cf93567517), can you make sure this specific version is included in the next aarch64 fcos builds? The subpackage is https://kojipkgs.fedoraproject.org//packages/qemu/7.0.0/13.fc37/aarch64/qemu-user-static-x86-7.0.0-13.fc37.aarch64.rpm

(filing this request as suggested in https://github.com/containers/podman/issues/15456#issuecomment-1398658313 )

**Comment by dustymabe** [comment]
Renaming this to more accurately reflect the problem that is fixed by the new `qemu` build.

This should be in the next round of releases.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20230122.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20230122.3.0`.
