### ISSUE TITLE
kola: rawhide: `ext.config.files.setuid` fails due to additional unknown file with SetUID/GID bit set

### ISSUE THREAD

**Issue by gursewak1997** [coreos/fedora-coreos-tracker#1391]
### Describe the bug

There's an additional unknown file (`/usr/libexec/openssh/ssh-keysign`) with SetUID/GID bit set which leads to `ext.config.files.setuid` test failure. Not too sure if the addition of this file is intentional or not.

### Reproduction steps

1. Run `cosa kola run ext.config.files.setuid`

### Expected behavior

It passes with no additional unknown file(s) with SetUID/GID bit set

### Actual behavior

It fails with additional unknown file(s) with SetUID/GID bit set. That unknown file is `/usr/libexec/openssh/ssh-keysign`

### System details

[rawhide][x86_64] ⚡ 38.20230125.91.0

**Comment by dustymabe** [comment]
Can we determine the exact package NVR that introduced this change?

**Comment by gursewak1997** [comment]
The package NVR change that introduced this change: 
`openssh 9.0p1-9.fc38 -> 9.0p1-10.fc38.1
`

**Comment by travier** [comment]
I've taken a look at the discussion in
- https://bugzilla.redhat.com/show_bug.cgi?id=2141272
- https://bugzilla.redhat.com/show_bug.cgi?id=1498845
- https://src.fedoraproject.org/rpms/openssh/pull-request/37
- https://bugzilla.mindrot.org/show_bug.cgi?id=1893
and I disagree with upstream in the last link but let's just update the skip list for this binary by moving the entry from the setgid test to the setuig one.

**Comment by travier** [comment]
This is related to this change: https://fedoraproject.org/wiki/Changes/SSHKeySignSuidBit

**Comment by dustymabe** [comment]
> let's just update the skip list for this binary by moving the entry from the [setgid test](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/files/setgid#L11) to the setuid one.

Sounds simple enough. @gursewak1997 - do you want to try that out?

**Comment by gursewak1997** [comment]
> Sounds simple enough. @gursewak1997 - do you want to try that out?

https://github.com/coreos/fedora-coreos-config/pull/2202
