### ISSUE TITLE
transfer https://github.com/overdrop/liboverdrop-rs/ into this org

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1395]
### Describe the enhancement

See discussion in https://github.com/overdrop/liboverdrop-rs/pull/14

I'd like to use this in other projects (rpm-ostree and bootc) and as of right now the coreos/ GH org has a lot of other common systems crates, this would just be one more.

**Comment by bgilbert** [comment]
For an active project I'd be hesitant to move it out of a purpose-built GH org, but this one looks sparsely-maintained with a low commit count.  +1 from me.

**Comment by jmarrero** [comment]
+1 from me as well

**Comment by bgilbert** [comment]
Transfer complete: https://github.com/coreos/liboverdrop-rs
