### ISSUE TITLE
rawhide: kola: coreos-platform-chrony systemd generator failure 

### ISSUE THREAD

**Issue by aaradhak** [coreos/fedora-coreos-tracker#1402]
### Describe the bug

There is a systemd generator failure occurring with all kola-aws, kola-azure, and kola-gcp tests in the rawhide stream. This issue is found to occur after the systemd package upgrade from systemd-252.4-4.fc38 to systemd-253~rc1-1.fc38.

```
17:47:14  --- FAIL: basic (401.44s)
17:47:14      --- PASS: basic/DbusPerms (0.44s)
17:47:14      --- PASS: basic/ServicesActive (0.27s)
17:47:14      --- PASS: basic/ReadOnly (0.23s)
17:47:14      --- PASS: basic/Useradd (0.42s)
17:47:14      --- PASS: basic/MachineID (0.28s)
17:47:14      --- PASS: basic/FCOSGrowpart (0.27s)
17:47:14      --- PASS: basic/PortSSH (0.25s)
17:47:14          harness.go:1564: Found systemd generator failure (/usr/lib/systemd/system-generators/coreos-platform-chrony) on machine i-0f314f6b764be465c console
```

The failure found in the test run:
journal.txt:
```
Jan 31 20:26:34.088456 systemd[1]: bpf-lsm: Failed to link program; assuming BPF LSM is not available
Jan 31 20:26:34.088468 zram_generator::config[1156]: No configuration found.
Jan 31 20:26:34.088481 /usr/lib/systemd/system-generators/coreos-platform-chrony: line 44: /etc/sysconfig/network: Read-only file system
Jan 31 20:26:34.088493 systemd[1135]: /usr/lib/systemd/system-generators/coreos-platform-chrony failed with exit status 1.
```

### Reproduction steps

1. Use latest [FCOS rawhide image](https://builds.coreos.fedoraproject.org/browser?stream=rawhide&arch=aarch64). (for aws image, rawhide version 38.20230127.91.0 in case of aarch64,  use ami-00b7b430397bbfac4)

2. Run any Kola test
   - kola basic (cosa kola run basic -p=aws --aws-credentials-file=aws-creds --arch=aarch64 --aws-region=us-east-1 --aws-ami=ami-00b7b430397bbfac4)

3.  Test fails -->  systemd generator failure ( `harness.go:1564: Found systemd generator failure (/usr/lib/systemd/system-generators/coreos-platform-chrony) on machine i-0048c3d9c59d10c45 console`)

### Expected behavior

All kola tests to PASS 

### Actual behavior

Kola tests fail because of systemd generator failure ( `harness.go:1564: Found systemd generator failure (/usr/lib/systemd/system-generators/coreos-platform-chrony) on machine i-0048c3d9c59d10c45 console`)

### System details

Fedora CoreOS Rawhide Version 38.20230127.91.0
AWS - ami-00b7b430397bbfac4

**Comment by dustymabe** [comment]
Package pin in https://github.com/coreos/fedora-coreos-config/pull/2208

**Comment by cgwalters** [comment]
systemd now isolates systemd generators; us mutating the system from a generator was always pretty broken.  We need to change our generator to enable a unit which does the mutation.

**Comment by aaradhak** [comment]
There has been a change in upstream systemd related to systemd generators which could be the reason for this issue. 
https://github.com/systemd/systemd/blob/main/NEWS#L102-L109

**Comment by dustymabe** [comment]
We probably need to figure out a different way to achieve the same goal that `PEERNTP=no` in `/etc/sysconfig/network` has.

https://github.com/coreos/fedora-coreos-config/blob/4e23c1563a790a7405a03edd05945eb2b03cd8a8/overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony#L37-L50

Is there a runtime way to do that?

**Comment by jlebon** [comment]
> systemd now isolates systemd generators; us mutating the system from a generator was always pretty broken. We need to change our generator to enable a unit which does the mutation.

Another hacky thing this generator does is redefining `ExecStart=`. Maybe we can see if upstream is interested in adding another `EnvironmentFile=-/run/chronyd/env` and a `$TRANSIENT_OPTIONS` variable that we can use (I guess short-term we could do that in postprocess). With that, I think everything else in there can run in the systemd unit and so we could get rid of the generator entirely (for making it platform-specific, we can use `ignition.platform.id` triggering conditions like we already have on some other units).

**Comment by dustymabe** [comment]
The systemd change here was [partially reverted in Fedora](https://src.fedoraproject.org/rpms/systemd/c/4bdd16eba5c409a5aa0afcc16f6e284f20793e06?branch=rawhide) for a short time.

We still need to fix this problem because they'll re-enable the stricter permissions soon, but for now we can unpin systemd in rawhide.

**Comment by dustymabe** [comment]
This should be fixed with https://github.com/coreos/fedora-coreos-config/pull/2271
