### ISSUE TITLE
Platform Request: Microsoft Hyper-V

### ISSUE THREAD

**Issue by baude** [coreos/fedora-coreos-tracker#1411]
### Why is the platform important?  Who uses it?

Microsoft HyperV is a widely known and adopted virtualization platform for Windows.  The Podman team would also like to being supporting HyperV with their `podman machine` function which uses FCOS as its base OS.  I understand separately FCOS would like to support HyperV as well presumably due to user demand.

### What is the official name of the platform?  Is there a short name that's commonly used in client API implementations?

Microsoft HyperV

### How can the OS retrieve instance userdata?  What happens if no userdata is provided?

HyperV implements a key-value-pair (KVP) through its hypervisor using Windows Management Implementation (WMI).

On the host side, the injection occurs by setting values in a given registry.  The KVP does have limitations; the key is limited to 512 bytes and the value 2048 bytes.  Because this is Windows UTF halves those values to 256 and 1024.

On the Linux guest, the KVPs are shared by WMI and are written to the Linux kernel.  Using code from the already existing hypervkvpd (daemon), we can extract the information we need.  Because of the 1K value limit, the values will need to be split up on the host and re-assembled on the guest.

### Does the platform provide a way to configure SSH keys for the instance?  How can the OS retrieve them?  What happens if none are provided?

I do not know. I want to use ignition for this.

### How can the OS retrieve network configuration?  Is DHCP sufficient, or is there some other network-accessible metadata service?

DHCP is sufficient

### In particular, how can the OS retrieve the system hostname?

The host hostname is also provided as a KVP automatically.  Otherwise the expectation is that DHCP delivers this.

### Does the platform require the OS to have a specific console configuration?

I do not believe so, but we should clarify what exactly this question is asking ...

### Is there a mechanism for the OS to report to the platform that it has successfully booted?  Is the mechanism required?

It could be done if really needed through KVPs as well but it would require code on the host looking for it.  The mechanism is not required.

### Does the platform have an agent that runs inside the instance?  Is it required?  What does it do?  What language is it implemented in, and where is the source code repository?

There are such things.  Early analysis suggests we do not need it and therefore is optional.

### How are VM images uploaded to the platform and published to other users?  Is there an API?  What disk image format is expected?

the disk format is vhd/vhdx.  the long term expectation is that these images would be produced upstream

### Are there any other platform quirks we should know about?

ah! it's windows!

**Comment by miabbott** [comment]
Previous investigation done by the CoreOS team in 2020 - https://issues.redhat.com/browse/COS-842

**Comment by bgilbert** [comment]
Thanks for filing this.  https://github.com/coreos/ignition/issues/1538 tracks the Ignition portion.

- For the platform name, `hyperv` is the obvious choice, and there's [precedent](https://github.com/coreos/fedora-coreos-tracker/issues/251#issuecomment-520243201) for it.

- I wouldn't expect the platform to provide special mechanisms for SSH keys (usually that happens on clouds), so we can likely ignore that part.

- The console configuration question means: does the Hyper-V UI expect the VM to produce console output on a graphical console?  Serial port?  Both?

- We should decide whether to produce VHD or VHDX.

> On the Linux guest, the KVPs are shared by WMI and are written to the Linux kernel. Using code from the already existing hypervkvpd (daemon), we can extract the information we need.

Re-emphasizing, for safety, that this needs to be new code for license compatibility reasons.

> The host hostname is also provided as a KVP automatically. Otherwise the expectation is that DHCP delivers this.

Does DHCP actually always deliver this?  If not (e.g. if Hyper-V doesn't control the DHCP server) we might need to teach Afterburn to read the hostname key.

**Comment by bgilbert** [comment]
Our Hyper-V docs should include a PowerShell script that takes a VM identifier and an Ignition config, chunks the config into appropriately-sized pieces, and creates the KVP keys.

**Comment by bgilbert** [comment]
Implementation checklist in #1421.

**Comment by bgilbert** [comment]
@baude pointed out that Windows can't decompress `.xz` (or indeed `.gz`) files by default.  We should probably consider compressing into a `.zip` file instead.

**Comment by dustymabe** [comment]
We discussed this during the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/BQBM6LUMEPHFJHNVEJYT444QNFWNVO7T/).

```
12:22:09   dustymabe | #agreed We think it's a good idea to enable Windows users who want
                     | to use FCOS and the Windows podman machine efforts by adding a
                     | Hyper-V FCOS platform under the `hyperv` platform ID.

```

**Comment by bgilbert** [comment]
I've looked through the Hyper-V Manager and Virtual Machine Connection UIs in Windows Server 2024, and serial port setup is not surfaced anywhere.  I think it's safe to stick with graphical console only for now.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230806.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230806.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230722.3.0`.

**Comment by dustymabe** [comment]
Please see our [docs](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-hyperv/) for more information on how to use this new image!

**Comment by Reflux0301** [comment]
Is it possible we can add the Hyper-V specific tools to the builds?

For example, `hyperv-daemons`, `hyperv-daemons-license`, `hyperv-tools`, `hypervkvpd` (provides the host with information about the VM) and `hypervvssd` (useful for backup replication).

**Comment by dustymabe** [comment]
Ususally we don't ship agents. see https://github.com/coreos/fedora-coreos-tracker/issues/12

If you'd like to carry this conversation further please open a new issue.
