### ISSUE TITLE
SELinux is preventing hardware initiated reboot on Azure

### ISSUE THREAD

**Issue by marmijo** [coreos/fedora-coreos-tracker#1412]
Recent `rawhide` kola-azure jobs have been timing out after 75 minutes causing them to fail. `testing-devel` kola-azure jobs finish in roughly 30-40 minutes.

Scanning the logs of some recent `rawhide` jobs shows that some kola tests are taking roughly twice as long to complete (this is not a complete list):

job 320:
```
09:32:13  --- PASS: ext.config.ignition.remote (414.17s)
09:34:48  --- PASS: coreos.ignition.once (565.13s)
09:45:57  --- PASS: ext.config.ignition.kargs (410.98s)
09:48:50  --- PASS: ext.config.gshadow (450.82s)
```
[kola_azure_320_rawhide.txt](https://github.com/coreos/fedora-coreos-tracker/files/10669390/kola_azure_321_rawhide.txt)

job 345:
```
13:26:56  --- PASS: ext.config.ignition.kargs (879.36s)
13:29:13  --- PASS: coreos.ignition.once (913.86s)
13:29:35  --- PASS: ext.config.gshadow (999.93s)
13:31:51  --- PASS: ext.config.ignition.remote (1129.70s)
```
[kola_azure_345_rawhide.txt](https://github.com/coreos/fedora-coreos-tracker/files/10669387/kola_azure_345_rawhide.txt)

**Comment by dustymabe** [comment]
Next step would probably be to look at the journal logs from the same test on both (i.e. ` ext.config.gshadow` on `testing-devel` and `rawhide`) and compare the timing of various parts of the startup to see where things are getting significantly different.

**Comment by marmijo** [comment]
FYI, we're not going to pin the selinux packages for now: https://github.com/coreos/fedora-coreos-config/pull/2240#issuecomment-1432440937

**Comment by marmijo** [comment]
SELinux is preventing the Microsoft Azure Hypervisor from performing a reboot. When trying to reboot from the Azure UI, and the AVC denial is seen in the VM. 

I opened a BZ for this issue: https://bugzilla.redhat.com/show_bug.cgi?id=2173759

**Comment by marmijo** [comment]
I changed the title from the symptom to the cause of the issue.

**Comment by marmijo** [comment]
The upstream package maintainers fixed the issue with https://github.com/fedora-selinux/selinux-policy/pull/1616 which has been incorperated into the f38 RPM: [selinux-policy-38.10-1.fc38](https://koji.fedoraproject.org/koji/search?terms=selinux-policy-38.10-1.fc38&type=build&match=exact) as well as the f39 RPM [selinux-policy-38.10-1.fc39](https://koji.fedoraproject.org/koji/search?terms=selinux-policy-38.10-1.fc39&type=build&match=exact).

I have also requested that it be backported to f37 as well.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230417.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230430.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230430.3.1`.
