### ISSUE TITLE
Requesting ` systemd-journal-remote` package in Fedora CoreOS

### ISSUE THREAD

**Issue by pampelmuse76** [coreos/fedora-coreos-tracker#1414]
I would like to collect all logs from my coreos instances on a central server for analyses/monitoring.
But I cannot find a good way to send (journal) logs to a remote server.
What about to add the systemd service "systemd-journal-upload" to coreos?
Thanks

**Comment by dustymabe** [comment]
Once you have filled out the template add the `meeting` label to the ticket and we'll discuss it at our weekly community meeting.

**Comment by travier** [comment]
Closing as a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/1415
