### ISSUE TITLE
kola: rawhide: ext.config.toolbox: no F39 toolbox container exists

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1416]
See https://github.com/containers/toolbox/issues/1233. Should be resolved soon.

**Comment by debarshiray** [comment]
`registry.fedoraproject.org/fedora-toolbox:39` [exists](https://koji.fedoraproject.org/koji/buildinfo?buildID=2150984) since Tuesday, and I also [rebuilt](https://koji.fedoraproject.org/koji/buildinfo?buildID=2150972) the the F38 image to pick up the post-branching changes.

**Comment by travier** [comment]
Thanks
