### ISSUE TITLE
[rawhide]: Error binding to address GUnixSocketAddress

### ISSUE THREAD

**Issue by gursewak1997** [coreos/fedora-coreos-tracker#1418]
### Describe the bug

Multiple kola tests are failing with `error: Error binding to address (GUnixSocketAddress): No such file or directory`.
This is a `glib2-2.75.3-1.fc39` issue as reverting to the previous `glib2-2.74.1-3.fc38.x86_64` fixes this.
Rawhide [build](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/build/detail/build/887/pipeline/247/) with failures.
```
[2023-02-14T13:03:08.994Z]     + sudo rpm-ostree install --cache-only /var/home/core/aht-dummy.rpm
[2023-02-14T13:03:08.994Z]     error: Error binding to address (GUnixSocketAddress): No such file or directory
```

### System details

[rawhide][x86_64] ⚡ 38.20230214.91.0

**Comment by dustymabe** [comment]
other places where this is being tracked:

- https://github.com/coreos/rpm-ostree/issues/4306
- https://bugzilla.redhat.com/show_bug.cgi?id=2169622

**Comment by cgwalters** [comment]
FTR if "our" tests were run as part of dist-git gating for critical packages, we would have caught this in the PR (assuming there was a PR at all, it's not mandatory today because well everything in the process is broken).

**Comment by dustymabe** [comment]
> FTR if "our" tests were run as part of dist-git gating for critical packages, we would have caught this in the PR (assuming there was a PR at all, it's not mandatory today because well everything in the process is broken).

FTR I don't find these comments helpful. I think we know we can do better and there's a path to get there, but we haven't had the capacity to do so. I've been seeing you make these comments for years. At this point it feels more like complaining than anything else. Are you asking for any specific action from anyone? If so then make it clear. If not then don't make the comment and work towards putting in place initiatives that make the goal happen.

**Comment by dustymabe** [comment]
The issue with the glib2 package was fixed and it was unpinned in https://github.com/coreos/fedora-coreos-config/pull/2243
