### ISSUE TITLE
Platform ID for bare-metal images (raw GPT disk)

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-tracker#142]
https://github.com/coreos/fedora-coreos-tracker/issues/91 is tracking progress on a bare-metal installer, based on `dd`-ing a raw GPT image to disk.

As prerequisite for that, coreos-assembler pipeline has to start producing such a raw GPT disk image. Currently, CL has `coreos_production_image.bin.bz2` which is mostly equivalent to this and consumed by coreos-install.

Before doing that, we should allocate a platform ID so that we are not losing static information when moving from buildtime to runtime. Software on those nodes can introspect that ID to detect the environment they are in and apply conditional logic (e.g. Ignition config fetcher).

I think there may be a few factors that may affect the granularity of this bare-metal ID, such as:
 * Boot method (BIOS, UEFI or a dual-image for both)
 * Measured boot (on UEFI with TPM, whether the node is performing boot measurement/attestation)
 * Multiple kinds of images (will we need to produce and distinguish different geometries in the future?)

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/coreos-assembler/pull/339

**Comment by dustymabe** [comment]
issue against ignition to add this: https://github.com/coreos/ignition/issues/724

**Comment by dustymabe** [comment]
a 'metal' platform id was added to ignition in https://github.com/coreos/ignition/pull/732 - It will filter down into FCOS in the next ignition release. Closing this out for now.
