### ISSUE TITLE
No network when PXE provisioning on bare metal since 37.20230122.3.0

### ISSUE THREAD

**Issue by wkruse** [coreos/fedora-coreos-tracker#1423]
### Describe the bug

We are using https://typhoon.psdn.io/ to provision Fredora CoreOS on bare metal. Since Fedora CoreOS **37.20230122.3.0** no network is available

- Using DNS of the matchbox server

```
coreos-livepxe-rootfs: curl: (6) Could not resolve host: xxx
coreos-livepxe-rootfs: Couldn't establish connectivity with the server specified by:
coreos-livepxe-rootfs: coreos.live.rootfs_url=http://xxx
```

- Using IP of the matchbox server

```
coreos-livepxe-rootfs: curl: (7) Couldn't connect to server
coreos-livepxe-rootfs: Couldn't establish connectivity with the server specified by:
coreos-livepxe-rootfs: coreos.live.rootfs_url=http://xxx
```

[coreos-enable-network.service](https://github.com/coreos/fedora-coreos-config/blob/stable/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-network/coreos-enable-network.service)

It looks like it is related to #1383.

Is it intended behavior?

Setting `rd.neednet=1` explicitly  fixes it for us.

CC: @dghubble

### Reproduction steps

1. Provision Fedora CoreOS 37.20230122.3.0 on bare metal

### Expected behavior

Network is available.

### Actual behavior

Network is not available.

### System details

- Bare Metal
- Fedora CoreOS 37.20230122.3.0

**Comment by dustymabe** [comment]
In https://github.com/coreos/fedora-coreos-config/pull/2176 we made two fixes:

1. [overlay.d: only run coreos-enable-network on first boot](https://github.com/coreos/fedora-coreos-config/commit/937d3295bd4ecd4ccb426c5e07ee0ab3f35a5ce5). It wasn't necessary.
2. [apply the udev rule to the initramfs](https://github.com/coreos/fedora-coreos-config/commit/8d631783693b0722fbcd40276518998ea5d10f81). So even if networking does get brought up it still won't bring up that device.


I suspect that we missed a use case that makes doing `1.` unsafe.

**Comment by bgilbert** [comment]
@wkruse Please post a full console log of the failed boot.

**Comment by ep1cman** [comment]
I have the same issue trying to PXE boot a raspberry pi 4, and the `rd.neednet=1` fix from above does indeed work for me too.


Please see a boot log attached
[boot.log](https://github.com/coreos/fedora-coreos-tracker/files/10788130/boot.log)

**Comment by dustymabe** [comment]
In this case (the first log from @ep1cman) here's our kernel command line:

```
[    0.000000] Kernel command line: fedora-coreos-37.20230122.3 initrd=main coreos.live.rootfs_url=http://private.goscik.com/boot//fedora-coreos-37.20230122.3.0-live-rootfs.aarch64.img coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://private.goscik.com/boot//config.ign
```

so `coreos.live.rootfs_url` exists (a triggering condition for `coreos-enable-network.service`), but `ignition.firstboot` doesn't, which means Ignition doesn't run on that boot and after https://github.com/coreos/fedora-coreos-config/commit/937d3295bd4ecd4ccb426c5e07ee0ab3f35a5ce5 we no longer pull that service in on non-Ignition boots. We'll likely need to rework that commit to handle this use case.

**Comment by ep1cman** [comment]
I got this command line from this section of the documentation: https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_installing_from_ipxe

**Comment by dustymabe** [comment]
one option may be to add a requirement on `coreos-enable-network.service` [here](https://github.com/coreos/fedora-coreos-config/blob/66da416fe3f75eaa6c96b4f3c4eee3f45ff13242/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-live/live-generator#L30-L32). @jlebon, @bgilbert - thoughts on the best way to proceed with this regression?

**Comment by jlebon** [comment]
I think this is related to https://github.com/coreos/fedora-coreos-tracker/issues/1426. There, we agreed to always force-enable Ignition on live boots. So in theory, enablement of `coreos-enable-network.service` via `ignition-complete.target` as done in https://github.com/coreos/fedora-coreos-config/commit/937d3295bd4ecd4ccb426c5e07ee0ab3f35a5ce5 should be sufficient once we implement that. Depending on when this gets implemented though, short-term we could indeed manually add an enablement via the live generator.

**Comment by dustymabe** [comment]
> I think this is related to #1426. There, we agreed to always force-enable Ignition on live boots.

I think the risk/reward of the complexity of implementing that is still up for debate, so...



> Depending on when this gets implemented though, short-term we could indeed manually add an enablement via the live generator.

I've opened https://github.com/coreos/fedora-coreos-config/pull/2262

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20230303.2.0`. Please try out the new release and report issues.

**Comment by wkruse** [comment]
The fix in `testing` stream works for us. Thank you! 👍
