### ISSUE TITLE
Implement Hyper-V support

### ISSUE THREAD

**Issue by baude** [coreos/fedora-coreos-tracker#1424]
# Implementing a new supported platform

 ## During Development
 Create PR's addressing the following:
 
 - [x] [stream-metadata-go](https://github.com/coreos/stream-metadata-go) - https://github.com/coreos/stream-metadata-go/pull/55
     - [Example PR](https://github.com/coreos/stream-metadata-go/pull/45/)
     - [x] Add platform to the `Media` struct in `release/release.go`
     - [x] Add supporting code for new platform to `toStreamArch` func in `release/translate.go`

 - [x] [fedora-coreos-tracker](https://github.com/coreos/fedora-coreos-tracker/) - https://github.com/coreos/fedora-coreos-tracker/pull/1425
     - [Example PR](https://github.com/coreos/fedora-coreos-tracker/pull/1213/)
     - [x] Update the metadata for the new platform

 - [x] [coreos-assembler](https://github.com/coreos/coreos-assembler)
     - [Example PR](https://github.com/coreos/coreos-assembler/pull/2489)
     - [x] Implement required functionality to support new platform

 - [x] [fedora-web](https://pagure.io/fedora-web/websites)
     - [Example PR](https://pagure.io/fedora-web/websites/pull-request/221#request_diff)
     - [x] Add platform to `sites/static/js/coreos-download.js`

- [x] [fedora-coreos-browser](https://github.com/coreos/fedora-coreos-browser) - https://github.com/coreos/fedora-coreos-browser/pull/45
     - [Example PR](https://github.com/coreos/fedora-coreos-browser/pull/35)
     - [x] Add a list element for new platform in `browser/index.html`

- [x] [build pipeline](https://github.com/coreos/fedora-coreos-pipeline) - https://github.com/coreos/fedora-coreos-pipeline/pull/815
     - [Example PR](https://github.com/coreos/fedora-coreos-pipeline/pull/500)
     - [x] Add platform to the list found in `jobs/build.Jenkinsfile` for building the new artifact
 
 - [x] [fedora-coreos-docs](https://github.com/coreos/fedora-coreos-docs) - https://github.com/coreos/fedora-coreos-docs/pull/545
     - [Example PR](https://github.com/coreos/fedora-coreos-docs/pull/377)
     - [x] Add a `provisioning-<platform>.adoc` that walks through how to setup the new platform
     - [x] Add an entry in the `modules/ROOT/nav.adoc` that points to new documentation

 ## At Release

1.  Merge metadata changes:
    
    - [x] stream-metadata-go
    - [x] fedora-coreos-tracker
    - [x] fedora website
    - [x] fedora-coreos-browser  

2. Create and push signed tags with appropriate versions
    
    ```
    # Ensure gpg key for signing in github settings that is associated to redhat email.
    # Verify you are on the upstream repo's main branch.

    git status

    RELEASE_VER=vx.y.z
    # Replace 'x.y.z' with the appropriate numbers.

    git tag -s ${RELEASE_VER}
    # Give appropriate detail to tag, check previous tags with 'git show ${RELEASE_VER}'
    
    git push git@github.com:coreos/targeted-repo.git ${RELEASE_VER}
    # Navigate to the targeted-repo's tag section to ensure a valid signed tag is listed.
    # e.g. https://github.com/...repo/tags 
    ```

    1. [x] Tag stream-metadata-go following the above steps. After tagging, ensure that dependabot has picked up latest version, and merged it into fedora-coreos-stream-generator && coreos-assembler.
        - These can be triggered manually by navigating to [fedora-coreos-stream-generator's Dependabot](https://github.com/coreos/fedora-coreos-stream-generator/network/updates/) and [coreos-assembler's Dependabot](https://github.com/coreos/coreos-assembler/network/updates) respectively; then, clicking "Check for updates". 
            - This might need to be done a few times, as the Dependabot might not pickup tag changes for a few attempts after initial tagging.

    2. [x] Tag fedora-coreos-stream-generator following the above steps.

3. Merge the following changes:
    - [x] coreos-assembler

4. Wait for updates made to coreos-assembler to be propagated to latest container
    - [x] Download latest version of coreos-assembler container. Verify platform support functionality. 
 
5. Merge changes for:
    - [x] Build pipeline 

6. Wait for new images to reach stable then merge documentation.
    - [x] fedora-coreos-docs merged

**Comment by bgilbert** [comment]
Updates for the checklist template:
- [ ] Add steps for adding Ignition and Afterburn support
- [ ] Replace link to pipeline example PR

**Comment by baude** [comment]
the fedora-web PR can be found -> https://pagure.io/fedora-web/websites/pull-request/282

**Comment by bgilbert** [comment]
We never decided in #1411 whether serial console is needed.  I've added a checklist step to enable that, and we can skip the checkbox if we decide to just stick with graphical console.

**Comment by baude** [comment]
Note: serial console is not needed

**Comment by bgilbert** [comment]
Hyper-V images will be available in the next set of FCOS releases.  I've gone ahead and merged the docs PR in advance.

**Comment by travier** [comment]
Thanks a lot work all the work here @baude @bgilbert @dustymabe

**Comment by bgilbert** [comment]
Looks like we missed adding `hyperv` to `cmd-generate-release-meta`.  Fix in https://github.com/coreos/coreos-assembler/pull/3546.  The example coreos-assembler PR does do that, so no checklist update is necessary.
