### ISSUE TITLE
Use ptp_kvm as an NTP time source on qemu when available

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1433]
### Describe the enhancement

There's a `ptp_kvm` kernel module that allows the guest to be in sync with the host. There's a proposal in https://github.com/coreos/fedora-coreos-config/pull/2263 to make use of it and a subproposal to make "partial use" of it (see https://github.com/coreos/fedora-coreos-config/pull/2263#issuecomment-1452219915).

Since the PR already has all the context, please keep discussions there.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/6NYIIUQR5IIOJ7GYWIPFQA4O3UE7WYRY/).

```
12:24:31   jlebon | #agreed we will make chrony take ptp_kvm as an additional source if
                  | it's found to be accurate enough. we will add a test verifying that
                  | this setup works.
```

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/UWRTWP7XJ32CEDQBPKNX5P4ZHE5KSIF4/).

```
12:55:27  jlebon | #agreed we will keep PEERNTP=yes on QEMU so
                 | that DHCP-provided NTP servers are still
                 | considered even if ptp_kvm is available
```

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230402.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20230401.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20230401.3.0`.
