### ISSUE TITLE
F38: tracker for package additions/removals

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1435]
This issue will help track package additions and removals when compared to the previous major version of Fedora. Usually the additions/removals are a result of changing dependencies in named packages in our manifests. Most of the time the changes are intentional, but sometimes they can be unintended and we'd like to document changes and reasoning here.

Ideally, we should do these checks directly in rawhide rather than at promotion time.

- Added:
    - [`amd-gpu-firmware`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458845801)
        - This also made it into F37 (`testing`/`stable`)
    - [`duktape`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458845933)
    - [`intel-gpu-firmware`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458845801)
        - This also made it into F37 (`testing`/`stable`)
    - [`kernel-modules-core`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458846006)
        - This also made it into F37 (`testing`/`stable`)
    - [`libmd`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458846103)
        - This also made it into F37 (`testing`/`stable`)
    - [`libunistring1.0`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458846234)
    - [`nvidia-gpu-firmware`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458845801)
        - This also made it into F37 (`testing`/`stable`)
    - [`rpm-sequoia`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458846296)
- Removed:
    - [`cracklib-dicts`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458847210)
        - This removal also made it into F37 (`testing`/`stable`). 
    - [`libsmbios`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458847298)
    - [`mozjs102`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458845933)
    - [`pcre`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1458847358)
    - [`systemd-boot-unsigned`](https://github.com/coreos/fedora-coreos-tracker/issues/1435#issuecomment-1508975019)

**Comment by jlebon** [comment]
Added:
- `amd-gpu-firmware`
- `intel-gpu-firmware`
- `nvidia-gpu-firmware`

Split out of `linux-firmware` (see https://github.com/coreos/fedora-coreos-tracker/issues/1350).

**Comment by jlebon** [comment]
Added:
- `duktape`

Removed:
- `mozjs102`

Polkit changed Javascript library from Mozjs to Duktape which is a lot smaller! (13M vs 640K).

**Comment by jlebon** [comment]
Added:
- `kernel-modules-core`

New kernel subpackage.

**Comment by jlebon** [comment]
Added:
- `libmd`

New transitive dep of `criu`. Hashing functions.

**Comment by jlebon** [comment]
Added:
- `libunistring1.0`

The `libunistring` package (which we also ship) had an unexpected soname bump and it looks like rather than forcing all the dependent packages to rebuild, a compat package was created: https://pagure.io/releng/issue/11175. So that package should drop out once all the deps are eventually rebuilt and enter the repos.

**Comment by jlebon** [comment]
Added:
- `rpm-sequoia`

New dep of rpm: https://fedoraproject.org/wiki/Changes/RpmSequoia

**Comment by jlebon** [comment]
Added:
- `samba-libs`

New dep of `samba-client-libs`. 375K.

**Comment by jlebon** [comment]
Removed:
- `cracklib-dicts`

This is now a weak dep which we no longer pull in: https://bugzilla.redhat.com/show_bug.cgi?id=2006063

**Comment by jlebon** [comment]
Removed:
- `libsmbios`

Dropped dep of `fwupd`.

**Comment by jlebon** [comment]
Removed:
- `pcre`

This package was deprecated: https://fedoraproject.org/wiki/PcreDeprecation

**Comment by jlebon** [comment]
Removed:
- `systemd-boot-unsigned`

Dropped dep of `systemd-udev`.

**Comment by dustymabe** [comment]
Only on `aarch64`

Added:
- `libatomic`

Pulled in now by `fwupd` dep chain:

```
[core@dustymabe ~]$ rpm -q libatomic
libatomic-13.0.1-0.12.fc38.aarch64
[core@dustymabe ~]$ rpm -e libatomic
error: Failed dependencies:
        libatomic.so.1()(64bit) is needed by (installed) libusb1-1.0.26-2.fc38.aarch64
[core@dustymabe ~]$ rpm -e libusb1
error: Failed dependencies:
        libusb-1.0.so.0()(64bit) is needed by (installed) libgusb-0.4.5-1.fc38.aarch64
[core@dustymabe ~]$ rpm -e libgusb
error: Failed dependencies:
        libgusb(aarch-64) >= 0.3.5 is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2()(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.1.0)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.1.1)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.1.7)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.2.11)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.2.2)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.2.5)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.2.8)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.3.1)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.3.3)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.3.5)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.3.6)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.3.8)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.4.0)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.4.1)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.4.3)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
        libgusb.so.2(LIBGUSB_0.4.4)(64bit) is needed by (installed) fwupd-1.8.14-1.fc38.aarch64
```

Looks like `libusb1` now [links with libatomic](https://github.com/libusb/libusb/commit/561dbdacfbcd8f26c81900d1a1a16d2f44093e0e) in `1.0.26` and newer. Not sure 100% on why this doesn't get pulled in on other architectures.
