### ISSUE TITLE
Fedora CoreOS talks for DevConf.cz & DevConf.us 2023

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1437]
DevConf.cz 2023 will happen on June 16 - 18, 2023, in Brno, Czech Republic.

The CfP is open until March 17th: https://cfp.devconf.info/

See: https://www.devconf.info/cz/

---

DevConf.us 2023 will happen on August 16, 2023 (Workshops) and August 17-19, 2023 (General Sessions) in Boston, USA.

The CfP is open until April 10, 2023: https://cfp.devconf.info/

See: https://www.devconf.info/us/

**Comment by dustymabe** [comment]
@travier and I submitted together:

- Hands On With Fedora CoreOS (workshop/lab)
- Customize your server/desktop OS like a container
    - highlights OSTree Native Container uses for FCOS/Silverblue

**Comment by dustymabe** [comment]
Updating the description. It appears the CFP deadline got extended to the 17th.

**Comment by cgwalters** [comment]
On Fri, Mar 10, 2023, at 5:18 PM, Dusty Mabe wrote:
> @travier <https://github.com/travier> and I submitted together:
>
>  • Hands On With Fedora CoreOS (workshop/lab)
>  • Customize your server/desktop OS like a container    • highlights 
> OSTree Native Container uses for FCOS/Silverblue

Cool.  I submitted one with Sinny around the OCP version of this.  I also submitted a lightning talk on Bootc and the CentOS SIG.

If anyone wants to co present on the Bootc one let me know!

**Comment by dustymabe** [comment]
The devconf.us CFP submission deadline was extended to April 10th.

**Comment by travier** [comment]
The deadline is passed now. The workshop about FCOS has been accepted.
