### ISSUE TITLE
Old bootloader versions don't boot new aarch64 6.2+ kernels

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1441]
I just pro-actively updated my `t4g.medium` AWS instance to `38.20230310.1.0` and it didn't come back. Upon inspecting the serial console I see:

```
error: ../../grub-core/loader/arm64/linux.c:58:invalid magic number.
error: ../../grub-core/loader/arm64/linux.c:278:you need to load the kernel
first.  
        
Press any key to continue...
```

Pressing a key and selecting the older boot entry (thankfully I had console access) allowed me to re-connect with my system.

This system was provisioned a long time ago with `34.20210904.2.0` (`testing` stream; later moved over to the `next` stream to allow for earlier testing).

The problem here is that by default the bootloader on machines isn't updated so it keeps the one from when you first installed the machine. [bootupd](https://github.com/coreos/bootupd) was created to solve this problem, but is [still a work in progress](https://github.com/coreos/bootupd#status) so not widely used.

Here's what it shows on my system:

```
[core@dustymabe ~]$ sudo bootupctl status 
Component EFI
  Installed: grub2-efi-aa64-1:2.06-2.fc34.aarch64,shim-aa64-15.4-4.aarch64
  Update: Available: grub2-efi-aa64-1:2.06-88.fc37.aarch64,shim-aa64-15.6-2.aarch64
No components are adoptable.
CoreOS aleph image ID: fedora-coreos-34.20210904.2.0-qemu.aarch64.qcow2
Boot method: EFI
```

After updating the bootloader...

```
[core@dustymabe ~]$ sudo bootupctl update
Updated EFI: grub2-efi-aa64-1:2.06-88.fc37.aarch64,shim-aa64-15.6-2.aarch64
```

I am able to boot the system:

```
[core@dustymabe ~]$ rpm-ostree status 
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Wed 2023-03-15 19:38:43 UTC)
Deployments:
● fedora:fedora/aarch64/coreos/next
                  Version: 38.20230310.1.0 (2023-03-10T22:51:50Z)
                   Commit: b0fdf736cdbbd3971380d5549635e30155f07af6100925d987de623b4722637f
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464

  fedora:fedora/aarch64/coreos/next
                  Version: 37.20230303.1.0 (2023-03-06T18:55:26Z)
                   Commit: 0e785d34bddf7ff985fe49a4a9bdf2e88050c366f02b19f28df74b67fb3792ae
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A

```

This is most likely due to recent changes for aarch64 kernels around [EFI_ZBOOT](https://cateee.net/lkddb/web-lkddb/EFI_ZBOOT.html), which we also think is the root cause for https://github.com/coreos/fedora-coreos-tracker/issues/1430.

**Comment by cgwalters** [comment]
> but is [still a work in progress](https://github.com/coreos/bootupd#status) so not widely used.

:arrow_right: https://github.com/coreos/bootupd/pull/439

> After updating the bootloader...I am able to boot the system:

Yeah.  One option here I guess is to add cross-checks where at least rpm-ostree (or zincati) know how to query bootupd and block updates if it's too old.

**Comment by bgilbert** [comment]
> One option here I guess is to add cross-checks where at least rpm-ostree (or zincati) know how to query bootupd and block updates if it's too old.

I mean, ideally bootupd would update the bootloader automatically.  How far are we from being able to do that?

**Comment by cgwalters** [comment]
This is covered in https://github.com/coreos/bootupd/#questions-and-answers

**Comment by bgilbert** [comment]
Well, it says "perhaps in the future bootupd will use some of those".  If we prioritized doing the work, do we have the ability to implement it today, and how much effort would it be?

**Comment by cgwalters** [comment]
Updating automatically is trivial, just a systemd unit that runs `bootupctl update`.  Anyone who wants that has been able to do so for a long time.  The intermediate model of "only run bootupctl update when it's truly necessary" is probably a week of work and testing.  What's not trivial is updating *transactionally*.

**Comment by jlebon** [comment]
> The intermediate model of "only run bootupctl update when it's truly necessary" is probably a week of work and testing.

To flesh this out, this would be something like: attach metadata to each release about the "minimum bootloader version" and then enhance rpm-ostree to update the bootloader using bootupd if it detects that it's too old before finalizing an update?

This is not something we want to do in a rush, but we may be in a situation where we can pin on an older kernel for now to give us time to do something like this.

The risk I see is that we haven't been updating the bootloader at all so far, so now years of potential regressions could manifest all at once. Though that's a concern anyway whether users do it or we do it. And we know we want to eventually have automatic bootloader updates.

**Comment by dustymabe** [comment]
new investigation information:

This is confirmed to be specific to the `6.2` kernels and isn't tied to the Fedora 38 major release (i.e. when 6.2 hits F37 our `testing` and `stable` streams would also be affected if we don't pin).

**Comment by dustymabe** [comment]
I was trying to gauge how far back you'd have to go to get a bootloader/EFI binary that wasn't compatible. In my random sampling here's what I found:

- `36.20220906.1.0` ❌
    - `Installed: grub2-efi-aa64-1:2.06-52.fc36.aarch64,shim-aa64-15.6-2.aarch64`
- `37.20221111.1.0` ✔️
    - `Installed: grub2-efi-aa64-1:2.06-60.fc37.aarch64,shim-aa64-15.6-2.aarch64`

**Comment by travier** [comment]
F36 is supposed to be able to update to F38 per Fedora policies so we should file a bug for that. Likely for the kernel.

This also likely affects Silverblue/Kinoite/Sericea & IoT (and we don't have bootupd there yet unfortunately): https://github.com/fedora-silverblue/issue-tracker/issues/120

**Comment by dustymabe** [comment]
> F36 is supposed to be able to update to F38 per Fedora policies so we should file a bug for that. Likely for the kernel.

I think this might not affect non-OSTree EFI systems because (IIUC) the bits get updated by the RPM on upgrade so we need to be careful about how we approach this. Justin Forbes is aware of the problem.

It's also possible a fully updated F36 system can update to F38, but for FCOS we stopped building F36 when F37 came out. 

> This also likely affects Silverblue/Kinoite/Sericea & IoT (and we don't have bootupd there yet unfortunately): [fedora-silverblue/issue-tracker#120](https://github.com/fedora-silverblue/issue-tracker/issues/120)

Note that this is a limited failure scenario IIUC. The releases had to have been building and releasing for `aarch64` since sometime in f36. That at least removes Sericea from the list. Not sure about Kinoite. Also, there are probably not that many people running `aarch64` since there is limited laptop/desktop hardware available there.

**Comment by dustymabe** [comment]
Since this problem is introduced with 6.2 kernels my short term proposal for FCOS `next` is to [pin on the latest F37 6.1 kernel](https://github.com/coreos/fedora-coreos-config/pull/2304) while we come up with our next steps.

For our next steps, I discussed this briefly with @jlebon yesterday. Here are a few potential options for us:

- run `bootupctl update` on every update
    - noting that for the first boot we'd [still be using the N-1 bootloader](https://github.com/coreos/bootupd/issues/108).
- run `bootupctl update` on select updates (maybe once a fedora major or something)
- use a systemd generator to detect when this specific problem (old old bootloader on aarch64/EFI) would occur and disable zincati and drop down CLHM warnings for the user telling them what to do
    - this puts the bootloader update (and the risk) in the user's hands

**Comment by bgilbert** [comment]
Note that we only caught this in advance because Dusty had an aarch64 system that he manually updated before the rollout started.  Thanks, Dusty, for doing that!  ...but we shouldn't rely on it.  How can we improve our upgrade testing to catch this case?

**Comment by dustymabe** [comment]
> How can we improve our upgrade testing to catch this case?

I added myself as assignee for https://github.com/coreos/coreos-assembler/issues/2519 to make it happen.

**Comment by travier** [comment]
Filed https://github.com/coreos/bootupd/issues/440

**Comment by travier** [comment]
Filed https://github.com/fedora-silverblue/issue-tracker/issues/434 for Silverblue/Kinoite

**Comment by travier** [comment]
Also filed: https://github.com/coreos/bootupd/issues/441

**Comment by bgilbert** [comment]
@dustymabe, @jlebon, @travier, and I discussed this OOB.

## Mitigation plan for `next`

- [ ] Deadend `next` 38.20230310.1.0 and revoke it from stream metadata.  Existing installs of 38.20230310.1.0 wouldn't be able to update without downgrading through the 37 barrier release, which isn't safe.  Rather than trying to do complex mitigations for that, it's easiest and safest to just drop that release on the floor, and shouldn't affect too many users.   https://github.com/coreos/fedora-coreos-streams/pull/667
- [ ] coreos-status announcement
- [ ] Revert F38 promotion from `next` branch
- [ ] Add service unit that triggers a `bootupctl update` unconditionally on boot on aarch64 UEFI only.
  - [ ] Check that this won't break Raspberry Pi in device-tree mode
  - [ ] Test
- [ ] Roll out F37 `next` release as a barrier release
- [ ] Remove `bootupctl` service unit from `next`
- [ ] Re-promote F38 to `next`
- [ ] Unpin 6.2 kernel
- [ ] Roll out new `next` release

## Mitigation plan for `testing` (less urgent)

- [ ] Add service unit to `testing-devel`
- [ ] Roll out barrier release
- [ ] Remove service unit

## Release timing

- Ad-hoc next release with bootloader update early next week
- Regular triple release toward the end of the week, including bootloader update for `testing` and F38+6.2 for `next`

**Comment by cgwalters** [comment]
> Add service unit that triggers a bootupctl update unconditionally on boot on aarch64 UEFI only. 

Was there a specific rationale for aarch64 only?  Trying to limit the blast radius?  One concern I have is that then we're going to be testing the flow less, particularly given our CI is predominantly x86_64.

**Comment by bgilbert** [comment]
Trying to limit the blast radius, yes.  We'll need to broaden to x86_64 later, but for now, we're doing this rollout under some degree of schedule pressure and it's automating an operation that hasn't been broadly field-tested before.  @dustymabe is going to put together a purpose-built upgrade test to validate this.

**Comment by dustymabe** [comment]
Just leaving a note here. I tested on RPi4 with both ways of installing that we have [documented](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/) (both uboot and EDK2).

Both of these install methods leverage EFI. Both ways are affected by this bootloader problem. Both ways are fixed via `bootupctl update`.

**Comment by bgilbert** [comment]
@dustymabe reports that the systemd unit correctly runs on RPi4+uboot.  (It's presumed to also work on RPi4+EDK2.)

**Comment by dustymabe** [comment]
PR to mark `37.20230303.1.1` as a barrier: https://github.com/coreos/fedora-coreos-streams/pull/671

**Comment by nullr0ute** [comment]
> The fix for this went into `next` stream release `37.20230303.1.1`. Please try out the new release and report issues.

Do you have a link to this fix/PR so we can ensure we do the same for IoT? Thx

**Comment by dustymabe** [comment]
Hey @nullr0ute - sorry, it's linked earlier from a callback link. Here's the fix for FCOS: https://github.com/coreos/fedora-coreos-config/pull/2307. Note that it's targetted specifically at `aarch64` + `uefi`, since that's the specific problem we are solving here. We'll roll out a more generic/permanent/always-on bootloader update in the future.

Unfortunately, IIUC, this won't work for IoT because I don't think `bootupd` is included currently in IoT. If you could ship `bootupd` and the systemd service unit before shipping kernel 6.2 then it would solve the problem.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20230322.2.0`. Please try out the new release and report issues.

**Comment by goshansp** [comment]
My rpi3 would give the `invalid magic number` issue when booting from `37.20230330.0`. Then `bootupctl update` on `37.20230320.0` would give `error: connecting to /run/bootupd.sock: ENOENT: No such file or directory`. Finally this got us back on track:
```
sudo grub2-switch-to-blscfg
sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
```
Now we have `rpm-ostree upgrade` to ` 37.20230330.0` and booting with success.

**Comment by dustymabe** [comment]
> Then `bootupctl update` on `37.20230320.0` would give `error: connecting to /run/bootupd.sock: ENOENT: No such file or directory`.

Just a guess here.. You probably needed to run it under `sudo`. i.e. via `sudo bootupctl update`.


Either way, if you were on Fedora CoreOS and following our automatic updates you should have never hit this problem. Can you share more about your setup?

**Comment by dustymabe** [comment]
> Can you share more about your setup?

Judging from your version numbers, you're probably on Silverblue?

**Comment by goshansp** [comment]
I didn't follow automatic updates on IoT as I update manually and infrequent. 
```
[hp@rpi01 ~]$ sudo bootupctl status
error: connecting to /run/bootupd.sock: ENOENT: No such file or directory
[hp@rpi01 ~]$ rpm-ostree status
State: idle
Deployments:
● fedora-iot:fedora/stable/aarch64/iot
                  Version: 37.20230330.0 (2023-03-30T13:39:02Z)
               BaseCommit: 6a3886990fb729818409d884e083f6581a311627d208f00e9dfe9664bad9c1ee
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
          LayeredPackages: bootupd git python-pip python3-libgpiod
...
[hp@rpi01 ~]$ rpm -qa | grep bootup
bootupd-0.2.8-3.fc37.aarch64
```

**Comment by goshansp** [comment]
As I've found the bootupctl issue on my silverblue spin as well, hence opened https://github.com/coreos/bootupd/issues/455

**Comment by bgilbert** [comment]
Checklist in https://github.com/coreos/fedora-coreos-tracker/issues/1441#issuecomment-1474062906 complete.

**Comment by dustymabe** [comment]
To reduce confusion I'm going to go through and mark comments related to Silberblue or IoT as off-topic since this is an FCOS issue tracker.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20230322.3.0`.

**Comment by bgilbert** [comment]
It turns out that the fix doesn't work for systems with mirrored disks: https://github.com/coreos/fedora-coreos-tracker/issues/1485
