### ISSUE TITLE
Fedora CoreOS preview release

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#145]
Fedora CoreOS will include a variety of new features and components, including: a multiple-stream structure with promotions and backported fixes, staged update rollout with reboot coordination, the Ignition 3.0 spec, live PXE support, metrics, a Fedora CoreOS config transpiler, and migration tooling from Container Linux.  It will also need to support much of the functionality and use cases of Container Linux.  With the magnitude of new work going into Fedora CoreOS, it would be useful to have a public preview period during which we can fix bugs and make breaking changes before the OS is deployed into production use.

A preview period could work like this:

1. The initial preview release would occur sometime after the release of F30.
1. Soon after F31 is released, Fedora CoreOS would rebase onto it via the usual `testing` -> `stable` promotion process.
1. Soon after, Fedora CoreOS would be declared stable and thus suitable for production use.

The preview release would aim to provide a working OS that is ready for broader use and feedback.  While it should give a good sense of what Fedora CoreOS will be, it would not be feature-complete, well-documented, or production-ready.  There would undoubtedly be environments or use cases where the OS will not work properly.  We'd also want to preserve the ability to make breaking changes to the OS if necessary.

## Implications for Fedora Atomic Host

Fedora Atomic Host would not be rebased onto Fedora 30.  It would continue to have two-week releases through the lifetime of F29, and then would be EOL.

## Implications for Container Linux

Container Linux EOL would occur ~6 months after Fedora CoreOS goes stable.  We'd want to announce a concrete EOL date with plenty of advance notice.  Migration tooling would likely not be complete for the initial preview release, but would improve throughout the preview period and be ready for production use by the stable release.

**Comment by vtolstov** [comment]
nice! where i can find info about live pxe support and staged update? (i'm use custom builded ostree from fedora 29 now)

**Comment by dustymabe** [comment]
> nice! where i can find info about live pxe support and staged update? (i'm use custom builded ostree from fedora 29 now)

This issue is where you can track progress on live pxe support: https://github.com/coreos/fedora-coreos-tracker/issues/105

**Comment by dustymabe** [comment]
Discussed in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/77ET7IPYB6IZ7ODF2GACID6DF4UEX46V/). In general the idea seems sane. Will try to socialize further.

**Comment by bgilbert** [comment]
@vtolstov Update rollout is being discussed in https://github.com/coreos/fedora-coreos-tracker/issues/83.

**Comment by bgilbert** [comment]
Fedora CoreOS preview has been [released](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/3HTW5SLUY6X2Y5SFXJSE4BWEDNJ2J5SL/)!
