### ISSUE TITLE
podman uses incorrect mapping for idmapped mounts

### ISSUE THREAD

**Issue by M1cha** [coreos/fedora-coreos-tracker#1455]
See this issue: https://github.com/containers/crun/issues/1182
crun >= 1.8.1 requires podman >= 4.4.4, meaning idmapped mounts are currently broken on all channels, including `stable` at `37.20230303.3.0`.

**Comment by travier** [comment]
podman 4.4.4 update is currently in testing: https://bodhi.fedoraproject.org/updates/FEDORA-2023-c40519168b

**Comment by travier** [comment]
Please use the issue template next time. Thanks

**Comment by M1cha** [comment]
sry about the template, no idea how that happened.
I was relying at the website to check which version is in other channels and there it still shows 4.4.2: https://getfedora.org/en/coreos?stream=testing

**Comment by travier** [comment]
Sorry, it's in Fedora testing repository, not yet in Fedora CoreOS testing stream.

**Comment by dustymabe** [comment]
We'll try to have [`podman-4.4.4-3.fc37`](https://bodhi.fedoraproject.org/updates/FEDORA-2023-c40519168b) in the next round of releases.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230408.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230414.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230414.3.0`.

**Comment by M1cha** [comment]
Sorry for not giving feedback during the testing phase. I'm running on bare metal and only have a single instance. I never got around setting up a VM for providing early feedback on those fixes.

Also: is there a delay within the streams used by zincati? The new build is available in downloads but not on the stable stream yet.

**Comment by dustymabe** [comment]
> Also: is there a delay within the streams used by zincati? The new build is available in downloads but not on the stable stream yet.

Once a release goes out the update server and zincati stage the rollout over a period of time (usually 48H). You can configure your systems to be more aggressive about adopting updates if you like: https://docs.fedoraproject.org/en-US/fedora-coreos/auto-updates/#_wariness_to_updates
