### ISSUE TITLE
Use NetworkManager to tear down networking on Ignition boot

### ISSUE THREAD

**Issue by jtoppins** [coreos/fedora-coreos-tracker#1459]
https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-teardown-initramfs.sh#L190

In thinking more about the whole service that effectively does `for i in $(ls /sys/class/net) do; ip link set $i down; done`. I don't see why this is needed, wouldn't in effect the same thing be accomplished if simply the networking service were stopped?

**Comment by dustymabe** [comment]
Potential fix in https://github.com/coreos/fedora-coreos-config/pull/2355

**Comment by jlebon** [comment]
> Potential fix in [coreos/fedora-coreos-config#2355](https://github.com/coreos/fedora-coreos-config/pull/2355)

Note this was reverted in https://github.com/coreos/fedora-coreos-config/pull/2658. Let's re-open this to track reverting the revert.

**Comment by jlebon** [comment]
To check whether this is safe to revert: build FCOS and RHCOS 9.4 with the revert reverted, build AMIs, upload them, then provision e.g. 20 `m4.metal` instances. Check that they all successfully come up.
