### ISSUE TITLE
New Package Request: ipcalc

### ISSUE THREAD

**Issue by zaneb** [coreos/fedora-coreos-tracker#1460]
### What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

Nothing additional, it's a standalone binary that only depends on glibc.

### What is the size of the package and its dependencies?

82KB, but only 57KB for the binary - the rest is documentation.

### What problem are you trying to solve with this package? Or what functionality does the package provide?

Often in network setup scripts it is really helpful to do stuff like converting between netmasks and CIDRs, figuring out whether a certain IP is in a certain CIDR, &c. It's almost impossible to do this stuff correctly for IPv6 in bash/awk, and pretty painful for IPv4. `ipcalc` allows you to do all of this and more from a bash script without having to compile anything or bring in an interpreted language runtime.

### Can the software provided by the package be run from a container?  Explain why or why not.

Usually you need this before networking is up so pulling a container image may not be an option.

### Can the tool(s) provided by the package be helpful in debugging container runtime issues?

Probably not.

### Can the tool(s) provided by the package be helpful in debugging networking issues?

Yes, definitely. There's a lot of human-readable output options.

### Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

Usually you need this before networking is up.

### In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

N/A, this is just a binary.

### Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS?

I'd be shocked if it could.

### Does the software provided by the package have a history of CVEs?

No.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/6EYIC43YJEMYGGUSQOFGQ5BSFO4BWTMP/).

@zaneb - We'd like to know more about your use case where you are using "network setup scripts" on the system. We typically have networking configured using [NetworkManager config files](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/) in which you wouldn't be dynamically calculating network slices. Can you illustrate your workflow for us?

**Comment by zaneb** [comment]
https://github.com/openshift/installer/pull/6111/files/023d5ef3a985d2fdbe2e05954b24ce05ba9ab38e#r918472605 was the specific discussion I was remembering that prompted me to add this request.
It looks like this was indeed after the network is configured, but I can imagine other uses (e.g. in a NetworkManager dispatcher script).

**Comment by jlebon** [comment]
> [openshift/installer/pull/6111/files/023d5ef3a985d2fdbe2e05954b24ce05ba9ab38e#r918472605](https://github.com/openshift/installer/pull/6111/files/023d5ef3a985d2fdbe2e05954b24ce05ba9ab38e#r918472605) was the specific discussion I was remembering that prompted me to add this request.

Trying to clarify this a bit to better understand the use case. Can you confirm if my interpretation is correct?

It seems like the idea there was to auto-determine the node IP that the kubelet should report based on a user-configured machine CIDR. So e.g. if the nodes have multiple network interfaces offering different routes, you need a way to know which IP to select as the in-cluster node IP.

**Comment by zaneb** [comment]
Yes, that was exactly it.

**Comment by jlebon** [comment]
This kinda feels like something that should be written in !bash with proper APIs to deal with IP addresses. But not strongly against baking it in either. There's definitely a lot of network scripts out there written in shell script.

**Comment by cgwalters** [comment]
I'm +0.5 to this...it's small.  But I think again ultimately we should be doing more of this stuff from container images, and we're already running containers from bootkube.sh.  

The dispatcher script case...well, ultimately I think anything nontrivial like this needs to do "two phase" initialization anyways where we get a basic network setup going, enough to pull the container image, then re-setup with the dispatcher script in place.

**Comment by travier** [comment]
I'm -0.5 to this. To me this should live in a container. Each "report back to cluster" script is going to look different and use different tools. If this is not needed to setup the network, we should not add it.

But it's super small, so fine with adding it.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/DGPKVE3ZMYHCZMK5Z2T62HCV6AQ7HNOU/).

```
 12:50:23* dustymabe | #agreed we'll include ipcalc to aid in some advanced custom
                     | networking calculations.
```

**Comment by dustymabe** [comment]
This was added in https://github.com/coreos/fedora-coreos-config/pull/2426

**Comment by zaneb** [comment]
Thanks everyone!

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230527.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230527.3.0`.
