### ISSUE TITLE
upgrades with 6.2 kernels running out of space on `aarch64`

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1464]
With our [recently implemented extended upgrade testing](https://github.com/coreos/coreos-assembler/issues/2519#issuecomment-1489327365) we are now running a matrix of extended upgrade tests when we do production builds.

With the (unreleased) `38.20230408.1.0` `next` build we are now hitting a problem where we are running out of space on upgrade:

```
Apr 11 21:43:24.721835 ostree[688]: error: ostree-finalize-staged.service failed on previous boot:
Installing kernel: Copying smk-k26-revA-sm-k26-revA-sck-kv-g-revB.dtb: regfile copy: No space left on device
```

Full logs for the upgrade test (`38.20230322.1.0`->`38.20230408.1.0`) are here: 

- [kola-uefi-14f77a26.console.txt](https://github.com/coreos/fedora-coreos-tracker/files/11213603/kola-uefi-14f77a26.console.txt)
- [kola-uefi-14f77a26.journal.txt](https://github.com/coreos/fedora-coreos-tracker/files/11213604/kola-uefi-14f77a26.journal.txt)

The `next` stream is now sitting at two releases with kernel-6.2 and this would be the third:

- `38.20230322.1.0` -> `38.20230402.1.0` -> `38.20230408.1.0` 

Noteworthy is the fact that with 6.2 the kernel changed formatting of the kernel to [EFI_ZBOOT](https://cateee.net/lkddb/web-lkddb/EFI_ZBOOT.html). 

The usage in /boot/ is only slightly larger but apparently it's enough to get us to a threshold where we run out of space when trying to fit 3 sets of kernel/initramfs at the same time (temporarily on upgrade).

For illustration here is the usage of a non 6.2 kernel deployment and a 6.2 kernel deployment on the same system (this is a `testing` stream based system):

```
[builder@coreos-aarch64-builder]$ rpm-ostree status 
State: idle
warning: Failed to query journal: couldn't find current boot in journal
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Wed 2023-04-12 13:21:41 UTC)
Deployments:
● fedora:fedora/aarch64/coreos/testing
                  Version: 37.20230401.2.0 (2023-04-03T20:03:03Z)
                   Commit: c375f7121f9804de91d70dac1e9f96a829e61a23de4b9e7ec9d1540af37083e2
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A

  fedora:fedora/aarch64/coreos/testing
                  Version: 37.20230322.2.0 (2023-03-22T18:10:46Z)
                   Commit: f5b62128344d8484773481f6b9fd89ca5c0b74af685022d807207c97aa242c6e
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A


[builder@coreos-aarch64-builder]$ rpm --root /sysroot/ostree/deploy/fedora-coreos/deploy/c375f7121f9804de91d70dac1e9f96a829e61a23de4b9e7ec9d1540af37083e2.0/ -q kernel
kernel-6.2.8-200.fc37.aarch64
[builder@coreos-aarch64-builder]$ rpm --root /sysroot/ostree/deploy/fedora-coreos/deploy/f5b62128344d8484773481f6b9fd89ca5c0b74af685022d807207c97aa242c6e.0/ -q kernel
kernel-6.1.18-200.fc37.aarch64


[builder@coreos-aarch64-builder fcos]$ du -sh /boot/ostree/*
111M    /boot/ostree/fedora-coreos-42e69e7bfcdf67d34ac950fd672ec4630904f6500ed73a018e24b93dcdec442c
115M    /boot/ostree/fedora-coreos-698b48a4df1602c282cd422c92ddc0dc065b8fb51f873909bd6f968852b7d0c7
```

If I boot `38.20230408.1.0` clean I see:

```
[core@cosa-devsh ~]$ rpm-ostree status
State: idle
AutomaticUpdatesDriver: Zincati
  DriverState: active; periodically polling for updates (last checked Wed 2023-04-12 16:08:05 UTC)
Deployments:
● fedora:fedora/aarch64/coreos/next
                  Version: 38.20230408.1.0 (2023-04-11T20:00:06Z)
                   Commit: d63b65f25908f417157805850421a39af3cb719f7970f36e0e2ffc29097db139
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464

[core@cosa-devsh ~]$ sudo du -sh /boot/ostree/*
116M    /boot/ostree/fedora-coreos-eeca130c728b59599b77e10f70f5dba4d39d95d4d2d49c16dd5fb042cccf4260
[core@cosa-devsh ~]$ sudo du -sh /boot/ostree/*/*
29M     /boot/ostree/fedora-coreos-eeca130c728b59599b77e10f70f5dba4d39d95d4d2d49c16dd5fb042cccf4260/dtb
72M     /boot/ostree/fedora-coreos-eeca130c728b59599b77e10f70f5dba4d39d95d4d2d49c16dd5fb042cccf4260/initramfs-6.2.9-300.fc38.aarch64.img
16M     /boot/ostree/fedora-coreos-eeca130c728b59599b77e10f70f5dba4d39d95d4d2d49c16dd5fb042cccf4260/vmlinuz-6.2.9-300.fc38.aarch64
```

**Comment by dustymabe** [comment]
Note that this is basically a new occurence of https://github.com/coreos/fedora-coreos-tracker/issues/1247 which will affect our production streams if we don't act.

**Comment by jlebon** [comment]
For more information, here's a comparison of the different sizes between the very first aarch64 image we built and the latest one.

On 34.20210821.3.0:

```
# du -sh *
14M     dtb
68M     initramfs-5.13.12-200.fc34.aarch64.img
13M     vmlinuz-5.13.12-200.fc34.aarch64
```

On 38.20230408.1.0:

```
# du -sh *
29M     dtb
72M     initramfs-6.2.9-300.fc38.aarch64.img
16M     vmlinuz-6.2.9-300.fc38.aarch64
```

So the kernel only increased by 3M, the initrd by 4M, and the dtb directory by 15M.

It'd be nice to be able to trim some of those devicetrees though it's theoretically possible that some users have installed FCOS on some of these boards.

**Comment by nullr0ute** [comment]
> It'd be nice to be able to trim some of those devicetrees though it's theoretically possible that some users have installed FCOS on some of these boards.

Depending on the firmwares, if they're SystemReady devices you could in theory remove all of the DTBs. For example in traditional Fedora if the dtb symlink isn't there it will use the DT provided by the firmware, but of course there's some devices that won't boot in that case. What size is /boot? the recommended default from anaconda should be OK.

**Comment by nullr0ute** [comment]
Looking at the directory of a recent F-38:

````
$ du -h /boot/dtb-6.2.9-300.fc38.aarch64/|sort -h
12K     /boot/dtb-6.2.9-300.fc38.aarch64/cavium
24K     /boot/dtb-6.2.9-300.fc38.aarch64/amd
40K     /boot/dtb-6.2.9-300.fc38.aarch64/apm
168K    /boot/dtb-6.2.9-300.fc38.aarch64/broadcom
188K    /boot/dtb-6.2.9-300.fc38.aarch64/hisilicon
252K    /boot/dtb-6.2.9-300.fc38.aarch64/arm
592K    /boot/dtb-6.2.9-300.fc38.aarch64/apple
640K    /boot/dtb-6.2.9-300.fc38.aarch64/marvell
660K    /boot/dtb-6.2.9-300.fc38.aarch64/ti
740K    /boot/dtb-6.2.9-300.fc38.aarch64/xilinx
1.2M    /boot/dtb-6.2.9-300.fc38.aarch64/allwinner
1.2M    /boot/dtb-6.2.9-300.fc38.aarch64/nvidia
2.5M    /boot/dtb-6.2.9-300.fc38.aarch64/amlogic
4.2M    /boot/dtb-6.2.9-300.fc38.aarch64/freescale
4.4M    /boot/dtb-6.2.9-300.fc38.aarch64/rockchip
14M     /boot/dtb-6.2.9-300.fc38.aarch64/qcom
30M     /boot/dtb-6.2.9-300.fc38.aarch64/
````
I would say if you removed qcom you'd get your 14Mb back an be unlikely to have a complaint YMMV

**Comment by jlebon** [comment]
Draft coreos-status email: https://hackmd.io/bq_3hYQHRKapbIZW-UpVtw

**Comment by dustymabe** [comment]
with https://github.com/coreos/fedora-coreos-config/pull/2367 we now have something like:

```
[core@cosa-devsh ~]$ sudo du -sh /boot/ostree/*
102M    /boot/ostree/fedora-coreos-5463cfa9e9b1e44c5f5bb7185e14fc907f7a093088a5bd542e58b45997ac60c6
```

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/6EYIC43YJEMYGGUSQOFGQ5BSFO4BWTMP/).

```
13:09:07*  dustymabe | #agreed we will try to remove the qcom dtb
                     | files and see if that gets us unblocked for
                     | now and then we'll deploy the ostree
                     | autoprune in the coming weeks as a more
                     | permanent "short-term" solution.

```

**Comment by dustymabe** [comment]
The update with removed qcom files went out in our `next` stream today in `38.20230408.1.1`

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230408.1.1`. Please try out the new release and report issues.

**Comment by jlebon** [comment]
Note we decided not to send out an email for this issue in the end. We believe there are few users (likely none) on these platforms. Nonetheless, I've opened https://github.com/coreos/fedora-coreos-tracker/issues/1467 to track the reversal of this change and serve as a landing point for anyone trying to get FCOS to work on the now broken devices.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230414.2.0`. Please try out the new release and report issues.
