### ISSUE TITLE
Add back Qualcomm DTBs on aarch64

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1467]
In https://github.com/coreos/fedora-coreos-tracker/issues/1464, we decided to [temporarily remove](https://github.com/coreos/fedora-coreos-config/pull/2367) the Qualcomm device tree blobs to make enough space in the boot partition to allow for future upgrades. This was done because we deemed the likelihood of users being affected by this removal to be minimal.

This ticket tracks adding the blobs back once we can rely on https://github.com/ostreedev/ostree/pull/2847.

**Comment by dustymabe** [comment]
This [upstream PR](https://github.com/ostreedev/ostree/pull/2847) merged 🎉. Once we get a new release of `ostree` we can then add back in the Qualcomm DTBs.

**Comment by cgwalters** [comment]
> Once we get a new release of ostree we can then add back in the Qualcomm DTBs.

No, because it's not on by default yet.

**Comment by jlebon** [comment]
> > Once we get a new release of ostree we can then add back in the Qualcomm DTBs.
> 
> No, because it's not on by default yet.

I think the idea is to turn this on in FCOS, possibly only on multi-arch. Will open a separate ticket to discuss this.

But anyway, if it works well in FCOS for a while, then we could consider turning it on upstream too?

**Comment by dustymabe** [comment]
In https://github.com/coreos/fedora-coreos-config/pull/2435 the DTBs were added back for F39+. This change will follow F39 and get fixed when that gets merged over into our production streams.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `39.20230916.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `39.20231101.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `39.20231101.3.0`.
