### ISSUE TITLE
Ship podman 4.5.x in Fedora CoreOS

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1471]
This was [recently released](https://github.com/containers/podman/releases/tag/v4.5.0). Let's get it in if it passes CI tests.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230417.1.0`. Please try out the new release and report issues.

**Comment by Nemric** [comment]
I did just run 3 image build/push from a Jenkins that run on podman 4.5, with jenkins node/agent that also run on podman4.5 and that drive the podman socket with podman-remote also in v4.5
Everything was fine ans did work as expected

I'll going forward with quadlet testing and will, in longterm unfortunately, GO for quadlet user (and system) units in ignition if POCs are ok
quadlet is a new born tech and didn't implement "logdriver" (as an example) in 4.4 and some other arguments
It looks like it's so promising !

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230430.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230430.3.1`.
