### ISSUE TITLE
Ship moby-engine 24.0.x

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1476]
Package maintainership of `moby-engine` (`docker`) in Fedora has [changed hands](https://github.com/coreos/fedora-coreos-tracker/issues/1291) and the first large version update in a long time is [on the horizon](https://bugzilla.redhat.com/show_bug.cgi?id=2093501):

- https://bodhi.fedoraproject.org/updates/FEDORA-2023-f0bb213148

We should try to ship this to our users.

**Comment by dustymabe** [comment]
Our automated test coverage of the `docker` CLI is pretty lacking. I'm wondering if we should try to ship this in `next` for some time before hoisting it to `testing` and `stable`.

**Comment by dustymabe** [comment]
PR to pin moby to the current version until we discuss how we want to handle this bump in our next meeting:

- https://github.com/coreos/fedora-coreos-config/pull/2394

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/PPCRDSWPCC2W4VYCFZPAJM5HZ7B3T6RC/).

```
12:59:30  dustymabe | #agreed once this makes it into bodhi stable we will add it to
                    | our `next` stream for at least a month to gather feedback before
                    | promoting it.

```

**Comment by dustymabe** [comment]
At this point we'll wait for the new version of `moby-engine` to land in Bodhi stable.

**Comment by fifofonix** [comment]
Experimentally upgrading a node to rawhide with `sudo rpm-ostree rebase fedora-compose:fedora/x86_64/coreos/rawhide` I can see that it operates fine as a docker swarm worker node with the new `moby-engine`.  This is not a comprehensive test but at least validates compatibility with lower version swarm manager nodes, scheduling of services, and a bunch of network connectivity / file mount things. A good next step would be upgrading a manager node but that is going to have to wait.

**Comment by dustymabe** [comment]
The new version of moby-engine is in `rawhide` and will ship with F39 unless something changes.

From discussion in the bug [comment#70](https://bugzilla.redhat.com/show_bug.cgi?id=2093501#c70) it appears the version currently in rawhide/F39 is deficient and may represent regressions for some use cases.

**Comment by prestist** [comment]
We talked about this in today's [meeting](https://discussion.fedoraproject.org/t/fedora-coreos-meeting-minutes-2023-08-23/87887). Removing meeting label.

AGREED: we will pick up the moby-engine update when our streams transition to Fedora 39. We will add a note to our f39 release communication about the update and any considerations that need to be made. (spresti, 17:03:49)

**Comment by dustymabe** [comment]
Looks like it was updated to `24.0.5` [recently](https://src.fedoraproject.org/rpms/moby-engine/c/94a83534c50ef10c8deaf9487227ef17c27639e8?branch=rawhide).

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `39.20230916.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
Fallout from this update: https://github.com/coreos/fedora-coreos-tracker/issues/1578

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `39.20231101.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `39.20231101.3.0`.
