### ISSUE TITLE
libGL error

### ISSUE THREAD

**Issue by blackshadow2002** [coreos/fedora-coreos-tracker#1482]
### Describe the bug

I'm using Fedora 38 on AMD Ryzen 5500U processor powered laptop and when I tried to run a OpenGL program, I am getting this-

I installed these packages:
yum install mesa-libGL-devel mesa-libGLU-devel freeglut-devel

Issue:
 libGL error: DRI driver not from this Mesa build ('23.0.2' vs '23.0.3')
libGL error: failed to load driver: radeonsi
libGL error: DRI driver not from this Mesa build ('23.0.2' vs '23.0.3')
libGL error: failed to load driver: swrast
freeglut (./a.out): Unable to create OpenGL 1.0 context (flags 0, profile 0)
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  51
  Current serial number in output stream:  52

### Reproduction steps

1. g++ fogtst.c -lglut -lGL -lGLU -lm -lx11 -lm
2. ./a.out

### Expected behavior

![Screenshot from 2023-04-28 19-45-08](https://user-images.githubusercontent.com/93479936/235176736-fc6daa67-4a26-4a76-a78a-e20cddd01061.png)

### Actual behavior

![Screenshot from 2023-04-28 19-46-23](https://user-images.githubusercontent.com/93479936/235176527-1cac99a3-63f3-4aee-bc98-e1e65e963ca4.png)

### System details

- Fedora 38
- AMD Ryzen 5500U processor powered laptop with integrated Radeon graphics.

### Additional information

//fogtst.c

/* Copyright (c) Mark J. Kilgard, 1994. */

/**
 * (c) Copyright 1993, Silicon Graphics, Inc.
 * ALL RIGHTS RESERVED 
 * Permission to use, copy, modify, and distribute this software for 
 * any purpose and without fee is hereby granted, provided that the above
 * copyright notice appear in all copies and that both the copyright notice
 * and this permission notice appear in supporting documentation, and that 
 * the name of Silicon Graphics, Inc. not be used in advertising
 * or publicity pertaining to distribution of the software without specific,
 * written prior permission. 
 *
 * THE MATERIAL EMBODIED ON THIS SOFTWARE IS PROVIDED TO YOU "AS-IS"
 * AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE,
 * INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR
 * FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL SILICON
 * GRAPHICS, INC.  BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT,
 * SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY
 * KIND, OR ANY DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION,
 * LOSS OF PROFIT, LOSS OF USE, SAVINGS OR REVENUE, OR THE CLAIMS OF
 * THIRD PARTIES, WHETHER OR NOT SILICON GRAPHICS, INC.  HAS BEEN
 * ADVISED OF THE POSSIBILITY OF SUCH LOSS, HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE
 * POSSESSION, USE OR PERFORMANCE OF THIS SOFTWARE.
 * 
 * US Government Users Restricted Rights 
 * Use, duplication, or disclosure by the Government is subject to
 * restrictions set forth in FAR 52.227.19(c)(2) or subparagraph
 * (c)(1)(ii) of the Rights in Technical Data and Computer Software
 * clause at DFARS 252.227-7013 and/or in similar or successor
 * clauses in the FAR or the DOD or NASA FAR Supplement.
 * Unpublished-- rights reserved under the copyright laws of the
 * United States.  Contractor/manufacturer is Silicon Graphics,
 * Inc., 2011 N.  Shoreline Blvd., Mountain View, CA 94039-7311.
 *
 * OpenGL(TM) is a trademark of Silicon Graphics, Inc.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <GL/glut.h>

GLenum doubleBuffer;
/* *INDENT-OFF* */
double plane[4] = {
  1.0, 0.0, -1.0, 0.0
};
float rotX = 5.0, rotY = -5.0, zTranslate = -65.0;
float fogDensity = 0.02;
GLint cubeList = 1;

float scp[18][3] = {
  {1.000000, 0.000000, 0.000000},
  {1.000000, 0.000000, 5.000000},
  {0.707107, 0.707107, 0.000000},
  {0.707107, 0.707107, 5.000000},
  {0.000000, 1.000000, 0.000000},
  {0.000000, 1.000000, 5.000000},
  {-0.707107, 0.707107, 0.000000},
  {-0.707107, 0.707107, 5.000000},
  {-1.000000, 0.000000, 0.000000},
  {-1.000000, 0.000000, 5.000000},
  {-0.707107, -0.707107, 0.000000},
  {-0.707107, -0.707107, 5.000000},
  {0.000000, -1.000000, 0.000000},
  {0.000000, -1.000000, 5.000000},
  {0.707107, -0.707107, 0.000000},
  {0.707107, -0.707107, 5.000000},
  {1.000000, 0.000000, 0.000000},
  {1.000000, 0.000000, 5.000000},
};

static float ambient[] = {0.1, 0.1, 0.1, 1.0};
static float diffuse[] = {1.0, 1.0, 1.0, 1.0};
static float position[] = {90.0, 90.0, 0.0, 0.0};
static float front_mat_shininess[] = {30.0};
static float front_mat_specular[] = {0.0, 0.0, 0.0, 1.0};
static float front_mat_diffuse[] = {0.0, 1.0, 0.0, 1.0};
static float back_mat_shininess[] = {50.0};
static float back_mat_specular[] = {0.0, 0.0, 1.0, 1.0};
static float back_mat_diffuse[] = {1.0, 0.0, 0.0, 1.0};
static float lmodel_ambient[] = {0.0, 0.0, 0.0, 1.0};
static float fog_color[] = {0.8, 0.8, 0.8, 1.0};
/* *INDENT-ON* */

/* ARGSUSED1 */
static void
Key(unsigned char key, int x, int y)
{
  switch (key) {
  case 'd':
    fogDensity *= 1.10;
    glFogf(GL_FOG_DENSITY, fogDensity);
    glutPostRedisplay();
    break;
  case 'D':
    fogDensity /= 1.10;
    glFogf(GL_FOG_DENSITY, fogDensity);
    glutPostRedisplay();
    break;
  case 27:
    exit(0);
  }
}

/* ARGSUSED1 */
static void
SpecialKey(int key, int x, int y)
{
  switch (key) {
  case GLUT_KEY_UP:
    rotX -= 5;
    glutPostRedisplay();
    break;
  case GLUT_KEY_DOWN:
    rotX += 5;
    glutPostRedisplay();
    break;
  case GLUT_KEY_LEFT:
    rotY -= 5;
    glutPostRedisplay();
    break;
  case GLUT_KEY_RIGHT:
    rotY += 5;
    glutPostRedisplay();
    break;
  }
}

static void
Draw(void)
{
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

  glPushMatrix();

  glTranslatef(0, 0, zTranslate);
  /* XXX hooky dual axis rotation! */
  glRotatef(rotY, 0, 1, 0);
  glRotatef(rotX, 1, 0, 0);
  glScalef(1.0, 1.0, 10.0);

  glCallList(cubeList);

  glPopMatrix();

  if (doubleBuffer) {
    glutSwapBuffers();
  } else {
    glFlush();
  }
}

static void
Args(int argc, char **argv)
{
  GLint i;
  doubleBuffer = GL_TRUE;

  for (i = 1; i < argc; i++) {
    if (strcmp(argv[i], "-sb") == 0) {
      doubleBuffer = GL_FALSE;
    } else if (strcmp(argv[i], "-db") == 0) {
      doubleBuffer = GL_TRUE;
    }
  }
}

int
main(int argc, char **argv)
{
  GLenum type;

  glutInit(&argc, argv);
  Args(argc, argv);

  type = GLUT_RGB | GLUT_DEPTH;
  type |= (doubleBuffer) ? GLUT_DOUBLE : GLUT_SINGLE;
  glutInitDisplayMode(type);
  glutInitWindowSize(300, 300);
  glutCreateWindow("Fog Test");

  glFrontFace(GL_CW);

  glEnable(GL_DEPTH_TEST);

  glLightfv(GL_LIGHT0, GL_AMBIENT, ambient);
  glLightfv(GL_LIGHT0, GL_DIFFUSE, diffuse);
  glLightfv(GL_LIGHT0, GL_POSITION, position);
  glLightModelfv(GL_LIGHT_MODEL_AMBIENT, lmodel_ambient);
  glLightModeli(GL_LIGHT_MODEL_TWO_SIDE, GL_TRUE);
  glEnable(GL_LIGHTING);
  glEnable(GL_LIGHT0);

  glMaterialfv(GL_FRONT, GL_SHININESS, front_mat_shininess);
  glMaterialfv(GL_FRONT, GL_SPECULAR, front_mat_specular);
  glMaterialfv(GL_FRONT, GL_DIFFUSE, front_mat_diffuse);
  glMaterialfv(GL_BACK, GL_SHININESS, back_mat_shininess);
  glMaterialfv(GL_BACK, GL_SPECULAR, back_mat_specular);
  glMaterialfv(GL_BACK, GL_DIFFUSE, back_mat_diffuse);

  glEnable(GL_FOG);
  glFogi(GL_FOG_MODE, GL_EXP);
  glFogf(GL_FOG_DENSITY, fogDensity);
  glFogfv(GL_FOG_COLOR, fog_color);
  glClearColor(0.8, 0.8, 0.8, 1.0);
  /* *INDENT-OFF* */
  glNewList(cubeList, GL_COMPILE);
    glBegin(GL_TRIANGLE_STRIP);
      glNormal3fv(scp[0]);
      glVertex3fv(scp[0]);
      glNormal3fv(scp[0]);
      glVertex3fv(scp[1]);
      glNormal3fv(scp[2]);
      glVertex3fv(scp[2]);
      glNormal3fv(scp[2]);
      glVertex3fv(scp[3]);
      glNormal3fv(scp[4]);
      glVertex3fv(scp[4]);
      glNormal3fv(scp[4]);
      glVertex3fv(scp[5]);
      glNormal3fv(scp[6]);
      glVertex3fv(scp[6]);
      glNormal3fv(scp[6]);
      glVertex3fv(scp[7]);
      glNormal3fv(scp[8]);
      glVertex3fv(scp[8]);
      glNormal3fv(scp[8]);
      glVertex3fv(scp[9]);
      glNormal3fv(scp[10]);
      glVertex3fv(scp[10]);
      glNormal3fv(scp[10]);
      glVertex3fv(scp[11]);
      glNormal3fv(scp[12]);
      glVertex3fv(scp[12]);
      glNormal3fv(scp[12]);
      glVertex3fv(scp[13]);
      glNormal3fv(scp[14]);
      glVertex3fv(scp[14]);
      glNormal3fv(scp[14]);
      glVertex3fv(scp[15]);
      glNormal3fv(scp[16]);
      glVertex3fv(scp[16]);
      glNormal3fv(scp[16]);
      glVertex3fv(scp[17]);
    glEnd();
  glEndList();
  /* *INDENT-ON* */

  glMatrixMode(GL_PROJECTION);
  glLoadIdentity();
  gluPerspective(45.0, 1.0, 1.0, 200.0);
  glMatrixMode(GL_MODELVIEW);

  glutKeyboardFunc(Key);
  glutSpecialFunc(SpecialKey);
  glutDisplayFunc(Draw);
  glutMainLoop();
  return 0;             /* ANSI C requires main to return int. */
}

**Comment by bgilbert** [comment]
Could you post the output of `cat /etc/os-release`?

**Comment by blackshadow2002** [comment]
> Could you post the output of `cat /etc/os-release`?

![Screenshot from 2023-04-28 21-02-43](https://user-images.githubusercontent.com/93479936/235190825-55805a1d-f51a-4e1f-88b6-a98347b801fc.png)

**Comment by blackshadow2002** [comment]
If i have posted this issue in wrong place, please let me know where to report this issue....

**Comment by blackshadow2002** [comment]
> Could you post the output of `cat /etc/os-release`?

If i have posted this issue in wrong place, please let me know where to report this issue....

**Comment by travier** [comment]
This is the issue tracker for Fedora **CoreOS**. As you are writing your own program here, I'd recommend starting with the Fedora discussion forums to get help: https://discussion.fedoraproject.org/
