### ISSUE TITLE
Error: System has 0 devices with a filesystem labeled 'boot'

### ISSUE THREAD

**Issue by abhinavdahiya** [coreos/fedora-coreos-tracker#1483]
### Describe the bug

AMI: fedora-coreos-37.20230401.3.0-x86_64

AWS instance failing to boot with following error : 

```
Displaying logs from failed units: coreos-ignition-unique-boot.service
May 01 21:15:40 systemd[1]: Starting coreos-ignition-unique-boot.service - CoreOS Ensure Unique Boot Filesystem...
May 01 21:15:40 rdcore[1511]: Error: System has 0 devices with a filesystem labeled 'boot': []
May 01 21:15:40 systemd[1]: [0;1;39m[0;1;31m[0;1;39mcoreos-ignition-unique-boot.service: Main process exited, code=exited, status=1/FAILURE[0m
May 01 21:15:40 systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mcoreos-ignition-unique-boot.service: Failed with result 'exit-code'.[0m
May 01 21:15:40 systemd[1]: [0;1;31m[0;1;39m[0;1;31mFailed to start coreos-ignition-unique-boot.service - CoreOS Ensure Unique Boot Filesystem.[0m
May 01 21:15:40 systemd[1]: coreos-ignition-unique-boot.service: Triggering OnFailure= dependencies.

```

This happens on some instances and not all the time.

### Reproduction steps

This is not exactly reproducible as it happens only sometimes

### Expected behavior

Expect the ignition to complete and AWS instance to boot

### Actual behavior

AWS instance is failing to boot

### System details

AWS

did not get `rpm-ostree status -b` as the instance is failing to boot on AWS.

**Comment by tomwans** [comment]
We have seen this on both c5.xlarge (amd64) and c6g.16xlarge (aarch64) instance types

**Comment by bgilbert** [comment]
Please obtain the full console log from the EC2 console or API and post it here.  Is there anything unusual about your instance configuration?  (For example, multiple disks.)

**Comment by tomwans** [comment]
@bgilbert Thanks - here is a sample of a full log we were able to obtain: https://gist.github.com/tomwans/5d89b652eaefe9e2772707d5f5ef8c21

We do use multiple disks in this case.

**Comment by bgilbert** [comment]
@tomwans Thanks.  In that log, you're booting from `/dev/nvme2n1`, but your Ignition config wipes that disk and repartitions it as a single RAID component.  And of course, once you do that, you don't have an operating system anymore.  Note that the Linux kernel does not guarantee that a storage device will be assigned the same name on every boot.  When specifying partitioning for multiple disks, you should use the stable device aliases in `/dev/disk` instead of the kernel's device names.

**Comment by tomwans** [comment]
@bgilbert thanks. Any idea why this might be intermittent, given the same disk layout and instance type in AWS? And why might we be seeing this only in this most recent version of CoreOS? 

We haven't changed the Ignition disk configuration in a very long time, so not sure why this would be coming up now.

**Comment by dustymabe** [comment]
> @bgilbert thanks. Any idea why this might be intermittent, given the same disk layout and instance type in AWS? 


If it's a race condition that could explain why the behavior may not be consistent.

And why might we be seeing this only in this most recent version of CoreOS?
 
Maybe newer kernels trigger the race condition more often?

**Comment by bgilbert** [comment]
Yup, that's the problem.  It's not safe for the config to assume that the boot disk is `nvme0n1` and the data disks are `nvme1n1` and up.
