### ISSUE TITLE
Uploading to cloud platforms: AWS

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#149]
This is part of https://github.com/coreos/fedora-coreos-tracker/issues/146 and tracks the work/discussion around uploading to AWS.

**Comment by bgilbert** [comment]
I think this involves the following:
- [ ] Identify the target AWS account.  The account number will be an implicit part of our ABI, so we should expect to use the account for the long term.
- [ ] Update plume for FCOS.
- [ ] Inquire about including FCOS in AWS CI.

If we want to publish to AWS Marketplace:
- [ ] Register with Marketplace and create a product.
- [ ] Set up automation for Marketplace updates.  CL uses a Greasemonkey userscript for this :disappointed:

**Comment by bgilbert** [comment]
Container Linux is also published to AWS GovCloud and AWS China.  This is non-trivial to arrange, and since Fedora CoreOS will not have commercial support, it may not be possible in both cases.  We should decide whether to pursue it for Fedora CoreOS.

**Comment by bgilbert** [comment]
- The current plan is to publish AMIs into a Fedora-controlled account.
- We currently don't plan to pursue GovCloud.
- AWS China is still undecided but not an initial priority.
- It'd be nice to publish to Marketplace, for the Marketplace product page if nothing else, but we won't block on it.

**Comment by ryanvade** [comment]
What would be required to support GovCloud? Would there be interest in a third party assisting with GovCloud?

**Comment by bgilbert** [comment]
@ryanvade There are no significant technical barriers to uploading to GovCloud; it's a matter of making GovCloud a priority and arranging the appropriate access.  At present we're not planning to pursue that, but we'll update this ticket if that changes.

**Comment by bgilbert** [comment]
`ap-east-1`, `me-south-1`, and all future AWS regions are disabled by default and require an explicit opt-in at the AWS account level.  I filed an [Infra ticket](https://pagure.io/fedora-infrastructure/issue/8299) to discuss enablement of these regions.

**Comment by bgilbert** [comment]
We're opted-in to currently existing regions.  https://github.com/coreos/fedora-coreos-pipeline/issues/152 proposes automation for detecting new regions.

---

The Marketplace [seller requirements](https://docs.aws.amazon.com/marketplace/latest/userguide/user-guide-for-sellers.html#seller-requirements-for-publishing-free-products) include:

> - Sell publicly available, full-feature production-ready software
> - Have a defined customer support process and support organization

So it appears that AWS Marketplace publishing isn't feasible for Fedora CoreOS.

**Comment by cgwalters** [comment]
> So it appears that AWS Marketplace publishing isn't feasible for Fedora CoreOS.

There was discussion around that here at devconf again - let me see if I can get the right people in this thread.

**Comment by cgwalters** [comment]
Consensus seems to be leaning against Marketplace.

**Comment by ryanvade** [comment]
Just want to leave a note that because Fedora CoreOS is not available in Govcloud means that I can't migrate our Kubernetes cluster which was made with https://github.com/kubernetes-incubator/kube-aws away from CoreOS once it stops receiving security updates.  Hopefully AWS pushes EKS to Govcloud soon but until then I'll be in a tight spot.

**Comment by dustymabe** [comment]
hey @ryanvade - IIUC you can upload your own images to Govcloud. The images we upload are downloadable on the "For Cloud Operators" tab of https://getfedora.org/en/coreos/download/ . So for the latest release that would be: 

- [fedora-coreos-31.20200118.3.0-aws.x86_64.vmdk.xz](https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200118.3.0/x86_64/fedora-coreos-31.20200118.3.0-aws.x86_64.vmdk.xz)
- [fedora-coreos-31.20200118.3.0-aws.x86_64.vmdk.xz.sig](https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200118.3.0/x86_64/fedora-coreos-31.20200118.3.0-aws.x86_64.vmdk.xz.sig)

**Comment by dustymabe** [comment]
Also - when importing you may find this information useful: https://github.com/openshift/os/blob/master/FAQ.md#q-how-do-i-get-rhcos-in-a-private-ec2-region

**Comment by LorbusChris** [comment]
Since we do publish images to AWS now, should we close this issue?

**Comment by bgilbert** [comment]
I've now opened https://github.com/coreos/fedora-coreos-tracker/issues/381 to track adding FCOS to AWS internal CI.  https://github.com/coreos/fedora-coreos-pipeline/issues/152 already tracks detecting new AWS regions.  We're not currently planning to pursue Marketplace, GovCloud, or AWS China.  I think those are all the pieces of this ticket; closing.
