### ISSUE TITLE
kola: rawhide, testing-devel tests failing in azure. Requesting new Afterburn release.

### ISSUE THREAD

**Issue by marmijo** [coreos/fedora-coreos-tracker#1492]
All `kola-azure` tests are failing in testing-devel and rawhide. Afterburn was upgraded in both streams and is using a newer version of openssl. We should release a new version of afterburn to support the new changes in the latest version of openssl.

Both `rawhide` and `testing-devel` recently saw afterburn upgraded:

- rawhide: afterburn 5.4.0-2.fc39.x86_64 → 5.4.0-3.fc39.x86_64
- testing-devel: afterburn 5.4.0-2.fc38.x86_64 → 5.4.0-3.fc38.x86_64

Kola tests run with this following command are failing.
```
cosa kola run --rerun --allow-rerun-success=tags=needs-internet 
```

The error that is returned from kola is:

```
[2023-05-09T09:02:10.725Z] 2023-05-09T09:02:09Z platform: some systemd units failed: [afterburn-sshkeys@core.service]
harness.go:1680: mach.Start() failed: machine "kola-23b9a780-88900f60eb" failed basic checks: detected failed or stuck systemd units
```

Looking into the logs for one of the failed tests shows:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/share/cargo/registry/openssl-0.10.52/src/pkcs12.rs:42:31
...
May  9 09:00:44.980843 systemd[1]: afterburn-sshkeys@core.service: Main process exited, code=exited, status=101/n/a
May  9 09:00:44.981055 systemd[1]: afterburn-sshkeys@core.service: Failed with result 'exit-code'.
May  9 09:00:44.986682 systemd[1]: Failed to start afterburn-sshkeys@core.service - Afterburn (SSH Keys).
May  9 09:00:44.996733 systemd[1]: Dependency failed for afterburn-sshkeys.target - Synchronize afterburn-sshkeys@.service template instances.
May  9 09:00:45.002815 systemd[1]: Dependency failed for multi-user.target - Multi-User System.
May  9 09:00:45.007000 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=afterburn-sshkeys@core comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
May  9 09:00:45.008828 systemd[1]: multi-user.target: Job multi-user.target/start failed with result 'dependency'.
May  9 09:00:45.008856 systemd[1]: afterburn-sshkeys.target: Job afterburn-sshkeys.target/start failed with result 'dependency'.
```

The error shows the issue originating from line 42 in `openssl-0.10.52/src/pkcs12.rs` [which is here](https://github.com/sfackler/rust-openssl/blob/5d2c40560f64a58fdd742881dd7fc8775146b998/openssl/src/pkcs12.rs#L42). The `parse()` method has been deprecated and [afterburn was updated](https://github.com/coreos/afterburn/commit/e4757c9750cc03cbba1c52ccb79e4e139433e388) to reflect that, but these changes haven't made it into a release of Afterburn yet.

We should perform a new release of afterburn to support these changes to openssl.

Here's a journal and console log from one of the failed tests:

[basic_console.txt](https://github.com/coreos/fedora-coreos-tracker/files/11443447/basic_console.txt)
[basic_journal.txt](https://github.com/coreos/fedora-coreos-tracker/files/11443449/basic_journal.txt)

**Comment by marmijo** [comment]
For completeness, the Afterburn change log shows updates to openssl
```
* Wed May 03 2023 Fabio Valentini <decathorpe@gmail.com> - 5.4.0-3
  - Rebuild for tokio, h2, and openssl crate security updates
```

**Comment by bgilbert** [comment]
Good find!  When `rust-openssl` deprecated `parse()`, it replaced it with a compatibility wrapper around `parse2()`.  The wrapper does an `unwrap()` on the `pkey` field, causing a panic if that field doesn't exist.  But in this case we're not parsing a normal SSL certificate, we're parsing the special-purpose X.509 certificates produced by Azure's infrastructure, which don't have a `pkey`.  Afterburn [switched](https://github.com/coreos/afterburn/commit/e4757c9750cc03cbba1c52ccb79e4e139433e388) to `parse2()` but that change hasn't made it to a release yet.

Afterburn release ticket in https://github.com/coreos/afterburn/issues/921.

**Comment by dustymabe** [comment]
The new `afterburn` 5.4.2 release should resolve this. Fast tracked in:

- https://github.com/coreos/fedora-coreos-config/pull/2429
- https://github.com/coreos/fedora-coreos-config/pull/2431
