### ISSUE TITLE
F38 Change: SPDX License Phase 2

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1497]
For the [proposed Fedora 39 changes](https://github.com/coreos/fedora-coreos-tracker/issues/1491) we decided to discuss further the following change:

- [SPDX License Phase 2](https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_2)
     - Second phase of transition from using Fedora's short names for licenses to SPDX identifiers in the License: field of Fedora package spec files. This phase addresses how to update the License: field for existing packages, including documenting more specific guidance on how to find licenses in a package.
     - Tracking bug: [#2184184](https://bugzilla.redhat.com/show_bug.cgi?id=2184184)
     - NOTE: [travier] We need to ensure our packages are compliant

Offhand our list of packages are:

- [x] ostree
- [x] rpm-ostree
- [x] ignition
- [x] butane
- [x] rust-afterburn
- [x] rust-coreos-installer
- [x] rust-ignition-config
- [x] rust-openssh-keys
- [x] rust-ssh-key-dir
- [x] rust-zincati
- [x] rust-bootupd
- [x] console-login-helper-messages

**Comment by jmarrero** [comment]
@dustymabe sure thing, will take `ostree` and `rpm-ostree`

**Comment by prestist** [comment]
@dustymabe, yeah I will take Ignition

**Comment by dustymabe** [comment]
[console-login-helper-messages-0.21.3-5.fc39](https://koji.fedoraproject.org/koji/buildinfo?buildID=2208230) has the updated license.

**Comment by jmarrero** [comment]
[ostree-2023.3-4.fc39
](https://koji.fedoraproject.org/koji/taskinfo?taskID=102115603)&
[rpm-ostree-2023.4-5.fc39](https://koji.fedoraproject.org/koji/taskinfo?taskID=102115602) 
have been updated with the SPDX license identifiers.

**Comment by dustymabe** [comment]
Nice - thanks!

**Comment by travier** [comment]
We missed `nss-altfiles` which I'm doing in https://src.fedoraproject.org/rpms/nss-altfiles/pull-request/6
