### ISSUE TITLE
Kernel Module Support

### ISSUE THREAD

**Issue by jdoss** [coreos/fedora-coreos-tracker#15]
This issue is a continuation of this [conversation](https://pagure.io/atomic-wg/issue/493) which details out some of the pain points of not having an official method for supporting kernel modules. On Fedora Atomic Host, and CoreOS CL you can work around not having kernel module support by building the modules in a [container](http://www.projectatomic.io/blog/2018/06/building-kernel-modules-with-podman/) but it doesn't easily solve the problem of having the kernel modules built on boot and it is a pretty fragile method for building kernel modules consistently. Also, @cgwalters had some feedback on this topic detailed out [here](https://github.com/jdoss/atomic-wireguard/issues/1) that might be relevant to this design topic. 

Having some sort of support for a [DKMS-like](https://github.com/dell/dkms) kernel module build system in Fedora CoreOS would be great.

**Comment by lucab** [comment]
For reference, on ContainerLinux side some users started exploring this: https://github.com/coreos/torcx/issues/93. The current idea would be to let third-party providers build kernel modules out-of-band for each release and provide them to the nodes at first boot and update time.

I don't think we ever planned to support DKMS directly on the host. At the same time I don't think we have any strong preference for in-container build systems, so DKMS would be just fine there. Our current documented approach is https://coreos.com/os/docs/latest/kernel-modules.html, but there are some more advanced variations like https://github.com/squat/modulus (k8s-based).

**Comment by jlebon** [comment]
I think the general issue here will be fixed by the bootable containers initiative.
See e.g. https://github.com/coreos/layering-examples/blob/main/build-zfs-module/Containerfile.
