### ISSUE TITLE
Updates to AWS EC2 AMI defaults 

### ISSUE THREAD

**Issue by prestist** [coreos/fedora-coreos-tracker#1502]
### Describe the enhancement

With the upcoming development on F39, we should make a few changes in bulk as there is a overhead overlap between the following changes.

-  Update our AWS AMIs with the IMDSv2-only flag
    - Since IMDSv1 is not part of this consideration, there is some potential application breakage. We need to be sure to announce this change in the f39 rebase and opening of `next`
-  Default EC2 AMI's to the `gp3 EBS` volume type
    - The gp3 volume type has a lower minimum IOP [rating](https://aws.amazon.com/blogs/storage/migrate-your-amazon-ebs-volumes-from-gp2-to-gp3-and-save-up-to-20-on-costs/) for volumes smaller than 3TB. We should include it in the release notes to inform the enduser of the default change.
-   Switch AMIs to uefi-preferred
    - Existing Draft [PR](https://github.com/coreos/coreos-assembler/pull/3402)

### System details

F39

### Additional information

These were discussed in the FCOS community meeting [5/31/23](https://meetbot-raw.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2023-05-31-16.30.log.txt)

xref: 
- https://github.com/coreos/fedora-coreos-tracker/issues/1491

**Comment by bgilbert** [comment]
> Since the gp3 volume type has a higher minimum IOP rating ([3000](https://aws.amazon.com/blogs/storage/migrate-your-amazon-ebs-volumes-from-gp2-to-gp3-and-save-up-to-20-on-costs/)) we should include it in the release notes

The concern is that it has a _lower_ minimum IOPS for volumes > 3 TB, and a minimum throughput that ranges from "slightly lower" to "half as much" depending on the volume size.

**Comment by quentin9696** [comment]
@bgilbert At my job, we already use gp3 with default IOPS option on FCOS in production and we don't have any complains about using gp3

**Comment by bgilbert** [comment]
@quentin9696 My point wasn't that we shouldn't switch, just that we need to announce that we're doing so.

**Comment by quentin9696** [comment]
@bgilbert this can also reassure people who are using it with the current disk

**Comment by dustymabe** [comment]
Some docs for the IMDSV2 changes:

- [AWS Overview](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)
- [Example accessing via curl](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html)
- [Example change in one of our FCOS tests](https://github.com/coreos/fedora-coreos-config/pull/2614)

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `39.20230916.1.1`. Please try out the new release and report issues.

**Comment by travier** [comment]
See: https://github.com/coreos/fedora-coreos-tracker/issues/1491#issuecomment-1766038929

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `39.20231101.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `39.20231101.3.0`.
