### ISSUE TITLE
selinux denies `machinectl import-fs` executing systemd-importd

### ISSUE THREAD

**Issue by wuxxin** [coreos/fedora-coreos-tracker#1514]
### Platform
+ Fedora Coreos Stable (38)

### Reproduction

- (**Works**) make a os filesystem with mkosi
```bash
rpm-ostree install --assumeyes --idempotent --allow-inactive mkosi apt
mkdir -p /etc/mkosi/debian-bookworm /var/lib/mkosi /var/cache/mkosi
printf "[Distribution]\nDistribution=debian\nRelease=bookworm\n[Output]Format=directory
[Packages]\n[Host]\n[Validation]" > /etc/mkosi/debian-bookworm/mkosi.conf
printf "[Exec]\nBoot=on\nLinkJournal=try-guest\n[Files][Network]
Private=on\nVirtualEthernet=on\n" > /etc/mkosi/debian-bookworm/mkosi.nspawn
mkosi -C /etc/mkosi/debian-bookworm -O /var/lib/mkosi --cache=/var/cache/mkosi build
mv /var/lib/mkosi/debian~bookworm /var/lib/mkosi/debian-bookworm
```
- (**Does Not Work**) import filesystem for nspawn with machinectl
```bash
machinectl import-fs /var/lib/mkosi/debian-bookworm hello-nspawn
```

If this is not the right repo for this issue, feel free to close/ignore this issue,
and point me to a more fitting one.

Related binaries:
```
-rwxr-xr-x. 4 root root system_u:object_r:systemd_importd_exec_t:s0 49824
     Jan  1  1970 /usr/lib/systemd/systemd-importd
-rwxr-xr-x. 4 root root system_u:object_r:init_exec_t:s0 33128 Jan  1  1970
    /usr/lib/systemd/systemd-import-fs
```

Relevant Log Output (formatted for better readability)
```log
audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 
    subj=system_u:system_r:init_t:s0 msg='unit=systemd-importd comm="systemd" 
    exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
audit: type=1130 audit(1687265080.304:465): pid=1 uid=0 auid=4294967295 ses=4294967295
    subj=system_u:system_r:init_t:s0 msg='unit=systemd-importd comm="systemd" 
    exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
audit[5023]: AVC avc:  denied  { execute } for  pid=5023 comm="(sd-transfer)" 
    name="systemd-import-fs" dev="dm-0" ino=14841116 
    scontext=system_u:system_r:systemd_importd_t:s0 
    tcontext=system_u:object_r:init_exec_t:s0 tclass=file permissive=0
audit[5023]: SYSCALL arch=c000003e syscall=59 success=no exit=-13 a0=5639dc5a36e8
    a1=7ffd102d2350 a2=5639dd7a91f0 a3=7ff68bdf8810 items=0 ppid=5022 pid=5023
    auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0
    tty=(none) ses=4294967295 comm="(sd-transfer)" exe="/usr/lib/systemd/systemd-importd"
    subj=system_u:system_r:systemd_importd_t:s0 key=(null)
audit: PROCTITLE proctitle="(sd-transfer)"
    (sd-transfer)[5023]: Failed to execute /usr/lib/systemd/systemd-import-fs 
    tool: Permission denied
```

**Comment by dustymabe** [comment]
Hmm so you are trying to layer in `mkosi` on top of Fedora CoreOS (which version specifically are you using?) and then trying to `machinectl import-fs` the created image?

I'm guessing the right place to file an issue would be an [SELinux Bugzilla](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=selinux-policy&list_id=13247928&product=Fedora).

**Comment by wuxxin** [comment]
### which version specifically are you using ?
   for development, i use x86_64 qemu qcow2.xz. with libvirt

### why ?
The idea was after a learning project, to learn pulumi (a terraform clone), and give Fedora-CoreOS a try, i implemented quadlet systemd container as base units.See https://github.com/wuxxin/infra-shared

That worked pretty well, then i thought, for some legacy compose applications, it would be nice to support compose stack too.

After that i thought it would be nice to support some legacy virtual machines, that are already automated install and self updating, 

#### so i tought nspawn would be a good fit for coreos because:

- its a very thin layer, does only a few things, and is architecture wise similar to lxc
- since it inception it learned to automatically faccilitate the USER Namespace, and has become a good enough isolation layer 
- its same kernel, which means, zero overhead, same caching layer, lots of mount options, file watch and everything else just works
- its feature wise similar to libvirt+ libvirt-lxc but without a ton of arcane XML configs, and a huge daemon in the background, and not retrofitted to lxc
- its ubiquitous and already installed on every linux os running under systemd
- it fits nicely with other systemd parts (networkd, resolvd), and its minimal scope looks like a match for coreos
- i already use nspawn for development container-machines, where i find it very useful

### the selinux error:
i just make a flat directory of a filesystem just like any container with mkosi, because its legacy free, doesnt use root.
for now as a workaround i simply https://github.com/wuxxin/infra-shared/blob/main/fcos/nspawn-provision%40.service#L26 copy the file tree to /var/lib/machines and start the machine using systemd-nspawn. 

all works fine, but when i try to use `machinectl import-fs` for copying the directory tree, it breaks, because machinectl spawns /usr/lib/systemd/systemd-importd which get denied by selinux. 

because coreos uses selinux in enforcing mode, this breaks import-fs in a non obvious way, and is probably wrong, and probably overlooked by selinux policy writers, that machinectl spawns systemd-import-fs.

**Comment by wuxxin** [comment]
opened an issue upstream: https://bugzilla.redhat.com/show_bug.cgi?id=2219398
thanks for pointing out the fitting place,closing this.
