### ISSUE TITLE
sysusers: remove `bin` entries and get `systemd.post: /etc/gshadow: Group "bin" already exists.`

### ISSUE THREAD

**Issue by HuijingHei** [coreos/fedora-coreos-tracker#1525]
Refer to https://github.com/coreos/rpm-ostree/issues/49#issuecomment-1612626563, do testing with `bin`:

1. Remove `bin` line in `group` and `passwd` (refer to https://github.com/coreos/fedora-coreos-config/tree/testing-devel/manifests)
2. Build FCOS, see logs:
```
...
systemd.post: Creating group 'bin' with GID 1.
systemd.post: Creating user 'bin' (bin) with UID 1 and GID 1.
systemd.post: /etc/gshadow: Group "bin" already exists.
...
```

According to @cgwalters 's pointer, the above log will lead `systemd-sysusers` (during `systemd.post`) exit early before saving the updated `/etc/{passwd,group}` refer to [code](https://github.com/systemd/systemd/blob/main/src/sysusers/sysusers.c#L820), and `bin` user/group will not be saved finally.

The root cause is the `gshadow` is not consistent with `group`, `gshadow` is from [setup](https://pagure.io/setup/blob/master/f/shadowconvert.sh), and we override `group` according to [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/group). And @cgwalters is correct, do testing with `override/rootfs/etc/gshadow`(from [setup](https://koji.fedoraproject.org/koji/buildinfo?buildID=2133230) package) which removs the `bin` line, rebuild FCOS no such logs and verify `bin` user / group saved in `/usr/lib/{passwd,group}` after boot the disk.

To fix this, we should make sure `gshadow` is consistent with `group` before layering, like regenerating `gshadow` according to `group`.

**Comment by cgwalters** [comment]
Right.  I think we can do this automatically in rpm-ostree.

BTW though, this issue also relates a bit to https://github.com/coreos/rpm-ostree/issues/4401 - I wonder if it would work for us to just empty out (or possibly even remove) the shadow files instead of regenerating them?

**Comment by cgwalters** [comment]
So I'd probably say we should transfer this issue to rpm-ostree.  This problem domain also applies to other systems using it (IoT, desktops, etc.)

**Comment by HuijingHei** [comment]
> I wonder if it would work for us to just empty out (or possibly even remove) the shadow files instead of regenerating them?

I tried with append `src/config/manifests/fedora-coreos-base.yaml` under `remove-from-packages:`, and build fcos, no error about `/etc/gshadow: Group "bin" already exists.`
```
  - [setup, /etc/shadow,
            /etc/gshadow]
```
And check shadow files have mode `0000`, seems they do not include all the `group/user`, not sure there is any concern.
```
[root@cosa-devsh ~]# ls -l /etc/*shadow*
----------. 1 root root 100 Jul 13 02:24 /etc/gshadow
----------. 1 root root  91 Jul 13 02:23 /etc/gshadow-
----------. 1 root root 107 Jul 13 02:24 /etc/shadow
----------. 1 root root  81 Jul 13 02:23 /etc/shadow-
```

**Comment by HuijingHei** [comment]
> I wonder if it would work for us to just empty out (or possibly even remove) the shadow files instead of regenerating them?

Test with empty shadow files:
Create empty file `override/rootfs/etc/{,g}shadow` and build fcos, no error logs.
Boot VM, check shadow files have same mode with override, and include the package prein groups.
Same with remove shadow files, they do not include all the `group/user`.
