### ISSUE TITLE
Including fedora specific behavior

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/fedora-coreos-tracker#153]
### Background

Some fedora packages contain fedora specific behavior that isn't carried upstream. This is frequently for legacy support (like the helper in `nfs-utils`) or to provide helpers for more easily adding arguments to daemons. Some packages are themselves are entirely fedora specific (like authconfig) and designed to abstract other upstream projects configuration. These abstractions are useful in some places but may not fit well in FCOS. Usually these changes involve config files in `/etc/sysconfig`. Currently [this](https://gist.github.com/ajeddeloh/453847d4eec0ed0955aad278d4b1f44a) is a list of things included in `/etc/sysconfig`.

Container Linux generally does not try to abstract the configuration of its components or provide other helpers. To a large degree we rely on users configuring each component separately via Ignition. We mostly rely on upstream documentation for components. The Container Linux Config Transpiler does some degree of automating common cases (e.g. providing sugar for `etcd`) but does so by generating an Ignition config that writes out the necessary configs.

### In the general case, to what degree do we want fedora specific behavior? To what degree is FCOS "fedora-like"?

Independent of the actions we would need to take to achieve this, how much should we include helper files that are not included in the upstream projects? This impacts both how much FCOS diverges from fedora proper and what configuration we support in the distro.

### If we do want to remove fedora specific bits, what degree of effort do we want to expend removing them?

If the answer to the above question is that we'd prefer to not carry some/all of the fedora specific bits, what actions if any should we take to remove them? We could:
 - Do nothing
 - Do nothing but tell users not to use them
 - Remove some/all packages that are just fedora specific
 - Split some/all packages like we're doing with python
 - Strip files with rpm-ostree during the compose from some/all packages with fedora specific bits

**Comment by dustymabe** [comment]
@bgilbert do you feel there is anything actionable for us to do on this ticket? Should we bring it up in a meeting?

**Comment by bgilbert** [comment]
I feel like we've answered this implicitly.  With some specific exceptions, we seem to be staying pretty close to the rest of Fedora.  To do otherwise would require a lot of ongoing work, and I think the current focus of FCOS is more on refining the deployment model and associated tools.

So I'd be in favor of closing.  Thoughts?

**Comment by dustymabe** [comment]
+1 from me - we definitely have to consider the maintenance cost of such decisions and we need to make sure we're set up for success over time. Closing this for now.
