### ISSUE TITLE
rawhide: ext.config.networking.default-network-behavior-change test failing with glib2-2.77.0-2.fc39 update 

### ISSUE THREAD

**Issue by aaradhak** [coreos/fedora-coreos-tracker#1530]
### Describe the bug

The kola test `ext.config.networking.default-network-behavior-change` is  failing on the latest rawhide x86_64 since build [39.20230716.91.0](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/1551/)

```
--- FAIL: ext.config.networking.default-network-behavior-change (25.95s)
[2023-07-18T13:04:51.163Z] cluster.go:162: Error: Unit kola-runext-41.service exited with code 1
[2023-07-18T13:04:51.163Z] cluster.go:162: 2023-07-18T13:04:47Z cli: Unit kola-runext-41.service exited with code 1
[2023-07-18T13:04:51.163Z] harness.go:1191: kolet failed: : kolet run-test-unit failed: Process exited with status 1
[2023-07-18T13:04:51.163Z] FAIL, output in /home/jenkins/agent/workspace/build/tmp/kola-Nbjtc/kola/rerun
[2023-07-18T13:04:51.163Z] Error: harness: test suite failed
[2023-07-18T13:04:51.163Z] 2023-07-18T13:04:50Z cli: harness: test suite failed
[2023-07-18T13:04:51.163Z] error: failed to execute cmd-kola: exit status 1
script returned exit code 1
```
Looks like the test began to fail after the glib2 version upgrade from glib2 2.76.4-1.fc39 -> 2.77.0-2.fc39

The test failure is trying to say there was one less newline in the diff where there shouldn't have been:
```
--- /dev/fd/63        2023-07-18 13:04:46.300701210 +0000
+++ /dev/fd/62        2023-07-18 13:04:46.298701210 +0000
@@ -1,5 +1,4 @@$                                         
 # Created by nm-initrd-generator$                       
-$                                                       
 [connection]$                                           
 id=Wired Connection$                                    
 uuid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx$             
``` 

It seems to come from this [code](https://github.com/coreos/fedora-coreos-config/blob/c7e35d0e66792560f55e1c299c25fa182bbb3171/tests/kola/networking/default-network-behavior-change/test.sh#L211-L227)

### Reproduction steps

1) build and run latest FCOS rawhide [image](https://builds.coreos.fedoraproject.org/browser?stream=rawhide&arch=x86_64)
2) Run kola test - `ext.config.networking.default-network-behavior-change`
3) `ext.config.networking.default-network-behavior-change` test fails

### Expected behavior

kola  `ext.config.networking.default-network-behavior-change` test to pass with upgraded **`glib2-2.77.0-2.fc39`**

### Actual behavior

kola  `ext.config.networking.default-network-behavior-change` test fails with pkg upgrade  **`glib2-2.77.0-2.fc39`**

### System details

Fedora CoreOS latest x86_64 [Rawhide](https://builds.coreos.fedoraproject.org/browser?stream=rawhide&arch=x86_64) Version

**Comment by dustymabe** [comment]
so with `glib2-2.77.0-2.fc39` there is a missing blank line (missing newline) in a file generated by NetworkManager as opposed to when `glib2-2.76.4-1.fc39` is installed. Obviously whitespace change here isn't a material change in behavior (it's cosmetic), but I worry that the underlying change is actually a bug that will cause problems in other places.

@thom311 @matthiasclasen would you know what would be causing the change in behavior?

**Comment by cgwalters** [comment]
Just knowing that these are GKeyFiles, I navigated to the git history of the source and https://gitlab.gnome.org/GNOME/glib/-/commit/86b4b0453ea3a814167d4a5f7a4031d467543716 jumps out as recent.

I am not sure our testing for the bit-for-bit identical output is really sustainable though.  Perhaps nowadays we can serialize and compare the nmstate?

**Comment by dustymabe** [comment]
> Just knowing that these are GKeyFiles, I navigated to the git history of the source and https://gitlab.gnome.org/GNOME/glib/-/commit/86b4b0453ea3a814167d4a5f7a4031d467543716 jumps out as recent.

👍. I wasn't sure if the change was intentional or not, but looks like it was.

> 
> I am not sure our testing for the bit-for-bit identical output is really sustainable though. Perhaps nowadays we can serialize and compare the nmstate?

We already have a [function](https://github.com/coreos/fedora-coreos-config/blob/c7e35d0e66792560f55e1c299c25fa182bbb3171/tests/kola/networking/default-network-behavior-change/test.sh#L172-L177) to normalize the files to remove unique pieces (i.e. like UUID). It should be simple enough to just modify that to remove all blank lines too.

**Comment by dustymabe** [comment]
> > I am not sure our testing for the bit-for-bit identical output is really sustainable though. Perhaps nowadays we can serialize and compare the nmstate?
> 
> We already have a [function](https://github.com/coreos/fedora-coreos-config/blob/c7e35d0e66792560f55e1c299c25fa182bbb3171/tests/kola/networking/default-network-behavior-change/test.sh#L172-L177) to normalize the files to remove unique pieces (i.e. like UUID). It should be simple enough to just modify that to remove all blank lines too.

Fix for this in https://github.com/coreos/fedora-coreos-config/pull/2528

**Comment by dustymabe** [comment]
and this drops the pin: https://github.com/coreos/fedora-coreos-config/pull/2530

**Comment by dustymabe** [comment]
With https://github.com/coreos/fedora-coreos-config/pull/2528 and https://github.com/coreos/fedora-coreos-config/pull/2530 we can close this.
