### ISSUE TITLE
Add a test for `SEV_SNP_CAPABLE` GCP instances

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1531]
### Describe the enhancement

Add a test to make sure that FCOS runs on `SEV_SNP_CAPABLE` instances in GCP.

See: https://github.com/coreos/coreos-assembler/pull/3547

### System details

GCP

**Comment by HuijingHei** [comment]
This is blocked by https://github.com/coreos/coreos-assembler/issues/3556

**Comment by HuijingHei** [comment]
The blocker issue https://github.com/coreos/coreos-assembler/issues/3556 is fixed by https://github.com/coreos/coreos-assembler/pull/3871, also existing test https://github.com/coreos/fedora-coreos-config/commit/0b797dd8eb376addab5884b4f391434027bd37fc, so we are good to close this now.
