### ISSUE TITLE
zincati / ostree not updating system anymore due to update urls no longer valid

### ISSUE THREAD

**Issue by NightWatchman** [coreos/fedora-coreos-tracker#1544]
### Describe the bug

According to my logs it looks like as of August 9th, the URLs that my CoreOS install rely on for updates are no longer available, and the system no longer automatically updates. I never made any changes to the configuration, so I assume these URLs are the ones are the "stock" ones so to speak.

These are the errors I'm getting:
```
Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for https://download.docker.com/linux/rhel/38/x86_64/stable/repodata/repomd.xml
````

Are there updated URLs I should be using now? How are they configured?

### Reproduction steps

Automatic OS updates fail due to missing files from download.docker.com

### Expected behavior

Automatic updates should apply updates if available, or not error if there are no updates available.

### Actual behavior

Automatic updates fail with error message due to 404 responses from download.docker.com

### System details

- Bare metal

```
     Static hostname: xxxx
           Icon name: computer-desktop
             Chassis: desktop 🖥️
          Machine ID: xxxx
             Boot ID: xxxx
    Operating System: Fedora CoreOS 38.20230709.3.0   
         CPE OS Name: cpe:/o:fedoraproject:fedora:38
      OS Support End: Tue 2024-05-14
OS Support Remaining: 9month
              Kernel: Linux 6.3.11-200.fc38.x86_64
        Architecture: x86-64
     Hardware Vendor: Dell Inc.
      Hardware Model: Wyse 5070 Thin Client
    Firmware Version: 1.5.0
```

**Comment by dustymabe** [comment]
>  https://download.docker.com/linux/rhel/38/x86_64/stable/repodata/repomd.xml

It appears you have added a third party yum repository to your system. You'll have to debug that failure further and figure out the root cause.

**Comment by dustymabe** [comment]
@NightWatchman - were you able to figure this out?

I'll close out this issue since the download.docker.com yum repo isn't something added by FCOS.

**Comment by NightWatchman** [comment]
Haven't had the time to look into it more yet, but thanks for the guidance.
