### ISSUE TITLE
New Package Request: tzdata

### ISSUE THREAD

**Issue by yasminvalim** [coreos/fedora-coreos-tracker#1546]
### What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

```
[core@cosa-devsh home]$ sudo rpm-ostree install --dry-run tzdata --allow-inactive
Inactive requests:
  tzdata (already provided by tzdata-2023c-1.fc38.noarch)
Exiting because of '--dry-run' option
```

_TODO: Check it._

### What is the size of the package and its dependencies?

```
Name        : tzdata
Version     : 2023c
Release     : 1.fc38
Architecture: noarch
Install Date: Fri Aug 11 19:19:19 2023
Group       : Unspecified
Size        : 1712794
License     : Public Domain
Signature   : RSA/SHA256, Wed Mar 29 14:54:57 2023, Key ID 809a8d7ceb10b464
Source RPM  : tzdata-2023c-1.fc38.src.rpm
Build Date  : Wed Mar 29 14:49:08 2023
Build Host  : buildhw-x86-14.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://www.iana.org/time-zones
Bug URL     : https://bugz.fedoraproject.org/tzdata
Summary     : Timezone data
Description :
This package contains data files with rules for various timezones around
the world.

```

### What problem are you trying to solve with this package? Or what functionality does the package provide?

The tzdata package contains data files with rules for various time zones around the world.  It is intended to be a fallback for systems that do not have system time zone data installed or don’t have it installed in a standard location.

This change will allow the removal of tzdata. When tzdata is removed, the system will default to UTC. In order to reduce overhead, many container installations now remove the data associated with tzdata but cannot fuly remove the package due to dependencies by other packages. This results in confusion regarding the expected timezone info.

In order for this to work, we need packages that use tzdata at run time to switch from Require'ing tzdata to Recommend'ing tzdata. These packages should also gracefully handle instances where tzdata has been removed. For example, this would require recognizing that tzdata is not present and providing an appropriate error, such as recommending that the user install tzdata.

You can read more about this task and why we are doing this[ here.](https://fedoraproject.org/wiki/Changes/AllowRemovalOfTzdata) 

### Can the software provided by the package be run from a container?  Explain why or why not.

Not sure.

_TODO: Check it._

### Can the tool(s) provided by the package be helpful in debugging container runtime issues?

No.

### Can the tool(s) provided by the package be helpful in debugging networking issues?

No.

### Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

Yes. The package can be installed later if the user needs it.

### In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

Does not apply.

### Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS?

No.

### Does the software provided by the package have a history of CVEs?

No.

**Comment by travier** [comment]
I think this is https://github.com/coreos/fedora-coreos-tracker/issues/1534 ?

I agree that the wording is confusing: The title of the issue is the title of the change in Fedora, not want we want to do in Fedora CoreOS.

In Fedora CoreOS we want to make sure to keep the package: https://github.com/coreos/fedora-coreos-tracker/issues/1534#issuecomment-1662869655

As this package is already in the image, you strictly don't need to go through this process. Adding it to the manifest should be good enough.

**Comment by yasminvalim** [comment]
Should I close this issue and work in the [#1534](https://github.com/coreos/fedora-coreos-tracker/issues/1534) instead?

Thanks!

**Comment by yasminvalim** [comment]
Issue closed. I will be working in this one #1534 since is the same issue.
