### ISSUE TITLE
cifs.upcall denied by SELinux

### ISSUE THREAD

**Issue by MrBrokenHelm** [coreos/fedora-coreos-tracker#1551]
### Describe the bug

After upgrading from Fedora Silverblue 37 to 38 my network shares stopped working, this has been reported by another user in #1447. Which pushed an update to stable, as that issue has been closed (which resolved some of the errors in logs) I am opening a new ticket.

However I see that this has not fixed the complete issue. 

For the shares I use a rather simple fstab:

`//SERVER.domain/company /mnt/company cifs sec=krb5,noauto,users,x-systemd.automount,uid=1000,gid=1000 0 0
//SERVER.domain/software /mnt/software cifs sec=krb5,noauto,users,x-systemd.automount,uid=1000,gid=1000 0 0
//SERVER.domain/users/username /mnt/users cifs sec=krb5,noauto,users,rw,x-systemd.automount,uid=1000,gid=1000 0 0
`

When accessing trying to access the shares, I see the following in the logs:

`type=AVC msg=audit(08/21/2023 12:01:15.028:492) : avc:  denied  { sys_admin } for  pid=18328 comm=cifs.upcall capability=sys_admin  scontext=system_u:system_r:cifs_helper_t:s0 tcontext=system_u:system_r:cifs_helper_t:s0 tclass=capability permissive=0`
`type=AVC msg=audit(08/21/2023 12:01:15.075:493) : avc:  denied  { sys_admin } for  pid=18334 comm=cifs.upcall capability=sys_admin  scontext=system_u:system_r:cifs_helper_t:s0 tcontext=system_u:system_r:cifs_helper_t:s0 tclass=capability permissive=0 
`

Disabling SELinux fixes this part, however I noticed a related issue. So I am adding it to this topic.
When using kinit as a mortal user (e.g. uid 1000) a '/tmp/krb5cc_1000' where autofs is attempting to open '/tmp/krb5cc_0' (root). Resulting in the following failure:
`Aug 21 12:18:38 zoidberg cifs.upcall[19311]: get_existing_cc: default ccache is FILE:/tmp/krb5cc_0
Aug 21 12:18:38 zoidberg cifs.upcall[19311]: get_tgt_time: unable to get principal
`
This can be easily worked around by linking the file, but different behavior to version 37 which handled krb5cc file correctly.

Please note that I still have Fedora 37 (37.20230424.0) pinned, if I use this version with the fstab described above than there a no issues with the shares.

The logs were extracted from Fedora Silverblue 38 (38.20230818.0)

### Reproduction steps

1. Making share you have a valid Kerberos5 ticket, using kinit username
2. Navigate to a share e.g. '/mnt/software'
3. Fails to navigate to '/mnt/software'
4. Systemd unit fails with journal logs indicating SELinux denials
5. Disable SELinux
6. Link the krb5cc_1000 -> krb5cc_0 file
7. Restart var-mnt-*.automount
8. Enable SELinux
9. Navigate to  '/mnt/software'
10. Use the share (as it now works)

### Expected behavior

The automount of the share works without the need of disabling SELinux and linking the krb5cc file.

### Actual behavior

Automount fails due to denial by SELinux:

`type=AVC msg=audit(08/21/2023 12:01:15.028:492) : avc:  denied  { sys_admin } for  pid=18328 comm=cifs.upcall capability=sys_admin  scontext=system_u:system_r:cifs_helper_t:s0 tcontext=system_u:system_r:cifs_helper_t:s0 tclass=capability permissive=0`

cifs.upcall using the wrong krb5cc file, namely 'krb5cc_0' (root) not the using initialised 'krb5cc_1000 file'.

### System details

fedora:fedora/38/x86_64/silverblue
- Version: 38.20230818.0 (2023-08-18T00:44:02Z)
- BaseCommit: 7eac82805d7e6747018e757d78fcfa9ab0dc58a4a6fc2874d77d953daafb02d2
- GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
- LayeredPackages: evolution evolution-ews hunspell-nl krb5-workstation minicom openssl rdesktop wodim

Pinned version 37 Fedora Silverblue (for testing only):
fedora:fedora/37/x86_64/silverblue
- Version: 37.20230424.0 (2023-04-24T01:43:39Z)
- BaseCommit: 3bc1d31482b2c52bdca19416c7b5f14500df7e37197e38dd33ac3274e5289f76
- GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
- LayeredPackages: autofs evolution evolution-ews hunspell-nl krb5-workstation minicom openssl rdesktop wodim

**Comment by dustymabe** [comment]
This issue tracker is for Fedora CoreOS.

Ultimately, though you need to report the issue against [SELinux in Fedora](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&product=Fedora&product=Fedora%20EPEL&component=selinux-policy) and try to get it fixed there.

**Comment by fifofonix** [comment]
This issue seems to be properly resolved in fedora39 `next`.
