### ISSUE TITLE
New Package Request: gvisor-tap-vsock-gvforwarder

### ISSUE THREAD

**Issue by baude** [coreos/fedora-coreos-tracker#1557]
### What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

No additional packages

```
[core@localhost ~]$ sudo rpm-ostree install --dry-run podman-gvproxy
Checking out tree 7db0ec7... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora updates-archive
Updating metadata for 'fedora-cisco-openh264'... done
Updating metadata for 'fedora-modular'... done
Updating metadata for 'updates-modular'... done
Updating metadata for 'updates'... done
Updating metadata for 'fedora'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2023-03-14T10:56:46Z solvables: 4
rpm-md repo 'fedora-modular'; generated: 2023-04-13T20:30:47Z solvables: 1082
rpm-md repo 'updates-modular'; generated: 2023-08-19T01:34:25Z solvables: 1086
rpm-md repo 'updates'; generated: 2023-08-29T01:27:00Z solvables: 22353
rpm-md repo 'fedora'; generated: 2023-04-13T20:37:10Z solvables: 69222
rpm-md repo 'updates-archive'; generated: 2023-08-18T02:36:14Z solvables: 31142
Resolving dependencies... done
Installing 1 packages:
  podman-gvproxy-5:4.6.0-1.fc38.x86_64 (updates-archive)
```

### What is the size of the package and its dependencies?

```
[core@localhost ~]$ rpm -qi podman-gvproxy
Name        : podman-gvproxy
Epoch       : 5
Version     : 4.6.0
Release     : 1.fc38
Architecture: x86_64
Install Date: Tue Aug 29 13:31:07 2023
Group       : Unspecified
Size        : 18000942
License     : Apache-2.0 and BSD-2-Clause and BSD-3-Clause and ISC and MIT and MPL-2.0
Signature   : RSA/SHA256, Fri Jul 21 12:32:40 2023, Key ID 809a8d7ceb10b464
Source RPM  : podman-4.6.0-1.fc38.src.rpm
Build Date  : Fri Jul 21 12:23:22 2023
Build Host  : buildhw-x86-05.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://podman.io/
Bug URL     : https://bugz.fedoraproject.org/podman
Summary     : Go replacement for libslirp and VPNKit
Description :
A replacement for libslirp and VPNKit, written in pure Go.
It is based on the network stack of gVisor. Compared to libslirp,
gvisor-tap-vsock brings a configurable DNS server and
dynamic port forwarding.
```

### What problem are you trying to solve with this package? Or what functionality does the package provide?

In this package, there is a binary called podman-gvforwader.  For usermode networking, this binary allows us to take traffic bound for a tap device and push it across a vsock to the host.

### Can the software provided by the package be run from a container?  Explain why or why not.

It cannot be run in a container.  It is the basic network setup for things like hyperv.

### Can the tool(s) provided by the package be helpful in debugging container runtime issues?

No

### Can the tool(s) provided by the package be helpful in debugging networking issues?

No

### Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

No.  It is required for basic networking use.

### In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

No service is required; for Podman machine, that is handled in ignition.

### Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS?

Not really

### Does the software provided by the package have a history of CVEs?

No

**Comment by baude** [comment]
> This is large (18MB) but it looks like it's truly needed for podman on some platforms. There is nothing else in the package so +1 from

there is more than one binary in there.  we could consider breaking it into its own rpm in the future?

**Comment by baude** [comment]
the actual binary size is just short of 5MB.  could we prune the unnecessary binaries?

**Comment by travier** [comment]
I could not find `podman-gvproxy` in recent builds https://koji.fedoraproject.org/koji/buildinfo?buildID=2272279, so I did:

```
$ dnf download podman-gvproxy
Last metadata expiration check: 1:53:01 ago on Tue 29 Aug 2023 04:04:44 PM CEST.
podman-gvproxy-4.4.2-2.fc38.x86_64.rpm                                                 2.0 MB/s | 3.6 MB     00:01    
$ rpm -qlp podman-gvproxy-4.4.2-2.fc38.x86_64.rpm
/usr/lib/.build-id
/usr/lib/.build-id/2d
/usr/lib/.build-id/2d/d2a6dcc1ac3b5f614bddca99c9efd447d50c20
/usr/libexec/podman
/usr/libexec/podman/gvproxy
/usr/share/doc/podman-gvproxy
/usr/share/doc/podman-gvproxy/README.md
/usr/share/licenses/podman-gvproxy
/usr/share/licenses/podman-gvproxy/LICENSE
```

Which for us FCOS is basically only a binary as we strip the docs.

**Comment by baude** [comment]
the name was changed to `gvisor-tap-vsock` I guess... I'll correct the title too.

https://koji.fedoraproject.org/koji/packageinfo?packageID=37521

**Comment by travier** [comment]
```
$ dnf download gvisor-tap-vsock
...
gvisor-tap-vsock-0.7.0-3.fc38.x86_64.rpm
$ rpm -qlp gvisor-tap-vsock-0.7.0-3.fc38.x86_64.rpm
/usr/lib/.build-id
/usr/lib/.build-id/2c
/usr/lib/.build-id/2c/04b02c1537a34e82640426646f3fbd810118d8
/usr/lib/.build-id/97
/usr/lib/.build-id/97/25e94b56349423daae1d77165de2f7ef0d1d4a
/usr/libexec/podman
/usr/libexec/podman/gvforwarder
/usr/libexec/podman/gvproxy
/usr/share/doc/gvisor-tap-vsock
/usr/share/doc/gvisor-tap-vsock/README.md
/usr/share/licenses/gvisor-tap-vsock
/usr/share/licenses/gvisor-tap-vsock/LICENSE
```

**Comment by travier** [comment]
```
[drwxr-xr-x tim      tim         17]  gvisor-tap-vsock-0.7.0-3.fc38.x86_64
└── [drwxr-xr-x tim      tim         45]  usr
    ├── [drwxr-xr-x tim      tim         23]  lib
    ├── [drwxr-xr-x tim      tim         20]  libexec
    │   └── [drwxr-xr-x tim      tim         40]  podman
    │       ├── [-rwxr-xr-x tim      tim       5.6M]  gvforwarder
    │       └── [-rwxr-xr-x tim      tim        12M]  gvproxy
    └── [drwxr-xr-x tim      tim         33]  share
        ├── [drwxr-xr-x tim      tim         30]  doc
        │   └── [drwxr-xr-x tim      tim         23]  gvisor-tap-vsock
        │       └── [-rw-r--r-- tim      tim       6.3K]  README.md
        └── [drwxr-xr-x tim      tim         30]  licenses
            └── [drwxr-xr-x tim      tim         21]  gvisor-tap-vsock
                └── [-rw-r--r-- tim      tim        11K]  LICENSE
```

**Comment by travier** [comment]
Could you clarify where this project fits in the networking stack? Why do we need it on top of https://github.com/containers/netavark or https://passt.top/passt/about/?

**Comment by travier** [comment]
If I look at https://github.com/containers/gvisor-tap-vsock#how-it-works-with-vsock, in both cases this package is needed on the host, not the VM.

**Comment by dustymabe** [comment]
I think there are still some open questions here about the architecture but we did discuss it during [the meeting today](https://discussion.fedoraproject.org/t/fedora-coreos-meeting-minutes-2023-08-30/88495):

```
13:12:44* dustymabe | #agreed In order to enable podman-remote like use cases on HyperV
                    | and AppleHV we will include the gvisor-tap-vsock package. The size
                    | of 5.6M for gvforwarder and 12M for gvproxy is a concern, though.
```

Let's work to get the above open questions answered and then also maybe discuss if there are any options for reducing sizes.

**Comment by baude** [comment]
the description provided in the template, i think, explains this:

```In this package, there is a binary called podman-gvforwader. For usermode networking, this binary allows us to take traffic bound for a tap device and push it across a vsock to the host.```

**Comment by dustymabe** [comment]
Had a chat with @baude about this today. The `gvisor-tap-vsock` is one piece of a solution that uses gvproxy to essentially create a generic tunnel back to the host for all networking for a VM. The tunnel isn't specific to podman (i.e. it's a generic tunnel in which container pulls and ostree updates and any other networking will traverse), but setting up the tunnel is specific to say podman machine/desktop.

The reason I didn't have any networking trouble (even without `gvisor-tap-vsock`) when executing our [documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-hyperv/) for setting up a hyperV FCOS instance is because the instructions tell the user to `Create A Virtual Switch`, which gives the VM networking.

In the podman machine/desktop case they want to make the UX seamless and not require this step.

Now, the podman machine/desktop software could create an FCOS VM that includes the `gvforwarder` binary in the Ignition config, but that might not work well considering on Windows the Ignition config has be split up into many Windows Registry entries.

Assuming we keep with our [original decision](https://github.com/coreos/fedora-coreos-tracker/issues/1557#issuecomment-1699874495) to include the `gvforwarder` in the host. @baude and I talked about options for this in the future to either reduce the size of the included binary or to remove the need for it at all. I'll enumerate those here just for record keeping. All of these were met with enthusiasm from @baude:


1. Split the RPM so that we just get the one binary that's needed. For now we can just hack out the binary that's not needed in post until the split has happened.
2. Update the passta networking stack that exists already to support vsock functionality. Then the passta RPM that is already included will have what they need.
3. Writing `gvforwarder` in another language to reduce size.
4. Vendor in vsock/forwarding functionality into podman itself. As a hacky example `/usr/bin/forwarder` is a symlink to `/usr/bin/podman` and then the `podman` binary switches on `$0` to act like the forwarder.

**Comment by cgwalters** [comment]
> Now, the podman machine/desktop software could create an FCOS VM that includes the gvforwarder binary in the Ignition config, 

(Or more sanely: start using a derived container image build...)

**Comment by cgwalters** [comment]
Thanks for summarizing this!

**Comment by jlebon** [comment]
We discussed this in [today's community meeting](https://meetbot-raw.fedoraproject.org//fedora-meeting-1/2023-09-13/fedora_coreos_meeting.2023-09-13-16.30.txt):

> AGREED: as previously agreed, we will include gvisor-tap-vsock in FCOS. For now we will remove the unneeded binaries from the RPM while we wait for the package to get split. In the future the podman team will explore other options and we'll open a podman issue to track that work.  (dustymabe, 17:24:56)

**Comment by baude** [comment]
this is awesome!

**Comment by baude** [comment]
@jlebon @dustymabe  lokesh has made a specific package for this already in f38 -> https://bodhi.fedoraproject.org/updates/?search=gvisor-tap-vsock

so i think we should use that one? ill update the title

**Comment by dustymabe** [comment]
It looks like the new version of podman [hard requires the new subpackage](https://src.fedoraproject.org/rpms/podman/c/e937b31ec5a1f2cff1c1514e49b702469f5f6e7e?branch=rawhide) so we don't need to update any package lists, but we do need to fast-track the new podman build.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `39.20230916.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230918.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230918.3.0`.
