### ISSUE TITLE
sshd.socket going away in Fedora 40

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1558]
### Describe the bug

Bug [BZ#2025716](https://bugzilla.redhat.com/show_bug.cgi?id=2025716) has been implemented in [openssh/8a294387d01967d610543b05d9b5078cea8a6543](https://src.fedoraproject.org/rpms/openssh/c/8a294387d01967d610543b05d9b5078cea8a6543?branch=rawhide) and will remove the `sshd.socket` unit starting with Fedora 39.

I had initially requested the socket unit removal but after more thoughts (and 2 years of migration and updates experience), it is not clear to me anymore that it's a good change.

This would impact FCOS users that switched openssh from the service to the socket unit. We would likely have to do something for the migration.

### Reproduction steps

Use `sshd.socket` instead of `sshd.service` (default).

### Expected behavior

System is still available over ssh after the F39 update.

### Actual behavior

System won't be accessible.

### System details

N/A

### Additional information

Fedora devel thread: [devel@lists.fedoraproject.org/thread/O6V7ZH3BMCWOREDWXOIAPUG7PGMWIBVR](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/O6V7ZH3BMCWOREDWXOIAPUG7PGMWIBVR/#BQPRQLXPBKPQL7KR62GUR5H7EEAS2CUN)

**Comment by dustymabe** [comment]
We discussed this in the [community meeting today](https://discussion.fedoraproject.org/t/fedora-coreos-meeting-minutes-2023-08-30/88495).

```
12:53:25* dustymabe | #agreed we will open a ticket with FESCO to see if this change
                    | would be better suited for Fedora 40. If it lands in F40 then we'll
                    | publish a CLHM helper to let people know the change is coming. If
                    | it lands in F39 we'll keep the socket for a notice period and warn
                    | people of the coming change.

```

**Comment by travier** [comment]
Filed the ticket for discussion by FESCo at https://pagure.io/fesco/issue/3062

**Comment by poettering** [comment]
→ https://github.com/systemd/systemd/pull/29159

**Comment by travier** [comment]
The change has been pushed-back to F40:
- https://pagure.io/fesco/issue/3062
- https://fedoraproject.org/wiki/Changes/Drop_Sshd_Socket

**Comment by travier** [comment]
https://github.com/systemd/systemd/pull/29159 has been merged upstream in systemd and fixes my concerns for me from what I tested.

**Comment by dustymabe** [comment]
> [systemd/systemd#29159](https://github.com/systemd/systemd/pull/29159) has been merged upstream in systemd and fixes my concerns for me from what I tested.

I think you were implying something here but it might be worth stating it explicitly. Are you trying to say that the upstream systemd new feature now makes it so that the SSH maintainer in Fedora probably won't need to drop the sshd.socket unit?

**Comment by travier** [comment]
Yes. I've commented https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/62Q4CWAPMQKGK5LTBGUPBVT76O3LSZYV/#62Q4CWAPMQKGK5LTBGUPBVT76O3LSZYV and https://discussion.fedoraproject.org/t/f40-change-proposal-drop-sshd-socket-self-contained/89604 that I don't think we should drop the socket anymore.

**Comment by dustymabe** [comment]
Looks like the change was rejected by FESCO: https://pagure.io/fesco/issue/3098#comment-887349

**Comment by travier** [comment]
Closing as this change has been rejected.
