### ISSUE TITLE
Microsoft Edge crash on Fedora release 38 (Thirty Eight)

### ISSUE THREAD

**Issue by dicatalin** [coreos/fedora-coreos-tracker#1561]
### Describe the bug

After the last updates Microsoft Edge (116.0.1938.69) keep crashing on Fedora 38 with dumping core.

`systemd-coredump[36753]: [🡕] Process 36520 (msedge) of user 1000 dumped core.
                                                     
                                                     Module libnss_resolve.so.2 from rpm systemd-253.7-1.fc38.x86_64
                                                     Module libnss_mdns4_minimal.so.2 from rpm nss-mdns-0.15.1-8.fc38.x86_64
                                                     Module libnss_myhostname.so.2 from rpm systemd-253.7-1.fc38.x86_64
                                                     Module libpcsclite.so.1 from rpm pcsc-lite-1.9.9-3.fc38.x86_64
                                                     Module libopensc.so.8 from rpm opensc-0.23.0-5.fc38.x86_64
                                                     Module opensc-pkcs11.so from rpm opensc-0.23.0-5.fc38.x86_64
                                                     Module p11-kit-trust.so from rpm p11-kit-0.25.0-1.fc38.x86_64
                                                     Module libibus-1.0.so.5 from rpm ibus-1.5.28-6.fc38.x86_64
                                                     Module im-ibus.so from rpm ibus-1.5.28-6.fc38.x86_64
                                                     Module libuuid.so.1 from rpm util-linux-2.38.1-4.fc38.x86_64
                                                     Module libsecret-1.so.0 from rpm libsecret-0.20.5-3.fc38.x86_64
                                                     Module libudev.so.1 from rpm systemd-253.7-1.fc38.x86_64
                                                     Module libdconfsettings.so from rpm dconf-0.40.0-8.fc38.x86_64
                                                     Module libpk-gtk-module.so from rpm PackageKit-1.2.6-6.fc38.x86_64
                                                     Module libogg.so.0 from rpm libogg-1.3.5-5.fc38.x86_64
                                                     Module libvorbis.so.0 from rpm libvorbis-1.3.7-7.fc38.x86_64
                                                     Module libltdl.so.7 from rpm libtool-2.4.7-6.fc38.x86_64
                                                     Module libtdb.so.1 from rpm libtdb-1.4.8-1.fc38.x86_64
                                                     Module libvorbisfile.so.3 from rpm libvorbis-1.3.7-7.fc38.x86_64
                                                     Module libgthread-2.0.so.0 from rpm glib2-2.76.5-1.fc38.x86_64
                                                     Module libgvfscommon.so from rpm gvfs-1.50.6-1.fc38.x86_64
                                                     Module libgvfsdbus.so from rpm gvfs-1.50.6-1.fc38.x86_64
                                                     Module libX11-xcb.so.1 from rpm libX11-1.8.6-1.fc38.x86_64
                                                     Module libjson-glib-1.0.so.0 from rpm json-glib-1.6.6-4.fc38.x86_64
                                                     Module libjpeg.so.62 from rpm libjpeg-turbo-2.1.4-2.fc38.x86_64
                                                     Module libXinerama.so.1 from rpm libXinerama-1.1.5-2.fc38.x86_64
                                                     Module libXcursor.so.1 from rpm libXcursor-1.2.1-3.fc38.x86_64
                                                     Module libwayland-egl.so.1 from rpm wayland-1.22.0-1.fc38.x86_64
                                                     Module libwayland-cursor.so.0 from rpm wayland-1.22.0-1.fc38.x86_64
                                                     Module libwayland-client.so.0 from rpm wayland-1.22.0-1.fc38.x86_64
                                                     Module libtracker-sparql-3.0.so.0 from rpm tracker-3.5.3-2.fc38.x86_64
                                                     Module libcloudproviders.so.0 from rpm libcloudproviders-0.3.2-1.fc38.x86_64
                                                     Module libepoxy.so.0 from rpm libepoxy-1.5.10-3.fc38.x86_64
                                                     Module libgdk_pixbuf-2.0.so.0 from rpm gdk-pixbuf2-2.42.10-2.fc38.x86_64
                                                     Module libcairo-gobject.so.2 from rpm cairo-1.17.8-4.fc38.x86_64
                                                     Module libpangoft2-1.0.so.0 from rpm pango-1.50.14-1.fc38.x86_64
                                                     Module libpangocairo-1.0.so.0 from rpm pango-1.50.14-1.fc38.x86_64
                                                     Module libgdk-3.so.0 from rpm gtk3-3.24.38-1.fc38.x86_64
                                                     Module libgtk-3.so.0 from rpm gtk3-3.24.38-1.fc38.x86_64
                                                     Module libbrotlicommon.so.1 from rpm brotli-1.0.9-11.fc38.x86_64
                                                     Module libbrotlidec.so.1 from rpm brotli-1.0.9-11.fc38.x86_64
                                                     Module libbz2.so.1 from rpm bzip2-1.0.8-13.fc38.x86_64
                                                     Module libxml2.so.2 from rpm libxml2-2.10.4-1.fc38.x86_64
                                                     Module libgraphite2.so.3 from rpm graphite2-1.3.14-11.fc38.x86_64
                                                     Module libdatrie.so.1 from rpm libdatrie-0.2.13-5.fc38.x86_64
                                                     Module liblz4.so.1 from rpm lz4-1.9.4-2.fc38.x86_64
                                                     Module libzstd.so.1 from rpm zstd-1.5.5-1.fc38.x86_64
                                                     Module liblzma.so.5 from rpm xz-5.4.1-1.fc38.x86_64
                                                     Module libcap.so.2 from rpm libcap-2.48-6.fc38.x86_64
                                                     Module libblkid.so.1 from rpm util-linux-2.38.1-4.fc38.x86_64
                                                     Module libgmp.so.10 from rpm gmp-6.2.1-4.fc38.x86_64
                                                     Module libhogweed.so.6 from rpm nettle-3.8-3.fc38.x86_64
                                                     Module libnettle.so.8 from rpm nettle-3.8-3.fc38.x86_64
                                                     Module libtasn1.so.6 from rpm libtasn1-4.19.0-2.fc38.x86_64
                                                     Module libunistring.so.5 from rpm libunistring-1.1-3.fc38.x86_64
                                                     Module libidn2.so.0 from rpm libidn2-2.3.4-2.fc38.x86_64
                                                     Module libp11-kit.so.0 from rpm p11-kit-0.25.0-1.fc38.x86_64
                                                     Module libcrypto.so.3 from rpm openssl-3.0.9-2.fc38.x86_64
                                                     Module libkeyutils.so.1 from rpm keyutils-1.6.1-6.fc38.x86_64
                                                     Module libkrb5support.so.0 from rpm krb5-1.21-3.fc38.x86_64
                                                     Module libcom_err.so.2 from rpm e2fsprogs-1.46.5-4.fc38.x86_64
                                                     Module libk5crypto.so.3 from rpm krb5-1.21-3.fc38.x86_64
                                                     Module libkrb5.so.3 from rpm krb5-1.21-3.fc38.x86_64
                                                     Module libpixman-1.so.0 from rpm pixman-0.42.2-1.fc38.x86_64
                                                     Module libxcb-shm.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                     Module libxcb-render.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                     Module libfreetype.so.6 from rpm freetype-2.13.0-2.fc38.x86_64
                                                     Module libfontconfig.so.1 from rpm fontconfig-2.14.2-1.fc38.x86_64
                                                     Module libpng16.so.16 from rpm libpng-1.6.37-14.fc38.x86_64
                                                     Module libharfbuzz.so.0 from rpm harfbuzz-7.1.0-1.fc38.x86_64
                                                     Module libthai.so.0 from rpm libthai-0.1.29-4.fc38.x86_64
                                                     Module libfribidi.so.0 from rpm fribidi-1.0.12-3.fc38.x86_64
                                                     Module libXau.so.6 from rpm libXau-1.0.11-2.fc38.x86_64
                                                     Module libxcb-randr.so.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                     Module libwayland-server.so.0 from rpm wayland-1.22.0-1.fc38.x86_64
                                                     Module libXrender.so.1 from rpm libXrender-0.9.11-2.fc38.x86_64
                                                     Module libXi.so.6 from rpm libXi-1.8.1-1.fc38.x86_64
                                                     Module libsystemd.so.0 from rpm systemd-253.7-1.fc38.x86_64
                                                     Module libselinux.so.1 from rpm libselinux-3.5-1.fc38.x86_64
                                                     Module libmount.so.1 from rpm util-linux-2.38.1-4.fc38.x86_64
                                                     Module libgmodule-2.0.so.0 from rpm glib2-2.76.5-1.fc38.x86_64
                                                     Module libz.so.1 from rpm zlib-1.2.13-3.fc38.x86_64
                                                     Module libgnutls.so.30 from rpm gnutls-3.8.1-1.fc38.x86_64
                                                     Module libavahi-client.so.3 from rpm avahi-0.8-22.fc38.x86_64
                                                     Module libavahi-common.so.3 from rpm avahi-0.8-22.fc38.x86_64
                                                     Module libgssapi_krb5.so.2 from rpm krb5-1.21-3.fc38.x86_64
                                                     Module libplds4.so from rpm nss-3.92.0-1.fc38.x86_64
                                                     Module libplc4.so from rpm nss-3.92.0-1.fc38.x86_64
                                                     Module libpcre2-8.so.0 from rpm pcre2-10.42-1.fc38.1.x86_64
                                                     Module libffi.so.8 from rpm libffi-3.4.4-2.fc38.x86_64
                                                     Module libasound.so.2 from rpm alsa-lib-1.2.9-1.fc38.x86_64
                                                     Module libcairo.so.2 from rpm cairo-1.17.8-4.fc38.x86_64
                                                     Module libpango-1.0.so.0 from rpm pango-1.50.14-1.fc38.x86_64
                                                     Module libxkbcommon.so.0 from rpm libxkbcommon-1.5.0-2.fc38.x86_64
                                                     Module libxcb.so.1 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                     Module libgbm.so.1 from rpm mesa-23.1.6-1.fc38.x86_64
                                                     Module libXrandr.so.2 from rpm libXrandr-1.5.2-10.fc38.x86_64
                                                     Module libXfixes.so.3 from rpm libXfixes-6.0.0-5.fc38.x86_64
                                                     Module libXext.so.6 from rpm libXext-1.3.5-2.fc38.x86_64
                                                     Module libXdamage.so.1 from rpm libXdamage-1.1.5-9.fc38.x86_64
                                                     Module libXcomposite.so.1 from rpm libXcomposite-0.4.5-9.fc38.x86_64
                                                     Module libX11.so.6 from rpm libX11-1.8.6-1.fc38.x86_64
                                                     Module libexpat.so.1 from rpm expat-2.5.0-2.fc38.x86_64
                                                     Module libatspi.so.0 from rpm at-spi2-core-2.48.3-1.fc38.x86_64
                                                     Module libdbus-1.so.3 from rpm dbus-1.14.8-1.fc38.x86_64
                                                     Module libdrm.so.2 from rpm libdrm-2.4.114-2.fc38.x86_64
                                                     Module libgio-2.0.so.0 from rpm glib2-2.76.5-1.fc38.x86_64
                                                     Module libcups.so.2 from rpm cups-2.4.6-4.fc38.x86_64
                                                     Module libatk-bridge-2.0.so.0 from rpm at-spi2-core-2.48.3-1.fc38.x86_64
                                                     Module libatk-1.0.so.0 from rpm at-spi2-core-2.48.3-1.fc38.x86_64
                                                     Module libnspr4.so from rpm nss-3.92.0-1.fc38.x86_64
                                                     Module libglib-2.0.so.0 from rpm glib2-2.76.5-1.fc38.x86_64
                                                     Module libgobject-2.0.so.0 from rpm glib2-2.76.5-1.fc38.x86_64
                                                     Stack trace of thread 36712:
                                                     #0  0x000055cfbba1aa76 n/a (msedge + 0x9218a76)
                                                     #1  0x00007f9f93f6833a ERR_clear_error (libcrypto.so.3 + 0x16833a)
                                                     #2  0x00007f9f69eb1687 _ZN5boost4asio3ssl6detail6engine7performEMS3_FiPvmES4_mRNS_6system10error_codeEPm (libmip_core.so + 0x4b1687)
                                                     #3  0x00007f9f69ec333e _ZNK5boost4asio3ssl6detail8write_opINS0_15const_buffers_1EEclERNS2_6engineERNS_6system10error_codeERm (libmip_core.so + 0x4c333e)
                                                     #4  0x00007f9f69ecac0f _ZN5boost4asio3ssl6detail5io_opINS0_19basic_stream_socketINS0_2ip3tcpEEENS2_8write_opINS0_15const_buffers_1EEENS0_6detail8write_opINS1_6streamIRS7_EES9_PKNS0_12const_bufferENSB_14transfer_all_tENSB_15write_dynbuf_opISF_NS0_19basic_streambuf_refISaIcEEESJ_NS_3_bi6bind_tIvNS_4_mfi3mf1IvN3web4http6client7details12asio_contextERKNS_6system10error_codeEEENSO_5list2INSO_5valueISt10shared_ptrISW_EEEPFNS_3argILi1EEEvEEEEEEEEEEclESY_mi (libmip_core.so + 0x4cac0f)
                                                     #5  0x00007f9f69ecb01a _ZN5boost4asio6detail8write_opINS0_3ssl6streamIRNS0_19basic_stream_socketINS0_2ip3tcpEEEEENS0_15const_buffers_1EPKNS0_12const_bufferENS1_14transfer_all_tENS1_15write_dynbuf_opISA_NS0_19basic_streambuf_refISaIcEEESF_NS_3_bi6bind_tIvNS_4_mfi3mf1IvN3web4http6client7details12asio_contextERKNS_6system10error_codeEEENSK_5list2INSK_5valueISt10shared_ptrISS_EEEPFNS_3argILi1EEEvEEEEEEEEclESW_mi (libmip_core.so + 0x4cb01a)
                                                     #6  0x00007f9f69ecb1cb _ZN3web4http6client7details15asio_connection11async_writeIN5boost4asio15basic_streambufISaIcEEENS5_3_bi6bind_tIvNS5_4_mfi3mf1IvNS2_12asio_contextERKNS5_6system10error_codeEEENSA_5list2INSA_5valueISt10shared_ptrISE_EEEPFNS5_3argILi1EEEvEEEEEEEvRT_RKT0_ (libmip_core.so + 0x4cb1cb)
                                                     #7  0x00007f9f69ecd173 _ZN3web4http6client7details12asio_context16handle_handshakeERKN5boost6system10error_codeE (libmip_core.so + 0x4cd173)
                                                     #8  0x00007f9f69ec2896 _ZN5boost4asio3ssl6detail5io_opINS0_19basic_stream_socketINS0_2ip3tcpEEENS2_12handshake_opENS_3_bi6bind_tIvNS_4_mfi3mf1IvN3web4http6client7details12asio_contextERKNS_6system10error_codeEEENS9_5list2INS9_5valueISt10shared_ptrISH_EEEPFNS_3argILi1EEEvEEEEEEclESJ_mi (libmip_core.so + 0x4c2896)
                                                     #9  0x00007f9f69ec2b54 _ZN5boost4asio6detail23reactive_socket_recv_opINS0_17mutable_buffers_1ENS0_3ssl6detail5io_opINS0_19basic_stream_socketINS0_2ip3tcpEEENS5_12handshake_opENS_3_bi6bind_tIvNS_4_mfi3mf1IvN3web4http6client7details12asio_contextERKNS_6system10error_codeEEENSC_5list2INSC_5valueISt10shared_ptrISK_EEEPFNS_3argILi1EEEvEEEEEEEE11do_completeEPvPNS1_19scheduler_operationESO_m (libmip_core.so + 0x4c2b54)
                                                     #10 0x00007f9f69eb2c76 _ZN5boost4asio6detail9scheduler10do_run_oneERNS1_27conditionally_enabled_mutex11scoped_lockERNS1_21scheduler_thread_infoERKNS_6system10error_codeE (libmip_core.so + 0x4b2c76)
                                                     #11 0x00007f9f69eb2dc8 _ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE (libmip_core.so + 0x4b2dc8)
                                                     #12 0x00007f9f69eceb11 n/a (libmip_core.so + 0x4ceb11)
                                                     #13 0x00007f9f69eb0fa3 boost_asio_detail_posix_thread_function (libmip_core.so + 0x4b0fa3)
                                                     #14 0x00007f9f94c6d907 start_thread (libc.so.6 + 0x8c907)
                                                     #15 0x00007f9f94cf3870 __clone3 (libc.so.6 + 0x112870)
                                                     
                                                     Stack trace of thread 36542:
                                                     #0  0x00007f9f94c6a1d9 __futex_abstimed_wait_common (libc.so.6 + 0x891d9)
                                                     #1  0x00007f9f94c6cee2 pthread_cond_timedwait@@GLIBC_2.3.2 (libc.so.6 + 0x8bee2)
                                                     #2  0x000055cfbba0a784 n/a (msedge + 0x9208784)
                                                     #3  0x000055cfbba41e08 n/a (msedge + 0x923fe08)
                                                     #4  0x000055cfbb9b2910 n/a (msedge + 0x91b0910)
                                                     #5  0x000055cfbb9ef30a n/a (msedge + 0x91ed30a)
                                                     #6  0x000055cfbba0ae62 n/a (msedge + 0x9208e62)
                                                     #7  0x00007f9f94c6d907 start_thread (libc.so.6 + 0x8c907)
                                                     #8  0x00007f9f94cf3870 __clone3 (libc.so.6 + 0x112870)
`

### Reproduction steps

1. Open Microsoft Edge for Linux (Work profile)
2. After one second the app is closed with core dump.

### Expected behavior

App open and working.

### Actual behavior

Crash with core dump

### System details

- HP Probook G7
- Fedora release 38 (Thirty Eight)

**Comment by travier** [comment]
This is the issue tracker for Fedora CoreOS. It looks like you are running a Fedora desktop variant so this is not the right place to report issues. I'd recommend starting with the discussion forums: https://discussion.fedoraproject.org/
