### ISSUE TITLE
Error upgrading nfs-utils

### ISSUE THREAD

**Issue by bionade24** [coreos/fedora-coreos-tracker#1564]
This gets retried for > 14 days now:

```
Sep 05 11:07:17 server1 zincati[6122]:     error: Checkout nfs-utils-1:2.6.3-1.rc3.fc38.x86_64: Hardlinking a9/3e5724cba2b79f0f3672459a6f9000b525ee87b96c2c4a036b214a6b0b6fba.fi
le to mount.nfs: File exists
```

Is this a packaging bug? Why the endless retries? Is this related to https://github.com/coreos/fedora-coreos-tracker/issues/572 ?

## Environment ##

What hardware/cloud provider/hypervisor is being used?
QUEMU

zincati config: 
```
[updates]
strategy = "periodic"

[[updates.periodic.window]]
days = [ "Sat", "Sun" ]
start_time = "02:30"
length_minutes = 120
```

**Comment by travier** [comment]
I've moved this issue to the Fedora CoreOS tracker as this is not specific to Zincati.

**Comment by travier** [comment]
Can you give us the output of `rpm-ostree status -b`? Thanks

**Comment by jlebon** [comment]
It's a packaging bug. The node should be able to upgrade to the 38.20230819.3.0 release currently rolling out containing an updated `nfs-utils-coreos` (or you can manually force an `rpm-ostree upgrade --bypass-driver`; this is normally not recommended but there are no barriers that require you to go to 38.20230806.3.0 first). See https://src.fedoraproject.org/rpms/nfs-utils/pull-request/9#comment-59201 for the gory details.

Let's keep https://github.com/coreos/fedora-coreos-tracker/issues/572 to track the larger packaging issue.
