### ISSUE TITLE
F39 FCOS Test Week on September 25

### ISSUE THREAD

**Issue by sumantro93** [coreos/fedora-coreos-tracker#1565]
Hey Folks,

I am opening this tracker to start the discussion about FCOS Test Week.

## Initial Tasks (to be done at least one week before test week)

- [x] Open this ticket in the `fedora-coreos-tracker` repo
- [x] Open a ticket with [Fedora QA](https://pagure.io/fedora-qa/issues).
  - [F36 example](https://pagure.io/fedora-qa/issue/695)

To be done after the Fedora QA folks have taken action on the QA ticket:

- [x] Confirm the Test Day page is created on the Fedora Wiki.
  - For example: <https://fedoraproject.org/wiki/Test_Day:Fedora_36_CoreOS_2022-04-04>
- [x] Confirm the Test Day results app is created.
  - For example: <https://testdays.fedoraproject.org/events/131>
- [x] Choose a day during the Test Week to host a video session for live debug help
- [x] Setup a Google Meet or other video conference session
- [x] Create a HackMD doc for capturing notes during live video session
- [x] Find volunteers to enumerate new documentation + test cases required for Test Week
  - Best done via dedicated video session
- [x] File an issue on `fedora-coreos-tracker` with TODO items.
  - For example: <https://github.com/coreos/fedora-coreos-tracker/issues/1147>
- [x] File a ticket requesting a Fedora badge is created
  - For example: <https://pagure.io/fedora-badges/issue/871>

## Announcing Test Week

Should be completed after the Initial Tasks are done

- [x] Draft an email to <coreos@lists.fedoraproject.org> announcing the Test Week
  - [x] Include a link to the Fedora Wiki
  - [x] Include a link to the Test Day results app
  - [x] Include a link to `fedora-coreos-tracker` for Test Week
  - [x] Include a link to the video conference
  - [x] Include a link to the HackMD doc
- [ ] Cross-post announcement email to discussion.fedoraproject.org with `#coreos` tag

- Example format: <https://hackmd.io/lCrVoW_RSMCRf2neiGhiPg>

## During Test Week

- Monitor `fedora-coreos-tracker` for new issues reported as part of Test Week
- Monitor #fedora-coreos on IRC for new issues reported as part of Test Week
- Ensure there is one or more representatives of Fedora CoreOS team present for live video session

## After Test Week

- [x] Update `fedora-coreos-tracker` ticket with any issues found
- [x] Update `fedora-coreos-tracker` ticket with any documentation updates made
- [x] Review Test Day results app and follow-up on any errors reported, if possible
- [ ] Follow up with the Fedora Badges ticket with Fedora Account System (FAS) usernames that participated in Test Week

**Comment by ravanelli** [comment]
@sumantro93 Thanks for opening it. We discussed it today in our FCOS meeting.
```
17:13:38 <ravanelli> #agreed Our test week is scheduled to take place from September 25th to September 29th
```
Does it work for you?
I'm also updating this issue to list the actions we need to work

**Comment by sumantro93** [comment]
> @sumantro93 Thanks for opening it. We discussed it today in our FCOS meeting.
> 
> ```
> 17:13:38 <ravanelli> #agreed Our test week is scheduled to take place from September 25th to September 29th
> ```
> 
> Does it work for you? I'm also updating this issue to list the actions we need to work

Yep!

**Comment by sumantro93** [comment]
qa tracker is open 
 wiki https://fedoraproject.org/wiki/Test_Day:Fedora_39_CoreOS
 test event https://testdays.fedoraproject.org/events/159
 fedocal https://calendar.fedoraproject.org/QA/2023/9/25/#m10581

**Comment by ravanelli** [comment]
Here is the link for the [F39 FCOS Test Day TODO List](https://github.com/coreos/fedora-coreos-tracker/issues/1571). I just copied and pasted the list from F38 for now. Will update it soon

**Comment by ravanelli** [comment]
Badge Ticket:  https://pagure.io/fedora-badges/issue/917

**Comment by ravanelli** [comment]
Docs Updated:
* https://github.com/coreos/fedora-coreos-docs/pull/587
* https://github.com/coreos/fedora-coreos-docs/pull/588
* https://github.com/coreos/fedora-coreos-docs/pull/591

New Test Case added:
* https://fedoraproject.org/wiki/QA:Testcase_CoreOS_Nutanix
* https://fedoraproject.org/wiki/QA:Testcase_CoreOS_HyperV
* https://fedoraproject.org/wiki/QA:Testcase_CoreOS_Kubevirt
