### ISSUE TITLE
Recommend Matrix over IRC

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1566]
It seems like FCOS discussions have stayed in the `#coreos:fedoraproject.org` Matrix channel now that the IRC/Matrix bridge is no longer active. Let's stop linking to the IRC channel (e.g. from [this repo](https://github.com/coreos/fedora-coreos-tracker#communication-channels-for-fedora-coreos) and [the website](https://docs.fedoraproject.org/en-US/fedora-coreos/)), turn off the IRC logger still active there, and mention in the channel topic that discussions have moved to Matrix.

**Comment by dustymabe** [comment]
One piece that would be nice to have in place is the "meeting bot" so that we don't have to trek back to IRC every Wednesday just for the meeting. I think work for that is happening over in https://pagure.io/cpe/initiatives-proposal/issue/29

**Comment by ravanelli** [comment]
We discussed it today during the FCOs meeting:
```
16:56:06 <ravanelli> #agreed We will enhance our documentation to encourage
day to day discussions within the Matrix channel, which has a substantial audience. 
During this transition, we will patiently await the setup of the Matrix bot before officially 
migrating there
```

**Comment by jlebon** [comment]
Implemented in https://github.com/coreos/fedora-coreos-tracker/pull/1568 and https://github.com/coreos/fedora-coreos-docs/pull/582.

I think the only thing that remains is to change the topic in the IRC channel. Maybe something like:

```
The community is moving to Matrix! Join us at <https://chat.fedoraproject.org/#/room/#coreos:fedoraproject.org>.
```

?

**Comment by dustymabe** [comment]
Updated the IRC channel topic.

I also sent an email to request dropping the IRC logging from https://libera.irclog.whitequark.org/fedora-coreos

**Comment by jlebon** [comment]
This looks done now.

**Comment by travier** [comment]
I've also updated the links in https://fedoraproject.org/wiki/Test_Day:Fedora_39_CoreOS
