### ISSUE TITLE
New Package Request: bash-color-prompt

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1567]
### What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

```
[core@cosa-devsh ~]$ sudo rpm-ostree install --dry-run bash-color-prompt
Checking out tree 3668815... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora updates-archive
Updating metadata for 'fedora-cisco-openh264'... done
Updating metadata for 'fedora-modular'... done
Updating metadata for 'updates-modular'... done
Updating metadata for 'updates'... done
Updating metadata for 'fedora'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2023-03-14T10:56:46Z solvables: 4
rpm-md repo 'fedora-modular'; generated: 2023-04-13T20:30:47Z solvables: 1082
rpm-md repo 'updates-modular'; generated: 2023-08-19T01:34:25Z solvables: 1086
rpm-md repo 'updates'; generated: 2023-09-06T01:11:10Z solvables: 22993
rpm-md repo 'fedora'; generated: 2023-04-13T20:37:10Z solvables: 69222
rpm-md repo 'updates-archive'; generated: 2023-09-05T01:01:28Z solvables: 34479
Resolving dependencies... done
Installing 1 packages:
  bash-color-prompt-0.1-6.fc38.noarch (updates)
Exiting because of '--dry-run' option
```

### What is the size of the package and its dependencies?

```
$ rpm -qip bash-color-prompt-0.1-6.fc38.noarch.rpm
Name        : bash-color-prompt
Version     : 0.1
Release     : 6.fc38
Architecture: noarch
Install Date: (not installed)
Group       : Unspecified
Size        : 19488
License     : GPL-2.0-or-later
Signature   : RSA/SHA256, Mon 21 Aug 2023 06:33:44 PM CEST, Key ID 809a8d7ceb10b464
Source RPM  : shell-color-prompt-0.1-6.fc38.src.rpm
Build Date  : Mon 21 Aug 2023 06:16:28 PM CEST
Build Host  : buildvm-s390x-26.s390.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://src.fedoraproject.org/rpms/shell-color-prompt
Bug URL     : https://bugz.fedoraproject.org/shell-color-prompt
Summary     : Color prompt for bash shell
Description :
Default colored bash prompt.
```

### What problem are you trying to solve with this package? Or what functionality does the package provide?

We're following the upstream Fedora change: https://fedoraproject.org/wiki/Changes/Color_Bash_Prompt

### Can the software provided by the package be run from a container?  Explain why or why not.

No as it's for the shell for the host

### Can the tool(s) provided by the package be helpful in debugging container runtime issues?

No

### Can the tool(s) provided by the package be helpful in debugging networking issues?

No

### Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

Yes

### In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

Only a config file

### Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS?

No

### Does the software provided by the package have a history of CVEs?

No

**Comment by cgwalters** [comment]
OK by me :+1: - not worth deviating from any other Fedora editions.

**Comment by dustymabe** [comment]
FWIW In the [community meeting today](https://discussion.fedoraproject.org/t/fedora-coreos-meeting-minutes-2023-09-06/89268) we discussed this and it was generally agreed that we'd pick up this change.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `39.20231002.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `39.20231101.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `39.20231101.3.0`.
