### ISSUE TITLE
dropping some firmware packages that provide Wi-Fi firmware

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1575]
The linux-firmware package [dropped](https://src.fedoraproject.org/rpms/linux-firmware/c/be92a95e169422f1108bce0aee70ed96fc26fb0b?branch=rawhide) the following firmware subpackages as requirements in F39+:

```
    atheros-firmware-20230804-153.fc38.noarch
    brcmfmac-firmware-20230804-153.fc38.noarch
    mt7xxx-firmware-20230804-153.fc38.noarch
    realtek-firmware-20230804-153.fc38.noarch 
```

We should determine if this is a change we want to make.

**Comment by travier** [comment]
We don't ship any wifi support and generally redirect to Fedora IoT or layering for those use cases, so it's a +1 for me.

Should we discuss this in a meeting?

**Comment by dustymabe** [comment]
> We don't ship any wifi support and generally redirect to Fedora IoT or layering for those use cases, so it's a +1 for me.

I think my biggest concern here is functionality changing without warning. One example: I layer in NetworkManager-wifi on a system I have. IIUC if we transparently pick up this change then the wifi in my system will stop working because NetworkManager-wifi doesn't name those firmware packages as requirements.

I think the state is fine for new installs, but for existing systems some care should be taken.

> 
> Should we discuss this in a meeting?

Yes! Added the meeting label. I created this ticket so we could discuss it in a meeting and also revert the drop in `next` for now while we figure out what we want to do.

**Comment by travier** [comment]
> I think my biggest concern here is functionality changing without warning. One example: I layer in NetworkManager-wifi on a system I have. IIUC if we transparently pick up this change then the wifi in my system will stop working because NetworkManager-wifi doesn't name those firmware packages as requirements.

Good point. Then we should probably announce it. I don't think we should keep them in but that can be discussed during the meeting.

**Comment by travier** [comment]
From today's meeting:
```
  * AGREED: We'll pause the rollout of the next stream due to
    https://github.com/coreos/fedora-coreos-tracker/issues/1578
    (travier, 16:51:35)
```

**Comment by dustymabe** [comment]
Capturing some of the discussion from the meeting I think we discussed a few options:

- having NetworkManager-wifi require the wifi firmware packages in the future
    - involves another team, not great because it requires firmwares that aren't needed
- running a migration that detects if NetworkManager-wifi is layered and add the 4 firmware packages to the layering requests
- adding a CLHM helper that detects when NetworkManager-wifi is layered and warning/instructing the user on necessary action.


In the meeting we were leaning more towards the last option and making the "warning period" last until F40 is released, but as mentioned in the previous comment we'll discuss more and finalize the plan next week.

**Comment by travier** [comment]
The issue with options 2 & 3 is that it extends the lifetime of the CLHM unit warning for modules to a full release worth of time: https://github.com/coreos/fedora-coreos-config/pull/2510. While the module related CLHM was limited in time until the F39 release, this one will be there for a while.

**Comment by dustymabe** [comment]
> The issue with options 2 & 3 is that it extends the lifetime of the CLHM unit warning for modules to a full release worth of time: [coreos/fedora-coreos-config#2510](https://github.com/coreos/fedora-coreos-config/pull/2510). While the module related CLHM was limited in time until the F39 release, this one will be there for a while.

Not sure I completely understand. IIUC this CLHM helper would have nothing to do with https://github.com/coreos/fedora-coreos-config/pull/2510. It would be implemented similarly, but be independent code. The CLHM helper added in https://github.com/coreos/fedora-coreos-config/pull/2510 will essentially be dead code in a month's time because `releasever == 38` will no longer be true.

**Comment by travier** [comment]
Turns out rpm-ostree is called by Zincati on boot anyway so the CLHM is not adding much overhead, thus resolving my concerns.

**Comment by travier** [comment]
From today's meeting:

```
  * AGREED: We'll keep the packages in FCOS until the rebase to F40.
    We'll add a CLHM module to warn for systems where wifi packages are
    layered and we'll send a warning mail.  (travier, 17:03:46)
```

**Comment by dustymabe** [comment]
Since we didn't follow through on the CLHM helper and the email warning to users I'm guessing we need to modify this proposal to target F41 instead.

**Comment by travier** [comment]
I think we should still do it, warning or not. WiFi is not part of the default image so we should not go out of our way to make it work.

**Comment by travier** [comment]
From https://github.com/coreos/fedora-coreos-tracker/issues/1700#issuecomment-2021454488, we'll need to add

```
nxpwireless-firmware
tiwilink-firmware
```

back as well to keep parity with current F39 content.

**Comment by travier** [comment]
Ideally we would document how to setup WiFi on Fedora CoreOS and document all the caveats around firmwares and layering.

**Comment by c4rt0** [comment]
We discussed this today in the [FCOS meeting](https://meetbot.fedoraproject.org/meeting-1_matrix_fedoraproject-org/2024-03-27/fedora-coreos-meeting.2024-03-27-16.30.log.html). 

It was decided to re-discuss the action plan for this issue during the next meeting.

**Comment by yasminvalim** [comment]
We discussed this issue today in the FCOS meeting.

We decided to implement wifi firmwares back for the F40 release and plan the deprecation for at least 3 months after initial announcement on coreos-status.

**Comment by dustymabe** [comment]
Let's keep this open for when this ships in our prod streams.

**Comment by c4rt0** [comment]
I have no idea how I closed this issue as complete - sorry folks, it must've been an unexpected 'Enter' stroke.

**Comment by travier** [comment]
It's because you pushed the commit where I mentioned it as fixed in a branch with a matching name. It should be fine now.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `41.20240916.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `41.20241027.3.0`.
