### ISSUE TITLE
bump-lockfile is failing?

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#1579]
https://bodhi.fedoraproject.org/updates/FEDORA-2023-13b41d2e37 shipped a few days ago, but isn't in testing-devel yet.

Are we blocked on e.g. https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/bump-lockfile/754/ ?  Something going wrong recently with ppc64le virt?

**Comment by dustymabe** [comment]
Another thing that happened recently is that we enabled the `next-devel` stream so now when `bump-lockfiles` runs (it's just a job that spawns the `bump-lockfile` job specifying what stream to run against) it now kicks off two `bump-lockfile` jobs: one for `testing-devel` and one for `next-devel`. These run simultaneously, which could be the reason why the ppc64le job is taking longer now. 

Maybe this can help: https://github.com/coreos/fedora-coreos-pipeline/pull/913

**Comment by dustymabe** [comment]
Since https://github.com/coreos/fedora-coreos-pipeline/pull/913 and we've had a few runs succeed that have been going serially I'll close this out and re-open it if we run into more problems.
