### ISSUE TITLE
Fedora Test Day during Fedora 30 development cycle?

### ISSUE THREAD

**Issue by kparal** [coreos/fedora-coreos-tracker#158]
Hello, 
I know that there's no official preview release yet (#145), but I wonder whether there's something you'd like to run a [Fedora Test Day](https://fedoraproject.org/wiki/QA/Test_Days) for. It could be some highly experimental pre-preview, or it could be some important part of the technology you build FCOS on. The only requirement is that it needs to be something that's interesting for your community, and that they can easily participate and test that image/technology, in order to provide feedback and report bugs. You surely have a better overview of your current community than I have, so it would be your call how high-level or low-level and technical the test day gets.

Is there anything you'd like to run as a Fedora Test Day in the next ~6 weeks, or is it still too early for this?

Cheers,
Kamil
Fedora QA

**Comment by dustymabe** [comment]
hey @kparal. I think it's still too early for this. We will update you here when we're ready. It will probably be after the Fedora 30 release.

**Comment by kparal** [comment]
OK, thanks for info.

**Comment by kparal** [comment]
Hello, now that F30 is out, do you have a better idea of the FCOS preview release schedule? Does it make sense to put some test day placeholder into our QA calendar, or is it still too early?

**Comment by sumantro93** [comment]
> Hello, now that F30 is out, do you have a better idea of the FCOS preview release schedule? Does it make sense to put some test day placeholder into our QA calendar, or is it still too early?

I am also interested to know the same!

**Comment by dustymabe** [comment]
Still too early right now - we're wiring up more of the releng parts. Will be in contact soon!

**Comment by kparal** [comment]
Hey, now that the preview release is out, is there something you want to organize? Or are you still getting enough feedback from the preview release and don't need any more?

**Comment by dustymabe** [comment]
@kparal nothing yet. thanks for asking

**Comment by dustymabe** [comment]
going to close this out.. we'll re-sync with the testing team once we're ready.
