### ISSUE TITLE
'Protocol not supported' on mounting NFS v4.1 mounts

### ISSUE THREAD

**Issue by vrutkovs** [coreos/fedora-coreos-tracker#1601]
### Describe the bug

On FCOS `testing-devel` bump in OKD (https://github.com/openshift/okd-machine-os/pull/681) from 38.20231006.20 to 38.20231024.20.0 several NFS tests start failing:
* [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] volumes should store data
*and other for `[Driver: nfs]` started failing

Journal shows that mount command fails:
```
Oct 26 10:22:32.315837 ip-10-0-43-136 kubenswrapper[2393]: E1026 10:22:32.315728    2393 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/nfs/59374f2c-aeab-449e-9664-dd648c403b9b-pvc-4f918fd6-6869-4ab7-a6b9-e36a5330b1c0 podName:59374f2c-aeab-449e-9664-dd648c403b9b nodeName:}" failed. No retries permitted until 2023-10-26 10:24:34.315705374 +0000 UTC m=+2441.793142782 (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "pvc-4f918fd6-6869-4ab7-a6b9-e36a5330b1c0" (UniqueName: "kubernetes.io/nfs/59374f2c-aeab-449e-9664-dd648c403b9b-pvc-4f918fd6-6869-4ab7-a6b9-e36a5330b1c0") pod "pod-30358f1a-daae-41a2-9ced-00e52db7126c" (UID: "59374f2c-aeab-449e-9664-dd648c403b9b") : mount failed: exit status 32
Oct 26 10:22:32.315837 ip-10-0-43-136 kubenswrapper[2393]: Mounting command: mount
Oct 26 10:22:32.315837 ip-10-0-43-136 kubenswrapper[2393]: Mounting arguments: -t nfs -o vers=4.1 10.131.0.35:/export/pvc-4f918fd6-6869-4ab7-a6b9-e36a5330b1c0 /var/lib/kubelet/pods/59374f2c-aeab-449e-9664-dd648c403b9b/volumes/kubernetes.io~nfs/pvc-4f918fd6-6869-4ab7-a6b9-e36a5330b1c0
Oct 26 10:22:32.315837 ip-10-0-43-136 kubenswrapper[2393]: Output: mount.nfs: Protocol not supported for 10.131.0.35:/export/pvc-4f918fd6-6869-4ab7-a6b9-e36a5330b1c0 on /var/lib/kubelet/pods/59374f2c-aeab-449e-9664-dd648c403b9b/volumes/kubernetes.io~nfs/pvc-4f918fd6-6869-4ab7-a6b9-e36a5330b1c0
```

Not sure why 4.1 protocol cause failure - or what exactly this error message means

### Reproduction steps

1. Create a k8s node using FCOS 38.20231024.20.0
2. Start k8s conformance tests for storage

### Expected behavior

Tests pass

### Actual behavior

Tests fail

### System details

- AWS, but reproducible on every platform
- FCOS testing-devel 38.20231024.20.0, but not 38.20231006.20 or `stable`

**Comment by dustymabe** [comment]
Since you are already on the `testing-devel` stream would you want to walk the tree of `testing-devel` releases between `38.20231006.20` and `38.20231024.20.0` to find the first offender?

**Comment by vrutkovs** [comment]
Binary search would indeed be great, but https://quay.io/repository/fedora/fedora-coreos doesn't have tagged versions, so I can't even roll back to `38.20231006.20`

**Comment by dustymabe** [comment]
The OCI archive for each is in the [builds browser](https://builds.coreos.fedoraproject.org/browser?stream=testing-devel&arch=aarch64). You can parse the metadata for each release or use the `download` link from the builds browser (shown below):

![Screenshot 2023-10-27 at 09-44-18 Fedora CoreOS Build Browser](https://github.com/coreos/fedora-coreos-tracker/assets/4530030/f2c0f472-edda-47e4-b1c9-9a556f464036)

**Comment by vrutkovs** [comment]
Seems its a kernel regression - rolling back to 6.5.4 fixes it.

Do we want to keep this issue open or should I close it in favor of a Fedora bugreport?

**Comment by dustymabe** [comment]
> Seems its a kernel regression - rolling back to 6.5.4 fixes it.

Thanks for tracking that down.

> 
> Do we want to keep this issue open or should I close it in favor of a Fedora bugreport?

I'd say both. If you open a BZ could you link it here?

Might also be worth seeing if it's fixed in latest `rawhide` kernel builds, which are on 6.6 RCs.

**Comment by vrutkovs** [comment]
Yup, checking Rawhide in https://github.com/openshift/okd-machine-os/pull/442 and going to test latest 6.5 from koji

**Comment by vrutkovs** [comment]
This is resolved in 6.6.x and 6.5.9. Keeping open to track this until it lands in F38/F39

**Comment by dustymabe** [comment]
Thanks @vrutkovs. 6.5.9+ will probably land in `testing` in two weeks and then in `stable` after that.

**Comment by vrutkovs** [comment]
Fixed in `next` 39.20231027.1.0

**Comment by dustymabe** [comment]
> Fixed in `next` 39.20231027.1.0

Yep with `kernel-6.5.9-300.fc39`.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `39.20231027.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `39.20231101.2.0`. Please try out the new release and report issues.
