### ISSUE TITLE
GA rebase checklist should handle "manual cherry-picks" into Pungi compose

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1602]
See e.g. https://github.com/coreos/fedora-coreos-config/pull/2692 in which we manually fast-tracked a package to match the compose.

Maybe we just need another GitHub Action that we can manually run for that period of time which just ensures our lockfiles match the latest compose output?

**Comment by dustymabe** [comment]
With https://github.com/coreos/fedora-coreos-config/pull/2705 and https://github.com/coreos/fedora-coreos-config/pull/2706 should we close this?

**Comment by jlebon** [comment]
I opened https://github.com/coreos/fedora-coreos-tracker/pull/1604 which will close this.
