### ISSUE TITLE
Add FedoraGroup=coreos to our AWS created AMIs/Snapshots

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1605]
It appears Fedora has a policy for the main AWS account that each group tag resources with the `FedoraGroup=` tag. We should start adhering to this policy. It's described at https://docs.fedoraproject.org/en-US/infra/sysadmin_guide/aws-access/#_ec2

The context for this is the email thread [here](https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/thread/YDQFDMYXNFW35EJUWYWPXNBT3ATKSRAU/#SWY3LXZVHMOQUD5AUPDT3IWHC7Z27DRJ).

**Comment by dustymabe** [comment]
ok the following two PRs should take care of the first part of this:

- https://github.com/coreos/fedora-coreos-pipeline/pull/978
- https://github.com/coreos/coreos-assembler/pull/3777


The remaining two pieces here:

1. we need to ensure that running `cosa aws-replicate`, as is done in the release job (in libcloud.groovy from the pipeline), also copies the tags. You can test this by just running the replicate your self and have it replicate to a single other region.
2. before the end of f40 final infra freeze we need to actually iterate over all builds of FCOS and retroactively add the `FedoraGroup=coreos` tag to them. We can probably script this up with `cosa buildfetch` or maybe with a read-only s3fs mount or something. For context see [this email](https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/message/DBXG6M4ORC3RHPIG4TV2RKBKTSENE632/) and the related thread.

**Comment by gursewak1997** [comment]
> 1. we need to ensure that running `cosa aws-replicate`, as is done in the release job (in libcloud.groovy from the pipeline), also copies the tags. You can test this by just running the replicate your self and have it replicate to a single other region.

Tested this and can confirm that `cosa aws-replicate` does copy the tags. Also added a [patch](https://github.com/coreos/coreos-assembler/pull/3778) to use local aws-credentials file to run `cosa aws-replicate`.

**Comment by dustymabe** [comment]
OK this is now done. @gursewak1997 wrote a script and we ran it and added tags to all AMIs that our build metadata is aware of.

- [aws_tag.py.txt](https://github.com/coreos/fedora-coreos-tracker/files/15136950/aws_tag.py.txt)
- [log.txt.zip](https://github.com/coreos/fedora-coreos-tracker/files/15136944/log.txt.zip)
