### ISSUE TITLE
Add kernel and initramfs.img to the pipeline output

### ISSUE THREAD

**Issue by imcleod** [coreos/fedora-coreos-tracker#161]
Much like a composed RHEL or Fedora tree, it would be great to have direct access to the kernel and initramfs of the installer.  For example, with F29 you have:

http://repo.ialab.dsu.edu/fedora/linux//releases/29/Server/x86_64/os/images/boot.iso

But you also have:

http://repo.ialab.dsu.edu/fedora/linux//releases/29/Server/x86_64/os/images/pxeboot/initrd.img
http://repo.ialab.dsu.edu/fedora/linux//releases/29/Server/x86_64/os/images/pxeboot/vmlinuz

This allows tools like virt-install or OZ to look at a "tree" and direct boot the kernel and ramdisk, with fine grain control over the kernel command line.  This is quite helpful.

Can we add these two artifacts to the pipeline output for FCOS?

**Comment by dustymabe** [comment]
Since it is just the same initramfs and vmlinuz can pretty easily add these as outputs to our pipeline. Worth noting, though, that there may be some changes once we start to work on #105 and #106.

cc @bgilbert

**Comment by lucab** [comment]
#105 (live-PXE artifacts) may end up producing a different pair of kernel+initramfs.
Thus, let's just make sure that the installer artifacts have a `.installer` component-label somewhere in their name.
That way we can produce side-by-side at some point in the future (and maybe eventually drop this, if we end up following CL live-PXE install path).

**Comment by dustymabe** [comment]
There are two ways we could implement this in COSA. We could either generate these during the same `buildextend-installer` command (the script [already pulls out the kernel/initrd](https://github.com/coreos/coreos-assembler/blob/63b56a4a43a746f0f5c810ddd1449bc94c46f2bf/src/cmd-buildextend-installer#L83-L88) anyway) and add them to the output artifacts or we could create a new command to do this piece.

**Comment by yuqi-zhang** [comment]
I vote we just have it as part of `buildextend-installer` unless we foresee a reason we'd need to have them in a separate process in the future

**Comment by mike-nguyen** [comment]
initramfs and kernel are now artifacts of a build: http://artifacts.ci.centos.org/fedora-coreos/prod/builds/latest/
