### ISSUE TITLE
Writing symlinks under /etc/systemd/system in Fedora IoT 39 apparently doesn't survive the reboot.

### ISSUE THREAD

**Issue by gabrieleturchi** [coreos/fedora-coreos-tracker#1615]
### Describe the bug

Apparently any symlink created or removed under /etc/systemd/system (like "systemctl disable ModemManager" or "systemctl set-default graphical.target" - I haven't checked under other /etc folders) is not kept for the next reboot.
Creating a file (like a new service) works. I'm pretty sure that worked well under Fedora IoT 38.

My current workaround in fact is to make a service who force the right target and usind predefined services configuration to enable my new services.

Of course I installed xfce before to run “systemctl set-default graphical.target”.

GT

### Reproduction steps

1. Install graphical environment
2. systemctl set-default graphical.target

### Expected behavior

Graphical environment running at boot

### Actual behavior

multi-user text environment running at boot

### System details

Raspberry Pi 3 

### Butane or Ignition config

```yaml
The image was made with arm-image-installer, just adding the ssh authorized_keys file.
```

**Comment by dustymabe** [comment]
This is the Fedora CoreOS issue tracker. Please open an issue in the IoT issue tracker: https://pagure.io/fedora-iot/issues

**Comment by miabbott** [comment]
> This is the Fedora CoreOS issue tracker. Please open an issue in the IoT issue tracker: https://pagure.io/fedora-iot/issues

We have a new issue tracker on GH - https://github.com/fedora-iot/iot-distro/issues
