### ISSUE TITLE
Use consistent approach to platform naming

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#162]
We've been referring to `AWS` rather than `EC2`, but `GCE` rather than `GCP`.  We might want to fix the inconsistency while we still have some ability to do so.

We've generally used the name of the overall platform rather than the compute component (`OpenStack` rather than `nova`; `VMware` generally), which suggests changing `GCE` to `GCP`.  OTOH there are `qemu` and `virtualbox`, but they're not part of larger suites.

**Comment by dustymabe** [comment]
+1 - i'm perfectly fine with using the name that is most appropriate. I think people will be able to find the proper artifacts either way.

**Comment by ashcrow** [comment]
:+1:

**Comment by bgilbert** [comment]
Changed `gce` -> `gcp` and (as it turns out) `ec2` -> `aws` in Ignition and Afterburn.  I think there are no other outstanding uses.
