### ISSUE TITLE
Give `coreos` Fedora group co-maintainership of all CoreOS-related packages in Fedora

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1631]
We have lots of upstream repos that require regular releases. We'd like to spread the load of cutting releases more. One hurdle to this is that not everyone on the CoreOS team is currently a packager. We'd like to get them added progressively, but to make maintenance easier, I'd like to propose making [the `coreos` group](https://accounts.fedoraproject.org/group/coreos/) a member of all the CoreOS projects with "commit" access to which we can then add co-maintainers.

**Comment by travier** [comment]
SGTM

**Comment by travier** [comment]
Let's do this. We can also consider creating another `coreos-packagers` group for commit only access and re-use the `coreos` group for admin access to all our repos.

**Comment by travier** [comment]
We discussed this issue in [today's community meeting](https://meetbot.fedoraproject.org/meeting-1_matrix_fedoraproject-org/2024-03-13/fedora-coreos-meeting.2024-03-13-16.34.html):

```
AGREED: We will create a coreos-packager group with commit access to packages maintained
by the group and use the coreos group for admin access to those same packages.
(@siosm:matrix.org, 17:12:43)
```

**Comment by travier** [comment]
So we need to follow:
- https://docs.fedoraproject.org/en-US/infra/howtos/groups_in_fedora/#_how_to_request_a_group_to_be_created
- And file a ticket in https://pagure.io/fedora-infrastructure/
- To request a group and then use those groups for all our packages:
  - [ ] ignition
  - [ ] butane
  - [ ] ...

**Comment by travier** [comment]
Filed: https://pagure.io/fedora-infrastructure/issue/11895

**Comment by travier** [comment]
We now have a new group that we can use to grant commit access to all the packages maintained by folks linked to Fedora CoreOS: https://accounts.fedoraproject.org/group/coreos-sig/

I'm currently the sole member able to sponsor people into this group but I'll file another ticket to add more.

Please add your Fedora Account ID here if you would like to request to be granted commit access and I haven't already added you to the group.

Note that although commit access lets anybody directly push changes to the repo, we strongly recommend that you still make changes in you fork and then open PRs. Make sure to clone the original repo as HTTPS and add your fork using SSH as if you create branches by mistake in the main repo for example, this will require a ticket to releng to remove them.

**Comment by jbtrystram** [comment]
> Please add your Fedora Account ID here if you would like to request to be granted commit access and I haven't already added you to the group.

jbtrystram

**Comment by travier** [comment]
As the existing `coreos` group is not a packaging group, I can not add it as admin to all repos.

**Comment by travier** [comment]
This is now done. Thanks all.
