### ISSUE TITLE
Fedora 40 Change: Switch pam_userdb from BerkeleyDB to GDBM

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1634]
For the [proposed Fedora 40 changes](https://github.com/coreos/fedora-coreos-tracker/issues/1626) we decided the following change needed action:

- [Switch pam_userdb from BerkeleyDB to GDBM](https://fedoraproject.org/wiki/Changes/PamBerkeleyDBtoGdbm)
     - pam_userdb was built with support for BerkeleyDB, but this project is no longer maintained as open source, so it is replaced by GDBM.
     - Tracking bug: [#2245149](https://bugzilla.redhat.com/show_bug.cgi?id=2245149)

The notes for this are:

- **NOTES**: jlebon: NEEDS INVESTIGATION. looks like they expect users to run a conversion tool

**Comment by travier** [comment]
According to https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/pam_userdb/, this is mostly used for systems with vsftpd installed, which we don't have by default. We can add a note pointing to the docs but I don't think we need to do anything here.

**Comment by travier** [comment]
Closing as there is nothing to do for us here besides mentioning it in the update notes and this is tracked in another issue.
