### ISSUE TITLE
Fedora 40 Changes: Removing SSSD ‘files provider’

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1635]
For the [proposed Fedora 40 changes](https://github.com/coreos/fedora-coreos-tracker/issues/1626) we decided the following change needed action:

- [Removing SSSD ‘files provider’](https://fedoraproject.org/wiki/Changes/SSSDRemoveFilesProvider)
     - Remove SSSD “files provider” feature that allows handling of local users.
     - Tracking bug: [#2252765](https://bugzilla.redhat.com/show_bug.cgi?id=2252765)

The notes for this are:

- **NOTES**: jlebon: *should* be transparent to us, but this touches nsswitch.conf, which is sensitive

**Comment by travier** [comment]
This one still needs to be investigated

**Comment by jlebon** [comment]
As suspected (by the fact that CI isn't completely broken on f40), `nsswitch.conf` still looks sane. One can see the removal of sssd in the passwd and group entries:

```
root@cosa-devsh:~# grep VERSION_ID /etc/os-release
VERSION_ID=39
root@cosa-devsh:~# grep ^passwd /etc/nsswitch.conf 
passwd:     files altfiles sss systemd
root@cosa-devsh:~# grep ^group /etc/nsswitch.conf 
group:      files altfiles sss systemd
```

vs

```
root@cosa-devsh:~# grep VERSION_ID /etc/os-release
VERSION_ID=40
root@cosa-devsh:~# grep ^passwd /etc/nsswitch.conf
passwd:     files altfiles systemd
root@cosa-devsh:~# grep ^group /etc/nsswitch.conf
group:      files [SUCCESS=merge] altfiles [SUCCESS=merge] systemd
```

The `group` line looks slightly different than just the removal of `sss` but that's a separate change ([related](https://github.com/coreos/fedora-coreos-tracker/issues/1680)).
