### ISSUE TITLE
Missing multi-arches images for iso-offline-install-iscsi.bios

### ISSUE THREAD

**Issue by jbtrystram** [coreos/fedora-coreos-tracker#1638]
`kola testiso iso-offline-install-iscsi.bios` on any other arch than `amd64`

  The test fails because it relies on https://quay.io/repository/jbtrystram/targetcli which is not multi-arch (yet)

This is a bit speculative because I am not able to see the logs from the tests :)

**Comment by marmijo** [comment]
This test is failing in RHCOS as well. Here's the console log from this test failing in a `[14-9.2][x86_64]` run today:
[console.txt](https://github.com/coreos/fedora-coreos-tracker/files/13745819/console.txt)

**Comment by jbtrystram** [comment]
This is waiting for #1639

**Comment by jbtrystram** [comment]
I am closing this as the multi arch images have been available for some time now

**Comment by jbtrystram** [comment]
To avoid confusion : 
The images currently live at quay.io/jbtrystram/targetcli

This is not ideal as we want those to be owned by coreos. 
The next step is to move them to the coreos-assembler repo, and this is tracked at https://github.com/coreos/fedora-coreos-tracker/issues/1639

**Comment by gursewak1997** [comment]
We can probably remove the test from https://github.com/openshift/os/blob/master/kola-denylist.yaml as well
