### ISSUE TITLE
Create a new repo to host Container images needed by Kola tests

### ISSUE THREAD

**Issue by jbtrystram** [coreos/fedora-coreos-tracker#1639]
Some kola tests requires external container images. In the case of iSCSI install, we use a `target` container to act as the iSCSI target server, from which we mount a block device and install coreOS on it. 

So far i have been building an hosting this image on my own, but having the kola tests rely on it is a bit brittle in my opinion. 
I've found at least another instance of it with `luks.*` tests, which pull `quay.io/mike_nguyen/tang`. the image have not been updated for 3 years. 
Maybe there are others tests like this that I am not aware of. 

I propose to create a new repo under the coreOS org, to host the source and build the images on a regular basis.
Maybe this would warrant the creation of a dedicated quay.io org as well ? e.g. coreos-kola-dependencies-images or something explicit. Names are hard.

I created a draft of such a repo here : https://github.com/jbtrystram/kola-container-images, f agreed i will transfer the ownership of it to the coreOS org.

**Comment by travier** [comment]
+1 for this. Let's discuss that in the first community meeting in January?

**Comment by travier** [comment]
In the mean time, if you could merge and update Mike's image into your repo that would be great!

**Comment by jbtrystram** [comment]
> In the mean time, if you could merge and update Mike's image into your repo that would be great!

yeah i am working on that :)

**Comment by dustymabe** [comment]
We discussed this in the [community meeting today](https://discussion.fedoraproject.org/t/fedora-coreos-meeting-minutes-2024-01-03/100838):


- AGREED: we will build manifest listed container images for specific tests using Jenkins jobs and our multi-arch builders (like we build cosa and fcos-buildroot today) and store them in the quay.io/coreos-assembler org in quay. (@dustymabe:matrix.org, 17:06:08)
