### ISSUE TITLE
New Package Request: mtr

### ISSUE THREAD

**Issue by maddymeows** [coreos/fedora-coreos-tracker#1644]
### What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

None

```
Checking out tree cd3ab59... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora updates-archive
Updating metadata for 'fedora-cisco-openh264'... done
Updating metadata for 'updates'... done
Updating metadata for 'fedora'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2023-03-14T10:57:01Z solvables: 4
rpm-md repo 'updates'; generated: 2024-01-04T01:58:21Z solvables: 17492
rpm-md repo 'fedora'; generated: 2023-11-01T00:12:39Z solvables: 70825
rpm-md repo 'updates-archive'; generated: 2024-01-04T02:21:43Z solvables: 20404
Resolving dependencies... done
Installing 1 packages:
  mtr-2:0.95-6.fc39.x86_64 (fedora)
Exiting because of '--dry-run' option
```

### What is the size of the package and its dependencies?

```
Name        : mtr
Epoch       : 2
Version     : 0.95
Release     : 6.fc39
Architecture: x86_64
Install Date: Thu Jan  4 19:24:19 2024
Group       : Unspecified
Size        : 197705
License     : GPL-2.0-only
Signature   : RSA/SHA256, Thu Jul 20 18:21:48 2023, Key ID 75cf5ac418b8e74c
Source RPM  : mtr-0.95-6.fc39.src.rpm
Build Date  : Thu Jul 20 16:17:22 2023
Build Host  : buildhw-x86-04.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://www.bitwizard.nl/mtr/
Bug URL     : https://bugz.fedoraproject.org/mtr
Summary     : Network diagnostic tool combining 'traceroute' and 'ping'
Description :
MTR combines the functionality of the 'traceroute' and 'ping' programs
in a single network diagnostic tool.

When MTR is started, it investigates the network connection between the
host MTR runs on and the user-specified destination host. Afterwards it
determines the address of each network hop between the machines and sends
a sequence of ICMP echo requests to each one to determine the quality of
the link to each machine. While doing this, it prints running statistics
about each machine.

MTR provides two user interfaces: an ncurses interface, useful for the
command line, e.g. for SSH sessions; and a GTK interface for X (provided
in the mtr-gtk package).
```

### What problem are you trying to solve with this package? Or what functionality does the package provide?

Debug network connectivity via traceroute

### Can the software provided by the package be run from a container?  Explain why or why not.

No, it requires either setuid or CAP_NET_RAW to run unprivileged.

### Can the tool(s) provided by the package be helpful in debugging container runtime issues?

No

### Can the tool(s) provided by the package be helpful in debugging networking issues?

Yes

### Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

Yes

### In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

It provides no services

### Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS?

No

### Does the software provided by the package have a history of CVEs?

No recent CVEs

**Comment by travier** [comment]
Given that it's easy to run from a container / toolbox, I'm -1. Isn't there anything else in the default tools available to do that?

**Comment by maddymeows** [comment]
I had issues running it from a container and ended up layering it to troubleshoot. `tracepath` exists but they're quite bare and only runs once instead of continuously.

**Comment by travier** [comment]
This worked for me:

```
$ sudo toolbox enter
# dnf install -y mtr
# mtr google.com
```

**Comment by prestist** [comment]
This was discussed in the meeting today, see below:
`AGREED: the basic functionality of mtr already exists in FCOS through tracepath. Additionally mtr can be installed and ran in a toolbox container. So we currently do not see the need to add this package to the base for everyone.  `

As a result of the meeting I am going to close this request.

Thank you again for your valuable input.

**Comment by maddymeows** [comment]
I got it working now thanks to a rootful container, rootless is probably why I couldn't get it working the first time around. I agree with the decision.
