### ISSUE TITLE
Switching architecture does not update the URLs on the website

### ISSUE THREAD

**Issue by lijian-cnsd** [coreos/fedora-coreos-tracker#1645]
### Describe the bug
https://fedoraproject.org/coreos/download?stream=stable&arch=aarch64#download_section
No matter what architecture you choose, the download url is x86_64.

### Reproduction steps

Select aarch64 and click download.

### Expected behavior

https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20231204.3.3/aarch64/fedora-coreos-39.20231204.3.3-live.aarch64.iso

### Actual behavior

https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20231204.3.3/x86_64/fedora-coreos-39.20231204.3.3-live.x86_64.iso

### System details

none

**Comment by travier** [comment]
The download links are indeed not correctly update for me until I refresh the page.

**Comment by travier** [comment]
Moved that issue to the website project: https://gitlab.com/fedora/websites-apps/fedora-websites/fedora-websites-3.0/-/issues/274

**Comment by dustymabe** [comment]
Fixed upstream by https://gitlab.com/fedora/websites-apps/fedora-websites/fedora-websites-3.0/-/merge_requests/951

Hasn't been rolled out to production yet, but should happen soon. As soon as some one confirms it working in production please do close this issue.

**Comment by travier** [comment]
Works well on the staging page: https://stg.fedoraproject.org/coreos/download?stream=stable

**Comment by dustymabe** [comment]
seems to be working now.
