### ISSUE TITLE
[rawhide][x86_64]: `root-reprovision.linear` kola test fails

### ISSUE THREAD

**Issue by gursewak1997** [coreos/fedora-coreos-tracker#1648]
`ext.config.root-reprovision.linear` fails with the mdadm error. This has been caused with the latest kernel change from 
`kernel 6.8.0-0.rc0.20240111gitde927f6c0b07.4.fc40 -> 6.8.0-0.rc0.20240112git70d201a40823.5.fc40`

```[   19.208322] ignition[1029]: disks: createRaids: op(1): [started]  waiting for devices [/dev/disk/by-id/virtio-disk1 /dev/disk/by-id/virtio-disk2]
[   19.216280] ignition[1029]: disks: createRaids: op(1): [finished] waiting for devices [/dev/disk/by-id/virtio-disk1 /dev/disk/by-id/virtio-disk2]
[   19.218194] ignition[1029]: disks: createRaids: created device alias for "/dev/disk/by-id/virtio-disk1": "/run/ignition/dev_aliases/dev/disk/by-id/virtio-disk1" -> "/dev/vda"
[   19.220269] ignition[1029]: disks: createRaids: created device alias for "/dev/disk/by-id/virtio-disk2": "/run/ignition/dev_aliases/dev/disk/by-id/virtio-disk2" -> "/dev/vdb"
[   19.221812] ignition[1029]: disks: createRaids: op(2): [started]  creating "foobar"
[   19.237356] md: personality for level -1 is not loaded!
[   19.237859] md: md127 stopped.
[   19.246186] ignition[1029]: disks: createRaids: op(2): [failed]   creating "foobar": exit status 1: 
Cmd: "mdadm" "--create" "foobar" "--force" "--run" "--homehost" "any" "--level" "linear" "--raid-devices" "2" "/run/ignition/dev_aliases/dev/disk/by-id/virtio-disk1" 
"/run/ignition/dev_aliases/dev/disk/by-id/virtio-disk2" Stdout: "mdadm: Defaulting to version 1.2 metadata\n" Stderr: "mdadm: RUN_ARRAY failed: Invalid argument\n"
[   19.253247] ignition[1029]: disks failed
[   19.253591] ignition[1029]: Full config:
[   19.253917] ignition[1029]: {
[[0;1;31mFAILED[0m] Failed to start [0;1;39mignition-disks.service[0m - Ignition (disks).
See 'systemctl status ignition-disks.service' for details.

**Comment by dustymabe** [comment]
Since this is only a single test failure and the rc kernel changes a lot during the merge window (i.e. this problem could be fixed in the next kernel update) let's instead keep the latest kernel (so we keep testing kernel updates that will be coming in multiple times a week) but denylist the test either with a short snooze (one week) or no snooze at all and just `warn: true`.

**Comment by marmijo** [comment]
It appears that md-linear has been deprecated for 2.5 years and was finally removed from the kernel.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v6.8-rc1&id=849d18e27be9a1253f2318cb4549cc857219d991

IIUIC, we could remove this test as linear raid is no longer be supported.

**Comment by marmijo** [comment]
However, md-linear is still available, although deprecated, in F39. We could denylist this test and only remove it when this change to the kernel is finally released in stable. What have we done in the past with changes like these?

**Comment by jlebon** [comment]
Nice work @marmijo!

Yeah, agree on dropping it. Not even sure we need to keep it running for RHCOS, but not against either!

**Comment by dustymabe** [comment]
+1 let's just drop it all around then.

**Comment by marmijo** [comment]
+1, I'll open a PR to drop it
