### ISSUE TITLE
Fedora 40 Changes: Enable IPv4 Address Conflict Detection by default

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1656]
For the [proposed Fedora 40 changes](https://github.com/coreos/fedora-coreos-tracker/issues/1626) we decided the following change needed action:

- [Enable IPv4 Address Conflict Detection by default](https://fedoraproject.org/wiki/Changes/Enable_IPv4_Address_Conflict_Detection)
     - Enable IPv4 Address Conflict Detection by default in NetworkManager.           
     - Tracking bug: [#2258083](https://bugzilla.redhat.com/show_bug.cgi?id=2258083)

Since this has the side effect of:

> Enabling ACD will cause an additional delay when bringing up interfaces, because NetworkManager needs first to probe the address. The delay is between 1.5 and 3 seconds, because RFC 5227 requires that the probe interval is randomized. The delay will affect both static and DHCP connections.

We may want to consider the implications of this in Fedora CoreOS.

**Comment by dustymabe** [comment]
Talked with @bengal about this change. He pointed out that the timeout value was adjusted from the original proposal from 3s down to 200ms. I think this alleviates some concern I had where in situations like cloud environments (tightly controlled, conflicts unlikely) we'd be paying a 1-3s penalty for no reason. 200ms seems much more reasonable.

**Comment by jlebon** [comment]
Copying a convo from Matrix:

jlebon: i guess technically we could disable it since it doesn't really make much sense for most cloud platforms. but we do want it in bare metal and some others (e.g. vmware), so simpler to just leave it on

dustymabe: right. with it being a much smaller timeout value I think I'm ok with the more simple, but slightly less ideal option of just accepting the change as is.

**Comment by dustymabe** [comment]
I'll close this out then unless you think it warrants meeting discussion. If so just re-open and add the meeting label.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `40.20240322.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `40.20240416.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `40.20240416.3.1`.
