### ISSUE TITLE
tracker: package additions/removals for F39

### ISSUE THREAD

**Issue by c4rt0** [coreos/fedora-coreos-tracker#1665]
This issue will help track package additions and removals when compared to the previous major version of Fedora. Usually, the additions/removals are a result of changing dependencies in named packages in our manifests. Most of the time the changes are intentional, but sometimes they can be unintended and we'd like to document changes and reasoning here.

- Removed:

- Added:

**Comment by jlebon** [comment]
Was this created by accident?

**Comment by c4rt0** [comment]
It wasn't an accident. As I was going through the main issue `tracker: Rebase onto Fedora 39` where I noticed the 'Open tickets to track related work for this release'. Should this be done in later stage?

**Comment by c4rt0** [comment]
I realized only today this wasn't necessary.
