### ISSUE TITLE
rawhide: ext.config.var-mount.scsi-id fails

### ISSUE THREAD

**Issue by c4rt0** [coreos/fedora-coreos-tracker#1670]
Kola test `ext.config.var-mount.scsi-id` is failing in Jenkins since Feb-13-2024 with the following error:
```
[2024-02-14T13:09:05.272Z] --- FAIL: ext.config.var-mount.scsi-id (56.26s)
[2024-02-14T13:09:05.272Z]         harness.go:1820: mach.Start() failed: machine 82d6a3cd-5a42-4c15-9b80-3f2439561b35 entered emergency.target in initramfs
```
Full console log of the jenkins job can be found [here](https://github.com/coreos/fedora-coreos-tracker/files/14281287/console.log).

When looking at the [console.txt](https://github.com/coreos/fedora-coreos-tracker/files/14297277/console.txt)  of the failed test we see:

```
[    5.964318] ignition[977]: Stage: disks
...
[    5.974301] ignition[977]: disks: createPartitions: op(1): [started]  waiting for devices [/dev/disk/by-id/scsi-0NVME_VirtualMultipath_disk1]
[    5.979497] systemd[1]: Expecting device dev-disk-by\x2did-scsi\x2d0NVME_VirtualMultipath_disk1.device - /dev/disk/by-id/scsi-0NVME_VirtualMultipath_disk1...
```

and further:

```
[51.057963] systemd[1]: dev-disk-by\x2did-scsi\x2d0NVME_VirtualMultipath_disk1.device: Job dev-disk-by\x2did-scsi\x2d0NVME_VirtualMultipath_disk1.device/start timed out.
[51.062464] ignition disks: createPartitions: op(1): [failed]   waiting for devices [/dev/disk/by-id/scsi-0NVME_VirtualMultipath_disk1]: device unit dev-disk-by\x2did-scsi\x2d0NVME_VirtualMultipath_disk1.device timeout
Failed to start ignition-disks.service Ignition (disks).

See 'systemctl status ignition-disks.service' for details.

Dependency failed for ignition-complete.target - Ignition Complete.

Dependency failed for initrd.target - Initrd Default Target.

[   51.072377] systemd[1]: Timed out waiting for device dev-disk-by\x2did-scsi\x2d0NVME_VirtualMultipath_disk1.device - /dev/disk/by-id/scsi-0NVME_VirtualMultipath_disk1.
[   51.076315] ignition[977]: disks failed
```

```
[   51.237327] ignition[977]: Ignition failed: create partitions failed: failed to wait on disks devs: device unit dev-disk-by\x2did-scsi\x2d0NVME_VirtualMultipath_disk1.device timeout
[   51.239411] systemd[1]: dev-disk-by\x2did-scsi\x2d0NVME_VirtualMultipath_disk1.device: Job dev-disk-by\x2did-scsi\x2d0NVME_VirtualMultipath_disk1.device/start failed with result 'timeout'.
```

**Comment by dustymabe** [comment]
denial/snooze for now while you investigate @c4rt0 https://github.com/coreos/fedora-coreos-config/pull/2854

**Comment by c4rt0** [comment]
Thank's for the denial @dustymabe. 
Here's the [console.txt](https://github.com/coreos/fedora-coreos-tracker/files/14296894/kola.tests.ext.config.var-mount.scsi-id_console.txt) for this test.

**Comment by jbtrystram** [comment]
I did a little bit of investigation here : 
the issue is that `udev` is not creating the expected symlink under `/dev/disk-by/id/` but i am not sure why this is happening.  There is definitely something going on with the latest release of systemd : 

systemd 254 
```
# udevadm info /dev/sda
P: /devices/pci0000:00/0000:00:03.0/virtio1/host2/target2:0:0/2:0:0:0/block/sda
M: sda
U: block
T: disk
D: b 8:0
N: sda
L: 0
S: disk/by-id/scsi-0NVME_VirtualMultipath_disk1
S: disk/by-id/scsi-SNVME_VirtualMultipath_disk1
S: disk/by-diskseq/2
S: disk/by-path/pci-0000:00:03.0-scsi-0:0:0:0
S: disk/by-id/wwn-0xa6c3213a36f94303
S: disk/by-id/scsi-3a6c3213a36f94303
Q: 2
E: DEVPATH=/devices/pci0000:00/0000:00:03.0/virtio1/host2/target2:0:0/2:0:0:0/block/sda
E: DEVNAME=/dev/sda
E: DEVTYPE=disk
E: DISKSEQ=2
E: MAJOR=8
E: MINOR=0
E: SUBSYSTEM=block
E: USEC_INITIALIZED=8423842
E: ID_SCSI=1
E: ID_VENDOR=NVME
E: ID_VENDOR_ENC=NVME\x20\x20\x20\x20
E: ID_MODEL=VirtualMultipath
E: ID_MODEL_ENC=VirtualMultipath
E: ID_REVISION=2.5+
E: ID_TYPE=disk
E: ID_SERIAL=3a6c3213a36f94303
E: ID_SERIAL_SHORT=a6c3213a36f94303
E: ID_WWN=0xa6c3213a36f94303
E: ID_WWN_WITH_EXTENSION=0xa6c3213a36f94303
E: ID_SCSI_SERIAL=disk1
E: ID_BUS=scsi
E: ID_PATH=pci-0000:00:03.0-scsi-0:0:0:0
E: ID_PATH_TAG=pci-0000_00_03_0-scsi-0_0_0_0
E: SCSI_TPGS=0
E: SCSI_TYPE=disk
E: SCSI_VENDOR=NVME
E: SCSI_VENDOR_ENC=NVME\x20\x20\x20\x20
E: SCSI_MODEL=VirtualMultipath
E: SCSI_MODEL_ENC=VirtualMultipath
E: SCSI_REVISION=2.5+
E: ID_SCSI_INQUIRY=1
E: SCSI_IDENT_SERIAL=disk1
E: SCSI_IDENT_LUN_VENDOR=disk1
E: SCSI_IDENT_LUN_NAA_LOCAL=a6c3213a36f94303
E: DEVLINKS=/dev/disk/by-id/scsi-0NVME_VirtualMultipath_disk1 /dev/disk/by-id/scsi-SNVME_VirtualMultipath_disk1 /dev/disk/by-diskseq/2 /dev/disk/by-path/pci-0000:00:03.0-scsi>
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

```

systemd 255 : 
```
# udevadm info /dev/sdb
udevadm info /dev/sdb
P: /devices/pci0000:00/0000:00:04.0/virtio2/host3/target3:0:0/3:0:0:0/block/sdb
M: sdb
U: block
T: disk
D: b 8:16
N: sdb
L: 0
S: disk/by-id/scsi-3ec07eb3b2cc71e61
S: disk/by-id/wwn-0xec07eb3b2cc71e61
S: disk/by-diskseq/3
S: disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
Q: 3
E: DEVPATH=/devices/pci0000:00/0000:00:04.0/virtio2/host3/target3:0:0/3:0:0:0/block/sdb
E: DEVNAME=/dev/sdb
E: DEVTYPE=disk
E: DISKSEQ=3
E: MAJOR=8
E: MINOR=16
E: SUBSYSTEM=block
E: USEC_INITIALIZED=7598873
E: ID_SCSI=1
E: ID_VENDOR=NVME
E: ID_VENDOR_ENC=NVME\x20\x20\x20\x20
E: ID_MODEL=VirtualMultipath
E: ID_MODEL_ENC=VirtualMultipath
E: ID_REVISION=2.5+
E: ID_TYPE=disk
E: ID_SERIAL=3ec07eb3b2cc71e61
E: ID_SERIAL_SHORT=ec07eb3b2cc71e61
E: ID_WWN=0xec07eb3b2cc71e61
E: ID_WWN_WITH_EXTENSION=0xec07eb3b2cc71e61
E: ID_SCSI_SERIAL=disk1
E: ID_BUS=scsi
E: ID_PATH=pci-0000:00:04.0-scsi-0:0:0:0
E: ID_PATH_TAG=pci-0000_00_04_0-scsi-0_0_0_0
E: SCSI_TPGS=0
E: SCSI_TYPE=disk
E: SCSI_VENDOR=NVME
E: SCSI_VENDOR_ENC=NVME\x20\x20\x20\x20
E: ID_SCSI_INQUIRY=1
E: SCSI_IDENT_SERIAL=disk1
E: SCSI_IDENT_LUN_VENDOR=disk1
E: SCSI_IDENT_LUN_NAA_LOCAL=ec07eb3b2cc71e61
E: DEVLINKS=/dev/disk/by-id/scsi-3ec07eb3b2cc71e61 /dev/disk/by-id/wwn-0xec07eb3b2cc71e61 /dev/disk/by-diskseq/3 /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

**Comment by jlebon** [comment]
Nice find! I would check for changes in udev rules (`/usr/lib/udev/rules.d`). Probably 60-persistent-storage.rules or one of the `*sg3*.rules` files.

**Comment by jbtrystram** [comment]
Thanks @jlebon  for the hint ! 
It looks like on 254 we hit this rule in `63-scsi-sg3_symlink.rules` : 
```
# 8: Vendor-specific identifier (prefix 0)
ENV{SCSI_IDENT_LUN_VENDOR}=="?*", ENV{DEVTYPE}=="disk", SYMLINK+="disk/by-id/scsi-0$env{SCSI_VENDOR}_$env{SCSI_MODEL}_$env{SCSI_IDENT_LUN_VENDOR}"
```

**Comment by jbtrystram** [comment]
Looks like we may be able to fix how cosa generates the [qemu args ](https://github.com/coreos/coreos-assembler/blob/main/mantle/platform/qemu.go#L1119)

**Comment by dustymabe** [comment]
I guess the question we have to ask ourselves is if this is behavior we think people are relying on or was it just behavior that was convenient that we were relying on for our tests?

If it's the former then we might need to engage upstream to fix it or at least consider the regression. If it's the latter then we can safely just change our usage and move on.

**Comment by jbtrystram** [comment]
I intuitively think people may rely on this, but they have "real" disks that would expose the values in the corrects fields and the issue is more on how QEMU "fakes" the disk. 
However i did a quick check on my PC and I only see `E` fields (i,e the same issue would occur) like a pasted above. My system is only SATA and NVME though, SCSI disk may be different I am not sure

**Comment by c4rt0** [comment]
To dig a little deeper on bare metal with 2 SAS drives I now installed F39 workstation. Following the sq3_utils installation I now get this output from `udevadm info /dev/sd*`


```
root@fedora-server:~# rpm -q sg3_utils
sg3_utils-1.46-6.fc39.x86_64
root@fedora-server:~# udevadm info /dev/sdd
P: /devices/pci0000:00/0000:00:01.0/0000:03:00.0/host10/target10:0:2/10:0:2:0/block/sdd
M: sdd
U: block
T: disk
D: b 8:48
N: sdd
L: 0
S: disk/by-id/wwn-0x5000c50041311ba3
S: disk/by-id/scsi-35000c50041311ba3
S: disk/by-diskseq/4
S: disk/by-id/scsi-SHP_MB2000FBZPN_Z1P1N4SL0000C2339WX8
S: disk/by-path/pci-0000:03:00.0-scsi-0:0:2:0
Q: 4
E: DEVPATH=/devices/pci0000:00/0000:00:01.0/0000:03:00.0/host10/target10:0:2/10:0:2:0/block/sdd
E: DEVNAME=/dev/sdd
E: DEVTYPE=disk
E: DISKSEQ=4
E: MAJOR=8
E: MINOR=48
E: SUBSYSTEM=block
E: USEC_INITIALIZED=10283330
E: ID_SCSI=1
E: ID_VENDOR=HP
E: ID_VENDOR_ENC=HP\x20\x20\x20\x20\x20\x20
E: ID_MODEL=MB2000FBZPN
E: ID_MODEL_ENC=MB2000FBZPN\x20\x20\x20\x20\x20
E: ID_REVISION=HPD4
E: ID_TYPE=disk
E: ID_SERIAL=35000c50041311ba3
E: ID_SERIAL_SHORT=5000c50041311ba3
E: ID_WWN=0x5000c50041311ba3
E: ID_WWN_WITH_EXTENSION=0x5000c50041311ba3
E: ID_SCSI_SERIAL=Z1P1N4SL0000C2339WX8
E: ID_BUS=scsi
E: ID_PATH=pci-0000:03:00.0-scsi-0:0:2:0
E: ID_PATH_TAG=pci-0000_03_00_0-scsi-0_0_2_0
E: SCSI_TPGS=0
E: SCSI_TYPE=disk
E: SCSI_VENDOR=HP
E: SCSI_VENDOR_ENC=HP\x20\x20\x20\x20\x20\x20
E: SCSI_MODEL=MB2000FBZPN
E: SCSI_MODEL_ENC=MB2000FBZPN\x20\x20\x20\x20\x20
E: SCSI_REVISION=HPD4
E: ID_SCSI_INQUIRY=1
E: SCSI_IDENT_SERIAL=Z1P1N4SL0000C2339WX8
E: SCSI_IDENT_LUN_NAA_REG=5000c50041311ba3
E: SCSI_IDENT_PORT_NAA_REG=5000c50041311ba1
E: SCSI_IDENT_PORT_RELATIVE=1
E: SCSI_IDENT_TARGET_NAA_REG=5000c50041311ba0
E: SCSI_IDENT_TARGET_NAME=naa.5000C50041311BA0
E: DEVLINKS=/dev/disk/by-id/wwn-0x5000c50041311ba3 /dev/disk/by-id/scsi-35000c50041311ba3 /dev/disk/by-diskseq/4 /dev/disk/by-id/scsi-SHP_MB2000FBZPN_Z1P1N4SL0000C2339WX8 /dev/disk/by->
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

root@fedora-server:~# udevadm info /dev/sde
P: /devices/pci0000:00/0000:00:01.0/0000:03:00.0/host10/target10:0:3/10:0:3:0/block/sde
M: sde
U: block
T: disk
D: b 8:64
N: sde
L: 0
S: disk/by-id/wwn-0x5000c50041324747
S: disk/by-id/scsi-SHP_MB2000FBZPN_Z1P1MTN70000C2345W6H
S: disk/by-id/scsi-35000c50041324747
S: disk/by-diskseq/5
S: disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0
Q: 5
E: DEVPATH=/devices/pci0000:00/0000:00:01.0/0000:03:00.0/host10/target10:0:3/10:0:3:0/block/sde
E: DEVNAME=/dev/sde
E: DEVTYPE=disk
E: DISKSEQ=5
E: MAJOR=8
E: MINOR=64
E: SUBSYSTEM=block
E: USEC_INITIALIZED=10283406
E: ID_SCSI=1
E: ID_VENDOR=HP
E: ID_VENDOR_ENC=HP\x20\x20\x20\x20\x20\x20
E: ID_MODEL=MB2000FBZPN
E: ID_MODEL_ENC=MB2000FBZPN\x20\x20\x20\x20\x20
E: ID_REVISION=HPD4
E: ID_TYPE=disk
E: ID_SERIAL=35000c50041324747
E: ID_SERIAL_SHORT=5000c50041324747
E: ID_WWN=0x5000c50041324747
E: ID_WWN_WITH_EXTENSION=0x5000c50041324747
E: ID_SCSI_SERIAL=Z1P1MTN70000C2345W6H
E: ID_BUS=scsi
E: ID_PATH=pci-0000:03:00.0-scsi-0:0:3:0
E: ID_PATH_TAG=pci-0000_03_00_0-scsi-0_0_3_0
E: ID_PART_TABLE_UUID=a435b335-daae-471c-8225-b5f3fa3dd50a
E: ID_PART_TABLE_TYPE=gpt
E: SCSI_TPGS=0
E: SCSI_TYPE=disk
E: SCSI_VENDOR=HP
E: SCSI_VENDOR_ENC=HP\x20\x20\x20\x20\x20\x20
E: SCSI_MODEL=MB2000FBZPN
E: SCSI_MODEL_ENC=MB2000FBZPN\x20\x20\x20\x20\x20
E: SCSI_REVISION=HPD4
E: ID_SCSI_INQUIRY=1
E: SCSI_IDENT_SERIAL=Z1P1MTN70000C2345W6H
E: SCSI_IDENT_LUN_NAA_REG=5000c50041324747
E: SCSI_IDENT_PORT_NAA_REG=5000c50041324745
E: SCSI_IDENT_PORT_RELATIVE=1
E: SCSI_IDENT_TARGET_NAA_REG=5000c50041324744
E: SCSI_IDENT_TARGET_NAME=naa.5000C50041324744
E: DEVLINKS=/dev/disk/by-id/wwn-0x5000c50041324747 /dev/disk/by-id/scsi-SHP_MB2000FBZPN_Z1P1MTN70000C2345W6H /dev/disk/by-id/scsi-35000c50041324747 /dev/disk/by-diskseq/5 /dev/disk/by->
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

**Comment by c4rt0** [comment]
The next step (after posting the above) was to run `rawhide` on this server and compare the results. Unfortunately during the cosa build process, my machine became unresponsive to the point that I could no longer produce what was intended (unrelated hardware issue).

**Comment by c4rt0** [comment]
> I guess the question we have to ask ourselves is if this is behavior we think people are relying on or was it just behavior that was convenient that we were relying on for our tests?
> 
> If it's the former then we might need to engage upstream to fix it or at least consider the regression. If it's the latter then we can safely just change our usage and move on.

How to find out if it's one or the other? What would be the next step here?

Let's say we start implementing the fix, considering it was convenient ...  rather quickly someone would express dissatisfaction - right?
I've been chewing all the above since yesterday and just to be transparent, at this stage I am not quite sure how to proceed.

**Comment by jlebon** [comment]
Mailing list thread for the upstream changes: https://listman.redhat.com/archives/dm-devel/2023-March/053645.html

The upstream changes seem reasonable to me but I would *not at all* be surprised if there are users/customers making use of the symlinks that are being removed. They would have to migrate to using the WWN-based ones, but if it's widespread enough, we (Fedora, Red Hat) might have to decide to re-enable some of those symlinks (or maybe only during upgrades e.g. [via LEAPP](https://github.com/oamg/leapp)). This will land in c10s soon also if it hasn't already and I think upgrade testing will also happen in that context at some point. I don't think there's a need to differ at the CoreOS level; we should just follow the distro.

I think `ext.config.var-mount.scsi-id` should be improved regardless. What it's testing is valid (verifying that `scsi-*` symlinks are created in the initramfs), but how it's testing it is an issue. It doesn't need to be a multipath device, I think that was just a convenient way to get a SCSI block device added to test the rules (probably based on [a suggestion from me](https://bugzilla.redhat.com/show_bug.cgi?id=1990506#c42)). But in fact, that hits one of the issues that the upstream change warns about (`/dev/disk/by-id/scsi-0NVME_VirtualMultipath_disk1` in that test is racy and can point to either `/dev/sda` or `/dev/sdb`). I think a better fix there is to support something like `5G:channel=scsi,wwn=...` and have kola actually attach the disk as a SCSI device instead of virtio-blk. Then the test would verify that an Ignition config can reference the `by-id/scsi-3$WWN` symlink (which matches what the reporter was trying to do in https://bugzilla.redhat.com/show_bug.cgi?id=1990506).

**Comment by jbtrystram** [comment]
Thanks @jlebon for the really detailed answer ! 

> Or maybe there is a better way to have QEMU attach the info to the device in way that comply with that rule

So i was not too far off there :) 
I'll cook up something based on your suggestion

**Comment by dustymabe** [comment]
A few PRs here that take care of this issue:

- https://github.com/coreos/coreos-assembler/pull/3772
- https://github.com/coreos/fedora-coreos-config/pull/2943
- https://github.com/coreos/fedora-coreos-config/pull/2964#event-12448509040
