### ISSUE TITLE
grub console settings with bootupd bootloader updates

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1671]
In the OSBuild workflow we are using bootupd to do the bootloader install along with `--with-static-configs` which will copy into place the files under `/usr/lib/bootupd/grub2-static/configs.d/` 

In https://github.com/coreos/fedora-coreos-config/pull/2769 we added the configs needed for CoreOS which included `30_console.cfg` with these contents:

```
$ cat 30_console.cfg 

# Any non-default console settings will be inserted here.
# CONSOLE-SETTINGS-START
# CONSOLE-SETTINGS-END
```

We then updated `coreos-installer` to [update that config](https://github.com/coreos/coreos-installer/pull/1360) with the platform specific console settings (i.e. like a find/replace on `CONSOLE-SETTINGS-START`/`CONSOLE-SETTINGS-END`) and are in the process of [adding a stage to OSBuild](https://github.com/osbuild/osbuild/pull/1589) that will do the same.

However, a really good question here is what will happen on these provisioned machines the next time the bootloader is updated? Will `/boot/grub2/30_console.cfg` just get overwritten by `bootupd` with the static version that is in `/usr/lib/bootupd/grub2-static/configs.d/30_console.cfg`, thus losing the applied console settings?

We may need to adjust our strategy to have the static config be something like:

```
if [ -f console.cfg ]; then
  source console.cfg
fi
```

and then have our disk building processes (not `bootupd`) create `console.cfg` with:

```
# Any non-default console settings will be inserted here.
# CONSOLE-SETTINGS-START
# CONSOLE-SETTINGS-END
```

This ticket came out of a conversation I had with @travier

**Comment by dustymabe** [comment]
> bootupd doesn't support updating the static configs right now, though it should.

Right. I imagine a future where we want that in which case the current structure that we have (per the description above) is going to be lossy.

**Comment by travier** [comment]
Ah, https://github.com/coreos/bootupd/pull/609 only does the tracking, not the updating part. I had misunderstood that.

**Comment by dustymabe** [comment]
@travier right. Either way let's assume that one day the static grub configs will get updated. Since nothing has shipped that uses `bootupd --with-static-configs` yet let's go ahead and perform a little musical chairs so we'll succeed either way.

Here is one proposal:

- [] rename [30_console.cfg](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/40grub/usr/lib/bootupd/grub2-static/configs.d/30_console.cfg) to `30_console-source.cfg` and update it to conditionally source in `console.cfg` if it exists.
- [] update `coreos-installer` to look for `console.cfg` rather than `30_console.cfg`
    - see https://github.com/coreos/coreos-installer/pull/1360
- [] update `coreos-assembler` to look for `console.cfg` rather than `30_console.cfg`
    - see https://github.com/coreos/coreos-assembler/commit/9688318cd9fd5017edc9796d3b5dc4c84e1b18f6
- [] update the new coreos.platform OSBuild stage to create `console.cfg`
    - https://github.com/osbuild/osbuild/pull/1589


Another proposal would be making `console.cfg` a more official thing within `bootupd`. by making the `if exists then source console.cfg` part one of `bootupd's builtin static configs.

- [] update bootupd to conditionally source in `console.cfg` in one or more of the files in https://github.com/coreos/bootupd/tree/main/src/grub2
- [] delete [30_console.cfg](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/40grub/usr/lib/bootupd/grub2-static/configs.d/30_console.cfg)
- [] update `coreos-installer` to look for `console.cfg` rather than `30_console.cfg`
    - see https://github.com/coreos/coreos-installer/pull/1360
- [] update `coreos-assembler` to look for `console.cfg` rather than `30_console.cfg`
    - see https://github.com/coreos/coreos-assembler/commit/9688318cd9fd5017edc9796d3b5dc4c84e1b18f6
- [] update the new coreos.platform OSBuild stage to create `console.cfg`
    - https://github.com/osbuild/osbuild/pull/1589

**Comment by travier** [comment]
Making part of the main bootupd config seems reasonable as well as it's definitely something that will be used on all platforms.

**Comment by cgwalters** [comment]
The second one seems sane to me.  One thing to bear in mind is that bootupd is also now used by anaconda if present, and ultimately I think we want to align the behavior and logic of console configuration with that too (the overlap/dup between osbuild/anaconda is another thread).

**Comment by dustymabe** [comment]
OK. Copying forward the proposal and starting to work on the checklist:

- [ ] update bootupd to conditionally source in `console.cfg` in one or more of the files in https://github.com/coreos/bootupd/tree/main/src/grub2
- [ ] delete [30_console.cfg](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/40grub/usr/lib/bootupd/grub2-static/configs.d/30_console.cfg)
- [ ] update `coreos-installer` to look for `console.cfg` rather than `30_console.cfg`
    - see https://github.com/coreos/coreos-installer/pull/1360
- [ ] update `coreos-assembler` to look for `console.cfg` rather than `30_console.cfg`
    - see https://github.com/coreos/coreos-assembler/commit/9688318cd9fd5017edc9796d3b5dc4c84e1b18f6
- [ ] update the new coreos.platform OSBuild stage to create `console.cfg`
    - https://github.com/osbuild/osbuild/pull/1589

**Comment by dustymabe** [comment]
Updated https://github.com/coreos/fedora-coreos-tracker/issues/1671#issuecomment-1952749649 with links to:

- https://github.com/coreos/coreos-installer/pull/1423
- https://github.com/coreos/bootupd/pull/619
- https://github.com/coreos/fedora-coreos-config/pull/2861
- https://github.com/coreos/coreos-assembler/pull/3738
- https://github.com/osbuild/osbuild/pull/1589

**Comment by dustymabe** [comment]
I think I can close this out now.
