### ISSUE TITLE
Images since Fedora 40 branched are confused about whether they're 40 or 41

### ISSUE THREAD

**Issue by AdamWill** [coreos/fedora-coreos-tracker#1673]
### Describe the bug

Since Fedora 40 branched from Rawhide, FCOS "40" images are confused about whether they're 40 or 41. They have 40 in the filenames, but various attributes in `/etc/os-release` say 41.

### Reproduction steps

1. Deploy a system from an FCOS 40 image since 40 branched, e.g. https://builds.coreos.fedoraproject.org/prod/streams/rawhide/builds/40.20240215.91.0/x86_64/fedora-coreos-40.20240215.91.0-live.x86_64.iso
2. Boot the installed system and examine `/etc/os-release`

### Expected behavior

All entries should be consistent with a Fedora 40 environment

### Actual behavior

Several aren't:

    VERSION should be 40.20240215.91.0 (CoreOS Prerelease) and is 41 (CoreOS Prerelease)
    VERSION_ID should be 40 and is 41
    PLATFORM_ID should be platform:f40 and is platform:f41
    PRETTY_NAME should be Fedora CoreOS 40.20240215.91.0 and is Fedora CoreOS 41
    REDHAT_BUGZILLA_PRODUCT_VERSION should be 40 and is rawhide
    REDHAT_SUPPORT_PRODUCT_VERSION should be 40 and is rawhide at fedora/tests/os_release.pm line 190.

### System details

fedora-coreos-40.20240215.91.0-live.x86_64.iso

**Comment by dustymabe** [comment]
fix in https://github.com/coreos/fedora-coreos-config/pull/2855#pullrequestreview-1883411177

**Comment by dustymabe** [comment]
This should be resolved now. Please let re-open if that's not the case.
