### ISSUE TITLE
client-side error: failed to decode graph: request or response body error: operation timed out

### ISSUE THREAD

**Issue by ChenQi1989** [coreos/fedora-coreos-tracker#1682]
# Bug Report #
Mar 01 03:33:13 localhost.localdomain zincati[1854]: [INFO  zincati::strategy] update strategy: immediate
Mar 01 03:33:13 localhost.localdomain zincati[1854]: [INFO  zincati::update_agent::actor] reached steady state, periodically polling for updates
Mar 01 03:33:13 localhost.localdomain systemd[1]: Started zincati.service - Zincati Update Agent.
Mar 01 03:33:15 localhost.localdomain zincati[1854]: [INFO  zincati::cincinnati] current release detected as not a dead-end
Mar 01 04:45:43 localhost.localdomain zincati[1854]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: failed to decode graph: request or response body error: operation timed out

## Environment ##
Ubuntu 22.04

What hardware/cloud provider/hypervisor is being used?
qemu

## Expected Behavior ##
No error.

## Actual Behavior ##
Mar 01 04:45:43 localhost.localdomain zincati[1854]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: failed to decode graph: request or response body error: operation timed out

## Reproduction Steps ##

  1. podman run --pull=always --rm -v `pwd`:/data -w /data quay.io/coreos/coreos-installer:release download -s stable -p qemu -f qcow2.xz - -decompress
  2. boot the qemu image
  3. systemctl status zincati

## Other Information ##
[root@localhost ~]# cat /etc/os-release 
NAME="Fedora Linux"
VERSION="39.20240210.3.0 (CoreOS)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora CoreOS 39.20240210.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='39.20240210.3.0'

**Comment by jlebon** [comment]
@ChenQi1989 Yeah, it doesn't have anything quite that explicit, but it'd make sense. The "reached steady state, periodically pooling for updates" means it's healthy and will update the machine if there are any updates (your node is already on the latest stable release).

**Comment by ChenQi1989** [comment]
@jlebon  Thanks for your reply.
Returning today and checking the logs again, I found it's giving me the same error again. It tells me 'Name or service not known'. 
Is it some server/client mismatch? I used coreos-installer to download the image, and made no modification. See logs below. If you have any suggestion how to proceed with this error, that would be best.

Mar 01 09:15:17 localhost.localdomain zincati[1688]: [INFO  zincati::cincinnati] current release detected as not a dead-end
Mar 01 09:57:25 localhost.localdomain zincati[1688]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: error sending request for url (https://updates.coreos.fedoraproject.org/v1/graph?node_uuid=acf99ad680624688a2b5bfcd13f8c0aa&platform=qemu&stream=stable&os_version=39.20240210.3.0&os_checksum=9ee1cb0963e253a2864c69a9450c8e3dd91b50b47f97389be0393c1db567dd5e&group=default&basearch=x86_64): error trying to connect: dns error: failed to lookup address information: Name or service not known
Mar 01 18:19:47 localhost.localdomain zincati[1688]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: error sending request for url (https://updates.coreos.fedoraproject.org/v1/graph?basearch=x86_64&platform=qemu&stream=stable&os_checksum=9ee1cb0963e253a2864c69a9450c8e3dd91b50b47f97389be0393c1db567dd5e&os_version=39.20240210.3.0&group=default&node_uuid=acf99ad680624688a2b5bfcd13f8c0aa): error trying to connect: dns error: failed to lookup address information: Name or service not known
Mar 01 18:40:44 localhost.localdomain zincati[1688]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: error sending request for url (https://updates.coreos.fedoraproject.org/v1/graph?platform=qemu&stream=stable&os_checksum=9ee1cb0963e253a2864c69a9450c8e3dd91b50b47f97389be0393c1db567dd5e&node_uuid=acf99ad680624688a2b5bfcd13f8c0aa&os_version=39.20240210.3.0&basearch=x86_64&group=default): error trying to connect: dns error: failed to lookup address information: Name or service not known
Mar 01 18:56:33 localhost.localdomain zincati[1688]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: error sending request for url (https://updates.coreos.fedoraproject.org/v1/graph?basearch=x86_64&os_checksum=9ee1cb0963e253a2864c69a9450c8e3dd91b50b47f97389be0393c1db567dd5e&platform=qemu&stream=stable&os_version=39.20240210.3.0&group=default&node_uuid=acf99ad680624688a2b5bfcd13f8c0aa): error trying to connect: dns error: failed to lookup address information: Name or service not known
Mar 03 19:49:19 localhost.localdomain zincati[1688]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: error sending request for url (https://updates.coreos.fedoraproject.org/v1/graph?stream=stable&basearch=x86_64&node_uuid=acf99ad680624688a2b5bfcd13f8c0aa&os_version=39.20240210.3.0&platform=qemu&os_checksum=9ee1cb0963e253a2864c69a9450c8e3dd91b50b47f97389be0393c1db567dd5e&group=default): error trying to connect: dns error: failed to lookup address information: Name or service not known
Mar 03 22:46:47 localhost.localdomain zincati[1688]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: error sending request for url (https://updates.coreos.fedoraproject.org/v1/graph?node_uuid=acf99ad680624688a2b5bfcd13f8c0aa&platform=qemu&group=default&os_checksum=9ee1cb0963e253a2864c69a9450c8e3dd91b50b47f97389be0393c1db567dd5e&os_version=39.20240210.3.0&stream=stable&basearch=x86_64): operation timed out
Mar 04 00:45:49 localhost.localdomain zincati[1688]: [ERROR zincati::cincinnati] failed to check Cincinnati for updates: client-side error: failed to decode graph: request or response body error: operation timed out
[root@localhost ~]# ping updates.coreos.fedoraproject.org
PING wildcard.fedoraproject.org (34.221.3.152) 56(84) bytes of data.
64 bytes from ec2-34-221-3-152.us-west-2.compute.amazonaws.com (34.221.3.152): icmp_seq=1 ttl=255 time=174 ms
64 bytes from ec2-34-221-3-152.us-west-2.compute.amazonaws.com (34.221.3.152): icmp_seq=2 ttl=255 time=176 ms
64 bytes from ec2-34-221-3-152.us-west-2.compute.amazonaws.com (34.221.3.152): icmp_seq=3 ttl=255 time=174 ms

--- wildcard.fedoraproject.org ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 174.098/174.764/175.814/0.751 ms

**Comment by travier** [comment]
There is nothing to do here. Those are intermittent errors and Zincati retries regularly.
