### ISSUE TITLE
s390x: sgdisk sometimes flakes during disk reprovision tests

### ISSUE THREAD

**Issue by jschintag** [coreos/fedora-coreos-tracker#1683]
When running kola tests on fcos rawhide stream on s390x, sometimes tests are failing with the error:
```
[   24.182309] ignition[950]: disks: createPartitions: op(2): [started]  partitioning "/run/ignition/dev_aliases/dev/vda"

[   24.182339] ignition[950]: disks: createPartitions: op(2): op(3): [started]  reading partition table of "/run/ignition/dev_aliases/dev/vda"

[   24.182761] ignition[950]: disks: createPartitions: op(2): op(3): [finished] reading partition table of "/run/ignition/dev_aliases/dev/vda"

[   24.182807] ignition[950]: disks: createPartitions: op(2): running sgdisk with options: [--pretend --new=4:0:+1048576 --new=5:0:+0 /run/ignition/dev_aliases/dev/vda]

[   24.185900] ignition[950]: disks: createPartitions: op(2): [failed]   partitioning "/run/ignition/dev_aliases/dev/vda": Failed to pretend to create partitions. Err: exit status 2. Stderr:
```
Last seen in https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build-arch/3589, during `ext.config.var-mount.simple`

[ext.config.var-mount.simple.zip](https://github.com/coreos/fedora-coreos-tracker/files/14556007/ext.config.var-mount.simple.zip)

**Comment by jlebon** [comment]
Did you attach the right file? I don't see that snippet of logs in there. It seems like the job passed.

Also, in the job linked, it didn't fail on `ext.config.root-reprovision.filesystem-only`.  (It failed earlier so never go to the `--tag reprovision` run.)

**Comment by jschintag** [comment]
> Did you attach the right file? I don't see that snippet of logs in there. It seems like the job passed.
> 
> Also, in the job linked, it didn't fail on `ext.config.root-reprovision.filesystem-only`. (It failed earlier so never go to the `--tag reprovision` run.)

Good catch, i think it also happened during that test in an earlier/later run and i got confused. I changed the text and uploaded the correct test output...

**Comment by jlebon** [comment]
Can you test https://github.com/coreos/fedora-coreos-config/pull/2892 ?
