### ISSUE TITLE
F40 FCOS Test Week on April 1

### ISSUE THREAD

**Issue by aaradhak** [coreos/fedora-coreos-tracker#1685]
## Initial Tasks (to be done at least one week before test week)

- [x] Open this ticket in the `fedora-coreos-tracker` repo
- [x] Open a ticket with [Fedora QA](https://pagure.io/fedora-qa/issues).
  - [F39 example](https://pagure.io/fedora-qa/issue/727)

To be done after the Fedora QA folks have taken action on the QA ticket:

- [x] Confirm the Test Day page is created on the Fedora Wiki.
  - For example: <https://fedoraproject.org/wiki/Test_Day:Fedora_39_CoreOS>
- [x] Confirm the Test Day results app is created.
  - For example: <https://testdays.fedoraproject.org/events/159>
- [x] Choose a day during the Test Week to host a video session for live debug help
- [x] Setup a Google Meet or other video conference session
- [x] Create a HackMD doc for capturing notes during live video session
- [x] Find volunteers to enumerate new documentation + test cases required for Test Week
  - Best done via dedicated video session
- [x] File an issue on `fedora-coreos-tracker` with TODO items.
  - https://github.com/coreos/fedora-coreos-tracker/issues/1686
- [x] As the Badges dustymabe ravanelli to give the badges to people who helped in the test week
  

## Announcing Test Week

Should be completed after the Initial Tasks are done

- [x] Draft an email to <coreos@lists.fedoraproject.org> announcing the Test Week
  - [x] Include a link to the Fedora Wiki
  - [x] Include a link to the Test Day results app
  - [x] Include a link to `fedora-coreos-tracker` for Test Week
  - [x] Include a link to the video conference
  - [x] Include a link to the HackMD doc
- [x] Cross-post announcement email to discussion.fedoraproject.org with `#coreos` tag

- Example format: <https://hackmd.io/lCrVoW_RSMCRf2neiGhiPg>

## During Test Week

- Monitor `fedora-coreos-tracker` for new issues reported as part of Test Week
- Monitor #fedora-coreos on IRC for new issues reported as part of Test Week
- Ensure there is one or more representatives of Fedora CoreOS team present for live video session

## After Test Week

- [x] Update `fedora-coreos-tracker` ticket with any issues found
- [x] Update `fedora-coreos-tracker` ticket with any documentation updates made
- [x] Review Test Day results app and follow-up on any errors reported, if possible
- [x] Follow up with the Fedora Badges ticket with Fedora Account System (FAS) usernames that participated in Test Week

**Comment by yasminvalim** [comment]
During the FCOS meeting, we decided to gather a group for a meeting on Friday (03/08) to determine if there are any missing documents or test cases, or if any need updating for the F40 Test Week on 03/18.

**Comment by aaradhak** [comment]
Fedora QA ticket - https://pagure.io/fedora-qa/issue/767

**Comment by aaradhak** [comment]
From the discussion today regarding the fedora test week, it is decided that we push the test week to March 25 as the podman test week is scheduled to happen around the week of March 18.  FCOS will overlap on Podman5 and Podman desktop. To avoid any regression issue, we decided to move the test week to March 25.

**Comment by sumantro93** [comment]
Wiki :  https://fedoraproject.org/wiki/Test_Day:Fedora_40_CoreOS
Test Day App : https://testdays.fedoraproject.org/events/179
Fedocal : https://calendar.fedoraproject.org/meeting/10760/ ( I'll be adding the videomeeting links when they are ready)

I will be taking care of disc.fp.o , fedoramagazine and other relevant marketing activities

**Comment by c4rt0** [comment]
Hackmd related to test cases: https://hackmd.io/nhLcXDbZTcWTzkvQAcUwtA

**Comment by sumantro93** [comment]
I have created a stub for Microsoft Hyper V TC : https://fedoraproject.org/wiki/QA:Testcase_windows_hyper_V_fcos

**Comment by aaradhak** [comment]
The Fedora test week might need to be pushed again by a week to the first week of April as the F40 Beta has shifted the target date to 2024-03-26. The test week should be scheduled after this.  

https://meetbot.fedoraproject.org/meeting_matrix_fedoraproject-org/2024-03-14/f40-beta-go-no-go-meeting.2024-03-14-17.01.html

**Comment by sumantro93** [comment]
So are we moving to 1st april to 7th ? @aaradhak

**Comment by aaradhak** [comment]
> So are we moving to 1st april to 7th ? @aaradhak

The test week is now rescheduled to be held between April 1st - April 5th, 2024.

**Comment by aaradhak** [comment]
> So are we moving to 1st april to 7th ? @aaradhak

Yes, the Fedora test week is rescheduled to happen between April 1st - 7th.

**Comment by sumantro93** [comment]
is everything ready here? do we have a gmeet link? can anyone send out invites? any new test case I can add to the test day app?

**Comment by sumantro93** [comment]
@jlebon @aaradhak ^^

**Comment by c4rt0** [comment]
Hey @sumantro93 -  AFAIK, @aaradhak sent out [an announcement](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/TF4BOBY5U7BZAXOLAJYW35J4OA52NFWL/) already. It contains the [google meet link](https://meet.google.com/uwb-enhy-evg?authuser=0).

**Comment by c4rt0** [comment]
Do you have any other invitations in mind?

**Comment by sumantro93** [comment]
Ahh I will fwd that on @test list and @test annouce

**Comment by aaradhak** [comment]
Fedora badge ticket - https://pagure.io/fedora-badges/issue/930

**Comment by ravanelli** [comment]
I already have a list of badges, https://pagure.io/fedora-badges/issue/917 Me or @dustymabe should be able to grant access. Let's update the template for the next time we don't need to open a ticket for it
