### ISSUE TITLE
Update all repos to peter-evans/create-pull-request@v6.0.2

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#1699]
We're [hitting](https://github.com/coreos/fedora-coreos-config/actions/runs/8407304866/job/23022122891) a [known issue](https://github.com/peter-evans/create-pull-request/issues/2790) that has been [fixed in v6.0.1](https://github.com/peter-evans/create-pull-request/issues/2790#issuecomment-1967972220).

All instances where we use this action: https://github.com/search?q=org%3Acoreos+%22uses%3A+peter-evans%2Fcreate-pull-request%22&type=code

None of the [breaking changes](https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md) should affect us, so we should be good to just bump to v6.0.2.

**Comment by travier** [comment]
Ideally, we should depandabot as well to get those updates in automatically. Example in https://github.com/travier/fedora-kinoite/blob/main/.github/dependabot.yml

**Comment by travier** [comment]
We can likely use https://github.com/coreos/repo-templates/tree/main/dependabot to do that.

**Comment by jlebon** [comment]
> Ideally, we should setup depandabot as well to get those updates in automatically. Example in [travier/fedora-kinoite@`main`/.github/dependabot.yml](https://github.com/travier/fedora-kinoite/blob/main/.github/dependabot.yml?rgh-link-date=2024-03-26T11%3A00%3A15Z)

Mayyybe. If it's bumping across major versions, you can't just merge as is. You have to check what breaking changes happened and verify that it doesn't apply to you. And of course for the workflows we're talking about here, it's not really tested by CI.

If it's bumping within major versions, then we don't need Dependabot for that; we just have to pin to a major version and not be more specific (e.g. `peter-evans/create-pull-request@v6`).

**Comment by aaradhak** [comment]
So do we just bump to `peter-evans/create-pull-request@v6.0.2` without setting up the dependabot ? 

> > Ideally, we should setup depandabot as well to get those updates in automatically. Example in [travier/fedora-kinoite@`main`/.github/dependabot.yml](https://github.com/travier/fedora-kinoite/blob/main/.github/dependabot.yml?rgh-link-date=2024-03-26T11%3A00%3A15Z)
> 
> Mayyybe. If it's bumping across major versions, you can't just merge as is. You have to check what breaking changes happened and verify that it doesn't apply to you. And of course for the workflows we're talking about here, it's not really tested by CI.
> 
> If it's bumping within major versions, then we don't need Dependabot for that; we just have to pin to a major version and not be more specific (e.g. `peter-evans/create-pull-request@v6`).

**Comment by jlebon** [comment]
> So do we just bump to `peter-evans/create-pull-request@v6.0.2` without setting up the dependabot ?

How about for now bumping to `peter-evans/create-pull-request@v6`? That'll give us minor version tracking and we could down the line set up Dependabot for major version bumps if we feel it's worth it.

**Comment by jlebon** [comment]
@aaradhak All of those PRs are bumping the GHA to v6.0.2, but in https://github.com/coreos/fedora-coreos-tracker/issues/1699#issuecomment-2046464852, my suggestion was to bump to v6 instead. Was that on purpose?

**Comment by aaradhak** [comment]
@jlebon I was trying to look into the difference between v6.0.2 and v6.0.0. 
I have updated to v6.0.0 now.

**Comment by jlebon** [comment]
This is done now. Thanks @aaradhak!
