### ISSUE TITLE
google-compute-engine-guest-configs-udev has been retired in Fedora

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1702]
We [include](https://github.com/coreos/fedora-coreos-config/blob/e656b31ddca883f73c2359c73790562840059732/manifests/fedora-coreos-base.yaml#L178-L186) this package in our manifest lists and it has been retired.

See https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/U27BIXM34W52TVUV327XJHD5BRTLZMXM/

This is now causing `rawhide` stream builds to fail.

**Comment by travier** [comment]
https://src.fedoraproject.org/rpms/google-compute-engine-guest-configs is still owned by Major and has Neal as second owner.
