### ISSUE TITLE
Download web page shows v 40.20240408.1.0 but the release notes are missing

### ISSUE THREAD

**Issue by eriksjolund** [coreos/fedora-coreos-tracker#1707]
### Describe the bug

The download web page shows the release  v 40.20240408.1.0 but the release notes web page has no release notes for this release.

### Reproduction steps

1. Go to https://fedoraproject.org/coreos/download?stream=next&arch=aarch64#download_section
   The web page shows the text _v 40.20240408.1.0_
2. Go to https://fedoraproject.org/coreos/release-notes?arch=aarch64&stream=next
    The web page does not show the release notes for _v 40.20240408.1.0_

### Expected behavior

In step 2 I would have expected to see the release notes.

### Actual behavior

In step 2 I did not see the release notes.

### System details

web browser Google Chrome `Version 123.0.6312.124 (Official Build) (arm64)`

### Butane or Ignition config

```yaml
n/a
```

**Comment by travier** [comment]
Looks like something is broken on the website indeed as it should display the release with the "Pending release notes" text: https://gitlab.com/fedora/websites-apps/fedora-websites/fedora-websites-3.0

**Comment by dustymabe** [comment]
This should fix it: https://github.com/coreos/fedora-coreos-streams/pull/885

Thanks for the report.

**Comment by travier** [comment]
Looks like this fixed it: https://fedoraproject.org/coreos/release-notes?arch=x86_64&stream=next

Thanks!
