### ISSUE TITLE
Mantle support for Ignition spec 3.0.0

### ISSUE THREAD

**Issue by arithx** [coreos/fedora-coreos-tracker#172]
We'd like to continue using Mantle / kola for developer tooling & image based testing in Fedora CoreOS. Currently Mantle does not support Ignition spec 3.0.0 (https://github.com/coreos/mantle/issues/974).

Notable changes required:
- [ ] switch mantle to go modules (so Ignition v0 & v2 can be imported at the same time)
- [ ] add spec 3.0.0 test configs for all tests that should run on *COS machines
- [ ] create runner mechanism for switching between spec 2 & 3 configs depending on the distribution under test (or an override cmdline flag)
- [ ] update `platform/conf` helper functions to support 3.0.0

**Comment by dustymabe** [comment]
Thanks @arithx - @ajeddeloh !
