### ISSUE TITLE
2079.3.0 did have changes -- all network device names were renamed

### ISSUE THREAD

**Issue by gigatexal** [coreos/fedora-coreos-tracker#173]
https://coreos.com/releases/#2079.3.0 states no changes in the release notes but our BGP networking which relies on static or known device names blew up upon upgrading to the latest stable version (2079.3.0).

**Comment by lucab** [comment]
@gigatexal I think you wanted to report this to https://github.com/coreos/bugs, can you please direct your tickets there, with details about your environment and config?

Moreover, that version is a stable promotion without changes with regards to the beta-channel version (2079.2.0). Are you reporting that the same breaking behavior is not observable on your beta and alpha nodes at 2079.x.x?

**Comment by gigatexal** [comment]
No, the stable image renamed the network device ids which would have saved us downtime had we known that was going to happen.

**Comment by bgilbert** [comment]
Closing in favor of https://github.com/coreos/bugs/issues/2578.
