### ISSUE TITLE
Add testing for kdump over network

### ISSUE THREAD

**Issue by jbtrystram** [coreos/fedora-coreos-tracker#1753]
We could host {SSH,NFS} server into a container like the [tang test](https://github.com/coreos/coreos-assembler/blob/main/mantle/kola/tests/ignition/luks.go) as well but the main issue i see is that in this scenario we need to : 

- start the NFS server (host 1)
- start a coreOS VM with kdump pointing to that NFS server (host 2), then crash it: `echo c > /proc/sysreq-trigger`
- **Check if logs are created into nfs source (host 1)** - this is the tricky part.

So that requires access on two separate instances. We could nest them as we do in the iscsi tests, but that's very expensive as it requires pulling COSA and doing an installation each time. it's justifiable in the iSCSI case but i am not sure for kdump.

I haven't read too much into the tang test so I don't know if that's feasible. Quickly looking at the tang test it seems it's just a case of "create a container with some config"

**Comment by jbtrystram** [comment]
hmmm maybe a way to validate the test would be to simply crash the VM, wait for reboot, mount the NFS destination again and look for the expected files. 

This way the source server would be just a "fire and forget" container like the tang test

**Comment by mike-nguyen** [comment]
Why can't we access both machines during the test?

**Comment by travier** [comment]
I vaguely remember that there are options for running multiple systems with kola.

Or we could have the first VM export an NFS mount, then start a VM inside it and point it to the host NFS, crash it and wait on the host for reboot to see if the crash dump is in the NFS mount?

**Comment by jbtrystram** [comment]
> Or we could have the first VM export an NFS mount, then start a VM inside it and point it to the host NFS, crash it and wait on the host for reboot to see if the crash dump is in the NFS mount?

Starting a VM inside the NFS host is the same approach as the iscsi test, as I mentioned it's very expensive in term of bandwidth and make the test quite long..

**Comment by mike-nguyen** [comment]
I think you should be able to access both VMs in kola.  If I recall correctly, the tang test sets up one machine with tang running as a container and another machine to use the first machine to decrypt with the tang fingerprint

**Comment by jlebon** [comment]
> I think you should be able to access both VMs in kola.

Agreed, I think the same setup as Tang should work there with port forwarding. It'd be nice to try to do this with the iSCSI tests too, but I think it'd require some finagling to satisfy IP-related requirements (related: https://github.com/coreos/coreos-assembler/pull/3645).

**Comment by jbtrystram** [comment]
Reopening this as we should consider testing kdump over NFS as well

**Comment by jlebon** [comment]
> Reopening this as we should consider testing kdump over NFS as well

Not against this, but also not really looking forward to have the team have to learn about NFS servers just for maintaining tests for this (whereas ssh is very familiar to most people).

How much value does this extra coverage bring vs the ssh one? Aren't they mostly on equal footing in the sense that our initrd by default doesn't include ssh?

(Anyway again, not blocking this.)

**Comment by jbtrystram** [comment]
> How much value does this extra coverage bring vs the ssh one? Aren't they mostly on equal footing in the sense that our initrd by default doesn't include ssh?

I am not sure, I think NFS requires an extra kernel module to load but that's just an additional line in kdump config file. 
I you think it's not worth it i'll happily follow your advice and move on :)

**Comment by jlebon** [comment]
> > How much value does this extra coverage bring vs the ssh one? Aren't they mostly on equal footing in the sense that our initrd by default doesn't include ssh?
> 
> I am not sure, I think NFS requires an extra kernel module to load but that's just an additional line in kdump config file. I you think it's not worth it i'll happily follow your advice and move on :)

The intent is good. :) Just weighing the cost/benefit. We can always revisit if we think this would be very beneficial to cover.
