### ISSUE TITLE
NFS server cause kernel errors

### ISSUE THREAD

**Issue by Nemric** [coreos/fedora-coreos-tracker#1755]
### Describe the bug

When using a containerized nfs server, I'm facing kernel errors that should be fixed in future kernel according to this related error on bugzilla
https://bugzilla.redhat.com/show_bug.cgi?id=2282287#c12

I did just notice logs as side effects, many logs from prometheus node_exporter that wanted to access some nfs stats but nfs server did serve files as expected

I went back to kernel 6.8.9 with previous FCOS stable release files

This issue is for tracing purpose

### Reproduction steps

not so easy to reproduce, be confident in bugzilla issue :)

### Expected behavior

no errors

### Actual behavior

errors

### System details

Bare metal pxe booted stable release

**Comment by jlebon** [comment]
We've pinned to the 6.8 kernel for now due to roll out https://github.com/coreos/fedora-coreos-config/pull/3042 first. The 6.9 kernel should hit next and testing in two weeks, and stable two weeks after that.

**Comment by Nemric** [comment]
Did update to kernel 6.9.7 and I don't notice error logs, I think it's ok :)
