### ISSUE TITLE
Azure VHD images don't boot successfully

### ISSUE THREAD

**Issue by dghubble** [coreos/fedora-coreos-tracker#1757]
### Describe the bug

It's been a while since I tested FCOS Azure images, so I'm not sure when this regressed unfortunately. But it looks like just booting the Fedora CoreOS Azure image will always land in an emergency shell. 

### Reproduction steps

1. Upload Fedora CoreOS 40.20240616.3.0 Azure VHD image to storage account and make an image per https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-azure/
2. Create a VM via any mechanisms
3. The VM will never successfully create

### Expected behavior

Without any user-data, Fedora CoreOS should at least complete boot and the VM should be marked as successful in the Azure portal.

### Actual behavior

Originally I observed this in Typhoon, which supplies Ignition via user-data. However, in a simpler test, I can repro this just creating a VM throug the Azure portal with no user-data. The instance never completes the boot process.

Since I'm not able to get onto the box, the best I've found is to use Azure "boot diagnostics" to capture a screenshot of the serial console. Looks like `afterburn-hostname.service` gets a 404 not found and the boot drops to an emergency shell.

I suspect this has been happening since at least May 29, and folks don't test Azure much https://github.com/coreos/fedora-coreos-tracker/issues/1741

![Screenshot from 2024-07-07 22-49-04](https://github.com/coreos/fedora-coreos-tracker/assets/2253428/9c96d34a-c169-4554-9257-27b4a355a850)

### System details

- Azure / 40.20240616.3.0

### Butane or Ignition config

```yaml
Reproducible without any Ignition
```

**Comment by jlebon** [comment]
Hmm odd, not sure what's going on there. We do test Azure in CI, and I've verified that it passed on that same stable release.

Ohh, wait a second: "failed to get metadata JSON" is an error string that only occurs in the Azure Stack flow. Are you sure you're using the Azure image and not the Azure Stack one?

**Comment by dghubble** [comment]
You're totally right, I uploaded the Azure stack image it seems! I didn't realize there were two Azure images and don't really know what Azure stack is for. I'll use the regular image and re-open if I run into issues.

**Comment by dghubble** [comment]
Just to confirm here, yes, it was because of the wrong azure image.
