### ISSUE TITLE
Which case for FCCT

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/fedora-coreos-tracker#176]
The Fedora CoreOS Config Transpiler (FCCT) will read FCCs and emit Ignition configs (see https://github.com/coreos/fedora-coreos-tracker/issues/129). This mirrors how with Container Linux is configured with CLCs and the Container Linux Config Transpiler (CLCT).

Ignition uses `camelCase` in it's config currently. CLCT uses `snake_case`. We should pick one for FCCT.

I'm not what will be more confusing: using a different case than Ignition or being different than CLCT.

Worth calling out we _can_ change Ignition with a major spec bump, but that's a lot of churn and I'd like to avoid it if possible.

**Comment by dustymabe** [comment]
From the meeting today jonathan and I both had this opinion:

```
a slight preference for dash-case overall, but between camelCase and
snake_case i'd rather the latter

```

**Comment by ajeddeloh** [comment]
FWIW I also prefer snake case, though very weakly. Talking with @crawford he thinks using snake case with yaml and camel case with json is pretty standard. Snake case also is also what cloudinit uses, so that's a tiny bit less friction for those coming from cloudinit-land.

I'm going to close this out in favor of snake case by EOD friday if no one has a strong case the other way.

**Comment by ajeddeloh** [comment]
Closing in favor of `snake_case`
