### ISSUE TITLE
Keep `coreos-tutorials` repo in the `coreos` org and setup access

### ISSUE THREAD

**Issue by c4rt0** [coreos/fedora-coreos-tracker#1765]
[coreos-tutorials](https://github.com/coreos/coreos-tutorials) does not have the right access set up. Creating this issue to gather consensus on this change.

**Comment by travier** [comment]
+1

**Comment by c4rt0** [comment]
Thank you for the edit @travier. 

I second that.

**Comment by travier** [comment]
As no-one complained, I think we can move forward with this.
