### ISSUE TITLE
*-wrapper scripts for FCOS

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/fedora-coreos-tracker#178]
See discussion in the [FCOS community meeting](https://meetbot.fedoraproject.org/fedora-meeting-1/2019-05-15/fedora_coreos_meeting.2019-05-15-16.30.log.html).

Container Linux has several wrapper scripts for setting up things like [etcd](https://github.com/coreos/coreos-overlay/tree/master/app-admin/etcd-wrapper) and [flannel](https://github.com/coreos/coreos-overlay/tree/master/app-admin/flannel-wrapper). The [Container Linux Config Transpiler](https://github.com/coreos/container-linux-config-transpiler) supports sugar to configure those scripts.

Historically, container linux shipped with both `etcd` and `flannel` binaries in the system image, then migrated to these wrapper scripts.

1) Do we want to include wrapper scripts in FCOS?
2) Independent of shipping wrapper scripts, should FCCT support sugar for these?

My inclination is to *not* ship wrapper scripts but provide FCCT sugar that writes out an equivalent unit file(s). If users are using FCCT then the lack of wrapper script should be invisible. This does mean that we cannot update the units once the user has provisioned the machine.

**Comment by dustymabe** [comment]
> My inclination is to _not_ ship wrapper scripts

+1

> but provide FCCT sugar that writes out an equivalent unit file

Could we ship this later if there is demand for it?

**Comment by ajeddeloh** [comment]
> Could we ship this later if there is demand for it?

Yup

**Comment by basvdlei** [comment]
If there is no dependency on any of these services, not having shipping any wrapper scripts or unit files is fine. Less stuff that can break.

Having to write your own units that run etcd and airlock in containers should not be a problem. But it would be nice to at least have a standard/endorsed/tested way of running them. What container runtime engine, level of isolation, systemd unit names and behavior, location for data and certificate files, custom SElinux policy, etc. Having FCCT generate these units with those conventions would be ideal though.

The question is how do you update these containers without having to SSH and fiddle with units on nodes provisioned like this? Tag on the minor version and pull each time it's started?

**Comment by ajeddeloh** [comment]
I'd imagine we'd include an `ExecStartPre=<runtime> pull <image>` in the units so they get updated every time the unit is started.

For actually changing the units, the usual "container linux-y way" is to reprovision.

**Comment by jbtrystram** [comment]
we now have suggar support for systemd units in Butane, and coreOS does not ship etcd or flannel as the cluster management is now done through k8s. Closing
