### ISSUE TITLE
Extend bootupd test to include testing adoption and updates

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#1788]
### Describe the enhancement

Can probably borrow some idea from upstream tests.

### System details

N/A

### Additional information

Would have helped with:
- https://github.com/coreos/fedora-coreos-tracker/issues/1771
- https://github.com/coreos/bootupd/issues/694
- https://bugzilla.redhat.com/show_bug.cgi?id=2300306

**Comment by jlebon** [comment]
And also strengthen the current bootupd test to sanity-check the output of `bootupctl status`:
https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/boot/bootupd

**Comment by travier** [comment]
Another potential test would be to:
- Overwrite an existing file in the ESP
- Verify that `bootupctl validate` now fails
- Remove `/boot/bootupd-state.json`
- Adopt / update again
- Verify that `validate` is successful

**Comment by HuijingHei** [comment]
Hold this issue until we transfer to F41 which has new `bootupd-0.2.24-1` (for https://github.com/coreos/fedora-coreos-config/pull/3181).

**Comment by HuijingHei** [comment]
Can I close this as [test](https://github.com/coreos/fedora-coreos-config/pull/3181) is merged (and remove denylist in https://github.com/coreos/fedora-coreos-config/pull/3235)?
