### ISSUE TITLE
kdump fails with composeFS enabled

### ISSUE THREAD

**Issue by jbtrystram** [coreos/fedora-coreos-tracker#1791]
kdump gets confused with the RO filesystem. 

https://bugzilla.redhat.com/show_bug.cgi?id=2284097

Fix : https://github.com/rhkdump/kdump-utils/pull/28

Denylisted in https://github.com/coreos/fedora-coreos-config/pull/3009

**Comment by jbtrystram** [comment]
Possibly solved in https://bodhi.fedoraproject.org/updates/FEDORA-2024-ce7991aa80

Test run in https://github.com/coreos/fedora-coreos-config/pull/3204

**Comment by travier** [comment]
Let's update the docs now that this is fixed: https://docs.fedoraproject.org/en-US/fedora-coreos/composefs/

**Comment by dustymabe** [comment]
We'll be doing a `next` release today (since F41 was `Go` yesterday), so feel free to open the PR.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `41.20241020.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
Since ComposeFS was only enabled for F41+ the regression where `kdump.crash` was failing only ever affected the `next` stream.
