### ISSUE TITLE
[pipeline] FCOS ppc64le builds fail due to low disk space

### ISSUE THREAD

**Issue by jbtrystram** [coreos/fedora-coreos-tracker#1811]
The ppc64 builds / tests intermittently fails due to low disk space on the ppc64 builder.  This has happened multiple times in the last few days.
The disk space there is 200G which can quickly get filled up if a couple of builds fail and are not cleaned. 

We should redeploy that builder with more storage. 
Note that the aarch64 builder ran into the same issue recently : https://github.com/openshift/os/issues/1554

**Comment by dustymabe** [comment]
I deployed https://github.com/coreos/fedora-coreos-pipeline/pull/1046 and https://github.com/coreos/fedora-coreos-pipeline/pull/1031 to this builder and I think that should help.

If we hit any more storage issues we can reach out to releng to increase the size of the disk.

**Comment by jbtrystram** [comment]
> I deployed https://github.com/coreos/fedora-coreos-pipeline/pull/1046 and https://github.com/coreos/fedora-coreos-pipeline/pull/1031 to this builder and I think that should help.
> 
> If we hit any more storage issues we can reach out to releng to increase the size of the disk.

Thanks Dusty! We SSH'ed into the builder with @marmijo yesterday and couldn't confirm the prune job is running, getting a systems error..  (although it looks like it does)

I'll continue to monitor this week

**Comment by dustymabe** [comment]
Closing this. Please re-open if we encounter the issue again.
