### ISSUE TITLE
systemd refuses to boot with cgroups v1 enabled in v256+ (F41+) 

### ISSUE THREAD

**Issue by LeoSum8** [coreos/fedora-coreos-tracker#1833]
### Describe the bug

This morning my FCOS VM was down. I think zincati ran an update.

Upon manually rebooting it, I get the following output via VNC:
![Pasted image 20241114095224](https://github.com/user-attachments/assets/a1b26234-42b0-400b-bb16-eb322540051e)
![Pasted image 20241114095452](https://github.com/user-attachments/assets/0d6535eb-a917-49ce-bc59-e8dd243669e1)
![Pasted image 20241114095522](https://github.com/user-attachments/assets/38a077fe-308c-48fa-9dbe-b611f87bb69a)

Those are the versions installed:
![Pasted image 20241114202732](https://github.com/user-attachments/assets/871ec12e-6f51-4181-b608-242af79f4c34)

Reverting back to Fedora 40 and everything works again as before.

The FCOS VM is a bhyve guest on a FreeBSD (TrueNAS) Host. The guest filesystem resides in a Zvol.

### Reproduction steps

-

### Expected behavior

Boot F41 after update.

### Actual behavior

Booting F41 fails, need to revert to F40

### System details

FCOS as Bhyve-VM on a FreeBSD 13.1-RELEASE-p9 (TrueNAS) host.
FCOS version before update: 40.20241019.3.0 (working)
FCOS version after update: 41.20241027.3.0 (not working)

### Additional information

Initial discussion at https://discussion.fedoraproject.org/t/fcos-vm-bhyve-on-truenas-failing-to-boot-after-automatic-update-systemd-1-freezing-execution/136788/3

**Comment by dustymabe** [comment]
what kernel arguments do you have set for this system?

this looks vaguely like [the issue where systemd won't book with cgroups V1](https://github.com/coreos/fedora-coreos-tracker/issues/1715#issuecomment-2331986149) but I don't see that message in your output you show.

**Comment by stackrainbow** [comment]
I can confirm also affected on a large amount of nodes, auto updates on, cgroups V1 enabled.
Was a little difficult to figure out what was going on apart from just rollbacking, there's no notice or information that cgroups V1 causes this apart from this issue being linked from OP's thread.

**Comment by LeoSum8** [comment]
I am not 100% sure what I am doing here, but judging by the output of `cat /proc/cgroups` I think I am on V1, right?

```
me@coreos:~$ cat /proc/cgroups 
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	11	47	1
cpu	3	108	1
cpuacct	3	108	1
blkio	4	108	1
memory	8	169	1
devices	7	110	1
freezer	12	47	1
net_cls	2	47	1
perf_event	10	47	1
net_prio	2	47	1
hugetlb	6	47	1
pids	5	115	1
rdma	9	47	1
misc	13	47	1

```

Does the F41 update switch to v2 which ends up braking me or is F41 incompatible with v1?
In the latter case, would a manual switch

**Comment by LeoSum8** [comment]
Hint: the docs still show a way how to stay on v1: https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/#_example_staying_on_cgroups_v1

This should be removed or at least a clear hint that this will break F41 should be added.

**Comment by travier** [comment]
https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/#_modifying_kernel_arguments_on_existing_systems We have an example about switching to cgroupsv2 here.

**Comment by travier** [comment]
We highlighted the cgroups v1 boot failure in the announcement: https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/thread/ALBBLBHA37S3YJCA4RDLO6UHNR4DY4MH/.

We recommend subscribing to the coreos-status mailing list as the volume should be really low and it includes announcements those major changes.

**Comment by dustymabe** [comment]
There was also a console login helper message warning that you should have seen on your systems since January: 

https://github.com/coreos/fedora-coreos-config/pull/2818

There are a few ways to make sure your critical infrastructure stays unbroken on updates:

1. Following the [coreos-status](https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/) mailing list
2. Run `next` and `testing` stream nodes to preview what is coming
3. Participate in our Fedora major release Test days (announced on our [devel](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/) mailing list)

[Here](https://github.com/coreos/fedora-coreos-tracker/issues/1802) is an example where an issue was found in `next` by a communmity member and it was fixed before F41 was promoted to `stable`.

**Comment by LeoSum8** [comment]
Thanks for the info!
I am not complaining at all here and don't feel underinformed. Also, my system is not at all critical.
In the contrary, I am amazed how quickly I am helped here by you guys.
The hint towards the "staying on cgroups v1 example" was not meant as criticism.

**Comment by LeoSum8** [comment]
I successfully switched to V2 now with `sudo rpm-ostree kargs --delete=systemd.unified_cgroup_hierarchy --reboot` and after reenabling zincati, it successfully updates to F41.
Thank you guys! 
And indeed I have been ignoring that warning for a few months. I just really read it for the first time now. 
So I do know who to blame ;)
