### ISSUE TITLE
Dracut config file name convention

### ISSUE THREAD

**Issue by daveyoung** [coreos/fedora-coreos-tracker#1837]
### Describe the bug

As described in the #1729  the dracut config file name are not named with digit prefixes which are used more in other places eg. dracut default config files,  or udev rules, or  sysctl.d files.   If CoreOS can use same convention these config files can be sourced in order.    Then the #1729  #1832 can be solved all together since kdump will use itsown config dir  with the new introduced --add-confdir option in dracut upstream.

### Reproduction steps

Put a new config 90-test.conf in /etc/dracut.conf.d/  and we hope it will be sourced after any other config files with number prefixs less than 90.

### Expected behavior

the config files are named with digit numbers

### Actual behavior

the config files CoreOS added are not named with digt number prefixes.

### System details

NA

**Comment by jbtrystram** [comment]
I will be back at work on December 2nd and will gladly look into that if no one have started yet :)

**Comment by travier** [comment]
Sound like a good plan and could help solve:
- https://github.com/coreos/fedora-coreos-tracker/issues/1832
- https://github.com/rhkdump/kdump-utils/issues/11
- https://github.com/coreos/fedora-coreos-tracker/issues/1729

**Comment by daveyoung** [comment]
@jbtrystram  Thanks for taking care of this!

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `41.20241215.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `41.20241215.2.0`. Please try out the new release and report issues.

**Comment by marmijo** [comment]
The fix for this went into `stable` stream release `41.20241215.3.0`. Please try out the new release and report issues.
