### ISSUE TITLE
Feature Request: Enable systemd-boot configuration on installation from LIVE image

### ISSUE THREAD

**Issue by MrPippin66** [coreos/fedora-coreos-tracker#1842]
### Describe the enhancement

Current doc indicates configuration of systemd-boot (sdboot) during initial installation is only an option via the netinst image.

Attempting to configure systemd-boot, even with "inst-sdboot" kernel option from LIVE image on x86 installation via Fedora41 fails with "Systemd-boot cannot be utilized with the current type of payload. Choose an installation media that supports package installation."

Request is for "Install to Hard Drive" option on Fedora LIVE image to support systemd-boot for boot loader vs. GRUB2.

I'm aware you can change the boot loader configuration after initial install, but would desire to not have this extra manual step be a requirement to use systemd-boot.
 
 

### System details

Fedora 41 x86 LIVE USB image

UEFI based 64-bit host with UEFI boot enabled.

**Comment by travier** [comment]
This is the issue tracker for Fedora CoreOS and we don't support using systemd-boot nor Anaconda for installing it.

You should probably start with the discussion forums to get help and redirected to the right place: https://discussion.fedoraproject.org/
