### ISSUE TITLE
[Rawhide]: system-generators/zram-generator failure

### ISSUE THREAD

**Issue by gursewak1997** [coreos/fedora-coreos-tracker#1844]
All kola tests for the latest Rawhide build fail with 
`Found systemd generator failure (/usr/lib/systemd/system-generators/zram-generator)`
This error possibly indicates that the zram-generator, a systemd tool for setting up zram, crashed during execution. It was terminated by the ABRT signal. This results in the zram setup failing at boot or when the generator is triggered.

`/usr/lib/systemd/system-generators/zram-generator terminated by signal ABRT.`

Transition of package that's causing it
`zram-generator 1.1.2-12.fc41 -> 1.2.0-1.fc42`

Rawhide Build introduced: `[rawhide][x86_64] 42.20241129.91.0`

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2329602

**Comment by gursewak1997** [comment]
Fixed in https://bodhi.fedoraproject.org/updates/FEDORA-2024-2d17438c8f

**Comment by jlebon** [comment]
This is fixed now. Thanks @gursewak1997!
