### ISSUE TITLE
Support ESXi 6.0?

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#185]
https://github.com/coreos/coreos-assembler/pull/528 changes the OVA to support ESXi 6.5+ and all supported versions of VMware Workstation and Fusion.  ESXi 6.0 (circa 2015) is [supported for another year](https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/support/product-lifecycle-matrix.pdf).  If we care about supporting it, we'd need to reduce the virtual hardware version to [11](https://kb.vmware.com/s/article/1003746).  If we don't particularly care about supporting it, we should probably not do that, since it makes the virtual hardware [slightly worse](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vm_admin.doc/GUID-789C3913-1053-4850-A0F0-E29C3D32B6DA.html), is not affected by OS upgrades, and is difficult to change later without breaking new installs for somebody.

**Comment by dustymabe** [comment]
>  is [supported for another year](https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/support/product-lifecycle-matrix.pdf).

IMHO we've got many other things to worry about and maybe this will be an incentive to move off of something that will soon be unsupported. +1 for not supporting

**Comment by bgilbert** [comment]
Okay, seeing three +1s for not supporting.  I'll close.
