### ISSUE TITLE
Where can I download FCOS version 38.20231027.3 for OKD 4.14?

### ISSUE THREAD

**Issue by ron981** [coreos/fedora-coreos-tracker#1854]
### Describe the enhancement

Hello,

I'm trying to set up OKD 4.14.0-0.okd-2023-11-12-042703 in an air-gapped environment. According to the release notes, this version requires Fedora CoreOS (FCOS) version 38.20231027.3.

I've tried looking for this specific FCOS version through:
- Fedora mirror manager
- Official Fedora CoreOS download page
- Various Fedora mirrors

However, I cannot locate this specific version. Could you please:
1. Provide a direct link to download FCOS 38.20231027.3?
2. Or alternatively, confirm if a newer version of FCOS 38 would be compatible with this OKD release?

Thank you for your help.

**Comment by Nemric** [comment]
Hi, perhaps you can try here : https://builds.coreos.fedoraproject.org/browser?stream=stable&arch=x86_64

**Comment by dustymabe** [comment]
Correct. Though, 4.14 is an old version of OKD??

In the future you might find better answers in the OKD issue tracker.
