### ISSUE TITLE
Fedora CoreOS is too large

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#186]
Random observations:
- We're shipping `systemd-bootchart`, `adcli`, `libxkbcommon`, and `cracklib-dicts`.  I think these are all coming in via recommends.
- We're shipping `cups-libs` and 64 MB of GeoIP database.
- We could drop man pages and info docs, but that would only save us ~12 MB.
- We're explicitly shipping dnsmasq, which seems like it could go.

Maybe we should try disabling recommends and seeing what happens.

**Comment by bgilbert** [comment]
We're currently shipping man pages and info docs, but not `man(1)` or `info(1)`.

**Comment by bgilbert** [comment]
https://github.com/coreos/fedora-coreos-config/pull/98 drops dnsmasq, man pages and info docs, and some recommends including the bulk of GeoIP.

**Comment by smekkley** [comment]
Locale related files might be able to be removed/stripped as well. I think Fedora comes with full locales instead of generating only necessary one.

**Comment by bgilbert** [comment]
`grub2-{pc,efi}` pulls in `grub2-tools-extra`, which pulls in `freetype`, which pulls in `libpng`.

**Comment by keithy** [comment]
Could we consider moving to providing a standard means to install 3rd party packages outside of overlays, such that those packages can be called in via ignition. Toolbox would only be one of such packages.

I set about developing such an install mechanism which includes a script and a unit that could be included as standard (or enabled via ignition)

https://github.com/keithy/ign-tool/wiki/plug:install-packages

**Comment by dustymabe** [comment]
and just by inspection it seems like `cups-libs` `systemd-bootchart` and `libxkbcommon` are no longer shipping either.

**Comment by dustymabe** [comment]
Maybe we should close this out?

**Comment by dustymabe** [comment]
> Maybe we should try disabling recommends and seeing what happens.

FYI: recommends were disabled and other things removed in https://github.com/coreos/fedora-coreos-config/pull/98
