### ISSUE TITLE
move automated koji tagging service into fedora infra openshift

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#188]
Now that we have the [automated koji tagging service](https://github.com/coreos/fedora-coreos-tracker/issues/179) source code written. Let's move it over into Fedora Infra. This card will serve as a tracker for getting the service running in Fedora Infra.

**Comment by dustymabe** [comment]
Today I sat in on getting an unrelated application into Fedora OpenShift instance. Afterwards I [opened a request with Fedora Infra](https://pagure.io/fedora-infrastructure/issue/7870) to get the process started coreos-koji-tagger.

**Comment by dustymabe** [comment]
labeling blocked as waiting on feedback and progress with fedora infra

**Comment by dustymabe** [comment]
proposed patch set for deploying in fedora infra: https://pagure.io/fedora-infrastructure/issue/7870#comment-577363

**Comment by dustymabe** [comment]
I got this into stage today - the keytab is still not quite working right, but we have made some progress.

**Comment by cgwalters** [comment]
It seems like it'd be *way* simpler to just have the FCOS pipeline own a service that adds rpms into a repo and runs `createrepo_c` and dumps the result in S3 or whatever rather than involving koji.  The whole authentication dance etc. seems very complex.  Was there a reason we're doing koji tags as opposed to just owning an rpm-md repo?

**Comment by cgwalters** [comment]
Although of course, if we want to do *builds* that use this tag...which, I guess we do (rpm-ostree depends ostree, etc.), that entangles the two worlds.

**Comment by jlebon** [comment]
Right, there are two major integration points required with Koji: building rpms, and signing rpms (and note that we may be building and signing RPMs which don't go through the regular Fedora channels, but strictly as backports to existing releases). Once you integrate at those levels, it's hard to ignore the fact that Koji can also be used to manage your rpm-md repo in ways which mesh well with the above workflows and the rest of Fedora.

**Comment by dustymabe** [comment]
This is now running in prod monitoring the testing-devel branch in the fcos configs. When we add lockfiles it'll start tagging into the right place. 

https://pagure.io/fedora-infrastructure/issue/7870#comment-590368
