### ISSUE TITLE
Add Zincati

### ISSUE THREAD

**Issue by rfairley** [coreos/fedora-coreos-tracker#190]
This tracks packaging [Zincati](https://github.com/coreos/zincati) as an RPM package. While Zincati is nearing a release, we can begin looking at the crate dependencies and evaluate whether to use crate dependencies packaged in Fedora (and package dependencies if needed), or bundle dependencies to start.

To add Zincati to FCOS the following are needed:

- [x] `zincati` crate is created on `crates.io`
- [x] Zincati has an RPM specfile which Koji can use to build the RPM
- [ ] `zincati` is added to the manifest in the fedora-coreos-config repository, and necessary bits are enabled/configured (e.g. systemd units)
- [ ] a `zincati` build on Koji is tagged in the coreos-pool RPM repo

To package `zincati` in Fedora:

- [x]  `zincati` is approved as a package in Fedora and has an SCM repo and module created if necessary

**Comment by rfairley** [comment]
The top level of dependencies that aren't satisfied in Fedora Rawhide (where the crates are built):

```
# From a zincati git repo
cargo package
rust2rpm target/package/zincati-0.0.0-dev.0.crate
dnf builddep rust-zincati.spec
...
No matching package to install: '(crate(actix/default) >= 0.8.1 with crate(actix/default) < 0.9.0)'
No matching package to install: '(crate(envsubst/default) >= 0.1.0 with crate(envsubst/default) < 0.2.0)'
No matching package to install: '(crate(libsystemd/default) >= 0.1.0 with crate(libsystemd/default) < 0.2.0)'
No matching package to install: '(crate(reqwest/default) >= 0.9.15 with crate(reqwest/default) < 0.10.0)'
...
```

The `reqwest` crate is [packaged in Fedora](https://src.fedoraproject.org/rpms/rust-reqwest), and the dependency version can be relaxed to 0.9.13. The following will need to be packaged:

- `actix` https://crates.io/crates/actix
- `envsubst` https://crates.io/crates/envsubst
- `libsystemd` https://crates.io/crates/libsystemd

**Comment by lucab** [comment]
@rfairley thanks for starting digging into this! My notes:
 * PR for relaxing `reqwest` constraint is up at https://github.com/coreos/zincati/pull/26
 * both `envsubst` and `libsystemd` are simple native crates I maintain, with very few transitive dependencies. I expect rust2rpm to directly work straightforward on them, but let me know if you need any tweaks upstream.
 * it's unfortunate that `actix` is missing in Fedora. I fear it may have a cascade of transitive dependencies missing too.

**Comment by rfairley** [comment]
Just looked into this a bit more:

- `envsubst` has all its dependencies satisfied with the specfile generated by rust2rpm.

- `libsystemd` just has a couple of dependencies missing:

    ```
    No matching package to install: '(crate(quickcheck/default) >= 0.7.0 with crate(quickcheck/default) < 0.8.0)'
    No matching package to install: '(crate(try_or/default) >= 0.2.0 with crate(try_or/default) < 0.3.0)'
    ```

    - The quickcheck dependency is [packaged in Fedora](https://src.fedoraproject.org/rpms/rust-quickcheck) at version `0.8.3`. The version that `libsystemd` is dependent on currently (in the `Cargo.toml`) is `quickcheck = "0.7"`. This dependency should be OK to change to `0.8` (just tested with `cargo build && cargo test` with `0.8`).

    - `try_or` will also need to be packaged (https://crates.io/crates/try_or) - this is straightforward with rust2rpm.

- Just noticed while looking for another Rust RPM - it looks like `actix` got packaged already! https://src.fedoraproject.org/rpms/rust-actix. Once a nightly compose of Rawhide includes this, this should get pulled in automatically when building the `zincati` RPM (version is `8.3.1` which is within the range needed for `zincati`).

**Comment by rfairley** [comment]
Opened package review requests for the remaining dependencies:
- `rust-envsubst` https://bugzilla.redhat.com/show_bug.cgi?id=1716579
- `rust-try_or` https://bugzilla.redhat.com/show_bug.cgi?id=1716584
- `rust-libsystemd` https://bugzilla.redhat.com/show_bug.cgi?id=1716673

**Comment by rfairley** [comment]
Started looking into packaging `prometheus` which will later be used for https://github.com/coreos/zincati/issues/27.

The build does succeed in Rawhide with some patches made to remove the `hyper` and `protobuf` dependencies (pushed to https://pagure.io/rust-prometheus/tree/master), however hit one issue building from the specfile:

The COPR build (as well as locally) failed only on the `counter.*negative_inc` tests, it looks like it could be a problem with using `should_panic` in the RPM build environment (https://copr-be.cloud.fedoraproject.org/results/rfairley/rust-prometheus/fedora-rawhide-x86_64/00920946-rust-prometheus/builder-live.log). Specifying `%bcond_with check` in the specfile, the build is successful (the default generated by `rust2rpm` is with `%bcond_without check`) (https://copr-be.cloud.fedoraproject.org/results/rfairley/rust-prometheus/fedora-rawhide-x86_64/00920942-rust-prometheus/rust-prometheus.spec).

The two builds with and without the `%bcond_without check` condition are in COPR: https://copr.fedorainfracloud.org/coprs/rfairley/rust-prometheus/builds/.

**Comment by rfairley** [comment]
COPR build works, with a SRPM that includes the upstream fix (https://github.com/pingcap/rust-prometheus/pull/246): https://copr.fedorainfracloud.org/coprs/rfairley/rust-prometheus/build/921364/.

Package review request for `rust-prometheus`: https://bugzilla.redhat.com/show_bug.cgi?id=1717614

**Comment by ignatenkobrain** [comment]
Please don't remove hyper, just port to one of latest versions (there are two of them available in Fedora).

**Comment by ignatenkobrain** [comment]
re:actix — it is 1.0.0 in Fedora, so you'd need to do some porting in code.

**Comment by ignatenkobrain** [comment]
Here's protobuf -- https://bugzilla.redhat.com/show_bug.cgi?id=1718683

**Comment by ignatenkobrain** [comment]
@rfairley @lucab also, would you mind being on #fedora-rust on freenode so that it is easier to reach to you?

**Comment by lucab** [comment]
@ignatenkobrain thanks for `protobuf`!

`actix` (which is different from `actix-web`) is already compatible with latest one in Fedora.

The hyper bump is ongoing at https://github.com/pingcap/rust-prometheus/pull/219 but stuck since some time on CLA things. Given it's only used in a single example, I wouldn't block on that (i.e. stub it for now).

We're both sitting on the IRC channel (`kaeso` and `rfairley`).

**Comment by rfairley** [comment]
Thanks @ignatenkobrain for creating the SCM repos and for `protobuf`!

Will sit in `#fedora-rust` from now.

**Comment by rfairley** [comment]
Pushed an initial import of `rust-prometheus`: https://src.fedoraproject.org/rpms/rust-prometheus/c/e9e6874cd79f2377ecfccefb89e7c81ac105a41c?branch=master, with `"protobuf"` enabled by default.

**Comment by lucab** [comment]
Initial release up at https://crates.io/crates/zincati/0.0.1.

**Comment by rfairley** [comment]
:+1: - will open up a package review request for the initial release (`0.0.1`) once the remaining dependencies (`rust-envsubst` and `rust-libsystemd`) make it to the next published Rawhide compose (currently are in https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20190613.n.0/compose/Everything/x86_64/os/).

**Comment by rfairley** [comment]
Fedora package review request for Zincati initial release: https://bugzilla.redhat.com/show_bug.cgi?id=1721564

**Comment by rfairley** [comment]
RPM source `rust-zincati` and module `zincati` were created:

https://src.fedoraproject.org/rpms/rust-zincati
https://src.fedoraproject.org/modules/zincati

A build of the module is in progress. For F30 this is: https://release-engineering.github.io/mbs-ui/module/4879

Once built, this can be tagged into `coreos-pool`.

**Comment by dustymabe** [comment]
looks like a bunch of the components already failed in that build

**Comment by rfairley** [comment]
Hmm, yes looks like due to missing build dependencies for the components, e.g. https://kojipkgs.fedoraproject.org//work/tasks/8468/35888468/root.log for `rust-actix`. Troubleshooting in `#fedora-rust`.

**Comment by rfairley** [comment]
A problem with ownership of the directories in FCOS was found today:

```
Jul 02 14:40:01 coreos zincati[1610]: Error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Jul 02 14:40:01 coreos zincati[1610]: failed to bind metrics service
```

due to `/root/zincati/private` being owned by `root` when created.

This needed the fix: https://src.fedoraproject.org/rpms/rust-zincati/c/7539f211bc4efae97b1bafeb015e41eb0cd1f78f?branch=master, which is now building: https://koji.fedoraproject.org/koji/taskinfo?taskID=36008351. Will rebuild the module once the RPM is finished building.

**Comment by rfairley** [comment]
> Will rebuild the module once the RPM is finished building.

Module build in progress: https://release-engineering.github.io/mbs-ui/module/4960
