### ISSUE TITLE
Consider loading Ignition platform ID from separate file in /boot

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#191]
The cosa code to set `ignition.platform.id` is kind of hairy.  Afterward, the platform ID is a regular kernel argument that can be removed with `rpm-ostree kargs --delete`.

coreos-installer should be able to change the platform ID after writing the image to disk.  This is needed for PXE-installing VMs, where the installer needs a raw disk image but the booted system should not expect a bare-metal environment.  The installer could rewrite grub configs the same way cosa does, but it'd be much cleaner to just have GRUB read the platform out of a separate file.

**Comment by dustymabe** [comment]
alternatively we implement https://github.com/coreos/coreos-installer/issues/13 and allow it to be overridden like any other kernel arg.

**Comment by bgilbert** [comment]
Possibly.  I've been arguing that Ignition is the right place for overriding kernel arguments, though, not the installer.

**Comment by arithx** [comment]
> Possibly. I've been arguing that Ignition is the right place for overriding kernel arguments, though, not the installer.

I agree that being able to override kernel arguments that are persistent across boots via Ignition makes sense. I would note though that coreos-installer will still need to be able to carry over certain kernel arguments into the first boot initramfs (including `ignition.platform.id`).

**Comment by jlebon** [comment]
>  Afterward, the platform ID is a regular kernel argument that can be removed with `rpm-ostree kargs --delete`

There are lots of other things in the cmdline that nuking would result in even worse fates :) We could maybe add some protection around this in rpm-ostree, but obviously nothing that would prevent users from really changing the args.

> but it'd be much cleaner to just have GRUB read the platform out of a separate file

Using a file instead of a cmdline means that we wouldn't be able to use `ConditionKernelCommandLine` though, right? I guess if we define the new scheme as e.g. `/boot/ignition.platform-id.$id`, then we could switch those to `ConditionPathExists`. Not as elegant though.

My bigger concern though is what this means compatibility-wise. Would RHCOS adopt this? If not, then we end with two sources of truth on what the platform id is.

**Comment by cgwalters** [comment]
>  I guess if we define the new scheme as e.g. /boot/ignition.platform-id.$id, then we could switch those to ConditionPathExists. Not as elegant though.

Seems OK to me?

> Would RHCOS adopt this? 

I see no reason we couldn't switch offhand.

**Comment by bgilbert** [comment]
> Using a file instead of a cmdline means that we wouldn't be able to use ConditionKernelCommandLine though, right?

It'd still be passed on the kernel command line.  GRUB would just read the value from a separate file, rather than having it encoded inline in the kargs list.

**Comment by jlebon** [comment]
> It'd still be passed on the kernel command line. GRUB would just read the value from a separate file, rather than having it encoded inline in the kargs list.

Ahh gotcha, that makes more sense now.

**Comment by dustymabe** [comment]
> alternatively we implement [coreos/coreos-installer#13](https://github.com/coreos/coreos-installer/issues/13) and allow it to be overridden like any other kernel arg.

The implementation for fixing https://github.com/coreos/coreos-installer/issues/13 is mostly already done because we already [pickup and add persisted networking kernel args](https://github.com/coreos/ignition-dracut/pull/65). We'd just need to make an argument users could pass and then we'd stick that string into a new var in the `/boot/ignition.firstboot` file.

**Comment by cgwalters** [comment]
>  The installer could rewrite grub configs the same way cosa does, but it'd be much cleaner to just have GRUB read the platform out of a separate file.

One thing on this topic - at least with the new "non-Anaconda" FCOS images, the canonical bootloader state is in `/boot/loader` and hence changing it externally is trivial with e.g. `sed -i`.  This change is still valid, but I think the motivation is smaller.

**Comment by dustymabe** [comment]
> > The installer could rewrite grub configs the same way cosa does, but it'd be much cleaner to just have GRUB read the platform out of a separate file.
> 
> One thing on this topic - at least with the new "non-Anaconda" FCOS images, the canonical bootloader state is in `/boot/loader` and hence changing it externally is trivial with e.g. `sed -i`. This change is still valid, but I think the motivation is smaller.

I think I agree with @cgwalters here. IIUC we can just `sed -i 's/ignition.platform.id=.* /ignition.platform.id=foo /' /boot/loader.1/entries/ostree-1-fedora-coreos.conf` during the installer. How stable is that filename, can we hardcode it and rely on that.

**Comment by cgwalters** [comment]
I think it'd be more like iterate over all entries in `/boot/loader/*.conf` or so.  (The `loader.[01]` are ostree implementation details, other software should go through the `/boot/loader` symlink generally).

That said...one wrinkle in this is it doesn't apply for architectures which are still using virt-install, or more generally where the bootloader doesn't directly read BLS fragments; AIUI the latter is the case on s390x for example.

But I also don't know how if the coreos-installer model is applicable for s390x either.  I think it is for ppc64le, but it also seems to me we should be able to get that platform into "BLS based bootloader" too.

**Comment by ajeddeloh** [comment]
IIRC zipl, the s390x bootloader, does in fact support BLS (though it's relatively new). We're also currently planning on doing a two stage bootload there, so zipl doesn't actually _need_ to understand bls anyway.

**Comment by cgwalters** [comment]
Right, but per https://github.com/ostreedev/ostree/issues/1888#issuecomment-511867110 one needs to run code to parse and write those entries into a native store *before* booting, in contrast to GRUB which reads the filesystem dynamically on boot.

**Comment by ajeddeloh** [comment]
Oh right, but if we do a two stage that wont be a problem.

**Comment by bgilbert** [comment]
I'm somewhat uncomfortable with coreos-installer knowing how to hack up bootloader config files, since I think of those as an implementation detail of FCOS.  I guess that's less true with BLS, though, and I'm okay with this approach if no one else is bothered by it.

**Comment by dustymabe** [comment]
I think we can maybe try it out and revert to the "grub magic that updates the kernel command line dynamically" if we find problems

**Comment by ajeddeloh** [comment]
> speaking of the "grub magic" does that even work on ppc64le and s390x ?

After some discussion on https://github.com/coreos/ignition-dracut/issues/84 the answer is "not yet but soon". When s390x supports the two stage boot, then it will, and when petitboot supports the grub `source` command then it will. I think we ought to put this on hold until those are complete, then do it. Switching now would block/make that work harder.

**Comment by dustymabe** [comment]
> One thing on this topic - at least with the new "non-Anaconda" FCOS images, the canonical bootloader state is in `/boot/loader` and hence changing it externally is trivial with e.g. `sed -i`. This change is still valid, but I think the motivation is smaller.

Another thing that just came to mind. If we can get all platforms to support bls then we could just set ignition.firstboot by default on the kernel command line and then just `sed` the bls config in `ignition-complete.service` instead of deleting the `/boot/ignition.firstboot` file

**Comment by ajeddeloh** [comment]
> Another thing that just came to mind. If we can get all platforms to support bls then we could just set ignition.firstboot by default on the kernel command line and then just sed the bls config in ignition-firstboot-complete.service instead of deleting the /boot/ignition.firstboot file

This goes against ostree owning the kargs though, and the current s390x issues are just a temporary problem. I think it's cleaner to stick with the current implementation and isolate the messiness to the stopgaps on the arches that need them.

**Comment by dustymabe** [comment]
> his goes against ostree owning the kargs though

isn't the canonical source of truth still the bls config?

**Comment by ajeddeloh** [comment]
> isn't the canonical source of truth still the bls config?

So I think the canonical source is the BLS config but managed by OSTree. Like ostree "owns" it but stores it as the BLS configs. (@cgwalters can you confirm?).

I still think it's much cleaner to use the grub script to set the variable. There's less to go wrong, it's simple to understand, and it means we don't need to worry about kargs changing. If we need to do this as a stopgap on s390x that's fine, but we shouldn't have it as a permanent solution.

**Comment by dustymabe** [comment]
> > isn't the canonical source of truth still the bls config?
> 
> So I think the canonical source is the BLS config but managed by OSTree. Like ostree "owns" it but stores it as the BLS configs. (@cgwalters can you confirm?).

In that case instead of using `sed` on the bls configs we could just call out to ostree in `firstboot-complete.service` to remove the `ignition.firstboot` kernel arg. 

> I still think it's much cleaner to use the grub script to set the variable. There's less to go wrong, it's simple to understand, and it means we don't need to worry about kargs changing. If we need to do this as a stopgap on s390x that's fine, but we shouldn't have it as a permanent solution.

But with what I'm proposing there is actually one fewer moving pieces. We don't need grub to dynamically interpret and add a kernel arg. There is still `ignition-firstboot-complete.service`, but we had that before anyway.

**Comment by cgwalters** [comment]
I think we really need ostree to own the bootloader config when the BLS isn't canonical; i.e. when you need to run `grub2-mkconfig` or equivalent.  Otherwise, I wouldn't necessarily say ostree "owns" the configuration, although...if one wants to make a new deployment with a new karg (rather than mutating the booted one), that probably does need to go through ostree.

Actually the BLS being canonical interacts in a tricky way with ostree's "staged deployment"; I think we may end up serializing a new copy of the pending kargs there.  Would need to verify.

Anyways at least for operating when ostree isn't running, editing the BLS config seems OK.

**Comment by bgilbert** [comment]
> In that case instead of using `sed` on the bls configs we could just call out to `ostree` in `firstboot-complete.service` to remove the `ignition.firstboot` kernel arg.

FWIW, it'd still be nice to move that service back to the initramfs to limit the size of the race condition during first boot.  Until we have ostree in the initramfs, calling out to it from firstboot-complete would create another dependency on that service running from the real root.

**Comment by dustymabe** [comment]
@bgilbert - so we can use `sed` then? :smile: What do you think of the idea of getting rid of the "dynamic grub" bits with this new model?

**Comment by ajeddeloh** [comment]
Using sed seems way more brittle. What if a user adds an unrelated karg our regex happens to match? What if we lose power while writing the config? The firstboot file also works well with the way we carry over install time kargs for networking, and using sed to remove those seems way more hairy.

**Comment by miabbott** [comment]
@bgilbert @ajeddeloh could one of you give some guidance regarding the above question from Allen?

**Comment by bgilbert** [comment]
@zonggen The BLS configs are definitely there in the distributed image.  They're in the `boot` partition, though, not `root`.

**Comment by dustymabe** [comment]
Right. You just have to mount the boot partition.  If I add `rd.break=pre-pivot` on the kernel command line I can mount up the boot partition and see the config before actually switching into the real root:

```
pre-pivot:/# ls /mnt/boot_partition/
pre-pivot:/# mount /dev/disk/by-label/boot /mnt/boot_partition/
[   45.654743] EXT4-fs (vda1): mounted filesystem with ordered data mode. Opts: (null)
pre-pivot:/# ls /mnt/boot_partition/
efi  grub2  ignition.firstboot  loader  loader.1  lost+found  ostree                                                                                                                 
pre-pivot:/# cat  /mnt/boot_partition/loader/entries/ostree-1-fedora-coreos.conf 
initrd /ostree/fedora-coreos-94273156298fde7f0d37e82c97e73f7d72451907dcf7cd614f6dceaea8ca6962/initramfs-5.2.9-200.fc30.x86_64.img
version 1
options root=/dev/disk/by-label/root rootflags=defaults,prjquota rw $ignition_firstboot mitigations=auto,nosmt console=tty0 console=ttyS0,115200n8 ignition.platform.id=qemu ostree0
linux /ostree/fedora-coreos-94273156298fde7f0d37e82c97e73f7d72451907dcf7cd614f6dceaea8ca6962/vmlinuz-5.2.9-200.fc30.x86_64
title Fedora 30.20190831.dev.0 (CoreOS preview) (ostree)
pre-pivot:/#
```
