### ISSUE TITLE
develop method for copying ostree content to the unified ostree repo

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#199]
In the past we have [decided to deliver content via an OSTree repo](https://github.com/coreos/fedora-coreos-tracker/blob/6fc260d22e8313fceb9f37619c5d7af6470689d8/Design.md#ostree-delivery-format). We have discussed in various "streams" discussions that our prod refs would go in the prod location ([Fedora unified ostree repo](https://kojipkgs.fedoraproject.org/ostree/repo/)) and our non prod refs would go into an annex location (separate ostree repo).

We need to develop a mechanism for getting the ostree content into our unified repo when we do a release.

**Comment by jlebon** [comment]
In https://github.com/coreos/fedora-coreos-tracker/issues/198#issuecomment-513944390, we came up with a fedmsg to request the import to happen: `org.fedoraproject.prod.coreos.build.request.ostree-import`. But AFAIK, there isn't a ticket yet on the Fedora releng side to have something react to it.

The spec in the linked comment implies that we would pass to releng the commit tarball directly, though we could also make it an OSTree repo to OSTree repo transfer once we set up an annex repo. (Though I think my personal preference would still be to have releng interact with the canonical build dir directly; this is also consistent with the other fedmsg requests.)

**Comment by dustymabe** [comment]
cross referencing: https://pagure.io/releng/issue/8811

**Comment by dustymabe** [comment]
WIP PR: https://github.com/coreos/fedora-coreos-releng-automation/pull/45

**Comment by dustymabe** [comment]
This is all done except we are waiting on beta freeze to be over before we re-work permissions in the repos. So the only remaining steps should be to run some chmod/chown commands and enable the importer.

**Comment by jlebon** [comment]
@dustymabe IIUC, I think this is all done now, right?

**Comment by dustymabe** [comment]
Almost completely there. I would like to get two PRs merged first https://pagure.io/releng/issue/8811#comment-641382

**Comment by dustymabe** [comment]
Those two PRs merged and the releng ticket closed. This is DONE now!
