### ISSUE TITLE
docker group or not

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#2]
We need to decide whether to include a docker group or not. Today CL does, Fedora does not. Context: https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by JasonGiedymin** [comment]
Prefer from a security standpoint that docker group not exist. Many enterprise customers will appreciate that. At least as a good default. To force the group creation by default would bring multiple dependencies into the fold from a security perspective. That is, a dependency on having strong auditing in place, and have a strong means to react to said auditing. Something across the spectrum not all have.

I understand that from a "part-time user" standpoint (read: non sysadmin with responsibility over many nodes) it could be difficult to use. At the same time, It shouldn't be too difficult to create such a group and chown across the things that need chowning.

To me the question is what group do you focus on? Enterprise, or (for lack of a better name) Desktop Users? Do you offer a different flavor of the OS? 

_Maybe you make docker groups package that when installed does all the work, let the user decide?_

**Comment by bgilbert** [comment]
If we made it optional, that would likely happen via an Ignition config and maybe some CT sugar.  "Installing packages" on Fedora CoreOS is not exactly a thing.

**Comment by JasonGiedymin** [comment]
A system container image I mean.

-Jason

**Comment by bgilbert** [comment]
I'm hoping we don't have any of those either.  :grin:

**Comment by JasonGiedymin** [comment]
That’s cool too. Anything to make my life easier.

**Comment by chrisweeksnz** [comment]
The Fedora CoreOS tech preview has a docker group added, but configured so that users can't be added to it. This is because the group appears to exist in /etc/gshadow, but not in /etc/group. Running 'echo "$(getent group docker)" >> /etc/group' facilitates normal use of tools to add users to the docker group / restore normal function (eg. 'usermod -aG docker myusername' will grant correct access to the docker daemon).

**Comment by dustymabe** [comment]
So the open question here is whether we do one of these two options:

- we add a docker group to /etc/group so that `usermod -aG docker myusername` works?
- we encourage users to use `sudo docker` instead

**Comment by ajeddeloh** [comment]
https://github.com/coreos/fedora-coreos-config/pull/175 is a short term solution, do we want to reopen until we have the final solution? cc @dustymabe  @jlebon

**Comment by dustymabe** [comment]
We are tracking the long term solution in https://github.com/projectatomic/rpm-ostree/issues/49. It's not a ticket in this tracker though.

If we want to track here then I'd suggest we open a new ticket that isn't specific to the docker group.
