### ISSUE TITLE
create a fedora-release-coreos rpm

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#20]
We'll need one of these similar to `fedora-release-atomichost`. It will need to be added to the [fedora-release package](https://src.fedoraproject.org/rpms/fedora-release) as a sub rpm. [Here](https://src.fedoraproject.org/rpms/fedora-release/blob/6d2e7b8a5c54b37ac0c0bd5149b55fd55a34fca8/f/fedora-release.spec#_36) is an example where atomic host is added today. upstream for that is https://pagure.io/fedora-release

**Comment by dustymabe** [comment]
once this PR gets merged let's get it backported to the f29 branch as well since we'll start work in case we want to experiment in the f29 time frame

**Comment by sinnykumari** [comment]
Another PR https://src.fedoraproject.org/rpms/fedora-release/pull-request/20 which contains required changes to create fedora-release-coreos sub-package in rawhide got merged.

**Comment by sinnykumari** [comment]
[PR#20](https://src.fedoraproject.org/rpms/fedora-release/pull-request/20) has already been backported to f29 branch in commit https://src.fedoraproject.org/rpms/fedora-release/c/2dc8d9cd7aac43c7a2a8991da2fc7a979e611107?branch=f29 .

Also, latest fedora-release build in koji contains fedora-release-coreos sub-package for both [F29 ](https://koji.fedoraproject.org/koji/buildinfo?buildID=1139873) and [rawhide](https://koji.fedoraproject.org/koji/buildinfo?buildID=1139855).

**Comment by sinnykumari** [comment]
@dustymabe I think we can close this issue now.

**Comment by dustymabe** [comment]
:fireworks:
