### ISSUE TITLE
repo for coreos-koji-tagger

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#202]
Right now it's at https://pagure.io/dusty/coreos-koji-tagger. Do we want to put it under https://github.com/coreos/coreos-koji-tagger ? The reason I ask is I anticipate we'll have several of these single purpose repos and don't know if we want to pollute the toplevel namespace in GH.

**Comment by dustymabe** [comment]
cc @bgilbert

**Comment by bgilbert** [comment]
We've never tried to limit what goes into the GH namespace, and there's a lot of stuff there already.  I think it's fine to put Fedora CoreOS-related projects in github.com/coreos by default.

**Comment by sinnykumari** [comment]
Is there a plan to use coreos-koji-tagger repo outside Fedora? If not, should we name it fedora-coreos-koji-tagger?

**Comment by dustymabe** [comment]
> Is there a plan to use coreos-koji-tagger repo outside Fedora? If not, should we name it fedora-coreos-koji-tagger?

not that I know of - I'm not opposed to putting `fedora` in the name. I'll do that unless someone else chimes in.

**Comment by sinnykumari** [comment]
I don't like much long names, but mentioned it because I thought this is the convention we are following for new repos under coreos/

**Comment by dustymabe** [comment]
https://github.com/dustymabe/fedora-coreos-koji-tagger

**Comment by dustymabe** [comment]
> https://github.com/dustymabe/fedora-coreos-koji-tagger

well that's my fork.. here is the real repo: https://github.com/coreos/fedora-coreos-koji-tagger
