### ISSUE TITLE
Move coreos-installer out of initramfs

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#203]
Under some circumstances, users need to run arbitrary code before/after coreos-installer.  (https://github.com/coreos/coreos-installer/pull/25 is the tip of the iceberg.)  At present, this requires either a) modifying coreos-installer to ship that code directly, or b) allowing users to run arbitrary code in the initramfs.  (a) presents an ongoing maintenance problem, and (b) adds compatibility constraints to the construction of the initramfs.  (For example, we couldn't remove a command-line tool that might be used by a third-party script.)

Once #105 and #106 land, it will be possible to drop the separate installer image, recommend running coreos-installer from the live PXE or ISO image, and move coreos-installer to the real root.  In the typical case, the UX wouldn't change: the installer would still be driven by kargs.  But the user could also provide an Ignition config which configures additional services to run before/after the installer, and those services would have access to all the facilities of a full FCOS system.

Alternatively, we could provide the option to run the installer in _either_ the initramfs or the real root.  That might allow dropping the separate installer PXE image (since the live PXE image would simply never look for the root filesystem when not needed), but we'd still need to make a decision about the installer ISO.  I don't think there's enough value to this approach to justify the complexity, though.

**Comment by strawgate** [comment]
This is a blocker for us to moving to Fedora CoreOS -- not being able to boot to a shell and invoke the install and other pre and post-install tasks makes the transition not possible at this time

**Comment by lucab** [comment]
@strawgate a small status update that may be relevant to you (on behalf of @bgilbert who did most of the work):
 * we now have live-PXE artifacts on the download page (but documentation needs updates): https://github.com/coreos/fedora-coreos-tracker/issues/105#issuecomment-542799249
 * we started work in coreos-installer to close this ticket here. Initial rework was just tagged as `v0.1.0`, which is not yet available in Fedora (and FCOS) but in the interim it can be consumed as a container: https://quay.io/repository/coreos/coreos-installer?tab=tags

**Comment by dustymabe** [comment]
Now that [we have systemd services for the new rustlang based coreos-installer](https://github.com/coreos/coreos-installer/pull/119) and a new [rust-coreos-installer rpm](https://src.fedoraproject.org/rpms/rust-coreos-installer) with them included. We have removed the old installer ISO from [the pipeline](https://github.com/coreos/fedora-coreos-pipeline/pull/182) and [the configs](https://github.com/coreos/fedora-coreos-config/pull/261).

This work should be complete. New releases will pick up all the changes and we'll do installs via the live images.
