### ISSUE TITLE
Create tool for propagating changes from testing-devel to bodhi-updates

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#204]
Our main development stream is `testing-devel` (e.g. it's the default branch for https://github.com/coreos/fedora-coreos-config). But we want changes we commit to it (e.g. changes to `overlay/`) to propagate automatically into `bodhi-updates`. Basically, the only differences between `bodhi-updates` and `testing-devel` should be (1) lockfiles/overrides in `testing-devel`, and (2) `manifest.yaml` (which holds the stream-specific ref and repos).

So we need a tool that will automatically merge changes to everything else from `testing-devel` to `bodhi-updates` (and then in the future `bodhi-updates-testing` as well).

**Comment by dustymabe** [comment]
Yeah I was actually thinking about this on Friday. It's almost like we want "everything else, but two files". We need overlayfs for our git repos now :smile:

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-releng-automation/pull/3

**Comment by dustymabe** [comment]
Anything left for this?

**Comment by jlebon** [comment]
Nope, done!
