### ISSUE TITLE
Create tool for push lockfiles around

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#205]
We need a tool that will:

1. watch for new `bodhi-updates` builds
2. push `manifest-lock.generated.json` to `bodhi-updates`
3. on some configurable interval, open PR to update `manifest-lock.json` to `testing-devel`

**Comment by dustymabe** [comment]
>     1. watch for new `bodhi-updates` builds

probably would be good to have our pipeline publish a fedmsg for new builds so other things can queue off of it

**Comment by dustymabe** [comment]
> > ```
> > 1. watch for new `bodhi-updates` builds
> > ```
> 
> probably would be good to have our pipeline publish a fedmsg for new builds so other things can queue off of it

which actually ties pretty closely with https://github.com/coreos/fedora-coreos-tracker/issues/198

**Comment by jlebon** [comment]
Related: https://github.com/CentOS-PaaS-SIG/ci-pipeline/blob/59b4cb3cefdabca41844ea6a2c1bbfc221d90148/src/org/centos/pipeline/PipelineUtils.groovy#L304

The `sendCIMessage` step is provided by https://github.com/jenkinsci/jms-messaging-plugin.

So I think it's a matter of adding that plugin to our master, then plugging in the right configs and creds into Jenkins so it's set up.

**Comment by dustymabe** [comment]
according to https://pagure.io/fedora-infrastructure/issue/7940#comment-579650 we need our own certs and can't re-use what the Fedora CI pipeline has done. I looked at rabbitmq publishers for jenkins today. I found [one](https://wiki.jenkins.io/display/JENKINS/RabbitMQ+Publisher+Plugin) but I don't see where it supports TLS cert auth. 

Fortunately the fedora-messaging CLI is [growing the ability to publish messages using the CLI](https://github.com/fedora-infra/fedora-messaging/pull/43). I tested that PR out and it seems to be working so maybe we can go with that. I'll try to test this out in a hacker pipeline run tomorrow.

**Comment by jlebon** [comment]
> according to https://pagure.io/fedora-infrastructure/issue/7940#comment-579650 we need our own certs and can't re-use what the Fedora CI pipeline has done. I looked at rabbitmq publishers for jenkins today. I found one but I don't see where it supports TLS cert auth.

Is the first sentence related to the next ones? I'm not sure if you're saying that because we can't use the same cert as the Fedora CI pipeline, we can't use the same plugin either. Isn't it just a matter of plugging in a different cert in the settings for `jms-messaging-plugin`?

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-releng-automation/pull/3

**Comment by dustymabe** [comment]
Anything left for this one?

**Comment by jlebon** [comment]
We still need to make it PR-based, though that's tracked by https://github.com/coreos/fedora-coreos-releng-automation/issues/32, so yeah let's close this one.
