### ISSUE TITLE
Formal schemas for FCOS metadata

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#206]
Consider providing JSON Schema documents for validating stream and release metadata, and validating that metadata immediately after it is generated.

**Comment by lucab** [comment]
@bgilbert I'd like to start tackling the release-index and update metadata portion of this. In which repository where you thinking to place the schemas?

**Comment by bgilbert** [comment]
In fedora-coreos-tracker.  We already have https://github.com/coreos/fedora-coreos-tracker/tree/master/metadata with sample metadata.

**Comment by jlebon** [comment]
We have schemas for the release index and update docs now: https://github.com/coreos/fedora-coreos-tracker/blob/main/metadata/updates/fcos-updates-schema.json, https://github.com/coreos/fedora-coreos-tracker/blob/main/metadata/release-index/fcos-release-index-schema.json. Though AFAIK, we don't currently use them to validate the documents.

I think this would be nice, but I don't see us having the time to codify the remaining documents. We also currently never touch most of these documents by hand (except maybe the update metadata one sometimes), which makes it harder (but of course not impossible!) to get wrong.

Closing for now, but we can reopen in the future if we hit issues that would've been caught by this.
