### ISSUE TITLE
Need repo for releng tools

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#210]
We now have https://github.com/coreos/fedora-coreos-koji-tagger, which is the first in a list of "automation tools" to write. There's a bunch more to come (see e.g. #204 and #205). Rather than having them scattered across multiple tiny repos, let's have them all in a single repo for the time being?

My first instinct was in fact to integrate them into https://github.com/coreos/fedora-coreos-pipeline given that there's going to be some tight coupling between them, but @dustymabe convinced me to start off as a separate repo and go from there (either split them into further repos, or keep them in a single repo, or fold them into the pipeline repo).

**Comment by dustymabe** [comment]
anybody have thoughts on github.com/coreos/fedora-coreos-releng-automation ? If that works I'll just rename the https://github.com/coreos/fedora-coreos-koji-tagger and move the koji tagger into a subfolder.

**Comment by lucab** [comment]
Generally in favor of a single `releng` repo (similar to mantle). Couple of doubts on such a single repo:
 * what's then plan for CI? 
 * do we plan to build a single or multiple containers out of it?
 * is that repo supposed to be multi-lang?

**Comment by dustymabe** [comment]
> Generally in favor of a single `releng` repo (similar to mantle). Couple of doubts on such a single repo:
> 
>     * what's then plan for CI?

No specific plans. The idea is to have it mostly be small self contained applications that are easily set up in openshift/kube. Typically I like the model where changes to the git repo trigger a new build/deployment so we can iterate fast, but that might not work for everything. 

> 
>     * do we plan to build a single or multiple containers out of it?

I'd say probably one container per subdirectory. 

> 
>     * is that repo supposed to be multi-lang?

It could be.. I was thinking it would mostly be interpreted languages but there's no reason a directory couldn't be a compiled language where the container build does the compilation.

**Comment by lucab** [comment]
Fine for me. I was just wondering if that's going to make the CI setup (whatever you were planning) harder, and same for auto-building a container with all the stuff (e.g. via quay). It sounds like it may, but it's overall just a minor annoyance.

**Comment by dustymabe** [comment]
> Fine for me.

:+1: thanks!

> I was just wondering if that's going to make the CI setup (whatever you were planning) harder, and same for auto-building a container with all the stuff (e.g. via quay). It sounds like it may, but it's overall just a minor annoyance.

Yeah, mostly planned to build the containers using a buildconfig in openshift for each subproject, that way it's all contained in the openshift namespace.

**Comment by dustymabe** [comment]
ok i'm going to rename https://github.com/coreos/fedora-coreos-koji-tagger to https://github.com/coreos/fedora-coreos-releng-automation in 30 minutes unless anyone opposes here first.

**Comment by mohanboddu** [comment]
> ok i'm going to rename https://github.com/coreos/fedora-coreos-koji-tagger to https://github.com/coreos/fedora-coreos-releng-automation in 30 minutes unless anyone opposes here first.

:+1:

**Comment by dustymabe** [comment]
done: https://github.com/coreos/fedora-coreos-releng-automation
