### ISSUE TITLE
coreos.fedoraproject.org is down

### ISSUE THREAD

**Issue by stickster** [coreos/fedora-coreos-tracker#214]
Some problem with CloudFront maybe? It's a 502 error. I wasn't sure where to file it so I started here.

**Comment by jlebon** [comment]
>  CloudFront wasn't able to connect to the origin. 

Hmm weird. AFAIK it's just fronting the GitHub site.

@sanjabonic @puiterwijk Any ideas? Did we twiddle with any of the CloudFront or repo settings recently?

**Comment by lucab** [comment]
Likely a temporarily problem? It is up now for me (in EU).

**Comment by jlebon** [comment]
Interesting. Still showing as down here for me (CAN).

```
502 ERROR
The request could not be satisfied.
CloudFront wasn't able to connect to the origin.
If you received this error while trying to use an app or access a website, please contact the provider or website owner for assistance.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by following steps in the CloudFront documentation (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.html).

Generated by cloudfront (CloudFront)
Request ID: mMqe4r3Yb4kIJKcR3rgQm56fuAMBukSsfk1eOP0Fes5pfQrTIFLadg==
```

Seems like it could be a CloudFront misconfiguration?

**Comment by sinnykumari** [comment]
It is working fine for me as well in India

**Comment by ajeddeloh** [comment]
Seems to be up now, closing. Feel free to reopen if it's down for you.

**Comment by bgilbert** [comment]
It's still down.  The problem seems to be specific to certain regions.

**Comment by shadowbq** [comment]
Its down in the US.

**Comment by shadowbq** [comment]
Like they said the CDN configuration is bad.

Down.com - It's you! Looks like https://coreos.fedoraproject.org is online.
https://downforeveryoneorjustme.com - Is coreos.fedoraproject.org down right now? It's not just you! coreos.fedoraproject.org is down.

**Comment by jlebon** [comment]
Right, it worked fine yesterday for me, but again not today (failing with the same 502).

Can we please have someone look at this? Ideally before we actually release preview?

**Comment by sanjabonic** [comment]
It's a regional problem and we decided to go along with Fedora's plans to not have subdomains for editions so instead of fixing the issue, we'll redirect the subdomain to point to the relevant part of getfedora.org. We have moved the FAQ to the official documentation corner for Fedora CoreOS and are working on adding more content in the period of preview release to stable.

https://docs.fedoraproject.org/en-US/fedora-coreos/faq/
