### ISSUE TITLE
OSTree finalization on shutdown errors out

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#215]
The latest FCOS preview release (30.20190716.0) seems to have an issue with OSTree finalization on shutdown:

```
Jul 16 18:19:02 localhost ostree[1914]: error: Unexpected state: /run/ostree-booted found and in / sysroot but not in a booted deployment
Jul 16 18:19:02 localhost systemd[1]: ostree-finalize-staged.service: Control process exited, code=exited, status=1/FAILURE
Jul 16 18:19:02 localhost systemd[1]: ostree-finalize-staged.service: Failed with result 'exit-code'.
Jul 16 18:19:02 localhost systemd[1]: Stopped OSTree Finalize Staged Deployment.
```

Still investigating this, but offhand it seems like `/boot` is being unmounted *before* `ostree-finalize-staged.service` "shuts down", which doesn't make sense since we have `After=local-fs.target`.

The workaround is manually calling `ostree admin finalize-staged` before restarting.

**Comment by jlebon** [comment]
Probably related: https://github.com/coreos/fedora-coreos-config/pull/105

**Comment by ajeddeloh** [comment]
What does the boot unit look like on a anaconda'd ostree setup? Maybe there's some other deps?

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/119
