### ISSUE TITLE
Don't relabel across mounts

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#223]
Today we have:

```
overlay/usr/lib/dracut/modules.d/40coreos-var/coreos-populate-var.sh
36:echo "Z /var - - -" > /run/tmpfiles.d/var-relabel.conf
```

But if I do e.g. `cosa run --srv /srv/walters`, systemd tries to relabel across the mount point, which is definitely wrong.  I think we need a flag to tell systemd not to traverse mount points when relabeling, or potentially change it to do that by default.

**Comment by ajeddeloh** [comment]
How would that impact people setting up mounts within /var (e.g. /var, /var/log, /var/lib each being separate filesystems)? Don't we want this behavior in that case?

**Comment by cgwalters** [comment]
I think we just need to relabel the files/dirs we create before policy is loaded.  If a user specifies a custom mount point, like `/var/srv`, we should ensure `/var/srv` is relabeled before a mount is placed there (this bit is tricky) but we definitely shouldn't try to recurse down into it.

If a user make a mountpoint for `/var/log` and we create `/var/log/journal` I think we may need to relabel that.  But not other files that happen to be there.

**Comment by SerialVelocity** [comment]
I just hit this. I have a huge amount of files in /var/lib/containers which I mount and already have the correct labels. It takes around 20 mins for the "Create Volatile Files and Directories" job to finish (which does the /var relabeling)

**Comment by jlebon** [comment]
> I just hit this. I have a huge amount of files in /var/lib/containers which I mount and already have the correct labels.

Hmm interesting. Note the relabeling only happens on first boot. Are you mounting a persistent `/var/lib/containers` partition between multiple reprovisionings of FCOS?

**Comment by SerialVelocity** [comment]
> Are you mounting a persistent /var/lib/containers partition between multiple reprovisionings of FCOS?

Yes, I PXE boot my hosts using a supplemental custom initrd. I will switch to coreos/fedora-coreos-config#155 when I can but that doesn't seem to deal with this issue.

**Comment by jlebon** [comment]
We've long since moved to relabeling from the initrd.
