### ISSUE TITLE
Shortlinks for launching on clouds

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#226]
For quick reference cards, cheat sheets, and the like, it might be nice to have short URLs that redirect to each cloud's web launch UI for the current FCOS image on that cloud.  For example:

- fcos.example.com/aws
  - implicitly `stable` in `us-east-1`
- fcos.example.com/aws/us-west-2
  - implicitly `stable`
- fcos.example.com/testing/aws/us-west-2
- fcos.example.com/gcp
  - implicitly `stable`
- fcos.example.com/testing/gcp

On the other hand, we could just refer users to the [getfedora download page](https://getfedora.org/coreos/download/) (or a short URL for it) and let them click one additional button.  That way we'd have an opportunity to give them some additional info about FCOS via text on that page.

**Comment by lucab** [comment]
Are there command-line clients that would support those short URL redirectors? If not, then additional buttons next to the download ones could be enough.

**Comment by bgilbert** [comment]
As proposed, the redirectors would point to interactive launch pages for the various clouds, so I don't think command-line clients would be especially useful here.  We're planning to add buttons in any event.

**Comment by sinnykumari** [comment]
I think link to [getfedora download](https://getfedora.org/coreos/download/) should be sufficient. Also, once in future if we can get FCOS web page designed according to the [suggested design](https://pagure.io/fedora-websites/issue/964#comment-576026) for c[loud images](https://pagure.io/fedora-websites/issue/raw/files/5d4422d3dd16084ea46f258be55806021b4274e74bf532fff2edb13e41203549-cloudlaunch.png), it will be a single click.

**Comment by bgilbert** [comment]
There doesn't seem to be much enthusiasm for this, so I'll close.
