### ISSUE TITLE
Ship systemd-nspawn

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#230]
## Version
```
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20190725.0 (2019-07-25T18:54:22Z)
                    Commit: 8b79877efa7ac06becd8637d95f8ca83aa385f89f383288bf3c2c31ca53216c7
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
```
## Enhancement

We don't ship the `systemd-container` package, which includes `systemd-nspawn`.  Should we add it?

cc @mrguitar

**Comment by cgwalters** [comment]
My 2¢ - ship it.  It's not a big addition, and while the overlap with e.g. `podman` and in particular things like `podman generate systemd` is large...still, I think the systemd group is likely to continue to maintain it into the future.

**Comment by mrguitar** [comment]
I think nspawn makes sense to include, and I can't think of a reason not to include it.

**Comment by cgwalters** [comment]
https://github.com/coreos/fedora-coreos-config/pull/126
