### ISSUE TITLE
Booting from ISO fails.

### ISSUE THREAD

**Issue by javexed** [coreos/fedora-coreos-tracker#234]
Was trying to use the ISO to install onto a VM built on a proxmox (KVM) server. 
Cannot seem to get booted, I get the following error:

cat: /tmp/selected_dev: No such file or directory
Image URL is required, please provided the -b flag or coreos.inst.image_url on the kcmdline

From the rdsosreport.txt

I do see
- Reached target CoreOS Installer Target
- Started CoreOS Installer
- Startup finished
- then the error above.

Nothing else in there is obvious to me before the error above. I was thinking that it may be "hardware related". I tried using different things in the creation of the VM (BIOS/UEFI, different display drivers, storage drivers, etc)... However, nothing is changing that error.

Thought I would document in case someone else has something similar.

**Comment by arithx** [comment]
You need to specify the device to install it onto (e.x. `sda` or `vda`). It can be specified via the `coreos.inst.image_url` flag on the kernel commandline or from inside of dracut you can run `/usr/libexec/coreos-installer -h` to get a list of the options it accepts.

**Comment by javexed** [comment]
Ok, further along:

/usr/libexec/coreos-installer -d /dev/sda -b https://stable.release.core-os.net/amd64-usr/current/coreos_production_image.bin.bz2

results in:
"failed to fetch ignition config from ignition.json"

Looking at: https://coreos.com/os/docs/latest/booting-with-iso.html
it seems that it is a known limitation of iso's and indicates that there is no easy way to provide an ignition config.

Maybe the obvious question is, why doesn't it install to the first drive or ask which drive to install to... (or is this a feature request?) And why is there no default ignition config on the ISO? (I don't even know if these are the right questions...)

**Comment by arithx** [comment]
Docs on https://coreos.com are for Container Linux not for Fedora CoreOS. [Here](https://github.com/coreos/coreos-installer/blob/master/README.md) are the docs for `coreos-installer`, and the general getting started docs for Fedora CoreOS are located at https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/

The Ignition config itself can be specified via either `coreos.inst.ignition_url` on the kcmdline or the `-i` option when interacting directly with `/usr/libexec/coreos-installer`.

**Comment by javexed** [comment]
Ok, seems like the same issue either way. Looks like I need to define an ignition.cfg file and somehow pass that to the vm. Not a criticism persay, just this is more involved than I was expecting... For my needs, I will just install fedora server and install docker on top  of that. Closing the issue. Will keep an eye on the project if this is addressed in a future version.

**Comment by idontusenumbers** [comment]
I just ran into the same issue; the install guide says the file is optional.

**Comment by lucab** [comment]
This ticket is mixing some bits from Container Linux and some from Fedora CoreOS, resulting into a lot of confusion. I'm going to lock this now to prevent further mixups.

@idontusenumbers if you are indeed looking for the **Fedora CoreOS** installer, double-check the documentation at https://github.com/coreos/coreos-installer/blob/master/README.md and if you see anything off please open a dedicated bug report.
