### ISSUE TITLE
Delaying auto-update finalization if ongoing interactive sessions

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-tracker#239]
On Container Linux, locksmithd was in charge of gating reboots in order to finalize auto-updates. As a UX-enhancing feature, locksmithd was able to broadcast to consoles about an upcoming reboot and delay by 5 minutes if it detected any ongoing interactive sessions, see https://github.com/coreos/locksmith/blob/dce618ae9a8ad110f90e7727a3076ff7d451727e/locksmithctl/daemon.go#L120.

Most of locksmith logic have been ported to Zincati (or is at least covered to fit into its current design), except for the above feature.

In FCOS world, Zincati is not responsible anymore of actually rebooting the node. Its last task is to invoke rpm-ostree finalization, which then proceed with its own logic towards (possibly) the final reboot.

As such, we should probably think of a better place and strategy for graceful-interactive-delays.
One option would be to move previous locksmith logic into rpm-ostree. Another option to explore would be implementing the [inhibitor-lock protocol](https://www.freedesktop.org/wiki/Software/systemd/inhibit/), in either of the components. There may be other routes to explore too, which I'm not seeing right now.

**Comment by cgwalters** [comment]
Related https://gitlab.gnome.org/GNOME/gnome-software/issues/397

**Comment by lucab** [comment]
Reading from that ticket, there are indeed multiple phases that I should have detailed a bit better.
Those go as follows:
 1. update checks against cincinnati server. Those are gated by `boot-complete.target`, and owned by Zincati.
 2. deploying new updates. Those are gated by a proper update-edge being available in the graph, and owned by Zincati.
 3. finalization trigger. This is gated by each node update strategy (default: immediately finalize once new deployment is staged), and owned by Zincati as its last logical step in the state machine.
 4. node reboot. This is gated by whatever is the outcome of this ticket and owned by rpm-ostree.

We are interested in point 4, with some degree of freedom to change point 3 to ease our plans. Download management is fully decoupled from reboot management in our scenario.

**Comment by jlebon** [comment]
> 3. finalization trigger. This is gated by each node update strategy (default: immediately finalize once new deployment is staged), and owned by Zincati as its last logical step in the state machine.
> 4. node reboot. This is gated by whatever is the outcome of this ticket and owned by rpm-ostree.

Hmm, though these two steps are coupled right now. `finalize-deployment` will unlock the deployment and immediately reboot. So detecting interactive sessions could still belong in Zincati, no?

**Comment by lucab** [comment]
@jlebon yes, we have room for changes in Zincati. However I was ideally trying to move such logic as close as possible to the final reboot action because:
 * previous detection logic had "broadcast to console, sleep, reboot" as a single atomic action
 * Zincati can detect only before finally calling `finalize-deployment`. If something fails after that, it will just keep spamming the console in a loop, without any real effect
 * if we stick to the simpler model of `reboot +time`, rpm-ostree needs to own it anyway

I won't mind adding some helper in Zincati, but from a design point of view I would place the "detect and delay" logic exactly one step before issuing the `reboot` command. That is, when the rest of the (possibly fallible/cancellable) finalization logic has already been committed.

**Comment by lucab** [comment]
After some chat with @jlebon we agreed on the following details:
 * rpm-ostree already provides a way to control when reboots should happen, via the dedicated `finalize-deployment`
 * risks of spamming the console due to broadcasting **before** calling finalize-deployment are not significant
 * there is strictly no need for further logic to be implemented in rpm-ostree
 * we can use the same broadcast-and-detect logic that we had in locksmith
 * we can use systemd-inhibit API to control for how long to delay updates
 * wishlist: we should investigate re-parenting systemd-inhibit so that it can survive even if Zincati dies/restarts
 * wishlist: we should investigate whether it is possible to tie the reboot-inhibition to a console session, and early-reboot if the user logouts earlier 
 * all of the above logic should be implemented in Zincati

**Comment by lucab** [comment]
This has been implemented in https://github.com/coreos/zincati/releases/tag/v0.0.19, which is already available in all streams.
