### ISSUE TITLE
Consider modifying `/etc/os-release` to have FCOS specific URLs

### ISSUE THREAD

**Issue by arithx** [coreos/fedora-coreos-tracker#243]
We should consider modifying the `/etc/os-release` file to have links that are more relevant to FCOS.

Example contents of `/etc/os-release` from `30.20190725.0`:
```
NAME=Fedora
VERSION="30.20190725.0 (CoreOS preview)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30.20190725.0 (CoreOS preview)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS preview"
VARIANT_ID=coreos
OSTREE_VERSION=30.20190725.0
```

Platform: AWS

```
$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20190725.0 (2019-07-25T18:54:22Z)
                    Commit: 8b79877efa7ac06becd8637d95f8ca83aa385f89f383288bf3c2c31ca53216c7
              GPGSignature: (unsigned)
```

**Comment by mike-nguyen** [comment]
Does this accurately summarize the changes we want for os-release?

```
PRETTY_NAME="Fedora CoreOS 30.20190725.0 (preview)"
HOME_URL="https://coreos.fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
```

**Comment by jlebon** [comment]
Yeah, that LGTM! I like that idea.

**Comment by bgilbert** [comment]
The `HOME_URL` should be https://getfedora.org/coreos/.  coreos.fedoraproject.org is just a redirect now.

**Comment by mike-nguyen** [comment]
This is test output and motd with the changes I've made to the spec file.  If it looks good I'll make create the PR to the fedora-release repo.

Note:  Anything that is 'CoreOS preview' will be just 'CoreOS' once stable is released and we remove https://github.com/coreos/fedora-coreos-config/blob/testing-devel/fedora-coreos.yaml#L61
```
Fedora CoreOS preview 30.20191017.dev.2
Tracker: https://github.com/coreos/fedora-coreos-tracker
Preview release: breaking changes may occur

[core@localhost ~]$ cat /etc/os-release 
NAME=Fedora
VERSION="30.20191017.dev.2 (CoreOS preview)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora CoreOS preview 30.20191017.dev.2"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS preview"
VARIANT_ID=coreos
OSTREE_VERSION='30.20191017.dev.2'
```

**Comment by dustymabe** [comment]
```
> HOME_URL="https://getfedora.org/coreos/"
```

This doesn't match https://github.com/coreos/fedora-coreos-tracker/issues/243#issuecomment-520835275

Otherwise - LGTM

**Comment by mike-nguyen** [comment]
https://src.fedoraproject.org/rpms/fedora-release/pull-request/100
https://src.fedoraproject.org/rpms/fedora-release/pull-request/101
https://src.fedoraproject.org/rpms/fedora-release/pull-request/102

**Comment by mike-nguyen** [comment]
> ```
> > HOME_URL="https://getfedora.org/coreos/"
> ```
> 
> This doesn't match [#243 (comment)](https://github.com/coreos/fedora-coreos-tracker/issues/243#issuecomment-520835275)
> 
> Otherwise - LGTM

It was changed to match bgilbert's comment here: https://github.com/coreos/fedora-coreos-tracker/issues/243#issuecomment-521399161

**Comment by mike-nguyen** [comment]
> ```
> > HOME_URL="https://getfedora.org/coreos/"
> ```
> 
> This doesn't match [#243 (comment)](https://github.com/coreos/fedora-coreos-tracker/issues/243#issuecomment-520835275)
> 
> Otherwise - LGTM

>> The HOME_URL should be https://getfedora.org/coreos/. coreos.fedoraproject.org is just a redirect now.

It matches what bgilbert was saying in the comment

**Comment by dustymabe** [comment]
> It matches what bgilbert was saying in the comment

ahh. I missed that

**Comment by keithy** [comment]
It would be handy to be able to add some additional metadata to this file (or another similar file) via the ignition script.

metadata:
   platform: kiosk
   version: v0.0.1

**Comment by mike-nguyen** [comment]
Checked the latest release of FCOS and verified /etc/os-release has the correct information.
```
$ cat /etc/os-release 
NAME=Fedora
VERSION="31.20191210.dev.1 (CoreOS preview)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora CoreOS preview 31.20191210.dev.1"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS preview"
VARIANT_ID=coreos
OSTREE_VERSION='31.20191210.dev.1'
```
