### ISSUE TITLE
Consider changing OS pretty name to "Fedora CoreOS"

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#245]
The MOTD, issue, and GRUB menu all say:

`Fedora 30.20190801.0 (CoreOS preview)`

That's a Fedora CoreOS version number, not a Fedora version number, so I'd argue that the message is confusing.  Consider changing the os-release `PRETTY_NAME`to `Fedora CoreOS NN.NNNN.N (preview)` and ensuring the change is picked up in the relevant places.  (console-login-helper-messages, at least, composes the MOTD out of `NAME` and `VERSION` and ignores `PRETTY_NAME`.)

**Comment by dustymabe** [comment]
cc @sgallagher just for guidance on if he thinks this would cause any issues

**Comment by arithx** [comment]
Related #243

**Comment by sgallagher** [comment]
@dustymabe If this causes any issues, that's actually a good thing. The `PRETTY_NAME` is not intended for parsing programmatically. It's defined only as a name presented to the user. So if it causes any issues, we learn which programs are using the wrong field for their purposes.

**Comment by mike-nguyen** [comment]
Current MOTD now is:
```
Fedora CoreOS preview 31.20191210.dev.1
Tracker: https://github.com/coreos/fedora-coreos-tracker
Preview release: breaking changes may occur
```

Grub displays
```
Fedora CoreOS preview 31.20191210.dev.1 (ostree:0) 
```

**Comment by AdamWill** [comment]
@sgallagher I quite like *checking* this stuff programmatically to check it's correct, though. And the more editions we have doing it differently for no particularly good reason, the [more complicated it gets](https://pagure.io/fedora-qa/os-autoinst-distri-fedora/blob/master/f/tests/os_release.pm)...
