### ISSUE TITLE
Provide coreos via DNF

### ISSUE THREAD

**Issue by alanconway** [coreos/fedora-coreos-tracker#246]
This page https://getfedora.org/en/coreos/download/ gives a poor install experience compared to normal Fedora/RHEL packaged software. It lists 9 separate downloads with manual signature verification. Then https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/  provides long mysterious command lines that must be applied before doing anything.

I want to see instructions like this:

----

Quick start:

    dnf install coreos-quickstart

This installs coreos-virt and starts a VM cluster on your machine with default settings, ready to experiment.

Other packages:

* `dnf install coreos-bare` - tools to configure a bare metal cluster.
* `dnf install coreos-virt` - tools to configure virtual clusters.
* `dnf install coreos-cloud` - tools to configure CoreOS in an existing cloud.

Once installed see /usr/share/doc/coreos-<version>/README.md.

----

# Rationale

As a long time Fedora/RHEL user I hate install instructions with wget, manual downloads etc. _Individual_ installs are not hard, managing software from many packages is.

An RPM isn't complicated - it's just automating the existing steps, cleaning up after ourselves, and making dependencies (or lack thereof) explicit. We can still provide manual steps for non-RPM platforms. If we care about debian/ubuntu then apt packages might also be a good idea.

## Problems with current approach.

* multiple manual steps and multiple web clicks required to get to a working system.
* coreos is invisible to `gnome-software` or `dnf search coreos`
* not clear if/how downloaded files (e.g. vmware or openstack) interact with the same files installed from supported RPMs.

## Advantages of dnf/RPM

* visibility: dnf is the reflex for Fedora or RHEL users who need new software.
* install and set-up a working system in one command.
* install local docs for offline use.
* setup scripts and docs are part of install, they can't go out of sync when the website changes.
* install instructions don't change with a new release even if install content does.
* free support for uninstall/reinstall/upgrade/downgrade/multi-version/satellite/gnome-software and other existing package management tools.

And of course: RPMs are what made Red Hat great! :)

**Comment by cgwalters** [comment]
Dup of https://github.com/coreos/fedora-coreos-tracker/issues/235 ?

**Comment by alanconway** [comment]
Duplicate of #235

**Comment by alanconway** [comment]
This is not really a duplicate of #235. 

* This issue is about a better user experience for https://getfedora.org/en/coreos/download/ 
*  #235 is about providing executable tools for coreos which also need to be packaged.

Each issue can be solved independently, but they should take account of each other so we end up with a consistent set of packages: without overlaps and with clear names and intention for each package.

**Comment by arithx** [comment]
I'm not sure I really understand this ticket then. The objects on https://getfedora.org/en/coreos/download/ are all OS images. What are you explicitly asking to be included in `dnf`?

**Comment by ajeddeloh** [comment]
I think there's some [X Y problem](https://en.wikipedia.org/wiki/XY_problem) going on here. What are you trying to achieve and how will packaging it as an RPM help?

**Comment by cgwalters** [comment]
Based on the ticket I think he is seeing a pretty expansive scope for provisioning tooling which general consensus seemed to be against us doing.

Among other reasons for that, there are already a wide variety of tools in this area, from Terraform to Foreman, etc.  So we'd be more likely to include in our documentation links to best practices or configuration etc.

That said this was mentioned as an aside but I think we should add explicit FCOS support to `virt-install`; no need for a new package.

**Comment by alanconway** [comment]
Apologies, nonsense, misread. Will install on my bare-metal cluster and raise some not-nonsense issues forthwith.

**Comment by bgilbert** [comment]
@cgwalters `virt-install` support is https://github.com/coreos/fedora-coreos-tracker/issues/221.
