### ISSUE TITLE
platform: add support for Hyper-V

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-tracker#251]
@praveenkumar just showed me that [CodeReady Containers](https://github.com/code-ready/crc) is looking into consuming and running FCOS images via [Hyper-V](https://en.wikipedia.org/wiki/Hyper-V) on Windows.

Their current solution is on [this github repo](https://github.com/code-ready/machine/blob/b6d974ad44d01f18861a8ad3c0949cfd56b15032/drivers/hyperv/hyperv.go#L175-L227) and just needs a disk image in the relevant format.

In order to properly support this, we should:
 * reserve and document a platform ID for this environment
 * check if we have some host->guest backchannel available for Ignition to use
 * add support in coreos-assembler to buildextend images for this platform
 * start publishing such images

**Comment by lucab** [comment]
It looks like in Container Linux we [already have](https://github.com/coreos/coreos-overlay/blob/50605361f92565653aa49550a8bbb33fa5c437ad/coreos-base/oem-hyperv/files/grub.cfg#L3) an `hyperv` OEM, so I think we can just keep using that label.

@ajeddeloh I didn't see any dedicated provider/logic in Ignition, and I'm not sure what's the current Ignition story on Hyper-V.

**Comment by mrguitar** [comment]
Did CL use any of the Hyper-V agents?

**Comment by lucab** [comment]
No, it didn't.
But at some point we opened a ticket for ourselves to investigate adding them https://github.com/coreos/bugs/issues/2161.

**Comment by ajeddeloh** [comment]
Ignition doesn't support HyperV right now. I don't know of any work/investigation into it offhand.

**Comment by DanielFroehlich** [comment]
any update on this? Any plans to support HyperV in near term future?

**Comment by lucab** [comment]
@DanielFroehlich no relevant updates, this is low priority at the moment and not on the radar for the future.

**Comment by lucab** [comment]
Self-note: values in the key-value store are limited to 2KiB, see https://github.com/torvalds/linux/blob/6f0d349d922ba44e4348a17a78ea51b7135965b1/include/uapi/linux/hyperv.h#L178.

**Comment by fsdrw08** [comment]
Hi, are there any updates? Is core os Ignition support hyper driver now?

**Comment by dustymabe** [comment]
no updates that I know of

**Comment by mwoodpatrick** [comment]
Any progress on this?

**Comment by bgilbert** [comment]
Please do not ping on this issue.  If someone would like to work on it, a good place to start is investigating how Ignition can retrieve userdata from the hypervisor.

**Comment by mwoodpatrick** [comment]
Can you elaborate on exactly what userdata is needed? I'm still trying to come upto speed on this. Any pointers would be appreciated.

**Comment by bgilbert** [comment]
Ignition needs to be able to fetch a user-supplied JSON document (the "Ignition config") from the hypervisor.  The user uses the Ignition config to specify the customizations that should be applied to the VM, such as files, systemd units, and SSH keys.

On cloud platforms, we fetch this config from the cloud provider's userdata mechanism.  In the cloud's web UI this usually looks like a text box.  Inside the VM, the data can generally be accessed via a network service or a virtual CD drive.

On other VM platforms, we use a host-guest communication mechanism provided by the hypervisor.  If we're lucky, the hypervisor UI provides a text box, but sometimes we need to document a CLI command for attaching the config to the VM, or maybe even how to hand-edit it into a VM description file.  Inside the VM, on VMware we read the config from a guestinfo variable; on VirtualBox, a guest property; on QEMU, a `fw_cfg` blob.

**Comment by bgilbert** [comment]
https://github.com/coreos/ignition/issues/1538 tracks Hyper-V support in Ignition.

**Comment by bgilbert** [comment]
This is now tracked in #1411 which uses the new platform request template.  Closing this one as a duplicate.
