### ISSUE TITLE
Consider adding jq package

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#254]
Container Linux has it.  Also, it could be useful for parsing stream metadata from scripts in the host.

**Comment by arithx** [comment]
It's also particularly useful with `python` not being included on the host to have some way of interacting with JSON data.

**Comment by dustymabe** [comment]
![foo](https://user-images.githubusercontent.com/4530030/63179350-e3cba400-c019-11e9-95cb-663725ffd055.jpg)

Looks like we have consensus. I opened https://github.com/coreos/fedora-coreos-config/pull/145

**Comment by dustymabe** [comment]
Looks like the only thing this brings is is the [oniguruma package](https://apps.fedoraproject.org/packages/oniguruma)
