### ISSUE TITLE
Update to docs clarifying Fedora Atomic to FCOS rebase is NOT coming.

### ISSUE THREAD

**Issue by keithy** [coreos/fedora-coreos-tracker#257]
Early announcements of FCOS indicated that despite Fedora Atomic (29) being effectively EOL, there were strong hints that there would be a direct (i.e. one/two clicks) rpm-ostree upgrade path from Fedora Atomic.

Following discussions in irc, it appears that this is not likely to happen, and documentation needs to be updated to reflect this and clarify the situation.

**Comment by lucab** [comment]
@keithy thanks for the report. Do you maybe have links to those places that you encountered and needs to be amended?

**Comment by keithy** [comment]
Principly - https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_how_do_i_migrate_from_fedora_atomic_host_to_fedora_coreos

**Comment by lucab** [comment]
For reference the source for that should be https://github.com/coreos/fedora-coreos-docs/blob/08dcc6ac106ca2d296982222ba3cf0379ae036c4/modules/ROOT/pages/faq.adoc#how-do-i-migrate-from-fedora-atomic-host-to-fedora-coreos.
