### ISSUE TITLE
tag in new ostree+rpm-ostree

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#259]
So I have builds done, and am now fighting to try to get them in the pool (so I can use rpm-ostree in cosa)

I did end up doing a bodhi update for ostree https://bodhi.fedoraproject.org/updates/FEDORA-2019-3a3b518302 but not for rpm-ostree since I don't want to ship the snapshot.

```
diff --git a/manifest-lock.overrides.x86_64.json b/manifest-lock.overrides.x86_64.json
index 5ad55d7..42b0664 100644
--- a/manifest-lock.overrides.x86_64.json
+++ b/manifest-lock.overrides.x86_64.json
@@ -3,6 +3,26 @@
     "ignition": {
       "evra": "2.0.1-2.gite75cf24.fc30.x86_64",
       "digest": "sha256:1c67a8d43ee1ece8414e5df326bb4dd26f61e43d518462f955af1724d7b5827a"
+    },
+    "ostree": {
+      "evra": "ostree-2019.3-3.fc30.x86_64",
+      "digest": "sha256:83c9c09548716a3e0c7d85aebade99bb53e4472d137dc81f9bc644fd8b406b9d"
+    },
+    "ostree-grub2": {
+      "evra": "ostree-2019.3-3.fc30.x86_64",
+      "digest": "sha256:653b51017bb612e32052b4c5bf03c7b0477d130b8e248a98d73b0fd6f2969d89"
+    },
+    "ostree-libs": {
+      "evra": "ostree-2019.3-3.fc30.x86_64",
+      "digest": "sha256:677b3a12c337afe015ef79a7c3a58f1cbb1caa7f2d7873bbbb7e7fb01efe68eb"
+    },    
+    "rpm-ostree": {
+      "evra": "rpm-ostree-2019.5.7.gcac5aa41-3.fc30.x86_64",
+      "digest": "sha256:d3cd6da799bcdf60a26cb11b9c7bc5102f5270555cb73e0dc1179e33cbe64fed"
+    },
+    "rpm-ostree-libs": {
+      "evra": "rpm-ostree-2019.5.7.gcac5aa41-3.fc30.x86_64",
+      "digest": "sha256:5c0ff9f5d4b82e450d0b9dae86808c0ae90151d142dbc97c267edd4304e99eed"
     }
   }
 }
```

However, local build isn't finding them because they're not in the main repos, nor the pool.  I guess once we do the bodhi thing for ostree that will be fixed by the bot.

But, trying to track rpm-ostree git master is still *really* painful with this system.  I guess SOP is probably: 

 - Do a git master snapshot build on the f30 branch, but don't create a bodhi update
 - Have someone tag into the pool
 - Update the lockfile here and git push

?

Anyways can someone with privs tag the above (do ostree and rpm-ostree)?

**Comment by cgwalters** [comment]
I guess in the end this case of needing to update rpm-ostree for cosa is still *somewhat* unusual.  Things will probably settle down more.

But, I do think we need to introduce a new stream that includes git master of "our stuff" (ignition, ostree) etc, plus possible automatic upstream git master builds of other stuff (systemd, kernel) as we need for testing - this we would just do on x86_64, bypassing Koji.

**Comment by cgwalters** [comment]
Only *needs* to be in `coreos-continuous` right now, but eh, might as well do both?

**Comment by dustymabe** [comment]
> Only _needs_ to be in `coreos-continuous` right now, but eh, might as well do both?

Sorry I incorrectly told you the name of the tag (edited in comment above). There is one `continuous` tag for every major release of fedora. Both the `ostree` and `rpm-ostree` builds are now in the `f30-coreos-continuous` and `coreos-pool` tags.

**Comment by dustymabe** [comment]
now you can apply your changes to the overrides file.

**Comment by cgwalters** [comment]
OK, the cosa container has them now, which was my main goal.  I think we're OK for now waiting till rpm-ostree passes through bodhi to take it.
