### ISSUE TITLE
CI: Prow + "CoreOS CI" tracker

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#263]
I'm spending a bit of time trying to improve CI for ostree/rpm-ostree.  Today the testing infrastructure is oriented around Fedora Atomic Host.  I'd obviously like to target FCOS.

Now, we have a few pieces of infrastructure here.  I am also investigating using Prow.

See: https://github.com/openshift/release/issues/4892

Jonathan has been working on directly using CentOS CI, see e.g. https://github.com/coreos/coreos-assembler/pull/667 and https://github.com/coreos/coreos-assembler/pull/685

Briefly the advantages of Prow are:

 - "merge policy stuff" i.e. `/lgtm`, `/approve` etc.
 - Maintained by a dedicated team and the core of OpenShift CI

The advantages of CentOS CI are:

 - We use Jenkinsfile and /dev/kvm for FCOS/RHCOS

**Comment by jlebon** [comment]
> "merge policy stuff" i.e. `/lgtm`, `/approve` etc.

AFAIK, this is mostly separate from what's actually running the tests. We could have all those niceties (including `/meow` :cat: !), but still use CentOS CI for testing.

**Comment by dustymabe** [comment]
Worth discussing at our next meeting?

**Comment by cgwalters** [comment]
> Worth discussing at our next meeting?

Sure.  (Though as a general rule I think meeting discussions work best when they are *in addition* to ongoing active conversation and work happening async, so hopefully people interested chime in here)

**Comment by cgwalters** [comment]
https://github.com/openshift/release/pull/4979 merged

**Comment by jlebon** [comment]
I opened https://github.com/openshift/release/pull/5254 too which sets it up for coreos-assembler. Given that many of us contribute there, it'd be a good way for more people to test drive and see how we like it before propagating it everywhere else.

**Comment by cgwalters** [comment]
https://github.com/openshift/release/pull/5263

**Comment by cgwalters** [comment]
https://github.com/openshift/release/pull/5392

**Comment by cgwalters** [comment]
@jlebon any reference point/docs for onboarding into https://jenkins-projectatomic-ci.apps.ci.centos.org/blue/organizations/jenkins/rpm-ostree/ ?

**Comment by jlebon** [comment]
OK, I've created a new repo and added a README there with details of the current state of things: https://github.com/jlebon/coreos-ci.

I've also enrolled a few more repos:
- coreos/ignition
- coreos/mantle
- ostreedev/ostree
- coreos/fedora-coreos-pipeline

As mentioned in the README, the goal is to migrate to https://jenkins-coreos-ci.apps.ci.centos.org/. We now have all the perms we need in that namespace. I'm currently experimenting there with GitHub OAuth, JCasC and Job DSL to make managing this trivial. Will PR that repo with configs for reviews!

**Comment by cgwalters** [comment]
Is the git repo in jlebon/ because it's basically awaiting group review?

**Comment by ashcrow** [comment]
It sounds like some folks were a bit surprised today to find repos expecting `OWNERS` files this morning. How wide has this been discussed (cabal? open discussion? mailing list?)?

**Comment by jlebon** [comment]
There are two separate things here:
1. enrolling the repos into CoreOS CI (this is where Jenkins executes `.cci.jenkinsfile` files -- we already had this for e.g. coreos-assembler, fedora-coreos-config, and rpm-ostree)
2. enrolling the repos into Prow (this is where e.g. `/lgtm` is enabled)

On Thursday, I enrolled the repos mentioned in https://github.com/coreos/fedora-coreos-tracker/issues/263#issuecomment-580342137 into 1. On Friday, I enrolled coreos-assembler specifically into Prow: https://github.com/openshift/release/pull/6954. I think this latter bit is more what you're talking about, right? No other repo was added to Prow.

This approach was discussed a while back in a community meeting, in a cabal, and in an internal mailing list.

Re. cosa specifically, I asked people on freenode and internally what they thought before submitting the Prow patch. Now, I acknowledge we could've done this a bit more slowly. But again, in my mind, this is where things were heading already. If that is not the case, then we can absolutely revert that patch and discuss it some more.

**Comment by cgwalters** [comment]
I agree this is where things are heading (unless someone comes up with some alternative plan).  But our SOP here should probably include announcing the changes across multiple channels, and we should have the onboarding scheduled in advance or something?

Or alternatively...maybe it is simpler to try to just do it all at once now; basically script adding a stub `cci.jenkinsfile` and the openshift/release changes?

**Comment by ashcrow** [comment]
Things are heading in this direction. I don't think there is any push back around that and don't think there is a need to revert. 

I was told mantle and Ignition had them turned on as well. We have a ton of communication channels which makes it harder to ensure folks see changes :slightly_frowning_face:. It sounds like you let folks know in the two major areas (Freenode and Internal Chat). If that's the case then people may have just missed it.

**Comment by darkmuggle** [comment]
The bigger problem, IMHO, is that the affected repos may not play in this Tracker. I have been told that filing issues that are not specific to FCOS are inappropriate for _this_ tracker. Having the discussion that affects other repositories that are used by FCOS, RHCOS, and even other distributions here seems to be imposing the will of FCOS development on those repositories. 

I do not think we should revert. 
Improving our CI story is admirable. The effect is positive. 

But before this Tracker is used to make changes in other repositories care should be taken to bring the affected development teams.

I might add that some of the developers do not have access to the Jenkins system (I still don't).

**Comment by cgwalters** [comment]
> I might add that some of the developers do not have access to the Jenkins system (I still don't).

This is documented [here](https://wiki.centos.org/QaWiki/CI/GettingStarted) and also mentioned in the [fedora-coreos-pipeline](https://github.com/coreos/fedora-coreos-pipeline#fedora-coreos-pipeline) bits.  (Yeah...it should really use GH auth...)

**Comment by cgwalters** [comment]
Currently we don't have any Prow jobs configured for coreos-assembler; I think this is why Prow isn't listening to `/lgtm`. 

Which - if we want to go this route, we probably should also standardize on a baseline script like `ci/build.sh` or whatever that gets run by both Prow and Jenkins?

**Comment by cgwalters** [comment]
Hmm, maybe in coreos-assembler's case the right thing is to convert the Travis job into a Prow job.

**Comment by darkmuggle** [comment]
> > I might add that some of the developers do not have access to the Jenkins system (I still don't).
> 
> This is documented [here](https://wiki.centos.org/QaWiki/CI/GettingStarted) and also mentioned in the [fedora-coreos-pipeline](https://github.com/coreos/fedora-coreos-pipeline#fedora-coreos-pipeline) bits. (Yeah...it should really use GH auth...)

Access was requested 08 Jan for me. Access is granted whenever the CentOS BuildSys people get around to it.

**Comment by jlebon** [comment]
I'm prioritizing https://github.com/jlebon/coreos-ci this week, which will leverage GitHub OAuth to fix this (and actually, you should already be able to log into https://jenkins-coreos-ci.apps.ci.centos.org/). I agree that not having access to Jenkins is a major pain point and has to be resolved before we can drive this across all the repos.

**Comment by cgwalters** [comment]
https://github.com/openshift/release/pull/6998

**Comment by cgwalters** [comment]
I know we discussed this before, but do we have any story on `/retest`?  What are we actually using on the Jenkins side, is it [GHPRB](https://github.com/jenkinsci/ghprb-plugin/blob/master/README.md) still?  How would I find out the answer to the latter, is there a place with the deployment code?

**Comment by jlebon** [comment]
> I know we discussed this before, but do we have any story on /retest? What are we actually using on the Jenkins side, is it GHPRB still?

The Jenkins <-> GitHub bits are all part of Jenkins itself (well, the GitHub and GitHub Branch Source plugins). It's more akin to Travis CI at this point; so you'd have to go in and retrigger the test if you want to rerun. We could probably have a lightweight solution for handling retests via comments though we need to be wary of adding too much complexity when a large part of the appeal (to me at least) is how vanilla the setup is.

> How would I find out the answer to the latter, is there a place with the deployment code?

Working on that, but essentially we're not doing anything more than setting up a [Multibranch Pipeline job](https://jenkins.io/doc/book/pipeline/multibranch/).

**Comment by cgwalters** [comment]
[ostree onboarding](https://github.com/ostreedev/ostree/pull/1999)

**Comment by jlebon** [comment]
CoreOS CI configuration: https://github.com/jlebon/coreos-ci/pull/1

**Comment by jlebon** [comment]
OK, so https://github.com/jlebon/coreos-ci/pull/1 I think is ready for review. I queued up enrollment of `coreos/ignition-dracut` as a first victim before we migrate repos which are already hooked up to projectatomic-ci: https://github.com/jlebon/coreos-ci/pull/2

And finally, with https://github.com/coreos/coreos-ci-lib/pull/10, I've encapsulated the `cosa build && cosa kola` pattern so that we can use it more easily. For example, with that, the `ignition-dracut` CI could just be to start with:

```groovy
@Library('github.com/coreos/coreos-ci-lib') _

cosaPod {
  checkout scm
  fcosBuild(make: true)
}
```

**Comment by jlebon** [comment]
OK, moved the repo to the coreos/ org: https://github.com/coreos/coreos-ci. We now have it up and running at https://jenkins-coreos-ci.apps.ci.centos.org/.

PRs to have ignition-dracut hooked up:
- https://github.com/coreos/coreos-ci/pull/2
- https://github.com/coreos/ignition-dracut/pull/152

To be clear, note that this does not hook up Prow. The only visible change from this is that PRs and branches will be automatically tested. Merges still need to happen manually.

**Comment by jlebon** [comment]
Once ignition-dracut is working well, I'll migrate over everything currently running on projectatomic-ci and add other repos like zincati and mantle. Will link to relevant PRs here.

**Comment by lucab** [comment]
A personal pain point I had with Prow is that splitting CI config and codebase in different repos is a source of troubles.
Am I understanding it right that we are not going into that direction, as we instead have CI configs living in each repo as Jenkinsfile?

**Comment by jlebon** [comment]
> A personal pain point I had with Prow is that splitting CI config and codebase in different repos is a source of troubles.
> Am I understanding it right that we are not going into that direction, as we instead have CI configs living in each repo as Jenkinsfile?

We're sort of in a hybrid mode right now, where most of the upstream testing (at least for the repos where CoreOS CI is turned on) is done in Jenkins, but merging is done by Prow. And for that to work well, we also have to define at least a dummy prowjob to run.

This has some repercussions, because Prow is not aware of Jenkins and e.g. doesn't rerun the tests before merging (meaning we're exposed to ["semantic conflicts"](https://bors.tech/essay/2017/02/02/pitch/)).

I think there are different ways to slice this, but essentially: if we're planning to really leverage Prow/OpenShift CI for our upstream repos such that e.g. we want to bring up a whole cluster for testing, then we'll want to reconcile these issues (i.e. somehow make Prow aware of CoreOS CI). If we really just want a merge bot, then I think it's worth exploring different more lightweight options, like Bors (which actually buildah recently switched to as well).

IMO, because OpenShift CI tests are generally already very expensive, I think the model of having it run at the central integration point makes more sense instead of in each individual component repo. E.g. we could have Prow jobs testing OKD on the fedora-coreos-config repo (and the equivalent RHCOS repo -- which we have today via promotion, but I think we want at the PR level too).

**Comment by cgwalters** [comment]
A reason OpenShift CI is very centralized is because for the core platform container images, there's a high degree of uniformity - they all build and work the same way.  We don't want to have to touch (as of 4.3.3¹) 100 git repositories to make a change to how CI works.

This is less true of our coreos stuff.  Even ostree and rpm-ostree differ in important ways (for example right now, rpm-ostree ships a spec file upstream, and one would have to argue really hard for me to agree to do that in ostree).

¹
```
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.3.3-x86_64 | grep -Ee '^  .* sha256:' | wc -l
100
```

**Comment by cgwalters** [comment]
The other thing I'll repeat here is at least nothing stops one from having a Prow job that basically boils down to running a script in the upstream repository.  

But I'd also agree that we should support defining jobs in upstream git and have automation update the jobs from there.

The other middle ground is what we already have with https://github.com/coreos/coreos-ci-lib - I do like that approach in general.

**Comment by jlebon** [comment]
Current status:
- Everything is now migrated over to https://jenkins-coreos-ci.apps.ci.centos.org/.
- I've opened a PR which hooks up many more repos: https://github.com/coreos/coreos-ci/pull/10. I'll try to write jobs for some of them, but encourage others to try it out for themselves as well (you can look at the `.cci.jenkinsfile` of repos already hooked up for inspiration).

**Comment by jlebon** [comment]
> A reason OpenShift CI is very centralized is because for the core platform container images, there's a high degree of uniformity

Yeah, the uniformity aspect is an interesting one. Like you mentioned, I think we get *some* of that with https://github.com/coreos/coreos-ci-lib (but clearly nowhere near the same level; with OpenShift, even GitHub labels are synced from CI).

Overall, my gut feeling is to go with simple solutions and see how it goes before trying to have a more advanced setup. IOW, it doesn't seem to me like the tradeoff is worth it right now to use Prow as a glorified merge bot vs something more no-frills like Bors.

I can see exceptions to that though with e.g. fedora-coreos-config CI testing OKD, or the CI for  https://github.com/coreos/airlock/ running on top of a cluster.

**Comment by cgwalters** [comment]
> IOW, it doesn't seem to me like the tradeoff is worth it right now to use Prow as a glorified merge bot vs something more no-frills like Bors.

We're not *just* using Prow for that though - we also run tests there.  The arguments for Prow are basically twofold:

- Running jobs that *don't* require KVM in CentOS CI is a bit of a waste
- It's maintained by a team, we already need it on OpenShift-aligned repos, as of recently it actually uses 4.x and RHCOS so we feel the pain of OS upgrades killing build pods

Now for the first point, one thing I think we may want to try to add to the mix is some Github Actions use for "basic build and lint" stuff.  In particular, the ones that use the Checks API are a *lot* nicer as you get build errors directly annotated in the code.

**Comment by cgwalters** [comment]
Related to this is that talking about "Jenkins/CentOS CI" and "Prow" is conflating a few things - the DPTP team is close to getting [external clusters](https://github.com/openshift/release/issues/4892) working and that changes things - there's no reason we couldn't e.g. run Jenkins and have KVM jobs there too, as well as direct Prow-managed KVM jobs.

**Comment by cgwalters** [comment]
In fact it also might work today to hand a kubeconfig for CentOS CI to Prow too.  (Except of course CentOS CI is a totally ancient OpenShift install)

**Comment by cgwalters** [comment]
OK!  So this is still a simmering topic.  A few notable things changed:

 - We introduced the "buildroot" container (built in api.ci/Prow) and are using that across various repos
 - We now have nested virt in Prow so we're not fully dependent on CentOS CI for virt testing
 - openshift/os is now a public git repo and is using that along with the RPM mirroring so our RHCOS CI uses Prow
 - coreos-assembler gangplank was introduced (but not yet used)
 - There's stuff going on at https://github.com/coreos/coreos-ci-lib/pull/61 that I am not sure about

Anyways so...one thing I'm thinking about here is how we share code/workflows across all of these.  One not-fully-fleshed out idea is that instead of encoding logic for builds in e.g. coreos-ci-lib Groovy or in Prow, we create a new "coreos-assembler-ci" container that's used in both places or so?

**Comment by cgwalters** [comment]
> Now for the first point, one thing I think we may want to try to add to the mix is some Github Actions use for "basic build and lint" stuff. In particular, the ones that use the Checks API are a lot nicer as you get build errors directly annotated in the code.

Actually on this topic I recently looked again at systemd's current CI, and we have stuff to learn from that.
See the stuff in https://github.com/systemd/systemd/tree/main/.github/workflows
(And look at a random PR to see the results, like https://github.com/systemd/systemd/pull/18705 )

In particular, this "LGTM.com" thing seems useful; it's a proprietary (zero cost to us) analysis, but personally I am (somewhat) ok adding that type of thing.  We still have gcc and clang analyzers that we can contribute to if we need to as well.

Obviously where GH Actions "gets you" is when you scale up to a nontrivial repo and need to pay them (versus us giving money to our own infrastructure).  I wonder if systemd is hitting those limits and/or is sponsored?
