### ISSUE TITLE
`ignition.firstboot` not in `/proc/cmdline` on first boot

### ISSUE THREAD

**Issue by brtknr** [coreos/fedora-coreos-tracker#267]
I am attempting to book Fedora CoreOS on bare metal OpenStack but looks like the `ignition.firstboot` arg is missing from `/proc/cmdline` which is possibly the reason why my user data doesn't get added to the instance that boots up. I have managed to successfully boot up the same image on virtual OpenStack and no issues there.

```
BOOT_IMAGE=(hd0,gpt1)/ostree/fedora-coreos-b2601a3ea2062ef19454f16d2bdbcd80348a1be8226542b0e9255b19149a24d8/vmlinuz-5.1.20-300.fc30.x86_64 root=/dev/disk/by-label/root rootflags=defaults,prjquota rw mitigations=auto,nosmt console=tty0 console=ttyS0,115200n8 ostree=/ostree/boot.1/fedora-coreos/b2601a3ea2062ef19454f16d2bdbcd80348a1be8226542b0e9255b19149a24d8/0 ignition.platform.id=openstack rd.break
```

This is the output of `cat /proc/cmdline`.

This is the image that I tried: `fedora-coreos-30.20190801.0-openstack.qcow2`.

**Comment by brtknr** [comment]
I manually edited the grub command line arg to include `ignition.firstboot` and it appears to have placed in my user data successfully but this was what I saw when I logged in:
```
Fedora 30.20190801.0 (CoreOS preview)
Tracker: https://github.com/coreos/fedora-coreos-tracker
Preview release: breaking changes may occur

[systemd]
Failed Units: 2
  ignition-firstboot-complete.service
  NetworkManager-wait-online.service
[core@focus3 ~]$ sudo systemctl status ignition-firstboot-complete
● ignition-firstboot-complete.service - Mark boot complete
   Loaded: loaded (/usr/lib/systemd/system/ignition-firstboot-complete.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-09-06 13:13:35 UTC; 1min 9s ago
     Docs: https://github.com/coreos/ignition
  Process: 1663 ExecStart=/bin/sh -c mount -o remount,rw /boot && rm /boot/ignition.firstboot (code=exited, status=1/FAILURE)
 Main PID: 1663 (code=exited, status=1/FAILURE)

Sep 06 13:13:35 localhost systemd[1]: Starting Mark boot complete...
Sep 06 13:13:35 localhost sh[1663]: rm: cannot remove '/boot/ignition.firstboot': No such file or directory
Sep 06 13:13:35 localhost systemd[1]: ignition-firstboot-complete.service: Main process exited, code=exited, status=1/FAILURE
Sep 06 13:13:35 localhost systemd[1]: ignition-firstboot-complete.service: Failed with result 'exit-code'.
Sep 06 13:13:35 localhost systemd[1]: Failed to start Mark boot complete.
```

**Comment by lucab** [comment]
Thanks for the report.
It looks like the reason why you are seeing issues is:
> '/boot/ignition.firstboot': No such file or directory

Root cause could be either some problems in finding the /boot partition, or a problem on our side when assembling the image.

**Comment by lucab** [comment]
Also, just to be sure: is this a pristine image, written to a pristine machine, which was not booted before? The missing file is removed on the first boot, so it could have been delete by a previous boot if the image is being re-used.

**Comment by brtknr** [comment]
I'm pretty sure its a pristine image written to a pristine machine. I didn't tamper with the image in any way.

**Comment by dustymabe** [comment]
Thanks @brtknr for the report.

Anyone have access to an openstack environment where they can sanity check the openstack images?

**Comment by brtknr** [comment]
@dustymabe FYI the same image works fine on VM OpenStack instance... guess there's something missing for baremetal? I can add your key to a VM OpenStack instance if that's any help but I suspect not.

**Comment by dustymabe** [comment]
@brtknr - hmm. your most recent comment raises some questions for me:

- can you link to the exact image you downloaded?
- can you briefly describe exactly how you got the image into openstack and started a instance using that image?

**Comment by brtknr** [comment]
Link to the image I downloaded: https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/30.20190801.0/x86_64/fedora-coreos-30.20190801.0-openstack.qcow2.xz

I ran `unxz` against the image to unpack it.

This is the glance command I ran to upload the image:
```
 openstack image create --container-format=bare --disk-format=qcow2 --file fedora-coreos-30.20190801.0-openstack.qcow2 FedoraCoreOS30
```

Then to create the instance:
```
 openstack server create --image FedoraCoreOS30 --flavor compute-A --network ilab --config-drive True --user-data /opt2/bharat/user-data.ign focus3
```

**Comment by dustymabe** [comment]
@brtknr, thanks for the details. OK one other followup question:

> the same image works fine to boot up a VM based OpenStack instance... guess there's something missing for baremetal?

Are you saying you have different types of instances in openstack. Some of them are VM instances and some are bare metal instances (not virtualized)? And.. that the VM instances work, but the bare-metal instances don't?

**Comment by brtknr** [comment]
This instance of OpenStack only has baremetal flavors. I was able to use the same image on another instance of OpenStack which only has virtualised flavors. I have not tested this on an OpenStack deployment that supports both. But Yes, VM version works and Baremetal doesn't. We have been able to use other off the shelf cloud images... like the Fedora Atomic image on the baremetal image without issues. In fact, even the CoreOS image boots up fine... it just seems to be missing something for injecting the `ignition.firstboot` arg.

**Comment by dustymabe** [comment]
When you upload an image into glance that is for a baremetal type do you know if openstack does anything to the image to prepare it for boot on a baremetal server? Basically grub needs to run and the file `/boot/ignition.firstboot` needs to exist.

**Comment by dustymabe** [comment]
In AWS you can boot an instance and then mount up a disk image (i.e. ebs snapshot of an AMI) to it and inspect the contents. Can you do the same in openstack? If so boot up any flavor of linux on that bare metal server and then attach a snapshot and mount up the filesystems. On the boot partition you should see an `ignition.firstboot` file.

**Comment by brtknr** [comment]
When I redownloaded the image and tried again, it worked! I completely forgot about an episode when I tried to boot up the same image with QEMU to check that it worked before uploading the same image to Glance without taking note of the fact that QEMU would have modified the qcow2 file. Thanks for walking me through it. I hereby announce Fedora CoreOS 30 `baremetal certified` :D

**Comment by dustymabe** [comment]
Thanks @brtknr for the update and closing out the ticket.

I wonder if there is something we can do to make it more clear to us when this has happened. @lucab - WDYT about us adding a clue to the kernel command line to let us know that ignition completed in the past. Here's a proposal:

- [stop using the dynamic code in grub to populate `ignition.firstboot`](https://github.com/coreos/fedora-coreos-tracker/issues/191#issuecomment-519647513), so we don't use a `/boot/ignition.firstboot` but rather hardcode `ignition.firstboot` when we build the images.
- in `ignition-firstboot-complete.service` we update the kernel CLI parameter to be `ignition.firstboot=completed`, which will be a no-op for future boots, but will let us know clearly that the instance has been booted before and ignition did run. 


bikeshedding on the naming we could use `ignition.firstboot=true` and `ignition.firstboot=false`.

**Comment by dustymabe** [comment]
cc @bgilbert @ajeddeloh

**Comment by bgilbert** [comment]
We'd have to do that behind rpm-ostree's back, right?  Otherwise there'd still be a deployment with `ignition.firstboot=true`.

We could have ignition-firstboot-complete write a file in `/etc`.  But maybe the better approach is to ask users for the output of `journalctl -t ignition`, which will still be available after subsequent boots.

**Comment by brtknr** [comment]
For one to access the journalctl logs, one needs to have ignition inject user data... which it can't do if it hasn't run as was the case for me.

**Comment by dustymabe** [comment]
> We'd have to do that behind rpm-ostree's back, right? Otherwise there'd still be a deployment with `ignition.firstboot=true`.

We established that [the BLS configs are the source of truth](https://github.com/coreos/fedora-coreos-tracker/issues/191#issuecomment-523636735), right? Colin [notes](https://github.com/coreos/fedora-coreos-tracker/issues/191#issuecomment-523657594) that *"Anyways at least for operating when ostree isn't running, editing the BLS config seems OK."*. 

> 
> We could have ignition-firstboot-complete write a file in `/etc`. But maybe the better approach is to ask users for the output of `journalctl -t ignition`, which will still be available after subsequent boots.

As @brtknr [pointed out ](https://github.com/coreos/fedora-coreos-tracker/issues/267#issuecomment-528966066) that doesn't really help us in this case.
