### ISSUE TITLE
rpm-ostree: AutomaticUpdates in status output is incorrect

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-tracker#271]
```
# rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20190801.0 (2019-08-01T13:54:21Z)
                    Commit: a9c8d66d3628d1b9b4c4690777e8b730d08329b4359410cb410a2003296af1ca
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
```

As the status output above shows, a user may be deceived by the `AutomaticUpdates: disabled` label, while instead auto-updates are working but driven by an external "update driver" (like [Zincati](https://github.com/coreos/zincati)).

This is an umbrella tracking ticket, as there are two sides that need to be fixed:
 - [x] rpm-ostree https://github.com/projectatomic/rpm-ostree/issues/1747
 - [x] zincati https://github.com/coreos/zincati/issues/132

**Comment by miabbott** [comment]
It would be nice if `rpm-ostreed.conf` on FCOS had some info about using `zincati`, too.  See coreos/fedora-coreos-config#181

**Comment by dustymabe** [comment]
At least we will no longer be printing the `AutomaticUpdates` in the status output of `rpm-ostree` soon: https://github.com/coreos/rpm-ostree/pull/2065

Thanks @cgwalters !

**Comment by kelvinfan001** [comment]
rpm-ostree side implemented: https://github.com/coreos/rpm-ostree/pull/2459

**Comment by kelvinfan001** [comment]
Zincati side is mostly complete; waiting for new rpm-ostree release before merging. https://github.com/coreos/zincati/pull/450

**Comment by kelvinfan001** [comment]
[Zincati 0.0.19](https://github.com/coreos/zincati/releases/tag/v0.0.19) has been in stable since version 33.20210412.3.0 released on Apr. 27, 2021.
