### ISSUE TITLE
Wrong permissions for top directories

### ISSUE THREAD

**Issue by yuvalturg** [coreos/fedora-coreos-tracker#272]
When composing a coreos image, if the workdir (mkdir ./fcos in cosa) permissions are set to 750 (as in mktemp -d), the top-level directories in the image will inherit the same permissions.  The system will boot, but it won't let crucial services run correctly.  We should document this right before `setfacl`, or change rpm-ostree's init_rootfs or glnx_ensure_dir to chmod the directories to the desired mode

**Comment by cgwalters** [comment]
Thanks!  I think this is a bug in rpm-ostree's `init_rootfs` as you say.  `glnx_ensure_dir` should respect `umask` as it's more general.

(In theory, we should potentially be using the `filesystem` RPM's permissions but...eh)

**Comment by cgwalters** [comment]
PR in https://github.com/projectatomic/rpm-ostree/pull/1902

**Comment by dustymabe** [comment]
since this was [fixed upstream](https://github.com/coreos/rpm-ostree/pull/1902) it will flow into FCOS. Going to close this out.
