### ISSUE TITLE
Add support for Alibaba Cloud

### ISSUE THREAD

**Issue by ashcrow** [coreos/fedora-coreos-tracker#276]
In order to properly support this, we should:

- [x] reserve and document a platform ID for this environment: https://github.com/coreos/fedora-coreos-docs/pull/12
- [x] check if we have some metadata endpoint (or hypervisor back-channel) available for Ignition to use
- [x] add support for Ignition: https://github.com/coreos/ignition/pull/869
- [x] add support in coreos-assembler to buildextend images for this platform
- [x] add support for ore to upload images https://github.com/coreos/mantle/pull/1066
- [x] add support for Afterburn: https://github.com/coreos/afterburn/pull/283

/cc @imcleod

**Comment by jlebon** [comment]
Just going to dump some info from perusing the documentation.

---

>  add support in coreos-assembler to buildextend images for this platform

[Looks like qcow2 is supported and recommended](https://www.alibabacloud.com/help/doc-detail/57187.htm), so this should be more or less the same thing as `cosa buildextend-openstack`.

---

> check if we have some metadata endpoint (or hypervisor back-channel) available for Ignition to use

Looks like a vanilla user-data endpoint. From the [docs](https://www.alibabacloud.com/help/doc-detail/49121.htm):

> You can use user data of an ECS instance to customize its startup behavior and to pass data into the instance.
> ...
> For Linux, run `curl http://100.100.100.200/latest/user-data` to view the user data. 

---

>  add support for ore to upload images

Seems to follow the AWS model of uploading the image into their storage service, then calling to the compute service to import from there ([docs](https://www.alibabacloud.com/help/doc-detail/25464.htm)).

---

>  add support for afterburn if needed

[SSH keys are supported](https://www.alibabacloud.com/help/doc-detail/51796.html). The docs don't say at what endpoint they're available, but cloud-init has:

```python
class DataSourceAliYun(EC2.DataSourceEc2):
    ...
    metadata_urls = ['http://100.100.100.200']
    ...
    def get_hostname(self, fqdn=False, resolve_ip=False, metadata_only=False):
        return self.metadata.get('hostname', 'localhost.localdomain')

    def get_public_ssh_keys(self):
        return parse_public_keys(self.metadata.get('public-keys', {}))
```

**Comment by jlebon** [comment]
Do we need to discuss this in a community meeting re. whether we want to support it in FCOS? RHCOS definitely will; it would be good for FCOS to lead.

**Comment by dustymabe** [comment]
> Do we need to discuss this in a community meeting re. whether we want to support it in FCOS?

I don't think so. Maybe we can FYI everyone on it but IMO the more platforms the better.

**Comment by ashcrow** [comment]
>> Do we need to discuss this in a community meeting re. whether we want to support it in FCOS?

> I don't think so. Maybe we can FYI everyone on it but IMO the more platforms the better.

That's my thought as well. Unless there is a reason to not support it I think supporting it in FCOS would be great!

**Comment by lucab** [comment]
For Afterburn purposes, the metadata endpoint and content is documented at https://www.alibabacloud.com/help/doc-detail/49122.htm.

**Comment by lucab** [comment]
For reference, terraform supports this cloud platform under the provider name `alicloud`: https://www.terraform.io/docs/providers/alicloud/index.html. I think we can align ourselves to that as the platform label.

**Comment by bgilbert** [comment]
@lucab: We normally avoid having noise like "cloud" in our platform names, and we don't actually need to align with Terraform.

**Comment by ashcrow** [comment]
@bgilbert Would `alibaba` make more sense?

**Comment by bgilbert** [comment]
Maybe.  I guess the thing that seems odd is abbreviating Alibaba but also adding in `cloud`.  If it's commonly called Alicloud and people will recognize that name, then that's likely the name we should use.  But it's not clear to me how common that usage is?

It's not as simple as just naming the platform after the vendor, since we're not fully consistent here; we have `digitalocean` and `packet` but also `aws` and `gcp`.

**Comment by ashcrow** [comment]
@bgilbert Got it. I did some searching to see if I could find a proper short name for Alibaba's Cloud but nothing came up. Most seem to call it "Alibaba Cloud".

**Comment by jlebon** [comment]
FWIW, cloud-init uses [`AliYun`](https://github.com/cloud-init/cloud-init/blob/571f7c36e89f67f4c2d1cacfd8f9269bf864d560/cloudinit/sources/DataSourceAliYun.py#L12). Not that we *need* to align there too, but (1) [the initial implementation (and hence naming)](https://github.com/cloud-init/cloud-init/commit/4f8ceffb2e3a9feefcb718bda7a7f0f21ef7ab7c) was done by someone who works there it seems, and (2) if there's ever another "platform" on Alibaba, cloud-init would likely have to add a new ID too.

**Comment by arithx** [comment]
FWIW there go sdk is [`Alibaba Cloud SDK for Go`](https://github.com/aliyun/alibaba-cloud-sdk-go) with `aliyun` being the org.

**Comment by bgilbert** [comment]
From Wikipedia and from poking around a bit on their website, I think the situation is: Ālǐyún is the pinyin for the Chinese name, Ali Cloud is the literal translation, and Alibaba Cloud is the English branding.

The official CLI is named `aliyun`.

**Comment by ashcrow** [comment]
`aliyun` :+1:

**Comment by ashcrow** [comment]
* Platform ID: `aliyun`
* Metadata Endpoint/Back channel: `http://100.100.100.200/latest/meta-data/ `
    * Docs: https://www.alibabacloud.com/help/doc-detail/49122.htm
    * Terraform Example: https://www.terraform.io/docs/providers/alicloud/index.html#ecs-role

**Comment by ashcrow** [comment]
>  reserve and document a platform ID for this environment

Is there a current location we keep track of the `platformid`'s?

**Comment by lucab** [comment]
@ashcrow I have this currently in flight https://github.com/coreos/fedora-coreos-docs/pull/11.

**Comment by ashcrow** [comment]
> @ashcrow I have this currently in flight [coreos/fedora-coreos-docs#11](https://github.com/coreos/fedora-coreos-docs/pull/11).

Perfect!!

**Comment by ashcrow** [comment]
Doc PR: https://github.com/coreos/fedora-coreos-docs/pull/12

**Comment by lucab** [comment]
Misc self-notes from my exploration of the API so far:
 * if no user-data is provided when creating an instance, the endpoint returns 404 (instead of an empty body)
 * I set up a single ssh-pubkey, but the API returns two entries for it (with the same content)
 * docs differ across language, and the English one lacks a few metadata entries (e.g. `instance/instance-type`)

**Comment by jlebon** [comment]
OK, we got all the prereqs in place. If we want to get FCOS there, we need to work out the legal stuff to get a Fedora account there.

**Comment by jlebon** [comment]
We could also just publish the artifacts for now so at least folks can upload to their own accounts.

**Comment by ashcrow** [comment]
> We could also just publish the artifacts for now so at least folks can upload to their own accounts.

That would be a good starting point for FCOS artifacts.

**Comment by lucab** [comment]
Just to recap, is the final goal of this ticket to "upload artifacts to FCOS bucket" or to "upload artifacts to Alibaba cloud"? (Is that decided yet?)

In both cases, should we add one last task in here to write a "Booting on Alibaba Cloud" doc?

**Comment by ashcrow** [comment]
This card is for the tools in place for the OS teams to utilize. In terms of uploading to `$LOCATION`, those would be other issues/cards IMHO.
