### ISSUE TITLE
Add support for IBM Cloud

### ISSUE THREAD

**Issue by ashcrow** [coreos/fedora-coreos-tracker#277]
In order to properly support this, we should:

- [x] reserve and document a platform ID for this environment
- [x] check if we have some metadata endpoint (or hypervisor back-channel) available for Ignition to use
- [ ] add support in coreos-assembler to buildextend images for this platform
- [ ] add support for ore to upload images
- [ ] add support for afterburn if needed

/cc @imcleod

**Comment by ashcrow** [comment]
Keying off https://github.com/coreos/fedora-coreos-tracker/issues/276#issuecomment-534157670

there doesn't seem to be a provider for ["IBM Cloud" in Terraform](https://www.terraform.io/docs/providers/). How about we use `ibmcloud`?

**Comment by ashcrow** [comment]
cc @arithx @ajeddeloh @darkmuggle @vrutkovs @lucab

**Comment by ashcrow** [comment]
It looks like `ibm` is used for the provider via a [third party repo](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/examples/ibm-vsi-cloudinit/provider.tf#L13).

**Comment by ashcrow** [comment]
In terms of metadata endpoint I've found docs pointing to https://cloudinit.readthedocs.io/en/latest/topics/datasources/configdrive.html (which isn't really an endpoint ..). Still digging.

**Comment by arithx** [comment]
> It looks like ibm is used for the provider via a third party repo.

In that same link they also have a variable called `ibmcloud_api_key` so I don't think even that is sure what to call it.

I'd personally lean towards `ibmcloud`

**Comment by ashcrow** [comment]
> I'd personally lean towards ibmcloud

I do as well

**Comment by lucab** [comment]
cloud-init calls it `IBMCloud`. It seems to be a variant of `openstack-configdrive`.
https://github.com/cloud-init/cloud-init/blob/master/cloudinit/sources/DataSourceIBMCloud.py

**Comment by ashcrow** [comment]
> cloud-init calls it `IBMCloud`. It seems to be a variant of `openstack-configdrive`.
> https://github.com/cloud-init/cloud-init/blob/master/cloudinit/sources/DataSourceIBMCloud.py

Side note: That points to config drive as well instead of a metadata endpoint. So far I've been unable to find a metadata endpoint in the docs :slightly_frowning_face:.

**Comment by ashcrow** [comment]
The other day @darkmuggle found https://cloud.ibm.com/apidocs/vpc. However, I can't seem to fund a location for `user-data`. I'll continue to look a bit more, but I'm not optimistic that a traditional `user-data` enabled endpoint is provided.

**Comment by ashcrow** [comment]
Updating docs: https://github.com/coreos/fedora-coreos-docs/pull/15

**Comment by lucab** [comment]
The docs/URLs referenced in https://github.com/coreos/fedora-coreos-tracker/issues/277#issuecomment-542236841 are for the **Internet-public API**, not for **link-local metadata**.

According to current @ajeddeloh research, we think that there is no metadata endpoint on this cloud provider (which is consistent with the cloud-init implementation I linked above), but we are waiting for confirmation.

**Comment by ashcrow** [comment]
> I got confirmation on userdata, though I didn't explicitly ask about other metadata endpoints.

To clarify, the confirmation is there is no endpoint for userdata and `ConfigDrive` is the expected solution, correct?

**Comment by ajeddeloh** [comment]
Correct

**Comment by lucab** [comment]
Misc notes from my exploration of the API so far.

In my IBM cloud console I see there are three types of infrastructure/compute-node available.
Each one has a specific and very different approach to networking:
 * classic: no DHCP, multiple interfaces, no NAT, legacy interface naming (ethX)
 * VPC gen1: no DHCP, single interface, NAT, legacy interface naming (eth0)
 * VPC gen2: DHCP, single interface, NAT, predictable interface naming (ens3)

None of those of seems to to have reachable link-local metadata endpoint. They all have a local config-drive, however location and content is **NOT** uniform:
 * classic and gen1: traditional openstack-like VFAT disk with JSON files
 * gen2: iso9660 disk (labeled `cidata`) with `user-data` and `meta-data` files. The latter consists of multiple lines in `key-name: value` format.

**Comment by ashcrow** [comment]
`classic` and `VPC Gen 2` should be supported. It may be worth having different platform id's for these so we can tell them apart easily. Thoughts?

**Comment by ajeddeloh** [comment]
Having both under one name isn't a problem from the Ignition side. We can do it like the openstack provider and just try both at the same time and see which one succeeds.

**Comment by ajeddeloh** [comment]
Thinking about this more though, we'd need to more for classic to bring up networking in the initramfs, so having it differentiated might be useful there. cc @lucab @bgilbert

**Comment by ashcrow** [comment]
> Thinking about this more though, we'd need to more for classic to bring up networking in the initramfs, so having it differentiated might be useful there. cc @lucab @bgilbert

cc'ing @darkmuggle as well

**Comment by darkmuggle** [comment]
Breaking the enablement into two separate "clouds" makes sense from a planning and implementation perspective.

**Comment by lucab** [comment]
After some more chatting and work planning, we decided to start with a reduced scope in order to break a few bootstrapping tasks in an easier way.
For the moment, we are scoping the `ibmcloud` platform ID to mean "VPC Gen2" only. Reference docs update at https://github.com/coreos/fedora-coreos-docs/pull/16.

Once we get to a reasonable state with "VPC Gen2", we will re-evaluate "classic" infrastructure next and decide whether it is feasible and better (from a technical point of view) to use the same platform ID for both. If not, we'll need to note down the new constraints and start work under a new platform ID.

**Comment by lucab** [comment]
Reached a further decision point on the chimera-cloud situation, input on https://github.com/coreos/coreos-assembler/issues/1119 appreciated.

**Comment by dustymabe** [comment]
I broke out the ore/kola work into #614

**Comment by dustymabe** [comment]
A few new PRs

- https://github.com/coreos/coreos-assembler/pull/1740
- https://github.com/coreos/fedora-coreos-pipeline/pull/280

Updated https://github.com/coreos/fedora-coreos-tracker/issues/277#issuecomment-678677137 to reflect current status.

**Comment by dustymabe** [comment]
A few more new PRs

- https://github.com/coreos/fedora-coreos-releng-automation/pull/124
- https://github.com/coreos/fedora-coreos-stream-generator/pull/13
- https://pagure.io/fedora-web/websites/pull-request/149

**Comment by dustymabe** [comment]
and a few final ones:

- https://github.com/coreos/fedora-coreos-browser/pull/17
- https://github.com/coreos/fedora-coreos-docs/pull/185

**Comment by dustymabe** [comment]
This is pretty much all done. See updated checklist in https://github.com/coreos/fedora-coreos-tracker/issues/277#issuecomment-678677137

The only thing left is me pushing the merge button on the docs PR, which we'll do when the round of releases goes out this week.

**Comment by dustymabe** [comment]
The IBM Cloud images first landed in:

- stable stream release `32.20200923.3.0`
- testing stream release `32.20201004.2`
