### ISSUE TITLE
s390x: handle default minimal /etc/zipl.conf file

### ISSUE THREAD

**Issue by tuan-hoang1** [coreos/fedora-coreos-tracker#278]
When working on : https://github.com/coreos/ignition-dracut/issues/84 by telling ignition-dracut/systemd/ignition-firstboot-complete.service to re-run zipl, I run into this new issue : zipl requires a minimal /etc/zipl.conf file to be present in target FCOS system along with existing BLS files. It might look like this : 
```
[defaultboot]
defaultauto
prompt=1
timeout=5
target=/boot
```

There are a couple of ways to do this:
1. Generate it in fedora-coreos-config via `postprocess:` thanks to rpm-ostree's `arch-include` feature  (courtersy of @cgwalters ).
2. Generate during `cosa build` and/or `cosa buildextend-metal` in `create_disk.sh`.
3. Generate via `ignition-dracut` at installation time.
4. Patch zipl to with cmdline option like `--minimal-conf` to assume above 5 options. (https://github.com/ibm-s390-tools/s390-tools/issues/70).

@cgwalters raised the concern if /etc/zipl.conf is updated by other forces (i.e. anaconda). @martinezjavier suggested it has been minimal and static/stable like that for some time now. He will talk with anaconda and @sharkcz and come to the conclusion of which path is chosen. @tuan-hoang1 said option 4. could be good to go.

**Comment by lucab** [comment]
For reference, this is in progress at https://github.com/ibm-s390-tools/s390-tools/pull/71.

**Comment by tuan-hoang1** [comment]
Upstream merged. Backporting in process.

**Comment by tuan-hoang1** [comment]
Small note. RHCOS uses anaconda and anaconda generates /etc/zipl.conf as usual. No need for this.

**Comment by cgwalters** [comment]
>  RHCOS uses anaconda

In OpenShift 4.2, but not as of 4.3 development - we have unified with FCOS.

**Comment by tuan-hoang1** [comment]
Correct.
