### ISSUE TITLE
python3 getting pulled in by crypto-policies

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#280]
In rawhide right now we grew a dependency on python again:

```
[root@coreos ~]# rpm -e python3
error: Failed dependencies:
        /usr/bin/python3 is needed by (installed) crypto-policies-20190816-3.gitbb9bf99.fc32.noarch
```

Looks like we need to dig into why `crypto-policies` now requires python3.

**Comment by dustymabe** [comment]
This is the case in f31 as well.

**Comment by lucab** [comment]
The underlying reason is that `/usr/bin/update-crypto-policies` has been rewritten (from bash to python3) circa one month ago: https://gitlab.com/redhat-crypto/fedora-crypto-policies/commit/1d527f5d8be544ba5b394bd37f66fafcddb6a0c4#c79ed67fb72b2d57acc8874b18106d8891510f68

**Comment by dustymabe** [comment]
and `crypto-policies` is needed by:

```
[core@coreos ~]$ rpm -e crypto-policies
error: Failed dependencies:
        crypto-policies >= 20180730 is needed by (installed) openssl-libs-1:1.1.1d-1.fc31.x86_64
        crypto-policies is needed by (installed) gnutls-3.6.9-1.fc31.x86_64
        crypto-policies >= 20180306-1 is needed by (installed) openssh-clients-8.0p1-8.fc31.1.x86_64
        crypto-policies >= 20180306-1 is needed by (installed) openssh-server-8.0p1-8.fc31.1.x86_64
        /etc/crypto-policies/back-ends/krb5.config is needed by (installed) krb5-libs-1.17-40.fc31.x86_64
```

**Comment by ajeddeloh** [comment]
I've been doing some digging. It looks like this package is composed of two parts:
1) a bunch of configuration for various packages to set different options related to which crypto algorithms to use. These are included in the rpm (not generated on the fly)
1) a script to enable or switch between them (now in python)

I think it's probably worth investigating if we can get the latter split out into a subpackage and not include it, then support what the script is doing in FCCT. Something like:

```
crypto_policy: fips
```

Using the script is somewhat of an antipattern for FCOS since all it does is write/link configs.

Thoughts?

**Comment by ajeddeloh** [comment]
Filed a bug upstream about splitting out the package: https://bugzilla.redhat.com/show_bug.cgi?id=1755629

**Comment by dustymabe** [comment]
We had been holding a release trying to get this in (so we didn't ship python3). We [decided in the meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/GBBVEL24RIZDJAUY7MCUK4Z27X67JJZF/) to go ahead and release while the work on this continues.

**Comment by dustymabe** [comment]
I tested https://src.fedoraproject.org/rpms/crypto-policies/pull-request/6# with a scratch build and python3 is gone!

```
Upgraded:                                     
  crypto-policies 20191128-2.gitcd267a5.fc31 -> 20191128-3.gitcd267a5.fc32                                            
Removed:                                    
  gdbm-libs-1:1.18.1-1.fc31.x86_64         
  python-pip-wheel-19.1.1-7.fc31.noarch      
  python-setuptools-wheel-41.2.0-1.fc31.noarch                                                                        
  python3-3.7.5-2.fc31.x86_64                   
  python3-libs-3.7.5-2.fc31.x86_64
```
