### ISSUE TITLE
rpm-ostreed fails to start on live systems

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#281]
rpm-ostreed refuses to start on live systems:

```
Sep 21 03:44:21 live systemd[1]: Starting RPM-OSTree System Management Daemon...
Sep 21 03:44:21 live rpm-ostree[1050]: Reading config file '/etc/rpm-ostreed.conf'
Sep 21 03:44:21 live rpm-ostree[1050]: error: Couldn't start daemon: Error setting up sysroot: Unexpected state: /run/ostree-booted found and in / sysroot but not in a booted deployment
Sep 21 03:44:21 live systemd[1]: rpm-ostreed.service: Main process exited, code=exited, status=1/FAILURE
```

As a consequence, commands like `rpm-ostree status` time out.

Upstream as https://github.com/ostreedev/ostree/issues/1921.

**Comment by keithy** [comment]
rpm-ostree still doesnt appear to be working at all in live images, everything timesout

**Comment by jlebon** [comment]
This is fixed now. I.e. `rpm-ostree status` works at least. (Though there's still the larger issue of teaching ostree about live systems; let's leave that in https://github.com/ostreedev/ostree/issues/1921.)
