### ISSUE TITLE
how to warn users about using `rpm-ostreed.conf` to configure updates

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#285]
Users familiar with `rpm-ostree` based systems may try to configure OS updates via `/etc/rpm-ostreed.conf`.

We want to steer folks to `zincati`, so how best to do that?

**Comment by miabbott** [comment]
See https://github.com/coreos/fedora-coreos-config/pull/181 where the default config file is massaged to have extra info.

**Comment by jlebon** [comment]
Can probably fold this back into #271?

**Comment by miabbott** [comment]
Sure; closing in favor of #271
