### ISSUE TITLE
python3-libs in latest testing/testing-devel builds pulled in by vim-minimal

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#289]
Noticed this while doing a release:

```
[root@coreos ~]# rpm -qa | grep python
python-pip-wheel-19.0.3-3.fc30.noarch
python-setuptools-wheel-40.8.0-1.fc30.noarch
python3-libs-3.7.4-1.fc30.x86_64
[root@coreos ~]# rpm -e python3-libs
error: Failed dependencies:
        libpython3.7m.so.1.0()(64bit) is needed by (installed) vim-minimal-2:8.1.1991-2.fc30.x86_64
```

Not so bad of course, since `/usr/bin/python3` itself is not present. But it's silly to have packages install Python scripts in the host if we don't even have the interpreter.

**Comment by zonggen** [comment]
Out of curiosity, is there anything we could do to prevent the python scripts pulled into host?

**Comment by dustymabe** [comment]
I don't think we have anything robust. We could:

- add tests (re-active)
- add a mechanism to rpm-ostree to enforce packages that match a regex don't get included (error out)

**Comment by miabbott** [comment]
@mike-nguyen added a test to `kola` to verify that `python` executables aren't on the host - https://github.com/coreos/mantle/commit/1a16ffd04201da8997ec710dd2eb01cabf2439b4

This could be expanded to be more aggressive with the checks for `python` related packages.

**Comment by keithy** [comment]
remove vim!

**Comment by jlebon** [comment]
> remove vim!

`vim-minimal` is what provides `vi` :)

Anyway, I filed https://bugzilla.redhat.com/show_bug.cgi?id=1769443.

**Comment by keithy** [comment]
It is still kind of large, one for the toolbox?

**Comment by dustymabe** [comment]
Now that the latest vim has [hit the fedora stable yum repos](https://bodhi.fedoraproject.org/updates/FEDORA-2019-0d118f9252) we can close this. The only thing depending on python3-libs now is python3 itself (which is another issue: #280):

```
[core@coreos ~]$ rpm -e python3-libs
error: Failed dependencies:
        libpython3.7m.so.1.0()(64bit) is needed by (installed) python3-3.7.5-1.fc31.x86_64
        python3-libs(x86-64) = 3.7.5-1.fc31 is needed by (installed) python3-3.7.5-1.fc31.x86_64
```
