### ISSUE TITLE
Fedora-CoreOS session on Fedora Classroom

### ISSUE THREAD

**Issue by siddharthvipul** [coreos/fedora-coreos-tracker#29]
*Everyone* is excited about Fedora-CoreOS.
It would be great if we can have a Fedora Classroom session on
* Introduction
* UseCase
* Getting started (contribution) with Fedora-CoreOS

Just had APAC meeting and I am sure the session can reach to a broader audience.

cc'ing @sinnykumari @prakashmishra1598

**Comment by sinnykumari** [comment]
Thanks @siddharthvipul for coming up with this nice idea.
To get better understanding, can you provide us with an example of any previous Fedora Classroom session done?

**Comment by siddharthvipul** [comment]
Sure,
https://fedoraproject.org/wiki/Classroom#Previous_Sessions -> Previous sessions (few of them are missing)
[Classroom wiki](https://fedoraproject.org/wiki/Classroom) has a table with upcoming sessions as well.

**Comment by prakashmishra1598** [comment]
I think we can do a series of sessions each covering a specific topic inside the domain of Fedora-CoreOS. The first 101 session can cover basic use cases and introduction to the project. The successive sessions can delve deeper into other topics in depth.

**Comment by prakashmishra1598** [comment]
I think we can do a series of sessions each covering a specific topic inside the domain of Fedora-CoreOS. The first 101 session can cover basic use cases and introduction to the project. The successive sessions can delve deeper into other topics in depth.

**Comment by sinnykumari** [comment]
In today's Fedora [CoreOS APAC meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/KZDFNFKPZPCVF2GMLP2LSZ7INP6FPSQJ/) we all agreed upon that it is too early for having a classroom session about Fedora CoreOS. We will do Fedora CoreOS classroom program once we have artifacts available officially on Fedora.

**Comment by c4rt0** [comment]
Closing this for now as there was no update here for the last 4 years.
