### ISSUE TITLE
Gateway timeout 504

### ISSUE THREAD

**Issue by jtligon** [coreos/fedora-coreos-tracker#291]
my box at home is getting these 504 errors
```
Oct 07 18:34:40 localhost zincati[749]: [ERROR] failed to check for updates: failed to query Cincinnati: https://updates.coreos.stg.fedoraproject.org/v1/graph?platform=qemu&basearch=x86_64&os_checksum=326dd9ef07f7ebf5dc862e263ad7ffa33cf58d2055ef48ea8e27b6a9c387ce19&group=default&os_version=30.20191002.0&stream=testing&node_uuid=0d71e252ed83459d8d3ef54f1aea7d31: Server Error: 504 Gateway Timeout

State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20191002.0 (2019-10-02T19:01:08Z)
                BaseCommit: 326dd9ef07f7ebf5dc862e263ad7ffa33cf58d2055ef48ea8e27b6a9c387ce19
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
           LayeredPackages: git

  ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20190905.0 (2019-09-05T14:36:50Z)
                BaseCommit: b4beca154dab3696fd04f32ddab818102caa9247ec3192403adb9aaecc991bd9
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
           LayeredPackages: Git
```

**Comment by jlebon** [comment]
Yeah, we've noticed this as well during the last release. It's likely due to the stage OpenShift cluster on which Cincinnati is hosted having flaky networking. Though @lucab was planning to investigate some more.

Note that Zincati keeps retrying, so it should go through once in a while at least and still apply any updates (as shown in the output here, assuming you were updated to `30.20191002.0` automatically).

**Comment by jtligon** [comment]
your assumption is correct, it did update.

**Comment by dustymabe** [comment]
Yeah.. I had the same issue. I assume the infra will clean up eventually and these will go away. Will leave the issue open for now but probably close it out after some time if people don't keep having the issues.

**Comment by lucab** [comment]
I'm self-assigning this, but I can properly investigate this only after some changes that are in Zincati master/0.0.6 hit a FCOS `testing` release. Marking it as blocked in the meanwhile.

**Comment by lucab** [comment]
For reference, my canary node since the last reboot has recorded the following metrics:
 * Total Cincinnati queries: ~1000
 * Code 200: 53.3%
 * Code 504: 46.6%
 * Code 503: 0.1%

**Comment by dustymabe** [comment]
Hitting this pretty consistently. My canary node has not yet updated to the 1014 release and it registers a 504 every 5 minutes in the zincati logs.

**Comment by dustymabe** [comment]
We should make sure we move to more reliable infrastructure before the stable FCOS release.

**Comment by lucab** [comment]
This seems to vary a lot over time. Situation over the last two days was slightly better, with ~20% rate of 504 and no other 5xx errors.

I also think I have a small bugfix on the server side to improve this case, but currently I cannot verify it as builds are broken cluster-wide: https://pagure.io/fedora-infrastructure/issue/8300.

**Comment by dustymabe** [comment]
> EDIT: bugfix deployed and cluster container runtime restarted at the same time; situation seemingly improved after those.

🥳

**Comment by dustymabe** [comment]
@lucab - considering your update in your last comment, can we close this?

**Comment by lucab** [comment]
@dustymabe I think we can, yes.

There are still two things that would be good to do under the "more reliable infrastructure" topic:
 1. move the code out of https://github.com/lucab/exp-dumnati (it served us well while developing, but we can move it to a more visible place now)
 1. deploy the pod to fedora-infra prod cluster

I'll follow up to both, in that order.
