### ISSUE TITLE
Have a dedicated lockfile updater for testing-devel and next-devel

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#293]
In https://github.com/coreos/fedora-coreos-tracker/issues/290, we discussed that the current model of inheriting the lockfile from `bodhi-updates` is limiting because it means that any regression causes `testing-devel` to stop consuming all updates. Instead, we should have the ability to freeze troublesome packages and keep consuming everything else.

[One mentioned solution](https://github.com/coreos/fedora-coreos-tracker/issues/290#issuecomment-539612227) was to instead have a dedicated lockfile bumper. At which point, `bodhi-updates` really just becomes a way to track FCOS - overrides.

And of course, we really want the lockfile bump workflow to be CI gated. But having daily/multiple PRs per day would probably get noisy and tiring fast. So one middle ground here is something like this:

- check out the latest `testing-devel`
- run `cosa fetch --update-lockfile`
- push updated lockfile to a staging branch, e.g. `testing-devel-staging`
- wait for CI to pass
- if it passes, then push into `testing-devel` (obviously being careful to handle races)
- if it fails, open a PR

@dustymabe mentioned also we could make it always open a PR under certain conditions, such as if some packages are added or dropped.

**Comment by jlebon** [comment]
Also need to watch for coreos-koji-tagger integration: https://github.com/coreos/fedora-coreos-releng-automation/issues/32

**Comment by dustymabe** [comment]
> * push updated lockfile to a staging branch, e.g. `testing-devel-staging`
> 
> * wait for CI to pass

A few questions:

- IIUC this implies that we have CI set up on the `testing-devel-staging` branch so we'd need a separate buildconfig set up for it in the fedora-coreos-pipeline repo?
- could we possibly just use a staging repo so we don't end up with branches in our config repo that may confuse people?

**Comment by jlebon** [comment]
> IIUC this implies that we have CI set up on the `testing-devel-staging` branch so we'd need a separate buildconfig set up for it in the fedora-coreos-pipeline repo?

This would be the Jenkins CI which already runs on PRs right now, not fedora-coreos-pipeline. They're related though, because we'll want to share much more between those to make gating more meaningful.

> could we possibly just use a staging repo so we don't end up with branches in our config repo that may confuse people?

Hmm, maybe. Though it'd only be one branch per "locked" stream, so e.g. `testing-devel-staging` and `next-devel-staging`. Seems OK? Definitely wouldn't be hard to e.g. make the bot use its fork though. A minor advantage of having it in the same repo means that it's easier to fetch and build locally when debugging issues.

**Comment by dustymabe** [comment]
> Definitely wouldn't be hard to e.g. make the bot use its fork though. 

+1 - I think I'd much prefer using a fork!

**Comment by jlebon** [comment]
OK the relevant patches here are:

https://github.com/coreos/rpm-ostree/pull/2058
https://github.com/coreos/fedora-coreos-config/pull/355

With those, we'll be able to make the updater code in https://github.com/coreos/fedora-coreos-releng-automation/pull/48 simply just do `cosa fetch --update-lockfile` the same way a developer would.

**Comment by jlebon** [comment]
This was fixed by https://github.com/coreos/fedora-coreos-pipeline/pull/229.
