### ISSUE TITLE
Should we include systemd-journal-remote?

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#294]
CL has it, FCOS currently doesn't.
Came up in https://github.com/coreos/mantle/pull/1089#discussion_r334091748.

**Comment by jlebon** [comment]
```
Added:
  firewalld-filesystem-0.6.5-1.fc30.noarch
  info-6.6-1.fc30.x86_64
  libmicrohttpd-1:0.9.66-1.fc30.x86_64
  systemd-journal-remote-241-10.git511646b.fc30.x86_64
...
# xargs rpm -q --qf '%{SIZE}\t%{NEVRA}\n'
239     firewalld-filesystem-0.6.5-1.fc30.noarch
611048  info-6.6-1.fc30.x86_64
211768  libmicrohttpd-1:0.9.66-1.fc30.x86_64
207789  systemd-journal-remote-241-10.git511646b.fc30.x86_64
```

Sizes aren't too scary (though the `firewalld-filesystem` and `info` packages getting pulled in is unfortunate).

So I guess it comes down to functionality/compatibility. Anyone with any notion of how widely used it was in CL? I see a few bugs in coreos/bugs at least mentioning it. Though of course, there's a bunch of containerized logging solutions already. Haven't used any of those much, so not sure how they compare. (Having it on the host though means it's not dependent on the container runtime working.)

**Comment by dustymabe** [comment]
> So I guess it comes down to functionality/compatibility. Anyone with any notion of how widely used it was in CL?

I don't know. @bgilbert ?

I don't have an opinion on including it for now. This could be one of those where we wait and see if people notice and ask for it back.

**Comment by dustymabe** [comment]
Closing this out. We'll stick with the status quo until somebody asks for it.
