### ISSUE TITLE
What coreos-assembler branches can we clean up?

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#297]
https://github.com/coreos/coreos-assembler/branches/all

```
  remotes/upstreamorigin/0.4.0-maipo
  remotes/upstreamorigin/alpha
  remotes/upstreamorigin/master
  remotes/upstreamorigin/pre-ignition-3
  remotes/upstreamorigin/prune-rewrite-f1
  remotes/upstreamorigin/revert-522-pr/nuke-hostname
  remotes/upstreamorigin/revert-831-install-backend
  remotes/upstreamorigin/rhcos
  remotes/upstreamorigin/rhcos-4.1
  remotes/upstreamorigin/rhcos-4.2
  remotes/upstreamorigin/rhcos-4.2-multiarch
  remotes/upstreamorigin/testing
```

**Comment by dustymabe** [comment]
cc @cgwalters @vrutkovs @darkmuggle @jlebon @lucab

**Comment by vrutkovs** [comment]
Removed `prune-rewrite-f1` - my mistake.

I'd say all except `rhcos-4.x`

**Comment by jlebon** [comment]
> I'd say all except `rhcos-4.x`

And `master` too right? :smile: 
But yeah, that makes sense to me!

**Comment by ashcrow** [comment]
We need the following at a minimum:

- master
- rhcos-4.1
- rhcos-4.2
- rhcos-4.2-multiarch

/cc @darkmuggle

**Comment by Prashanth684** [comment]
`rhcos-4.2-multiarch` was created specifically for multiarch changes so as to not destabilize x86 for the `rhcos-4.2` branch. This is only for the near future especially for s390x. We would not need it once we start multiarch on 4.3 i believe.

**Comment by darkmuggle** [comment]
Recapping the conversations:

- master
- rhcos-4.1
- rhcos-4.2
- rhcos-4.2-multiarch

:+1:

**Comment by dustymabe** [comment]
ok will clean up all other branches before the end of the day today. This gives some opportunity for others to chime in before if there are any we need to save.

**Comment by dustymabe** [comment]
ok deleted all other branches and added branch protection for the ones we care about.
