### ISSUE TITLE
PRD: Red Hat CoreOS upstream

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#30]
I think the Fedora CoreOS PRD should explicitly call out being the upstream for Red Hat CoreOS.

**Comment by ajeddeloh** [comment]
We should also be clear about what "upstream" means in our case.

**Comment by cgwalters** [comment]
> We should also be clear about what "upstream" means in our case.

That's a very complex topic; but roughly speaking...I'd expect it to boil down to much of the same things as the relationship between Fedora and Red Hat Enterprise Linux in general.

Now...IMO...some parts of that relationship are fairly dysfunctional :smile: but it's what we have.

I'd say at a high level at least:

 - Being the entrypoint for FOSS contribution
 - Shipping newer features first, and be willing to drop them if they don't work out - on a shorter lifecycle than downstream

**Comment by dustymabe** [comment]
I'm not opposed. Would you like to open a PR  to https://github.com/coreos/fedora-coreos-tracker/blob/master/PRD.txt

**Comment by dustymabe** [comment]
@cgwalters ^^

**Comment by dustymabe** [comment]
closing this out.. please open a PR if you'd like
