### ISSUE TITLE
Implement versioning scheme

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#301]
Tracker issue to actually implement the versioning scheme decided upon in #81 and #211.

**Comment by dustymabe** [comment]
@jlebon, done?

**Comment by jlebon** [comment]
Yup!

**Comment by jlebon** [comment]
For posterity:

https://github.com/coreos/fedora-coreos-releng-automation/pull/50
https://github.com/coreos/fedora-coreos-pipeline/pull/154
