### ISSUE TITLE
Unable to Login to Basic Image

### ISSUE THREAD

**Issue by keithy** [coreos/fedora-coreos-tracker#306]
Booting 30.20191014.0 LiveCD in VirtualBox.
Downloaded and mounted the raw image at /opt/image.raw.xz

Ran coreos-installer via a mounted script:
/usr/libexec/coreos-installer -d sda -b file:///opt/image.raw.xz -i skip

The result is a machine that boots and presents a login: prompt but I cant log into it.

I tried hitting tab very quickly at boot (why is it so quick?) and added coreos.autologin=tty1 which didnt seem to help.

**Comment by bgilbert** [comment]
You skipped specifying an Ignition config, so you ended up with the default `core` user with no SSH keys and no password.  On cloud platforms, SSH keys are automatically imported from the cloud provider, but on VirtualBox the only way to configure authentication is via Ignition.

**Comment by keithy** [comment]
And that doesnt work either!

**Comment by keithy** [comment]
OK so supplying pasword_hash works! 
It only took 2 days to work out that if you provide "password_hash" (for console) and ssh_authorized_keys (for remote) does not work for console login.
If you do provide only "password_hash" then password login via ssh is disabled!

**Comment by bgilbert** [comment]
There are specific reasons you might not want an Ignition config.  Most people will, though.

Could you post the config with the password hash that doesn't work for you?  Does the machine still boot to a login prompt in that case?

**Comment by bgilbert** [comment]
Yeah, we disable SSH password login by default; see #138.  We'll document that better once we have more documentation.

**Comment by keithy** [comment]
You guys are far too clever. When something is not working, you get it working and invistigate the settings. So I removed the ignition config and cant login, this is a bug, not a feature.

**Comment by bgilbert** [comment]
We do need better documentation in this area.  The [getting-started guide](https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/) does talk about creating Ignition configs, but we'll need to be more explicit that an Ignition config is fundamental to launching a Fedora CoreOS system.  Stay tuned for more and better documentation in the next couple months, and thanks for bearing with us.
