### ISSUE TITLE
Can't change password for a user complains about missing dictionary

### ISSUE THREAD

**Issue by keithy** [coreos/fedora-coreos-tracker#308]
So I add a user to the wheel group, and sudo requires a password.
Attempting sudo passwd usename fails due to missing dictionary.

**Comment by dustymabe** [comment]
hey @keithy - can you provide the ignition config you are using and a few steps that you execute on the booted system that illustrate the problem you are having?

**Comment by keithy** [comment]
At the time I raised the report I do not think that my ignition file contained anything.

I am just trying to change the password via #> /usr/bin/passwd
```
/usr/share/cracklib/pw_dict.pwd.gz: No such file or dictionary
BAD PASSWORD: The password fails the dictionary check - error leading dictionary
```

**Comment by dustymabe** [comment]
> At the time I raised the report I do not think that my ignition file contained anything.

weird. how did you get in to the system?

**Comment by keithy** [comment]
The problem is present on the liveCD, if you use `> sudo passwd`
You are correct at that time I had managed to add an ssh-key as my user login, but my attempts to set password_hash were failing.

**Comment by bgilbert** [comment]
I can reproduce this on 20191014:

1. Set a password for the `core` account, e.g. using Ignition.
2. From the `core` account, run `passwd`.
3. Enter a password that passes other validation checks, e.g. is not a palindrome or too short.

```
[core@localhost ~]$ passwd
Changing password for user core.
Current password: 
New password: 
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
BAD PASSWORD: The password fails the dictionary check - error loading dictionary
New password: 
```

**Comment by bgilbert** [comment]
Thanks for the report.  https://github.com/coreos/fedora-coreos-config/pull/221 should fix it.

**Comment by dustymabe** [comment]
> Thanks for the report. [coreos/fedora-coreos-config#221](https://github.com/coreos/fedora-coreos-config/pull/221) should fix it.

I was able to get this to work in a local build+test. Fixed!
