### ISSUE TITLE
python3-libs is preventing use of overlays

### ISSUE THREAD

**Issue by keithy** [coreos/fedora-coreos-tracker#315]
The 30.20191014.0 (current) release of the LiveCD/raw has python3-libs 3.7.4-1.fc30

This raises errors when you attempt to install many additional packages which refuse to load via rpm-ostree due to python3-libs 3.7.4-1.fc30 -> 3.7.5-1.fc30 (updates)

Could it be time for a new relase of LiveCD (fedora 31?) either with the newer version of python3-libs, or none at all.

**Comment by dustymabe** [comment]
A new vim package just got cut so I believe python3-libs will not be in the next release of FCOS. Stay tuned.

**Comment by dustymabe** [comment]
ok I lied because https://github.com/coreos/fedora-coreos-tracker/issues/280 is also still outstanding

**Comment by keithy** [comment]
As long as the python libs was the later version this problem would be fixed.

**Comment by keithy** [comment]
Fixed in 31.20191127.1

**Comment by lucab** [comment]
For reference, this will likely come back as soon as we slowly start drifting away from Fedora-updates python3-libs.
The final way out of this is fixing https://github.com/coreos/fedora-coreos-tracker/issues/280.
