### ISSUE TITLE
Provide a standard way to change kernel command line options via Ignition

### ISSUE THREAD

**Issue by martinpitt** [coreos/fedora-coreos-tracker#318]
EDIT: Current solution: https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/

---

On FCOS there is no official way how to change the kernel command line, e. g. the `mitigations=auto,nosmt` option. The only place where they occur is in /boot/loader.0/entries/ostree-{1,2}-fedora-coreos.conf, but that's not very predictable, nor is it clear whether modifying these will also apply to installing kernel updates.  Right now, none of the standard mechanisms (grubby, /etc/default/grub, /boot/grub/grubenv) are available.

Background: In Cockpit we have a UI for detecting/enabling/disabling the `nosmt` option. Changing a kernel command line option is annoyingly hard, we have quite an [elaborate script](https://github.com/cockpit-project/cockpit/blob/master/pkg/systemd/kernelopt.sh) for that.

Could grubby be added to FCOS images, or if not, what's the recommended way to persist kernel options? Thanks!

**Comment by lucab** [comment]
Thanks for the report.
On FCOS, rpm-ostree owns the kernel command-line arguments. This is exposed to consumer via `rpm-ostree kargs` (or DBus).

That said, I agree the UX here could be enhanced by:
 * supporting default dropins, see https://github.com/ostreedev/ostree/pull/1836
 * adding a page to [FCOS docs](https://github.com/coreos/fedora-coreos-docs) describing how kargs are handled

**Comment by martinpitt** [comment]
`rpm-ostree kargs` sounds promising, I'll have a look at that. Thank you!

**Comment by cgwalters** [comment]
https://github.com/coreos/rpm-ostree/pull/1789 also redirects `grubby`.

**Comment by martinpitt** [comment]
I added rpm-ostree kargs to [cockpit's kernelopt.sh script](https://github.com/cockpit-project/cockpit/pull/13167), now this works great on FCOS. Thanks for your help!

**Comment by cgwalters** [comment]
Just to xref this, for RHCOS (OpenShift) we support [kernelArguments in MachineConfig](https://github.com/openshift/machine-config-operator/blob/8fa45661c50047de097db3ed7592e48910bfe401/docs/MachineConfiguration.md#kernelarguments).

**Comment by cgwalters** [comment]
Going to reopen this since I think we do want to standardize an Ignition method for this for FCOS and ideally have that same method apply to RHCOS.

**Comment by cgwalters** [comment]
For anyone who wants to change kargs today with FCOS, you'll basically need to write a systemd unit that runs `rpm-ostree kargs --append`, and you'll also need to use e.g. `ConditionFirstBoot=yes`.

**Comment by kelvinfan001** [comment]
> I think we do want to standardize an Ignition method for this for FCOS and ideally have that same method apply to RHCOS.
Would this "standard way" be support for `kargs.d` as implemented in https://github.com/ostreedev/ostree/pull/2217? This way, once Ignition supports [rebooting in the initramfs](https://github.com/coreos/ignition/issues/1051), we can use Ignition configs to specify our desired default kargs, write a file into `kargs.d`, create a new deployment, and reboot.

**Comment by jlebon** [comment]
> Would this "standard way" be support for kargs.d as implemented in ostreedev/ostree#2217? This way, once Ignition supports rebooting in the initramfs, we can use Ignition configs to specify our desired default kargs, write a file into kargs.d, create a new deployment, and reboot.

I think we'd probably want to optimize it so that we don't create a new deployment at all. So e.g. the user's Ignition config drops files in `kargs.d`, we notice it, add the kargs to the BLS, and reboot. All before ever switching root.

**Comment by kelvinfan001** [comment]
After [some discussion today](https://hackmd.io/cXQ-SqXUScC_t-Ja4foxRQ?view), we've decided that for CoreOS purposes, the BLS will still be the source of truth. In FCOS, there will be no new API or standard way for changing/setting kargs through OSTree. Setting/editing custom kernel arguments on first boot will be handled by Ignition.

**Comment by cgwalters** [comment]
To remove the default `mitigations=auto,nosmt` default, currently you can write a systemd unit in ignition that does e.g.
```
[Unit]
ConditionKernelCommandLine=mitigations

[Service]
ExecStart=/usr/bin/rpm-ostree kargs --remove=mitigations --reboot
RemainAfterExit=yes
```

If you're running other units that might depend on this, you should change them to order `After=` this unit.

**Comment by jlebon** [comment]
The `rpm-ostree kargs` approach is currently documented here: https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/.

**Comment by bgilbert** [comment]
This will be addressed via Ignition's new kernel argument support (https://github.com/coreos/ignition/issues/1168), which has been implemented in an experimental config spec but not yet stabilized.  Leaving this open until the functionality is stabilized and documented.

**Comment by bgilbert** [comment]
@sohankunkerkar Yep, and we've [added documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/#_modifying_kernel_arguments_via_ignition) with a suitable warning.  However, we can't unconditionally recommend the functionality until Ignition spec 3.3.0 is stabilized, since Ignition configs using the experimental spec will break at that point.

**Comment by dustymabe** [comment]
v3.3.0 stabilization happened in ignition 2.11.0 which is in `testing`.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `34.20210626.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `34.20210626.3.1`.

**Comment by dustymabe** [comment]
Docs will get updated soon when the new `butane` hits Fedora repos: https://github.com/coreos/fedora-coreos-docs/pull/307#issuecomment-880933671
