### ISSUE TITLE
Make btrfs a weak dependency in ignition

### ISSUE THREAD

**Issue by nullr0ute** [coreos/fedora-coreos-tracker#323]
In Fedora IoT we don't intend on supporting btrfs so it would be useful to make the rpm dep for ignition a weak dependency so it can be excluded if not required.

from the spec:
<pre>
%if 0%{?fedora}
Requires: btrfs-progs
%endif
</pre>

**Comment by jlebon** [comment]
https://src.fedoraproject.org/rpms/ignition/pull-request/43

Now, this will automatically also drop out `btrfs-progs` from FCOS. Do we want to keep it in? I lean towards yes. Some folks like btrfs and it's not large (nor does it bring in new deps AFAICT). (See also discussions in https://github.com/coreos/fedora-coreos-tracker/issues/33)

**Comment by dustymabe** [comment]
Sounds good to me. I'm good for keeping `btrfs-progs` in.

**Comment by nullr0ute** [comment]
> Now, this will automatically also drop out `btrfs-progs` from FCOS. Do we want to keep it in? I lean towards yes. Some folks like btrfs and it's not large (nor does it bring in new deps AFAICT). (See also discussions in #33)

Could FCOS not just include it specifically in their package manifest?

**Comment by jlebon** [comment]
> Could FCOS not just include it specifically in their package manifest?

Yup, that's what we're discussing. :)

**Comment by ajeddeloh** [comment]
Another thought: we should see about conditionalizing support for it in ignition itself. So if you build without btrfs configs using it will fail validation.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/249

**Comment by lucab** [comment]
> we should see about conditionalizing support for it in ignition itself. So if you build without btrfs configs using it will fail validation.

My understanding is that [weak dependencies](https://rpm.org/user_doc/dependencies.html#weak-dependencies) are conditionalized at runtime, not at build-time.

I fear that build-time conditionals would require building a matrix of binary packages (for all the possible combinations) or a package system that natively support that (e.g. `USE` flags). So, while a good idea, I don't think it would help here.

Perhaps we can instead enhance Ignition to probe for `btrfs-prog` at runtime (if a `btrfs` filesystem was requested by config) before trying to perform. Same for anything else that we want to demote to a `Recommends`.

**Comment by nullr0ute** [comment]
> My understanding is that [weak dependencies](https://rpm.org/user_doc/dependencies.html#weak-dependencies) are conditionalized at runtime, not at build-time.

Do you mean install time? In the case of ostree use cases that would be compose time.

**Comment by dustymabe** [comment]
> I fear that build-time conditionals would require building a matrix of binary packages (for all the possible combinations) or a package system that natively support that (e.g. `USE` flags). So, while a good idea, I don't think it would help here.

I agree. Let's not try to do anything fancy here.

**Comment by jlebon** [comment]
PR merged; this will be fixed in the next build!
