### ISSUE TITLE
docs: tracker for official release documentation

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#330]
We would like to have a basic set of documentation for the first release out of Preview that will help guide users on their use of FCOS.

A basic outline with some comments + questions has been started here - https://docs.google.com/document/d/14WthmPD_4q_99jBcPoVGa_ysQ7dJkxeAZxyRGbyEeSM/edit

This issue is tracking that we will deliver this set of documentation when we are ready to release.

**Comment by dustymabe** [comment]
I'm going to say this is done since we have https://docs.fedoraproject.org/en-US/fedora-coreos/ and we've been building on it iteratively over the past few weeks. Probably a lot of stuff we still want to cover but we're making individual issues for most of those things.

@miabbott - WDYT?

**Comment by miabbott** [comment]
Agreed.  Closing it out.
