### ISSUE TITLE
Create stable stream

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#331]
As we approach the stable release, we need to be ready to actually perform the release mechanically. There are a few things that need to happen for this:
- [x] create the stable branch
- [x] add the stable stream to the pipeline
- [x] add instructions for making a stable release to the [streams](https://github.com/coreos/fedora-coreos-streams) repo
- [x] verify tools don't need to be adapted (`plume release`, `fedora-coreos-stream-generator`)
- [x] verify Cincinnati is adapted to handle the stable stream (https://github.com/coreos/fedora-coreos-cincinnati/issues/4)
- [x] update website to have a drop-down selector between `stable` and `testing` streams, defaulting to `stable` (though in a pinch, `s/testing/stable/` would work too short-term) (https://github.com/coreos/fedora-coreos-tracker/issues/332)

(Chime in if there's anything else missing from there).

Seems like we should just go through all the steps of making a release to test this out, up to but not including actually updating the website?

**Comment by jlebon** [comment]
>  add instructions for making a stable release to the streams repo

https://github.com/coreos/fedora-coreos-streams/pull/39

**Comment by lucab** [comment]
Cross-reference: https://github.com/coreos/coreos-installer/issues/106

**Comment by jlebon** [comment]
>  verify tools don't need to be adapted (`plume release`, `fedora-coreos-stream-generator`)

I've had a quick look at them and I don't see anything offhand that would require adapting. Both of them parameterize on the stream to operate on.

**Comment by lucab** [comment]
Cincinnati is also already parametrized, but the backend will need a small update (possibly just its configuration) to start consuming `stable` updates metadata and release index.

**Comment by jlebon** [comment]
> Cincinnati is also already parametrized, but the backend will need a small update (possibly just its configuration) to start consuming `stable` updates metadata and release index.

Good call, thanks. I added a checkbox for Cincinnati!

**Comment by lucab** [comment]
@jlebon do you plan to have the JSON metadata URL created in advance (and empty) to align the tools earlier, or do you prefer to use this event to exercise metadata creation logic?

**Comment by jlebon** [comment]
> @jlebon do you plan to have the JSON metadata URL created in advance (and empty) to align the tools earlier, or do you prefer to use this event to exercise metadata creation logic?

Hadn't thought about it, though probably a good opportunity? We still have quite a few more streams (mostly mechanical) that we'll want to set up eventually.

**Comment by jlebon** [comment]
Going to close this one out. Thanks all!
