### ISSUE TITLE
Adapt FCOS download page for stable release

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#332]
This is split out of https://github.com/coreos/fedora-coreos-tracker/issues/331. We want the download page to be ready to handle the stable stream when it's made available. I.e. users need to be able to select between the testing and stable stream, and the page should default to the stable stream.

**Comment by dustymabe** [comment]
@zonggen - is this something you could help us with?

**Comment by zonggen** [comment]
Sure, will proceed with the design mentioned in https://pagure.io/fedora-websites/issue/964

**Comment by dustymabe** [comment]
hey @zonggen - any updates here?

**Comment by zonggen** [comment]
Sorry about the delay, was on vacation leave, will keep working on this asap.
Made initial commits https://pagure.io/fedora-web/websites/pull-request/78, though thanks to the help of @rfairley the download page should be ready very soon.

**Comment by jlebon** [comment]
Let's mark this as done. Thanks a lot @rfairley and @zonggen!
