### ISSUE TITLE
Cannot alias iptables-nft as iptables with `alternatives`

### ISSUE THREAD

**Issue by LorbusChris** [coreos/fedora-coreos-tracker#342]
Fedora in F32 will use the nft implementation of iptables by default (see https://fedoraproject.org/wiki/Changes/iptables-nft-default).

Right now, however, it is not possible to alias it as `iptables` in FCOS with `alternatives` even though it is installed, as one cannot change the `alternatives` priority on rpm-ostree based systems (https://github.com/fedora-sysv/chkconfig/issues/27) and `iptables` therefore always points to `iptables-legacy`.

RHCOS already and exclusively uses the nft implementation, leading FCOS in that regard.

Context: `iptables-legacy` is suspected to be the cause of https://bugzilla.redhat.com/show_bug.cgi?id=1781575 which only seems to appear on systems that still use the legacy implementation.

**Comment by dustymabe** [comment]
Here is the previous conversation around firewalling: https://github.com/coreos/fedora-coreos-tracker/issues/26

This simply sounds like a bug that needs to be fixed (and you've linked to one).

Can you just workaround it in ignition with the equivalent of:

```
[core@coreos ~]$ sudo ln -sf /usr/sbin/iptables-nft /etc/alternatives/iptables 
[core@coreos ~]$ 
[core@coreos ~]$ iptables --version
iptables v1.8.3 (nf_tables)
```

**Comment by LorbusChris** [comment]
Changing the symlink in `/etc/alternatives/` does the trick indeed, thanks Dusty!
