### ISSUE TITLE
Unable to boot from .iso Probing EDD... ok

### ISSUE THREAD

**Issue by medard1337** [coreos/fedora-coreos-tracker#344]
When I try to boot fedora fedora-coreos-31.20191217.2.0-live.x86_64.iso - after kernel selection screen (where I can put in parameters if I press <tab>) I just end up on screen saying:

`Probing EDD (edd=off to disable)... ok.` 
Then just the cursor flashing forever. I tried to put edd=off to kernel parameters but then only cursor went flashing.

Is this bug or Did I do anything wrong? I'm using  specified .iso, a transpiled_config.ign (which only contains my pubkey) and parameters: 
`coreos.inst.install_dev=/dev/sda`
`coreos.inst.ignition_url=http://example.com/config.ign`

**Comment by dustymabe** [comment]
hey @medard1337 - can you try with the latest images from the `31.20200108.2.0` release from  https://getfedora.org/en/coreos/download/? Are you on a VGA console or on a serial console? Try adding `console=tty0` for VGA or `console=ttyS0` for serial console (though depending on your setup in may be a different device, but those are the most common).

**Comment by dustymabe** [comment]
@medard1337 I believe I've seen messages from you in IRC which indicate you've managed to get past the `Probing EDD` screen and are doing installs now. I'm going to close this but feel free to re-open if you encounter this issue again.
