### ISSUE TITLE
deploy coreos-cincinnati to prod cluster

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#347]
We need to get our update server into the production Fedora Infra openshift instance. This is being tracked over in https://pagure.io/fedora-infrastructure/issue/8537

**Comment by lucab** [comment]
This is in progress, OpenShift objects are already fully deployed.
The service is not yet operational though, likely a reverse proxy in front of it needs some tweaking.

**Comment by lucab** [comment]
This is now deployed to production. I'm closing this, but I'll progress somewhere else with other tasks:
 * updating the URL in Zincati default config
 * writing SOP for the service
