### ISSUE TITLE
Booting from ISO w/o DHCP server fails and ends in emergency mode

### ISSUE THREAD

**Issue by cmonty14** [coreos/fedora-coreos-tracker#349]
Hello!
I try to boot a KVM from _fedora-coreos-31.20200113.3.1-live.x86_64.iso_.
However, there's no DHCP service in the network, and therefore the boot shows many DHCPDISCOVER issues.
In the end the console is opening in emergency mode only.

I have created a screenshot documenting this.
![2020-01-21_09-14-58](https://user-images.githubusercontent.com/12523591/72786712-8a058080-3c2e-11ea-9a5b-daf73af4de41.png)

In my opinion there's an issue booting from ISO w/o DHCP service available.
But I want to use a static IP and configure this with the ignition file accordingly.

I proceeded this way with CoreOS (_coreos_production_iso_image.iso_) w/o any problems.

Please advise how to fix this.

THX

**Comment by jlebon** [comment]
Right, we need better documentation around this. The live ISO today assumes there is DHCP available. You'll see the kernel cmdline will have `ip=dhcp`. If that's not the case, you'll have to change that karg and use e.g. `ip=<static-ip>:<gateway>:...` (see http://man7.org/linux/man-pages/man7/dracut.cmdline.7.html).

Note this is separate from what the networking configuration of the installed system itself should be (if that's the reason you booted up the live ISO). That should be configured via Ignition using [NetworkManager keyfiles](https://developer.gnome.org/NetworkManager/stable/nm-settings-keyfile.html).

Where they overlap is that Ignition may need networking in the initramfs, before keyfiles take effect. If installing via kargs (e.g. using `coreos.inst.install_dev`), the installer automatically carries through the networking kargs to the first boot for this. If you're using the installer CLI interactively, you'll want to use `--firstboot-args 'ip=...'`.

So yes, this is a complex issue. The TL;DR though is "really try to use DHCP if possible". :)

**Comment by cmonty14** [comment]
Hi,
I thought so and therefore installed a simple DHCP server.
This solved the issue during ISO booting and allowed me to use a simple ignition file.

BTW I faced the same issue with DHCP when using the QEMU file.

Anyway, I would consider this issue as solved.

Thanks for your support!

**Comment by dustymabe** [comment]
> Right, we need better documentation around this. The live ISO today assumes there is DHCP available. You'll see the kernel cmdline will have `ip=dhcp`. If that's not the case, you'll have to change that karg and use e.g. `ip=<static-ip>:<gateway>:...` (see http://man7.org/linux/man-pages/man7/dracut.cmdline.7.html).

@jlebon I wonder if we should make it so it will get dhcp if it exists but not fail into emergency mode if it doesn't. For example I could see someone wanting to get to the live ISO bash prompt and then set static networking via the command line before running the installer.

**Comment by cmonty14** [comment]
I fully agree with this proposal.
There shouldn't be any issues creating a static IP (with `ip` command) once the ISO is loaded completely.
And, by the way, this was the procedure with CoreOS (coreos_production_iso_image.iso).

**Comment by jlebon** [comment]
> I wonder if we should make it so it will get dhcp if it exists but not fail into emergency mode if it doesn't.

I'm not sure if there's a way to do this with dracut's `ip=` though. It has its own init system. Things might be different when we switch to NM (though that one *also* uses the dracut initqueue).

**Comment by CptDaniel** [comment]
Coming from CoreOS and trying to get a VM running I ran into this issue as well. A solution as close as possible to CoreOS would be great (as @dustymabe suggested) or at least have it somewhere in the documentation, so folks not running their own dhcp server don't have to search for this.

**Comment by dustymabe** [comment]
related: https://github.com/coreos/coreos-installer/issues/164

**Comment by jlebon** [comment]
This is part of the more generic conditional networking issue: https://github.com/coreos/fedora-coreos-tracker/issues/443.

**Comment by dustymabe** [comment]
The fix for this landed upstream. It is now pending a testing stream release.

**Comment by jlebon** [comment]
Accidentally closed.

**Comment by dustymabe** [comment]
:) - it actually should be closed. I only re-opened it to test that closing it again would trigger some downstream automation.. Closing again now.

**Comment by dustymabe** [comment]
@cmonty14 do you want to try out the [latest testing-devel](https://builds.coreos.fedoraproject.org/prod/streams/testing-devel/builds/31.20200401.20.1/x86_64/fedora-coreos-31.20200401.20.1-live.x86_64.iso) to see if you have more success?

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `31.20200407.2.2`.  Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `31.20200407.3.0`.
