### ISSUE TITLE
Document network configuration via Ignition + NM keyfiles

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#351]
Most of the examples on the web use ifcfg files instead of keyfiles. Would be helpful to document some example configs of the more common scenarios (static IP, bonding, unmanaged device, etc...).

NM conf documentation: https://developer.gnome.org/NetworkManager/stable/NetworkManager.conf.html
Keyfile conf documentation: https://developer.gnome.org/NetworkManager/1.22/nm-settings-keyfile.html

**Comment by basvdlei** [comment]
I've been battling with the NetworkManager keyfiles to configure multiple ipv4 addresses on an interface and ended up with this, which seems to do the job:

```
[connection]
type=ethernet
interface-name=eth1

[ipv4]
method=manual
address1=192.168.121.11/24
address2=192.168.121.50/24
address3=192.168.121.51/24
gateway=192.168.121.1
dns=1.1.1.1;8.8.8.8
```

Note the different notation between multiple interface addresses and multiple DNS servers.

**Comment by lucab** [comment]
Cross referencing this here: https://github.com/coreos/fedora-coreos-docs/issues/19.

**Comment by dustymabe** [comment]
I'm pretty sure this is covered by our documentation now. Specificall [this page](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/).
