### ISSUE TITLE
 Failed to open file “/home/core/example.ign”: Permission denied

### ISSUE THREAD

**Issue by skycastlelily2** [coreos/fedora-coreos-tracker#357]
I'm following this page to install fcos on a virtual machine,but failed
with ERROR    internal error: process exited while connecting to monitor: 2020-01-29T09:01:55.069911Z qemu-system-x86_64: -fw_cfg name=opt/com.coreos/config,file=/home/core/example.ign: can't load /home/core/example.ign: Failed to open file “/home/core/example.ign”: Permission denied

https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/
Here is the command I use,
virt-install -n fcos2 --vcpus 2 -r 2048 --os-variant=fedora31 --import --network bridge=virbr0 --disk=/home/lnie/Downloads/fedora-coreos-31.20200113.3.1-qemu.x86_64.qcow2,format=qcow2,bus=virtio --noautoconsole --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=/home/core/example.ign"

FYI,it works after I use /tmp/example.ign

**Comment by lucab** [comment]
Thanks for the report.
What is the host OS where you are running this? Does it have SELinux enabled (and what do AVC logs say)? Does your user have read access to that path?

For SELinux issues, it may be worth changing the security context of the file first `chcon -t svirt_home_t /path/to/example.ign`

**Comment by skycastlelily2** [comment]
I'm running this on fedora workstation. chcon -t svirt_home_t /path/to/example.ign works,thanks for your help

**Comment by lucab** [comment]
For reference, https://github.com/coreos/fedora-coreos-docs/pull/34 is adding the SELinux note to docs.
