### ISSUE TITLE
feature request: limit size of /sysroot partition

### ISSUE THREAD

**Issue by felixkrohn** [coreos/fedora-coreos-tracker#360]
Would it be possible to somehow configure the installer to use only X GiB for the /sysroot partition instead of "whatever is left from the hard disk"?

The use case would be for bare-metal installations, where often you find disks in the multi-Terabyte range. 
I'd like to reduce the /sysroot to say, 50 GiB, in order to be able to use the remaining part of the disk for a data partition (ideally, mirrored to identical-sized partition on further disk(s) in a further step)

For this it would be great to either:
* have a flag to limit /sysroot to a given size, or
* have a flag to limit sysroot to "whatever is left minus X GiB", so that this space can be configured using a custom ignition config.

**Comment by felixkrohn** [comment]
pointer from @dustymabe:

> < dustymabe> for reference, the service that grows the partition today is run on first boot and is called `ignition-ostree-growfs.service`

**Comment by bgilbert** [comment]
The resize happens after the Ignition disks stage.  So, have Ignition create your data partition at a specified offset into the disk.  For example, in your FCC, set `start_mib` to `51200`.  After Ignition runs, the root partition will be resized up to the 50 GiB boundary but no further.

We should document this explicitly.
