### ISSUE TITLE
Is there some particular reason to keep username as core

### ISSUE THREAD

**Issue by alpana17** [coreos/fedora-coreos-tracker#367]
Is there some particular reason to keep username as core

**Comment by jlebon** [comment]
Is the question why have a default user, or why have that default user's name be `core`? For the former, this matches FAH (cloud-init) and CL (Ignition) behaviour. For example, this allows you to bring up a host in AWS right now without an Ignition config and just passing a key pair (see [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/#_launching_on_amazon_web_services_aws)). For the latter, I'm not sure if we discussed it explicitly, though it helps migration to match CL.

**Comment by dustymabe** [comment]
> For the latter, I'm not sure if we discussed it explicitly, though it helps migration to match CL.

Yes. Also, if you need a default then it has to have a name and `core` is a reasonable enough default IMHO.

**Comment by bgilbert** [comment]
I'll go ahead and close.  In general, please direct community discussion to [Fedora Discourse](https://discussion.fedoraproject.org/c/server/coreos).
