### ISSUE TITLE
Purpose of Fedora CoreOS

### ISSUE THREAD

**Issue by alpana17** [coreos/fedora-coreos-tracker#369]
As we know, CoreOS was being used on a very large scale.
Then, why Fedora CoreOS is created?
Is there any drawback or limitation of CoreOS that is being addressed in Fedora CoreOS?

**Comment by lucab** [comment]
This is covered in a few places, so I won't repeat everything here but instead just point to relevant entries:
 * https://docs.fedoraproject.org/en-US/fedora-coreos/faq
 * https://coreos.com/blog/fedora-coreos-red-hat-coreos-and-future-container-linux
 * https://fedoramagazine.org/announcing-fedora-coreos/

Furthermore, please do not overuse the bug-tracker for discussion. There is a dedicated community forum at https://discussion.fedoraproject.org/c/server/coreos.
