### ISSUE TITLE
How to install chef 14 on fedora coreos

### ISSUE THREAD

**Issue by alpana17** [coreos/fedora-coreos-tracker#370]
How to install chef 14 on fedora coreos

**Comment by jlebon** [comment]
Hi, could you redirect your question to https://discussion.fedoraproject.org/c/server/coreos/? I'll make sure to answer you there. :) The tracker is for Fedora CoreOS bugs or feature requests.

Thanks!

**Comment by alpana17** [comment]
@jlebon 
I have registered at https://admin.fedoraproject.org/
But still, I am not able to login to 
![image](https://user-images.githubusercontent.com/8611615/73917113-c8fd2c80-48e4-11ea-9a0a-c71967273dcb.png)

I tried to join the group CoreOS on https://admin.fedoraproject.org/ portal.
But Apply button does not appear there
![image](https://user-images.githubusercontent.com/8611615/73917192-ee8a3600-48e4-11ea-826d-d6f475eaf1ab.png)

**Comment by LorbusChris** [comment]
You should be able to log in at https://discussion.fedoraproject.org now

**Comment by dustymabe** [comment]
> @jlebon
> I have registered at https://admin.fedoraproject.org/

I assume that means you have a [Fedora Account](https://fedoraproject.org/wiki/Account_System#The_Fedora_Account_System) now? 

> But still, I am not able to login to

Maybe it takes some time to sync everything over. Can you log in to other apps like https://pagure.io/ (log in button in the top right corner)? Can you share your account username?

> 
> I tried to join the group CoreOS on https://admin.fedoraproject.org/ portal.
> But Apply button does not appear there

You don't need access to that group, so don't worry about that.

**Comment by dustymabe** [comment]
hi @alpana17 - any luck creating an account?
