### ISSUE TITLE
F32 rebase tracker for changes discussion

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#372]
The tentative schedule for F32 is:

```
2020-02-11  Branch Fedora 32 from Rawhide (Rawhide becomes future F33)
2020-02-11  Post-branch Freeze                               
2020-02-14  Post-branch Un-Freeze
2020-02-25  Bodhi activation point Beta Freeze (*)           
2020-03-17  Beta Release Target date                            
2020-04-07  Final Freeze (*)
2020-04-21  Fedora 32 Final Release (GA) Target date
```

While we aren't beholden to that schedule and will likely switchover to F32 some time after the official release date we should have a discussion about what changes we need to make as part of the rebase and also enumerate and discuss the changes that are being made to Fedora for F32 to see if they affect us and we should react to them in any way.

Currently the changes to Fedora are enumerated and linked from https://fedoraproject.org/wiki/Releases/32/ChangeSet. We should evaluate that change set to see if there is anything we need to do regarding those changes.

The following section will be updated/edited during investigation:

### Changes we are considering making to FCOS

- ~~Should we switch to cgroups v2 for F32: https://github.com/coreos/fedora-coreos-tracker/issues/373~~

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/N2REC7A42JYVFMWA7VPBTIRQJJV6AY4C/). Some interesting things from the [F32 Changeset](https://fedoraproject.org/wiki/Releases/32/ChangeSet):

- [Adopting sysusers.d format](https://fedoraproject.org/wiki/Releases/32/ChangeSet#Adopting_sysusers.d_format)
    - This should help us pick up our longstanding work ([issue](https://github.com/coreos/rpm-ostree/issues/49), [PR](https://github.com/coreos/rpm-ostree/pull/1679)) for adopting sysuers
- [Make iptables-nft the preferred iptables variant](https://fedoraproject.org/wiki/Releases/32/ChangeSet#iptables-nft-default)
    - any implications for kubernetes/OpenShift here?
    - @cgwalters noted this could break user's scripts if that have any.
        - for static rules they should probably be using a config file, does the same config file still work?
        - for dynamic rules, indeed, this could break user/application scripts
            - if we want to make this change we need to get it into `next` and promote it
- Also of note is the [Limit Scriptlet Usage of core packages](https://fedoraproject.org/wiki/Releases/32/ChangeSet#Limit_Scriptlet_Usage_of_core_packages) self contained change
    - running less in scriptlets always will help the OSTree model of delivering an OS

**Comment by dustymabe** [comment]
In the meeting on 04/29 we proposed this schedule for the switch to f32 in our other streams:

```
16:58:36 <dustymabe> - next week: first `next` release after GA
16:58:55 <dustymabe> - 3 weeks: first `testing` release based on f32
16:59:06 <dustymabe> - 5 weeks first `stable` release based on f32
```

which translates to:

- 05/05/2020 - first `next` release after GA
- 05/19/2020 - first `testing` release based on f32
- 06/02/2020 - first `stable` release based on f32

**Comment by jlebon** [comment]
Moving testing-devel to f32: https://github.com/coreos/fedora-coreos-config/pull/394

**Comment by dustymabe** [comment]
> Moving testing-devel to f32: [coreos/fedora-coreos-config#394](https://github.com/coreos/fedora-coreos-config/pull/394)

hold that for now as we might need to spin a new testing: https://github.com/coreos/fedora-coreos-tracker/issues/479#issuecomment-628208611

**Comment by dustymabe** [comment]
Considering https://github.com/coreos/fedora-coreos-tracker/issues/481 we have pushed out the schedule a bit to let the fix propagate. Here is the newly proposed schedule:

- 06/02/2020 - first `testing` release based on f32
- 06/16/2020 - first `stable` release based on f32

**Comment by vrutkovs** [comment]
Tested OKD-on-FCOS, booting from stable 31.20200420.3.0 and updating to machine-os-content based on `next` - worked perfectly

**Comment by jlebon** [comment]
We discussed this in the community meeting today. We're still planning to go ahead with the dates suggested in https://github.com/coreos/fedora-coreos-tracker/issues/372#issuecomment-631586457.

**Comment by dustymabe** [comment]
updates:

- our `testing` stream is now on a Fedora 32 base with today's release of `32.20200601.2.1`
- our `stable` stream will follow in the next cycle unless we find issues
- there are some known issues in the Fedora 32 rebase that we are investigating:
    - Ignition fails to set selinux labels on absolute symlinks: https://github.com/coreos/fedora-coreos-tracker/issues/512
    - Kernel warnings in our CI tests when executing on AWS: https://github.com/coreos/fedora-coreos-tracker/issues/507
- users need to use the v0.2.1 version of `coreos-installer` or newer since it has the updated f32 signing key

**Comment by dustymabe** [comment]
Fedora CoreOS `32.20200601.3.0` (the first `stable` stream build based on Fedora 32) is rolling out to clients over the next 3 days. Let us know if you see issues!
