### ISSUE TITLE
F32: should we switch to cgroups v2

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#373]
We originally decided to stay on cgroups v1 so that the container ecosystem could catch up. We should evaluate if we can move to cgroups v2 for the Fedora 32 rebase. Some examples of things to investigate:

- can moby-engine upstream support cgroups v2 yet (assigned to @jlebon)
- can we get a rebase of moby-engine to the latest release in rawhide? (assigned to @mike-nguyen to ask maintainers)
- what is the state of kubernetes when it comes to cgroups v2?

**Comment by dustymabe** [comment]
this ticket is related to: #372

**Comment by LorbusChris** [comment]
cc'ing @vrutkovs for that 3rd bullet point :)

**Comment by vrutkovs** [comment]
>what is the state of kubernetes when it comes to cgroups v2?

cgroupvs2 can be used, but it requires https://github.com/kubernetes/enhancements/pull/1370 (https://github.com/kubernetes/kubernetes/pull/85218), few crio fixes (merged in master already afaik) and swapping runc with crun (afaik runc is planning to support cgroupsv2). @giuseppe would know more details

on OKD side we're safe because bootstrap / masters / workers switch to cgroupsv1 mode on pivot, so we're independent on defaults here

**Comment by giuseppe** [comment]
the plan is to have cgroups v2 Alpha support for Kubernetes 1.19.

**Comment by AkihiroSuda** [comment]
Moby already has a basic support for cgroup2, but `docker stats` still remains unimplemented due to a Go mod hell: https://github.com/moby/moby/issues/40360

**Comment by dustymabe** [comment]
We discussed during the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/W4WDMAOEWVJFL2ISCFS5VKU3CRXPXZRN/)

It appears that the moby and kubernetes projects are not quite there yet with regards to cgroups v2 support. In the meeting we proposed and agreed that we should probably wait for now:

```
11:57:56      dustymabe | #agreed while the container ecosystem is maturing, 
                          both moby (docker) and kubernetes aren't yet to a place 
                          where we're comfortable moving to cgroups v2 by default for
                          F32 based FCOS, we'll consider again at a later time
```
