### ISSUE TITLE
fcct: add support for sourcing local file content

### ISSUE THREAD

**Issue by alpana17** [coreos/fedora-coreos-tracker#375]
Earlier in coreOS there was 'local' flag in 'storage.files.contents'
![image](https://user-images.githubusercontent.com/8611615/73921079-b4249700-48ec-11ea-90cd-4388ed87bdff.png)

What can be used in FCOS ignition that provides same functionality?

**Comment by lucab** [comment]
Thanks for the report.
The field you mention has never been part of the Ignition configuration spec, and I don't think that will change.

However, `ct` used to have an option to embed local files via the `local` specifier. I think `fcct` could (in theory) support the same, so this is a legit request feature for it. I've re-titled this ticket accordingly.

**Comment by alpana17** [comment]
ok,
currently, there is no such thing that can be used in place of 'local'
Right?

**Comment by lucab** [comment]
To my knowledge, at the moment `fcct` only supports file content from within the YAML file (`inline`) or from a remote source fetched at Ignition time (`source`). See https://github.com/coreos/fcct/blob/master/docs/configuration-v1_1-exp.md.

**Comment by ashcrow** [comment]
Related: https://github.com/coreos/fcct/issues/83

**Comment by bgilbert** [comment]
Fixed in https://github.com/coreos/fcct/pull/99.

**Comment by dghubble** [comment]
In https://github.com/coreos/fcct/pull/99, the Fedora CoreOS Config spec document now mentions `local` depends on the directory set via fcct command line flag. I'm anticipating tools that handle Fedora CoreOS Configs (e.g. use fcct as a package) will need to warn folks that fields like this are specific to "fcct the tool"

**Comment by bgilbert** [comment]
@dghubble I hesitated to put that wording into the spec for exactly that reason.  The FCCT Go API allows callers to specify the files-dir via an options struct, so the feature should work for library use as well.  (Unlike the equivalent feature in CLCT, actually.)  Any suggestions for better docs wording?

**Comment by dghubble** [comment]
I think I'm wondering about it for what the `local` field means for other integrations. If another orchestration system accepts a FCC, does it need to implement a way to read local content? Or hypothetically if a web UI let a user input a FCC, that implemention should ignore local I guess. For my own particular Terraform integration I consume the Go package, so sounds like it wouldn't be an issue there. 

Seems like, to keep the FCC spec and CLI tool independent, `fcct` would need to use the `content` or `inline` field but preprocess some "read and insert file" value. But then that's a contract of sorts too and probably less clear that just having `local`. So I'm not really sure how you'd support `local` behaviors without having an FCC field that has a caveat.

**Comment by dghubble** [comment]
I see CLC has the `local` field too as you say and I've just ignored it. Maybe its a minor thing.

**Comment by bgilbert** [comment]
I'd expect systems that work with some sort of filesystem hierarchy (Matchbox?) would set a files-dir, maybe a sibling of the FCC file or its parent dir.  Web transpilers wouldn't set one.  If we'd need to provide a callback API for systems that don't use a filesystem, we could consider doing that.

It is somewhat awkward to allow non-self-contained FCCs, regardless of mechanism.  But there's user demand for file inclusion, and it's the sort of functionality one would expect from a preprocessor.  On balance I think I'd rather have the conditionally-supported field.

**Comment by dghubble** [comment]
That all sounds reasonable to me, thanks for the thoughts around it. :+1: 

For FCOS, Matchbox just acts as a server of Ignition with the client plugin interpretting an FCC to prepare Ignition configs, so I think it would fit in that web category being online.

**Comment by bgilbert** [comment]
FCCT 0.6.0 was just released, including support for a `local` directive in [FCC spec 1.1.0](https://github.com/coreos/fcct/blob/master/docs/configuration-v1_1.md).  This spec version requires Ignition 2.3.0 and above, which is available in FCOS `testing` and will be in the next FCOS `stable` release.
