### ISSUE TITLE
user-data in GCP not working

### ISSUE THREAD

**Issue by YadominJinta** [coreos/fedora-coreos-tracker#380]
Hey, I am trying to use FCOS on GCP but met problems.
I upload FCOS image to GCP and use it to create an instance. I add the ignition file as `user-data` in metadata.
But the `user-data` metadata not working, so I can't login to the system because the user's keys are not added.

I checked the serial port output and confirmed that `user-data` didn't work.

**Comment by dustymabe** [comment]
@YadominJinta I see you closed this issue. Did you figure out the problem?

**Comment by moritz31** [comment]
@YadominJinta have the same issue? How did you resolve this ?
