### ISSUE TITLE
Any plan to publish fedore-coreos on aws cn-northwest-1 region?

### ISSUE THREAD

**Issue by MartinForReal** [coreos/fedora-coreos-tracker#383]
I have no luck to find fedora-coreos AMI images in the cn-northwest-1 region. Is there any plan to support cn-northwest-1 region? Thanks!

**Comment by lucab** [comment]
I think the current answer here is "no", and same goes for GovCloud. Within AWS, they both are separate **partitions** (not just **regions**) which require dedicated handling.

Last status update on this was at https://github.com/coreos/fedora-coreos-tracker/issues/149#issuecomment-584244583.

**Comment by dustymabe** [comment]
> I think the current answer here for China is "no", and same goes for GovCloud. Within AWS, they both are separate **partitions** (not just **regions**) which require dedicated handling.

@lucab, he can still manually upload an AMI using our AWS vmdk, correct? 

more details: https://github.com/coreos/fedora-coreos-tracker/issues/149#issuecomment-583471489

**Comment by lucab** [comment]
Indeed, sorry for omitting those details. If we intend to stick to this plan of not publishing to China/GovCloud, we should probably have a FAQ entry with the whole explanation and directions.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-docs/pull/44

**Comment by dustymabe** [comment]
With https://github.com/coreos/fedora-coreos-docs/pull/44 merging and the landing in the FAQ at https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_how_do_i_upload_fedora_coreos_to_private_aws_ec2_regions I think we can close this now.
