### ISSUE TITLE
Add Exoscale provider to Fedora Coreos

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [coreos/fedora-coreos-tracker#384]
[Exoscale](https://exoscale.com) is a solid European cloud hosting alternative.

We wish to support Fedora CoreOS in our default featured template to start a VM instance.

Also, it's possible for a user to create a custom template, can be great if users can download the Exoscale qcow2 from fedora's website and create a template by own.

- [x] ignition https://github.com/coreos/ignition/pull/922
(get user ignition config from user-data server)

- [x] coreos-assembler https://github.com/coreos/coreos-assembler/pull/1127
(build the qcow2 for exoscale)

- [x] afterburn (https://github.com/coreos/afterburn/pull/357)
(get sshkey, hostname...etc from meta-data server)

- [x]  Add Exoscale to build pipeline https://github.com/coreos/fedora-coreos-pipeline/pull/208

- [x]  edora-coreos-stream-generator https://github.com/coreos/fedora-coreos-stream-generator/pull/7

- [x]  coreos-meta-translator https://github.com/coreos/fedora-coreos-releng-automation/pull/82

- [x] Fedora coreos doc https://github.com/coreos/fedora-coreos-docs/pull/53

- [x]  website https://pagure.io/fedora-web/websites/pull-request/97
(Add qcow image to download page)

**Comment by jlebon** [comment]
Remaining items:
- `buildextend-exoscale` in the pipeline: https://github.com/coreos/fedora-coreos-pipeline
- teach exoscale to coreos-meta-translator and the stream generator: https://github.com/coreos/fedora-coreos-releng-automation/tree/master/coreos-meta-translator https://github.com/coreos/fedora-coreos-stream-generator/
- Add to download website, see e.g. https://pagure.io/fedora-web/websites/pull-request/80

Just noting this here, but not necessarily something you have to address yourself. :)

**Comment by pierre-emmanuelJ** [comment]
Thank you @jlebon :)

**Comment by pierre-emmanuelJ** [comment]
Thank you @jlebon :)

**Comment by dustymabe** [comment]
one more thing.. would be nice to see links to the exoscale artifacts in the [build browser](https://builds.coreos.fedoraproject.org/browser). Can you open a PR there: https://github.com/coreos/fedora-coreos-browser

**Comment by jlebon** [comment]
Build browser patch: https://github.com/coreos/fedora-coreos-browser/pull/5

After this, I think we can close this. The latest release is on https://getfedora.org/en/coreos/ !

**Comment by dustymabe** [comment]
All done! Closing
