### ISSUE TITLE
Release Notes for New Images

### ISSUE THREAD

**Issue by imranrazakhan** [coreos/fedora-coreos-tracker#389]
I just saw new Live ISO is available to download, where we can find release notes, whats fixed in it or what feature is introduced?

**Comment by lucab** [comment]
Please do note that we have a discussion forum for questions at https://discussion.fedoraproject.org/c/server/coreos.

Specifically on release notes, we still don't have a proper flow in place but we are discussing approaches at https://github.com/coreos/fedora-coreos-tracker/issues/194. Closing as a duplicate of that.
