### ISSUE TITLE
OVA format issues prevent deployment to VMWareFusion and VMWareWorkstation

### ISSUE THREAD

**Issue by fifofonix** [coreos/fedora-coreos-tracker#391]
OVA file fedora-coreos-31.20200118.3.0-vmware.x86_64.ova does not deploy successfully locally using VMWareFusion & VMWareWorkstation as described in the FCOS forum [here](https://discussion.fedoraproject.org/t/vmware-fusion-deployment-issue-w-ova-format/16816).

Exporting the OVF from the OVA file using VMWare's ovftool reveals:
* Wrong file size specified in OVF descriptor for ‘disk.vmdk’ (specified: 8589934592, actual 713167360).  Fixing packaging to set this correctly is the one must fix.
* Line 54: Unsupported virtual hardware device ‘VirtualSCSI’.  This can be ignored
* No manifest file found.  This can be ignored, but FCOS should really provide a manifest.

Additionally, depending on whether FCOS supports a default state when no ignition file is specified, the guestinfo.ignition.config.* properties should be marked optional as opposed to their current status of required.

----
Edit by @dustymabe - fixed markdown syntax for link

**Comment by eskes1** [comment]
31.20200127.3.0 (fedora-coreos-31.20200127.3.0-vmware.x86_64.ova) dose not work in vmware vCenter deployment, giving error loading Error: 
Selected OVA file is not a valid template.
fedora-coreos-31.20200118.3.0-vmware.x86_64.ova works better bout seams to have issues, ends up in lopp wen boting, that clud be a ignition file isue so if 31.20200127.3.0 are fixed, it would be fine.

**Comment by darkmuggle** [comment]
PR submitted to fix this.

**Comment by darkmuggle** [comment]
Sorry about the mid-air collision @bgilbert. I didn't realize that we were both working on this issue at the same time.

**Comment by bgilbert** [comment]
- [x] Wrong file size
  - Should be fixed by https://github.com/coreos/coreos-assembler/pull/1136
- [ ] Unsupported `VirtualSCSI` device
- [ ] No manifest
- [ ] `Did not find an .ovf file at the beginning of the OVA package`
- [ ] OVF properties shouldn't be required

**Comment by bgilbert** [comment]
This should be fixed enough to be usable now.  The situation isn't ideal (https://github.com/coreos/fedora-coreos-tracker/issues/391#issuecomment-588033000) but it's better than it was.  Thanks for the report!
