### ISSUE TITLE
package layering: split versions between OSTree base vs yum repo

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#400]
- **NOTE**: we currently discourage package layering in FCOS as it makes updates less reliable. The root of this ticket is part of the reason why, but this issue is not specific to FCOS as mentioned below.

This is a problem that periodically plagued the Atomic Host community, periodically does plague the Silverblue community and is starting to creep into FCOS as users attempt to package layer rpms that aren't included in the base. The user attempts a package layering operation that fails because the versions of packages in the base OS are out of sync with the versions in the yum repositories. There is also [an issue against the RPM-OSTree repo](https://github.com/coreos/rpm-ostree/issues/415) for this problem, but it's a high level problem and a solution will probably take some coordination at multiple levels so we're creating a new ticket here to track that coordination.

The user ends up with an error like:

```
Forbidden base package replacements:
  libgcc 8.2.1-6.fc29 -> 8.3.1-2.fc29 (updates)
```

We need to coordinate with Fedora releng, Fedora Silverblue working group, and the RPM-OSTree maintainers, in order to try to come up with a better solution to this problem. @owtaylor from the Silverblue team did a nice writeup on the problem last year in this [public google document](https://docs.google.com/document/d/1yS0PTaUPmD-CkQkdlJ9OvY-Z5hBOIMlRKDyqutEG_ks), so there is much more context about the problem and possible solutions in there.

**Comment by cgwalters** [comment]
Feels like a dup of https://github.com/coreos/fedora-coreos-tracker/issues/401

**Comment by dustymabe** [comment]
> Feels like a dup of #401

They are closely related, but originally intentionally left separate. #400 is the problem we are seeing. #401 is a potential solution. I'm working on #401 now so hopefully we'll see some progress in that area soon.

**Comment by dustymabe** [comment]
This is pretty much done now. It's hitting `testing-devel` over in https://github.com/coreos/fedora-coreos-config/pull/673 and will be in the next `testing` release.

- How does this affect end users?

The idea is that you continue to do what you were doing in the past and from the next set of releases and on you should hopefully never hit the `Forbidden base package replacements:` problem ever again, especially if you are on `stable` or `testing` streams. There is some opportunity for issues during Fedora major "pre-release" time (which is where the `next` stream is right now with Fedora 33), but that something we can live with for now.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `32.20201018.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20201018.3.0`.
