### ISSUE TITLE
installer fails on signature-fetching errors

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fedora-coreos-tracker#402]
I have a PXE config such as:
```
LABEL FedCoreOSLAP
  MENU LABEL Fedora CoreOS ^LAP
  KERNEL fedora-coreos-31.20200127.3.0-live-kernel-x86_64
  APPEND ip=dhcp rd.neednet=1 nameserver=10.20.0.1 initrd=fedora-coreos-31.20200127.3.0-live-initramfs.x86_64.img coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.stream=stable coreos.inst.insecure=yes coreos.inst.image_url=http://10.20.0.1/coreos/fedora-coreos-31.20200127.3.0-metal.x86_64.raw.xz coreos.inst.ignition_url=http://10.20.0.1/coreos/bare_metal_config.ign
```
I also have the file http://10.20.0.1/coreos/fedora-coreos-31.20200127.3.0-metal.x86_64.raw.xz.sig located.

**Issue1**
Documentation does not indicate that *.sig file must be present.  `coreos-installer `script is looking for that in the same location as *.raw.xz file.

**Issue2**
Once that signature file is found, the URL is turned into https - I have no https service running on the same location.  Addition option of ```coreos.inst.insecure=yes``` does not help.

![coreos_install_screenshot](https://user-images.githubusercontent.com/1679347/75568688-98eb0a00-5a08-11ea-8878-68ed18b775ac.jpg)

**Comment by lucab** [comment]
@shivarammysore thanks for the report! I think those are indeed two valid bugs. Just a bunch of followup questions.

> Documentation does not indicate that *.sig file must be present

Can you please link here the documentation you are following, so we can update it?

> Once that signature file is found, the URL is turned into https - I have no https service running on the same location.

This one is a bit bizarre, it would be helpful to get a network a trace.
My gut feeling is that the following is happening:
 * there is a custom 404 handler on the HTTP service
 * the 404 handler points to the same location, but over HTTPS
 * there is a HTTPS service running at the same IP, with a self-signed (or similar) certificate
 * coreos-installer follows the redirect-on-404, hitting the HTTPS service and failing to verify its trust chain

**Comment by shivarammysore** [comment]
I used documentation from:
https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/
https://github.com/coreos/coreos-installer

Please note that supported PXE options are not provided in main documentation pages, but, only sporadically included in the coreos-installer Github repo.

The other thing that I noticed was that even though I had ```coreos.inst.insecure``` option set, it did not help.  I expected that signature file lookup would be bypassed completely.

Unfortunately, I will need to setup a lot more of the infrastructure  to get you more traces.  First, my headless device with only console service was not sufficient.  Hence, I tried via laptop install and I was able to see some better information which I have shared.

**Comment by lucab** [comment]
@shivarammysore ack. Even just the access logs/configuration for the HTTP and HTTPS service should be enough to confirm/dismiss my theory.

**Comment by shivarammysore** [comment]
Per https://github.com/coreos/coreos-installer/blob/master/src/cmdline.rs#L227 ```coreos.inst.insecure``` option does not take a value.  I have since corrected it.  Still does not help.

From ```nginx.log```
```
Feb 28 10:35:59 tor tor.road.foobar.org nginx: 10.20.30.193 - - [28/Feb/2020:10:35:59 -0800] "GET /coreos/bare_metal_config.ign HTTP/1.1" 301 178 "-" "curl/7.66.0"
Feb 28 10:36:01 tor tor.road.foobar.org nginx: 10.20.30.193 - - [28/Feb/2020:10:36:01 -0800] "GET /coreos/fedora-coreos-31.20200127.3.0-metal.x86_64.raw.xz.sig HTTP/1.1" 301 178 "-" "reqwest/0.9.24"
```

**Comment by shivarammysore** [comment]
@lucab There is a HTTPS service running on the same box - for authenticated access - but, it does not have this "*.sig" file content.

**Comment by bgilbert** [comment]
> The other thing that I noticed was that even though I had coreos.inst.insecure option set, it did not help. I expected that signature file lookup would be bypassed completely.

`coreos.inst.insecure` currently doesn't prevent fetching and verifying the signature.  It's only supposed to make a failure non-fatal.

**Comment by lucab** [comment]
@shivarammysore thanks for the access log. You can see indeed that there is a 301 for the signature, which is (possibly) where the HTTP -> untrusted-HTTPS redirects happens.

**Comment by shivarammysore** [comment]
The issue #403 is not related to this though they can look similar.

**Comment by shivarammysore** [comment]
I understand the need for using `https`.  But, when the user explicitly specifies `http`, it is not right to just redirect to `https` service - don't assume that user meant `https`.

**Comment by lucab** [comment]
@shivarammysore your HTTP service is the one forcing the redirect (via a 301 response), right here:
> "GET [...].raw.xz.sig HTTP/1.1" 301 [...]

**Comment by dustymabe** [comment]
@lucab - anything else to do for this issue?

**Comment by lucab** [comment]
@dustymabe tagging a coreos-installer release containing https://github.com/coreos/coreos-installer/pull/177, and waiting for it to propagate to stable.

**Comment by dustymabe** [comment]
coreos-installer 0.1.3 went into testing stream release `31.20200407.2.2`.  Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `31.20200407.3.0`.
