### ISSUE TITLE
Fedora Coreos no ssh connection possible

### ISSUE THREAD

**Issue by moritz31** [coreos/fedora-coreos-tracker#405]
Tried to run the stable and unstable fedora coreos image on google cloud. 
It boot's up, but the problem is that i cannot connect via ssh like i can on other images. 
Is this behaviour intendended and a ignition file with the ssh key needs to be provided or is this a faulty behaviour? Couldn't find any documentation on that

**Comment by rochacon** [comment]
This can happen if you have issues with ignition (Fedora CoreOS cloud-init agent). If possible, retrieve the console log of the instance and you should see some errors during the boot regarding the issue with ignition execution.

**Comment by jlebon** [comment]
To confirm, you have SSH public keys registered in GCP either at the instance level or project level? If so, then yes, those should get picked up automatically by FCOS on boot and you don't have to provide an Ignition config.

**Comment by dustymabe** [comment]
@moritz31 - also make sure you are trying to connect as the `core` user.

**Comment by dustymabe** [comment]
@moritz31 - do you still have an issue or were you able to get in?

**Comment by moritz31** [comment]
@dustymabe i can now connect, but in my opinion it is not very well documented how this works. For coreos you could simply click to the connect with web-based ssh button in the gcp console and it connected with your user. With fedora coreos this is not possible. But besides that i think the issue can be closed

**Comment by jlebon** [comment]
> For coreos you could simply click to the connect with web-based ssh button in the gcp console

Hmm, is that OS login? See discussions in https://github.com/coreos/fedora-coreos-tracker/issues/67 about that.

**Comment by serge-wq** [comment]
@moritz31 Can you please write how yo fixed it? I'm having the same problem.

**Comment by xinzhang** [comment]
We also have this issue due to we are using this image for gitlab runner.
Gitlab runner can start the instance then it is failed with error in ssh connection.

**Comment by bfarayev** [comment]
It'd good to at least know how it was fixed for anyone

**Comment by jlebon** [comment]
Project and instance-specific SSH keys should be added automatically to the `core` user. Is that not what you're seeing?

Note FCOS does not support OS Login.

**Comment by MohamedZ3kri** [comment]
For people wanting to know how it was fixed, you'll need a public ssh key in [project/vm] metadata for the `core` user, then ssh using the `core` user and the private key.
