### ISSUE TITLE
Importing Fedora CoreOS VMDK into AWS

### ISSUE THREAD

**Issue by Promaethius** [coreos/fedora-coreos-tracker#406]
I've run into a situation where I need to import Fedora CoreOS into ec2 as a custom ami. After downloading, unzipping, and uploading into S3, I get this error.
```
{
    "ImportImageTasks": [
        {
            "ImportTaskId": "import-ami-...",
            "SnapshotDetails": [
                {
                    "DiskImageSize": 733499904.0,
                    "Format": "VMDK",
                    "Status": "completed",
                    "UserBucket": {
                        "S3Bucket": "...",
                        "S3Key": "fedora-coreos-31.20200210.3.0-aws.x86_64.vmdk"
                    }
                }
            ],
            "Status": "deleted",
            "StatusMessage": "ClientError: EFI partition detected. UEFI booting is not supported in EC2.",
            "Tags": []
        }
    ]
}
```
I'm using the cloud operator aws version.

**Comment by cgwalters** [comment]
See https://github.com/openshift/os/pull/396

**Comment by Promaethius** [comment]
@cgwalters thank you!

**Comment by dustymabe** [comment]
related: we also added this information to the FCOS docs:
- https://github.com/coreos/fedora-coreos-docs/pull/44
- https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_how_do_i_upload_fedora_coreos_to_private_aws_ec2_regions
