### ISSUE TITLE
cri-o unavailable in Fedora CoreOS 31

### ISSUE THREAD

**Issue by Promaethius** [coreos/fedora-coreos-tracker#409]
```
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200210.3.0 (2020-02-24T16:48:02Z)
                    Commit: 4ea6beed22d0adc4599452de85820f6e157ac1750e688d062bfedc765b193505
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
```
I see that fedora 30+ use modules to install cri-o. Is there an equivalent to Fedora CoreOS? Or is it out of scope for the time being?

**Comment by dustymabe** [comment]
Unfortunately this is complicated. See https://discussion.fedoraproject.org/t/installing-using-cri-o-on-fedora-coreos/15961/6

This is mostly a duplicate/combo of https://github.com/coreos/fedora-coreos-tracker/issues/88 and https://github.com/coreos/fedora-coreos-tracker/issues/93

**Comment by dustymabe** [comment]
@Promaethius Does that answer your question?

I'm going to close this out since it's covered by #88 and #93.
