### ISSUE TITLE
Move the build browser to the coreos/ GitHub org

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#410]
The FCOS build browser (https://builds.coreos.fedoraproject.org/browser) source code is currently at https://github.com/jlebon/fedora-coreos-browser/. I think it's time to transfer the repo to the coreos/ org.

Filing this for visibility.

One thing related to this is that the internal RHCOS builds also has its own build browser. It would be nice to unify them, though it doesn't seem like a high-priority item.

**Comment by jlebon** [comment]
Will do this by the end of the week unless there are any objections.

**Comment by dustymabe** [comment]
👍

**Comment by jlebon** [comment]
This is [done](https://github.com/coreos/fedora-coreos-browser)!
