### ISSUE TITLE
Missing kernel parameters to run Cilium/eBPF in Fedora CoreOS

### ISSUE THREAD

**Issue by rochacon** [coreos/fedora-coreos-tracker#411]
I'm trying to migrate from Container Linux to Fedora CoreOS, but it seems like a few kernel parameters required by Cilium [1] are not present in fcos, even though they were in Container Linux.

Is there a way to meet this requirements [1] without recompiling the kernel myself?

[1] https://docs.cilium.io/en/v1.7/install/system_requirements/#linux-kernel

**Comment by dustymabe** [comment]
On the latest stable (`31.20200210.3.0`) I see:

 ```
$ grep  -P 'CONFIG_BPF=|CONFIG_BPF_SYSCALL=|CONFIG_NET_CLS_BPF=|CONFIG_BPF_JIT=|CONFIG_NET_CLS_ACT=|CONFIG_NET_SCH_INGRESS=|CONFIG_CRYPTO_SHA1=|CONFIG_CRYPTO_USER_API_HASH=|CONFIG_NETFILTER_XT_TARGET_TPROXY=|CONFIG_NETFILTER_XT_MATCH_MARK=|CONFIG_NETFILTER_XT_MATCH_SOCKET=' /lib/modules/*/config
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_NETFILTER_XT_TARGET_TPROXY=m
CONFIG_NETFILTER_XT_MATCH_MARK=m
CONFIG_NETFILTER_XT_MATCH_SOCKET=m
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_JIT=y
CONFIG_CRYPTO_SHA1=y
CONFIG_CRYPTO_USER_API_HASH=y
```
This means that several of the required things are modules. You can get more information on them with

```
modinfo cls_bpf sch_ingress xt_mark xt_socket xt_TPROXY
```
You can load them interactively with:

```
sudo modprobe -a cls_bpf sch_ingress xt_mark xt_socket xt_TPROXY
```

But we recommend you lay down a file in `/etc/modules-load.d` using Ignition. Here is an FCCT config you can use:

```
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/modules-load.d/cilium.conf
      mode: 0660
      contents:
        inline: |
          cls_bpf
          sch_ingress
          xt_mark
          xt_socket
          xt_TPROXY
```

**Comment by rochacon** [comment]
Cool!! I'm unsure which version I used on previous testing, its been a few weeks already. I'll bootstrap a new cluster with fcos and the modules-load.d file as mentioned and in case I hit any other roadblock I'll re-open this issue.
Thank you very much @dustymabe for the great explanation.

**Comment by dustymabe** [comment]
> Thank you very much @dustymabe for the great explanation.

No problem. Thanks for using Fedora CoreOS!
