### ISSUE TITLE
Fedora CoreOS content for Community Central for RH Virtual Summit

### ISSUE THREAD

**Issue by riecatnor** [coreos/fedora-coreos-tracker#416]
Hi CoreOS folks,

We are planning to highlight Fedora CoreOS at Community Central virtual event for RH Summit. We are in need of some ideas/content for presentation. Please brainstorm some ideas of how you would like to show it off - don't worry about the design logistics yet. Come up with 3-5 ideas, and we should be able to execute on at least one :)

Thanks!

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/7PA5CZ6RDOPN6V33EZRSX425NCIXPWV3/).

It seems like the general sentiment is that the group would like to publish some sort of recorded presentation about the project in general and the value proposition behind it. This presentation could include demos that illustrate the various points. So the proposal is:

- produce talk with demos interspersed throughout
- publish demos individually for more focused content, but with a link back to the talk for context

Ideas for things to demo:

- show off ignition (simple example) + maybe show how much it's leveraged during an openshift/OKD install
- show off automatic updates
- show off a failed update and being able to recover
- show off immutability (possibly rm / protection)
- explain/show off bare metal installs using Ignition for FCOS


With all of this said, we don't yet have any volunteers to produce the material so we'll work on that.

**Comment by dustymabe** [comment]
@riecatnor - do you have a deadline for this material?

**Comment by dustymabe** [comment]
RH summit has passed.
