### ISSUE TITLE
download page: allow for direct links to the three tabs

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#417]
The [download page](https://getfedora.org/en/coreos/download/) has three main tabs on it, but you can't link someone directly to anything other than the "Cloud Launchable" tab. This means that when you are sharing information you need to tell someone 2 steps to get to the content you are referring to rather than 1.

Today if I wanted to tell someone to download the latest live ISO image:

- Go to https://getfedora.org/en/coreos/download/
- click `Bare Metal & Virtualized` tab
- click `Download` under the `ISO` section

Ideally in the future it would just be:

- Go to https://getfedora.org/en/coreos/download/tabname
- click `Download` under the `ISO` section

Where `tabname` is whatever we decide the tabs naming scheme should be.

**Comment by dustymabe** [comment]
cc @zonggen - do you know of a way to solve this issue?

**Comment by zonggen** [comment]
That seems like a matter of adding routing for the frontend and redirecting to the target tab view.
Will submit a PR on this shortly.

**Comment by zonggen** [comment]
EDIT:
fcct-onine (https://github.com/coreos/fcct-online/blob/master/client/src/router.js#L17) used Vue templates and the configs in the URLs are processed by the Frontend before sending to the backend.

Whereas in the download website we didn't use Vue templates and the requests are directly sent to the backend, therefore modifications on the backend are required, e.g. (https://pagure.io/fedora-web/websites/blob/master/f/sites/getfedora.org/main.py#_208). Though I'm not sure if this is a good design to add more detailed routing so I filed https://pagure.io/fedora-web/websites/issue/98. Just wanted to make sure before I proceed.

**Comment by dustymabe** [comment]
@zonggen thanks for [the PR](https://pagure.io/fedora-web/websites/pull-request/99) that makes the following links route to the appropriate tabs:

- https://getfedora.org/en/coreos/download/cloud_launchable/
- https://getfedora.org/en/coreos/download/metal_virtualized/
- https://getfedora.org/en/coreos/download/cloud_operators/

There is one remaining issue I see. Right now I need to memorize those URLs if I want to link someone to one of the pages because when I click on the tabs within the page it doesn't update the URL in my browser bar at the top. Is there a way to update the URL in my browswer at the top when the tabs are clicked?

**Comment by zonggen** [comment]
Sure, it makes sense to keep the url and tabs consistent :+1:

**Comment by dustymabe** [comment]
The download page has been updated [demo here](https://pagure.io/fedora-web/websites/pull-request/102#comment-113590) and now makes perfect sense. Thanks @zonggen !
