### ISSUE TITLE
re-using existing disks when doing an install; re-creating partitions with Ignition

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#418]
During our internal cabal meeting, the topic of installing *CoreOS onto existing infrastructure was discussed; specifically the need for preserving existing partitions during the install phase.

One of the suggested approaches was to determine the existing partition table of a disk, determine which partitions need to be preserved, and then have Ignition create the partition table with the preserved partitions included.

@jlebon suggested we discuss this path for installing + preserving partitions in more detail, so filing this issue as place to start.

cc: @glennswest

**Comment by bgilbert** [comment]
Specifically, the Ignition config for the live system would:
1. Run a unit `Before=coreos-installer.service` that would probe the partition table and detect the relevant partition/offset/length.
2. Run coreos-installer as usual.  For safety we might want something like https://github.com/coreos/coreos-installer/issues/190.
3. Run another unit `After=coreos-installer.service` which recreates the desired data partition.

As an alternative, we could avoid step 3 by having step 1 inject the partition info into the Ignition config.  But the proposed approach would be more self-contained.

**Comment by travier** [comment]
With this workflow, the data partitions selected for preservation may end up being lost if an issue where to happen (power loss, etc.) between the beginning of the installation process (step 2) and the partition restoration step (3).

**Comment by travier** [comment]
Also related to: https://github.com/coreos/fedora-coreos-tracker/issues/399

**Comment by travier** [comment]
I am currently looking if it could be possible to reuse a partition layout while ensuring there is enough space for the installation thus avoiding the repartitioning step.

**Comment by glennswest** [comment]
Actually in the version using classic installer, I save the partitions numbers above partition #4, let the install run, and append them after the install. Further if there is no partitions above 4, I create a data partition. Generally with disk sizes, there is plenty of space. This approach works well. 
In the bash mode, I use sfdisk to pull the existing partitions, and concat the saved partitions.
Need to look how to do this in rust.

Done properly no change in ignition is needed.

**Comment by bgilbert** [comment]
Implemented via `coreos-installer install --save-partindex/--save-partlabel` in [coreos-installer 0.5.0](https://github.com/coreos/coreos-installer/releases/tag/v0.5.0).

**Comment by dustymabe** [comment]
Thanks @bgilbert!

The fix for this went into stable stream release `32.20200809.3.0`, which was released a few weeks ago.
