### ISSUE TITLE
Fedora CoreOS talks for devconf.us 2020

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#420]
https://www.devconf.info/us/

Happening sept 23-25th in MA. We should submit some talks.

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/7PA5CZ6RDOPN6V33EZRSX425NCIXPWV3/).

Some ideas:

- State of Fedora CoreOS talk 
- Intro to Fedora CoreOS talk (maybe combine with state of FCOS talk)
- Ignition deep dive talk (might have some content for this already from Andrew)
- Re-run of Luca's talk about our update service

**Comment by LorbusChris** [comment]
CfP closes April 27.

I'm thinking about submitting the following proposals:
- OKD talk
- greenboot presentation/demo (possibly as part of a Fedora IoT talk)

**Comment by dustymabe** [comment]
Note the CFP got extended and closes tomorrow (May 30). Please submit talks.

Benjamin and I are planning to submit later today a generic Fedora CoreOS overview talk. Would be nice to get some specific talks submitted. Maybe one from @jlebon about osmet would be cool. Or ones from @lucab or @cgwalters that are re-runs of their interesting talks from devconf.cz.

**Comment by LorbusChris** [comment]
@dmueller2001 @runcom and I have submitted a joint talk about OKD 4 and MCO: `OKD 4 - OpenShift K8s on Fedora CoreOS`

**Comment by dustymabe** [comment]
@bgilbert and I submitted `Inside Fedora CoreOS`, an introductory and overview talk to try to raise awareness.

I'll close out this issue now that the CFP is closed.
