### ISSUE TITLE
Modify Afterburn openstack defaults to try config-drive, then metadata service

### ISSUE THREAD

**Issue by jamescassell** [coreos/fedora-coreos-tracker#422]
The afterburn folks think this is "not a bug": https://github.com/coreos/afterburn/issues/373

We should work around it here, and attempt to get SSH keys from MD service, especially if no IGN is provided.

See also about hostname: https://github.com/openshift/machine-config-operator/pull/964#issuecomment-513178768

```
State: idle
AutomaticUpdates: disabled
Deployments:
* ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 31.20200310.2.0 (2020-03-12T01:21:36Z)
                    Commit: fef0f5a226ebf0e9915d8ee03a3bc70d3cc0593f0c22841264b3bc906dff0957
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
```

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/NA7CMN5HZWKUVVQNG4XPJDX5226BBNGG/):

```
13:54:19     dustymabe | #agreed modify afterburn to only know about `openstack` and in that mode, read from the config drive first
                       | then fallback to fetch from metadata server

```

**Comment by stamak** [comment]
@dustymabe any updates on this?
thx

**Comment by dustymabe** [comment]
@stamak - not currently. It's decided what the path forward is but we haven't had time to implement it yet. Stay tuned

**Comment by lucab** [comment]
This has been implemented by @zonggen in https://github.com/coreos/afterburn/pull/462 and released as part of Afterburn 4.5.0.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `32.20200824.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20200824.3.0`. Please try out the new release and report issues.
