### ISSUE TITLE
OKD-4.4 install, FCOS does not persist NIC settings provided as kernel args

### ISSUE THREAD

**Issue by cgruver** [coreos/fedora-coreos-tracker#425]
_I will attempt to grab `rpm-ostree status` and post it below._

FCOS version: 31.20200210.3.0-metal-x86_64 

I am trying to get an OKD-4.4 cluster to bootstrap with 2 NICs in the master and worker nodes.   However, FCOS appears to be overriding the IP configuration that I am setting in the iPXE boot file, and reverting the second NIC to DHCP.  It is then trying to set a route on the second NIC and is therefore unable to communicate with the bootstrap node.  The same configuration will successfully install with just one NIC, (DHCP Reservation on eth0).  

The iPXE file is named for the MAC of the primary NIC and has the following kernel config: 

```
kernel path/to/fcos/vmlinuz ip=:::::eth0:dhcp ip=10.11.12.100:::255.255.255.0::eth1:none rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=path/to/fcos/install.xz coreos.inst.ignition_url=path/to/fcos/ignition/master.ign coreos.inst.platform_id=qemu console=ttyS0
```

During the initial boot, and subsequent install of FCOS it is honoring the ip configuration.  But then appears to revert to DHCP for eth1 after performing its first-boot.  I have also tried DHCP for eth1 with IP reservations, but it still tries to use it as a route-able network, and thus cannot bootstrap.

Suspect that dracut is not persisting the network config that is provided by the initial kernel args.

I am very new to RHCOS/FCOS so let me know what additional information will be useful.

**Comment by vrutkovs** [comment]
Seems related to https://github.com/coreos/fedora-coreos-tracker/issues/394

**Comment by cgwalters** [comment]
Yep, RHCOS today carries [this code](https://github.com/coreos/ignition-dracut/pull/89) but the intention is that once we have NM in the initrd, NM will honor kernel arguments for the firstboot and subsequent.

**Comment by cgruver** [comment]
Thanks!

I'll monitor the progress.  Let me know when there is an FCOS image ready to test.  I'll give it a shot.

**Comment by dustymabe** [comment]
We are now [using NetworkManager in the initramfs](https://github.com/coreos/fedora-coreos-tracker/issues/394) and also [propagating network information from the initramfs (kargs) when appropriate](https://github.com/coreos/fedora-coreos-tracker/issues/394#issuecomment-599721173), which we think fixes this issue.

See https://github.com/coreos/fedora-coreos-tracker/issues/394#issuecomment-604598128 and the preceding discussion for more details.

**Comment by cgruver** [comment]
Excellent!

I will run an OKD deployment with fixed IPs and test it out.
