### ISSUE TITLE
equivalent of user-config.target in FCOS

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fedora-coreos-tracker#430]
What is the equivalent of using `user-config.target` [1] in FCOS?  Examples?

[1] https://github.com/coreos/coreos-cloudinit/blob/master/units/user-config.target

**Comment by dustymabe** [comment]
hey @shivarammysore. I believe that target is/was associated with CoreOS Cloud Init. Is that correct?

In Fedora CoreOS [we only have Ignition](https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_how_are_fedora_coreos_nodes_provisioned_can_i_re_use_existing_cloud_init_configurations).

**Comment by shivarammysore** [comment]
hi @dustymabe you are right.  This was needed in CoreOS earlier to get access to the AWS AMI `user_config_data`.
Per my subsequent investigation (ongoing), I think it will work by just having `network-online.target` service running.

**Comment by dustymabe** [comment]
K let us know what you find

**Comment by dustymabe** [comment]
I'm going to assume we can close this. Please re-open if there is more to discuss.

**Comment by shivarammysore** [comment]
Just to complete the thread - In my use cases, I replaced target `user-config` with just `network-online` in my `systemd` files and it works.
