### ISSUE TITLE
PXE boot hangs

### ISSUE THREAD

**Issue by fclerg** [coreos/fedora-coreos-tracker#431]
Hello,

during PXE boot, the installation hangs at:
```
[   29.382477] random: crng init done
[   29.386462] random: 7 urandom warning(s) missed due to ratelimiting.
```

It seem to be due to a lack of entropy on the VM. I tried to pass the kernel option `random.trust_cpu=on` but still get the issue. I waited up to 12 hours but no progression in the boot process.

I also tried to add the _virtio-rng-pci_ device to the VM  to use the host's /dev/urandom. In that case the install still hangs even before the above stage (see [screenshot](https://user-images.githubusercontent.com/29798784/77261554-24159380-6c87-11ea-91a6-2360de9769e0.png)). Same thing by passing either with /dev/urandom or /dev/random to the VM:
```
args: -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,addr=4
```

Although when the VM is running with these arguments, I can confirm that it uses the specified random file from the host :
```
# lsof /dev/urandom
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
kvm     14815 root   11r   CHR    1,9      0t0   11 /dev/urandom
```

I installed haveged on the host to increase the entropy but no luck.

Ideally, I would like to install haveged on the initramfs.  I can't do it via an ignition file asI’m afraid ignition is run later in the boot process.

Such entropy issues seem to have been raised before, like [here](https://bugzilla.redhat.com/show_bug.cgi?id=1572916)

Here is my config :
**Host OS**: Proxmox 5.2-12
**Host Kernel**: 4.15.18-9-pve
**Qemu version**: 2.12.1

Let me know if you need any other info. Thank you!

**Comment by dustymabe** [comment]
hey @fclerg. A few questions:

- what version of FCOS are you using?
- what image artifact did you download?
- what exact commands are you using to launch the instance?

**Comment by fclerg** [comment]
I am using FCOS version 31.20200210.3.0

I downloaded
- _fedora-coreos-31.20200210.3.0-live-kernel-x86_64_
- _fedora-coreos-31.20200210.3.0-live-initramfs.x86_64.img_
- _fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz_

the VM is launched with this command :
```
/usr/bin/kvm\
  -id 883
  -name kmaster1\
  -chardev socket,id=qmp,path=/var/run/qemu-server/883.qmp,server,nowait\
  -mon chardev=qmp,mode=control\
  -chardev socket,id=qmp-event,path=/var/run/qmeventd.sock,reconnect=5\
  -mon chardev=qmp-event,mode=control\
  -pidfile /var/run/qemu-server/883.pid\
  -daemonize\
  -smbios type=1,uuid=3742ce17-384d-4da8-8339-61cb642cbf3a\
  -smp 2,sockets=1,cores=2,maxcpus=2\
  -nodefaults\
  -boot menu=on,strict=on,reboot-timeout=1000,splash=/usr/share/qemu-server/bootsplash.jpg\
  -vnc unix:/var/run/qemu-server/883.vnc,x509,password\
  -cpu kvm64,+lahf_lm,+sep,+kvm_pv_unhalt,+kvm_pv_eoi,enforce\
  -m 3072\
  -device pci-bridge,id=pci.2,chassis_nr=2,bus=pci.0,addr=0x1f\
  -device pci-bridge,id=pci.1,chassis_nr=1,bus=pci.0,addr=0x1e\
  -device piix3-usb-uhci,id=uhci,bus=pci.0,addr=0x1.0x2\
  -device usb-tablet,id=tablet,bus=uhci.0,port=1\
  -device VGA,id=vga,bus=pci.0,addr=0x2\
  -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x3\
  -iscsi initiator-name=iqn.1993-08.org.debian:01:c06aedf59735\
  -drive file=/var/lib/vz/images/883/vm-883-disk-0.qcow2,if=none,id=drive-ide0,cache=unsafe,format=qcow2,aio=threads,detect-zeroes=on\
  -device ide-hd,bus=ide.0,unit=0,drive=drive-ide0,id=ide0,bootindex=200\
  -device ide-cd,bus=ide.0,unit=1,drive=drive-ide1,id=ide1,bootindex=300\
  -netdev type=tap,id=net0,ifname=tap883i0,script=/var/lib/qemu-server/pve-bridge,downscript=/var/lib/qemu-server/pve-bridgedown\
  -device e1000,mac=0E:20:38:5D:46:BC,netdev=net0,bus=pci.0,addr=0x12,id=net0,bootindex=100
  -machine type=pc
```

**Comment by dustymabe** [comment]
I'm slightly missing where the downloaded images are represented in the qemu/kvm command you've shared. Are you trying to do a PXE boot?

One example of a qemu-kvm CLI invocation is shown [in our documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/#_launching_with_qemu_or_libvirt) (Note that the example shows booting a *qemu.qcow2* image). Maybe you can compare your command line invocation with that one? 

I also [recently wrote a blog about using some new features of libvirt along with the live PXE artifacts to test full installs](https://dustymabe.com/2020/01/30/virt-install-boot-from-specific-kernel/initrd-just-for-install/), but that uses libvirt, not qemu directly.

**Comment by cgwalters** [comment]
Additionally, we have https://github.com/coreos/coreos-assembler/blob/master/src/cmd-virt-install
and actual CI tests (most recently https://github.com/coreos/coreos-assembler/pull/1168 )

I think the real problem is something else and you're just seeing the entropy logs last.

**Comment by fclerg** [comment]
@dustymabe I am indeed trying to do a PXE boot (as mentioned in the title of this issue;).
Here is my iPXE config (it is provided by Matchbox to match a configuration with a machine):
```
        "boot": {
                "kernel": "http://10.20.30.100:8000/fedora-coreos-31.20200210.3.0-live-kernel-x86_64",
                "initrd": [
                        "http://10.20.30.100:8000/fedora-coreos-31.20200210.3.0-live-initramfs.x86_64.img"
                ],
                "args": [
                        "ip=dhcp",
                        "rd.neednet=1",
                        "initrd=fedora-coreos-31.20200210.3.0-live-initramfs.x86_64.img",
                        "coreos.inst.image_url=http://10.20.30.100:8000/fedora-coreos-31.20200210.3.0-metal.x86_64.raw.xz",
                        "coreos.inst.ignition_url=http://matchbox.yuzu.local:8080/ignition?uuid=${uuid}\u0026mac=${mac:hexhyp}",
                        "coreos.inst.install_dev=sda",
                        "console=tty0",
                        "console=ttyS0"
                ]
        }
```

@cgwalters you're right, it is very possible that the problem is something else, other than entropy related.

**Comment by bgilbert** [comment]
`random: crng init done` means that entropy initialization completed successfully.  The actual issue is that you're specifying `ttyS0` as the primary console (it's the last `console=` argument in the list) and your userspace boot messages are going to the serial port instead of VGA.  It's possible that you're getting a boot failure due to a bad Ignition config.

**Comment by fclerg** [comment]
Thanks @bgilbert!
Removing `ttyS0` and leaving only `tty0` worked to see installation progress. It ended up being stuck because of signature verification failure. Adding the _.sig_ file of the release to my local web repo fixed it.

**Comment by dustymabe** [comment]
nice work @bgilbert ! Thanks for getting back to us @fclerg and letting us know the problem was resolved!
