### ISSUE TITLE
Bare metal installation failure on Ignition OSTree Mount (firstboot)

### ISSUE THREAD

**Issue by beelzetron** [coreos/fedora-coreos-tracker#433]
I am doing a FCOS bare metal installation on a HP Proliant Microserver N40L using the live iso following the procedure described here: https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/

The very first boot after the coreos-installer has ran stops at the Ignition OSTree: mount (firstboot) stage with the error
`ignition-ostree-mount-sysroot[704]: /usr/sbin/ignition-ostree-mount-sysroot: line 13: TYPE: unbound variable`

![ignition_error](https://user-images.githubusercontent.com/3071092/77292548-cf9f0200-6ce0-11ea-9e80-3f633bab096e.jpg)

The boot fails after this error and the system remains in this state forever.

**Comment by cgwalters** [comment]
https://github.com/coreos/fedora-coreos-config/pull/313

**Comment by cgwalters** [comment]
is your ignition config doing anything to reprovision the rootfs (or any partitioning at all?)

**Comment by beelzetron** [comment]
Yes, it wipes the partition table on the boot disk.
Here is my ignition config:
https://github.com/beelzetron/thor-fcos/blob/master/thor.ign

**Comment by beelzetron** [comment]
It turned out that this was a bad use of ignition on my side, thank you @jlebon for helping me out on this on IRC.

I was trying to reprovision my boot device on the first boot and this is not (yet?) supported, driving me to the reported error.

Feel free to close this one and thank you all for the advice and for the great work.
