### ISSUE TITLE
issue tracker for fedora releng integration

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#44]
I don't know all of the issues until we try but here's some I think may be issues:

 - I want our build process to use modern containers - specifically https://github.com/coreos/coreos-assembler/  (not koji+mock)
 - The prototype config repo currently lives [on github](https://github.com/cgwalters/fedora-coreos-config) - now I want to support "offline" builds too, do we just set up an automatic pagure import, or do people want to move it to pagure?

**Comment by bgilbert** [comment]
For the record, why does Pagure need to be involved?

**Comment by dustymabe** [comment]
> For the record, why does Pagure need to be involved?

It is a place fedora releng pulls configs from for builds (i.e. image builds or rpm-ostree composes, etc..) I'm not aware of any place other than pagure being allowed (at the moment), but I could be wrong.

**Comment by dustymabe** [comment]
some of this work (i.e. answering the question "What asks to we have of Fedora Releng?") is predicated on some of the work I'm doing in #49 - marking this as blocked for now.

**Comment by dustymabe** [comment]
I believe we have done some of this (design doc was created in https://github.com/coreos/fedora-coreos-tracker/pull/171) and we can close this in favor of follow on tickets. Some of which are:

- https://github.com/coreos/fedora-coreos-tracker/issues/137
- https://github.com/coreos/fedora-coreos-tracker/issues/169

**Comment by jlebon** [comment]
Agreed, though the Pagure bit is still outstanding I think. We should bring this up with releng.

**Comment by dustymabe** [comment]
> Agreed, though the Pagure bit is still outstanding I think. We should bring this up with releng.

We're already pulling from github and I interpreted them being willing to accept CentOS CI built artifacts as them also being OK with us pulling our manifest from Github. I'll open a ticket to get it ratified.

**Comment by dustymabe** [comment]
>  I'll open a ticket to get it ratified.

opened a ticket with releng: https://pagure.io/releng/issue/8373

**Comment by dustymabe** [comment]
releng acknowledged us using GitHub for our configs and are OK with it: https://pagure.io/releng/issue/8373#comment-571672
