### ISSUE TITLE
Missing coreos-metadata binary and systemd unit

### ISSUE THREAD

**Issue by jdel** [coreos/fedora-coreos-tracker#446]
In the process of migrating my CoreOS EC2 instances to Fedora CoreOS I am encountering the following issue.

Expected behaviour:
`systemctl start coreos-metadata.service` creates the file `/run/metadata/coreos` 

Actual behaviour:
```
Failed to start coreos-metadata.service: Unit coreos-metadata.service not found.
```

The binary `/usr/bin/coreos-metadata` does not exist and I could not find a way to install it with `rpm-ostree`.

Output of `rpm-ostree` status:
```
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200310.3.0 (2020-03-25T19:42:10Z)
                    Commit: 436592e6eb93e899bebab8dbd17514c85be683390ef8bbce8c6d96069ce4c543
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
```

Please advise on an alternative way to fetch metadata, possibly in the same env format so it is directly usable by `systemd` units.

Thanks in advance

**Comment by bgilbert** [comment]
coreos-metadata has been [renamed to Afterburn](https://docs.fedoraproject.org/en-US/fedora-coreos/migrate-cl/#_configuration_changes).

**Comment by jdel** [comment]
Ah I missed that ! Thanks you for pointing it out.
