### ISSUE TITLE
Enabling instance of service unit does not work

### ISSUE THREAD

**Issue by jdel** [coreos/fedora-coreos-tracker#448]
It seems impossible to start an instance of a service using Ignition.

`fcct` snippet used:

```
systemd:
  units:
  - name: echo@foo.service
    enabled: true

  - name: echo@bar.service
    enabled: true

  - name: echo@.service
    contents: |
      [Unit]
      Description=f
      [Service]
      Type=oneshot
      ExecStart=/bin/echo %i
      RemainAfterExit=yes
      
      [Install]
      WantedBy=multi-user.target
```

Expected result: `echo@foo.service` and `echo@bar.service` are both enabled and started on system first boot.

Actual result: both services are still disabled, despite being mentioned in `/etc/systemd/system-preset/20-ignition.preset`

```
enable echo@foo.service
enable echo@bar.service
enable afterburn.service
enable install-rpms.service
enable bootstrap-netdata.service
enable confd.service
enable sssd.service
```

Output of `rpm-ostree status`:
```
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200310.3.0 (2020-03-25T19:42:10Z)
                    Commit: 436592e6eb93e899bebab8dbd17514c85be683390ef8bbce8c6d96069ce4c543
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
```

Since [coreos/ignition PR #934](https://github.com/coreos/ignition/pull/934/files) has been merged, please consider this ticket more like a reminder / test case to include the new ignition release in the next FCOS release.

**Comment by lucab** [comment]
Can you please try with current `testing` release (31.20200323.2.1)? It should already contain the fix for this, thus it would be to check whether everything is fine now.

**Comment by lucab** [comment]
Cross-referencing: next stable release is going to be https://github.com/coreos/fedora-coreos-streams/issues/74 (next week).

**Comment by jdel** [comment]
Hello Luca,

Confirmed this works as expected with the latest testing AMI. 👍 

Thanks

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `31.20200323.3.2`.
