### ISSUE TITLE
fcct: duplicate units name should be detected/rejected

### ISSUE THREAD

**Issue by jdel** [coreos/fedora-coreos-tracker#451]
I discovered this by mistake, but `fcct` translates duplicate `yaml` systemd units into duplicate `json` entries that are treated as invalid by Ignition despite being valid `json`.

This makes ignition crash with:
```
[    5.972411] ignition[522]: error at $.systemd.units.1, line 1 col 1263: duplicate entry defined
[    5.972764] ignition[522]: failed to fetch config: config is not valid
[    5.972859] ignition[522]: failed to acquire config: config is not valid
[    5.973083] ignition[522]: Ignition failed: config is not valid
```

Expected behaviour:
To match one of Ignition's original goal:
> By making users run their configs through ct before they attempt to boot a machine, issues with their configs can be caught before any machine attempts to boot. This will save users time, as they can much more quickly find problems with their configs. Were users to provide Container Linux Configs directly to machines at first boot, they would need to find a way to extract the Ignition logs from a machine that may have failed to boot, which can be a slow and tedious process.

`fcct` outputs a warning in such cases and fails with `--strict` instead of letting me discover the error in the console log of my instance stuck in a crashed boot loop.

Actual behaviour: 
`fcct` doesn't output anything even with `--strict` and generates `json` with duplicate entries.

To reproduce the issue, use this simple configuration:

```
variant: fcos
version: 1.0.0

systemd:
  units:
  - name: echo@foo.service
    enabled: true

  - name: echo@foo.service
    enabled: true

  - name: echo@.service
    contents: |
      [Unit]
      Description=f
      [Service]
      Type=oneshot
      ExecStart=/bin/echo %i
      RemainAfterExit=yes
      
      [Install]
      WantedBy=multi-user.target
```

The same behaviour is observed with regular (non instantiated) services.

Output of `rpm-ostree status`:

```
State: busy
AutomaticUpdates: disabled
Transaction: (null)
Deployments:
  ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 31.20200323.2.1 (2020-03-31T03:01:53Z)
                BaseCommit: c94da3c9b79523e7e45e77ad5f1946ef419ab589e096ab68df3e097d34370ae2
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
                      Diff: 1 added
           LayeredPackages: libsss_sudo

● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 31.20200323.2.1 (2020-03-31T03:01:53Z)
                    Commit: c94da3c9b79523e7e45e77ad5f1946ef419ab589e096ab68df3e097d34370ae2
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
```

I created the issue here because it could be resolved in either `fcct` or Ignition.

**Comment by lucab** [comment]
Thanks for the report.

It sounds like a bug in Ignition validation logic (which `fcct` uses) not catching it. Did you try if `ignition-validate` miss that? If it does, it should be enough to fix it there and update `fcct` to use that.

**Comment by lucab** [comment]
@jdel additionally, which version of `fcct` are you using?

**Comment by jdel** [comment]
Hello Luca, I'm using `Fedora CoreOS Config Transpiler 0.5.0`.

`ignition-validate` fails as expected with the same error as in the boot log:
```
error at $.systemd.units.2, line 1 col 1329: duplicate entry defined
```

**Comment by lucab** [comment]
I looked a bit into the code and this is indeed a bug in `fcct`, not following the same validation path as Ignition. Fix is in progress at https://github.com/coreos/fcct/pull/93.

**Comment by dustymabe** [comment]
This was fixed upstream and is now pending a release of `fcct`.
