### ISSUE TITLE
Lacking troubleshooting method for ignition

### ISSUE THREAD

**Issue by hadmut** [coreos/fedora-coreos-tracker#453]
can't report rpm-ostree status, because I can't login. 

Hi,

I was giving latest Fedora CoreOS a try 31.20200310.3.0, using the iso to install on a kvm virtual test environment. 

A first, very simple ignition file worked as expected, but didn't do much, it created the account I've expected. 

Then I tried an ignition file with more options, and a complete fresh install (fresh virtual disk, coreos-installer from iso image), and obviously made some mistake in the ignition file. 

However, the console output was scrolling up so fast, that I did not  have a chance to see the output or any error messages.  Since there was no login possible later, not even a login prompt, I do not see how I could troubleshoot the ignition process and find it's output (except attaching the virtual disk to a running machine and hoping that the debug output somehow found it's way to the disk.)

So it's really difficult to troubleshoot once the ignition process failed. fcct found the file to be good.

**Comment by cgwalters** [comment]
See https://github.com/coreos/ignition-dracut/pull/146 for the qemu case and https://github.com/coreos/ignition/issues/585 for the general case.

**Comment by jlebon** [comment]
When Ignition fails, it should cause `emergency.target` to trigger, which should give you a prompt. By default, that prompt is on ttyS0 (i.e. on the serial console), but if you're doing this over VGA, you can change that by adding `console=tty0` at the end of the kernel cmdline or removing `console=ttyS0` (yes, this is a bit awkward).

**Comment by bgilbert** [comment]
Addressed by https://github.com/coreos/fedora-coreos-docs/pull/74.
