### ISSUE TITLE
compose failure `fedora-release-common` has lua script

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#459]
When trying to bump the lockfiles for testing-devel and we [hit an issue](https://github.com/coreos/fedora-coreos-config/pull/343#issuecomment-613466975) because:

```
error: Package 'fedora-release-common' has (currently) unsupported <lua> script in '%posttrans'
```

Looks like a lua scriptlet was added in https://src.fedoraproject.org/rpms/fedora-release/c/bfc4c31d8f625d4963a8169c9ba65686da7a4ce0?branch=f31 and [rpm-ostree doesn't support lua](https://github.com/coreos/rpm-ostree/issues/749). The good news is that it was only implemented for f31.

**Comment by jlebon** [comment]
Just going to paste relevant parts from IRC chat:

```
09:58:34 < jlebon> https://src.fedoraproject.org/rpms/fedora-release/c/bfc4c31d8f625d4963a8169c9ba65686da7a4ce0?branch=f31
09:58:58 < jlebon> which is totally irrelevant for us, so i think we can blacklist it in rpm-ostree
...
10:00:38 < dustymabe> jlebon: note we shouldn't have to do this for f32+
10:00:46 < dustymabe> looks like that change was only made on the f31 branch
...
10:09:52 < jlebon> https://bugzilla.redhat.com/show_bug.cgi?id=1780827#c30
10:10:42 < jlebon> that said, since it is indeed only on f31, and we don't actually need the patch, and we're moving to f32 soonish... we could probably leave it as an override and
                   ride it out
```

**Comment by dustymabe** [comment]
+1 to letting it ride in f31

**Comment by dustymabe** [comment]
ok since this isn't a problem in f32 and we are switching over to f32 soon anyway I'm going to close this out.

**Comment by heyakyra** [comment]
Seems related to https://github.com/fedora-silverblue/issue-tracker/issues/210 

is there a workaround? or a way to pinpoint the dependency leading to this?
