### ISSUE TITLE
4 (or 5) bullet points for marketing infographic

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#462]
Let's get 4 or 5 bullet point for a marketing infographic for Fedora (see https://pagure.io/design/issue/642). We can use the [server infographic](https://pagure.io/design/issue/647#comment-579419) for inspiration.

Maybe something along the lines of:

- Automatic Updates
- Container Focused
- Immutable (but without using the immutable word)

What else? Do we tout our various streams? Do we tout reliability of updates? Do we tout the automated testing we do?

**Comment by lucab** [comment]
My personal ones would be:
 * Automation-friendly provisioning
 * Ready for clusters and containerized workflows
 * Multiple rolling streams
 * Atomic version-control for OS components 
 * Auto-updates by default

**Comment by dustymabe** [comment]
We discussed this in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/LUVFUJEZAEJOCEDYBX6RDQ7IN5CQZ6VI/).  We started with @lucab's previous suggestions but wanted to try to get the title of each bullet down to as few words as possible.. Here's what we were brainstorming in the meeting:

- Automated Provisioning or something along the lines of Ignition based provisioning
- OS Versioning
- Automatic Updates
- Cloud Native

Also possibly a bullet about Security, but as was noted in the meeting sometimes advertising security is not the best idea.

More or less we we'd like to try to get top level bullets that allow us to cover these lower level bullets in the details:

- SELinux enforcing
- Read only filesystem mounts
- Optimized for containerized applications
- Ready for clustered deployment
- Automated provisioning with Ignition
- OS versioning with rpm-ostree ("git for your OS")
- Atomic Rollbacks
- Automatic updates on by default
- Multiple streams (next, testing, stable)
- Ubiquitous (available in as many platforms as possible)

**Comment by dustymabe** [comment]
Man this is really hard.. This is what I came up with... I'm not good at marketing. :smile: 

Automated Declarative Provisioning

- Leveraging Ignition for provisioning, Fedora CoreOS allows you the the flexibility
to control an instances identity from first boot, without ever needing to log in or
perform manual configuration.

Automatic Updates

- No need to think about keeping your Host OS up to date. Fedora
CoreOS is set to auto-update by default. CI testing and multiple
update streams help to battle test updates before they reach your
system.

Cloud Native

- Fedora CoreOS is offered on many different cloud platforms. With
Ignition you can burst and add new instances to your cluster.
Don't have a cloud? No problem. The Fedora CoreOS image is the same across
bare metal and cloud; leveraging the same Ignition provisioning stack
to unify provisioning across heterogeneous environments.

Container Focused

- Have a containerized application that you'd like to run? Fedora
CoreOS has the podman and moby-engine container runtimes that can be
leveraged for standalone uses. Want more? Leverage a
Kubernetes distribution to bring full blown orchestration platform to
your fingertips.

OS Versioning & Security

- Fedora CoreOS is built on RPM-OSTree and hardened in and
out with an enforcing SELinux policy. Rest easy knowing that
software versions are strongly tracked and binary files are read/only
by default.

**Comment by dustymabe** [comment]
cc @bgilbert to be my guiding light

**Comment by cgwalters** [comment]
I think what's there is great!

**Comment by dustymabe** [comment]
Reported in the [marketing ticket](https://pagure.io/design/issue/642#comment-666652) that we can move forward with https://github.com/coreos/fedora-coreos-tracker/issues/462#issuecomment-659025570. Will close this out.
