### ISSUE TITLE
switch to root=<uuid> post-firstboot?

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#465]
Currently we rely on finding the rootfs by just assuming `/dev/disk/by-label/root`, on both firstboot and subsequent boots.

One problem I hit is that if you e.g. image a USB stick with the FCOS metal image and put it in a machine that has an existing install, you can easily boot from the main hard drive but have the OS mount the USB stick as `/`, which is confusing to say the least.

One option would be for us to extend the existing [GPT uuid regeneration](https://github.com/coreos/ignition-dracut/blob/master/dracut/30ignition/coreos-gpt-setup@.service) to also generate a new XFS uuid for the rootfs, and inject a `root=<uuid>` karg using it by default.

It's also just cleaner for e.g. backup/snapshot systems if they don't have to deal with potentially duplicate UUIDs.

I can't think of any downsides to this really.

The other reason to do this is in order to support [complex root devices](https://github.com/coreos/fedora-coreos-tracker/issues/94) we'll end up changing the kernel cmdline, and so we might as well do it always.

**Comment by cgwalters** [comment]
However, one other thing we could do in addition - if we can figure out how - is to somehow determine from the bootloader which disk it used to boot, and by default find the rootfs on that disk.  In complex root scenarios we'd want to break that "lock", but it would add even more robustness in the !reprovisioned case.

It looks like grub for example injects `BOOT_IMAGE=(hd0,gpt1)/ostree/fedora-coreos-2b43aa9994cbeaaf271dd1e873c6d563178d383c4996d1db32d0981af0ba4f53/vmlinuz-5.5.15-200.fc31.x86_64 ` but would need to dig in on if/how `hd0,gpt1` can be reliably translated into the same thing that the Linux kernel sees.

**Comment by darkmuggle** [comment]
In principle, I'm not opposed. But https://github.com/coreos/ignition-dracut/issues/154#issuecomment-615290462 shows how this could be a problem - once you though DM mapper into the mix, the selection becomes a PITA. Pretty much every device mapper target uses its own method of setting up a link.

What do you think about a udev rule set that creates `/dev/disk/coreos/<UUID>` that handles the device heirchy? Then the change would be `root=/dev/disk/coreos/<UUID>`.

**Comment by jlebon** [comment]
I like the optics of having a minimal set of kargs. I admit this is a very superficial reason though and shouldn't have as much importance put into it over solving real technical issues (but it's still worth some importance I think?).

That said, I really like the idea in https://github.com/coreos/fedora-coreos-tracker/issues/465#issuecomment-615286296. It's explicit already: you *chose* to boot from this specific device.

**Comment by cgwalters** [comment]
> I like the optics of having a minimal set of kargs. 

Agree; OTOH, we fully expect a sizable percentage of users to use complex root devices too.

> That said, I really like the idea in #465 (comment). It's explicit already: you chose to boot from this specific device.

Right actually...here's an idea, we generate a new uuid for `boot` and have `boot=<uuid>` on the kernel cmdline.  Then if there's no `root=` karg, we can find the root disk by looking just at the disk containing the boot uuid.

>  But coreos/ignition-dracut#154 (comment) shows how this could be a problem - once you though DM mapper into the mix, the selection becomes a PITA. 

I don't think this makes multipath any better or worse - finding the root device via a UUID isn't much different from finding it by label - there are still multiple paths to the device.

However, how I see this helping multipath (and rootfs reprovisioning in general) is that we standardize on the "discovery via boot/root" kernel args even in the "default" case.

> What do you think about a udev rule set that creates /dev/disk/coreos/<UUID> that handles the device heirchy? Then the change would be root=/dev/disk/coreos/<UUID>.

Not sure I follow; isn't that just "move logic from systemd unit into udev"?

**Comment by darkmuggle** [comment]
>> What do you think about a udev rule set that creates /dev/disk/coreos/ that handles the device heirchy? Then the change would be root=/dev/disk/coreos/.

> Not sure I follow; isn't that just "move logic from systemd unit into udev"?

The idea here is that we create a udev rule based on the device attributes that fill the gap that traditional Udev rules miss. For example, udev does not create by `by-{label,uuid}` devices for Raid, Multipath and LVM devices, so our custom rule would create the symlink to our own `/dev/disk/coreos` location. Relying on the `uuid` side-steps the problem of `by-label` but doesn't solve the problem of the pathing.

While I think that the CoreOS installer is really awesome (it is) that's a one-time thing. Having the logic for finding root regardless of the installer is an area where can make it easier to scale from individual to making RHCOS and FCOS to multi-node clusters. Having the installer understand WWID, or LVM (ugh) just moves the work to the installer. 

My thinking is that we use both  `systemd` unit and a `udev` rule together. Going back to MPIO devices, udev sets a couple of attributes that we could use:
````
:/root# udevadm info /dev/sda | grep DM
E: DM_MULTIPATH_DEVICE_PATH=1
```

And then :
```
:/root# udevadm info /dev/mapper/mpatha | grep DM
E: DM_ACTIVATION=1
```

Our udev rule for creating `/dev/disk/coreos` would then look like: 
```
ACTION=="remove", GOTO="coresos_end"                                                                                                                                                                                    
SUBSYSTEM!="block", GOTO="coreos_end"

ENV{DM_SUSPENDED}!="Active", GOTO="coreos_end"
ENV{DM_MULTIPATH_DEVICE_PATH}==1, GOTO="coreos_end"
ENV{DM_ACTIVATION}==0, GOTO="coreos_end

ENV{ID_FS_USAGE}=="filesystem",  \
             ENV{ID_FS_UUID}=="?*",  \
             SYMLINK+="disk/coreos/$env{ID_FS_UUID}"

LABEL="coreos_end"
```
(caveat emptor: not tested, YMMV)

In this case, we use udev to find the device and set up the persistent naming for us. Finally, tieing the proposed idea back my suggestion and  _after_ setting the unique filesystem UUID on second boot we'd use `root=/dev/disk/coreos/<UUID>`.

**Comment by darkmuggle** [comment]
I guess the real reason I'm pushing for a udev rule is that using uuid or WWID's makes the problem a bit harder. Nevermind that a bunch of code _relies_ on `by-label` existing (ala `Ignition`, `Ingition Dracut` and CoreOS itself. 

To whit:
```
[    4.529462] ignition-setup-user[685]: mount: /mnt/boot_partition: /dev/sdb1 already mounted or mount point busy.
[    4.533050] systemd[1]: ignition-setup-user.service: Main process exited, code=exited, status=32/n/a
[    4.536314] systemd[1]: ignition-setup-user.service: Failed with result 'exit-code'.
[FAILED] Failed to start Ignition (setup user config).
```
Hint: its not mounted in this case, just _locked_.

Changing the code to understand `/dev/disk/coreos...` give CoreOS the ability to manage the device links.

**Comment by cgwalters** [comment]
> In this case, we use udev to find the device and set up the persistent naming for us.

I don't understand this - what does the udev rule use as a source of truth?

Are you disagreeing with using kernel arguments, or agreeing but think we should use udev to implement it?

**Comment by cgwalters** [comment]
> Nevermind that a bunch of code relies on by-label existing (ala Ignition, Ignition Dracut and CoreOS itself.

I'm not proposing removing the labels to start.  But, broadly speaking, using uuids or something else is about *subsequent* boots; a lot of what uses labels today is the ignition boot.

**Comment by darkmuggle** [comment]
> > In this case, we use udev to find the device and set up the persistent naming for us.
> 
> I don't understand this - what does the udev rule use as a source of truth?
> 
> Are you disagreeing with using kernel arguments, or agreeing but think we should use udev to implement it?

I'm clearly failing at expressing myself these days...

I'm agreeing, but stating that we need a udev rule to help implement it. Or put another way, setting uuid's only gets us part of the way there. We need something else to help and I'm proposing we use UDEV to get there.

**Comment by darkmuggle** [comment]
> > Nevermind that a bunch of code relies on by-label existing (ala Ignition, Ignition Dracut and CoreOS itself.
> 
> I'm not proposing removing the labels to start. But, broadly speaking, using uuids or something else is about _subsequent_ boots; a lot of what uses labels today is the ignition boot.

That makes sense, and I'm :+1: on it as first steps.

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/fedora-coreos-config/pull/354

**Comment by jlebon** [comment]
See related discussions in https://github.com/coreos/ignition-dracut/pull/183.

**Comment by martinezjavier** [comment]
> However, one other thing we could do in addition - if we can figure out how - is to somehow determine from the bootloader which disk it found `/boot` (and the kernel/initramfs), and by default find the rootfs on that disk. In complex root scenarios we'd want to break that "lock", but it would add even more robustness in the !reprovisioned case.
>

The bootloader determines from what disk and partition to load the kernel/initrd by using the `$root` variable. In the FCOS `grub.cfg` file, this variable is set by searching the partition that has the `boot` label using grub's [search](https://www.gnu.org/software/grub/manual/grub/html_node/search.html#search) command.

```
search --label boot --set boot
set root=$boot
```
The value set in that `$root` variable is what ends in the `BOOT_IMAGE=` kernel cmdline parameter. How the bootloader maps the disks / partitions and the syntax used is documented in the grub manual [here](https://www.gnu.org/software/grub/manual/grub/html_node/Device-map.html) and [here](https://www.gnu.org/software/grub/manual/grub/grub.html#Device-syntax) respectively.
 
> It looks like grub for example injects `BOOT_IMAGE=(hd0,gpt1)/ostree/fedora-coreos-2b43aa9994cbeaaf271dd1e873c6d563178d383c4996d1db32d0981af0ba4f53/vmlinuz-5.5.15-200.fc31.x86_64 ` but would need to dig in on if/how `hd0,gpt1` can be reliably translated into the same thing that the Linux kernel sees.

The [grub2-probe](https://www.gnu.org/software/grub/manual/grub/html_node/Invoking-grub_002dprobe.html) user-space tool can be used to get the (disk,partition) tuple or filesystem UUID to be used as a hint to set the `$root` variable. And that's what `grub2-mkconfig` calls to get the hint for the search` command then generating a grub config file.

So that tool could also be used to map what was injected in `BOOT_IMAGE=` with a linux block device. Something like the following should work (I think that even for complex / mapped device case):

```
for dev in $(lsblk -lnp -o NAME)
do
    bios="mbr"
    [ -d /sys/firmware/efi/efivars/ ] && bios="efi"
    
    hint="$(grub2-probe --target=${bios}_hints -d "$dev")"
    cmdline_hint="$(grep -oE "BOOT_IMAGE=\([a-z0-9]*[,][a-z0-9]*\)" /proc/cmdline | sed -E 's/BOOT_IMAGE=//' | tr -d '()')"

    if [ ${hint} = ${cmdline_hint} ]; then
        disk="$(lsblk -spnlo name "$dev" | tail -n1)"
        echo "kernel was booted from ${disk}"
    fi
done
```
But I'm not sure how reliable that would be, since it would depend on the order in which grub and the kernel probed the different storage drivers. I guess in most cases the order will always be the same (i.e: a USB stick will be probed after a SATA disk, etc) but still that won't be completely deterministic so I don't know if is something that can be relied upon.

That's why by default `grub2-mkconfig` uses UUIDs unless `GRUB_DISABLE_LINUX_UUID=true` is set in `/etc/default/grub`.

**Comment by cgwalters** [comment]
Oh right, I'd completely missed that our default GRUB config is using the label.   So if we switch to using UUIDs we'd also need to edit that.

**Comment by jlebon** [comment]
> switch to root=<uuid> post-firstboot?

This is done in https://github.com/coreos/fedora-coreos-config/pull/503.
