### ISSUE TITLE
OKD 4.4 Baremetal UPI Install: FCOS does not persist its hostname after reboot

### ISSUE THREAD

**Issue by cgruver** [coreos/fedora-coreos-tracker#466]
I opened this in https://github.com/openshift/okd for visibility to folks working on OKD 4.4

https://github.com/openshift/okd/issues/153

OKD version: 4.4.0-0.okd-2020-04-07-175212
OS Version: Fedora CoreOS 31.20200406.20.0

Cluster installed as Baremetal UPI

FCOS installed with iPXE and fixed IP using kernel params:

`ip=10.11.11.71::10.11.11.1:255.255.255.0:okd4-worker-1.my.domain.org:eth0:none`

The cluster installed and ran just fine.

I shutdown the cluster for transport of the lab machines:

1. Cordon the workers:
    `for i in 0 1 2 ; do oc adm cordon okd4-worker-${I}.my.domain.org ; done`
    `for i in 0 1 2 ; do oc adm drain okd4-worker-${I}.my.domain.org --ignore-daemonsets --force --grace-period=60 --delete-local-data; done`
1. Shutdown the workers
1. Shutdown the masters

When the master nodes were restarted.  They all came up with their hostname set to `localhost`.  They were obviously unable to join the cluster since etcd did not know them.

I was able to recover the cluster by correcting the hostname on each master and worker node:

    for i in 0 1 2 ; do ssh core@okd4-master-${I}.my.domain.org "sudo hostnamectl set-hostname okd4-master-${I}.my.domain.org && sudo shutdown -r now"; done
    for i in 0 1 2 ; do ssh core@okd4-worker-${I}.my.domain.org "sudo hostnamectl set-hostname okd4-worker-${I}.my.domain.org && sudo shutdown -r now"; done

**Comment by dustymabe** [comment]
Proposed fix in: https://github.com/coreos/ignition-dracut/pull/174

**Comment by dustymabe** [comment]
/retest

bump CI because github is being unreliable

**Comment by dustymabe** [comment]
The fix for this landed upstream. It needs a pull+rebuild of the ignition rpm ([open PR](https://src.fedoraproject.org/rpms/ignition/pull-request/56)).  It is now pending a testing stream release.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `31.20200505.2.0`.  Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `31.20200505.3.0`.

**Comment by cgruver** [comment]
I verified this with a new OKD 4.4 build.

Thanks!
