### ISSUE TITLE
How to update a ignition file on a running system?

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fedora-coreos-tracker#470]
I have a FCOS installed with a specific Ignition file. I make some changes.  When a auto update happens, the changes are lost.  Now, how I can I update the ignition file so that I can finalize my changes so that they can be carried forward on updates?

Thanks!

**Comment by Terkwood** [comment]
The ignition file is meant to be immutable

https://docs.fedoraproject.org/en-US/fedora-coreos/producing-ign/

**Comment by jamescassell** [comment]
Could be helpful if you describe what changes you're making that are being lost upon update.

**Comment by shivarammysore** [comment]
https://github.com/coreos/fedora-coreos-tracker/issues/456

**Comment by dustymabe** [comment]
Ignition is only ran once on boot. It will never run again. You have to re-provision your machine and provide an updated Ignition config if you'd like to try something different. It would help if you added more details in #456 so we can try to help. There aren't enough details there.

**Comment by shivarammysore** [comment]
Thanks @dustymabe - I will try to re-provision the machine.  I guess that means call `coreos-installer` with an updated `ignition` file.

**Comment by dustymabe** [comment]
@shivarammysore - can you try to reproduce and add more details here?

**Comment by dustymabe** [comment]
I'm going to close this. Please re-open if the problem persists and you have more details.

**Comment by shivarammysore** [comment]
To complete this issue, it does not work:
```
sudo coreos-installer install --ignition-file /home/core/my.ign 
error: The following required arguments were not provided:
    <device>

USAGE:
    coreos-installer install <device> --architecture <name> --ignition-file <path> --stream <name>

$ sudo coreos-installer install /dev/sda --architecture x86_64 --ignition-file /home/core/my.ign 
Downloading stable image and signature
Error: checking for exclusive access to /dev/sda
Caused by: couldn't reread partition table: device is in use
Caused by: EBUSY: Device or resource busy
```

**Comment by bgilbert** [comment]
```
Error: checking for exclusive access to /dev/sda
Caused by: couldn't reread partition table: device is in use
```
It seems you're trying to install onto a disk with mounted partitions.  Are you booted from `/dev/sda`?  You can't install onto the drive you've booted from.
