### ISSUE TITLE
GCP documentation page in Fedora CoreOS docs

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#475]
Now that we are uploading images to GCP we need to add a documentation page dedicated to GCP in our FCOS docs (smilar to [the one we have for Azure](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-azure/)). 

Rough notes to get started:

```
gcloud auth activate-service-account --key-file=/root/creds-gcp.json
gcloud compute images describe-from-family --project fedora-coreos-cloud fedora-coreos-stable
gcloud compute instances create node1 --project fedora-coreos-testing --zone us-east1-b --image-project fedora-coreos-cloud --image-family fedora-coreos-stable --metadata-from-file=user-data=/root/user-systemd.ign
```

**Comment by dustymabe** [comment]
Thanks @lucab for volunteering to make this docs page for us.

**Comment by lucab** [comment]
Docs PR at https://github.com/coreos/fedora-coreos-docs/pull/70.
Any native-speaking proofreader is welcome!
