### ISSUE TITLE
Include clevis 

### ISSUE THREAD

**Issue by sghosh151** [coreos/fedora-coreos-tracker#477]
Include clevis to support automated disk encryption
Related: https://github.com/coreos/ignition/issues/577

**Comment by rugk** [comment]
Maybe interesting: [Another post](https://blog.dowhile0.org/2017/10/18/automatic-luks-volumes-unlocking-using-a-tpm2-chip/) on how to use that with TPM2 unlocking.

**Comment by dustymabe** [comment]
This seems to be resolved by the recent work we did to support LUKs on the root device

https://github.com/coreos/fedora-coreos-config/pull/609

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `32.20200923.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20200923.3.0`.
