### ISSUE TITLE
Support for Digital Ocean

### ISSUE THREAD

**Issue by zomilanovic** [coreos/fedora-coreos-tracker#482]
Hi,

since our company is currently relying heavily on CoreOS Container Linux on Digital Ocean and the EOL will come next week, I wanted to know what will happen further on, will the successor Fedora CoreOS be supported on Digital Ocean in time too?
I'm asking this because I couldn't find anything about Digital Ocean, only other hosting providers, like AWS, Azure or similar in the currently available docs.

Warm regards,
Zoran from Ganescha Labs

**Comment by lucab** [comment]
Hi @zomilanovic, have you seen https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-digitalocean/?
Unrelated, we also have a [discussion forum](https://discussion.fedoraproject.org/c/server/coreos) for usage questions.

**Comment by zomilanovic** [comment]
Hi @lucab, no I haven't seen https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-digitalocean/ yet, but it seems like exactly what I needed, thanks.
