### ISSUE TITLE
coreos-installer-service fails when coreos.inst.install_dev is set to a path below /dev/disk

### ISSUE THREAD

**Issue by elemental-lf** [coreos/fedora-coreos-tracker#485]
# Bug #

The `coreos-installer-service` fails when the installation disk is specified by using a path under `/dev/disk` (like `/dev/disk/by-path/pci-0000:5c:00.0-scsi-0:1:0:0`). It works when using a direct reference to a device directly under `/dev` (like `/dev/sdi`). The problem isn't with `coreos-installer` but occurs after it completes.

## Version Information ##

Fedora CoreOS 31 (2247.6.0)

* `fedora-coreos-31.20200407.3.0-live-kernel-x86_64`
* `fedora-coreos-31.20200407.3.0-live-initramfs.x86_64.img`
* `fedora-coreos-31.20200407.3.0-metal.x86_64.raw.xz`

## Expected Behavior ##

The installation should complete without error.

## Actual Behavior ##

The installation fails because it is trying to mount a wrongly constructed device path (`/dev/disk/by-path/sdi1`):

```
         Starting CoreOS Installer...
[  311.244897] audit: type=1131 audit(1589824254.991:88): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[  311.321800]  sdi: sdi1 sdi2 sdi3 sdi4 sdi6 sdi7 sdi9
[  278.746972] coreos-installer-service[1651]: coreos-installer install /dev/disk/by-path/pci-0000:5c:00.0-scsi-0:1:0:0 --ignition /tmp/coreos-installer-xwQhBX --firstboot-args rd.neednet=1 ip=dhcp  --image-url http://<redacted>:8080/assets/fedora-coreos/fedora-coreos-31.20200407.3.0-metal.x86_64.raw.xz
[  279.397191] coreos-installer-service[1651]: Downloading image from http://<redacted>:8080/assets/fedora-coreos/fedora-coreos-31.20200407.3.0-metal.x86_64.raw.xz
[  279.592944] coreos-installer-service[1651]: Downloading signature from http://<redacted>:8080/assets/fedora-coreos/fedora-coreos-31.20200407.3.0-metal.x86_64.raw.xz.sig
[  280.130234] coreos-installer-service[1651]: Read disk 29.8 MiB/461.6 MiB (6%)
[...]
[  348.480915] coreos-installer-service[1651]: Read disk 461.6 MiB/461.6 MiB (100%)
[  349.009502] coreos-installer-service[1651]: gpg: Signature made Tue Apr 21 21:20:22 2020 UTC
[  349.111943] coreos-installer-service[1651]: gpg:                using RSA key 50CB390B3C3359C4
[  349.217948] coreos-installer-service[1651]: gpg: Good signature from "Fedora (31) <fedora-31-primary@fedoraproject.org>" [ultimate]
[  349.362954] coreos-installer-service[1651]: R[  381.930730] GPT:Primary header thinks Alt. header is not at the end of the disk.
ead disk 461.6 M[  382.022701] GPT:5593087 != 781357231
iB/461.6 MiB (10[  382.082456] GPT:Alternate GPT header not at the end of the disk.
0%)
[  382.171585] GPT:5593087 != 781357231
[  382.219858] GPT: Use GNU Parted to correct GPT errors.
[  382.282984]  sdi: sdi1 sdi2 sdi3 sdi4
[  350.033832] coreos-installer-service[1651]: Error: mounting device /dev/disk/by-path/sdi1 on /tmp/coreos-installer-1lpvQG
[  350.167959] coreos-installer-service[1651]: Caused by: ENOENT: No such file or directory
[FAILED] Failed to start CoreOS Installer.
See 'systemctl status coreos-installer.service' for details.
[  350.265956] coreos-installer-service[1651]: Clearing partition table
[DEPEND] Dependency failed for CoreOS Installer Target.
[  350.483057] c[  383.097313] audit: type=1130 audit(1589824326.843:89): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=coreos-installer comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
oreos-installer-service[1651]: Error: install failed
```

## Other Information ##

We're migrating from Container Linux to FCOS and this path specification has worked with the CL installer. Unfortunately the logical RAID-1 volume on these HP servers which is used as the system disk is enumerated last by the Linux kernel and so any changes of the storage configuration lead to a shift of this device name. So simply specifying `/dev/sdi`  instead of `/dev/disk/by-path/pci-0000:5c:00.0-scsi-0:1:0:0` is not an option as it might lead to a destruction of a data disk when the `coreos-installer-service` installs an OS on it.

**Comment by elemental-lf** [comment]
I've just now seen that `coreos-installer-service` is part of `coreos-installer` (https://github.com/coreos/coreos-installer/blob/master/systemd/coreos-installer-service). Is that the version used by FCOS? So should I open the issue there?

**Comment by elemental-lf** [comment]
Yeah, this definitely belongs there. Sorry for the noise.

**Comment by dustymabe** [comment]
@elemental-lf no problem - you can feel free to open issues here (they get more visibility). If we deem it necessary they be moved to another project we have the power to do that.

Feel free to re-open this bug.

**Comment by dustymabe** [comment]
bug in coreos-installer repo: https://github.com/coreos/coreos-installer/issues/242

**Comment by dustymabe** [comment]
As noted over in https://github.com/coreos/coreos-installer/issues/242#issuecomment-631476620 we believe this is fixed by https://github.com/coreos/coreos-installer/pull/215, which is in coreos-installer 0.2.0. 

The fix for this went into stable stream release `31.20200505.3.0`.

**Comment by elemental-lf** [comment]
@dustymabe thank you for this bit of information. I will try the new release!

**Comment by dustymabe** [comment]
Thanks @elemental-lf - please do let us know if it is fixed for you.

**Comment by elemental-lf** [comment]
@dustymabe the problem is fixed for me. Thanks again.
