### ISSUE TITLE
GCP: increase image size to 10G 

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#492]
The GCP has shared anecdotal advice with us that image sizes <10G can suffer performance issues. We need to develop a way to get the images we create for GCP at least 10G. This would include a change to COSA and possibly a chance to the configs to specify an image size per platform.

**Comment by jlebon** [comment]
Do you have more details on this? What kind of performance issues?

**Comment by zmarano** [comment]
I wish I had more details but it is anecdotal evidence from an old study on persistent disk performance. Our recommendation is that images are at least 10GB in size.

**Comment by pierre-emmanuelJ** [comment]
This request can be also useful for Exoscale image. 
Because to register a custom Template(image) (or official one in internal) we accept only qcow2 file with minimum virtual size of 10G.

>This would include a change to COSA and possibly a chance to the configs to specify an image size per platform. 

Yes I think we can do something generic to let providers choose the size of the image,

**Comment by dustymabe** [comment]
Looks like this is resolved now that we've [increased our disk size to 10G across the board](https://github.com/coreos/fedora-coreos-config/pull/888). With the latest stable (`33.20210314.3.0`):

```
[core@fcos-node01 ~]$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   10G  0 disk 
├─sda1   8:1    0    1M  0 part 
├─sda2   8:2    0  127M  0 part 
├─sda3   8:3    0  384M  0 part /boot
└─sda4   8:4    0  9.5G  0 part /sysroot
[core@fcos-node01 ~]$ sudo systemctl start afterburn.service
[core@fcos-node01 ~]$ 
[core@fcos-node01 ~]$ cat /run/metadata/afterburn
AFTERBURN_GCP_HOSTNAME=fcos-node01.us-east1-b.c.dusty-test-april-12.internal
AFTERBURN_GCP_IP_LOCAL_0=10.142.0.2
AFTERBURN_GCP_MACHINE_TYPE=projects/655567497558/machineTypes/n1-standard-1
AFTERBURN_GCP_IP_EXTERNAL_0=35.227.92.91
```

**Comment by pierre-emmanuelJ** [comment]
Awesome, thanks!
