### ISSUE TITLE
It's hard to find and download testing/next composes

### ISSUE THREAD

**Issue by kparal** [coreos/fedora-coreos-tracker#493]
As a common Joe, I opened https://getfedora.org and wanted to download FCOS. The big `Download Now` button brings me to:
https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable
There, I have a colorful representation of 3 major streams - `stable`, `testing` and `next`. I decided I want to download `next`. So I clicked the obvious big orange button `View Next Releases` under the `Next` column. Which brought me to:
https://getfedora.org/en/coreos?stream=next
Now I got confused, because I couldn't identify anything downloadable. I could see the release timestamps, but no download link. Then I realized it must be the big red `Download Now` button at the top right. So I clicked on it and arrived again on:
https://getfedora.org/en/coreos/download?tab=cloud_launchable&stream=stable
But I was here already! I went through this cycle of pages several times, and almost thought your web links were broken. Several minutes later, I finally spotted the small, shy, almost invisible stream picker right under those big colorful columns:
![fcos](https://user-images.githubusercontent.com/755451/82688838-d6eb7900-9c59-11ea-9a52-3cdcbc270d9f.png)

I believe this is really close to invisible for newcomers to your download pages. If you want better experience for your users, please work with the websites team to make this much more obvious.

I suggest the picker should be removed completely, and those colorful buttons in each column should be called `Download now`. Upon clicking, they would display the right content in the tabs below, and scroll down to them, so that it's obvious that this is the content you want. The `View All Streams` button should be renamed to `View release notes` or `View changelog`, it can be repositioned if necessary, and it will lead to the `Release notes` page. You don't need 3 more additional buttons to see the release notes, because the tabs are pretty obvious on that page, just a single button is completely sufficient.

What do you think?

**Comment by jlebon** [comment]
Thanks for the excellent feedback!

> I suggest the picker should be removed completely, and those colorful buttons in each column should be called `Download now`.

Or maybe we just remove the button entirely and make the whole area the stream picker? I like the idea of making it scroll down for you too.

And then a single "View release notes" underneath the stream pickers which links to the specific release notes for the currently selected stream?

**Comment by zonggen** [comment]
@kparal Thank you for the feedback!

Yes, I do agree the functionality of the three buttons are overlapped and somewhat redundant. The original intention for linking to the release notes is for users who went to download page directly and adding links to releases notes might be helpful. This is a new major styling rework for the website and will also followup with improvements like you suggested :)

Like @jlebon 's comment above, it's better to:
1. remove the picker and allow clicking on renamed button / the whole stream tab to scroll down to the download section with correct stream selected.
2. Rename the top "View All Streams" to "View Release Notes", and make it link to the release notes.

**Comment by cgwalters** [comment]
Agree, thanks for filing this!  I also found it confusing.

**Comment by zonggen** [comment]
Update:

Filed https://pagure.io/fedora-web/websites/pull-request/117 and the implementation now uses `View Release Notes` and three `Download Now` buttons that act as a selector for download streams.

**Comment by kparal** [comment]
As an alternative, `Download Now` could be also named `Show Downloads` (and it would scroll you there), which might be even more intuitive.

**Comment by zonggen** [comment]
Yes I agree with the idea of `Show Downloads`, also @lucab proposed changing `Show Release Notes` -> `View Releases` and change it back after we have a proper and detailed release notes.
And added a line indicating the selected stream with corresponding stream color.

Screenshot demo is: https://pagure.io/fedora-web/websites/pull-request/117#comment-121447

**Comment by dustymabe** [comment]
Feedback incorporated into https://pagure.io/fedora-web/websites/pull-request/117

Thanks @kparal - all!
