### ISSUE TITLE
Add rawhide stream

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#497]
We should add a mechanical stream to track rawhide. This'll give us some heads up on the major changes that might affect us.

Right now, for example, it looks like rpm-ostree might break on the [rpmdb sqlite change](https://fedoraproject.org/wiki/Changes/Sqlite_Rpmdb):

https://bugzilla.redhat.com/show_bug.cgi?id=1838691

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/793
https://github.com/coreos/fedora-coreos-pipeline/pull/302
https://github.com/coreos/fedora-coreos-releng-automation/pull/127

**Comment by lucab** [comment]
> We should add a mechanical stream to track rawhide.

Just to double-check, this means we are going to set Zincati there with `updates.enabled = false` and Cincinnati is not going to know about this stream, right?

**Comment by jlebon** [comment]
> > We should add a mechanical stream to track rawhide.
> 
> Just to double-check, this means we are going to set Zincati there with `updates.enabled = false` and Cincinnati is not going to know about this stream, right?

Yup, exactly! The upgrade tests in kola at least will still exercise Zincati.

**Comment by jlebon** [comment]
This is done now!

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/XPYEN7VTK26E5NHEI7YUXMJRK5LNGRXY/

**Comment by dustymabe** [comment]
Just adding a note here.. Added a license to GCP for the rawhide stream:

```
./license.sh create fedora-coreos-cloud "fedora-coreos-rawhide" "Fedora CoreOS Rawhide"
Creating license ID for fedora-coreos-rawhide with description Fedora CoreOS Rawhide
{
  "id": "7556520113214168076",
  "name": "operation-1620320995091-5c1ac6155a3dd-c0a55b2b-cc1f4776",
  "operationType": "compute.licenses.insert",
  "targetLink": "https://www.googleapis.com/compute/v1/projects/fedora-coreos-cloud/global/licenses/fedora-coreos-rawhide",
  "targetId": "5967584498063875084",
  "status": "DONE",
  "user": "dustymabe@fedora-coreos-cloud.iam.gserviceaccount.com",
  "progress": 100,
  "insertTime": "2021-05-06T10:09:55.460-07:00",
  "startTime": "2021-05-06T10:09:55.460-07:00",
  "endTime": "2021-05-06T10:09:55.460-07:00",
  "selfLink": "https://www.googleapis.com/compute/v1/projects/fedora-coreos-cloud/global/operations/operation-1620320995091-5c1ac6155a3dd-c0a55b2b-cc1f4776",
  "kind": "compute#operation"
}
```
