### ISSUE TITLE
PXE boot fails into emergency shell

### ISSUE THREAD

**Issue by Himansh-ilink** [coreos/fedora-coreos-tracker#498]
Hello !
I am trying to install fedora coreos using PXE method on hp bare metal server.
My default pxe configuration is below.
```
DEFAULT pxeboot                                                                                                                
TIMEOUT 20                                                                                                                     
PROMPT 0                                                                                                                       
LABEL pxeboot                                                                                                                  
    KERNEL vmlinuz                                                                                                             
    APPEND initrd=initramfs.img console=tty0 console=ttyS0 coreos.autologin=ttyS0  coreos.inst.install_dev=/dev/sda coreos.inst
.stream=stable coreos.inst.ignition_url=http://192.168.31.176/example.ign                                                      
IPAPPEND 2
```
My ignition file content is below:
```json
{                                                                                                                              
  "ignition": {                                                                                                                
    "config": {                                                                                                                
      "replace": {                                                                                                             
        "source": null,                                                                                                        
        "verification": {}                                                                                                     
      }                                                                                                                        
    },                                                                                                                         
    "security": {                                                                                                              
      "tls": {}                                                                                                                
    },                                                                                                                         
    "timeouts": {},                                                                                                            
    "version": "3.0.0"                                                                                                         
  },                                                                                                                           
  "passwd": {                                                                                                                  
    "users": [                                                                                                                 
      {                                                                                                                        
        "name": "core",                                                                                                        
        "sshAuthorizedKeys": [                                                                                                 
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUqmr"                                                                                                                    
        ]                                                                                                                      
      }                                                                                                                        
    ]                                                                                                                          
  },                                                                                                                           
  "storage": {},                                                                                                               
  "systemd": {}
```

When I am trying to install fedora coreos using above pxe config, os stucked in maintainence mode.

![fedora-error](https://user-images.githubusercontent.com/62114274/82919460-b1c97400-9f93-11ea-92e8-8955c13f6d39.PNG)

Can someone please help me regarding this issue.

Thank you
Himanshu ved

**Comment by jlebon** [comment]
Are you streaming the console over iLO? Do you see any errors during the boot process or from Ignition?

Can you try again but without the `console=ttyS0 coreos.autologin=ttyS0` arguments and changing `console=tty0` to `console=tty1`? This should allow you to get a prompt. (Note that `coreos.autologin` isn't supporting in FCOS; instead we support `single`: https://github.com/coreos/fedora-coreos-tracker/issues/112).

**Comment by lucab** [comment]
@Himansh-ilink if you scroll back in that console, you should see what errors caused the boot to fail.
Additionally, after adjusting your parameters as suggested by @jlebon above, you should be able to get into the emergency console by pressing Enter, as prompted in your screenshot. Once there, you can check the logs via `journalctl` to get all relevant failure details.

**Comment by dustymabe** [comment]
hi @Himansh-ilink. Are you still having this problem? Can you provide us any more details?

**Comment by kbaegis** [comment]
I have also been struggling with validating that the ignition templates are being read appropriately. 

Seeing as how coreos users are being punished with the https://github.com/coreos/fedora-coreos-tracker/issues/112 WONTFIX I'm not sure of the best way to proceed.

**Comment by dustymabe** [comment]
> I have also been struggling with validating that the ignition templates are being read appropriately.

We recently added some output on the console of the machine that indicates if an Ignition config was read and applied or not. For example, see https://github.com/coreos/fedora-coreos-config/pull/344#issuecomment-632924952 . I don't think this has hit `stable` yet, but it's in `testing`. 

> Seeing as how coreos users are being punished with the #112 WONTFIX I'm not sure of the best way to proceed.

It's not the same, but we did add some documentation for recovering a system https://docs.fedoraproject.org/en-US/fedora-coreos/access-recovery/, which should help some people in this situation.

**Comment by kbaegis** [comment]
I got it into a functional state; templates are now being read and are no longer failing (I was hitting https://github.com/coreos/fedora-coreos-tracker/issues/496 and rolled back to the 4/20 commit). 

Is there no ability to get packages injected with rpm-ostree via ignition?

**Comment by jlebon** [comment]
> (I was hitting #496 and rolled back to the 4/20 commit).

FWIW that bug should be fixed in the latest install media.

> Is there no ability to get packages injected with rpm-ostree via ignition?

Freely layering packages in general is not recommended, though we're working on an extension system which uses layering for a subset of known tested packages (see https://github.com/coreos/fedora-coreos-tracker/issues/401). Support for it on PXE is also on the radar (see https://github.com/coreos/fedora-coreos-tracker/issues/401#issuecomment-634279049).

**Comment by dustymabe** [comment]
Hi @Himansh-ilink - i'm going to close this issue. If you're still having a problem in the future you can re-open this issue with more details or open a new issue. Thanks!
