### ISSUE TITLE
Cannot SSH into VM after ignition updates core user

### ISSUE THREAD

**Issue by matteoiacovitti** [coreos/fedora-coreos-tracker#499]
# Bug #
# Bug Report #
I am using a tool called packer to create a VM inside vCenter using Fedora CoreOS.
I created an ignition file that has the core user and an ssh key but after the ignition step on bootup, I cannot log in using my pen key

Here is the passed of my ignition file

```
{
  "ignition": {
    "config": {
      "replace": {
        "source": null,
        "verification": {}
      }
    },
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "3.0.0"
  },
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa AAAA[...]tS7lXpQ47f Dev Master"
        ]
      }
    ]
  }
}
```
The public key I'm using was verified using `ssh-keygen -y -e -f key.pem`and both the pub and pri keys match. 

Are there may issues with `sshAuthorizedKeys`? The documentation is very minimal so I'm not sure if I'm missing anything other details

Also, How can you check if the `.ssh/authorized_keys` was updated by the ignition file?
## Operating System Version ##
FCOS 31.20200505.3.0
## Ignition Version ##
3.0.0
## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?
vCenter via Packer (vSphere-iso)
## Expected Behavior ##
Login via SSH
## Actual Behavior ##
I get this error when the packer crashes

`--> vsphere-iso: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

## Reproduction Steps ##

  1. ...
  2. ...

**Comment by lucab** [comment]
> I am using a tool called packer to create a VM inside vCenter using Fedora CoreOS.

This sounds a lot like https://www.packer.io/. If that is the case, it is possible that the tool is booting the machine once and then snapshotting it. The Ignition configuration is only applied to the first boot ever of the machine/image.

It would be helpful to know which image/format you are starting from, how you are passing the Ignition configuration to it, and how you are SSHing to it (is this using the `core` user?).

> Also, How can you check if the .ssh/authorized_keys was updated by the ignition file?

Your SSH pubkeys would be stored in `/home/<USER>/.ssh/authorized_keys.d/ignition`. That file is referenced from `/etc/ssh/sshd_config`. You can check this by booting in [recovery mode](https://docs.fedoraproject.org/en-US/fedora-coreos/access-recovery/). You may need to adjust the [serial console](https://docs.fedoraproject.org/en-US/fedora-coreos/emergency-shell/) to match your environment, though.

**Comment by matteoiacovitti** [comment]
Yes this is Packer.io and I have verified that it is not snapshotting the VM during the deployment

I have updated the ISO version I am using in the description. 
I am passing the ignition file using the coreos-installer command (coreos-installer install /dev/sda -i ignition.json) 

I am SSHing using a remote PC using a private key pem file. The public key is added via the ignition file using passwd.  

I have verified the keys work using `ssh-keygen` and I can ssh to another VM that was using CoreOS CL with the same pub and pri keys

I'll try the recovery mode and see if its getting added

**Comment by matteoiacovitti** [comment]
I'm adding single to the grub menu according to https://docs.fedoraproject.org/en-US/fedora-coreos/access-recovery/ doc but it's not booting into single. It crashes here

![image](https://user-images.githubusercontent.com/25353683/83042184-59d05300-a00f-11ea-91f7-c347423ed13d.png)

**Comment by lucab** [comment]
@matteoiacovitti I think you may have an emergency prompt waiting for you on a different console. See https://docs.fedoraproject.org/en-US/fedora-coreos/emergency-shell/ to steer it toward the console you are actually in front og.

**Comment by matteoiacovitti** [comment]
Thanks @lucab I got into the console. I went to /home/core/.ssh/ and noticed there is just the authorized_keys.d folder with ignition file in there that has the pub key in it.

![image](https://user-images.githubusercontent.com/25353683/83046573-35777500-a015-11ea-8f99-52bff30d8a7f.png)

In CoreOS CL, after ignition, the key is added to a file in .ssh called `authorized_keys`
```
core@localhost ~ $ ls -la .ssh/
total 24
drwx------. 3 core core 4096 Apr 30 15:13 .
drwxr-xr-x. 6 core core 4096 May 14 18:42 ..
-rw-------. 1 core core  393 Apr 30 15:13 authorized_keys
drwx------. 2 core core 4096 Apr 30 15:13 authorized_keys.d
core@localhost ~ $ 
```

Is this what FCOS does now with the key? IT doesn't seem proper unless I'm missing a step in the ignition or missing an option somewhere?

**Comment by bgilbert** [comment]
@matteoiacovitti Yup, that's correct.  `sshd` is configured to read directly from the file in `authorized_keys.d`.

**Comment by matteoiacovitti** [comment]
@bgilbert Thank you for clarifying. Is there a way to place the key in another file, say .ssh/athorized_keys?

**Comment by lucab** [comment]
That setting is controlled by `/etc/ssh/sshd_config` (as stated in a previous comment), which currently contains:
```
# Read authorized_keys fragments written by Ignition and Afterburn
AuthorizedKeysFile .ssh/authorized_keys .ssh/authorized_keys.d/ignition .ssh/authorized_keys.d/afterburn
```

You can overwrite that configuration file via Ignition, but we'd recommend not to do that (as the defaults in there get updated over time by the package providing that file).

**Comment by matteoiacovitti** [comment]
Ahh. ok I found the problem.

It looks like in the previous CoreOS CL ignition file, the sshd_config was modified. When I migrated over, I didn't take into consideration that FCOS might have a different config.

I'll take a look at the config and add it to our custom file

**Comment by matteoiacovitti** [comment]
THanks @lucab

**Comment by matteoiacovitti** [comment]
@lucab YAY!! It worked. So it was my config of sshd that was the issue. 

I can ssh to the VM now. Thanks for all the help :D
