### ISSUE TITLE
should notifications from github issue tracker go to the mailing list?

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#5]
For the atomic working group we had pagure notifications go to the atomic@lists.fedoraproject.org mailing list. We also had the atomic-devel@projectatomic.io mailing list that these notifications did not go to. 

For Fedora CoreOS I think each person can subscribe to the issue tracker on github and we'll leave the mailing list alone.

Thoughts?

**Comment by glevand** [comment]
Subscribing to things of interest seems best to me. Otherwise you just get a bunch of noise.

**Comment by jasonbrooks** [comment]
+1 to a less noisy list

**Comment by ajeddeloh** [comment]
I'd prefer less noise. If we want this maybe an entirely seperate list people can opt in to.

**Comment by sayanchowdhury** [comment]
I agree with @dustymabe to leave the ML alone

**Comment by dustymabe** [comment]
From [today's meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/BGGRMVVU7KLKLSFXJRDURTQFMEEFEPSG/):

```
* AGREED: we will allow individuals to subscribe to the GH tracker and not send notifications to the mailing list (dustymabe, 16:52:34)
```
