### ISSUE TITLE
migrating FCOS openshift apps to new Fedora Infra cluster

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#501]
Fedora infra is undergoing a datacenter migration. They have asked us to move our apps over to the new cluster.

The following apps should get migrated:

- coreos-cincinnati
- coreos-koji-tagger
- coreos-ostree-importer
- fedora-ostree-pruner

Anything else?

<details>

```
As you all may or may not know, we are moving datacenters (in only a few
weeks now!). From phx2 to iad2.

We have the iad2 infrastructure largely setup now.

We have our prod openshift cluster there and working. 

Can you all in the next week or so:

* deploy your apps in the iad2 cluster too (should just be an ansible
change of your apps playbook to have:

  hosts: os_masters[0]:os_masters_stg[0]:os-master01.iad2.fedoraproject.org
 
* Do whatever testing you are able to before we migrate things on the
week of 2020-06-08. 

You can add a /etc/hosts file to hit the iad2 proxies for some testing: 

38.145.60.20    fedoraproject.org getfedora.org admin.fedoraproject.org apps.fedoraproject.org mirrors.fedoraproject.org os.fedoraproject.org console.app.os.fedoraproject.org app.os.fedoraproject.org id.fedoraproject.org qa.fedoraproject.org apps.fedoraproject.org koji.fedoraproject.org

* Let us know if there's any problems or if you need any special
instructions / care / timing the week of the move. 
```

</details>

**Comment by lucab** [comment]
I can take care of baby-sitting our Cincinnati backend.

**Comment by jlebon** [comment]
I can split the others with Dusty next week.

**Comment by lucab** [comment]
There were a bunch of hiccups in the cluster configuration (see https://pagure.io/fedora-infrastructure/issue/8979), but the Cincinnati backend is now active and confirmed working in both the old and the new datacenter. That part is ready for the switch.

**Comment by dustymabe** [comment]
👍 - i'll sync with the infra team and look at switching over the koji tagger sometime today

**Comment by dustymabe** [comment]
The following apps were migrated this week and the latest testing/next
releases were run on the new apps/infrastructure.

    * coreos-cincinnati (thanks @lucab)
    * coreos-koji-tagger
    * coreos-ostree-importer
    * fedora-ostree-pruner
