### ISSUE TITLE
How to disable Auto-Updates

### ISSUE THREAD

**Issue by matteoiacovitti** [coreos/fedora-coreos-tracker#502]
Not really a bug, but a question.
How do you disable auto-updates in the ignition file?

Is it like CoreOS CL where you need to mask the locksmith and update-engine or is it a different service?

```
      {
        "mask": true,
        "name": "update-engine.service"
      },
      {
        "mask": true,
        "name": "locksmithd.service"
      }
```

**Comment by lucab** [comment]
Thanks for the report. From the context I assume you are asking about Fedora CoreOS, so I moved the ticket to the bug tracker there. For general user-questions we do have a forum too: https://discussion.fedoraproject.org/c/server/coreos/5.

I'd recommend you to start reading the general docs about FCOS auto-updates at https://docs.fedoraproject.org/en-US/fedora-coreos/auto-updates/.

After getting comfortable with the general topic, Zincati docs have more details on each configuration knob.
Specifically for your question, see https://github.com/coreos/zincati/blob/v0.0.11/docs/usage/auto-updates.md. But please do not disable auto-updates unless there is really a strict need to.

As a last note, beware of https://github.com/coreos/fedora-coreos-tracker/issues/392.

**Comment by matteoiacovitti** [comment]
This worked. The Auto-updates have been disabled. Thanks :D
