### ISSUE TITLE
Provide a working podman open-vm-tools sample?

### ISSUE THREAD

**Issue by remoe** [coreos/fedora-coreos-tracker#503]
I try to run open-vm-tools with FCOS. It runs, but it does not reboot/shutdown the host system. I know about the https://github.com/coreos/fedora-coreos-tracker/issues/70 topic.

This command does not shutdown the host:

```govc vm.power -s -force <name>```

Docker file:

```dockerfile
FROM alpine:3.11

RUN apk update && \
    apk add open-vm-tools && \
    rm -rf /var/cache/apk/*

CMD ["/usr/bin/vmtoolsd"]
```

Service:

```
variant: fcos
version: 1.0.0 
systemd:
  units:
    - name: open-vm-tools.service
      enabled: true
      contents: |
        [Unit]
        Description=Open VM Tools
        After=network-online.target
        Wants=network-online.target

        [Service]
        Environment=REGISTRY_AUTH_FILE=<your host>/.docker/config.json
        TimeoutStartSec=0
        ExecStartPre=-/bin/podman kill open-vm-tools
        ExecStartPre=-/bin/podman rm open-vm-tools
        ExecStartPre=/bin/podman pull <your host>/openvmtools
        ExecStart=/bin/podman run -e SYSTEMD_IGNORE_CHROOT=1 -v  /proc/:/hostproc/ -v /sys/fs/cgroup:/sys/fs/cgroup \
          -v /run/systemd:/run/systemd --pid=host --net=host --ipc=host --uts=host --rm --privileged \
          --name open-vm-tools <your host>/openvmtools

        [Install]
        WantedBy=multi-user.target
```

Does anyone can help on this? And when yes, it would be great when we have a working sample in the docs, because agents will not be installed on vmware-ova.

UPDATE: I've tried ```debian:bullseye-slim``` as base image. It does not work as well.

Thanks

**Comment by lucab** [comment]
While I don't have a direct answer to this (a privileged container should do fine, but it depends on the specific image arrangement and software logic), you may want to have a look at https://github.com/vmware/govmomi/tree/master/toolbox too.

**Comment by dcode** [comment]
I've been able to get this to work and I can successfully send ACPI shutdown and at least get out the information that I need. My FCCT snippet and Dockerfile are in [this gist](https://gist.github.com/dcode/7e734ab3a519ee7ea913a8d8006c4ef0).

**Comment by remoe** [comment]
@dcode, thanks for sharing. But it need to crunch this to a minimum. For example fedora:31 does not need systemd ( https://gist.github.com/dcode/7e734ab3a519ee7ea913a8d8006c4ef0#file-dockerfile-L12 ). It is already installed. I'm not sure this https://gist.github.com/dcode/7e734ab3a519ee7ea913a8d8006c4ef0#file-fcct-snippet-vmtools-yml-L25 are all needed.

**Comment by remoe** [comment]
@dcode, I think it was the container. You use fedora:31. Here is a smaller sample that works:

Dockerfile:

```docker
FROM fedora:31

RUN dnf -y --setopt=tsflags=nodocs --setopt=override_install_langs=en_US.utf8 --setopt=install_weak_deps=False install file open-vm-tools net-tools iproute && \ 
dnf clean all

CMD /usr/bin/vmtoolsd
```

Service:

```
variant: fcos
version: 1.0.0 
systemd:
  units:
    - name: open-vm-tools.service
      enabled: true
      contents: |
        [Unit]
        Description=Open VM Tools
        After=network-online.target
        Wants=network-online.target
        ConditionVirtualization=vmware

        [Service]
        Environment=REGISTRY_AUTH_FILE=<your host path>/.docker/config.json
        TimeoutStartSec=0
        ExecStartPre=-/bin/podman kill open-vm-tools
        ExecStartPre=-/bin/podman rm open-vm-tools
        ExecStartPre=/bin/podman pull <your host>/openvmtools:v1
        ExecStart=/bin/podman run -e SYSTEMD_IGNORE_CHROOT=1 \
          --detach \
          -v /proc/:/hostproc/ \
          -v /sys/fs/cgroup:/sys/fs/cgroup \
          -v /run/systemd:/run/systemd \
          -v /var/lib/sss/pipes:/var/lib/sss/pipes \
          -v /etc/adjtime:/etc/adjtime \
          -v /etc/nsswitch.conf:/etc/nsswitch.conf:rw \
          -v /etc/sysconfig:/etc/sysconfig:rw \
          -v /etc/passwd:/etc/passwd \
          -v /etc/shadow:/etc/shadow \
          -v /etc/hosts:/etc/hosts:rw \
          -v /etc/hostname:/etc/hostname:rw \
          --pid=host \
          --net=host \
          --ipc=host \
          --uts=host \
          --rm --privileged \
          --name open-vm-tools <your host>/openvmtools:v1
        KillMode=none
        Type=forking
        [Install]
        WantedBy=multi-user.target
```

I'm pretty sure, this can be smaller :)

**Comment by dcode** [comment]
Awesome. So far I've been working on functional. I know things can be smaller and I need that too.

**Comment by dcode** [comment]
Awesome. So far I've been going for functional, but I do need things as small as possible too. I'll give that a go.

**Comment by remoe** [comment]
@dcode can you please report back if this sample works for you as well?

**Comment by arnegroskurth** [comment]
See: https://github.com/coreos/fedora-coreos-tracker/issues/70#issuecomment-1073751584
