### ISSUE TITLE
How do you install wget

### ISSUE THREAD

**Issue by matteoiacovitti** [coreos/fedora-coreos-tracker#504]
In my ignition file, I need to install 2 packages, docker-compose and confd.
In CoreOS CL I was able to wget these packages and install them via packer.io script.

But it seems wget is not installed on FCOS.

How do I install wget via ignition?

Thanks

**Comment by bgilbert** [comment]
`curl` is included in FCOS.  In general, if you'd like to run additional software, you should run it from a container, not on the host.

If you have the URL for the files you need, you can fetch them directly from the Ignition config using the `storage.files[].contents.source` field.

**Comment by matteoiacovitti** [comment]
Thank you @bgilbert I'll use curl for my script instead.

**Comment by djangit** [comment]
@dustymabe Thanks for the help. Can't check now as the download is blocked as the proxy is not configured. 
I found one thing though : i cannot specify multiple different path/storage keys. Say for ex i need to configure chrony, certificates which are in different paths...

**Comment by dustymabe** [comment]
> I found one thing though : i cannot specify multiple different path/storage keys. Say for ex i need to configure chrony, certificates which are in different paths...

I'm not sure I follow. Can you describe the problem more completely in a new issue?

**Comment by djangit** [comment]
Sure  i will. Thanks a lot.
