### ISSUE TITLE
tests: add CI test for live ISO/PXE scenario

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#515]
In #496 we identified a problem with setting an SSH key for the core user provided via Ignition config to our live ISO/PXE artifacts. Running workloads via our live artifacts is a valid use case and #496 represents breakage in that. Luckily #496 is now fixed but this [identified a gap](https://github.com/coreos/fedora-coreos-tracker/issues/496#issuecomment-633233190) in our CI.

Let's test providing Ignition configs to live artifacts during our CI runs. At a minimum this test should at least catch the regression that was introduced and documented in #496.

**Comment by cgwalters** [comment]
We already do this in `testiso`, we just weren't testing ssh keys.

I think the fix here is more to add `kola -p qemu-metal` - i.e. change `kola testiso` to `kola run -p qemu-pxe-metal basic` or so.

**Comment by dustymabe** [comment]
> We already do this in `testiso`, we just weren't testing ssh keys.

ahh that's great news! 

> I think the fix here is more to add kola -p qemu-metal - i.e. change kola testiso to kola run -p qemu-pxe-metal basic or so.

👍

I opened this ticket to track that there was more work to do from #496 other than just fixing the bug.

**Comment by cgwalters** [comment]
I think the simplest short term fix would be adding an Ignition config to generate a ssh key around this bit of code:
https://github.com/coreos/coreos-assembler/blob/b574572fe6b209f3c22f239364bc992305b4c046/mantle/cmd/kola/testiso.go#L423
