### ISSUE TITLE
fcos can not boot with inappropriate ioctl for device

### ISSUE THREAD

**Issue by majorinche** [coreos/fedora-coreos-tracker#516]
goal: install openshift/okd 4.4 with FCOS
infra: vmware vsphere 6.0
ocp release: 4.4.3-x86_64 
install method: pxe
install reference: https://docs.okd.io/latest/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html
FCOS version: fedora-coreos-31.20200505.3.0
ignition file generated by command: openshift-install create ignition-configs --dir=install_dir

description: install can be ok, but can not boot after reboot for bootstrap node, with error as following: 
_**emergency.service: inappropriate ioctl for device**_

debug steps:
1, analysis the bootstrap.ign file
[root@ip-172-31-8-20 ~]# podman run --rm -i quay.io/coreos/ignition-validate - < bootstrap.ign
error at $.storage.files.49, line 1 col 110199: duplicate entry defined
error at $.storage.files.50, line 1 col 112087: duplicate entry defined
warning at $.networkd, line 1 col 81: Unused key networkd
warning at $.storage.files.0.mode, line 1 col 1650: Unused key filesystem
warning at $.storage.files.1.mode, line 1 col 2102: Unused key filesystem

found duplicate entry, after deduplicate, only warning message left, then retry, still the same result
2, check ignition version
openshift-install create version is: 2.2.0
and ignition-validate is: 3.0.0
not sure if it is a problem

**Comment by lucab** [comment]
This smells like an OKD issue.
The fact that the generated Ignition configuration does not pass validation, and that is has a `networkd`, is a bit of concern.

/cc @LorbusChris @vrutkovs

**Comment by LorbusChris** [comment]
@majorinche it looks like you might be using the OCP installer?
Ignition config spec version must be 3.0.0 for OKD (from installer's fcos branch).
In spec 3, there's no duplicates allowed, and the filesystem identifier as well as the networkd section don't exist.

Please ensure you are using the proper Ignition and Installer versions.
If this problem persists, please add the `must-gather` logs to this report here.

**Comment by majorinche** [comment]
@LorbusChris  i try re-generate ignition file like following steps
git clone https://github.com/openshift/installer.git
git checkout -b fcos
hack/build.sh
openshift-install version
openshift-install unreleased-master-3156-g5face7c5dda8689601a377d6a70878a0aece2504
built from commit 5face7c5dda8689601a377d6a70878a0aece2504
release image registry.svc.ci.openshift.org/origin/release:4.5

openshift-install create manifests --dir=aa-1
openshift-install create ignition-configs --dir=aa-1

the ignition version still be 2.2.0
{"ignition":{"config":{},"security":{"tls":{}},"timeouts":{},"version":"2.2.0"},..}

**Comment by vrutkovs** [comment]
https://github.com/openshift/installer/commit/5face7c5dda8689601a377d6a70878a0aece2504 is master, not `fcos` branch

**Comment by LorbusChris** [comment]
@majorinche please ensure you are correctly checking out the branch, or even better use the pre-built binaries from our latest Beta release: https://github.com/openshift/okd/releases/tag/4.4.0-0.okd-2020-05-23-055148-beta5

**Comment by majorinche** [comment]
yes, some mistake i just made, use the ocp installer not okd installer to generate ignition

now, i extract openshift-installer command from okd mirrored registry, and it is ok to install and reboot bootstrap node with new ignition

but try install master node, it reports this error again(emergency.service: inappropriate ioctl for device)

i try go to emergency mode by using single in kernel command, but still meet this error
i try examine the ignition file by command "podman run --rm -i quay.io/coreos/ignition-validate - < master-1.ign", validation reports no error

i think it maybe be ignition problem, while master node has same environment with bootstrap node

i'm a little confused, why does this error to block to get inside the OS, or i can check some logs

**Comment by dustymabe** [comment]
@LorbusChris @vrutkovs ^^
