### ISSUE TITLE
chrony time server config DHCP support

### ISSUE THREAD

**Issue by egeturgay** [coreos/fedora-coreos-tracker#517]
Chrony ntp setting is currently defaults to the fedora NTP pools, this poses two problems for enterprise environments
- outbound access to the public servers may not be available (or can be behind a proxy)
- external / 3rd party time sources may not be appropriate for PCI compliance

Coming from container-linux, the NTP pools could be fetched from the DHCP config.
In the public cloud (aws in my case), an internal time source is provided by DHCP which does not require additional ACLs for network access (169.254.169.123).

Knowing the chrony config can be provided as part of the ignition deployment, this increases the size of the userdata which has a hard limit in AWS (16kb) and It would be better if the time source can be considered from the DHCP to reduce config management.

**Comment by lucab** [comment]
Thanks for the report, this is indeed something we are actively working on at https://github.com/coreos/fedora-coreos-config/pull/412.

/cc @rfairley @cgwalters @miabbott

**Comment by rfairley** [comment]
Thanks @egeturgay for catching this! Indeed the exec bits were missing. Opened a PR to fix in #454.

**Comment by cgwalters** [comment]
The fix for this should be in [the latest testing release](https://github.com/coreos/fedora-coreos-config/commit/7bbd96a83aa458402a4aef02eaa8dd6de3171290).

**Comment by dustymabe** [comment]
> The fix for this should be in [the latest testing release](https://github.com/coreos/fedora-coreos-config/commit/7bbd96a83aa458402a4aef02eaa8dd6de3171290).

Thanks Colin. The final bits to make the file executable did land in the testing release.

The fix for this went into testing stream release `32.20200615.2.0`.  Please try out the new release and report issues.

**Comment by egeturgay** [comment]
I can confirm this is now working as expected, thank you!

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20200615.3.0`.
