### ISSUE TITLE
races in boot.mount

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#523]
https://github.com/coreos/fedora-coreos-config/pull/346#issuecomment-639779100

We have multiple things mounting `/boot` and we're not cleanly waiting for the device.  https://github.com/coreos/fedora-coreos-config/pull/420 tried to fix this but was withdrawn; we will need some solution.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `32.20200615.2.0`.  Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20200615.3.0`.
