### ISSUE TITLE
Docker malfunctions with normal user privileges.

### ISSUE THREAD

**Issue by lruzicka** [coreos/fedora-coreos-tracker#526]
During a CoreOS test day I was trying to accomplish the following test case: https://fedoraproject.org/wiki/QA:Testcase_CoreOS_build_container

While `podman` worked without any issues, `docker` could not be used without running it under `sudo`. 

I got the following message:
~~~
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=ygpuv2ntei891zd7re5iidxh3&shmsize=0&t=fcct&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
~~~

With `sudo`, the problem went away and I was able to build and run the container.

~~~
[core@localhost ~]$ rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/next
                   Version: 32.20200601.1.1 (2020-06-03T02:26:26Z)
                    Commit: 08040bebbab87a3343a281f94bb68010df618eb6ce6ac3d4230d2595959b5da1
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0

~~~

**Comment by lucab** [comment]
Thanks for the report. I think it's just a case where the test is not correctly worded, as to the best of my knowledge rootless `docker` is not supported without further user customization (see https://github.com/coreos/fedora-coreos-tracker/issues/2).

I've updated the Wiki page with a full matrix of cases: rootless podman, privileged podman, and privileged docker. Does that work for you?

**Comment by lruzicka** [comment]
Yes, that works for me. Thank you very much.
