### ISSUE TITLE
After change stream from stable to next and revert, sssd.service fails

### ISSUE THREAD

**Issue by bdlink** [coreos/fedora-coreos-tracker#529]
Reproduce:
1. Install FCOS 31.20200517.3.0 ISO on vmWare guest, ssh to FCOS
2. sudo systemctl stop zincati.service
3. STREAM=“next”
4. sudo rpm-ostree rebase “fedora/x86_64/coreos/${STREAM}”
5. Receiving objects…Staging deployment….Upgraded (list) Removed (list) Added (List)
6. sudo systemctl reboot
7. ssh back in after boot:
8. sudo rpm ostree status
9. Try temporary rollback (selecting from boot screen)
10. Try permanent rollback,  sudo rpm-ostree rollback -r (logged in to the temporarily rolled back version)
11. Both cases, get message on login:
[systemd]
Failed Units: 1
  sssd.service
----------------------------------------
**Original system:**

[core@test-fcos ~]$ sudo rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200517.3.0 (2020-06-01T17:15:29Z)
                    Commit: 967b7b8d624e6d10ff51c2e81ef198fae966c567ac2e9b479771c693d0987949
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4

**After change to next:**

State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/next
                   Version: 32.20200601.1.1 (2020-06-03T02:26:26Z)
                    Commit: 08040bebbab87a3343a281f94bb68010df618eb6ce6ac3d4230d2595959b5da1
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0

  ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200517.3.0 (2020-06-01T17:15:29Z)
                    Commit: 967b7b8d624e6d10ff51c2e81ef198fae966c567ac2e9b479771c693d0987949
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4

**After temporary rollback:**

[systemd]
Failed Units: 1
  sssd.service
[core@test-fcos ~]$ sudo rpm-ostree status
State: idle
Deployments:
  ostree://fedora:fedora/x86_64/coreos/next
                   Version: 32.20200601.1.1 (2020-06-03T02:26:26Z)
                    Commit: 08040bebbab87a3343a281f94bb68010df618eb6ce6ac3d4230d2595959b5da1
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
                      Diff: 356 upgraded, 6 removed, 5 added

● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200517.3.0 (2020-06-01T17:15:29Z)
                    Commit: 967b7b8d624e6d10ff51c2e81ef198fae966c567ac2e9b479771c693d0987949
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4

**After permanent rollback:**

[systemd]
Failed Units: 1
  sssd.service
[core@test-fcos ~]$ sudo rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200517.3.0 (2020-06-01T17:15:29Z)
                    Commit: 967b7b8d624e6d10ff51c2e81ef198fae966c567ac2e9b479771c693d0987949
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4

  ostree://fedora:fedora/x86_64/coreos/next
                   Version: 32.20200601.1.1 (2020-06-03T02:26:26Z)
                    Commit: 08040bebbab87a3343a281f94bb68010df618eb6ce6ac3d4230d2595959b5da1
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0

**Comment by jlebon** [comment]
Right, this is likely because `sssd` is erroring out with

> Lower version of database is expected!

due to the newer `sssd` having done a migration of some kind. Can you verify this is the case with `journalctl -u sssd.service`?

This is just how things work currently: `/var` is shared data across deployments and we don't snapshot it when creating a new deployment.

**Comment by bdlink** [comment]
Correct:
Jun 08 18:58:53 test-fcos sssd[3833]: Lower version of database is expected!
Jun 08 18:58:53 test-fcos sssd[3833]: Removing cache files in /var/lib/sss/db should fix the issue, but note that r>
Jun 08 18:58:53 test-fcos systemd[1]: sssd.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED

**Comment by jlebon** [comment]
Thanks. I'm going to close this issue now since it's an expected side-effect of how things work. Maybe one day we'll have an option for snapshotting `/var` or something though it ties to lots of other things. Feel free to re-open (or anyone else) if you'd like to discuss further having this in FCOS.

**Comment by dustymabe** [comment]
Thanks for the report @bdlink and for participating in the test day! @jlebon I agree this is an example of application data (this case happens to be a system application) basically not being able to handle a downgrade. The question is how fatal is it (probably depends on each individual's configuration).

**Comment by lucab** [comment]
I wonder whether sssd should provide a "clear cache on boot" service that we could opt-in. That would help handling cache issues across upgrades/rollbacks, as I think server workloads do not rely on "cache credentials across reboots" generally.

**Comment by dustymabe** [comment]
> I wonder whether sssd should provide a "clear cache on boot" service that we could opt-in. That would help handling cache issues across upgrades/rollbacks, as I think server workloads do not rely on "cache credentials across reboots" generally.

Agree.

For now, anyone hitting this issue can just delete the cache files and restart the service:

```
$ sudo su -
# rm -rf /var/lib/sss/db/*
# systemctl start sssd
```

**Comment by lucab** [comment]
Forwarded to https://github.com/SSSD/sssd/issues/5214.
