### ISSUE TITLE
how to download docker-ce

### ISSUE THREAD

**Issue by majorinche** [coreos/fedora-coreos-tracker#530]
problem: 
podman pull docker-repo.sonic.com:443/okd44/okd:4.4.0-0.okd-2020-05-23-055148-beta5-thanos
Get https://docker-repo.sonic.com:443/v2/: _**x509: certificate signed by unknown authority**_

FCOS version: Fedora CoreOS 31.20200505.3.0

i know this error can be fixed by docker, like: scp docker-repo.sonic.com.crt /etc/docker/certs.... and then cat docker-repo.sonic.com.crt >> /etc/pki/tls/certs/ca-bundle.crt, and then systemctl restart docker

but by default, there is no docker exist, so i try install docker-ce by adding repo
[docker]
name=docker
baseurl=http://172.16.24.213/docker-ce/linux/fedora/31/x86_64/stable/
gpgcheck=0
enabled=1

rpm-ostree install docker-ce
nothing provides libcgroup needed by docker-ce-3:19.03.0-3.fc31.x86_64

so where can i find out where libcgroup is, or any other method to fix "certificate signed by unknown authority" promblem in FCOS

many thanks

**Comment by dustymabe** [comment]
@majorinche  If you're looking for `docker`, we do provide `/usr/bin/docker` via the `moby-engine` package in FCOS. Does that meet your needs?

**Comment by majorinche** [comment]
originally, i wanna a docker service, not a comand
but anyway, i fix this issue by changing the FCOS date with ntp service.
thanks

**Comment by dustymabe** [comment]
> originally, i wanna a docker service, not a comand

Yeah I'm not  sure what problem you're having or what your desired outcome is exactly. Could you be more clear?

> but anyway, i fix this issue by changing the FCOS date with ntp service.
> thanks

Or.. maybe everything is good now?

**Comment by majorinche** [comment]
@dustymabe  yes, as i mentioned above, this error always can be seen, and i only know how to fix it in docker environment, not podman, so i need a docker service, like:
scp docker-repo.sonic.com.crt /etc/docker/certs.... and then cat docker-repo.sonic.com.crt >> /etc/pki/tls/certs/ca-bundle.crt, and then systemctl restart docker

but etcd is ok now, after i adjust the ntp time, i cannot say everything is good, as it is a little tough to install okd with fcos. long road to go :-)
