### ISSUE TITLE
package layering fails on f32 base with libvirt package

### ISSUE THREAD

**Issue by grantral** [coreos/fedora-coreos-tracker#537]
## Steps to reproduce
1. `$ sudo rpm-ostree install libvirt`

## Actual behaviour
```
Checking out tree 08040be... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-03-17T20:10:45Z
rpm-md repo 'updates' (cached); generated: 2020-06-07T18:20:54Z
rpm-md repo 'fedora' (cached); generated: 2020-04-22T22:22:36Z
Importing rpm-md... done
Forbidden base package replacements:
  gnutls 3.6.13-4.fc32 -> 3.6.14-1.fc32 (updates)
This likely means that some of your layered packages have requirements on newer or older versions of some base packages. Doing `rpm-ostree cleanup -m` and `rpm-ostree upResolving dependencies... done
error: Some base packages would be replaced
```

### Ignition config
```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc...
```
### rpm-ostree status
```
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/next
                   Version: 32.20200601.1.1 (2020-06-03T02:26:26Z)
                    Commit: 08040bebbab87a3343a281f94bb68010df618eb6ce6ac3d4230d2595959b5da1
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
```

**Comment by dustymabe** [comment]
hey @grantral - you're bumping up into #400 . Basically, right now package laying can make upgrades unreliable. We're disussing how to make layering more reliable in #401.  We do recommend running as much as you can in a container to try to avoid hitting this problem.

That being said, we'll drop a round of releases next week and the `testing` release will have the new gnutls that you need.

**Comment by dustymabe** [comment]
Just verified that I could `rpm-ostree install libvirt` on the current `next` (`32.20200625.1.0`) and `testing` (`32.20200629.2.0`) releases. I'm going to close this out since it's just another instance of #400. We'll hopefully get around to #401 soon enough that this won't be an issue for much longer.

**Comment by spaced** [comment]
just hit the same issue, tested with `32.20200824.3.0`, but also with `next` stream.
Just if someone struggle with this, my workaround until #400 is solved:
```
curl -O  https://download-ib01.fedoraproject.org/pub/fedora/linux/updates/32/Everything/x86_64/Packages/g/gnutls-3.6.15-1.fc32.x86_64.rpm
rpm-ostree override replace ./gnutls-3.6.15-1.fc32.x86_64.rpm
rpm-ostree install libvirt qemu-kvm tmux virt-install
```
