### ISSUE TITLE
enhance ostree mirroring for better UX

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#54]
Since we [have decided]( https://github.com/coreos/fedora-coreos-tracker/issues/23#issuecomment-420760366) on using ostree repos to deliver content to end users for now, let's work with Fedora Infra and upstream in ostree to get ostree mirroring set up and working well.

related: 

- https://github.com/coreos/fedora-coreos-tracker/issues/23#issuecomment-425927357
- https://pagure.io/fedora-infrastructure/issue/5970

**Comment by dustymabe** [comment]
mariking as high priority as the UX is something we want to get right for FCOS

**Comment by sinnykumari** [comment]
Mirrormanager issue - https://github.com/fedora-infra/mirrormanager2/issues/258

**Comment by sinnykumari** [comment]
We are also exploring using cloudfront to CDN entire ostree repo/ for content delivery and making use of contenturl to fetch repo/deltas/ and repo/objects/ content on client machine. This approach has some interesting results at https://github.com/ostreedev/ostree/issues/1541#issuecomment-452721757

**Comment by sinnykumari** [comment]
We have new cloudfront set-up done from Fedora side caching content of ostree repo https://kojipkgs.fedoraproject.org/atomic/repo/ . 
With new config, user's config looks something like:
```
[remote "fedora"]
url=https://ostree.fedoraproject.org
gpg-verify=true
gpgkeypath=/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-29-primary
contenturl=mirrorlist=https://ostree.fedoraproject.org/mirrorlist
```
With new config, we have seen nice results with speed improvement upto 20 times faster. See https://github.com/ostreedev/ostree/issues/1541#issuecomment-458975486

**Comment by jlebon** [comment]
Let's discuss this in today's community meeting? And if we're agreed, then we can move forward with planning on updating user configs. (This is more for other Fedora OSTree-based systems available right now of course, given that FCOS is not yet out :)).

One note: was talking about this with @sinnykumari and @puiterwijk at DevConf.cz about shipping the config as part of a package. Now that we have https://github.com/ostreedev/ostree/pull/1773, we should definitely do this from day 0 for FCOS.

**Comment by dustymabe** [comment]
This work is in progress and should be complete today.

**Comment by sinnykumari** [comment]
In [FCOS community meeting](https://meetbot.fedoraproject.org/fedora-meeting-1/2019-01-30/fedora_coreos_meeting.2019-01-30-16.30.log.html) , we agreed that using [ostree config](https://github.com/coreos/fedora-coreos-tracker/issues/54#issuecomment-458979768) with contenturl set makes ostree update much faster on user's system.

Updated ostree ostree config looks like:
```
[remote "fedora"]
url=https://ostree.fedoraproject.org
gpg-verify=true
gpgkeypath=/etc/pki/rpm-gpg/
contenturl=mirrorlist=https://ostree.fedoraproject.org/mirrorlist
```
Latest ostree supports [passing directory containing list of gpgpkeys in gpgkeypath](https://github.com/ostreedev/ostree/pull/1773) .

Next step is to ship this config to user through an rpm package. This allow us to update the remote config whenever required without effecting user's existing ostree remote config. This will be tracked in https://github.com/coreos/fedora-coreos-tracker/issues/143 .

**Comment by dustymabe** [comment]
Nice work sinny!
