### ISSUE TITLE
Question: What services/targets to require for a service which starts container using podman

### ISSUE THREAD

**Issue by claudio-walser** [coreos/fedora-coreos-tracker#543]
Hello fcos people

I have a hard time to start services reliably on startup using podman. With docker it works fine because i can rely on docker.service. With podman i am not getting it to work reliably every time.

The following is my service file of haproxy for example:
```
[Unit]
Description=Haproxy in a Container
After=local-fs.target
Requires=local-fs.target

[Service]
TimeoutStartSec=0
Restart=always
User=core
Group=core
EnvironmentFile=/etc/env
ExecStartPre=-/usr/bin/podman rm -f haproxy
ExecStartPre=-/usr/bin/podman pull docker.io/library/haproxy:2.1-alpine
ExecStart=/usr/bin/podman run \
    -p 8080:8080 \
    -p 8083:8083 \
    -p 6443:6443 \
    -p 22623:22623 \
    -p 80:80 \
    -p 443:443 \
    -p 24007:24007 \
    -p 49152:49152 \
    -v /etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:z \
    -e LB_HOST=${HOSTNAME} \
    --name haproxy \
    docker.io/library/haproxy:2.1-alpine
ExecStop=/usr/bin/podman stop haproxy

[Install]
WantedBy=multi-user.target
```

Most of the time, this service fail to start automatically with the error
```Error: could not get runtime: error creating tmpdir /run/user/1000/libpod/tmp: mkdir /run/user/1000: permission denied```
Sometimes it works without issues though.

I tried playing aroung with After/Requires with many different values but are not able to get it to run every time. I played around with TimeoutStartSec as well but dont like to just wait a fixed amount of time, there needs to be a service/target  for this, I just dont see it.

Thank you and best regards
Claudio

**Comment by lucab** [comment]
Thanks for the report. This sounds like something racing in podman. Can you please report this to https://github.com/containers/libpod, along with the podman version where this is happening?

**Comment by claudio-walser** [comment]
Thank you for your evaluation, i will file a bug for libpod.

**Comment by dustymabe** [comment]
> Thank you for your evaluation, i will file a bug for libpod.

Did you open an issue against libpod? Was it fixed upstream?

**Comment by claudio-walser** [comment]
To be honest, i did not until now. It also seems that libpod did alot systemd related work in the latest releases and i wanted to test with the latest Podman release before i file a bug there. If you want, you can close this issue/question here. This was mainly because i thougth i might just be doing something simple wrong, which seems not to be the case according to you guys.

**Comment by claudio-walser** [comment]
I digged a bit deeper into it. I am not very convinced this is a race condition in libpod, are you guys sure about that?

The following is my situation
I have 4 nodes on baremetal which i setup by myself. On this nodes i face this issue. These nodes are running FCOS 32.20200629.3.0

Then i ran an OKD Cluster with 7 nbdes, using OKD 4.5.0-0.okd-2020-07-12-134038-rc
I assume, since it is from the stable channel, it's using the same fcos version.
Not sure how to check to be honest since rpm-ostree status  just state
```
pivot://quay.io/openshift/okd-content@sha256:b8da3969dc12c6d17eb1ddc5463561c7f3691cbcc17b8d583bab360d7a23100a
```

The thing is, the systemd services run on the OKD instances without a problem under root and under core
They run on my self installed FCOS instances under root without a problem
The only case where this issue happens to me is on my self installed FCOS instances with core user.

If you really think this is an issue regarding libpod, i am happy to file a bug there. But i feel like i just miss something important on my self provisioned instances.

BTW, i can provide a simple ignition file to reproduce that behavior. 
Podman is in the same version on both, my self installed boxes and my OKD boxes.

I've digged through various sources online, like https://discussion.fedoraproject.org/t/run-podman-as-non-root-gives-file-permission-errors/8506/7 for example.

**Comment by lucab** [comment]
See https://github.com/containers/podman/issues/6940 and https://github.com/containers/podman/issues/5572. Enabling user session lingering may help avoiding the race here, but in general there are some changed happening on podman side to improve its integration with systemd.

**Comment by claudio-walser** [comment]
Thank you Luca, I will try user session lingering as soon as I am back from holidays.

Do you have a time estimation when fcos will deliver podman in version >= 2?

**Comment by dustymabe** [comment]
See https://github.com/coreos/fedora-coreos-tracker/issues/575. You can try it out now on the `next` stream. Please report your good or bad experience!

**Comment by claudio-walser** [comment]
Thank you both very much, enabling user session lingering works perfect.
