### ISSUE TITLE
Generating password_hash

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fedora-coreos-tracker#546]
CoreOS way of generating password hash 
```console
$ python3 -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'
```
does not work.  What is the correct way to generate one that works with FCOS?

**Comment by bgilbert** [comment]
Looks like the [docs site](https://docs.fedoraproject.org/en-US/fedora-coreos/) is down, but you can see the authentication doc source [on GitHub](https://github.com/coreos/fedora-coreos-docs/blob/master/modules/ROOT/pages/authentication.adoc#using-password-authentication).
