### ISSUE TITLE
How Can /etc/issue Be Changed?

### ISSUE THREAD

**Issue by medined** [coreos/fedora-coreos-tracker#548]
I'd like to add a warning to the /etc/issue file but it is on a read-only disk. Is there a work-around for this?

**Comment by dustymabe** [comment]
Yeah `/etc/issue/` is a symlink to a file under `/usr/`, which is read-only. You could replace the symlink but how about something like this instead:

```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAA...
storage:
  files:
    - path: /etc/issue.d/80_warning.issue
      contents:
        inline: |
          WARNING WARNING WARNING
```

**Comment by medined** [comment]
Can I replace the symlink inside the Ignition file?

**Comment by medined** [comment]
Changing the `/etc/issue` symlink to a banner file resolved the Lynis BANN-0716 finding. I saw that it was a link, but it had not occurred to me that it was changeable. I also did not know about the `issue.d` directory. Thanks.

**Comment by medined** [comment]
I see the confused emoji. While using `/etc/issue.d/80_warning.issue` is a fine idea, my goal was to resolve the Lynis security check. Adding a file to the `issue.d` directory did not resolve the check. However, changing the symbolic link to a file that I can change works.

At https://github.com/medined/lynis-on-fedora-coreos, I am trying to pass as many Lynis tests as possible. Part of that work is providing context for decisions so that others can challenge them.

**Comment by dustymabe** [comment]
Makes sense to me. It might be worth following up with Lynis (not sure if they have an issue tracker somewhere) to see if issue.d is on their radar.
