### ISSUE TITLE
No Permission To View Ignition Documentation

### ISSUE THREAD

**Issue by medined** [coreos/fedora-coreos-tracker#550]
I don't know if this is the right forum for this issue. When I visit the Ignition documentation, I see "You don't have permission to access this resource." This is the URL.
```
https://docs.fedoraproject.org/en-US/fedora-coreos/producing-ign/
```

**Comment by lucab** [comment]
Thanks for the report. There are indeed some known issues with the fedora docs website, see https://pagure.io/fedora-infrastructure/issue/8964.

**Comment by lucab** [comment]
This should have been fixed on the infra side. Please report back on the ticket there if you still see errors.
