### ISSUE TITLE
Is /usr/local/bin a good place to put commands?

### ISSUE THREAD

**Issue by skycastlelily2** [coreos/fedora-coreos-tracker#551]
Hi,
I'm trying to set up k8s on Fedora CoreOs,and the k8s guide says I should put commands into /opt/bin, but it's not in the default PATH or secure_path,and I've tried to put commands into /usr/local/bin,and set up the cluster successfully.I'm thinking to update the guide and suggest users put commands to /usr/local/bin.Do you think /usr/local/bin is a good place to put?Thanks.

**Comment by lucab** [comment]
@skycastlelily2 how are the binaries getting there? Via some sort of packaging or directly as binary drops?

In general both places are suitable for placing local binaries, with some subtle nuances depending on the answer above. I'll let @cgwalters or @jlebon chime in with more details.

The overall recommendation though is: do not place and run applications on the host, move them to a container.

**Comment by cgwalters** [comment]
I think this is a duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/354

**Comment by skycastlelily2** [comment]
@lucab By downloading them there,and by commands I  mean kubelet,etc, sorry for failing to say it clearly.
