### ISSUE TITLE
FCOS first boot fails if ignition config is wrong version, and does not tell you

### ISSUE THREAD

**Issue by gjsmo** [coreos/fedora-coreos-tracker#556]
I'm using the OVA image of FCOS 31.20200517.3.0 and booting with OKD generated configs. Due to the length of the config I've got a "append config" as below:

```
{
  "ignition": {
    "config": {
      "append": [
        {
          "source": "http://IP/bootstrap.ign",
          "verification": {}
        }
      ]
    },
    "timeouts": {},
    "version": "2.1.0"
  },
  "networkd": {},
  "passwd": {},
  "storage": {},
  "systemd": {}
}
```

This file is then converted to base64 and pasted into the OVA config option when booting in vSphere. This fails with the following error screen:

![image](https://user-images.githubusercontent.com/12057767/85936240-94573500-b8c6-11ea-9e5f-3e4cc332f5aa.png)

Note that in this case the only issue is actually that the version was wrong (2.1.0 instead of the required 3.0.0) but no information about this is presented. Using a screen recording software shows a working boot up until "Started Ignition (setup base config)" and the next frame is the above error, which is totally useless. Would be nice if there was at least some hint as to the issue.

**Comment by dustymabe** [comment]
IIRC the relevant error messages only get printed on one console. You'll need to make sure you're on the primary console. See https://docs.fedoraproject.org/en-US/fedora-coreos/emergency-shell/ to see if that helps you get to a point where an appropriate error message is being displayed for you.

**Comment by dustymabe** [comment]
@gjsmo can you confirm that you were able to get the relevant error messages when booted to the primary console?

**Comment by dustymabe** [comment]
Closing this out. Please re-open if there is any more information to add.
