### ISSUE TITLE
VirtualBox ISO boot fails: Failed to start Switch Root

### ISSUE THREAD

**Issue by matryoshkababushka** [coreos/fedora-coreos-tracker#559]
# Steps for reproduction

0. Create VirtualBox Fedora 64-bit with default settings
3. Use "coreos_production_iso_image.iso" as bootable Optical Disk in Virtual Box
4. Start Virtual Machine

# Expected Behavior
CoreOS starts normal shell with `coreos-installer` available.

# Actual Behavior
CoreOS reports an error and only suggests switching to the Emergency Shell.

# Emergency shell details

## rpm-ostree status

```
rpm-ostree: command not found
```

## systemctl status initrd-switch-root.service

```
Specified switch root path '/sysroot' does not seem to be an OS tree. os-release file is missing.
```

**Comment by bgilbert** [comment]
`coreos_production_iso_image.iso` is a CoreOS Container Linux image.  You can download a Fedora CoreOS image [here](https://getfedora.org/coreos/download?tab=metal_virtualized&stream=stable).

**Comment by matryoshkababushka** [comment]
Good catch! Missed the selection between two ISO files in the same folder.
