### ISSUE TITLE
sending podman 2.x major version bump to `next` stream first

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#560]
`podman-2.0.1-1.fc32 ` landed in fedora stable (and thus FCOS `testing-devel`) last week. Since this is a major version bump should we consider letting this soak in `next` for a cycle before sending it to `testing`?

**Comment by jdoss** [comment]
IMO this PR really should get merged https://github.com/containers/podman/pull/6842 and baked into a release first and podman 2.0.2 has a lot of fixes that maybe are worth waiting for.

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/RKIU2F7NQHLLTPGWEFP3HXYMIVCRUJ4Y/). 

```
13:22:13     dustymabe | #agreed relegate podman major version bump to the `next` stream for a few cycles
```
