### ISSUE TITLE
"System BootOrder not found. Initializing defaults" can be worked around with "Boot from file" 

### ISSUE THREAD

**Issue by eriksjolund** [coreos/fedora-coreos-tracker#563]
On a newly bought laptop **HP Elitebook 850 G6** (without Windows but with FreeDos) I can boot 

**CentOS-8.1.1911-x86_64-dvd1.iso**

from a USB stick just fine but when I try boot

**fedora-coreos-32.20200601.3.0-live.x86_64.iso**

 this text is shown on the monitor

    System BootOrder not found. Initializing defaults.
    Creating boot entry "Boot0009" with label "Fedora" for file "\EFI\fedora\shimx64.efi"
    
    Reset System

and after about one second the computer is automatically rebooted.

When I enter the BIOS I can see that the setting: __Configure Legacy Support and Secure Boot__ is set to _Legacy Support Disable and Secure Boot Disable_.

(That setting has not been changed since the computer came delivered)

It is possible to change that setting to either:
_Legacy Support Enable and Secure Boot Disable_
or
_Legacy Support Disable and Secure Boot Enable_

If I change to
 _Legacy Support Enable and Secure Boot Disable_
a warning is shown that other settings in the BIOS need to be changed (for instance regarding Thunderbolt security) so I decided not to change that setting.

I restarted the computer and and pressed F9 to enter the _Boot Menu_.
Previously I had selected 

_UEFI - Kingston DataTraveler 3.0 60A44 ..._

but this time I chose

_Boot from file_

which gave me the possibility to navigate in the file system down to the file _shim64.efi_

1. Select _PciRoot(0x0)/Pci(0x14,0x0)/USB(0xC,0x0)/HD(1,MBR,0x6E2CF7 ...._
2. Select _EFI_
3. Select _fedora_
4. Select _shimx64.efi_

Now Fedora CoreOS booted up just fine.

Is this a bug or expected behavior?

### How the 2 USB sticks were created:

To write the 2 USB sticks, I used the commands

    sudo su -c "cat /tmp/fedora-coreos-32.20200601.3.0-live.x86_64.iso > /dev/sda"

and 

    sudo su -c "cat /tmp/CentOS-8.1.1911-x86_64-dvd1.iso > /dev/sda"

on a Fedora 32 computer.

**Comment by junjiequ** [comment]
+1
I have exactly the same question. 
I did almost the same to install the live image on a HP machine.
What I did differently was I flashed the ISO file using balenaEtcher from a windows client.

**Comment by cgwalters** [comment]
I see this too on a recent Lenovo laptop.  I am not sure if it's related, but the laptop also emits an incredibly loud beep when this happens.

**Comment by jlebon** [comment]
Might be unrelated, though an issue with the same final error message showed up yesterday too in Silverblue: https://bugzilla.redhat.com/show_bug.cgi?id=1855116.

**Comment by dustymabe** [comment]
Anyone still able to reproduce this? When it does happen, does it happen every boot or is it intermittent?

**Comment by axed** [comment]
Same error after live installation here on my second hand Thinkpad t560.
Secureboot was disabled in the bios.

**Comment by bgilbert** [comment]
@axed Are you installing Fedora CoreOS or Fedora Workstation?

**Comment by axed** [comment]
@bgilbert Workstation - aaah sorry, i must have overread that this thread was CoreOS specific after digging through so many pages looking for a solution. But since workstation isnt working, i can take the time to test Fedora CoreOS as well... just to see if the result is the same

**Comment by eriksjolund** [comment]
I made a new test on the same  __HP Elitebook 850 G6__ laptop as in https://github.com/coreos/fedora-coreos-tracker/issues/563#issue-653450910 but with the latest `next` release. The same thing happens as before. It happens every time. (At least the three times in a row tested that I now tested). A few months ago I tested it many more times. Also then it happened every time. 
```
[erik@laptop ~]$ coreos-installer download -s next -f iso
gpg: Signature made Tue 01 Dec 2020 10:30:36 PM CET
gpg:                using RSA key 963A2BEB02009608FE67EA4249FD77499570FF31
gpg: Good signature from "Fedora (33) <fedora-33-primary@fedoraproject.org>" [ultimate]
> Read disk 750.0 MiB/750.0 MiB (100%)   
./fedora-coreos-33.20201130.1.0-live.x86_64.iso
[erik@laptop ~]$
```
I wrote the iso file to a USB stick
```
[root@laptop ~]# cat ~erik/fedora-coreos-33.20201130.1.0-live.x86_64.iso > /dev/sda
[root@laptop ~]# echo $?
0
[root@laptop ~]# 
```

The new test:
1. The __HP Elitebook 850 G6__ is turned off
2. Insert the USB stick
3. Press the power button
4. Press _F9_ to get the boot menu
5. This text is shown:
(a bit abbreviated)

Boot Menu

     * UEFI - Fedora
     * UEFI - Kingston DataTraveler 3.0 60A44.............
     * UEFI N/W - IPV4 Network - .....
     * UEFI N/W - IPV6 Network - .....
     * Boot from file

6. Press _arrow down_
7. Press _enter_ to select _UEFI - Kingston DataTraveler 3.0 60A44_
8. This text is shown on the monitor for 1 second

```
System BootOrder not found. Initializing defaults.
Creating boot entry "Boot0009" with label "Fedora" for file "\EFI\fedora\shimx64.efi"

Reset System
and after about one second the computer is automatically rebooted.
```
9. The computer is automatically rebooted.

### Regarding the beep mentioned in another comment

I don't hear any beep as described in  https://github.com/coreos/fedora-coreos-tracker/issues/563#issuecomment-656182905

There are some audio related settings in the BIOS:

* [x] Audio Device
* [x] Microphone
* [ ] Internal Speakers

**Comment by sar** [comment]
> Anyone still able to reproduce this? When it does happen, does it happen every boot or is it intermittent?

Seems like it's still there, was able to replicate this on a Mac using FCOS revision `33.20210328.3.0` which hits `Boot0009: BootOrder not found`.

I can access the GRUB prompt, on Mac it defaults to the path `/EFI/BOOT/BOOTX64.EFI`.

**Comment by boniek83** [comment]
Still there:
33.20210426.3.0
HP 600 G4, UEFI boot, latest bios (2.15)
Fedora Server 34 boots normally though.

**Comment by dustymabe** [comment]
Thanks for the data points. Please keep reporting when you hit this and on what hardware. Eventually we'll get a developer with some hardware that can reproduce and be able to drill down to where the problem actually is.

**Comment by eriksjolund** [comment]
It's not reproducible __fedora-coreos-35.20211203.1.0-live.x86_64.iso__.
(I use the same laptop as in the original bug report https://github.com/coreos/fedora-coreos-tracker/issues/563#issue-653450910)

**Comment by dustymabe** [comment]
Thanks @eriksjolund - I think this may be a result of https://github.com/coreos/fedora-coreos-tracker/issues/946#issuecomment-964415295 (implemented in https://github.com/coreos/coreos-assembler/pull/2435). @bgilbert - does that sound right?

**Comment by bgilbert** [comment]
Awesome, thanks for the update.  Yup, that sounds right.  It turns out that shim's fallback.efi was adding the CD to the boot order, and on systems with a TPM, rebooting the machine afterward.
