### ISSUE TITLE
Not compatible with the latest docker-compose

### ISSUE THREAD

**Issue by loganmc10** [coreos/fedora-coreos-tracker#565]
I am downloading the latest version of docker-compose using ignition (v1.26.2)

When I try to run it I get:
```
[2262] Error loading Python lib '/tmp/_MEITRwUG9/libpython3.7m.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory
```
The remedy is:
```
sudo rpm-ostree install libxcrypt-compat
```

I am trying to get docker-compose working "out-of-the-box" using ignition, and I'd rather not mess with the ostree. Is it possible to include libxcrypt-compat in the default image?

Here is my ignition section if it matters:
```
{
        "path": "/var/home/core/docker-compose",
        "contents": {
          "source": "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64"
        },
        "mode": 493
  }
```

EDIT:
I suppose the other acceptable solution would be to include ```rpm-ostree install docker-compose```, I don't really need the absolute latest version, I'm just trying to get docker-compose installed automatically on boot

**Comment by dustymabe** [comment]
To me this seems like a good candidate to run inside of a container. All you would need to do is bindmount in the docker socket and also the `$PWD` into the container and then you'd get the same experience as you do with `docker-compose` itself. Something like (untested):

```
alias docker-compose='docker run -it --rm -v $PWD:/pwd/ -v /var/run/docker.sock:/var/run/docker.sock --workdir=/pwd/ --entrypoint=/usr/bin/docker-compose docker-compose'
```

**Comment by loganmc10** [comment]
Doesn't selinux block a container from mounting /var/run/docker.sock?

**Comment by loganmc10** [comment]
I guess this can be closed, I understand the goal is to keep the image lean. It's possible to run docker-compose remotely using DOCKER_HOST so it probably doesn't need to be included

**Comment by travier** [comment]
Calling `docker run` with `--privileged` (or `--security-opt label=disable`) should remove all SELinux restrictions regarding access to the Docker socket.

**Comment by ppettina** [comment]
For those still wanting a drop-in binary, they can build one using:
https://github.com/ppettina/docker-compose-fedora

**Comment by ciri** [comment]
I had this very same issue with the latest version on arch. Solve similarly by issuing:

`yay -S libxcrypt-compat`
