### ISSUE TITLE
meeting times and daylight savings

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#57]
In the past we have kept the meeting time on UTC year round. This was mainly to minimize confusion as well as not favor any one part of the world when making decisions. I'd like to propose we do the same thing with the fedora-coreos meeting, but let's discuss and come to a conclusion.

**Comment by dustymabe** [comment]
discussed in [today's IRC meeting](https://meetbot.fedoraproject.org/fedora-meeting-1/2018-10-17/fedora_coreos_meeting.2018-10-17-16.30.html). The sentiment from the group was that sticking with UTC would be best to keep confusion down and not prefer any one locale over the other.

Will keep the issue open for a week to see if anyone who couldn't make the meeting has input.

**Comment by sinnykumari** [comment]
+1 for sticking to UTC

**Comment by sayanchowdhury** [comment]
+1 for sticking to UTC, saves a lot of confusion IMO

**Comment by dustymabe** [comment]
no objections. we will follow UTC time for meetings in the future. Everyone will have to pay attention to local timezone changes and make adjustments accordingly. You can add the meeting to your calendar to help with this: https://apps.fedoraproject.org/calendar/CoreOS/

**Comment by dustymabe** [comment]
FYI this made it into the design doc in https://github.com/coreos/fedora-coreos-tracker/pull/40

**Comment by ajeddeloh** [comment]
Uh wrong issue or PR?

**Comment by dustymabe** [comment]
> Uh wrong issue or PR?

yep :man_facepalming:  https://github.com/coreos/fedora-coreos-tracker/issues/12#issuecomment-433135092
