### ISSUE TITLE
FCOS AWS AMIs for the new m6g instances

### ISSUE THREAD

**Issue by dhawal55** [coreos/fedora-coreos-tracker#579]
AWS recently launched M6g instances powered by Arm-based AWS Graviton2 processors. These instances arguably deliver up to 40% better price performance over the current generation x86-based Amazon EC2 M5 instances.

The current FCOS AMIs in AWS doesn't support 64-bit Arm-based processors. Is it possible to add AMIs for 64-bit Arm processors?

**Comment by cgwalters** [comment]
See https://github.com/coreos/fedora-coreos-tracker/issues/262

**Comment by lucab** [comment]
Pending work to provide `aarch64` images (in general, not only AWS) is tracker at https://github.com/coreos/fedora-coreos-tracker/issues/13. Closing this as a duplicate.
