### ISSUE TITLE
OKD v4.4 on bare metal installation stuck in the fcos setup 

### ISSUE THREAD

**Issue by milan-dikkumburage** [coreos/fedora-coreos-tracker#582]
we are trying install okd 4.4 cluster on Digital Ocean.

Following the https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html documentation

we stuck into the step of bootstrap of fcos step. But after we provide the kernel edit steps mentioned in the docs and we noticed it was not downloading the fcos raw image. any idea on this ?

[core@bootstrap ~]$ sudo rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200505.3.0 (2020-05-19T13:39:46Z)
                BaseCommit: 01f074cc6cd88d8d2b43f821da692f2367c101eb4377802cb35092bde0ef02f7
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: wget

  ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200505.3.0 (2020-05-19T13:39:46Z)
                    Commit: 01f074cc6cd88d8d2b43f821da692f2367c101eb4377802cb35092bde0ef02f7
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4

**Comment by dustymabe** [comment]
I'm working on writing down the steps I use to set up OKD on DigitalOcean, which should help get you where you want to be.

**Comment by milan-dikkumburage** [comment]
Hi @dustymabe Thanks for the reply .

Seems bootstrap process fail. its giving below error message ,

 [core@service ~]$ tail -f install_dir/.openshift_install.log
time="2020-07-22T18:40:27Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.okd4.rcloud.ca:6443/version?timeout=32s: EOF"
time="2020-07-22T18:40:57Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.okd4.rcloud.ca:6443/version?timeout=32s: EOF"
time="2020-07-22T18:41:27Z" level=debug msg="Still waiting for the Kubernetes API: Get https://api.okd4.rcloud.ca:6443/version?timeout=32s: EOF"


[root@linux home]# openshift-install --dir=installation_directory/ wait-for bootstrap-complete --log-level=info
INFO Waiting up to 20m0s for the Kubernetes API at https://api.okd4.rcloud.ca:6443...
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get https://api.okd4.rcloud.ca:6443/apis/config.openshift.io/v1/clusteroperators: dial tcp xxx.xxx.xxx.xxx:6443: connect: connection refused.

we provide the kernel edit steps mentioned in the docs and we noticed it was not downloading the fcos raw image. any idea on this ?

**Comment by vrutkovs** [comment]
Dupe of https://github.com/openshift/okd/issues/257

**Comment by lucab** [comment]
Closing this duplicate, let's keep the thread going in openshift/okd#257.
