### ISSUE TITLE
kubespray does not work with 32.20200715.3.0  libselinux-python3 forbidden

### ISSUE THREAD

**Issue by DirkTheDaring** [coreos/fedora-coreos-tracker#591]
The following package MUST be installed in order to support ansible, which then allows kubespray to run.
python3 libselinux-python3
The following error turns up with 32.20200715.3.0
```
#  rpm-ostree install libselinux-python3

Checking out tree a3b08ee... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-03-17T20:10:45Z
rpm-md repo 'updates' (cached); generated: 2020-07-31T00:48:42Z
rpm-md repo 'fedora' (cached); generated: 2020-04-22T22:22:36Z
Importing rpm-md... done
⠁
Forbidden base package replacements:
  libselinux 3.0-3.fc32 -> 3.0-5.fc32 (updates)
  libselinux-utils 3.0-3.fc32 -> 3.0-5.fc32 (updates)
Resolving dependencies... done
```

No clue how to fix this. Override seems not to work

**Comment by jlebon** [comment]
Hi @DirkTheDaring, see #400 about this specific problem. See also #578 re. Ansible and #93 for discussions about Kubernetes and OKD.

**Comment by DirkTheDaring** [comment]
found a temporary workaround, disable the updates repo..

`/usr/bin/sed -i 's/^enabled=.*/enabled=0/' /etc/yum.repos.d/fedora-updates.repo`
