### ISSUE TITLE
F33 Silverblue Rawhide version of toolbox forces password when using sudo but doesn't respect sudoer password

### ISSUE THREAD

**Issue by TheOneandOnlyJakfrost** [coreos/fedora-coreos-tracker#593]
When using toolbox on F33 Silverblue rawhide, entering a newly created toolbox results in an error as follows ...

> /usr/bin/id: cannot find name for group ID 1000

Inside of toolbox, when issuing a command sudoer privileges are required for, such as dnf like so ...
`sudo dnf install vim-enhanced terminator` results in the following prompt to the user ...

> We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

then, if I enter the user password the result is password attempt failure ...

> [sudo] password for ssnow: 
Sorry, try again.
[sudo] password for ssnow: 
Sorry, try again.

This issue was originally reported at https://discussion.fedoraproject.org/t/toolbox-and-root/22123/29 and I originally thought the users system must be broken in some way. That was until I installed a fresh rawhide version of Silverblue.
IMO, it may relate to the first message I get when entering the toolbox container. Perhaps not mapping the user as the root of the container.

**Comment by lucab** [comment]
Thanks for the report. We only track Fedora CoreOS bugs over here.

Can you please report your toolbox on Silverblue issue directly to the relevant developers at https://github.com/containers/toolbox?

**Comment by TheOneandOnlyJakfrost** [comment]
Sorry, I really thought I submitted this at the toolbox issue tracker. It is now though!
