### ISSUE TITLE
Ignition failure: failed to set SSH key: permission denied v2

### ISSUE THREAD

**Issue by trexx** [coreos/fedora-coreos-tracker#599]
Hello. I seem to be running in to an error similar to https://github.com/coreos/fedora-coreos-tracker/issues/496 except I am attempting to add a SSH key to new user and not core.

I've added a gist here of the ignition logs which includes my rendered ignition file: https://gist.github.com/trexx/7676767b358365adda18582f96813ff5
On first glimpse it looks like selinux maybe blocking the operation due to the `audit res=failed message` or I might be doing something wrong.

Any help would be appreciated :)

Maybe worth mentioning I'm transpiling a v1.1.0 yaml file in to a v3.1.0 ignition file 

Attempting to set a password to the new user is also failing
```
[    8.979755] ignition[606]: INFO     : files: createUsers: op(4): [started]  creating or modifying user "ceph"
[    8.992151] ignition[606]: CRITICAL : files: createUsers: op(4): [failed]   creating or modifying user "ceph": exit status 6: Cmd: "usermod" "--root" "/sysroot" "--password" "$6$<snip>" "ceph" Stdout: "" Stderr: "usermod: user 'ceph' does not exist in /etc/passwd\n"
[FAILED] Failed to start [    8.983867] ignition[606]: DEBUG    : files: createUsers: op(4): executing: "usermod" "--root" "/sysroot" "--password" "$6$<snip>" "ceph"
Ignition (files).
```

$ rpm-ostree status
```
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 32.20200715.3.0 (2020-07-27T11:36:29Z)
                    Commit: a3b08ee51b1d950afd9d0d73f32d5424ad52c7703a6b5830e0dc11c3a682d869
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
```

**Comment by trexx** [comment]
Upon further investigation, I've had success with ceph2. So I guess "ceph" is an internal user of some sorts?

**Comment by jlebon** [comment]
> So I guess "ceph" is an internal user of some sorts?

Yes, we already ship a system user called `ceph`: https://github.com/coreos/fedora-coreos-config/blob/d4d95291e1ea6feb1fd45f1bc0897b442d9c1bb0/manifests/passwd#L28. I think the error you're getting is from `usermod` getting confused about our use of nss-altfiles. We should be able to drop these hardcoded values once we move to systemd-sysusers.

But anyway, since `ceph` is a system user (and even with systemd-sysusers, overlaying the `ceph` package would re-add it), indeed you should use a different username for your new non-system user.

**Comment by trexx** [comment]
Thanks for the confirmation, we'll change the user. We are actually using cephadm to install the cluster which runs ceph in containers but we wanted a separate user cephadm could ssh as for orchestration purposes.
