### ISSUE TITLE
Have a coreos-assembler stable release to work with the stable branch of fedora-coreos-config

### ISSUE THREAD

**Issue by junjiequ** [coreos/fedora-coreos-tracker#602]
Hi,

I found myself in this situation: I could use neither the `v0.8.1` tag (too old) nor the `master` tag (too new) of the **coreos-assembler** to build the stable branch of the `fedora-coreos-config` repo.

The main cause here I think is the commit below:
https://github.com/coreos/coreos-assembler/commit/6f533ef55ee5cf2b10ad97df51eb2d190b6b2c2b#diff-f5e5c331891c4081b21b1f733752ba12 
I couldn't see the corresponding commit promoted to the `stable` branch of fedora-coreos-config yet... It's still sitting in the testing-devel branch: https://github.com/coreos/fedora-coreos-config/commit/346f77036f0061a10515449ce1b0bdd690ee1f36

I think the same dependency issue would happend to the coreos-installer as well..

It's great to see new changes happening all the time. But I couldn't create a new custom build using the latest tooling, and there is no fallback build of coreos-assembler I could use, which is a bit headache for me.

What would be the recommended approach to build the **stable** branch of the fedora-coreos-config repo while the coreos-assembler develops in such an advanced pace? i.e., Is there any milestone plan that we could refer to?

**Comment by bgilbert** [comment]
In this case, there's a [coreos-assembler branch](https://github.com/coreos/coreos-assembler/tree/fcos-32.20200726.3.0) for building the stable fedora-coreos-config.  In general, we try not to get into this situation too often.

coreos-installer tries to be independent of specific FCOS releases and there isn't a version dependency in this case.

**Comment by jlebon** [comment]
Normally, we try to avoid this issue by making the new coreos-assembler behaviour conditional on a new knob in e.g. [`image.yaml`](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/image.yaml). For this, we missed the compatibility constraints during code review.

We also have an outstanding issue in https://github.com/coreos/fedora-coreos-streams/issues/64 to investigate automatically pinning cosa whenever we do an FCOS release. For now, as Benjamin said we manually fork off a temporary branch whenever required.

**Comment by junjiequ** [comment]
Great! Thank you guys for the quick answer. 

In the mean time I also found that this was mentioned [here](https://github.com/coreos/fedora-coreos-streams/issues/158#issuecomment-671453114).
