### ISSUE TITLE
How to insert GuestInfo values into FCOS

### ISSUE THREAD

**Issue by matteoiacovitti** [coreos/fedora-coreos-tracker#603]
Hello,

Is it possible to add the GuestInfo values from a VM and insert them into the ignition file? 
![image](https://user-images.githubusercontent.com/25353683/90257078-aa886880-de14-11ea-864c-6f90473fedd0.png)

Or is there another way to have Fedora CoreOS insert these values?

Before on CoreOS CL I was able to do this using a script that modifies the static.network file but it does not look like Fedora CoreOS uses this file.

**Comment by dustymabe** [comment]
You might be able to glean some information from https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-vmware/

I don't think we support anything more than the folloing values right now:

- `guestinfo.ignition.config.data.encoding`
- `guestinfo.ignition.config.data`
- `guestinfo.afterburn.initrd.network-kargs`

**Comment by matteoiacovitti** [comment]
Ok thatnks.
