### ISSUE TITLE
Install open-vm-tools in fedora core

### ISSUE THREAD

**Issue by matteoiacovitti** [coreos/fedora-coreos-tracker#604]
Is there a way to install vmtools in fedora core using ignition? 

I am using packer.io to create a VM with FCOS and it requires adding some GuestInfo properties into the VM but without tools installed, vCenter won't be able to pick up the values in the VM.

**Comment by dustymabe** [comment]
hey @matteoiacovitti - sorry for the late reply here. You can package layer it:

```
sudo rpm-ostree install open-vm-tools
```

You can do this via Ignition as well. See the example in [our documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/os-extensions/#_example_layering_nano_and_setting_it_as_the_default_editor).
