### ISSUE TITLE
[meeting] Discuss adding systemd-networkd to FCOS

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#610]
Placeholder `meeting` issue for https://github.com/coreos/fedora-coreos-config/pull/574.  I'm locking this issue; please continue discussion in the linked PR.

**Comment by dustymabe** [comment]
We discussed this during the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/2H42NGC2ELXJEDCPOXOVGJLYPADJ6BTR/).

The two options that were discussed were:

- A. Ship networkd in the base layer. Stop removing the binary files during compose.
    - Also disable it by default using a systemd dropin and write documentation on how to enable it, along with accompanying documentation on the possible things that might not work as a result of enabling it. 
- B. Break out networkd into its own subpackage (if upstream systemd will accept the split) so it can be package layered easily.
    - Add a FAQ entry about using networkd.

There was lots of great discussion and creative ideas on how to solve the problem and the implications of both options. For now we have settled on:

```
13:35:07 dustymabe | #agreed we'll reach out to the systemd team to see how they
                   | feel about making a systemd-networkd subpackage. If they
                   | refuse or are not interested we will explore option A
                   | (including systemd-networkd in the base layer) but with a
                   | dropin that disables it by default.
```

The next step here is to reach out to the systemd team about the package split and base our future work on the outcome of that discussion.

I will cross post this in https://github.com/coreos/fedora-coreos-config/pull/574 where the targeted discussion for this has been happening.

**Comment by dustymabe** [comment]
The package was broken out and is now able to be layered.

The fix for this went into testing stream release `33.20201116.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `33.20201201.3.0`.
