### ISSUE TITLE
Start running tests against OpenStack in our CI

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#612]
We've been graciously offered an account from [Vexxhost](https://vexxhost.com/) we can use for running CI against openstack. Running CI against OpenStack on every build will help us make sure we don't regress behavior there so let's try to get it added to our pipeline.

**Comment by maclermo** [comment]
Installed from ISO using packer and running on OpenStack. Installed cloud-init and we are having a few issues :

1- You have to login as fedora instead of core with ssh-keys.
2- The script fails at "missing /etc/fstab"
3- The script fails at "service restart sshd, command not found"

PRETTY_NAME="Fedora CoreOS 32.20200907.3.0"
cloud-init --version = /usr/bin/cloud-init 19.4

**Comment by cgwalters** [comment]
> Installed from ISO using packer and running on OpenStack. Installed cloud-init 

Fedora CoreOS is centered on using [Ignition](https://github.com/coreos/ignition/).  Please try the pre-built openstack image and use an Ignition configuration in your user data.

**Comment by maclermo** [comment]
> > Installed from ISO using packer and running on OpenStack. Installed cloud-init
> 
> Fedora CoreOS is centered on using [Ignition](https://github.com/coreos/ignition/). Please try the pre-built openstack image and use an Ignition configuration in your user data.

Thank you for your reply. The main issue is that I need to get the ssh keys and the hostname from the metadata: http://169.254.169.254/meta-data. I have not been able to find a way to use Packer + OpenStack + fcct so that I can deploy VMs from OpenStack and that every VM querys the meta-data and adjusts accordingly.

**Comment by dustymabe** [comment]
IIUC our openstack image will query the metadata service and apply the SSH keys and hostname to the instance for you. You shouldn't need to use Packer at all. Just grab and use our openstack image directly. The latest one can be picked up from https://getfedora.org/en/coreos/download?tab=cloud_operators&stream=stable

**Comment by dustymabe** [comment]
I just checked this and it turns out the metadata service isn't being hit to grab the ssh key. This issue should be fixed by https://github.com/coreos/afterburn/pull/493. For now you can simply provide an SSH key in your ignition config (provided via userdata) like [this](https://docs.fedoraproject.org/en-US/fedora-coreos/producing-ign/#_writing_the_fcc_file). 

The hostname is getting provided by DHCP so we're good there.

**Comment by dustymabe** [comment]
> I just checked this and it turns out the metadata service isn't being hit to grab the ssh key. This issue should be fixed by [coreos/afterburn#493](https://github.com/coreos/afterburn/pull/493). For now you can simply provide an SSH key in your ignition config (provided via userdata) like [this](https://docs.fedoraproject.org/en-US/fedora-coreos/producing-ign/#_writing_the_fcc_file).
> 
> The hostname is getting provided by DHCP so we're good there.

will track the fix for this issue over in https://github.com/coreos/fedora-coreos-tracker/issues/633

**Comment by dustymabe** [comment]
Part of the work for this landed in https://github.com/coreos/coreos-assembler/pull/1833

**Comment by dustymabe** [comment]
And the last part of the work landed in https://github.com/coreos/fedora-coreos-pipeline/pull/294

New pipeline builds will now run tests against our OpenStack images in the [VEXXHOST](https://vexxhost.com/) public cloud.
