### ISSUE TITLE
How to setup NetworkManager with vm-tools

### ISSUE THREAD

**Issue by matteoiacovitti** [coreos/fedora-coreos-tracker#615]
Hello

I tried setting up a static IP using the method stated [here](https://docs.fedoraproject.org/en-US/fedora-coreos/static-ip-config/) and using variables that I pulled from the vmtoolsd file. My script i use to run in ignition is

`#!/bin/sh

          # Check to see if vmtools is where we expect it
          [ -x /usr/bin/vmtoolsd ] || {
                echo -e "[ ${colour_red}FAIL${colour_nc} ]ovfconf: VMWare Tools was not found.  Exiting..."
                exit 1
          }

          #pull values
          var_dhcp=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.interface.0.dhcp' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_dns0=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.dns.server.1' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_dns1=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.dns.server.0' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_fqdn=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.hostname' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_ipaddress=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.interface.0.ip.0.address' |  awk -F"value=" '{print $2}' | awk '{print substr($0,1,length()-2)}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_defaultgw=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.interface.0.route.0.gateway' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`

          #ignore case-sensitivity
          var_dhcp=${var_dhcp,,}

          #set up networking
          if [ "$var_dhcp" == "no" ]
          then

          sudo hostnamectl set-hostname $var_fqdn
          sudo touch /etc/NetworkManager/system-connections/ens192.nmconnection
          sudo cat << EOS > /etc/NetworkManager/system-connections/ens192.nmconnection
          [connection]
          type=ethernet
          id=Wired Connection
          interface-name=ens192

          [ipv4]
          method=manual
          addresses=$var_ipaddress
          gateway=$var_defaultgw
          dns=$var_dns0;$var_dns1

          [ipv6]
          method=ignore
          EOS

          elif [ "$var_dhcp" == "yes" ]
          then

          sudo touch /etc/NetworkManager/system-connections/ens192.nmconnection
          sudo cat << EOS > /etc/NetworkManager/system-connections/ens192.nmconnection
          [connection]
          type=ethernet
          id=Wired Connection
          interface-name=ens192

          [ipv4]
          method=auto

          [ipv6]
          method=ignore
          EOS

          else
          echo "Network Creation error!"

          fi

          sudo systemctl restart NetworkManager.service

          exit 0
`
When the machine boots up, I dont get any ipv4 ip just a auto-generated ipv6 ip

Another method I tried was using `nmcli`

`          #!/bin/sh

          # Check to see if vmtools is where we expect it
          [ -x /usr/bin/vmtoolsd ] || {
                echo -e "[ ${colour_red}FAIL${colour_nc} ]ovfconf: VMWare Tools was not found.  Exiting..."
                exit 1
          }

          #pull values
          var_dhcp=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.interface.0.dhcp' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_dns0=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.dns.server.1' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_dns1=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.dns.server.0' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_fqdn=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.hostname' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_ipaddress=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.interface.0.ip.0.address' |  awk -F"value=" '{print $2}' | awk '{print substr($0,1,length()-2)}' | awk '{print substr($0, 2, length($0) - 2)}'`
          var_defaultgw=`/usr/bin/vmtoolsd --cmd="info-get guestinfo.ovfEnv" | grep 'guestinfo.interface.0.route.0.gateway' |  awk -F"value=" '{print $2}' | awk -F "/" '{print $1}' | awk '{print substr($0, 2, length($0) - 2)}'`

          var_dhcp=${var_dhcp,,}

          #set up networking
          if [ "$var_dhcp" == "no" ]
          then

          sudo nmcli general hostname $var_fqdn
          sudo nmcli connection modify ens192 ipv4.addresses "$var_ipaddress"
          sudo nmcli connection modify ens192 ipv4.gateway "$var_defaultgw"
          sudo nmcli connection modify ens192 ipv4.dns "$var_dns0 $var_dns1"
          sudo nmcli connection modify ens192 ipv4.method manual
          sudo nmcli connection modify ens192 ipv6.method ignore
          sudo nmcli connection modify ens192 connection.autoconnect yes

          elif [ "$var_dhcp" == "yes" ]
          then

          sudo nmcli connection modify ens192 ipv4.method auto
          sudo nmcli connection modify ens192 ipv6.method ignore
          sudo nmcli connection modify ens192 connection.autoconnect yes

          else

          echo "Network Creation error!"

          fi

          sudo systemctl restart NetworkManager.service

          exit 0
`

What is the proper way to inject Network settings into FCOS?

Thanks

**Comment by bgilbert** [comment]
`vmtoolsd` is not shipped in Fedora CoreOS.  If you want to configure static networking via VMware guestinfo variables, see [here](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-vmware/#_first_boot_networking_and_ignition).
