### ISSUE TITLE
Dkms creates wrong simlinks for previous kernel

### ISSUE THREAD

**Issue by enigma131** [coreos/fedora-coreos-tracker#618]
I've build Dkms in Fedora I've used before under Ubuntu for my DVB cards.

Fedora use weak-updates for previous kernel module loading, and this contains wrong simlinks to the newest Kernel module instead the relevant kernel module.

Example, I got update to kernel 5.8 today. The module for kernel 5.8 works , but i have, as example for previous kernel : 
ls -l /lib/modules/**5.7.17-200.fc32.x86_64**/weak-updates
lrwxrwxrwx. 1 root root   54  4 sept. 10:21 stb0899.ko.xz -> /lib/modules/**5.8.4-200.fc32.x86_64**/extra/stb0899.ko.xz
instead:
lrwxrwxrwx. 1 root root   54  4 sept. 10:21 stb0899.ko.xz -> /lib/modules/**5.7.17-200.fc32.x86_64**/extra/stb0899.ko.xz (module is in correct place but wrong simlink)

So when i boot to previous kernel, modules loading fails .
I know i can manually change the simlinks of each line at each kernel update, but this is not the purpose of dkms ,isen't it ?

Can you correct the dkms routine ?

**Comment by lucab** [comment]
Hi @enigma131, thanks for the report. Can you please post the output of `rpm-ostree status` on your system?

**Comment by enigma131** [comment]
Fist i had to install the packet rpm-ostree, then : 
rpm-ostree status
error: This system was not booted via libostree; cannot operate

**Comment by lucab** [comment]
@enigma131 I see. Then I believe you just installed some version of Fedora and hitting a bug with that.
This issue tracker is only relevant for **Fedora CoreOS**, so I'm closing this ticket.
To report a bug against Fedora in general, see https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/.

**Comment by enigma131** [comment]
Ok thanks, I've posted there !
