### ISSUE TITLE
Move rpmdb backend from bdb to sqlite

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#623]
For at least the first f33 release (and possibly a few more), we're going to stick with bdb as the rpmdb backend to minimize rebase disruptions on nodes with layered packages (see https://github.com/coreos/fedora-coreos-tracker/issues/609#issuecomment-688977962).

This ticket tracks moving FCOS to sqlite to match the rest of Fedora.

**Comment by dustymabe** [comment]
@jlebon - is the first half of this (freezing on bdb) already in place in FCOS?

**Comment by jlebon** [comment]
We just need to make sure that whenever cosa moves to f33, it's using rpm-ostree v2020.5. Since that's [in f33](https://bodhi.fedoraproject.org/updates/FEDORA-2020-0f1c4e8bae) now, that should be the case. I opened https://github.com/coreos/fedora-coreos-config/pull/629 as a failsafe in case something goes wrong.

**Comment by pmatilai** [comment]
> For at least the first f33 release (and possibly a few more), we're going to stick with bdb as the rpmdb backend 

I don't know how coreos release model works, but just so it's clear to everybody: Fedora 34 will not have BDB at all, so there's an actual deadline for this. Rpm will continue to have read-only support for BDB though, so you'll be able to convert a pre-existing BDB rpmdb to a supported format.

**Comment by travier** [comment]
Yes, I think the goal is to switch the rpmdb backend during the F33 cycle, just not on the first release.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/795 will fix this for FCOS.
https://github.com/coreos/rpm-ostree/pull/2408 will fix it in f34 for everything else.
