### ISSUE TITLE
Add basic monitoring tools to the base image

### ISSUE THREAD

**Issue by rtsisyk** [coreos/fedora-coreos-tracker#628]
It would be nice to have some extra command-line monitoring tools in the base image.
My favourite list is:

```
rpm-ostree install \
    strace \
    nc \
    telnet \
    tcpdump \
    atop \
    iotop \
    ioping \
    iftop \
    htop \
    iperf \
    sysstat \
    dmidecode \
    smartmontools \
    numactl \
    lshw \
    pciutils \
    ipmitool \
    vim-enhanced
```

Some items can be controversial, but let's agree on some necessary minimum. Yes, I understand that it is possible to run a privileged container with required tools, but these tools are really necessary on the host system for troubleshooting, especially on the bare metal.  AFAIK, all these packages consume less than 50Mb of space.

**Comment by dustymabe** [comment]
Thanks @rtsisyk. I added the meeting label so we'll discuss it in the next meeting (next Wednesday).

**Comment by jlebon** [comment]
Oh those, I think `strace` is a big one which could be worth shipping by default. It's easy to run in a `--pid=host` container, though it can help break the "debug bootstrapping problem". For comparison, note RHCOS does ship `strace`.

**Comment by rtsisyk** [comment]
I see that htop requires python, which [should not be included](https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#approach-towards-shipping-Python).

Without htop:

```
Transaction Summary
=========================================================================================================================
Install  51 Packages

Total download size: 23 M
Installed size: 83 M
```

Without vim-enhanced:

```
Install  46 Packages

Total download size: 14 M
Installed size: 50 M
```

**Comment by travier** [comment]
To prepare for the meeting, I would recommend that you give at least one use case per tool that would benefit with the tool being installed on the host rather than used from a container.

**Comment by dustymabe** [comment]
We discussed this in [last week's meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/IQBWA72NU3KK3AOJUZTNJXJF2RW63DUX/).

We started to discuss each tool individually, but then took a step back and decided to define a set of questions to answer when we propose adding new packages to the base layer.

```
* ACTION: we'll file a tracker ticket to come up with rough criteria
    for adding packages  (dustymabe, 17:28:12)
```

The tracker ticket was created by micah at: https://github.com/coreos/fedora-coreos-tracker/issues/641

**Comment by dustymabe** [comment]
hey @rtsisyk do you mind creating a new ticket for each item you'd like to include in the host? We have a new issue template that you can select for proposing a new package for inclusion. The issue template has a lot of questions. Some will be relevant, some might not be. Either way, more information helps us make a decision about the qualifications of each package. Recently we [went through this exercise](https://github.com/coreos/fedora-coreos-tracker/issues/622#issuecomment-713890925) with `kexec-tools`.
