### ISSUE TITLE
Support for changing timezone

### ISSUE THREAD

**Issue by rtsisyk** [coreos/fedora-coreos-tracker#629]
According to https://access.redhat.com/solutions/4994241:

> Is changing timezone of RHCOS and OpenShift pods supported?
> No, it's not supported as they are designed to run with UTC timezone. Changing timezone of RHCOS or OpenShift system pods is not tested by Red Hat.

Getting log messaage with proper timezone is important for operations. Why guys from, say, Australia should see UTC timezone?

I propose to add support for changing timezone via DHCP. DHCP has [option 101](https://tools.ietf.org/html/rfc4833) which can be used to link /etc/localtime to a proper file. Minor changes are required to DHCP hooks.

Any thoughts?

**Comment by rtsisyk** [comment]
> Independent of the DHCP issue, you can always use an Ignition config to change /etc/localtime.

Yeah, I will try this way. I already have too many patches via ignition to get basic things work.
What is about [adding a hook to NetworkManager](https://github.com/coreos/fedora-coreos-config/pull/412) to fix this problem? 
I probably can try make a patch, but let's discuss this approach first.

**Comment by dustymabe** [comment]
> Yeah, I will try this way. I already have too many patches via ignition to get basic things work.
> What is about [adding a hook to NetworkManager](https://github.com/coreos/fedora-coreos-config/pull/412) to fix this problem?
> I probably can try make a patch, but let's discuss this approach first.

This might be better to discuss with the NetworkManager community directly, as it would benefit all users of NetworkManager, not just FCOS. They have an [issue tracker](https://gitlab.freedesktop.org/NetworkManager/NetworkManager) and a [mailing list](https://mail.gnome.org/mailman/listinfo/networkmanager-list).

**Comment by dustymabe** [comment]
Closing this out. Please discuss the feature request with NetworkManager upstream.
