### ISSUE TITLE
How to make docker-compose working fedora core-os?

### ISSUE THREAD

**Issue by mukul-c2fo** [coreos/fedora-coreos-tracker#632]
How to make docker-compose working fedora core-os and how to install it?

**Comment by lucab** [comment]
Thanks for asking, that's quite a broad question, see some previous discussion at https://github.com/coreos/fedora-coreos-tracker/issues/565.
In general, on FCOS most software does not come as part of the OS and should be run in a container (permission and SELinux policy may need to be tweaked first).
I'm going to close this ticket as it isn't a bug that affect any OS-shipped component.
For further discussions, we do have a forum at https://discussion.fedoraproject.org/c/server/coreos/5 where other users may  (or may not) have tackled the same workload and have tips to share.
