### ISSUE TITLE
afterburn: openstack images not pulling SSH keys from metadata service

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#633]
Originally reported over in https://github.com/coreos/fedora-coreos-tracker/issues/612#issuecomment-698922886

We didn't have the sshkeys service enabled on the openstack platform, which means that afterburn wouldn't pick up ssh keys from the metadata server.

Fixed in https://github.com/coreos/afterburn/pull/493.

**Comment by dustymabe** [comment]
patch backport: https://src.fedoraproject.org/rpms/rust-afterburn/pull-request/8

**Comment by bgilbert** [comment]
f-c-c PRs:
https://github.com/coreos/fedora-coreos-config/pull/688
https://github.com/coreos/fedora-coreos-config/pull/689

**Comment by bgilbert** [comment]
This should be fixed in next week's `next` and `testing` releases.

**Comment by dustymabe** [comment]
This looks to be taken care of now:

```
[core@f3 ~]$ cat /proc/cmdline | tr ' ' '\n' | grep platform
ignition.platform.id=openstack
[core@f3 ~]$ rpm-ostree status 
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 32.20201018.2.0 (2020-10-19T16:41:09Z)
                    Commit: 202e702598617005407c0aecf049be5a5387d69cb53e823de6d53413d052ee91
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
[core@f3 ~]$ find .ssh/authorized_keys.d/
.ssh/authorized_keys.d/
.ssh/authorized_keys.d/afterburn
```

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `32.20201018.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into next stream release `33.20201020.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `32.20201018.3.0`.
