### ISSUE TITLE
podman: fcos 32.20200907.3.0 update breaks disable cgroups feature

### ISSUE THREAD

**Issue by zyclonite** [coreos/fedora-coreos-tracker#634]
after upgrading from `32.20200824` to `32.20200907` all our systemd managed podman containers failed
we are using the `--cgroup disabled` option to enable systemd to satisfy all configured unit dependencies to guarantee a graceful shutdown

example unit file
```
        [Unit]
        Description=Hello World Container
        After=network-online.target
        Wants=network.target

        [Service]
        Environment=PODMAN_SYSTEMD_UNIT=%n
        TimeoutStartSec=0
        Restart=on-failure
        ExecStartPre=/bin/podman rm -i -f %N
        ExecStartPre=/usr/bin/rm -f %t/%N.pid
        ExecStart=/bin/podman run --name %N --conmon-pidfile %t/%N.pid --cgroups disabled --log-driver journald --pull always -d -q hello-world
        ExecStop=/bin/podman stop -i -t 10 %N
        ExecStopPost=-/bin/podman image prune -f
        PIDFile=%t/%N.pid
        KillMode=none
        Type=forking

        [Install]
        WantedBy=multi-user.target
```

the service failed with the following error
`podman[]: Error: requested OCI runtime runc is not compatible with NoCgroups: invalid argument`

after some research we found that in the new fcos version the `/usr/share/containers/libpod.conf` was gone, so podman falls back to `runc` as oci runtime but only `crun` does support disabling cgroups

as a workaround we upgraded all nodes to serve `/etc/containers/libpod.conf` containing
```
runtime = "crun"
```

was this on purpose and what's the strategy for future releases?

**Comment by bgilbert** [comment]
I assume you mean 32.20200907.3.0?

**Comment by zyclonite** [comment]
yes, stable branch but the .x.y had the same issue

**Comment by dustymabe** [comment]
Note: This was carried forward from the discussion at https://github.com/coreos/fedora-coreos-tracker/issues/575#issuecomment-698178892

**Comment by travier** [comment]
Upstream commit removed this file from the podman RPM in: https://src.fedoraproject.org/rpms/podman/c/c691e9f?branch=f32
Maybe we should ask the podman team about that?

**Comment by giuseppe** [comment]
I think the reason for that change is to dynamically find out the OCI runtime, where it is runc on cgroup v1 and crun on cgroup v2. 

If that is causing problem, we could probably reconsider it.

Is cgroup v1 used because of Kubernetes?

CC @rhatdan

**Comment by dustymabe** [comment]
We're using cgroups v1 in FCOS for now to give the container ecosystem (other than podman) some time to catch up. Hopefully we'll be switching for Fedora 34.

**Comment by zyclonite** [comment]
as long as there are both runtimes packaged we can configure crun. currently i do not see any other option to make systemd keep control of the container processes (especially for during shutdown)

**Comment by dustymabe** [comment]
Yep, we have no intention of removing `crun`. Sorry the underlying change in podman caused issues here and thanks for raising awareness so others will be able to fix it as well.

Is there anything else we should do as part of this?

**Comment by zyclonite** [comment]
from my perspective we can close this issue, i have not yet investigated how cgroups v2 will work together with systemd and podman units... but i guess that will not happen before fedora 34

**Comment by dustymabe** [comment]
thanks @zyclonite - yep we intend to start going down that path soon. Will close this out for now.
