### ISSUE TITLE
fcos 32.20200907.3.0 no longer be install from pxe

### ISSUE THREAD

**Issue by lfarkas** [coreos/fedora-coreos-tracker#638]
until now we use the version 32.20200629.3.0 for pxe install all of our coreos (both virtual and bare matel) machines. and of course if we install this version it's update itself to the latest 32.20200907.3.0 version.
after we update our local mirror images to 32.20200907.3.0 it's no longer install and i can't find the reason. but i can attach what i see in the console of the virt-manager when it's stop.
and not it's not the rootfs kernel parameter since i update it to the recommended way ie: add to file to the initrd parameter.

![Screenshot from 2020-09-29 16-36-30](https://user-images.githubusercontent.com/959957/94573609-8c66b280-0272-11eb-9223-639eff15ccb8.png)

**Comment by lucab** [comment]
> and not it's not the rootfs kernel parameter since i update it to the recommended way ie: add to file to the initrd parameter.

Thanks for the report and for mentioning this, it would have been my first suggestion too.

To inspect what's going on, can you please share the whole PXE configuration?
Assuming you have an input mechanism for this node console, can you please continue into the maintenance console and check the output `journalctl` to see if there are any hints of what is failing in the initramfs?

**Comment by lfarkas** [comment]
this is the pxe config in both case (just replace the fedora-coreos-live-kernel-x86_64, fedora-coreos-live-initramfs.x86_64.img, fedora-coreos-live-rootfs.x86_64.img symlink to the given version):
```
label fedora-coreos-virt
	menu label Fe^dora CoreOS Virt
	kernel CoreOS/fedora-coreos-live-kernel-x86_64
	append initrd=CoreOS/fedora-coreos-live-initramfs.x86_64.img coreos.inst.platform_id=qemu coreos.inst.install_dev=/dev/vda coreos.inst.ignition_url=ftp://192.168.209.1/download/vidux/tftpboot/bios/pxelinux.cfg/vidux.ign ip=dhcp rd.neednet=1 console=tty0 console=ttyS0
#	append initrd=CoreOS/fedora-coreos-live-initramfs.x86_64.img,CoreOS/fedora-coreos-live-rootfs.x86_64.img coreos.inst.platform_id=qemu coreos.inst.install_dev=/dev/vda coreos.inst.ignition_url=ftp://192.168.209.1/download/vidux/tftpboot/bios/pxelinux.cfg/vidux.ign ip=dhcp rd.neednet=1 console=tty0 console=ttyS0
```
this is full journalctl
[journalctl.txt](https://github.com/coreos/fedora-coreos-tracker/files/5300281/journalctl.txt)

**Comment by lucab** [comment]
@lfarkas thanks for both. It looks like the install flow is failing on
```
coreos-installer-service[759]: coreos-installer install /dev/vda --ignition-url ftp://192.168.209.1/download/vidux/tftpboot/bios/pxelinux.cfg/vidux.ign --insecure-ignition --firstboot-args rd.neednet=1 ip=dhcp  --platform qemu
coreos-installer-service[779]: Error: parsing arguments
coreos-installer-service[779]: Caused by: unknown protocol for URL 'ftp://192.168.209.1/download/vidux/tftpboot/bios/pxelinux.cfg/vidux.ign'
```
which indeed matched the PXE entry:
```
coreos.inst.ignition_url=ftp://192.168.209.1/download/vidux/tftpboot/bios/pxelinux.cfg/vidux.ign
```

I think this another incarnation of https://github.com/coreos/coreos-installer/issues/381, see the answer there for more details.

/cc @bgilbert on whether he wants to keep/move/close/document this one.

**Comment by bgilbert** [comment]
Yup, this has the same cause as https://github.com/coreos/coreos-installer/issues/381.  The situation is slightly different, though: FTP is supported by neither coreos-installer nor Ignition and there are no plans to add support.  Given that, I'll close this issue.  Can you move your Ignition config to an HTTP or HTTPS server instead?

**Comment by lfarkas** [comment]
this was working in 32.20200629.3.0! so it's strange that it's not working here. on the other hand http redirect also not working:-(

**Comment by bgilbert** [comment]
It worked unintentionally until https://github.com/coreos/coreos-installer/commit/1659e126e918505e1e9184b96b7824c10e2d8d7e.

If you're seeing issues with HTTP redirects, could you file a new bug?  I just tried a redirected Ignition config here and it seems to be working for me.
