### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by mskarbek** [coreos/fedora-coreos-tracker#64]
FAH ships "slightly" modified version based on Docker 1.13.1, CL follows Docker CE and currently delivers 18.06.1. AFAIR it was mentioned during one of the meetings that FCOS will ship both options (correct me if I'm wrong), the question is which one will be the default one?
The difference is significant - 11 API releases:
  - Docker 1.13.1 - API v1.26
  - Docker CE 18.06.1 - API v1.37

**Comment by dustymabe** [comment]
We think for docker* software we will default to the [moby-engine package](https://apps.fedoraproject.org/packages/moby-engine), which is based on newer upstream versions and is not heavily patched for special functionality. There will also be podman, which will have the patches that make things function better in the Fedora/Red Hat ecosystem.

**Comment by dustymabe** [comment]
> @dustymabe in Podman, those aren't extra patches, but part of the canonical source, right?

Right. I was just trying to say that the "extra functionality" will still be around, just in podman (i.e. in the source code) and not in moby-engine (as patches).

**Comment by mskarbek** [comment]
Ok, that simplifies few things. :P

**Comment by dustymabe** [comment]
moby engine has been merged into the fedora coreos configs in https://github.com/coreos/fedora-coreos-config/pull/26 so I'm going to close this.
