### ISSUE TITLE
accessibility of /boot/efi

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-tracker#640]
Splitting this from https://github.com/coreos/bootupd/pull/48#discussion_r497607504

Today:
```
$ rpm -q efi-filesystem
efi-filesystem-4-4.fc32.noarch
$ rpm -qlv efi-filesystem
drwx------    2 root     root                        0 Jan 28  2020 /boot/efi
drwxr-xr-x    2 root     root                        0 Jan 28  2020 /boot/efi/EFI
drwx------    2 root     root                        0 Jan 28  2020 /boot/efi/EFI/BOOT
drwx------    2 root     root                        0 Jan 28  2020 /boot/efi/EFI/fedora
```

I also verified that an unprivileged user can't `ls -al /boot/efi` on Fedora (traditional) Workstation 32.

Yet on FCOS:
```
[core@cosa-devsh ~]$ ls -al /boot/efi/EFI/
total 22
drwxr-xr-x. 4 root root  2048 Sep 23 08:21 .
drwxr-xr-x. 3 root root 16384 Jan  1  1970 ..
drwxr-xr-x. 2 root root  2048 Sep 23 08:21 BOOT
drwxr-xr-x. 3 root root  2048 Sep 23 08:21 fedora
```

We weren't paying attention to perms in https://github.com/coreos/coreos-assembler/blob/master/src/create_disk.sh before, nor are we currently with bootupd.

Perhaps we should be `0700 `in all of these directories.  (Though if the toplevel `/boot/efi` is `0700` then most of the other perms don't matter)  

AFAICS those perms came in with https://src.fedoraproject.org/rpms/efi-rpm-macros/c/4d38fc38961a39f6109eb6b5897c6c5a406b436e though there's no rationale for `0700` in the commit or comments in the code.

As far as I know there's not any private/secret data there.

**Comment by cgwalters** [comment]
(Tangential: I discovered `virt-install --os`, e.g. `virt-install --boot uefi --vcpus 4 --memory 4096 --connect qemu:///system --install os=debian9 --unattended=admin-password-file=/tmp/pw,profile=jeos`)

`/boot/efi` is also `0700` on Debian 9 at least.

**Comment by bgilbert** [comment]
There's no point in putting restrictive perms on packaged content.  Is there likely to be any machine-specific data in those directories?

**Comment by cgwalters** [comment]
> There's no point in putting restrictive perms on packaged content.

Agree.  (tangent: I love the libguestfs message about this)

>  Is there likely to be any machine-specific data in those directories?

But yes...I think in a dual boot scenario there could be arbitrary things in there, potentially machine specific or private.  This isn't quite a CoreOS concern because we don't (explicitly) support dual-boot and assume we can create+own the ESP.

I asked @vathpela about this via chat, and also briefly tried to figure out what creates/manages `/boot/efi` on Debian and where its source code is (I didn't succeed).

I lean towards matching and making it `0700` just on general principle.

**Comment by vathpela** [comment]
In general, initramfs can have secrets in it (isns/iscsi auth tokens and the like). All the while, FAT's permissions are junk in various ways, so we normally make sure the mountpoint is 0700 and mount the fs with "fmask=0077,dmask=0077" to avoid something unexpected going wrong just because the filesystem is weird.

**Comment by cgwalters** [comment]
> In general, initramfs can have secrets in it (isns/iscsi auth tokens and the like). 

(Somewhat tangential) Right, though...does anyone put the initramfs on the ESP?  We don't in Fedora (neither yum-based nor rpm-ostree) right?  I guess maybe sd-boot and some custom setups that do things like roll the kernel/initrd together into a blob for SB signing and maybe put that on the ESP.  rpm-ostree today always makes the initramfs `0700` for this reason anyways but I don't think rpm-ostree would work sanely if you tried to put the kernel/initramfs on the ESP.

Anyways OK seems like we have consensus so l'll fix our mount generator.
