### ISSUE TITLE
Template/questionnaire for requesting packages to base OS

### ISSUE THREAD

**Issue by miabbott** [coreos/fedora-coreos-tracker#641]
Based on the output of the community meeting discussion around #628, it seems like we could benefit from a template or questionnaire that can be filled out when users have a request to add a package to the base OS.

Different questions/considerations will have different weights, but let's spitball a list of things to ask:

- Can the package be run from a container?
- Can the tool be helpful in debugging container runtime issues?
- Can the tool be helpful in debugging networking issues?
- Is it possible to layer the package onto the base OS as a day 2 operation?
- Does the package have additional dependencies?  (i.e. does it drag in Python, Perl, etc)
- What is the size of the package and its dependencies?
- Can the packaging be adjusted to just deliver binaries?
- What is the intended use case of the package?
- Can the tool be used to do things we’d rather users not be able to do in FCOS? (E.g. can it be abused as a Turing complete interpreter?)
- Does the tool have a history of CVEs?

**Comment by miabbott** [comment]
Oops, missed the HackMD with some additional questions - https://hackmd.io/3LlGUzYjT-C3sbkIDBquKQ

**Comment by travier** [comment]
Looks like this could be an issue template but our current template seems to be outdated: https://github.com/coreos/fedora-coreos-tracker/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by bgilbert** [comment]
@travier We intentionally use the old-style template so its contents are pre-filled directly into the form, rather than sending users through the [chooser flow](https://github.com/coreos/ignition/issues/new/choose).  I think it'd make sense to change that, though, and to have "Add a package to the OS" as a separate bug-reporting option.

**Comment by jlebon** [comment]
> Oops, missed the HackMD with some additional questions - hackmd.io/3LlGUzYjT-C3sbkIDBquKQ

I merged the remaining ones into the first comment.
