### ISSUE TITLE
F33: ext.config.root-reprovision* tests failing

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#644]
These tests are failing in the Fedora 33 rebase (coreos/fedora-coreos-config#640). We'll disable the tests for now to unblock.

@jlebon has done some preliminary investigation over in: https://github.com/coreos/fedora-coreos-config/pull/640#issuecomment-703751994

**Comment by jlebon** [comment]
Fix for this in https://github.com/coreos/fedora-coreos-config/pull/685.

**Comment by dustymabe** [comment]
The fix for this went into next stream release `33.20201020.1.0`. Please try out the new release and report issues.
