### ISSUE TITLE
next: Promtail Journald Log Shipping Not Working (Likely Promtail Issue)

### ISSUE THREAD

**Issue by fifofonix** [coreos/fedora-coreos-tracker#651]
The promtail agent, responsible for log shipping to GrafanaLab's Loki, running as a podman systemd unit, does not work on 'next' when scraping journald.  This is probably a promtail issue but I'm posting here for awareness.

In our development cluster only canary nodes on next have been affected.  To eliminate various possibilities we've wiped and re-deployed Loki and promtail configuring nodes to monitor a dummy local log file.  All nodes successfully ship logs to Loki via (i) Docker Loki plugin, (ii) Promtail in-container dummy log file.  All pre-next nodes successfully ship journald via Promtail podman container but 'next' nodes do not.

No debug logging (for journald) is produced on the promtail agent or on ingestion with loki on the problematic nodes, which would seem to indicate that promtail is somehow not even noticing journald changes.  Exec'ing into promtail container shows journal files with up to date timestamps.  No SELinux permissioning issues noticed in host journald and issue recreated even when SELinux is made permissive.

Are we expecting any changes on journald processing with Fedora33?

ostree://fedora:fedora/x86_64/coreos/next
                   Version: 33.20201020.1.0 (2020-10-21T13:53:58Z)
                    Commit: 70e72166e506df1218609128eedb5e169c63bdd5d5f1ac43dd7530525c8e1f36
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31

ostree://fedora:fedora/x86_64/coreos/next
                   Version: 33.20201006.1.0 (2020-10-07T17:48:23Z)
                    Commit: 13a9eedf16110c6b7b52cbd384bc8ad34501a8ee7fb2b9141d3cc64263f611ce
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31

**Comment by lucab** [comment]
@fifofonix Thanks for the heads up. When did this start happening on `next`? The initial F33 bump in `33.20201006.1.0` contains both a kernel, systemd, and container runtime bumps which could have a role here.

**Comment by lucab** [comment]
I also noticed that `promtail` container [image](https://github.com/grafana/loki/blob/v1.6.1/cmd/promtail/Dockerfile#L11) is based on  Debian "Stretch", which is quite ancient at this point.

As journal reading logic relies on the `libsystemd` .so in the running environment, a desync in supported journal format may have happened (e.g. compression method).
It would be interesting to try the exact same `promtail` binary with a newer base image (possibly F33 or Debian testing) or directly on the host to see if that works.

**Comment by fifofonix** [comment]
@lucab I think this started occuring on the first F33 bump on 'next' but I didn't immediately notice, and it has taken time to eliminate various potential issues on our side before reporting.  The theory you advance above makes sense and at this point I'm going to relay as a probable issue in promtail project.  In terms of workflow not sure whether I should have raised this in this forum given that it isn't likely a FCOS issue?

**Comment by lucab** [comment]
> In terms of workflow not sure whether I should have raised this in this forum given that it isn't likely a FCOS issue?

No worries, we appreciate heads up even if in the end there is no actionable outcome on our side.

In this case it would be good to confirm what was the first version affected on the `next` channel, and note down `systemctl --version` flags from working and non-working environments (host and containers). That should also help Grafana people pinning down their compatibility matrix.

**Comment by fifofonix** [comment]
Non-working and working `systemctl -version` (required `apt-get install systemd` in promtail containers)

Non-working Host View
```
systemd 246 (v246.6-3.fc33)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

Non-Working Container View
```
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

Working Host View:
```
systemd 245 (v245.8-2.fc32)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

Working Container View:
```
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by lucab** [comment]
Diffing the feature flags, it looks like on-host `v246.6-3.fc33` gained a `+ZSTD` entry for zstd support which in-container `232` does not know about.

**Comment by dustymabe** [comment]
@fifofonix can you work with the upstream provider of the container to try to update the components inside the container to be compatible?

**Comment by fifofonix** [comment]
@dustymabe I'll re-double my efforts!

**Comment by dustymabe** [comment]
@fifofonix I didn't realize you were already working upstream in https://github.com/grafana/loki/issues/2792. Thanks!

Another idea is you could try to configure the journal to maybe not use compression on the host side and see if that at least unblocks you. Something like:

```
cat /etc/systemd/journald.conf.d/nocompress.conf
[Journal]
Compress=no
```

**Comment by fifofonix** [comment]
Thanks @dustymabe but surprisingly, to me, but I am seriously over my skis at this point, this does not resolve the issue.

**Comment by fifofonix** [comment]
@dustymabe as per my notes in upstream issue it is possible to build a working version of promtail for 'next' from source.  How this is to be fixed properly in the project itself is still up for debate but at least this is no longer a blocker for me.

**Comment by fifofonix** [comment]
Changed description to note that as expected with f33 now in testing this issue will be experienced on nodes following that stream.  The upstream issue is getting more attention as it affects more platforms and a developer has claimed it so hopefully a more robust solution will be forthcoming shortly.

**Comment by dustymabe** [comment]
@fifofonix - do you want to try to the workaround linked to from https://github.com/grafana/loki/issues/2792#issuecomment-727865943? 

https://github.com/systemd/systemd/blob/9101cd1a239ce916a1f339f6a74d20bb33610228/NEWS#L971-L979

**Comment by fifofonix** [comment]
@dustymabe I'm using the workaround that I documented upstream thanks to yours and @jlebon's help.  I'm just keeping this thread up to date in case others come across the problem.

**Comment by dustymabe** [comment]
Looks like this is [fixed upstream](https://github.com/grafana/loki/issues/2792#event-4033564159) now. Thanks for the report and keeping this up to date. I'll close.
