### ISSUE TITLE
Fedora Test day for our `next` stream (Fedora 33)

### ISSUE THREAD

**Issue by sumantro93** [coreos/fedora-coreos-tracker#659]
We'll want to have a CoreOS test day for F33. This involves figuring out important changes in F33 FCOS ''next'' stream. Testers may submit results anytime between 2020-11-06 and 2020-11-12.
The focus will be 

- Bugs not caught by the CI
- Documentations
- Raise Awareness about Fedora CoreOS

xref: [Fedora QA ticket](https://pagure.io/fedora-qa/issue/656)

**Comment by dustymabe** [comment]
Please review the test cases on [the results page](https://testdays.fedorainfracloud.org/events/98) to see if there is anything missing or anything we need to add!

**Comment by dustymabe** [comment]
@jlebon found #664 during test day

**Comment by dustymabe** [comment]
@lucab and I found https://github.com/coreos/fedora-coreos-tracker/issues/668 during test day

**Comment by dustymabe** [comment]
We had over 25 people come out and participate in our test day! Thanks to everyone who participated and everyone who has been running `next` and helping us find issues along the way!
