### ISSUE TITLE
[next] Found ordering cycle on systemd-machine-id-commit.service/start

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#660]
**Describe the bug**
Ordering cycle reported by systemd on bootup.

**Reproduction steps**
1. Boot the latest Next FCOS release (33.20201101.1.0).

**System details**
 - QEMU
 - Fedora CoreOS version: Next release 33.20201101.1.0

**Ignition config**
Default COSA config.

**Additional information**

```
Nov 04 13:59:35 fedora systemd[1]: sysinit.target: Found ordering cycle on systemd-machine-id-commit.service/start
Nov 04 13:59:35 fedora systemd[1]: sysinit.target: Found dependency on coreos-update-ca-trust.service/start
Nov 04 13:59:35 fedora systemd[1]: sysinit.target: Found dependency on sysinit.target/start
Nov 04 13:59:36 fedora systemd[1]: Starting Apply Kernel Variables...
Nov 04 13:59:35 fedora systemd[1]: sysinit.target: Job systemd-machine-id-commit.service/start deleted to break ordering cycle starting with sysinit.target/start
Nov 04 13:59:35 fedora systemd[1]: Queued start job for default target Multi-User System.
```

I can provide the full journal log for this boot if needed.

**Comment by jlebon** [comment]
Ahh yes, OK this is likely fallout from https://github.com/coreos/fedora-coreos-config/pull/699. Investigating.

**Comment by dustymabe** [comment]
Is this in `testing` too? If so, is it worth an ad-hoc release to fix?

**Comment by jlebon** [comment]
Fix in https://github.com/coreos/fedora-coreos-config/pull/723.

> Is this in `testing` too? If so, is it worth an ad-hoc release to fix?

Yes to both questions. :) Otherwise if `systemd-machine-id-commit.service` doesn't run on first boot, services with `ConditionFirstBoot=true` will run again on the second boot.

We already released `testing` and `next` but haven't updated any metadata yet, so users haven't been exposed to this yet (and it doesn't really matter for users who force upgrade since this is a firstboot issue). So we can just do another release.

**Comment by dustymabe** [comment]
> So we can just do another release.

🙏

**Comment by dustymabe** [comment]
> We already released `testing` and `next` but haven't updated any metadata yet, so users haven't been exposed to this yet (the OSTree is out, but it doesn't really matter for users who force upgrade since this is a firstboot issue).

The `haven't updated any metadata yet` isn't quite accurate because the webiste shows the new releases (people grabbing it from there (or tracking latest in GCP via image family) will start an instance with the firstboot issue). Am I understanding correctly?

**Comment by jlebon** [comment]
> The haven't updated any metadata yet isn't quite accurate because the webiste shows the new releases (people grabbing it from there (or tracking latest in GCP via image family) will start an instance with the firstboot issue). Am I understanding correctly?

It's in the releases we just built, but not in the previous releases. We haven't updated the stream metadata yet for this round so it's not showing on the website yet. Good point about the GCP family though, that one happens in the release job so it was updated.

**Comment by dustymabe** [comment]
> We haven't updated the stream metadata yet for this round so it's not showing on the website yet.

Ah.. This is what was confusing me. The release notes page shows the release but if you click over to downloads it doesn't. 

![Screenshot_2020-11-04 Get Fedora](https://user-images.githubusercontent.com/4530030/98132826-d6067680-1e8a-11eb-98a9-dfb86cae8933.png)

**Comment by dustymabe** [comment]
> Good point about the GCP family though, that one happens in the release job so it was updated.

OK I fixed it for now:

```
[coreos-assembler]$ ore gcloud promote-image --log-level=INFO --project=fedora-coreos-cloud --json-key /srv/gcpcreds --family fedora-coreos-next --image fedora-coreos-33-20201020-1-0-gcp-x86-64
2020-11-04T15:58:58Z cli: Started logging at level INFO
2020-11-04T15:58:58Z ore/gce: Attempting to promote fedora-coreos-33-20201020-1-0-gcp-x86-64 in family fedora-coreos-next
2020-11-04T15:58:58Z ore/gce: Changing deprecation state of image: fedora-coreos-33-20201020-1-0-gcp-x86-64 -> ACTIVE
2020-11-04T15:58:59Z ore/gce: Changing deprecation state of image: fedora-coreos-33-20201101-1-0-gcp-x86-64 -> DEPRECATED

[coreos-assembler]$ ore gcloud promote-image --log-level=INFO --project=fedora-coreos-cloud --json-key /srv/gcpcreds --family fedora-coreos-testing --image fedora-coreos-32-20201018-2-0-gcp-x86-64
2020-11-04T16:00:23Z cli: Started logging at level INFO
2020-11-04T16:00:23Z ore/gce: Attempting to promote fedora-coreos-32-20201018-2-0-gcp-x86-64 in family fedora-coreos-testing
2020-11-04T16:00:23Z ore/gce: Changing deprecation state of image: fedora-coreos-32-20201018-2-0-gcp-x86-64 -> ACTIVE
2020-11-04T16:00:24Z ore/gce: Changing deprecation state of image: fedora-coreos-32-20201101-2-0-gcp-x86-64 -> DEPRECATED
```

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `32.20201104.2.0`. Please try out the new release and report issues.
