### ISSUE TITLE
Need a bigger FCOS image for IPI OKD deployment

### ISSUE THREAD

**Issue by hroyrh** [coreos/fedora-coreos-tracker#670]
**Describe the bug**
When doing IPI deployment of OKD using dev-scripts, we are using the *fcos* branch of the openshift-installer and the bootstrap VM used as part of it has 8G total disk space which seems to be insufficient. The bootstrap VM for OCP installer has 16G size and we don't see any issues while deploying it.

**Reproduction steps**
1. Switch to FCOS branch of openshift-installer, and use other upstream images wherever available for OKD deployment using dev-scripts
2. When you reach the Bootstraping phase and waiting for hosts to come up, login to the bootstrap VM
3.  Check the journal logs for Ironic service, and it will complain about - no space found while creating a container

**Expected behavior**
The space in the bootstrap VM should be sufficient for the deployment.

**Actual behavior**
The bootstrap VM runs out of space and the disk is full right after it boots and comes online.

**System details**
 - okd deployment with dev-scripts using libvirt vms running on Bmetal host
 - fedora-coreos-32.20201004.3.0

**Ignition config**
Not available

**Additional information**

**Comment by cgwalters** [comment]
The "make the default disk bigger" game will never end.  Instead we have a sane default, and most consumers we'd expect will resize it.

In this case for OKD, https://github.com/openshift/installer/pull/4364
