### ISSUE TITLE
Add checklist template for implementing a new platform

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#675]
@jlebon in https://github.com/coreos/fedora-coreos-tracker/pull/672:

> A follow-up to this would be to have a checklist for actually implementing support for it (e.g. see checklist in https://github.com/coreos/fedora-coreos-tracker/issues/355#issue-556377201). Depending on what's actually required though some of those checkboxes might not apply (e.g. if the platform reuses an existing artifact, and we just need to upload it to the cloud).

This isn't a type of issue that users would file directly, so we should probably create the template without YAML front matter to keep it out of the chooser, and link to it from developer documentation instead ([example](https://github.com/coreos/ignition/blob/master/docs/development.md#releasing-ignition)).

**Comment by dustymabe** [comment]
@sohankunkerkar - since you added the label, did you want to work on this?

**Comment by sohankunkerkar** [comment]
> @sohankunkerkar - since you added the label, did you want to work on this?

Sorry for the late reply. Presently, I'm not working on it, so feel free to assign it someone else

**Comment by prestist** [comment]
https://github.com/coreos/fedora-coreos-tracker/pull/1170 Done
