### ISSUE TITLE
Actually move iptables to the nft backend

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#676]
In Fedora 32, Fedora moved the backend of `iptables` to use the nft implementation by default (see [the change proposal](https://fedoraproject.org/wiki/Changes/iptables-nft-default). In #26 we decided to ship all the tools and accept the Fedora defaults.

Unfortunately, applying the default of `iptables-nft` in Fedora 32 didn't work on FCOS because it was implemented via alternatives and alternatives don't currently work with the way `rpm-ostree` composes the OS (see https://github.com/coreos/fedora-coreos-tracker/issues/677).

Now that we know we're misconfigured, let's figure out how to move to get back in line with Fedora's defaults while we wait on alternatives to get fixed (probably won't happen til Fedora 34).

There were some previous musings about this (before the f32 change landed) in https://github.com/coreos/fedora-coreos-tracker/issues/342.

Rolling out:
- [ ] wait until scheduled migration date for `next-devel` (when rebasing to f36)
- [ ] merge https://github.com/coreos/fedora-coreos-config/pull/1324
- [ ] wait until the new overlay dir is propagated to `next-devel`
- [ ] rebase and merge https://github.com/coreos/fedora-coreos-config/pull/1460
- [ ] send email ([draft](https://hackmd.io/P07lJugyTciC_rkj8v4-8w))
- [ ] cut `next` release, possibly making it a barrier
- [ ] revert `35coreos-iptables` inclusion in `next-devel`'s `manifest.yaml` (second commit in https://github.com/coreos/fedora-coreos-config/pull/1460)
- [ ] wait until scheduled migration date for `testing-devel` (when rebasing to f36)
- [ ] lower iptables-nft postprocess into a shared manifest into `testing-devel` and out of `next-devel`'s `manifest.yaml` (first commit in https://github.com/coreos/fedora-coreos-config/pull/1460)
- [ ] add `35coreos-iptables` inclusion to `testing-devel`'s `manifest.yaml`
- [ ] cut `testing` release, cherry-picking `35coreos-iptables` inclusion to its `manifest.yaml`, and possibly making it a barrier
- [ ] revert `35coreos-iptables` inclusion to `testing-devel` and `testing`
- [ ] cut `stable` release, cherry-picking `35coreos-iptables` inclusion to its `manifest.yaml`, and possibly making it a barrier
- [ ] revert `35coreos-iptables` inclusion to `stable`

**Comment by dustymabe** [comment]
One proposal:

1. leave existing systems on the old implementation (similar to the way the Fedora Change intended)
2. group the switch to `iptables-nft` into the f33 rebase on the `stable` stream (would need to go through `testing` first)

Either way let's discuss it in next week's meeting to see what the most appropriate path forward is.

**Comment by dustymabe** [comment]
cc @nullr0ute for awareness - since this likely affects IoT

**Comment by jlebon** [comment]
I think conceptually we want the default in the OSTree commit to be nft, and have upgraded systems therefore carry a delta in their `/etc` for staying on legacy. This is tricky to do though because the symlinks are managed by OSTree itself, so as soon as we change the commit, upgrading nodes will inherit the change.

Hmm, I think to implement this we'd need two barrier releases:
- do a first barrier release with a systemd service which marks a stamp file at e.g. `/var/lib/iptables-nft.stamp` if the machine is already using the nft backend
- in a second barrier release
    - we add a postprocess script that does `ln -sf` as needed to link `/etc/alternatives/iptables` to `/usr/sbin/iptables-nft` (and similarly for the related symlinks) -- once `alternatives` becomes OSTree-compatible, that postprocess script should no longer be necessary
    - we add a systemd service in the initramfs which determines whether to keep with the new default (nft), or revert back to legacy
        - if it's the first boot, then do nothing (we want freshly booted machines to use nft)
        - if `/sysroot/var/lib/iptables-nft.stamp` is present, then delete the stamp file and do nothing (we want upgrading machines which previously used nft to stay on nft)
        - if the symlinks are already different from nft, then do nothing (we don't want to touch upgrading machines which previously somehow used neither nft nor legacy, just to be safe)
        - otherwise, revert the `/etc` symlinks back to legacy; this will mark the symlinks as modified as per `ostree admin config-diff`

**Comment by jlebon** [comment]
Another approach which requires user action is a single barrier where we add a service which optionally sets the backend to legacy if some stamp file in `/var` is present. Then we inform users that if no action is taken, their nodes will be moved to `iptables-nft`. Otherwise, they can touch that stamp file before `$release_date`. This is more aggressive, though is much simpler in implementation. (I personally lean towards this).

**Comment by dustymabe** [comment]
> * do a first barrier release with a systemd service which marks a stamp file at e.g. `/var/lib/iptables-nft.stamp` if the machine is already using the nft backend

Could we get away with doing just one barrier release if we just take a peak at what's in the rollback deployment's /etc/ to determine if it was using nft already or not?

**Comment by jlebon** [comment]
> Could we get away with doing just one barrier release if we just take a peak at what's in the rollback deployment's /etc/ to determine if it was using nft already or not?

Hmm, I think that would work in 99% of cases, but it's not entirely foolproof, because there are no guarantees about correspondence between "previous deployment" and "rollback deployment" (what's considered the rollback is more a convention based on deployment ordering) and whether it still exists.

**Comment by jlebon** [comment]
This was discussed in [the community meeting today](https://meetbot.fedoraproject.org/fedora-meeting-1/2020-11-25/fedora_coreos_meeting.2020-11-25-16.30.html):

> AGREED: we will stay with the legacy backend for now while we pursue a fixed alternatives for OSTree systems. meanwhile, we will document how users can move to the nft backend

**Comment by travier** [comment]
Upstream issue for easier reference: https://github.com/fedora-sysv/chkconfig/issues/9

**Comment by cgwalters** [comment]
If we switch the default to nft, do we then document+support a way to stay on legacy for new systems too?  It'd probably make sense because we need to carry most of that logic for previous systems too, but it is a different case.

**Comment by ibotty** [comment]
Without having anything to say: why support legacy iptables at all?  AFAICT there are more bugs in legacy iptables and many features get easier with nft.  Most people would not notice anyway.

Isn't current RHEL and RHCOS also on nft?  I don't see a reason for legacy iptables.

**Comment by nullr0ute** [comment]
> cc @nullr0ute for awareness - since this likely affects IoT

We actually use firewalld, as opposed to an iptables based static firewall, and it defaults to the nft backend so I'm not sure how much this applies by default to IoT. Thanks for the heads up, let me know if I've missed something.

**Comment by dustymabe** [comment]
If people who know much more about this than me tell me that switching the nft on an upgrade is a relatively safe thing to do then we could consider that option. Keep in mind that FCOS auto-updates, so the goal is to not break people's systems that are updating themselves. Do we have a high degree of confidence that iptables-nft is a safe upgrade?

/me wonders why the rpm doesn't just default to it now instead of relying on updating priorities via alternatives in %post scriptlets.

**Comment by dghubble** [comment]
Host iptables legacy vs nft has been a pain point in Kubernetes-land for years, with much of the ecosystem hanging back on legacy. kube-proxy should [detect](https://github.com/kubernetes/release/blob/master/images/build/debian-iptables/buster/iptables-wrapper#L29) the mode in theory. Other network-related apps, components, or tools need to be prepared as well (e.g. CNIs). I'd have a healthy fear on this topic.

**Comment by champtar** [comment]
Not all CNI autodetect, and they might not autodetect by default.
Also k8s-dns-node-cache support autodetection only since 1.16.0 / nov 16 (https://github.com/kubernetes/dns/pull/367)
You can today run with iptables-nft, but switching automatically will break some prod :)

**Comment by jlebon** [comment]
So if we want to err on the side of caution and not auto-migrate systems on legacy but only affect new nodes, that takes us back to something like https://github.com/coreos/fedora-coreos-tracker/issues/676#issuecomment-732514979.

**Comment by jlebon** [comment]
We discussed this in the community meeting today. @lucab was concerned about increasing the support matrix yet again if we just migrate new nodes.

One proposal is to split migration into two phases:
- migrate new nodes
- declare iptables-legacy in a deprecation period and provide instructions on how to migrate (possibly with doc links for e.g. additional OKD/k8s-specific instructions)
- wait X months
- force migrate old nodes
- no longer consider iptables-legacy supported

**Comment by jlebon** [comment]
Let's discuss this (hopefully for the last time) in this week's community meeting to see if the proposal at https://github.com/coreos/fedora-coreos-tracker/issues/676#issuecomment-824225675 sounds good to everyone. I'm thinking we should try to target f35 GA for the first part of having new nodes come up on nft.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/QCJDYZR26SFCF5UKNSEOUWI5F7A5QNS4/).

```
13:04:44*   dustymabe | #agreed Talk with typhoon about proposed migration. The proposed migration is: 1.
                      | declare iptables-legacy in a deprecation period 2. allow people to opt out of
                      | automigration 3. wait 3 months 4. force migrate old and new nodes

```

**Comment by jlebon** [comment]
@dghubble Does the above make sense to you? Is Typhoon planning to stick to legacy for upgrading clusters only, or even for new clusters? We're thinking this is a sane approach, but it may require Typhoon to actively touch the stamp file if it wants to stay on legacy on upgrading nodes. Are you in a position to easily do that?

@champtar Re.

>  You can today run with iptables-nft, but switching automatically will break some prod :)

When you say switching automatically will break things, does that include if the switch is done from the initramfs? (I.e. before anything actually has had a chance to start up yet.) IOW, is this about keeping the iptables legacy vs nft state of a node the same across its lifetime, or only within a single boot?

**Comment by champtar** [comment]
> @champtar Re.
> 
> > You can today run with iptables-nft, but switching automatically will break some prod :)
> 
> When you say switching automatically will break things, does that include if the switch is done from the initramfs? (I.e. before anything actually has had a chance to start up yet.) IOW, is this about keeping the iptables legacy vs nft state of a node the same across its lifetime, or only within a single boot?

For example Calico can be forced to legacy, nft or auto-detect, if it's set to legacy next reboot will break things. Pretty easy to fix once you know it. I don't have another example than the CNI in mind.

**Comment by dghubble** [comment]
@jlebon From FCOS I'd need a way to try options, run it in real world scenarios. If cluster changes are needed to switch to nft, I'd want to add something now to block current users' nodes (lacking those future changes) from auto-upgrading into having nft. There are too many components both within Kubernetes and running atop Kubernetes for me to know all the cascading issues with confidence before then.

**Comment by dghubble** [comment]
I see comments its usable now, is there some Ignition snippet for enabling nft?

**Comment by dustymabe** [comment]
I think if you want to test our nft backed iptables today you can just update the symlink.. currently today:

```
[core@weevm ~]$ ls -l /usr/sbin/iptables
lrwxrwxrwx. 3 root root 26 Jun 28 15:46 /usr/sbin/iptables -> /etc/alternatives/iptables
[core@weevm ~]$ ls -l /etc/alternatives/iptables
lrwxrwxrwx. 1 root root 25 Sep 28 10:44 /etc/alternatives/iptables -> /usr/sbin/iptables-legacy
```

So you just need to update the link to be `/etc/alternatives/iptables -> /usr/sbin/iptables-nft`.

Though, assuming for now that Typhoon would want to stay on legacy iptables would you be able to create a stamp file via a typhoon update somehow  to indicate to FCOS that it wants to stay on legacy iptables?

**Comment by dustymabe** [comment]
> I see comments its usable now, is there some Ignition snippet for enabling nft?

I found this on my filesystem (from a previous lifetime):

```
variant: fcos
version: 1.2.0
storage:
  links:
    - path: /etc/alternatives/iptables
      target: /usr/sbin/iptables-nft
      overwrite: true
      hard: false
    - path: /etc/alternatives/iptables-restore
      target: /usr/sbin/iptables-nft-restore
      overwrite: true
      hard: false
    - path: /etc/alternatives/iptables-save
      target: /usr/sbin/iptables-nft-save
      overwrite: true
      hard: false
    - path: /etc/alternatives/ip6tables
      target: /usr/sbin/ip6tables-nft
      overwrite: true
      hard: false
    - path: /etc/alternatives/ip6tables-restore
      target: /usr/sbin/ip6tables-nft-restore
      overwrite: true
      hard: false
    - path: /etc/alternatives/ip6tables-save
      target: /usr/sbin/ip6tables-nft-save
      overwrite: true
      hard: false
```

I suspect it still works.

**Comment by dghubble** [comment]
What's the "stamp file" approach you're suggesting?

**Comment by dghubble** [comment]
Alright, how about something like `/etc/fedora-coreos/iptables-legacy.stamp` to mark nodes now https://github.com/poseidon/typhoon/pull/1051. It does look like cluster configuration changes will be needed to prepare for iptables-nft.

**Comment by travier** [comment]
Current doc about this issue: https://docs.fedoraproject.org/en-US/fedora-coreos/alternatives/

**Comment by dustymabe** [comment]
> @dghubble
> Alright, how about something like `/etc/fedora-coreos/iptables-legacy.stamp` to mark nodes

We haven't quite finalized the stamp file location just yet. I think there may be some issue with using `/etc/` for this. Will update here when we've decided.

> @travier 
> Current doc about this issue: https://docs.fedoraproject.org/en-US/fedora-coreos/alternatives/

Thanks! I forgot we had added this to the docs.

**Comment by jlebon** [comment]
> Any potential rollback issues with using `/etc/` ?

I think rollbacks should work fine. `rpm-ostree rollback` doesn't do any etc merging, it just changes the boot order, so it should preserve what's in `/etc` as is (both the stamp file and how iptables is configured). `rpm-ostree deploy <older version>` will do an etc merge, so there it'll indeed carry the stamp file if it exists. But by design, it should be harmless on older versions which still used legacy. Let me know if you're thinking of a different scenario.

**Comment by jlebon** [comment]
Migration to iptables-nft in https://github.com/coreos/fedora-coreos-config/pull/1324. How do we want to announce the migration window? coreos-status email?

**Comment by dustymabe** [comment]
>  How do we want to announce the migration window? coreos-status email?

seems reasonable. I wonder if we should have a "notices" section in our docs as well with links to status post emails and maybe even reproduced text. It would be nice to consolidate them in a single place.

**Comment by jlebon** [comment]
Email draft in https://hackmd.io/P07lJugyTciC_rkj8v4-8w

**Comment by travier** [comment]
> Email draft in https://hackmd.io/P07lJugyTciC_rkj8v4-8w

LGTM

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/E47SUSGIWAUP77HK2SOVDJQRT7HPAH4E/).

```
11:44:13         dustymabe | #agreed To make it easier to understand and easier to rollout we will
                           | couple the conversion to iptables-nft with the rebase to F36. This
                           | means the notice period window will be shorter than initially
                           | discussed.
```

**Comment by jlebon** [comment]
Email: https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/message/UHVBNXDIDMFEFFXCY73CVJPFY4NYAJJZ/

**Comment by jdbarnes-isi** [comment]
Looking forward to the release that has this default. Will it be in whatever is after `Stable v 35.20220131.3.0` ? Is it already in `Testing v 35.20220213.2.0`?

**Comment by dustymabe** [comment]
It will be when the rebase to Fedora Linux 36 happens. See [the email](https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/message/UHVBNXDIDMFEFFXCY73CVJPFY4NYAJJZ/) Jonathan sent out.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220505.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `36.20220505.3.2`.
