### ISSUE TITLE
Make ISO images UEFI bootable

### ISSUE THREAD

**Issue by bjencks** [coreos/fedora-coreos-tracker#678]
My environment doesn't support non-UEFI boot, so the ISO images aren't usable as-is. The Isohybrid page describes how to do this:
https://wiki.syslinux.org/wiki/index.php?title=Isohybrid#UEFI

Alternatively, if you want to support secure boot, you can look at how upstream Fedora makes their images.

**Comment by bgilbert** [comment]
The ISO images are UEFI-bootable, and we test that in CI.  What problem are you seeing?

**Comment by bjencks** [comment]
Whoops, sorry about that. My boot configuration was apparently just broken. I'll be sure to repro in a VM next time.
