### ISSUE TITLE
kola run_upgrade failure

### ISSUE THREAD

**Issue by bh7cw** [coreos/fedora-coreos-tracker#686]
kola run_upgrade fails in cosa continuous-integration/jenkins/pr-merge due to:
```
--- FAIL: fcos.upgrade.basic/upgrade-from-previous (2.40s)

basic.go:332: failed to find 'zincati_update_agent_updates_enabled 1' on Zincati metrics.promsock
```

See details: 
[1] https://github.com/coreos/coreos-assembler/pull/1908
[2] https://github.com/coreos/coreos-assembler/blob/25517479417b3e42a0b8240110984a938006ac2f/mantle/kola/tests/upgrade/basic.go#L332

**Comment by lucab** [comment]
I did a check on latest `testing-devel`, Zincati seems fine and after manually enabling updates the metrics output seems ok too:
```
$ sudo socat - UNIX-CONNECT:/run/zincati/public/metrics.promsock | grep enabled 

# HELP zincati_update_agent_updates_enabled Whether auto-updates logic is enabled.
# TYPE zincati_update_agent_updates_enabled gauge
zincati_update_agent_updates_enabled 1
```

This is probably something that has gone wrong on the test setup.

**Comment by lucab** [comment]
It looks like other run successfully completed afterwards, so this may have been a flake. I've re-triggered Jenkins there to confirm.

**Comment by bh7cw** [comment]
It did work. Thank you! @lucab

**Comment by dustymabe** [comment]
Seeing this at least [one more time](https://jenkins-coreos-ci.apps.ocp.ci.centos.org/blue/organizations/jenkins/github-ci%2Fcoreos%2Ffedora-coreos-config/detail/PR-694/24/pipeline/57):

```
=== RUN   fcos.upgrade.basic
=== RUN   fcos.upgrade.basic/setup
=== RUN   fcos.upgrade.basic/upgrade-from-previous
=== RUN   fcos.upgrade.basic/upgrade-from-current
--- FAIL: fcos.upgrade.basic (642.60s)
    --- PASS: fcos.upgrade.basic/setup (86.27s)
    --- PASS: fcos.upgrade.basic/upgrade-from-previous (328.71s)
    --- FAIL: fcos.upgrade.basic/upgrade-from-current (23.34s)
            basic.go:332: failed to find 'zincati_update_agent_updates_enabled 1' on Zincati metrics.promsock

```

**Comment by jlebon** [comment]
The relevant code here is:

```go
		c.MustSSH(m, "sudo systemctl start zincati.service")

		// sanity-check that Zincati has updates enabled
		metrics := getZincatiMetrics(c, m)
		if !strings.Contains(metrics, "zincati_update_agent_updates_enabled 1") {
			c.Fatalf("failed to find 'zincati_update_agent_updates_enabled 1' on Zincati metrics.promsock")
		}
```

@lucab Is it possible that we're racing between Zincati starting up and it exposing the metrics on the socket? Should Zincati use `sd_notify` to make sure it waits until it's fully up? (Related https://github.com/coreos/zincati/issues/94).

**Comment by lucab** [comment]
@jlebon Hmm, I think that the race is because this specific `updates_enabled` metrics is only set [later on](https://github.com/coreos/zincati/blob/v0.0.14/src/update_agent/actor.rs#L35) when the actor starts. This is generally not a problem for Prometheus as it stays in an "unset" state until it re-appears, but the test does not know about this tri-state semantics.

I can move it to be set earlier in Zincati, but it would be good to also update the test to retry if the required metrics is not present in the output yet.

**Comment by lucab** [comment]
The Zincati side of this is https://github.com/coreos/zincati/issues/420.

**Comment by lucab** [comment]
A tentative improvement for this is at https://github.com/coreos/coreos-assembler/pull/1933, totally untested though.
