### ISSUE TITLE
azure: boot issues due to missing networking in initramfs

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-tracker#689]
I was trying booting a custom FCOS image in Azure and saw this on the serial console:

```
[   73.342818] afterburn[543]: Dec 02 15:22:14.000 INFO Fetching http://168.63.129.16/?comp=versions: Attempt #9
[   73.355681] afterburn[543]: Dec 02 15:22:14.013 INFO Failed to fetch: error sending request for url (http://168.63.129.16/?comp=versions): error trying to connect: tcp connect error: Network is unreachable (os error 101)
```

Apparently when we moved to optional networking in initramfs we broke plain Azure booting, as the Ignition configuration is coming from a config-drive but other pieces (e.g. hostname and boot check-in from Afterburn) needs to reach the metadata endpoint and the wireserver over the network.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `33.20201214.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `33.20201214.3.1`.
