### ISSUE TITLE
no cloud agents: packet

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#69]
In #12 we decided that we'd like to try to not ship cloud agents. This ticket will document investigation and strategy for shipping without a cloud agent on the **packet bare metal cloud platform**.

See also #41 for a discussion of how to ship cloud specific bits using ignition.

**Comment by bgilbert** [comment]
Packet doesn't have an agent.  The instance does need to report successful boot, but that only requires a [single HTTP POST](https://github.com/coreos/coreos-overlay/blob/1a846fbe914bed4583d02cc322ff011821d2fa8d/coreos-base/oem-packet/files/units/packet-phone-home.service).

**Comment by bgilbert** [comment]
One other caveat: a machine's public IPv4 address is available via DHCP, but its private IPv4 and public IPv6 addresses are only available from the Packet metadata server.  coreos-metadata [handles that now](https://github.com/coreos/coreos-metadata/blob/c2f8bc468c7b157ceea0c5fe2e389da9ef28ae0b/src/providers/packet/mod.rs).

**Comment by dustymabe** [comment]
thanks @bgilbert for the info. So the single gap we have here is that we need to send out an HTTP POST on successful boot ? Should we create an Action Item for that? Do we need to do anything complicated like integrate with greenboot and only send out the HTTP POST on successful boot according to greenboot.

**Comment by bgilbert** [comment]
It appears that the necessary work is:

- https://github.com/coreos/coreos-metadata/issues/120
- https://github.com/coreos/fedora-coreos-tracker/issues/110
- https://github.com/coreos/fedora-coreos-tracker/issues/111

Will PR the design doc.

**Comment by vielmetti** [comment]
Thanks for tackling this @bgilbert . Let me know if there are any gaps you see on the Packet side, and alert me when the design doc is ready to look at.

**Comment by vielmetti** [comment]
Several accounts were added to the Fedora CoreOS project at Packet; details at https://github.com/WorksOnArm/cluster/issues/110 . Happy to report back any progress, success, or challenges you have seen.

**Comment by dustymabe** [comment]
design doc PR: https://github.com/coreos/fedora-coreos-tracker/pull/130

**Comment by bgilbert** [comment]
On Container Linux on Packet, the `core` user is automatically logged in on the serial (SOS) console to ease troubleshooting.  Fedora CoreOS could do something similar.  Alternatively, we could automatically randomize the root password and pass it back to the Packet API, which would make it available for 24 hours (https://github.com/coreos/fedora-coreos-tracker/issues/110#issuecomment-454619647).

In general, we'd like to avoid automatically logging in on console by default (https://github.com/coreos/fedora-coreos-tracker/issues/114#issuecomment-457015273), and it seems inconsistent and surprising to automatically set a root password on only one platform.  So let's plan not to automatically enable any sort of credential access for the SOS console.  If users would like SOS access, they can use Ignition to enable autologin or to set a password on the `core` account; we'll document how to do that.

I've checked this plan with the Packet folks and they're okay with it.

**Comment by bgilbert** [comment]
New design doc PR in #133.
