### ISSUE TITLE
Error: invalid entry point PID of container fedora-toolbox-33

### ISSUE THREAD

**Issue by ziswiler** [coreos/fedora-coreos-tracker#693]
**Describe the bug**
While toolbox of stable stream works fine (albeit fedora-toolbox-32 in that case) it currently fails in testing stream.

**Reproduction steps**
1. toolbox enter
2.Error: invalid entry point PID of container fedora-toolbox-33

**Expected behavior**
Toolbox should successfully be entered.
⬢[user@toolbox user]$ 

**Actual behavior**
[user@host ~]$ toolbox enter
No toolbox containers found. Create now? [y/N] y
Image required to create toolbox container.
Download registry.fedoraproject.org/f33/fedora-toolbox:33 (500MB)? [y/N]: y
Error: invalid entry point PID of container fedora-toolbox-33

**System details**
 - Bare Metal running on an HPE ProLiant DL380 GEN8 server
 - Fedora CoreOS version
[user@host ~]$ rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 33.20201201.2.0 (2020-12-02T13:20:32Z)
                    Commit: 60a778505110e5bc4a4ed2b7925e9c0853147c39d25dcd2eaebf981c9e0a4a39
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31

**Ignition config**
It is NOT an ignition issue as stable tree works just fine.
[user@host ~]$ sudo rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 32.20201104.3.0 (2020-11-17T10:56:39Z)
                    Commit: 318de830c2f30a97333cd43aa1d500a46ccfedcb2de70a04d0c48228944346da
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
[user@host ~]$ toolbox enter
No toolbox containers found. Create now? [y/N] y
Image required to create toolbox container.
Download registry.fedoraproject.org/f32/fedora-toolbox:32 (500MB)? [y/N]: y
⬢[user@toolbox user]$ 

**Additional information**
Let me know what additional information may be required.

**Comment by lucab** [comment]
Thanks for the report. This looks like an upstream issue in `toolbox`, can you please report it directly to https://github.com/containers/toolbox. Also, does it work if run as root or via sudo?

**Comment by CBGameDev** [comment]
hello i had the same problem and the problem for me was no /etc/localtime file.
to check if you don`t have that file run "ls -l /etc/localtime" and 
see if you get 
ls: cannot access '/etc/localtime': No such file or directory

if you don`t have that file you will need to create one
use "timedatectl list-timezones" to list all the timezones
then run "sudo timedatectl set-timezone Europe/London" replace "Europe/London" with your timezone
then run "toolbox enter"

**Comment by HarryMichal** [comment]
Toolbox assumes `/etc/localtime` exists on the host system. It seems this assumption is wrong and we'll make Toolbox more resilient.

I'm wondering what triggers this situation, though. I'm not aware of being in a situation when `/etc/localtime` is not present on a machine (unless I was installing Arch Linux where I had to set it manually). Did something change in the configuration that caused this? I'm not very knowledgeable when it comes to systemd and all the fluff around it.

**Comment by lucab** [comment]
> I'm wondering what triggers this situation, though.

It's a combination of the following two things:
 * most FCOS nodes run in the default and recommended UTC timezone (i.e. no custom `/etc/localtime`).
 * FCOS does not run `systemd-firstboot(1)`, so the symlink for the `UTC` default case does not get generated.

Please note that a non-existing `/etc/localtime` is a legit case which is equivalent to `UTC`, see https://github.com/systemd/systemd/blob/v247/src/basic/time-util.c#L1460-L1469.

But I agree this isn't clearly spelled out in the [specs](https://www.freedesktop.org/software/systemd/man/localtime.html), so I've opened a PR to fix it: https://github.com/systemd/systemd/pull/18046

**Comment by CBGameDev** [comment]
i was using coreos. by default /etc/localtime doesn't exists and is required by toolbox. so if your using coreos. you will need to create the /etc/localtime file.

**Comment by debarshiray** [comment]
Yes, this was a regression in Toolbox 0.0.97 due to commit https://github.com/containers/toolbox/commit/b9a0bd5f0c2a2421ec15eea286ca20f03b7152d2

I think https://github.com/containers/toolbox/pull/656 should fix it. Some testing would be appreciated.

**Comment by travier** [comment]
Adding `/etc/localtime` does not work as workaround for me. I hit this on FCOS stable. Will check the fix on testing.

**Comment by debarshiray** [comment]
> Adding `/etc/localtime` does not work as workaround for me.

Did you add it as a symbolic link? The easiest way to do that might be to use something like `timedatectl set-timezone Europe/Prague`.

**Comment by HarryMichal** [comment]
Since version 0.0.98 Toolbox should not fail to enter a container when `/etc/localtime` is missing. I'd be in favor of closing this issue.

> Adding `/etc/localtime` does not work as workaround for me. I hit this on FCOS stable. Will check the fix on testing.

Are you sure it is the same issue? The `Error: invalid entry point PID of container fedora-toolbox-33` error is quite generic and signals the container did not start correctly. Try to start it with `podman start --attach fedora-toolbox-33`.

**Comment by travier** [comment]
So far I can not reproduce this issue on `33.20210201.3.0` with `toolbox version 0.0.99` so closing.

**Comment by debarshiray** [comment]
Great. Thanks @travier

**Comment by dilyevsky** [comment]
This definitely still happens:

```
$ ls -l /etc/localtime
lrwxrwxrwx. 1 root root 23 Mar 26 17:39 /etc/localtime -> /usr/share/zoneinfo/UTC
```

```
$ cat /etc/os-release |grep OSTREE_VERSION
OSTREE_VERSION='33.20210301.3.1'
```

```
$ toolbox enter -v
DEBU Running as real user ID 1001
DEBU Resolved absolute path to the executable as /usr/bin/toolbox
DEBU Running on a cgroups v1 host
DEBU Checking if /etc/subgid and /etc/subuid have entries for user dilyevsky
DEBU TOOLBOX_PATH is /usr/bin/toolbox
DEBU Toolbox config directory is /var/home/dilyevsky/.config/toolbox
DEBU Current Podman version is 3.0.1
DEBU Creating runtime directory /run/user/1001/toolbox
DEBU Old Podman version is 3.0.1
DEBU Migration not needed: Podman version 3.0.1 is unchanged
DEBU Resolving container and image names
DEBU Container: ''
DEBU Distribution: ''
DEBU Image: ''
DEBU Release: ''
DEBU Resolved container and image names
DEBU Container: 'fedora-toolbox-33'
DEBU Image: 'fedora-toolbox:33'
DEBU Release: '33'
DEBU Checking if container fedora-toolbox-33 exists
DEBU Inspecting mounts of container fedora-toolbox-33
DEBU Starting container fedora-toolbox-33
DEBU Inspecting entry point of container fedora-toolbox-33
DEBU Entry point PID is a float64
DEBU Entry point of container fedora-toolbox-33 is toolbox (PID=0)
Error: invalid entry point PID of container fedora-toolbox-33
```

```
$ sudo rm /etc/localtime
$ toolbox enter -v
DEBU Running as real user ID 1001
DEBU Resolved absolute path to the executable as /usr/bin/toolbox
DEBU Running on a cgroups v1 host
DEBU Checking if /etc/subgid and /etc/subuid have entries for user dilyevsky
DEBU TOOLBOX_PATH is /usr/bin/toolbox
DEBU Toolbox config directory is /var/home/dilyevsky/.config/toolbox
DEBU Current Podman version is 3.0.1
DEBU Creating runtime directory /run/user/1001/toolbox
DEBU Old Podman version is 3.0.1
DEBU Migration not needed: Podman version 3.0.1 is unchanged
DEBU Resolving container and image names
DEBU Container: ''
DEBU Distribution: ''
DEBU Image: ''
DEBU Release: ''
DEBU Resolved container and image names
DEBU Container: 'fedora-toolbox-33'
DEBU Image: 'fedora-toolbox:33'
DEBU Release: '33'
DEBU Checking if container fedora-toolbox-33 exists
DEBU Inspecting mounts of container fedora-toolbox-33
DEBU Starting container fedora-toolbox-33
DEBU Inspecting entry point of container fedora-toolbox-33
DEBU Entry point PID is a float64
DEBU Entry point of container fedora-toolbox-33 is toolbox (PID=4927)
DEBU Waiting for container fedora-toolbox-33 to finish initializing
DEBU Creating runtime directory /run/user/1001/toolbox
DEBU Checking if initialization stamp /run/user/1001/toolbox/container-initialized-4927 exists
DEBU Container fedora-toolbox-33 is initialized
DEBU Looking for command /bin/bash in container fedora-toolbox-33
DEBU Checking if 'podman exec' supports disabling the detach keys
DEBU 'podman exec' supports disabling the detach keys
DEBU Creating list of environment variables to forward
DEBU COLORTERM is unset
DEBU DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
DEBU DBUS_SYSTEM_BUS_ADDRESS is unset
DEBU DESKTOP_SESSION is unset
DEBU DISPLAY is unset
DEBU LANG=C.UTF-8
DEBU SHELL=/bin/bash
DEBU SSH_AUTH_SOCK is unset
DEBU TERM=xterm-256color
DEBU TOOLBOX_PATH=/usr/bin/toolbox
DEBU USER=dilyevsky
DEBU VTE_VERSION is unset
DEBU WAYLAND_DISPLAY is unset
DEBU XAUTHORITY is unset
DEBU XDG_CURRENT_DESKTOP is unset
DEBU XDG_DATA_DIRS is unset
DEBU XDG_MENU_PREFIX is unset
DEBU XDG_RUNTIME_DIR=/run/user/1001
DEBU XDG_SEAT is unset
DEBU XDG_SESSION_DESKTOP is unset
DEBU XDG_SESSION_ID=1
DEBU XDG_SESSION_TYPE=tty
DEBU XDG_VTNR is unset
DEBU Running in container fedora-toolbox-33:
DEBU podman
DEBU --log-level
DEBU error
DEBU exec
DEBU --detach-keys
DEBU
DEBU --interactive
DEBU --tty
DEBU --user
DEBU dilyevsky
DEBU --workdir
DEBU /var/home/dilyevsky
DEBU --env=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
DEBU --env=LANG=C.UTF-8
DEBU --env=SHELL=/bin/bash
DEBU --env=TERM=xterm-256color
DEBU --env=TOOLBOX_PATH=/usr/bin/toolbox
DEBU --env=USER=dilyevsky
DEBU --env=XDG_RUNTIME_DIR=/run/user/1001
DEBU --env=XDG_SESSION_ID=1
DEBU --env=XDG_SESSION_TYPE=tty
DEBU fedora-toolbox-33
DEBU capsh
DEBU --caps=
DEBU --
DEBU -c
DEBU exec "$@"
DEBU /bin/sh
DEBU /bin/bash
DEBU -l

Welcome to the Toolbox; a container where you can install and run
all your tools.

 - Use DNF in the usual manner to install command line tools.
 - To create a new tools container, run 'toolbox create'.

For more information, see the documentation.

⬢[dilyevsky@toolbox ~]$
```

**Comment by travier** [comment]
Looks like it's the reverse now, it fails if the symlink exists. You should be able to workaround that short term by removing it.

**Comment by ziswiler** [comment]
> Looks like it's the reverse now, it fails if the symlink exists. You should be able to workaround that short term by removing it.

Hm, that doesn't seem to cut it for me:

```
[user@host ~]$ toolbox create
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:33 (500MB)? [y/N]: y
Created container: fedora-toolbox-33
Enter with: toolbox enter
[user@host ~]$ toolbox enter
Error: invalid entry point PID of container fedora-toolbox-33
[user@host ~]$ ls -l /etc/localtime
lrwxrwxrwx. 1 root root 35 18. Mär 21:05 /etc/localtime -> ../usr/share/zoneinfo/Europe/London
[user@host ~]$ sudo rm /etc/localtime 
[user@host ~]$ toolbox enter
Error: invalid entry point PID of container fedora-toolbox-33
```

**Comment by dilyevsky** [comment]
Actually I realized this only happens when symlink is absolute (also see https://github.com/containers/toolbox/issues/622). It works on 0.99 if there is not /etc/localtime or if it's relative.

**Comment by dilyevsky** [comment]
Workaround I added to my ignition yaml:

```yaml
  links:
    - path: /etc/localtime
      target: ../usr/share/zoneinfo/UTC
      overwrite: true
      hard: false
```

**Comment by travier** [comment]
> Is there actually still hope to get toolbox working ever again?

We have toolbox tests in CI now so we're taking toolbox working on FCOS seriously.

I usually use `podman star xyz` and `podman exec -ti xyz` to get a full error and figure out toolbox issues.

> Actually I realized this only happens when symlink is absolute (also see containers/toolbox#622). It works on 0.99 if there is no /etc/localtime or if it's relative.

Closing again as this seems to be the solution.

**Comment by ziswiler** [comment]
> I usually use podman start xyz and podman exec -ti xyz to get a full error and figure out toolbox issues.

Unfortunately, that does not seem to work:

```
[user@host ~]$ podman start fedora-toolbox-33
fedora-toolbox-33
[user@host ~]$ podman exec -ti fedora-toolbox-33
Error: must provide a non-empty command to start an exec session: invalid argument
```

**Comment by travier** [comment]
`podman exec -ti fedora-toolbox-33 bash`

**Comment by travier** [comment]
Is this the same discussion/issue as https://github.com/coreos/fedora-coreos-tracker/issues/734? If yes, let's keep the discussion there.

**Comment by HarryMichal** [comment]
The most reliable way to get a startup log should be `podman start --attach <container>`.

**Comment by ziswiler** [comment]
> Can you try `podman exec -ti fedora-toolbox-33 bash`?

```
[zim@linuxdev ~]$ podman start fedora-toolbox-33
fedora-toolbox-33
[zim@linuxdev ~]$ podman exec -ti fedora-toolbox-33 bash
Error: can only create exec sessions on running containers: container state improper
```

**Comment by ziswiler** [comment]
> The most reliable way to get a startup log should be `podman start --attach <container>`.

Maybe it really has to do with that user/group ID stuff. But, again, that would just be a regression as that all used to work just fine.

```
[zim@linuxdev ~]$ podman start --attach fedora-toolbox-33
level=debug msg="Running as real user ID 0"
level=debug msg="Resolved absolute path to the executable as /usr/bin/toolbox"
level=debug msg="TOOLBOX_PATH is /usr/bin/toolbox"
level=debug msg="Creating /run/.toolboxenv"
level=debug msg="Monitoring host"
level=debug msg="Path /run/host/etc exists"
level=debug msg="Binding /etc/machine-id to /run/host/etc/machine-id"
level=debug msg="Creating /run/systemd/journal"
level=debug msg="Binding /run/systemd/journal to /run/host/run/systemd/journal"
level=debug msg="Creating /run/udev/data"
level=debug msg="Binding /run/udev/data to /run/host/run/udev/data"
level=debug msg="Creating /tmp"
level=debug msg="Binding /tmp to /run/host/tmp"
level=debug msg="Creating /var/lib/systemd/coredump"
level=debug msg="Binding /var/lib/systemd/coredump to /run/host/var/lib/systemd/coredump"
level=debug msg="Creating /var/log/journal"
level=debug msg="Binding /var/log/journal to /run/host/var/log/journal"
level=debug msg="Creating /var/mnt"
level=debug msg="Binding /var/mnt to /run/host/var/mnt"
level=debug msg="Creating /sys/fs/selinux"
level=debug msg="Binding /sys/fs/selinux to /usr/share/empty"
level=debug msg="Preparing to redirect /home to /var/home"
level=debug msg="/var/home isn't a symbolic link"
level=debug msg="Redirecting /home to /var/home"
level=debug msg="Looking up group for sudo"
level=debug msg="Group for sudo is wheel"
level=debug msg="Modifying user zim with UID 1001:"
level=debug msg=usermod
level=debug msg=--append
level=debug msg=--groups
level=debug msg=wheel
level=debug msg=--home
level=debug msg=/home/zim
level=debug msg=--shell
level=debug msg=/bin/bash
level=debug msg=--uid
level=debug msg=1001
level=debug msg=zim
level=debug msg="Removing password for user zim"
level=debug msg="Removing password for user root"
level=debug msg="Setting up daily ticker"
level=debug msg="Setting up watches for file system events"
level=debug msg="Finished initializing container"
level=debug msg="Creating runtime directory /run/user/1001/toolbox"
Error: failed to change ownership of the runtime directory /run/user/1001/toolbox: chown /run/user/1001/toolbox: operation not permitted
```

**Comment by ZhangChengX** [comment]
```
$ toolbox enter -v
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user zhangcheng 
DEBU Validating sub-ID file /etc/subuid           
DEBU Validating sub-ID file /etc/subgid           
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Migrating to newer Podman                    
DEBU Toolbox config directory is /home/zhangcheng/.config/toolbox 
DEBU Current Podman version is 3.4.4              
DEBU Creating runtime directory /run/user/1000/toolbox 
DEBU Old Podman version is 3.4.4                  
DEBU Migration not needed: Podman version 3.4.4 is unchanged 
DEBU Resolving container and image names          
DEBU Container: ''                                
DEBU Distribution: ''                             
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'fedora-toolbox-33'               
DEBU Image: 'fedora-toolbox:33'                   
DEBU Release: '33'                                
DEBU Checking if container fedora-toolbox-33 exists 
DEBU Inspecting mounts of container fedora-toolbox-33 
DEBU Starting container fedora-toolbox-33         
DEBU Inspecting entry point of container fedora-toolbox-33 
DEBU Entry point PID is a float64                 
DEBU Entry point of container fedora-toolbox-33 is toolbox (PID=0) 
Error: invalid entry point PID of container fedora-toolbox-33

$ podman start fedora-toolbox-33
fedora-toolbox-33

$ podman exec -ti fedora-toolbox-33 bash
Error: can only create exec sessions on running containers: container state improper

$ podman start --attach fedora-toolbox-33
toolbox: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by toolbox)
```

**Comment by dustymabe** [comment]
@ZhangChengX open a new issue if you have an issue with Fedora CoreOS. This is a 2 year old issue.

**Comment by ernstki** [comment]
@ZhangChengX's [post](https://github.com/coreos/fedora-coreos-tracker/issues/693#issuecomment-1724497017) wasn't off-topic, it just lacked context. And yes, I'm 100% with the CoreOS maintainers that this isn't their problem to fix.

Fact is, actively-supported distros using distro packages are still affected by this, and this issue ranks high in search engine results for this error message. Here I am with the same problem on Ubuntu 22.04, using `toolbox` 0.0.99.2 from the official repositories, which ships with the timezone-related patch from #634:

```console
$ toolbox enter
Error: invalid entry point PID of container fedora-toolbox-33

$ podman start --attach fedora-toolbox-33 
toolbox: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by toolbox)
```

The reason this happens is

* older `toolbox` distro packages still pull `fedora-toolbox-33` or `-34` by default when you run `toolbox create`
  * **these are [crazy out-of-date](https://en.wikipedia.org/wiki/Fedora_Linux_release_history#Release_history)** , but that's not obvious to people who don't keep up with Fedora releases
* this results in the host-container libc compatibility problem further discussed in [containers/toolbox #821](https://github.com/containers/toolbox/issues/821)
  * …because the `toolbox` binary is (for reasons I don't claim to understand) bind-mounted and set as the container's entrypoint[^fn1]

If your circumstances match what's described above, and you're still getting this error in 2026, the real answer is: **stop using `toolbox create`** without arguments. Instead, specify a contemporary Fedora release where the libc version is more likely to match your host system's, like this:

```console
me@myhost$ toolbox create -d fedora -r f43
Created container: fedora-toolbox-43
Enter with: toolbox enter --release 43

me@myhost:~$ toolbox enter -r 43
me@toolbox:~$ cat /etc/redhat-release 
Fedora release 43 (Forty Three)
```

…or explicitly specify a image, for distros that `toolbox` doesn't directly support:

```bash
toolbox create --image quay.io/toolbx-images/debian-toolbox:13
toolbox enter debian-toolbox-13
```

You needn't feel shame for using an older LTS distro, with packages from your distro's official repositories. Just prepare yourself for having to do workarounds like this, and report problems to the distro package maintainers [like somebody did here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014463) if a workaround can't be found.

[^fn1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014463#10
