### ISSUE TITLE
OS Fails to boot with ignition: systemd - Inappropriate ioctl for device

### ISSUE THREAD

**Issue by matteoiacovitti** [coreos/fedora-coreos-tracker#698]
**Describe the bug**
I cannot boot up Fedora Core with an ignition file. It keeps getting a kernel panic with this error:
![image](https://user-images.githubusercontent.com/25353683/101915774-15b03480-3b94-11eb-910e-9a71e79aa614.png)

**Reproduction steps**
1. Boot up fedora core for the first time
2. download my ignition file via http file server
3. run the command `coreos-installer install /dev/sda -i ignition.ign`
4. reboot

**Expected behavior**
I'm expecting the OS to boot up and set up my systemd and files correctly via ignition process

**Actual behavior**
The system halts and the above error appears
**System details**
The version I tested with was *32.20201104.3.0* But I also tried with:

- 32.20201004.3.0
- 32.20200907.3.0
- 33.20201130.1.0 (NEXT)

And also changed the ignition version to match the compatible version for each build

**Ignition config**
I tried booting up with just the bare minimum and I still get the error
```{
  "ignition": {
    "version": "3.1.0"
  }
}
```

**Additional information**
I have tried with the example in your docs where it's just the passwd node and it still crashes.

This was working without issues about 2 months ago and now all of a sudden it just crashes all the time.
It is worth to mention that I am using Packer to build the Virtual Machine, but packer is on hold when the fcos and ignition are being installed. Once the os is installed packer resumes opperations.

Anyone else getting this error?

**Comment by dustymabe** [comment]
- What does the output from `coreos-installer` show you?
- What is your full ignition config you're passing?
- There are probably messages on the serial console that you're not seeing. Try doing the install and running `coreos-installer` with the `--append-karg console=tty0` option to get that output to come to the VGA console.

**Comment by RyanMeulenkamp** [comment]
Same is happening for me. Just switched from flatcar. Tried both `stable`: `33.20201214.3.1` and `next`: `33.20210104.1.0`.

**Comment by bgilbert** [comment]
One likely explanation is that Ignition is failing for some reason, but the system is failing to drop to an emergency shell because FCOS sets the serial console to primary by default and you don't have a serial port.  If you delete `console=ttyS0,115200` from the kernel command line, you should be able to see the Ignition errors.

**Comment by RyanMeulenkamp** [comment]
Thanks. Turns out the problem was: `uid` `1000` was already in use by user `core`.

**Comment by CristinaAlonso1** [comment]
Hi!

I'm new in this world (_linux included..._) so it's hard to me to understand the resolution...

In my case, I have installed Openshift on my 3xmaster + 3xworkers cluster by using PXE.
Now (_with the same PXE menu and same ignition files_), I'm trying to add a 4th worker node to the cluster.
After updating all the relevant configurations (_dns, haproxy, dhcp, ..._), I launched the installation of my 4th node but I'm getting the exact same error posted here by **matteoiacovitti**.

In my case, I don't know how to apply that "**console=ttyS0, 115200**" as the installation is triggered from the same ignition file that worked perfectly fine for my 3 previous worker nodes.

On the other hand, I'm running "**journalctl -t ignition**", "**journalctl -xn**", "**journalctl -xe**" in my bastion node but I don't get anything relevant and related to my problem.

Any hint is more than super appreciated!
Thanks & regards.

**Comment by dustymabe** [comment]
@CristinaAlonso1 - welcome to FCOS (and linux). Do you mind opening a new issue and share the information above (as well as your PXE configuration) there?

**Comment by bgilbert** [comment]
The behavior described here is a symptom of another problem, perhaps an invalid Ignition config.  To get more details on the other problem, follow the instructions in https://github.com/coreos/fedora-coreos-tracker/issues/698#issuecomment-757162365.  Closing this out.

#567 should improve the UX here.
