### ISSUE TITLE
flesh out use cases for Fedora CoreOS

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#7]
We should flesh out use cases for Fedora CoreOS and develop some user stories so that we can define what we are providing and what we are not providing for users. This will help us stay focused and have defined reasoning for our decisions. 

Additionally defining how we expect users to interact with the OS will be key for success.

**Comment by jlebon** [comment]
For comparison, here's the Atomic PRD: https://fedoraproject.org/wiki/Atomic/PRD.

**Comment by dustymabe** [comment]
@bgilbert and I talked with the existing CL and Atomic Host teams and tried to gather some feedback to get an initial list of use cases for Fedora CoreOS. This is an initial list that should help us kickstart the discussion with the rest of the community:

### Primary Use Cases

The primary use cases of Fedora CoreOS are:

* Being a Clustered Server Node for Running Kubernetes/OpenShift Origin
* Being a Single Server Node for Running Containerized Applications

### Secondary Use Cases

The secondary use cases of Fedora CoreOS are:

* Clustered Server Node for Running non Kubernetes Container Orchestration Platforms

### Use Case Indifferent Goals

Fedora CoreOS is indifferent about the following use cases:

* IoT
* Fedora CoreOS as a Development Platform

### Use Case Anti-Goals

There are some Use Cases for which Fedora CoreOS should not be used. These are:

* Being a Host for Running Non-Containerized Applications
* Being a User Desktop


I took a stab at creating a [PRD](https://fedoraproject.org/wiki/CoreOS/PRD) with this content (along with more supporting words for each) in it. We can modify as we update these throughout the discussion.

**Comment by jberkus** [comment]
Is this a statement that running upstream Kubernetes is a targeted use-case?

**Comment by dustymabe** [comment]
>@jberkus
> Is this a statement that running upstream Kubernetes is a targeted use-case?

it is a proposed draft of a statement that would claim that, yes

**Comment by dustymabe** [comment]
in the [2018-07-25 meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/EEGMH6X5I7AYKE73NXXHCLBHA2ZFUYU3/) it was determined that we should better define what the various use case categories imply. Here is what we came up with in the meeting:

## Primary:
   - Primary use cases are factored into design decisions
   - Primary use cases are actively tested
   - Bugs that affect primary use cases are actively fixed
   - Supporting tools exist

## Secondary:
   - Secondary use cases are factored into design decisions
   - Secondary use cases may be tested (individuals or groups within the community may make stronger guarantees depending on the use case and technology used)
   - Bugs that affect secondary use cases are actively fixed,
     but may be low priority or handed to related upstreams

## Indifferent:
   - An attempt is made to not break these use cases if possible, unless they conflict with primary use cases.
   - No active testing is performed for these use cases.

## Anti Use Cases:
   - The working group explicitly asks users to not use Fedora CoreOS for these use cases.

**Comment by dustymabe** [comment]
Now that we have some definition of what primary vs secondary means we will circle back to the [proposed use cases](https://github.com/coreos/fedora-coreos-tracker/issues/7#issuecomment-407532435) in the next meeting.

**Comment by PaulCapestany** [comment]
FWIW, as an SRE one of the main things that appealed to me when I first discovered and started using CoreOS/Container Linux was the project’s stated focus—and approach—to security. If a similar security stance may still be an implicit goal of Fedora CoreOS, I figured I’d point out that I don’t think I came across anything in the PRD that specifically addressed the topic yet. Apologies if this wouldn’t be the correct place to expect this info or if it can be found elsewhere.

It’s great to see this repo and the PRD; as a happy user of CL I’ve been anxious to get more details on what the merger might look like. Definitely interested in following along with what might, or might not, be changing

**Comment by jasonbrooks** [comment]
+1 to these use cases -- we do need to discuss some specifics on the kube/origin cluster case, though. Like, do we include the bits in the image? How will the clusters be configured, etc.

**Comment by dustymabe** [comment]
Thanks all! 

I'll add the [defined categories](https://github.com/coreos/fedora-coreos-tracker/issues/7#issuecomment-408454966) and [use cases from above](https://github.com/coreos/fedora-coreos-tracker/issues/7#issuecomment-407532435) to the [PRD](https://fedoraproject.org/wiki/CoreOS/PRD) and propose the PRD to the working group in a separate mail/issue.

**Comment by dustymabe** [comment]
> I'll add the defined categories and use cases from above to the PRD and propose the PRD to the working group in a separate mail/issue.

Uploaded 2nd Draft of PRD: https://fedoraproject.org/wiki/CoreOS/PRD 

Sent [mail](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/3O3ZLEU733VEHBXTMIVXSA6RUNIVEUZ3/) to the list.
