### ISSUE TITLE
tracker: Fedora 34 rebase work

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#704]
This is still early, but I want us to start tracking Fedora 34 changes and evaluate which are relevant to FCOS.

Fedora 34 schedule:

```
# https://fedorapeople.org/groups/schedule/f-34/f-34-key-tasks.html
2020-12-29 Change Checkpoint: Proposal submission deadline (System Wide Changes)
2021-01-19 Change Checkpoint: Proposal submission deadline (Self Contained Changes)
2021-02-09 Branch Fedora 34 from Rawhide
2021-02-12 Post-branch Freeze (end date approximate)
2021-02-23 Bodhi updates-testing activation point
2021-03-16 Beta Release (Preferred Target)
2021-04-06 Final Freeze
2021-04-20 Preferred Final Target date
```

List of system-wide and self-contained changes available in https://fedoraproject.org/wiki/Releases/34/ChangeSet.

Offhand, going through the list, here are some changes I think we should dig a bit into:
- [DNS over TLS](https://fedoraproject.org/wiki/Changes/DNS_Over_TLS): we should sanity-check DoT works on FCOS (need to roll back to using systemd-resolved first)
- [Restart services at end of rpm transaction](https://fedoraproject.org/wiki/Changes/Restart_services_at_end_of_rpm_transaction): should sanity-check the scriptlet approach there gracefully no-ops in the rpm-ostree scriptlet container
- [Rust Crate Packages For Release Branches](https://fedoraproject.org/wiki/Changes/Rust_Crate_Packages_For_Release_Branches): should adapt workflow/checklist of our Rust-based packages

**Comment by jlebon** [comment]
Related to this, we're working on setting up [the rawhide stream](https://github.com/coreos/fedora-coreos-tracker/issues/497) which will help with getting CI coverage as well for any changes we need to make.

**Comment by travier** [comment]
https://fedoraproject.org/wiki/Changes/EnableSystemdOomd > This one might impact us

**Comment by jlebon** [comment]
We'll want to drop at least this postprocess script: https://github.com/coreos/fedora-coreos-config/pull/765.

**Comment by jlebon** [comment]
Note also we should be able to drop the [systemd stub-resolv.conf relabeling hack](https://github.com/coreos/fedora-coreos-config/commit/b9a2c39e44120a1d46de37e956e8cbead1aac9fd) in f34 (see https://github.com/coreos/fedora-coreos-config/pull/780#issuecomment-746684705 and https://github.com/coreos/fedora-coreos-tracker/issues/751#issuecomment-782314226).

**Comment by jlebon** [comment]
SOP for rebases now also include grepping f-c-c for `TODO fNN` to see if there are things we should add/remove/check at rebase time. (See e.g. https://github.com/coreos/fedora-coreos-config/pull/882).

**Comment by jlebon** [comment]
Note: the beta go/no-go meeting is today. If it's a go, we should look at moving `next` over to f34 in either the next set of releases or the one after that.

**Comment by jlebon** [comment]
Beta was no-go. So let's stick with f33 for `next` for this week's release.

**Comment by jlebon** [comment]
F34 rebase note: need to ensure we have this NM or newer: https://bodhi.fedoraproject.org/updates/FEDORA-2021-fb173bc82f (for this patch: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/770).

**Comment by jlebon** [comment]
next-devel rebase: https://github.com/coreos/fedora-coreos-config/pull/902

**Comment by lucab** [comment]
Apparently this induced three downgrades in 34.20210328.1.0:
```
    conmon 2:2.0.26-1.fc33.x86_64 → 2:2.0.22-0.9.dev.git2fbeb9f.fc34.x86_64
    containers-common 4:1-4.fc33.noarch → 1:1.2.1-28.dev.git1b813f8.fc34.x86_64
    skopeo 1:1.2.2-1.fc33.x86_64 → 1:1.2.1-28.dev.git1b813f8.fc34.x86_64
```

**Comment by dustymabe** [comment]
> Apparently this induced three downgrades in 34.20210328.1.0:

Next iteration should resolve this: https://github.com/coreos/fedora-coreos-config/pull/931

Next time we'll [catch it sooner](https://github.com/coreos/fedora-coreos-config/pull/892).

**Comment by jlebon** [comment]
The schedule we're leaning on based on discussions during today's IRC meeting is:

```
Week 0 (GA): next release with bumped content
Week 1: testing release based on last next
Week 3: stable release based on last testing
```

where week 0 is the week when Fedora 34 actually GAs. This may end up meaning we shift our release schedule depending on whether GA is on a release week (Apr 27th) or not (Apr 20th).

We'll also publish next releases every week until `testing` gets f34.

**Comment by jlebon** [comment]
F34 is no-go for Apr 20th. The new target date is thus Apr 27th: https://lists.fedoraproject.org/archives/list/devel-announce@lists.fedoraproject.org/thread/2UHYXZ6LDWEQ2EUEL3QUMV753JKEAUXZ/.

**Comment by dustymabe** [comment]
Was browsing and ran across https://github.com/coreos/fedora-coreos-tracker/issues/676. Maybe we should look at that this round?

**Comment by jlebon** [comment]
> Was browsing and ran across #676. Maybe we should look at that this round?

I think we were sort of hoping for a declarative way to drive this via `alternatives`, but it doesn't look like there are any plans to address this anytime soon. So agreed we shouldn't block on that to get this done.

**Comment by bgilbert** [comment]
We need to remember to run all of the steps in the [rebase SOP](https://github.com/coreos/fedora-coreos-config/#moving-to-a-new-major-version-n-of-fedora).  Would it make sense to convert that checklist into an issue template in this repo?

I've updated the coreos-installer signing keys in https://github.com/coreos/coreos-installer/pull/530.

**Comment by jlebon** [comment]
> We need to remember to run all of the steps in the [rebase SOP](https://github.com/coreos/fedora-coreos-config/#moving-to-a-new-major-version-n-of-fedora). Would it make sense to convert that checklist into an issue template in this repo?

Yeah, that makes sense sense to me!

**Comment by bgilbert** [comment]
Issue template PR in https://github.com/coreos/fedora-coreos-tracker/pull/806.

**Comment by bgilbert** [comment]
Checklist in https://github.com/coreos/fedora-coreos-tracker/issues/808.

**Comment by travier** [comment]
Testing moved to F34 with this week's releases

**Comment by dustymabe** [comment]
We moved the stable stream starting with ` 34.20210427.3.0` in mid may.

The checklist ticket (#808) still has a few items left, but we can close this out.
