### ISSUE TITLE
iscsiadm does not allow creating a new node inside a systemd unit file

### ISSUE THREAD

**Issue by patsoffice** [coreos/fedora-coreos-tracker#705]
**Describe the bug**
When attempting to create a new iscsi node in a systemd unit file, permission is denied writing to /var/lib/iscsi/nodes/. However, running the same command as root via sudo works.

**Reproduction steps**
1. `sudo systemctl start iscsi-apps-new.service` fails
2. `sudo systemctl status iscsi-apps-new.service` shows the failure is a permission denied error
3. `dmesg | grep iscsi` shows the SELinux AVC denied error.

**Expected behavior**
Running the `iscsiadm` command as root via `sudo` results in a node directory being created and the session file being created in said directory.

```
$ sudo /usr/sbin/iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:core-102-apps -o new -p 192.168.1.0:3260
New iSCSI node [tcp:[hw=,ip=,net_if=,iscsi_if=default] 192.168.1.0,3260,-1 iqn.2005-10.org.freenas.ctl:core-102-apps] added
$ sudo ls -laZ /var/lib/iscsi/nodes/iqn.2005-10.org.freenas.ctl\:core-102-apps/
total 4
drw-------. 2 root root system_u:object_r:iscsi_var_lib_t:s0       30 Dec 26 05:08 .
drwxr-xr-x. 3 root root system_u:object_r:iscsi_var_lib_t:s0       55 Dec 26 05:07 ..
-rw-------. 1 root root unconfined_u:object_r:iscsi_var_lib_t:s0 2109 Dec 26 05:08 192.168.1.0,3260
```

**Actual behavior**
The systemd unit file is:

```
[Unit]
Description=Add iSCSI node for apps volume
Before=iscsid.service
ConditionPathExists=!/var/lib/iscsi/nodes/iqn.2005-10.org.freenas.ctl:core-102-apps

[Service]
Type=oneshot
ExecStart=/usr/sbin/iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:core-102-apps -o new -p 192.168.1.0:3260
ExecStart=/usr/sbin/iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:core-102-apps -o update -n node.startup -v automatic
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

Starting the above unit file fails with:

```
$ sudo systemctl status iscsi-apps-new.service
● iscsi-apps-new.service - Add iSCSI node for apps volume
     Loaded: loaded (/etc/systemd/system/iscsi-apps-new.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2020-12-26 05:12:42 UTC; 5s ago
    Process: 48409 ExecStart=/usr/sbin/iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:core-102-apps -o new -p 192.168.1.0:3260 (code=exited, status=6)
   Main PID: 48409 (code=exited, status=6)

Dec 26 05:12:42 coreos-102.chezlawrence.com systemd[1]: Starting Add iSCSI node for apps volume...
Dec 26 05:12:42 coreos-102.chezlawrence.com iscsiadm[48409]: iscsiadm: Could not open /var/lib/iscsi/nodes/iqn.2005-10.org.freenas.ctl:core-102-apps/192.168.1.0,3260: Permission deniedd
Dec 26 05:12:42 coreos-102.chezlawrence.com iscsiadm[48409]: iscsiadm: Error while adding record: encountered iSCSI database failure
Dec 26 05:12:42 coreos-102.chezlawrence.com systemd[1]: iscsi-apps-new.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Dec 26 05:12:42 coreos-102.chezlawrence.com systemd[1]: iscsi-apps-new.service: Failed with result 'exit-code'.
Dec 26 05:12:42 coreos-102.chezlawrence.com systemd[1]: Failed to start Add iSCSI node for apps volume.
```

While the node directory is successfully created:

```
$ sudo ls -laZ /var/lib/iscsi/nodes/iqn.2005-10.org.freenas.ctl\:core-102-apps/
total 0
drw-------. 2 root root system_u:object_r:iscsi_var_lib_t:s0  6 Dec 26 05:12 .
drwxr-xr-x. 3 root root system_u:object_r:iscsi_var_lib_t:s0 55 Dec 26 05:12 ..
```

There is an selinux avc violation when attempting to create the session file:

```
$ sudo dmesg | grep iscsi
...
[15846.538311] audit: type=1400 audit(1608959562.805:1201): avc:  denied  { dac_override } for  pid=48409 comm="iscsiadm" capability=1  scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:system_r:iscsid_t:s0 tclass=capability permissive=0
[15846.570744] audit: type=1130 audit(1608959562.836:1202): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=iscsi-apps-new comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed
```

The target context being used in the systemd unit file is `tcontext=system_u:system_r:iscsid_t:s0` however, the filesystem context is `system_u:object_r:iscsi_var_lib_t:s0`.

**System details**
 - Bare Metal
 - Fedora CoreOS version: Fedora CoreOS 33.20201201.3.0

**Ignition config**
Please attach your FCC or Ignition config used to provision your system. Be sure to sanitize any private data. If not using FCCT to generate your Ignition config, does the Ignition config pass validation using [ignition-validate](https://coreos.github.io/ignition/getting-started/#config-validation)?

The ignition file is not an issue. It's working just fine creating the above unit file. There are no selinux changes in the FCC/ignition files.

**Additional information**
Add any other information about the problem here.

**Comment by dustymabe** [comment]
Hey @patsoffice, Thanks for the report.

I suspect this is an issue in the SELinux policy in Fedora. One way to check is to spin up a [Fedora Cloud Base image](https://alt.fedoraproject.org/cloud/) instance and check that the behavior also happens there in the same way.

Assuming that's the case would you mind opening an issue against [selinux-policy in bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=selinux-policy)? The upstream for Fedora's policy is in GitHub at https://github.com/fedora-selinux/selinux-policy so if you're motivated you might be able to open a PR there and link to it in the BZ.

**Comment by patsoffice** [comment]
@dustymabe, yeah, I figured that was likely the case (problem upstream). Thanks! I'll validate it later today or tomorrow. Closing this issue.

**Comment by dustymabe** [comment]
👍 - If you do open a bug or PR please do link it back here.

**Comment by patsoffice** [comment]
@dustymabe I think I did it all correctly -- sorry, Github n00b in many ways. Opened https://bugzilla.redhat.com/show_bug.cgi?id=1911161 and submitted a PR upstream (trivial fix).
