### ISSUE TITLE
nm-initrd-generator should support rd.net.timeout.carrier karg

### ISSUE THREAD

**Issue by adarshaj** [coreos/fedora-coreos-tracker#708]
I have a physical server that has Intel NIC on PCIe slot, which takes about 30s to come up with carrier link during boot up. I am using kernel cmdline to add `ip=eno2:dhcp` and `rd.neednet=1` for the network config in initramfs. I see that NetworkManager parses the kernel cmdline and generates eno2.nmconnection file. However, by the time NetworkManager starts up, the carrier link is not up yet (I see `ixgbe` driver log messages where it says the link is being setup and it goes up & down & back up), as a result, NetworkManager changes from unmanaged -> unavailable and immediately followed by unavailable -> disconnected. Later when the `ixgbe` module reported the network link as UP, there was no dhcp or networkmanager logs trying to activate it.

I have had the same behavior on FCOS latest stable version - `33.20201201.3.0` as well as latest testing version - `33.20201214.2.0`.

I have researched a bit about this and found that this was a known problem earlier with RH specific dracut modules and suggested workaround was to add `rd.net.timeout.carrier=30`. I tried adding this and it did not work. I went into `nm-initrd-generator` and saw that it does not generate any code for handling this parameter at all (It did have dhcp timeout, however, in my case it notices the link is not UP so it won't even try dhcp).

So I am not stuck with the servers which are forever stuck trying to fetch ignition config and unable to connect to network.

Is there any workaround whereby I can change the NetworkManger config for ignition in initramfs and add the `[device]` section with `carrier-wait-timeout` setting?  (I tried to add it as "merge" section with ignition config, but it did not work)

**Comment by jlebon** [comment]
> I went into nm-initrd-generator and saw that it does not generate any code for handling this parameter at all (It did have dhcp timeout, however, in my case it notices the link is not UP so it won't even try dhcp).

Hmm, this might be a good RFE for NetworkManager.

Stepping back though, are you hitting this when trying to boot the live PXE/live ISO, or when rebooting into the installed system for the first time? If the latter, you should be able to inject NM configs into the installed system using [`coreos-installer install --copy-network`](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/#_via_coreos_installer_copy_network). Another approach if the Ignition config itself doesn't have any network references is to embed the Ignition config at install time via `coreos-installer install <--ignition-file|--ignition-url>` assuming it can be fetched at that point in time.

For the live PXE/live ISO, you should be able to avoid requiring networking at all in the initramfs by (for live PXE) [appending the Ignition config as a secondary initramfs](https://coreos.github.io/coreos-installer/cmd/pxe/), or by (for live ISO) [injecting the Ignition config into the ISO](https://coreos.github.io/coreos-installer/cmd/iso/#coreos-installer-iso-ignition-embed). (Again, these assume that the Ignition config itself doesn't have any network references).

**Comment by adarshaj** [comment]
> Hmm, this might be a good RFE for NetworkManager. (Edit: filed https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/626.)
>

Thanks for filing it! I'll keep an eye on it.
 
> Stepping back though, are you hitting this when trying to boot the live PXE/live ISO, or when rebooting into the installed system for the first time?

The boot from PXE is okay (I do iPXE boot), the first install does go through fine.  Now that I think about it, the first boot did have a network reference (in coreos.inst.*) to the metal image of fcos and ign, which was fetched fine. However the next boot (first boot of disk install) fails since the ignition has config url pointing to a network resource (this is part of OKD 4.6, so its trying to fetch from api-int end point)

> If the latter, you should be able to inject NM configs into the installed system using [`coreos-installer install --copy-network`](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/#_via_coreos_installer_copy_network). Another approach if the Ignition config itself doesn't have any network references is to embed the Ignition config at install time via `coreos-installer install <--ignition-file|--ignition-url>` assuming it can be fetched at that point in time.
> 

I have not tried the `--copy-network`, shall give it a try, could you outline (or point to a link) the steps to get into the live ipxe? (I try to put  rd.break=cmdline, and see a log message saying Starting Dracut Emergency Console, but nothing happens, I tried to press enter key multiple times (over KVM) but the system seems to ignore it.

> For the live PXE/live ISO, you should be able to avoid requiring networking at all in the initramfs by (for live PXE) [appending the Ignition config as a secondary initramfs](https://coreos.github.io/coreos-installer/cmd/pxe/), or by (for live ISO) [injecting the Ignition config into the ISO](https://coreos.github.io/coreos-installer/cmd/iso/#coreos-installer-iso-ignition-embed). (Again, these assume that the Ignition config itself doesn't have any network references).

I tried appending ignition config (by manually curl to https://api-int.host:22623/config/worker)  as secondary initrd, it got detected and injected into roots, i saw log message which copied it from /config.ign to user.ign. However, ignition failed saying version not supported (The version from OKD 4.6 was `2.2.0`). I am doing this remotely and live ISO is a bit network intensive, so haven't yet tried it. 

As you noted, my installation via coreos.inst.* kernel cmdline works possibly because the system already exited initrd and therefore is able to setup network properly, but network in initrd does not work.. as a result `ignition.config.url` with a network point *always* fails.. 

Please let me know if there is any more information that I can provide to fix the issue..

**Comment by adarshaj** [comment]
> (I try to put rd.break=cmdline, and see a log message saying Starting Dracut Emergency Console, but nothing happens, I tried to press enter key multiple times (over KVM) but the system seems to ignore it.

Just noticed it was probably getting redirected to ttyS0 (since I have it as kernel cmdline). I removed it and now I am able to see a responsive and functional terminal via KVM. I'll try to debug further from this point.

**Comment by adarshaj** [comment]
I made some headway... I added `rd.break=initqueue` and was able to get the shell prompt (after removing `console=ttyS0`). On one of the worker node, I just issued `NetworkManager --configure-and-quit=initrd --no-daemon`, it gave the exact same output as the one started by dracut.. i.e. it started and found eno2 had no link and declared as startup done and exited. Right after it exited I noticed `ixgbe` driver print log messages showing eno2 going up, down and back up again, as soon as it printed the last Up status, I issued same command again - `NetworkManager --configure-and-quit=initrd --no-daemon` and immediately it obtained the dhcp connection and ignition proceeded to fetch the config and install.. 

On a different machine, I used the same `rd.break=initqueue` and dropped into shell prompt, but this time, I created a file at: `/run/NetworkManager/conf.d/delay.conf` with the following settings in it: 
```
[device]
match-device=interface-name:eno2
carrier-wait-timeout=20000
```

and issued the same command - `NetworkManager --configure-and-quit=initrd --no-daemon` this time, Network Manager did wait until eno2 would be up and issued a dhcp and configured the interface properly!!!

@jlebon - Thank you so much for your support! I had been trying continuously from past 3 days to find a way around this and finally now I have it! I will followup on NetworkManager repo issue and shall help to get it fixed in upstream.

I am not sure if I have to close this issue, since the friction to install still exists.

**Comment by jlebon** [comment]
> Now that I think about it, the first boot did have a network reference (in coreos.inst.*) to the metal image of fcos and ign, which was fetched fine.

Note BTW that you shouldn't have to give a URL to the metal image anymore. The image is included in the live environment already. (Notice how the example PXE config in [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_installing_from_pxe) doesn't use it.)

> I have not tried the `--copy-network`, shall give it a try, could you outline (or point to a link) the steps to get into the live ipxe? (I try to put rd.break=cmdline, and see a log message saying Starting Dracut Emergency Console, but nothing happens, I tried to press enter key multiple times (over KVM) but the system seems to ignore it.

If you boot the live PXE without any `coreos.inst.*` kargs, by default you'll be dropped into a shell. You can then configure the network using e.g. `nmcli` or `nmtui`. And then when you're ready, run e.g. `coreos-installer install /dev/sda ... --copy-network`.

> @jlebon - Thank you so much for your support!

No problem, happy we're making progress! :)

**Comment by adarshaj** [comment]
> Note BTW that you shouldn't have to give a URL to the metal image anymore. The image is included in the live environment already. (Notice how the example PXE config in [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_installing_from_pxe) doesn't use it.)

Wow, I did not realize metal image is now part of live pxe! Shall try it out :)

> If you boot the live PXE without any `coreos.inst.*` kargs, by default you'll be dropped into a shell. You can then configure the network using e.g. `nmcli` or `nmtui`. And then when you're ready, run e.g. `coreos-installer install /dev/sda ... --copy-network`.

Just to clarify, does this only copy the `/etc/NetworkManager/system-connections` files? or does it also copy `/etc/NetworkManager/devices/` or/and `/etc/NetworkManager/conf.d/` files too? For my use case I would need `[device]` section to be copied, which iirc is placed in device folder or conf.d folder within NetworkManager when using the nmcli tools..

**Comment by jlebon** [comment]
> Just to clarify, does this only copy the `/etc/NetworkManager/system-connections` files? or does it also copy `/etc/NetworkManager/devices/` or/and `/etc/NetworkManager/conf.d/` files too? For my use case I would need `[device]` section to be copied, which iirc is placed in device folder or conf.d folder within NetworkManager when using the nmcli tools..

Ahh yeah, good catch. It only copies `/etc/NetworkManager/system-connections`, so your `devices/` file wouldn't be copied. Hmm... have to think about whether to support that. Ideally though, we'd be able to use the `rd.net.timeout.carrier` karg once https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/626 is fixed.

> However the next boot (first boot of disk install) fails since the ignition has config url pointing to a network resource (this is part of OKD 4.6, so its trying to fetch from api-int end point)

Since you mentioned OKD, note that there's been some work recently to alleviate that chicken-and-egg issue. See:
- https://github.com/openshift/enhancements/pull/540
- https://github.com/openshift/installer/pull/4413
- https://github.com/openshift/installer/pull/4427

The summary IIUC is that you should be able to do the same thing OpenShift bare metal IPI now does and give to coreos-installer (either via `coreos.inst.ignition_url` or `--ignition-url`) the rendered Ignition config itself from the API endpoint. There shouldn't be any network references in there and so it shouldn't request networking at all.

And ahh OK, rereading, I see you did try something similar:

> I tried appending ignition config (by manually curl to api-int.host:22623/config/worker) as secondary initrd, it got detected and injected into roots, i saw log message which copied it from /config.ign to user.ign. However, ignition failed saying version not supported (The version from OKD 4.6 was 2.2.0). I am doing this remotely and live ISO is a bit network intensive, so haven't yet tried it.

The Ignition config from the API is meant for the installed system, not the live environment, i.e. `coreos.inst.ignition_url`/`--ignition-url`, not the PXE's `ignition.config.url=`/secondary initrd. (Yeah, this is confusing -- see the OpenShift docs here for more details about that: https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal/installing-bare-metal.html#installation-user-infra-machines-advanced_ignition_installing-bare-metal).

**Comment by romfreiman** [comment]
@jlebon what's the plan regarding this issue?

**Comment by jlebon** [comment]
@romfreiman Do you have a similar issue? It looks like there's progress on https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/730. If you'd like this in el8, I suggest creating an RHBZ. Otherwise, does the workaround in https://github.com/coreos/fedora-coreos-tracker/issues/708#issuecomment-756846248 work?

**Comment by romfreiman** [comment]
Yes we do. @empovit can elaborate.

**Comment by romfreiman** [comment]
@jlebon we need it in rhcos

**Comment by lucab** [comment]
Self note: this landed in upstream release `1.29.10-dev`. It is my understanding that the fix for this will reach FCOS once we rebase to F34.

**Comment by adarshaj** [comment]
> Self note: this landed in upstream release `1.29.10-dev`. It is my understanding that the fix for this will reach FCOS once we rebase to F34.

Just noticed that part two testing stream has fcos 34 which contains NM 1.3.2 which includes the fix for this issue.

**Comment by dustymabe** [comment]
@adarshaj - thanks for pointing that out. Is it working for you?

**Comment by adarshaj** [comment]
I haven't yet gotten to reinstall my test cluster, shall update here once I do!

**Comment by dustymabe** [comment]
The fix for this went into next stream release `34.20210328.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `34.20210427.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `34.20210427.3.0`.
