### ISSUE TITLE
no cloud agents: digitalocean

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#71]
In #12 we decided that we'd like to try to not ship cloud agents. This ticket will document investigation and strategy for shipping without a cloud agent on the **digitalocean cloud platform**.

See also #41 for a discussion of how to ship cloud specific bits using ignition.

**Comment by bgilbert** [comment]
DigitalOcean doesn't have an agent.  On Container Linux, coreos-metadata is [responsible for configuring networkd](https://github.com/coreos/coreos-metadata/blob/c2f8bc468c7b157ceea0c5fe2e389da9ef28ae0b/src/providers/digitalocean/mod.rs) from the initramfs on every boot, since DigitalOcean provides network parameters via a link-local metadata server and didn't originally support DHCP.  I'm not sure whether DHCP works now, but I presume the metadata server is still needed for configuring private IPs.

**Comment by ryanpq** [comment]
DHCP in DO is only in a very limited release.  User-imported images are set to use DHCP since no cloud agent or standard cloud-init can be ensured.  DHCP is not in use on any base or application images (or droplets created with them) currently.

**Comment by dustymabe** [comment]
Thanks @ryanpq :smiley: . We have some time before Fedora CoreOS will be shipped so maybe time to improve that there. We'll play around with DHCP as it exists in DO today and see if it works well enough for us.

**Comment by bgilbert** [comment]
@ryanpq Since a private IP address is assigned to the same NIC as the public one, I assume private IPs will still require querying the metadata service?

**Comment by ryanpq** [comment]
Yes.  We can support providing this information via the metadata service or a configdrive

**Comment by ryanpq** [comment]
That is correct.  DHCP isn't offered at all for standard images.  Currently it is a feature only in use by droplets created via custom images (images imported using the new feature).  The reason for this is that we cannot be sure that a VM image a user imports will have a compatible cloud-init or similar service available.  DHCP on DO is not yet compatible with some services like private IPs and ipv6. For this reason it is not yet used for any droplets created using standard (base OS or one-click) images.

**Comment by bgilbert** [comment]
It appears that https://github.com/coreos/fedora-coreos-tracker/issues/111 is the only missing piece.  Will PR the design doc.

**Comment by dustymabe** [comment]
thanks @bgilbert

**Comment by bgilbert** [comment]
It turns out that DO does have an [agent](https://github.com/digitalocean/do-agent) for reporting droplet metrics back to DO.  I don't think there's any reason for us to ship it.

**Comment by bgilbert** [comment]
Design doc PR merged in #113.
