### ISSUE TITLE
2021-02-03: gather status update for Fedora Council 

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#710]
The Fedora Council has a status reporting system in place for the various Editions to raise awareness of what is going on in each one. We should compile some new information that we want to publicize once a month and share it by updating the https://pagure.io/Fedora-Council/status_reports/blob/main/f/modules/dashboard/pages/editions/fcos.adoc file.

We will gather content for this update in the weekly meeting on 2021-02-03.

**Comment by jlebon** [comment]
Previous one was https://github.com/coreos/fedora-coreos-tracker/issues/690.
When this is closed, please create a new ticket for the next update.

**Comment by jlebon** [comment]
We discussed this at the community meeting today:

- Boot disk mirroring (RAID 1) support GA
- `/boot` is now mounted read-only, and `/boot/efi` is no longer mounted by default
    - Kernel argument changes are managed via rpm-ostree kargs.
    - Bootloader updates are managed by bootupd.
    - There's no longer a canonical EFI; each mirrored boot disk will have its own. bootupd will handle updating bootloader binaries from each System EFI partition.
- New rpm-ostree release v2021.1
    - The `rpm-ostree livefs` command is now called `live-apply` and is now much safer to use.
    - rpm-ostree now ships a DNF Count Me compatible timer and systemd unit, though they're still disabled for the time being.
- Performed an async release for the sudo CVE. Thankfully, the kernel CVE lined up with a scheduled release.
- Had virtual face-to-face meetings about growing the FCOS community, and FCOS as an edition
  - Recordings and notes available: https://github.com/coreos/fedora-coreos-tracker/tree/master/docs
- FCOS now uses the sqlite rpmdb backend

**Comment by bgilbert** [comment]
https://pagure.io/Fedora-Council/status_reports/pull-request/20
