### ISSUE TITLE
Disk Size on IBM Cloud

### ISSUE THREAD

**Issue by arcdigital** [coreos/fedora-coreos-tracker#713]
**Describe the bug**
When launching a VM on IBM Cloud, I can't get my boot disk to show the correct size.

**Reproduction steps**
1. Follow instructions here to upload image: https://docs.fedoraproject.org/my/fedora-coreos/provisioning-ibmcloud/ (I used the IBM Cloud 33.20201214.3.1 stable version)
2. Create a VM using the image, I created a bx2-2x8 instance with the standard 100GB boot volume.
3. SSH into the instance and you'll see the disk size is 8GB, instead of 100GB.

**Expected behavior**
The disk size is 100GB.

**Actual behavior**
The disk size is 8GB.

**System details**
 - IBM Cloud
 - Fedora CoreOS version 33.20201214.3.1

**Ignition config**
N/A

**Additional information**
```
[core@testdisk2 ~]$ lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    252:0    0    8G  0 disk
├─vda1 252:1    0    1M  0 part
├─vda2 252:2    0  127M  0 part /boot/efi
├─vda3 252:3    0  384M  0 part /boot
└─vda4 252:4    0  7.5G  0 part /sysroot
vdb    252:16   0  370K  0 disk
vdc    252:32   0   44K  0 disk
```

```
[core@testdisk2 ~]$ journalctl -u ignition-ostree-growfs.service
-- Logs begin at Wed 2021-01-13 02:58:29 UTC, end at Wed 2021-01-13 03:08:51 UTC. --
Jan 13 02:58:32 localhost systemd[1]: Starting Ignition OSTree: Grow root filesystem...
Jan 13 02:58:32 localhost coreos-growpart[505]: CHANGED: partition=4 start=1050624 old: size=4820992 end=5871616 new: size=15726559 end=16777183
Jan 13 02:58:32 localhost coreos-growpart[531]: meta-data=/dev/vda4              isize=512    agcount=4, agsize=150656 blks
Jan 13 02:58:32 localhost coreos-growpart[531]:          =                       sectsz=512   attr=2, projid32bit=1
Jan 13 02:58:32 localhost coreos-growpart[531]:          =                       crc=1        finobt=1, sparse=1, rmapbt=0
Jan 13 02:58:32 localhost coreos-growpart[531]:          =                       reflink=1
Jan 13 02:58:32 localhost coreos-growpart[531]: data     =                       bsize=4096   blocks=602624, imaxpct=25
Jan 13 02:58:32 localhost coreos-growpart[531]:          =                       sunit=0      swidth=0 blks
Jan 13 02:58:32 localhost coreos-growpart[531]: naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
Jan 13 02:58:32 localhost coreos-growpart[531]: log      =internal log           bsize=4096   blocks=2560, version=2
Jan 13 02:58:32 localhost coreos-growpart[531]:          =                       sectsz=512   sunit=0 blks, lazy-count=1
Jan 13 02:58:32 localhost coreos-growpart[531]: realtime =none                   extsz=4096   blocks=0, rtextents=0
Jan 13 02:58:32 localhost coreos-growpart[531]: data blocks changed from 602624 to 1965819
Jan 13 02:58:32 localhost systemd[1]: Finished Ignition OSTree: Grow root filesystem.
Jan 13 02:58:35 localhost systemd[1]: ignition-ostree-growfs.service: Succeeded.
Jan 13 02:58:35 localhost systemd[1]: Stopped Ignition OSTree: Grow root filesystem.
```

![image](https://user-images.githubusercontent.com/551002/104401801-c8641180-5509-11eb-924c-74ffe9e5c372.png)

**Comment by lucab** [comment]
Thanks for the report. From the logs, apparently the rootfs got grown correctly but `lsblk` is showing the previous size. 
Can you please manually run `sudo kpartx /dev/vda && lsblk` and post the full output of that?

**Comment by arcdigital** [comment]
yep here you go @lucab 

```
[core@testdisk2 ~]$ sudo kpartx /dev/vda && lsblk
vda1 : 0 2048 /dev/vda 2048
vda2 : 0 260096 /dev/vda 4096
vda3 : 0 786432 /dev/vda 264192
vda4 : 0 15726559 /dev/vda 1050624
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda    252:0    0    8G  0 disk
├─vda1 252:1    0    1M  0 part
├─vda2 252:2    0  127M  0 part /boot/efi
├─vda3 252:3    0  384M  0 part /boot
└─vda4 252:4    0  7.5G  0 part /sysroot
vdb    252:16   0  370K  0 disk
vdc    252:32   0   44K  0 disk
```

**Comment by cgwalters** [comment]
This looks like something going wrong at the hypervisor/cloud layer; it's not reporting the correct size to the OS or you somehow didn't get provisioned the expected space. 

The kernel is telling us the physical disk is just 8GB.

Have you tried sanity checking the same boot configuration with a different OS (traditional RHEL, Ubuntu or whatever)?

**Comment by arcdigital** [comment]
I did and that came back as expected with ~100GB.

**Comment by jlebon** [comment]
Are those other images you've tried already part of the cloud stock images or did you upload them? Wonder if we're missing something in our upload docs.

**Comment by arcdigital** [comment]
hey - sorry I'm not using IBM cloud for this anymore so I can't test it.
