### ISSUE TITLE
Container Plumbing Days CFP

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#727]
[Container Plumbing Days](https://containerplumbing.org/) is happening March 9-10, 2021. CFP closing on February 10, 2021. CoreOS is specifically called out in https://containerplumbing.org/speakers.

Is anyone interested in submitting a talk?

Let's use this ticket to discuss CoreOS-related talk ideas and submissions.

**Comment by JaimeMagiera** [comment]
25 minutes is just about right to cover rpm-ostree basics and the boot process in a digestible fashion.

**Comment by travier** [comment]
Clement and/or I could give a talk about the [article we wrote about hosting a Matrix homeserver on Fedora CoreOS](https://fedoramagazine.org/deploy-your-own-matrix-server-on-fedora-coreos/) as this is includes a lot of podman usage. We can also work on moving the exemple a little bit further to include more podman features such as auto-updates of containers and automated builds from Quay.io.

**Comment by travier** [comment]
We (@travier & @cverna) submitted a proposal for the above mentioned talk.

**Comment by bgilbert** [comment]
The CFP is now closed, so I'll close this.  Thanks for submitting a proposal, @travier and @cverna!
