### ISSUE TITLE
no cloud agents: virtualbox

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#73]
In #12 we decided that we'd like to try to not ship cloud agents. This ticket will document investigation and strategy for shipping without a cloud agent on the **virtualbox virtualization platform**.

See also #41 for a discussion of how to ship cloud specific bits using ignition.

**Comment by bgilbert** [comment]
Container Linux runs on VirtualBox only via Vagrant, and not very well at that.  CL never shipped the VirtualBox Guest Additions, nor enabled the `VBOXGUEST` or `VBOXVIDEO` kernel drivers.  We should investigate whether FCOS can run acceptably without, at least, the Guest Additions.

Ignition currently uses a [config-drive hack](https://github.com/coreos/ignition/blob/5a75c8d34af20cea487dca93de6fda8de69d68fb/internal/providers/virtualbox/virtualbox.go) to obtain userdata on VirtualBox.  That's only an acceptable UX when run in Vagrant, since Vagrant glue can generate the config drive on behalf of the user.  Also, Ignition has avoided supporting config drives in general, since it's impossible to know how long to wait for a config drive to appear before deciding that the user did not provide one.  https://github.com/coreos/ignition/issues/629 proposes improving VirtualBox's "guest properties" system and then using that; we may want to pursue that rather than propagate config-drive support into FCOS.

**Comment by dustymabe** [comment]
We offer a virtualbox vagrant box of Fedora Atomic Host today. I don't think we do anything special for it for virtualbox. I haven't heard any complaints.

**Comment by bgilbert** [comment]
Ignition [just landed](https://github.com/coreos/ignition/pull/1269) built-in support for VirtualBox guest properties.  The Fedora kernel already ships the `vboxvideo`, `vboxguest`, and `vboxsf` drivers.  That only leaves the Guest Additions, and in my experience, VirtualBox runs VMs adequately without them.  I'm going to close this out for now, but we can revisit later if needed.

**Comment by cgwalters** [comment]
Are we planning to ship pre-built Vagrant boxes?  Or just this is basic enablement for someone who wants to do it on their own today?

**Comment by bgilbert** [comment]
This is basic enablement for anyone who wants to run FCOS in a VirtualBox VM, e.g. for local experimentation (the way we'd use QEMU on Linux).  Vagrant support is a separable issue; see https://github.com/coreos/fedora-coreos-tracker/issues/144.
