### ISSUE TITLE
Discuss enabling rpm-ostree cliwrap

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#730]
This is a pointer issue for https://github.com/coreos/fedora-coreos-config/pull/830 to raise visibility.  That PR proposes to replace the `dracut`, `grubby`, and `rpm` commands with wrappers that don't allow modifying the system.

I'm locking this issue; please discuss in the above-linked PR.

**Comment by jlebon** [comment]
(Cross-posting)

This was discussed in [the community meeting](https://meetbot.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2021-02-17-16.30.html):

> AGREED: We will turn on cliwrap in the FCOS `next` stream to gain feedback. We will document it, and send an email to coreos-status. We will file an f35 Change before turning it on on all streams (as well as possibly other rpm-ostree variants like FSB and IoT).

**Comment by prestist** [comment]
We talked about his in the meeting today:
`AGREED: Enable cliwrap with f40 rebase; Additionally communicate this to our users by updating https://github.com/coreos/fedora-coreos-tracker/issues/1655 (@spresti:fedora.im, 17:09:05)`

**Comment by jlebon** [comment]
Note https://github.com/coreos/fedora-coreos-config/pull/2887 changes the proposal so that we only wrap `dnf` since that's the one we care most about (and `kernel-install`, until https://github.com/coreos/rpm-ostree/issues/4726 is fixed). As previously discussed, wrapping other commands that already exist in the OS is confusing and can cause (and already has caused) issues.

**Comment by jlebon** [comment]
Instead of this, I now propose https://github.com/coreos/fedora-coreos-tracker/issues/1687.

**Comment by jlebon** [comment]
> Instead of this, I now propose #1687.

Another reason why the cliwrap path is not great that became more obvious as I dug into it is that the CLI is far from parity. `dnf install` works, but for replacing existing packages, you'd still have to do `rpm-ostree override replace` (i.e. rpm-ostree still tries to maintain the distinction it makes client-side between layering and overriding -- this information would be nice to maintain in the derivation flow, but a nicer way to do that is at the container image layer level instead). We could fix that of course, but if we agree to ship dnf anyway eventually then it doesn't seem like the best use of our time.

**Comment by jlebon** [comment]
Closing in favour of https://github.com/coreos/fedora-coreos-tracker/issues/1687.
