### ISSUE TITLE
Dell PowerEdge Servers incompatible with CoreOS installation media.

### ISSUE THREAD

**Issue by lessfoobar** [coreos/fedora-coreos-tracker#740]
I was asked to create a new issue with more information. Really, aside from "You can't install to certain Dell PowerEdge servers using an ISO9660 image" I don't know what to add. You either provide what works or expect it to fail.

I do not know the extent of this limitation on Dell's part. It fails on my R815, and since it's basically a firmware thing, I bet it has wider applicability but do not have the ability to explore further. 

The problem is I can't boot when the bios is in UEFI. As soon as I change to BIOS it boots without a problem. I was told its a know issue and guess this version of fcos haven't fixed it. 
FCOS version:  fedora-coreos-33.20210117.3.2-live.x86_64.iso
Dell r815 Hardware Tag: 3svgsw1
Bios version 1.10 3.4.1

Hope this helps for resolving the issue

**Comment by bgilbert** [comment]
Duplicate of #707
