### ISSUE TITLE
Add `branched` stream

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#743]
Fedora 34 has branched now, which means FCOS rawhide should now follow f35. But we need to keep close tabs on f34 as we move closer to GA. Short-term we could have rawhide keep following f34, but it wouldn't be hard to add a `branched` stream instead.

**Comment by jlebon** [comment]
This was discussed in [the community meeting](https://meetbot.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2021-02-17-16.30.html):

> AGREED: We will add a branched stream which tracks Fedora 34 until the next stream moves over. We will move the switchover for next to be the beta release.

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-pipeline/pull/310
https://github.com/coreos/fedora-coreos-releng-automation/pull/130
https://github.com/coreos/fedora-coreos-browser/pull/24

**Comment by dustymabe** [comment]
GCP enablement bits are done:

```
./license.sh create fedora-coreos-cloud "fedora-coreos-branched" "Fedora CoreOS Branched"
Creating license ID for fedora-coreos-branched with description Fedora CoreOS Branched
{
  "id": "2238784936393414574",
  "name": "operation-1620322625465-5c1acc2832b52-25fc2a90-06d1fc66",
  "operationType": "compute.licenses.insert",
  "targetLink": "https://www.googleapis.com/compute/v1/projects/fedora-coreos-cloud/global/licenses/fedora-coreos-branched",
  "targetId": "7090747570141108142",
  "status": "DONE",
  "user": "dustymabe@fedora-coreos-cloud.iam.gserviceaccount.com",
  "progress": 100,
  "insertTime": "2021-05-06T10:37:05.791-07:00",
  "startTime": "2021-05-06T10:37:05.791-07:00",
  "endTime": "2021-05-06T10:37:05.791-07:00",
  "selfLink": "https://www.googleapis.com/compute/v1/projects/fedora-coreos-cloud/global/operations/operation-1620322625465-5c1acc2832b52-25fc2a90-06d1fc66",
  "kind": "compute#operation"
}
```

**Comment by dustymabe** [comment]
We've had a `branched` stream for a while that we use in the period before we switch `next-devel` over to the next Fedora version.
