### ISSUE TITLE
Cloud CLI Clients

### ISSUE THREAD

**Issue by arithx** [coreos/fedora-coreos-tracker#75]
Opening this ticket to discuss possible inclusions of different cloud clients (`gsutil`, `awscli`, etc) in the image. 

There are multiple potential approaches:
- Including the clients in the base image
- Including a container for the clients in the base image
- Having a container created (if one does not already exist) and noting the location in the docs
- Not including them

**Comment by dustymabe** [comment]
Changed title to `Cloud CLI Clients` because when I first saw it I thought `Cloud Agents` for some reason.

**Comment by dustymabe** [comment]
My vote would be to not include them and optionally having a container created and noting the location in the docs. We could include them in a "tools" container maybe? Either way prefer not including them for now.

**Comment by jschintag** [comment]
This issue is marked as done in https://github.com/coreos/fedora-coreos-tracker/issues/159, closing it.
