### ISSUE TITLE
CoreOS live environment leaves console prompt solid white after displaying welcome message

### ISSUE THREAD

**Issue by AdamWill** [coreos/fedora-coreos-tracker#750]
Since Fedora-CoreOS-33.20210217.2.0 , after boot, the CoreOS live environment displays a welcome message in bright white, then leaves the prompt colored that same bright white. Before, the message and prompt were the standard light grey.

I'm not sure whether it's intentional that the prompt is left solid white after the message is displayed, so I'm filing an issue in case it wasn't intended.

![white](https://user-images.githubusercontent.com/916551/108439065-692ea680-7205-11eb-9fad-6530941ab0b9.png)

**Comment by AdamWill** [comment]
BTW, I'm not sure if the above fixes it there too, but I also noticed this happens after deployment too.

**Comment by bgilbert** [comment]
@AdamWill Yes, it should fix the issue there too.  Thanks for reporting!

@lucab This issue has the `status/pending-upstream-release` label applied, so AIUI it can be closed?

**Comment by lucab** [comment]
Oops, I thought it was closed by accident, my bad.

**Comment by kelvinfan001** [comment]
Sorry for the delay. I cut a new release of console-login-helper-messages (v0.21.2) which should fix the issue regarding the solid white console prompt. https://bodhi.fedoraproject.org/updates/FEDORA-2021-99a286473a

**Comment by dustymabe** [comment]
The fix for this went into next stream release `34.20210413.1.0`. Please try out the new release and report issues.

The fix for this went into testing stream release `33.20210412.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `33.20210412.3.0`.
