### ISSUE TITLE
New Package Request: stalld

### ISSUE THREAD

**Issue by jmencak** [coreos/fedora-coreos-tracker#753]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)
```
$ rpm -qp stalld-1.9-2.el8.x86_64.rpm --requires
/bin/sh
/bin/sh
/bin/sh
/usr/bin/bash
config(stalld) = 1.9-2.el8
libc.so.6()(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
rtld(GNU_HASH)
systemd
```

2. What is the size of the package and its dependencies?
```
$ stat -c '%s' stalld-1.9-2.el8.x86_64.rpm 
41804
```

3. What problem are you trying to solve with this package? Or what functionality does the package provide?
https://gitlab.com/rt-linux-tools/stalld.git

> The stalld program (which stands for 'stall daemon') is a
> mechanism to prevent the *starvation* of operating system threads in a
> Linux system. The premise is to start up on a *housekeeping* cpu (one
> that is not used for real-application purposes) and to periodically
> monitor the state of each thread in the system, looking for a thread
> that has been on a run queue (i.e. ready to run) for a specifed length
> of time without being run. This condition is usually hit when the
> thread is on the same cpu as a high-priority cpu-intensive task and
> therefore is being given no opportunity to run.

4. Can the software provided by the package be run from a container?  Explain why or why not.
Not really, it needs to be managed on the host level by `systemd`.

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?
No.

6. Can the tool(s) provided by the package be helpful in debugging networking issues?
No.

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.
Theoretically yes.  However, this would be very cumbersome and also keep old versions of the package installed when managed by an operator tied to an OCP release rather than RHCOS release.  We also believe the very small size of the package counts in favour of the inclusion.

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?
The systemd units need to be shipped too.  I.e. the complete package, please.

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)
To use `stalld`, elevated privileges are already required.

10. Does the software provided by the package have a history of CVEs?
No.

**Comment by cgwalters** [comment]
One gap is that today we have no RT story for FCOS; eventually when [rt is upstreamed fully](https://lwn.net/Articles/830660/) that gap may naturally close.

Today Red Hat is maintaining an RT-patched kernel for RHEL - this is rebuilt by CentOS8 and is probably available in C8S.  The longer term relationship of CoreOS and C8S is still TBD.

Anyways, I'm broadly in favor - this case seems very similar to irqbalance which we added in: https://github.com/coreos/fedora-coreos-config/pull/158 

Zooming out slightly, other operating systems like e.g. Android have significant amounts of "userspace scheduling policy helpers".  Personally, I'd like to see this type of stuff (including irqbalance) eventually rolled into systemd - that feels like the most coherent place to expose general tunable knobs around the (performance, latency, power usage) space.

Anyways for now, given the small size and the fact that no one will want multiple versions, adding to FCOS by default seems fine to me.

**Comment by MarSik** [comment]
I would like to add couple of details:

- stalld inclusion is a similar in concept to inclusion of other tools like irqbalance, it workarounds a hard to fix kernel bug (a RCU stall causing NMI when a close to real time process starves the kernel rcu thread).
- the package is at the moment maintained by the kernel-rt team at Red Hat
- eventually this service will be needed by some of the stock Fedora (and RHEL) tuned profiles the user can apply to nodes via NTO

Stalld and the RCU stall issue are present even when running the stock (non-RT) kernel. The real time term here is connected to the process priority (FIFO:X) and scheduling.

**Comment by dustymabe** [comment]
looks like just the `stalld` package gets brought in:

```
Added:
  stalld-1.8-1.fc33.x86_64
Run "systemctl reboot" to start a reboot
```

**Comment by travier** [comment]
Is this package useful outside of RT kernels?

**Comment by cgwalters** [comment]
> Is this package useful outside of RT kernels?

I think that was [answered above](https://github.com/coreos/fedora-coreos-tracker/issues/753#issuecomment-785111629):  

> Stalld and the RCU stall issue are present even when running the stock (non-RT) kernel. 

So I think in theory someone using non-RT might still want to enable stalld to reduce latency at the cost of performance.

Though this also seems at least to me superficially related to https://lwn.net/Articles/844976/

**Comment by travier** [comment]
This was discussed in today meeting and the inclusion of this package was accepted. @cgwalters can you make a PR? Thanks
