### ISSUE TITLE
Rawhide: Lots of "logger: unknown facility name: --user" logs during dracut initramfs build

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#758]
**Describe the bug**
On Rawhide (for FCOS & Silverblue-like too), initramfs build with dracut will generate copious amount of those log lines:

```
logger: unknown facility name: --user
```

See for example: https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/fedora-coreos/job/fedora-coreos-fedora-coreos-pipeline/1126/consoleFull

This appears to be harmless as builds are still succeeding but this is not happening in F34/branched builds. Filling this here to raise visibility and help with tracking.

**Expected behavior**

Less logs 😄

**Actual behavior**

Lots of logs 😄

**Comment by dustymabe** [comment]
upstream fix proposed: https://github.com/dracutdevs/dracut/pull/1351

**Comment by dustymabe** [comment]
This landed in https://github.com/coreos/fedora-coreos-config/pull/976

**Comment by travier** [comment]
Thanks @dustymabe
