### ISSUE TITLE
Create /dev/disk/* symlink to boot disk, for use by Ignition config

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#759]
(apologies for writing a JIRA card; actually I copypasted this)

As a user configuring disk partitions via FCC,
I want a stable device path for the boot disk,
so I can write a `storage.disks` section without hardcoding `/dev/sda`, `/dev/vda`, or `/dev/nvme0n1`.

Acceptance criteria:
 - Create `/dev/disk/...` symlink for disk containing `root` filesystem when there's exactly one such disk, and create no such symlink in other cases (e.g. rootfs RAID)
 - Confirm symlink doesn't propagate to the real root
 - Possibly add an FCCT validation to check for symlink being used outside `storage.disks.device` context (to prevent adding a mount unit pointing to the symlink)
 - FCOS and RHCOS docs updated to explicitly resize root partition when rootfs LUKS configured without RAID
 - FCOS and RHCOS docs updated to use stable symlink when configuring `/var` partition on boot disk
 - kola test for stable symlink added

**Comment by bgilbert** [comment]
I don't think udev rules natively have a way to take action based on the properties of a child device.  In principle we could shell out to a script, though.  However: if we do this with udev, race conditions could be a concern.  At some point during ignition-disks, the boot device will no longer have a recognizable rootfs on it, and udev will remove the symlink.  Ignition device aliases _should_ handle this, if the symlink is only used to partition the disk.  But if the config tries to reuse the symlink e.g. to put a filesystem on the whole-disk device for the original boot disk, it may fail.

We might want to create the symlink programmatically from a systemd service, instead.  That would avoid any possible races.  Plus, we're used to sequencing systemd units in the initrd, and less used to debugging udev interactions.

**Comment by cgwalters** [comment]
This is also related to...some tracker issue where we discussed discovering the boot disk and how for us that boils down to our GRUB config hardcoding `LABEL=boot`.  If this is about *before* the `root` partition might be moved by Ignition, then we can create this in early boot exactly once, right?

Because this refers to the `root` label which is FCOS specific it'd live in f-c-c git?

Agree that systemd unit makes the most sense; we can just explicitly sequence it where we want.

**Comment by bgilbert** [comment]
> If this is about before the root partition might be moved by Ignition, then we can create this in early boot exactly once, right?

Right.

> Because this refers to the root label which is FCOS specific it'd live in f-c-c git?

Yep.

**Comment by jlebon** [comment]
Fixed in https://github.com/coreos/fedora-coreos-config/pull/1308.

**Comment by dustymabe** [comment]
Would be cool to add some docs for this.

**Comment by jlebon** [comment]
> Would be cool to add some docs for this.

Opened https://github.com/coreos/fedora-coreos-docs/issues/353 so we don't lose that.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `35.20220213.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `35.20220213.3.0`.
