### ISSUE TITLE
rpm-ostree startup delays because of GPG key loading

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#761]
When `rpm-ostreed.service` starts, there's a noticeable delay and a slight CPU spike caused by rpm-ostree having to load all the GPG keys from `/etc/pki/rpm-gpg` to verify deployment commits (because we use `gpgkeypath=/etc/pki/rpm-gpg/`):

```
$ grep gpgkeypath /etc/ostree/remotes.d/fedora.conf
gpgkeypath=/etc/pki/rpm-gpg/
$ time rpm-ostree status
State: idle
...

real	0m2.848s
user	0m0.040s
sys	0m0.074s
$ systemctl stop rpm-ostreed
$ grep gpgkeypath /etc/ostree/remotes.d/fedora.conf
gpgkeypath=/etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-33-primary
$ time rpm-ostree status
State: idle
...

real	0m0.384s
user	0m0.041s
sys	0m0.073s
```

Ideally it'd only import the one key it needs corresponding to the right release, but it's more complicated than that because of major version rebases.

We could probably at least nuke all the super ancient keys in there to start (could do that in a post-processing script though... maybe all of Fedora should do that; yum-based systems don't really suffer from the status quo because yumrepo files always point to a specific key).

This also applies to other rpm-ostree-based Fedora variants with the same remote configuration

**Comment by jlebon** [comment]
Supporting `$releasever` in `gpgkeypath` like yumrepos is possible I guess. The tricky bit is that the `releasever` needs to come from the target commit, which implies that we've downloaded e.g. `/etc/os-release` at least without verifying anything yet. We'd probably have to fold it into the commit metadata, which is still iffy because the remote commit is dictating which key to use.

Maybe best is to have all commits signed with the N *and* the N-1 keys.

**Comment by cgwalters** [comment]
Makes sense, though an entirely different fix is to cache the deployment verification status (debate whether to do it in `/run` or persistently).

**Comment by jlebon** [comment]
The original problem which motivated me filing this is fixed by https://github.com/coreos/rpm-ostree/pull/3406, but as mentioned there, we should probably still discuss if there's something we should do about all those keys.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `35.20220313.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `35.20220313.3.1`.
