### ISSUE TITLE
Help from Fedora QA

### ISSUE THREAD

**Issue by cverna** [coreos/fedora-coreos-tracker#762]
@sumantro93 who is part of Fedora QA is volunteering to help us  to make it easier for QA community members to contribute to FCOS. For example working on defining our release criteria, test cases, running Test days and help us better integrate with the wider Fedora community.

I think it would be good to walk @sumantro93 through our CI pipeline and our kola test cases, and also consider adding him to the release executors o he can get a better idea of how we release Fedora CoreOS.

Let's discuss about it during our weekly meeting.

**Comment by bgilbert** [comment]
See also #17.

**Comment by bgilbert** [comment]
[Discussed](https://meetbot.fedoraproject.org/fedora-meeting-1/2021-03-10/fedora_coreos_meeting.2021-03-10-16.29.log.html) at today's meeting.  There were no objections to adding @sumantro93 as a release executor.

**Comment by cverna** [comment]
Will coordinate with @sumantro93 to make sure he has everything needed to get started :)
