### ISSUE TITLE
FCOS demo video for conferences

### ISSUE THREAD

**Issue by jasonbrooks** [coreos/fedora-coreos-tracker#765]
[As discussed](https://meetbot.fedoraproject.org/fedora-meeting-1/2021-03-10/fedora_coreos_meeting.2021-03-10-16.29.log.html) in the meeting today, we're looking for a demo video to use at virtual conferences, such as Red Hat Summit.

The deadline for getting the video in for Red Hat Summit is very soon, March 16, so I talked to Josh Berkus about using the video he put together for the last Kubecon for use at Red Hat Summit.

However, we do have more time to produce a new video for the next Kubecon, the deadlines for which we'll know soon (I'll update this ticket when I find out).

Josh pointed out that if we make a video w/o any intro and outro slides, we could add those as needed and reuse it for multiple conferences in the future.

@travier and @JaimeMagiera expressed interest in working on this.

**Comment by travier** [comment]
Ping @jasonbrooks here for an update.

**Comment by jasonbrooks** [comment]
We can start working on this video whenever. Maybe the first thing to consider is what elements we want to include.

**Comment by travier** [comment]
Some questions to get started:
- What was the content of the previous video?
- What format are we looking at? How long?
- Would this target devops folks first? Should this act as an introduction to FCOS?
- Should we showcase OKD?

**Comment by dustymabe** [comment]
I'm going to close this out. Feel free to re-open.
