### ISSUE TITLE
Joint community meeting with Podman folks

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#768]
I'll be setting up a community meeting with people involved in podman development. Anyone is welcomed to assist to this meeting.

The meeting will happen next week, March 24th, via video conferencing (Google Meet), replacing the existing Fedora CoreOS community meeting at 16:30 UTC. The meeting will be recorded.

----

Potential topics that will be discussed:

* cgroups v2 support status: https://github.com/coreos/fedora-coreos-tracker/issues/292
* aarch64 support: https://github.com/coreos/fedora-coreos-tracker/issues/13
* Kubernetes v1.22+ container runtime on Fedora CoreOS: https://github.com/coreos/fedora-coreos-tracker/issues/767
* podman v3, docker-compose compatibility
* Reducing the size of Fedora CoreOS: https://github.com/coreos/fedora-coreos-tracker/issues/82
* Removing support for moby-engine, runc, etc. https://github.com/coreos/fedora-coreos-tracker/issues/804

Feel free to raise topics of discussion or ask questions here if you can not attend and we will try to discuss those during the meeting.

**Comment by LorbusChris** [comment]
Another topic that I think is related here is:
- Kubernetes v1.22+ container runtime on Fedora CoreOS: https://github.com/coreos/fedora-coreos-tracker/issues/767

**Comment by travier** [comment]
During the community meeting, we agreed to replace next week meeting with this one.

**Comment by travier** [comment]
Added links for the meeting in the first comment.

**Comment by egeturgay** [comment]
It would be great if the team consider some improvements on the release notes #194 , particularly on the CVEs. Visibility in CVEs allow us to choose to upgrade or hold on to a specific release. It's an important set of information for various compliance requirements.
We currently workaround it by running the below and looking up CVE severity manually on the web.
`ostree pull fedora:fedora/x86_64/coreos/stable &&
rpm-ostree db diff fedora:fedora/x86_64/coreos/stable --changelogs | grep -A 1 -B 3 CVE`

**Comment by travier** [comment]
> It would be great if the team consider some improvements on the release notes #194 , particularly on the CVEs. Visibility in CVEs allow us to choose to upgrade or hold on to a specific release. It's an important set of information for various compliance requirements.

Thanks for the feedback. Can you add this suggestion to the tracking issue you linked? This one is more related to podman specific discussions. Thanks

**Comment by egeturgay** [comment]
@travier apologies, I misinterpreted the group meeting email.

**Comment by travier** [comment]
No worries :)

**Comment by travier** [comment]
Short notes here: https://hackmd.io/KaC9A2XUQameI4pasC1uzw
Will create issues for specific topics tomorrow.

**Comment by travier** [comment]
Recording and chat notes are temporarily available at:
  - https://siosm.fedorapeople.org/Fedora_CoreOS_Podman_meeting_2021-03-24.mp4
  - https://siosm.fedorapeople.org/Fedora_CoreOS_Podman_meeting_2021-03-24.sbv
The video recording should be uploaded to Youtube in the coming days and I will update this issue with the link.

**Comment by travier** [comment]
Link to meeting recording on Youtube: https://www.youtube.com/watch?v=9xOEroULZ5w

**Comment by travier** [comment]
Created https://github.com/coreos/fedora-coreos-tracker/issues/804 & https://github.com/coreos/zincati/issues/539
