### ISSUE TITLE
Remove fedora-coreos-pinger

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#770]
fedora-coreos-pinger was intended to serve two purposes.  In the medium term, it was intended to provide a mechanism for collecting anonymized aggregate statistics about the Fedora CoreOS installed base.  In the short term, the plan was to ship only the parser for the config file.  That way we could ship configuration docs alongside the first release of FCOS, allowing users to opt out of statistics gathering on day 1 and avoid surprises when the rest of the statistics system eventually shipped.

We did ship the config parser, but we've never implemented the rest of the statistics system and it hasn't been a priority to do so.  Also, the only place we ever documented pinger configuration in FCOS is in the [CL migration notes](https://docs.fedoraproject.org/en-US/fedora-coreos/migrate-cl/#_operator_notes).

We're currently planning to do some basic population counting via #717, which addresses part of the problem pinger was meant to solve.  If we want to gather additional statistics down the road, we'll need to provide a lot of advance notice, since most users probably aren't aware of pinger's opt-out mechanism.  Given that, it doesn't seem important to continue shipping a tool for validating an unused config file.

Consider removing fedora-coreos-pinger from the distro.  We can always add it back later if we end up needing it.

**Comment by ashcrow** [comment]
If "count me" fills the same requirements the team and community were hoping for then :+1:

**Comment by bgilbert** [comment]
Most of the info we were hoping to get from pinger will not be collected by countme.

**Comment by bgilbert** [comment]
Added meeting label.

**Comment by bgilbert** [comment]
To do:
- [x] Archive [coreos/fedora-coreos-pinger](https://github.com/coreos/fedora-coreos-pinger)
- [ ] Retire Fedora package
- [ ] Drop from fedora-coreos-config

**Comment by bgilbert** [comment]
> There are a few hits in cosa as well we'll want to rip out.

Good catch!

**Comment by bgilbert** [comment]
Done!

**Comment by jlebon** [comment]
Also https://github.com/ostreedev/ostree/pull/2658.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `36.20220703.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220703.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `36.20220703.3.1`.
