### ISSUE TITLE
podman cp is broken in 33.20210301.3.1

### ISSUE THREAD

**Issue by vrutkovs** [coreos/fedora-coreos-tracker#771]
**Describe the bug**
OKD is using `podman cp` to extract machine os content and rebase OS to it. This functionality is broken in podman 3.0.1

**Additional information**
See https://bugzilla.redhat.com/show_bug.cgi?id=1936927 for more information

**Comment by jlebon** [comment]
Based on that RHBZ, it looks like the patches we need aren't yet in a podman release. We'll have to wait until v3.1.0 is out and we can fast-track it.

Can OKD pin to the previous release for now?

**Comment by vrutkovs** [comment]
Yup, that's what we're doing now

**Comment by travier** [comment]
We may fast track a podman update from testing. Would this one help? https://bodhi.fedoraproject.org/updates/FEDORA-2021-1da12eb9ce

**Comment by Conan-Kudo** [comment]
There's Podman 3.1.0 final released this morning:

* F33: https://bodhi.fedoraproject.org/updates/FEDORA-2021-d8a3be0829
* F34: https://bodhi.fedoraproject.org/updates/FEDORA-2021-96ee965d88

**Comment by jlebon** [comment]
@travier Want to submit fast-tracks for those into testing-devel and next-devel? :)

**Comment by jdoss** [comment]
Can we get Podman 3.1.0 into Next soon? https://github.com/containers/podman/pull/9768 got merged into 3.1 and it fixes volume mount ownership.

**Comment by travier** [comment]
https://github.com/coreos/fedora-coreos-config/pull/924 > podman fast-track in progress for testing-devel. It should be in next-devel and in next in the next release.

**Comment by dustymabe** [comment]
The new podman has landed in `testing-devel`. Should hit `testing` soon.

**Comment by jdoss** [comment]
Is there an equivalent https://builds.coreos.fedoraproject.org/streams/testing.json for testing-devel that we can use to test things out?

**Comment by bgilbert** [comment]
We don't publish stream metadata for development streams.  You can get development builds from the [development build browser](https://builds.coreos.fedoraproject.org/browser).

**Comment by dustymabe** [comment]
The fix for this went into next stream release `34.20210328.1.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `33.20210328.2.1`. Please try out the new release and report issues.

**Comment by vrutkovs** [comment]
Verified that `podman cp` is no longer broken in `33.20210328.2.1`

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `33.20210328.3.0`.
