### ISSUE TITLE
coreos-reset-stub-resolv-selinux-context.service hits start-limit-hit

### ISSUE THREAD

**Issue by JaimeMagiera** [coreos/fedora-coreos-tracker#777]
**Describe the bug**
coreos-reset-stub-resolv-selinux-context.service (originating from https://github.com/systemd/systemd/pull/17976) successfully changes the context on first run, but continues to rerun until hitting the start limit. It's not a showstopper by any means, but the less visible errors the better. Maybe change the intervals or run reset-failed from elsewhere.

**Reproduction steps**
1. Install OKD 4.7.0-0.okd-2021-03-28-152009 on 33.20210201.2.1
2. Node updates to 33.20210301.3.1
3. OKD install completes 
4. Log in to the node and find...

=================
Fedora CoreOS 33.20210301.3.1
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/

[systemd]
Failed Units: 2
  coreos-reset-stub-resolv-selinux-context.path
  coreos-reset-stub-resolv-selinux-context.service

===================

Checking the status of the service...

====================

[core@master-2 ~]$ systemctl status coreos-reset-stub-resolv-selinux-context.service
● coreos-reset-stub-resolv-selinux-context.service - Fixup SELinux context on /run/systemd/resolve/stub-resolv.conf
     Loaded: loaded (/usr/lib/systemd/system/coreos-reset-stub-resolv-selinux-context.service; enabled; vendor preset: enabled)
     Active: failed (Result: start-limit-hit) since Mon 2021-03-29 03:10:35 UTC; 1h 24min left
TriggeredBy: ● coreos-reset-stub-resolv-selinux-context.path
       Docs: https://github.com/systemd/systemd/pull/17976
    Process: 1172 ExecStart=/usr/sbin/restorecon -v /run/systemd/resolve/stub-resolv.conf (code=exited, status=0/SUCCESS)
   Main PID: 1172 (code=exited, status=0/SUCCESS)
        CPU: 4ms

Mar 29 03:10:35 localhost.localdomain systemd[1]: Starting Fixup SELinux context on /run/systemd/resolve/stub-resolv.conf...
Mar 29 03:10:35 localhost.localdomain restorecon[1172]: Relabeled /run/systemd/resolve/stub-resolv.conf from system_u:object_r:systemd_resolved_var>
Mar 29 03:10:35 localhost.localdomain systemd[1]: coreos-reset-stub-resolv-selinux-context.service: Succeeded.
Mar 29 03:10:35 localhost.localdomain systemd[1]: Finished Fixup SELinux context on /run/systemd/resolve/stub-resolv.conf.
Mar 29 03:10:37 localhost.localdomain systemd[1]: coreos-reset-stub-resolv-selinux-context.service: Start request repeated too quickly.
Mar 29 03:10:37 localhost.localdomain systemd[1]: coreos-reset-stub-resolv-selinux-context.service: Failed with result 'start-limit-hit'.
Mar 29 03:10:37 localhost.localdomain systemd[1]: Failed to start Fixup SELinux context on /run/systemd/resolve/stub-resolv.conf.

**Expected behavior**
No systemd errors on the node. 

**Actual behavior**
systemd errors on the node. 

**System details**
 - vSphere
 - 33.20210301.3.1

**Ignition config**
The initiation config generated by the OKD installer passes validation. 

**Additional information**
This happened on 2/3 nodes.  I'll run a couple more OKD installs to see if it happens again and on how many nodes.

**Comment by jlebon** [comment]
Yeah, this is a hack we'll be dropping once we move to f34 because we'll have the necessary systemd patch. Though it is odd that it would be restarted multiple times this quickly (the idea is that it fires anytime the `stub-resolv.conf` is changed, but I don't expect it to change that many times).

**Comment by JaimeMagiera** [comment]
Yeah, > 5 times in 10 seconds seems like a lot for stub-resolve.conf. It had two name server lines and a search path line, presumably all written at once when the DHCP reservation was accepted. 

One other thing noticed is that on nodes where the units *didn't* fail, the hostname when it joined the cluster was localhost.localdomain. I'm going to do a few more OKD installs and see if I can track down what's hitting the file so much.

**Comment by dustymabe** [comment]
One way to fix this for good is to remove the units completely. We did just that for f34 based FCOS now (currently in `next`). See https://github.com/coreos/fedora-coreos-config/pull/941.

**Comment by dustymabe** [comment]
The fix for this went into next stream release `34.20210413.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `34.20210427.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `34.20210427.3.0`.
