### ISSUE TITLE
Requesting to add 'sumantrom' to fedora-coreos namespace 

### ISSUE THREAD

**Issue by sumantro93** [coreos/fedora-coreos-tracker#778]
Hey Folks,

I have created a CentOS account and I request to be added to fcos namespace.

Thanks

**Comment by cverna** [comment]
This is to allow @sumantro93 to run the FCOS releases https://github.com/coreos/fedora-coreos-tracker/issues/762

His centos username is sumantrom

**Comment by jlebon** [comment]
Hi Sumantro, can you follow the steps in https://github.com/coreos/fedora-coreos-pipeline#fedora-coreos-pipeline to file a ticket in https://pagure.io/centos-infra?

**Comment by sumantro93** [comment]
Hey, This issue can be closed now. Thanks to FCOS team for all the help!!
