### ISSUE TITLE
Document the FCOS release cadence guidelines

### ISSUE THREAD

**Issue by jdoss** [coreos/fedora-coreos-tracker#785]
It would be nice to have end user documentation of the cadence that we follow for releasing new version of FCOS. Particularly w/r/t Fedora moving between major releases. Here are some example copy of what a release cadence guideline could be:

*General Releases*
We release new `next` versions on X date of the month. This release in `next` stays for Y weeks before being promoted to `testing`. `testing` streams get promoted to `stable` after Z weeks in `testing`. These timeframes are just guidlines we try to follow for doing releases. They may be delayed if we are seeing issues with packages that need to be sorted out before doing a new release. You can see all blocking issues on our issues tracker under the `release blocker` tag.

*Security Releases*
If there are important security updates the FCOS team will issues releases on a case per case basis and these releases will be communicated on the mailing list and you can follow security issues under the `security issue` tag.

*Fedora Release Rebases*
For rebasing on the next version of Fedora we follow the following cadence.

When the next release of Fedora hits Beta we rebase the `next` stream on that release. When the Fedora Beta hits GA we will do a release on `testing` in 2 weeks or so after that date. In another two weeks we will move `testing` to stable.

This copy is just an example. The time frames are made up and open for discussion. This document would allow us to help set some expectations for users on when to see new releases of FCOS while allowing for us to be flexible with our releases to account for stability issues within our core package set.

**Comment by dustymabe** [comment]
Attempt at some wording over in https://github.com/coreos/fedora-coreos-tracker/pull/801 that me and @jlebon came up with.

**Comment by travier** [comment]
We discussed that in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/2QTHMPJIWLWBZ3ZHOXOTFI4DEBXLGHW5/).

We will move with this for this release cycle and might improve tweak for the next release.

**Comment by jdoss** [comment]
I think the wording in #801 solves the Fedora Release Rebases section, but I would love to see some sort of guidelines written out for the processes and cadence for General Releases and Security Releases. These are partly defined in https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#out-of-cycle-releases and https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#production-refs

I guess what I am looking for is something a little more defined, so users can fully aware when one stream moves to the next. For example I am not exactly sure when the next `stable` release is going to happen even today. I am not sure what issues are impacting users in `testing` or `next` and are delaying a `stable` release without being fully in tune with the day to day of the team working on FCOS. 

Having better defined guidelines on releases and maybe release tracker or log of some sort  (A calendar? Not sure.) that people can follow would be super helpful in planning the roll out of updates in production.

**Comment by dustymabe** [comment]
> I think the wording in #801 solves the Fedora Release Rebases section, 

Yep

> but I would love to see some sort of guidelines written out for the processes and cadence for General Releases and Security Releases. These are partly defined in https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#out-of-cycle-releases and https://github.com/coreos/fedora-coreos-tracker/blob/master/Design.md#production-refs

We saw the other sections (the ones you just linked) and thought they handled the request. 

> 
> I guess what I am looking for is something a little more defined, so users can fully aware when one stream moves to the next. For example I am not exactly sure when the next `stable` release is going to happen even today.

from #801 

```
- Fedora General Availability
    - Fedora CoreOS re-orients its release schedule in the following way:
        - Week 0 (GA release): triple release;`next` with latest Fedora N content
        - Week 1: triple release; `testing` release promoted from previous `next`
        - Week 3: triple release; `stable` release promoted from previous `testing`, now fully rebased to Fedora N. `next` and `testing` are now in sync.
```

"triple release" means a new stream release for all of `next`, `testing`, `stable`.  We just put out a `stable` release today (week 0), and we'll put one out again next week (week 1), and another two weeks after that (week 3).

> I am not sure what issues are impacting users in `testing` or `next` and are delaying a `stable` release without being fully in tune with the day to day of the team working on FCOS.

Yeah. It's a bit fluid right now. We need to get more organized, but we also need help getting more organized. Maybe an opportunity for someone to step up and help?

> 
> Having better defined guidelines on releases and maybe release tracker or log of some sort (A calendar? Not sure.) that people can follow would be super helpful in planning the roll out of updates in production.

I don't disagree with you, but I think it's simple enough where the general rule is "every two weeks". The only time we "re-orient" is around Fedora GA, which we just decided to do recently to prevent confusion about timing for every GA release.

Roughly we keep up with the release schedule and who is going to perform the release in the following shared document: https://hackmd.io/WCA8XqAoRvafnja01JG_YA That isn't user facing (and isn't intended to be), but it just let's you know that the goal really is "every two weeks".

**Comment by bgilbert** [comment]
Adding to what @dustymabe said: while we do have a general cadence ("every two weeks"), by policy we don't commit to either a specific release schedule or individual release dates.  Since updates roll out automatically, the idea is that users shouldn't have to explicitly plan (or think about) deployments to their fleet.  Instead, users should 1) configure the Zincati update strategy to express their constraints on updates/reboots, and 2) run the `testing` release and report regressions so we can keep them from reaching `stable`.
