### ISSUE TITLE
Fedora Test day for our `next` stream (Fedora 34)

### ISSUE THREAD

**Issue by JaimeMagiera** [coreos/fedora-coreos-tracker#797]
It's time to schedule a CoreOS test day. FCCT has been renamed to Butane and the extensions of the respective files has been standardized (#780) The Next stream release will be rebased to Fedora 34 the week that it goes GA (see #704). 

The focus of the test day will be:

- Bugs not caught by the CI
- File editors properly handling the new extensions
- Documentation
- Raise Awareness about Fedora CoreOS

Fedora QA ticket will be forthcoming, once the F34 release date is finalized.

**Comment by dustymabe** [comment]
Thanks for opening this!

> Fedora QA ticket will be forthcoming, once the F34 release date is finalized.

I'd say we could probably go ahead and schedule a test day. The content set for f34 is pretty frozen already. The sooner we get information on problems the more we can do about it.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/A7MZMVXHDH6ZNOPXL44D6LK6L4QYKATK/).

```
12:47:40* dustymabe | #agreed We'll schedule and try to run the test day on Monday. Of course, contributions
                    | are welcome throughout the week.                                                      

```

Will reach out to the QA team about scheduling the test day for Monday (04/26).

**Comment by sumantro93** [comment]
> We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/A7MZMVXHDH6ZNOPXL44D6LK6L4QYKATK/).
> 
> ```
> 12:47:40* dustymabe | #agreed We'll schedule and try to run the test day on Monday. Of course, contributions
>                     | are welcome throughout the week.                                                      
> ```
> 
> Will reach out to the QA team about scheduling the test day for Monday (04/26).

Thanks for reaching out
I have created the event and I am going to announce them in a couple of hours.
Wiki : https://fedoraproject.org/wiki/Test_Day:Fedora_34_CoreOS_2021-04-26
Results : https://testdays.fedoraproject.org/events/113


Thanks for reaching out

**Comment by travier** [comment]
We discussed that in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/2QTHMPJIWLWBZ3ZHOXOTFI4DEBXLGHW5/).

We're currently missing Exoscale testing. @jlebon "volunteered" to do that 🙂.

**Comment by dustymabe** [comment]
Thanks to everyone who participated in the test day. It was a huge success with 30+ people submitting results or giving us feedback. Everyone who participated and has a fedora account will get a badge for participation as soon as the badge is published.

Thanks again!
