### ISSUE TITLE
Containers building and delivery ?

### ISSUE THREAD

**Issue by cverna** [coreos/fedora-coreos-tracker#8]
We are currently using OSBS (Openshift Build Service) to build and release containers to registry.fedoraproject.org, we also inherit from containers hosted on Quay.io so the questions is what do we want to do with containers we are building in Fedora ?

**Comment by dustymabe** [comment]
I think this is a discussion that should heavily involve Fedora Release Engineering and Fedora Infra. We should work with them to come up with a solution to this problem. What I will say is that within the RH umbrella, maintaining a single registry vs two separate registries would have value.

**Comment by dustymabe** [comment]
in [today's meeting](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/BGGRMVVU7KLKLSFXJRDURTQFMEEFEPSG/) we decided that it would probably be most appropriate if there was a separate working group within fedora created for containers work/topics @cverna has taken the action item to try to flesh out what this would look like.

**Comment by cverna** [comment]
Sent out an email about starting a Container SIG

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/55QK4AYKBFGLFXCGAVJSXLEVEMC5NJQ2/

**Comment by dustymabe** [comment]
Thanks @cverna !
