### ISSUE TITLE
sarea.h missing

### ISSUE THREAD

**Issue by udovdh** [coreos/fedora-coreos-tracker#800]
**Describe the bug**
After upgrade to Fedora 34 I'd like to build some software that requires sarea.h.
This worked ok on Fedora 33, but after the upgrade sarea.h is no longer there.
So which rpm does provide sarea.h?
Not the xorg-x11-server-devel rpm on my system.

**Reproduction steps**
1. Try to compile xorg-xf86-video-amdgpu from git.
2.
3. 

**Expected behavior**
No error about missing sarea.h
**Actual behavior**
drmmode_display.c:43:10: fatal error: sarea.h: No such file or directory

**System details**
Fedora 34 on AMD Ryzen 5 3400G with Radeon Vega Graphics on Gigabyte X570 AORUS PRO

**Ignition config**
????

**Additional information**

**Comment by lucab** [comment]
Thanks for the report, but I think you wanted to submit this as a general Fedora bug. If so, see https://fedoraproject.org/wiki/Bugzilla.
Fedora CoreOS does not ship Xorg nor a C compiler out of the box.
