### ISSUE TITLE
Installer and grub2-mkconfig do not detect the second ssd

### ISSUE THREAD

**Issue by karnhack** [coreos/fedora-coreos-tracker#802]
Hi,
during the installation of fedora 34 the second windows sdd  was not detected. 
grub2-mkconfig do not detect the second ssd.

When i do:
`sudo grub2-mkconfig -o /boot/grub2/grub.cfg`
or
`sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg`
 the second disk is not detected.

`sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
Generating grub configuration file ...
Adding boot menu entry for UEFI Firmware Settings ...
done`

`sudo grub2-mkconfig -o /boot/grub2/grub.cfg
Generating grub configuration file ...
Adding boot menu entry for UEFI Firmware Settings ...
done`

Regards

Gianluca

**Comment by lucab** [comment]
Thanks for the report, but I think you wanted to submit this as a general Fedora bug. If so, see https://fedoraproject.org/wiki/Bugzilla.
On Fedora CoreOS the `/boot` partition is read-only and shouldn't be manually changed by users.
