### ISSUE TITLE
Rebase to a new version of Fedora (34)

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#808]
# Rebase to a new version of Fedora (34)

## Release engineering changes

- [x] Verify that a few tags have been created. These should have been created by releng scripts on branching: 

- `f${releasever}-coreos-signing-pending`
- `f${releasever}-coreos-continuous`

- [x] The tag info for the coreos-pool tag has the new release (N) and next release (N+1) signing keys (just to stay ahead of the curve) and removes the old release (N-2) signing key. The following commands view the current settings and then update the list to 32/33/34 keys. You'll most likely have to get someone from releng to run the second command (`edit-tag`).

- `koji taginfo coreos-pool`
- `koji edit-tag coreos-pool -x tag2distrepo.keys="12c944d0 9570ff31 45719a39"`

- [x] `koji untag` N-2 packages from the pool (at some point we'll have GC in place to do this for us, but for now we must remember to do this manually or otherwise distRepo will fail once the signed packages are GC'ed). For example the following snippet finds all RPMs signed by the Fedora 32 key and untags them.

Find the key short hash. Usually found [here](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/bodhi2/backend/templates/pungi.rpm.conf.j2). Then:

```
f32key=12c944d0
key=$f32key
untaglist=''
for build in $(koji list-tagged --quiet coreos-pool | cut -f1 -d' '); do
    if koji buildinfo $build | grep $key 1>/dev/null; then
        untaglist+="${build} "
        echo "Adding $build to untag list"
    fi
done
```

Now we have a list of builds to untag. But we need one more sanity check. Let's make sure none of those are actually being used. Fire up the latest FCOS `testing-devel` and run:

```
f32key=12c944d0
key=$f32key
rpm -qai | grep -B 8 $key
```

If there are any RPMs signed by the old key they'll need to be investigated. Maybe they shouldn't be used any longer. Or maybe they're still needed.

After verifying the list looks good:

```
koji untag-build coreos-pool $untaglist
```

Now that untagging is done, give a heads up to rpm-ostree developers that N-2 packages have been untagged and that they may need to update their CI compose tests to freeze on a newer FCOS commit.

## coreos-installer changes

- [x] Update coreos-installer to know about the signing key used for the future new major version of Fedora (N+1). Note that the signing keys for N+1 may not be created until releng branches and rawhide becomes N+1.

## Update [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/) `next-devel`

- [x] Bump `releasever` in `manifest.yaml`
- [x] Update the repos in `manifest.yaml` if needed
- [x] Run `cosa fetch --update-lockfile`
- [x] PR the result

## Ship rebased `next`

- [x] Ship `next`
- [x] Set a new update barrier for N-2 on `next`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/). See [discussion](https://github.com/coreos/fedora-coreos-tracker/issues/480#issuecomment-631724629).

## Update [fedora-coreos-config](https://github.com/coreos/fedora-coreos-config/) `testing-devel`

- [x] Bump `releasever` in `manifest.yaml`
- [x] Update the repos in `manifest.yaml` if needed
- [x] Run `cosa fetch --update-lockfile`
- [x] Bump the base Fedora version in `ci/buildroot/Dockerfile`
- [x] PR the result

## Ship rebased `testing`

- [x] Ship `testing`
- [x] Set a new update barrier for N-2 on `testing`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/).

## Ship rebased `stable`

- [x] Ship `stable`
- [x] Set a new update barrier for N-2 on `stable`. In the barrier entry set a link to [the docs](https://docs.fedoraproject.org/en-US/fedora-coreos/update-barrier-signing-keys/).

## Miscellaneous container updates

These are various containers in use throughout our ecosystem. We should update or open a ticket to track updating them once a new Fedora release is out. If you open a ticket instead of doing the update add a link to the ticket as comment.

- [x] Update coreos-assembler or open ticket to update:
    - [Dockerfile](https://github.com/coreos/coreos-assembler/blob/main/Dockerfile)
- [x] Update coreos-installer
    - [Dockerfile](https://github.com/coreos/coreos-installer/blob/main/Dockerfile)
- [ ] Update fedora-coreos-cincinnati
    - [Dockerfile](https://github.com/coreos/fedora-coreos-cincinnati/blob/main/dist/fedora-infra/Dockerfile)
- [x] Update config-bot
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/config-bot/Dockerfile)
- [x] Update coreos-koji-tagger
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/coreos-koji-tagger/Dockerfile)
    - [ImageStream](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-koji-tagger/templates/imagestream.yml)
    - [BuildConfig](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-koji-tagger/templates/buildconfig.yml)
- [x] Update coreos-ostree-importer
    - [Dockerfile](https://github.com/coreos/fedora-coreos-releng-automation/blob/main/coreos-ostree-importer/Dockerfile)
    - [ImageStream](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/imagestream.yml)
    - [BuildConfig](https://pagure.io/fedora-infra/ansible/blob/main/f/roles/openshift-apps/coreos-ostree-importer/templates/buildconfig.yml)

**Comment by dustymabe** [comment]
https://github.com/coreos/coreos-installer/pull/530

**Comment by dustymabe** [comment]
https://github.com/coreos/fedora-coreos-config/pull/902

**Comment by bgilbert** [comment]
https://github.com/coreos/coreos-installer/pull/529

**Comment by jlebon** [comment]
https://github.com/coreos/fedora-coreos-config/pull/991

**Comment by travier** [comment]
https://github.com/coreos/fedora-coreos-config/pull/997 > Testing moved to F34

**Comment by dustymabe** [comment]
We skipped the update barriers since updating from older releases was [broken](https://github.com/coreos/fedora-coreos-tracker/issues/749) for now, but maybe we should go ahead and put them in place just for consistency for now?

**Comment by dustymabe** [comment]
> We skipped the update barriers since updating from older releases was [broken](https://github.com/coreos/fedora-coreos-tracker/issues/749) for now, but maybe we should go ahead and put them in place just for consistency?

https://github.com/coreos/fedora-coreos-streams/pull/323

**Comment by dustymabe** [comment]
@bgilbert @lucab - Are we unblocked now to move `coreos-installer` and `fedora-coreos-cincinnati` to f34 ? Those are our two remaining checkboxes.

**Comment by bgilbert** [comment]
Looks like F34-based coreos-installer container builds still fail in Quay.  The tracking issue is [PROJQUAY-2006](https://issues.redhat.com/browse/PROJQUAY-2006).

**Comment by lucab** [comment]
https://github.com/coreos/fedora-coreos-cincinnati/pull/46

**Comment by lucab** [comment]
The cluster on fedora-infra seems to have the same problem (EPERM/ENOSYS mismatch) possibly due to an outdated container runtime stack. It's tracked at https://pagure.io/fedora-infrastructure/issue/10111.

**Comment by bgilbert** [comment]
It looks like Quay is fixed now.  Submitted https://github.com/coreos/coreos-installer/pull/617.

**Comment by bgilbert** [comment]
fedora-coreos-cincinnati was reverted in https://github.com/coreos/fedora-coreos-cincinnati/pull/49.

**Comment by travier** [comment]
We are moving to F35 now. How are we here?

**Comment by jlebon** [comment]
Yup, this is clearly done. Good catch @travier!

**Comment by bgilbert** [comment]
We were holding it open for the fedora-coreos-cincinnati Dockerfile bump, but that can equally well be covered by the F35 ticket.
