### ISSUE TITLE
Support PowerVS  - Power Virtual Server (extension to IBMCloud) platform

### ISSUE THREAD

**Issue by Prashanth684** [coreos/fedora-coreos-tracker#815]
The Power Virtual Server platform [1] is an extension of the IBMCloud platform which offers instances of Power systems. The main requirement to support this platform is for Openshift IPI deployments [2]. In order to support this platform we would need:

- platform ID `powervs` to be recognized for this platform by various components. This is mainly needed for ignition, for which this platform would make use of the Openstack way of fetching ignition config as Power Virtual servers are based on the gen1 IBM Cloud which mimics Openstack.
- a `buildextend-powervs` command in coreos-assembler to create powervs specific OVA images. these ova images consists of raw disk images with a particular ovf format required for Power virtual servers
- ore upload support in coreos-assembler to upload images to ibmcloud. PowerVS would require these images to be in a storagebucket in the IBMCloud which can then be retrieved by the Openshift installer to perform IPI deploys. The ore command would apply to the IBMCloud platform rather than the PowerVS platform as the images are stored in IBMCloud.
-  add the new platform `powervs` to the cosa schema in coreos-assembler so that the artifacts can be written into the metadata

[1] https://www.ibm.com/cloud/power-virtual-server
[2] https://github.com/openshift/enhancements/pull/736

**Comment by bgilbert** [comment]
@Prashanth684 Thanks for the ticket.  Could you fill out the "Request a new platform" form linked from the [new ticket page](https://github.com/coreos/fedora-coreos-tracker/issues/new/choose)?

Also, if PowerVS is mostly just Power on IBM Cloud Gen 1, should we just implement it as part of IBM Cloud support, rather than as a separate platform?

**Comment by Prashanth684** [comment]
> @Prashanth684 Thanks for the ticket. Could you fill out the "Request a new platform" form linked from the [new ticket page](https://github.com/coreos/fedora-coreos-tracker/issues/new/choose)?
> 
> Also, if PowerVS is mostly just Power on IBM Cloud Gen 1, should we just implement it as part of IBM Cloud support, rather than as a separate platform?

@bgilbert yes- this is filed as a request for a new platform.

I did think about having it as part of IBMCloud but few reasons led me to think this needs a new platform:
- the images generated for IBMCloud (gen-1 x86) are qemu qcows sized at 100G. the images required for PowerVS are ova images with a specific ovf format (a little different from VMWare) using raw disk image.
- Because this artifact will be referenced in the openshift installer so that they can be used, it would be better if they are referenced in the metadata as `powervs` images as it will only be applicable for a PowerVS install and not an IBMCloud installation (which is not supported today).
- Ignition needs to recognize PowerVS as a separate platform because the way ignition is injected for IBMCloud is not applicable to PowerVS as PowerVS is using the old gen-2 which mimics openstack. So when the method of ignition injection is fetched, it needs to be Openstack and not IBMCloud.
- IBMCloud images are x86 specific whereas PowerVS images would be only ppc64le specific

**Comment by bgilbert** [comment]
I think the platform ID part could use more discussion, but I don't want to split it across two bugs, so I'll close this.  Please fill out the new-platform form using the link I pasted above, and let's continue discussion in that ticket.
