### ISSUE TITLE
Fcos enable gui

### ISSUE THREAD

**Issue by Amos-85** [coreos/fedora-coreos-tracker#820]
I wonder if it's possible to run fcos in kiosk mode with some lightweight desktop ?

**Comment by bgilbert** [comment]
Lots of things are possible.  :slightly_smiling_face:  You could overlay packages, or try running the desktop environment in containers.  It's not really a primary use case for FCOS, though.  Depending on your needs, [Silverblue](https://silverblue.fedoraproject.org/) might be worth a look.

**Comment by dustymabe** [comment]
Hey @Amos-85 - if you'd like to ask more questions like this our [discussion forum](https://discussion.fedoraproject.org/c/server/coreos) is a good place for that.
