### ISSUE TITLE
Group writable files in /etc

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#829]
**Describe the bug**

The following files are group writable in `/etc` when they should not be:

```
$ sudo find /etc -type f -perm /g+w
/etc/group
/etc/crypto-policies/state/current
/etc/iscsi/initiatorname.iscsi
/etc/selinux/config
/etc/systemd/dont-synthesize-nobody
/etc/group-
/etc/passwd
```

Initial fix for rpm-ostree is https://github.com/coreos/rpm-ostree/pull/2824 and this will fix most of those during an update but we need manual handling for passwd/group files as they are marked an modified (M) by ostree:

```
$ sudo ostree admin config-diff | grep -E "group|passwd"   
M    passwd
M    group
A    group-
A    passwd-
```

Corresponding test is in progress in https://github.com/coreos/fedora-coreos-config/pull/1003

**Reproduction steps**

By default

**Expected behavior**

Those files are not group writable.

**Actual behavior**

Those files are group writable.

**System details**

All Fedora CoreOS images I have tested (at least in the last month).

**Ignition config**

N/A

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `34.20210611.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `34.20210611.3.0`.
