### ISSUE TITLE
fully enabling systemd-resolved

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#834]
In the past we enabled systemd-resolved, but disabled the stub listener because of issues related to setting node hostnames using reverse DNS queries. 

context: https://github.com/coreos/fedora-coreos-tracker/issues/649

There continues to be issues with interactions between NetworkManager
and systemd-resolved that make setting the hostname via reverse DNS
unpredictable. 

current status: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/601#note_892280

We should track and work with the upstreams here to get the issues sorted out so we can fully enable `systemd-resolved` in Fedora CoreOS and match the rest of Fedora.

**Comment by travier** [comment]
Hopefully we will have https://github.com/systemd/systemd/issues/8639 too at some point

**Comment by dustymabe** [comment]
> current status: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/601#note_892280

The issues outlined above [are now resolved](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/601#note_992080).

**Comment by dustymabe** [comment]
> The issues outlined above [are now resolved](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/601#note_992080).

Though, the fix has only landed in Fedora 35 so we'll have to make the change in the rebase to F35.

Here is a PR to make that happen passively: https://github.com/coreos/fedora-coreos-config/pull/1112
