### ISSUE TITLE
/etc/skel not used for core/root user

### ISSUE THREAD

**Issue by sgohl** [coreos/fedora-coreos-tracker#847]
**Describe the bug**

Excplicitely adding a user will populate the home directory with the contents of `/etc/skel` as expected, but does not happen with existing `root` or `core` user

**Reproduction steps**
1. provision coreos machine
2. view contents of `~/.bashrc`
3. view contents of `/etc/skel/.bashrc`

**Expected behavior**
even `root` and `core` user should be populated with the contents of `/etc/skel`

**Actual behavior**
does not happen
Why I am actually experiencing the bug, or how I did come across this: I wanted to use the `.bashrc.d` sourcing of optional/additional files and found that this procedure already exists in `/etc/skel/.bashrc` but was not existing in the `.bashrc` of neither `root` nor `core` user.

**System details**
 - Bare Metal/QEMU/AWS/GCP/etc.
 - .. any
 - Fedora CoreOS version
`Fedora CoreOS 34.20210427.3.0`

**Ignition config**
n/a

**Additional information**
n/a

**Comment by jlebon** [comment]
Hmm, I can't reproduce this.

```
[core@cosa-devsh ~]$ diff /home/core/.bashrc /etc/skel/.bashrc
[core@cosa-devsh ~]$ echo $?
0
[core@cosa-devsh ~]$ sudo -i
[root@cosa-devsh ~]# diff ~/.bashrc /etc/skel/.bashrc
[root@cosa-devsh ~]# echo $?
0
```

Can you provide an exact FCOS version along with exact provisioning details?

**Comment by sgohl** [comment]
hm thats strange, did this perhaps come with `Fedora CoreOS 34.20210427.3.0` ?

```
# diff ~/.bashrc /etc/skel/.bashrc
18a19,27
> if [ -d ~/.bashrc.d ]; then
> 	for rc in ~/.bashrc.d/*; do
> 		if [ -f "$rc" ]; then
> 			. "$rc"
> 		fi
> 	done
> fi
> 
> unset rc
```

**Comment by sgohl** [comment]
ok I checked agains a v33 machine, there it's missing, exactly what I need :-D 

(side problem is, v34 broke cups-libs, which is deep dependency for pacemaker, so I can't upgrade right now to 34)

**Comment by sgohl** [comment]
but you can't do anything about that now I see, hence I'll close the issue. Thanks for inspecting though :-)

**Comment by dustymabe** [comment]
> (side problem is, v34 broke cups-libs, which is deep dependency for pacemaker (why on earth I don't know), so I can't upgrade right now to 34)

is there a bugzilla bug for that?

Also, `cups-libs` is getting pulled in on the host because of `samba-client-libs` which is a dep of some of the `sssd` stack. If that need were to ever drop then it would drop out of FCOS. For this reason depending on host packages can be problematic. Could you run your app in a container to isolate yourself from problems like the one you're hitting now and the one I described in the future?

**Comment by sgohl** [comment]
I know it's not recommended, therefore I didn't make a big deal, since some things just solve themselves if you wait long enough, right :-D

Running pacemaker/corosync in containers has other negative side-affects and this is actually one of the very few situations  I  decide: Yes, this really belongs on the Host OS.

Docker runs application workload and I don't want to mix that with system stuff
Podman would be a try worth, but from the docs it is explicitely discouraged to mix docker and podman

**Comment by dustymabe** [comment]
> I know it's not recommended, therefore I didn't make a big deal,

Fair. Hopefully the `cups-libs` issue will be fixed soon.

**Comment by sgohl** [comment]
I'm pretty sure it will fix itself just because both packages/versions are pushed and deps most certainly will be updated vice-versa anyway :-)
