### ISSUE TITLE
Hand over projectatomic/container-best-practices to Fedora Container SIG

### ISSUE THREAD

**Issue by LorbusChris** [coreos/fedora-coreos-tracker#85]
I personally think this would make sense.
I also see a lot of duplication between the [wiki](https://fedoraproject.org/wiki/Container:Guidelines#Container_Guidelines) and that repo. Maybe there should just be a link to the Best Practices in the wiki to just have one source of truth?

RFC.

**Comment by sanjabonic** [comment]
I'll ask Eliska to take a look at this issue and respond.

**Comment by eliskasl** [comment]
Although the overlap, there is still some useful information, which would be pity to discard. So moving the content under Fedora docs and linking to it sounds like a reasonable solution.
But the best practices are not really actively maintained, so it might also be worth if someone reviewed it first and maybe consolidated with the wiki somehow to make sure it's still up-to-date. I'm afraid I won't be able to do it...

**Comment by LorbusChris** [comment]
@eliskasl I agree with you, before removing anything there should be a thorough review and consolidation of all info in one place.

I put this topic on the Container SIG agenda for the next meeting (next Monday, see: https://pagure.io/ContainerSIG/container-sig/issue/21). The group will certainly have to make sure to take responsibility of maintaining the docs in the future. If you're interested, you're cordially invited to join the SIG as well and help distribute any related work within the group!

**Comment by LorbusChris** [comment]
Let's postpone this topic to next weeks mtg, as I won't be there tmrw, and I'll be able to gauge the Container SIG's willingness to take over responsibility for `container-best-practices` only next Monday in the SIG mtg anyways.

**Comment by eliskasl** [comment]
@LorbusChris sounds good. I'll try join as well in case you need me.

**Comment by dustymabe** [comment]
now that this weeks meeting is over I'll add the meeting label back

**Comment by asamalik** [comment]
From the Docs perspective, I can add this repo whenever you're ready. If I remember correctly we've discussed it with @sanjabonic when we were adding [the Silverblue docs](https://docs.fedoraproject.org/en-US/fedora-silverblue/) into the site.

So just let me know when you're ready.

**Comment by LorbusChris** [comment]
working on converting them to Antora docs for use on docs.fp.i now

**Comment by LorbusChris** [comment]
It has been decided to hand off the repo to the Container SIG. While the move hasn't been completed, yet. There is no need to keep this issue open on the tracker.
