### ISSUE TITLE
Clevis error "Error communicating with the server!" on startup

### ISSUE THREAD

**Issue by rugk** [coreos/fedora-coreos-tracker#852]
**Describe the bug**
At boot (finished provisioned device, but no reboot) my device does not detect the network or so.
Thus this is a folllow-up of https://github.com/coreos/fedora-coreos-tracker/issues/827#issuecomment-839911304

**Reproduction steps**
Setup a bare-metal LUKS device with tang encryption.
Boot device. Shutdown. Boot device. (_no_ reboot)

**Expected behavior**
Tang server can be contacted.

**Also:** There was a systemd warning "Timed out waiting for `/dev/…` etc. Maybe this is problematic if the Tang server can later be reached, but the dependency

**Actual behavior**
> clevis-luks-askpass[…]: Error communicating with the server![…]

in a loop… it seems to retry, but always fails.

Even 

**System details**
 - Bare Metal
 - Fedora CoreOS version: 34.20210518.3.0 (IIRC)

Connected via Ethernet.

**Additional information**

I have no idea yet again and thought this was fixed. But it re-appeared… :slightly_frowning_face: 

See also https://github.com/coreos/ignition/issues/1201

I do have confirmed that the pinned tang servers are reachable (I do have a script that just encrypts and decrypts a test secret with the JSON I provide, so that is easy to test) from another device.

Again, booting an USB drive with `fedora-coreos-34.20210427.3.0-live.x86_64` and just rebooting into the live system with a reboot from there, seems to work fine. (as a workaround, however)

**Edit:** Ah, okay, apparently it does not like a "cold boot". I.e. I can also shutdown the device, be fast enough to move the device to another location, start it up and it has network connectivity. However, when I leave it "cold" for a longer time, it fails to boot due to no network connectivity.

**Comment by bgilbert** [comment]
Please post a full console log from the failed boot.

**Comment by bgilbert** [comment]
Closing due to lack of response.  If you can provide logs from a failed boot, please feel free to reopen this bug.

**Comment by ShamimIslam** [comment]
> **Describe the bug** At boot (finished provisioned device, but no reboot) my device does not detect the network or so. Thus this is a folllow-up of [#827 (comment)](https://github.com/coreos/fedora-coreos-tracker/issues/827#issuecomment-839911304)
> 
> **Reproduction steps** Setup a bare-metal LUKS device with tang encryption. Boot device. Shutdown. Boot device. (_no_ reboot)
> 
> **Expected behavior** Tang server can be contacted.
> 
> **Also:** There was a systemd warning "Timed out waiting for `/dev/…` etc. Maybe this is problematic if the Tang server can later be reached, but the dependency
> 
> **Actual behavior**
> 
> > clevis-luks-askpass[…]: Error communicating with the server![…]
> 
> in a loop… it seems to retry, but always fails.
> 
> Even
> 
> **System details**
> 
>     * Bare Metal
> 
>     * Fedora CoreOS version: 34.20210518.3.0 (IIRC)
> 
> 
> Connected via Ethernet.
> 
> **Additional information**
> 
> I have no idea yet again and thought this was fixed. But it re-appeared… slightly_frowning_face
> 
> See also [coreos/ignition#1201](https://github.com/coreos/ignition/issues/1201)
> 
> I do have confirmed that the pinned tang servers are reachable (I do have a script that just encrypts and decrypts a test secret with the JSON I provide, so that is easy to test) from another device.
> 
> Again, booting an USB drive with `fedora-coreos-34.20210427.3.0-live.x86_64` and just rebooting into the live system with a reboot from there, seems to work fine. (as a workaround, however)
> 
> **Edit:** Ah, okay, apparently it does not like a "cold boot". I.e. I can also shutdown the device, be fast enough to move the device to another location, start it up and it has network connectivity. However, when I leave it "cold" for a longer time, it fails to boot due to no network connectivity.

Are you still out there? Looking for some assistance to emulate a similar setup.
