### ISSUE TITLE
kola: ext.config.kdump investigate failures on aarch64 and cloud platforms

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-tracker#860]
The kdump test is currently QEMU on x86_64 only.

To improve the situation here, we need to investigate:

- QEMU aarch64 failures (in rawhide as of 2021-10-19)
- Failures and/or support on cloud platforms:
  - AWS
  - GCP
  - Azure
  - etc.

----

The kdump test from https://github.com/coreos/fedora-coreos-config/pull/1043 has been disabled in https://github.com/coreos/fedora-coreos-config/pull/1053.

https://github.com/coreos/fedora-coreos-config/pull/1043#issuecomment-859028582:

> This test seems to be failing on our cloud platforms. For example with the lastest `testing-devel` (`34.20210610.20.0`) all three cloud platforms failed:
> 
> - [AWS](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-aws/451/)
> - [OpenStack](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-openstack/216/)
> - [GCP](https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/job/kola-gcp/435/)

https://github.com/coreos/fedora-coreos-config/pull/1043#issuecomment-859212045:

> This is also failing CoreOS CI for Ignition.  The `console.txt` of the failed test has a variety of errors in it:
>
> ```
> [    1.927308] systemd[1]: /usr/lib/systemd/system/kdump-capture.service:23: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
> [    1.930253] systemd[1]: /usr/lib/systemd/system/kdump-capture.service:24: Standard output type syslog+console is obsolete, automatically updating to journal+console. Please update your unit file, and consider removing the setting altogether.
> [    3.260866] mount[360]: mount: /kdumproot/sysroot: unknown filesystem type 'xfs'.
> [    3.324660] systemd[1]: kdumproot-sysroot.mount: Mount process exited, code=exited, status=32/n/a
> [    3.330266] systemd[1]: kdumproot-sysroot.mount: Failed with result 'exit-code'.
> [    3.338024] systemd[1]: Failed to mount /kdumproot/sysroot.
> /lib/kdump-logger.sh: line 91: logger: command not found
> [    3.807210] kdump[419] No '/dev/log' or 'logger' included for syslog logging
> failed to initiate the kdump logger.
> [    3.846470] systemd[1]: kdump-error-handler.service: Main process exited, code=exited, status=1/FAILURE
> [    3.853033] systemd[1]: kdump-error-handler.service: Failed with result 'exit-code'.
> [    3.972374] systemd[1]: Requested transaction contradicts existing jobs: Transaction for kdump-error-handler.service/start is destructive (ignition-virtio-dump-journal.service has 'start' job queued, but 'stop' is included in transaction).
> ```

**Comment by dustymabe** [comment]
@travier - you working on fixing this?

**Comment by travier** [comment]
Blocked by https://bugzilla.redhat.com/show_bug.cgi?id=2003780 as long as we are on F34. F35 should be OK.

**Comment by gursewak1997** [comment]
Online platform failure fix: https://github.com/coreos/coreos-assembler/pull/2639
Skip test in coreos-installer: https://github.com/coreos/coreos-installer/pull/750
Skip test in afterburn: https://github.com/coreos/afterburn/pull/686

Issue for kdump.crash failure in coreos-installer and afterburn repos: https://github.com/coreos/fedora-coreos-tracker/issues/1075

Re-enable test in kola-denylist: https://github.com/coreos/fedora-coreos-config/pull/1420

**Comment by dustymabe** [comment]
Nice work @gursewak1997!
