### ISSUE TITLE
New Package Request: Falco security

### ISSUE THREAD

**Issue by JarleB** [coreos/fedora-coreos-tracker#863]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)
No

2. What is the size of the package and its dependencies?
A few Megabytes 

3. What problem are you trying to solve with this package? Or what functionality does the package provide?
Be able to run Falco security , https://falco.org/ on FCOS. 

4. Can the software provided by the package be run from a container?  Explain why or why not.
No. Antipattern for both security and deps. Need kernel-devel/headers to build ebpf-/kernel-module. Breaks the minimalistic/immutable properties of FCOS

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?
Absolutely, "Falco, the cloud-native runtime security project, is the de facto Kubernetes threat detection engine"

6. Can the tool(s) provided by the package be helpful in debugging networking issues?
N/A (or see point 5. )

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.
To be able to deploy Falco as a daemonset in okd4, at least the ebpf/kernel module must already be available in base-os

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?
....?

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)
Don't know 

10. Does the software provided by the package have a history of CVEs?
https://www.cvedetails.com/product/54984/Falco-Falco.html?vendor_id=19887

**Comment by lucab** [comment]
Thanks for the report. From a quick lock I didn't spot any `falco` package in Fedora, what's the name of the package there?

**Comment by LorbusChris** [comment]
It looks like one can run Falco as a DaemonSet on K8s, which I think would be preferable here: https://github.com/falcosecurity/falco-security-workshop/blob/master/exercise2/k8s-using-daemonset/README.md

**Comment by JarleB** [comment]
@lucab it is not i Fedora. @LorbusChris yes, that is probably a better approach. I'll try that direction first.
