### ISSUE TITLE
rawhide: irqbalance package was retired

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#865]
https://src.fedoraproject.org/rpms/irqbalance/c/5c113c69b1cd0386a0b1c6ccf4854569223e2a14?branch=rawhide

This is causing builds in our rawhide stream to fail. Do we care about this package enough to take any action? If no, we'll need to remove it from our manifests.

**Comment by jlebon** [comment]
Looks like the maintainer left Red Hat: https://pagure.io/fesco/issue/2587.

I suspect it'll probably come back alive under new maintainership, though until then we don't really have a choice in removing it from rawhide unless one of us is willing to maintain it.

**Comment by jlebon** [comment]
@ryncsn or @contyk might have more information.

**Comment by ryncsn** [comment]
Hi, currently I maintain irqbalance package in RHEL, but not in Fedora, I can help maintain the Fedora package.

**Comment by dustymabe** [comment]
hey @ryncsn - that's awesome! I think the procedures for trying to revive a package are listed here:

https://fedoraproject.org/wiki/Orphaned_package_that_need_new_maintainers

**Comment by dustymabe** [comment]
If you go to https://src.fedoraproject.org/rpms/irqbalance# and click on the `retired` button on the left hand side of the page it will pop up and auto populate a releng ticket you can fill out.

**Comment by miabbott** [comment]
FWIW, the history for inclusion of `irqbalance` goes back to a requirement from RHCOS/OpenShift - https://github.com/coreos/fedora-coreos-config/pull/158

**Comment by cgwalters** [comment]
It's completely stupid that a package can still be removed, yet listed in our list of things to ship.

**Comment by cgwalters** [comment]
OK I clicked the "unretire" button at https://pagure.io/releng/issue/10183

**Comment by dustymabe** [comment]
New build should hit rawhide repos in the next compose: https://koji.fedoraproject.org/koji/buildinfo?buildID=1776698

Thanks @cgwalters for taking care of this.
