### ISSUE TITLE
Support converting the live ISO into a minimal live ISO

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-tracker#868]
This is a tracker ticket. See details in https://github.com/coreos/coreos-installer/pull/559 for the proposal and keep all discussions there.

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/4IRREF6EHWWRXX5C7A56KX7ZEX74A7BR/).

```
  * AGREED: we will ship tooling to generate a minimal ISO image for
    those who need it, but we won't ship it as a separate artifact to
    try to reduce confusion for users who might not understand the
    differences  (dustymabe, 16:40:07)
```

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-installer/pull/559 is now merged. Next step is to wait for a release and to enable `--miniso` by default in `cosa buildextend-live`.

Let's keep this open to track the feature actually landing in FCOS.

**Comment by jlebon** [comment]
> [coreos/coreos-installer#559](https://github.com/coreos/coreos-installer/pull/559) is now merged. Next step is to wait for a release and to enable `--miniso` by default in `cosa buildextend-live`.

https://github.com/coreos/coreos-assembler/pull/2579

**Comment by dustymabe** [comment]
coreos-installer v0.11.0 was released

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `35.20211119.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `35.20211119.3.0`.

**Comment by jlebon** [comment]
The CLI for this is documented at https://coreos.github.io/coreos-installer/cmd/iso/#coreos-installer-iso-extract-minimal-iso. We should have more user-friendly docs under some other section.

**Comment by jlebon** [comment]
User-friendly docs added in https://github.com/coreos/fedora-coreos-docs/pull/355 :arrow_right: https://docs.fedoraproject.org/en-US/fedora-coreos/live-reference/#_using_the_minimal_iso_image.
