### ISSUE TITLE
CoreOS randomly failed to boot when install to disk on bare metal

### ISSUE THREAD

**Issue by khuedoan** [coreos/fedora-coreos-tracker#870]
**Describe the bug**

CoreOS randomly failed to boot on some bare metal machines when install to disk, and the one booted successfully has some failed systemd services due to read-only fiile system (`systemd-rfkill.service` and `systemd-rfkill.socket`)

The symptoms look similar to https://github.com/coreos/fedora-coreos-tracker/issues/483 and https://github.com/coreos/fedora-coreos-tracker/issues/488

**Reproduction steps**

1. PXE boot bare metal machines from the network (GRUB config bellow)
2. Install to disk (Ignition install config below)
3. Reboot

**Expected behavior**

All machines boot successfully.

**Actual behavior**

Some failed to boot, I've tried again multiple times on the same set of machines and the failed one(s) is random (usually 1-2 out of 4 machines, sometimes none of them failed).
It only happens when install to disk, I haven't seen the issue when booting directly from the network.

**System details**

 - Bare metal
 - I've tried the following Fedora CoreOS versions:
   - `stable/builds/34.20210518.3.0`
   - `testing/builds/34.20210529.2.0`
   - `next/builds/34.20210529.1.0`
   - `stable/builds/34.20210529.3.0` (currently using)

**Ignition config**

Full config:

```yaml
variant: fcos
version: 1.3.0

passwd:
  users:
    - name: root
      ssh_authorized_keys:
        - ssh-ed25519 xxx

storage:
  files:
    # Set hostname
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: metal2
    # Set static IP
    - path: /etc/NetworkManager/system-connections/eno1.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=eno1
          type=ethernet
          interface-name=eno1
          permissions=
          [ipv4]
          address1=192.168.1.112/24,192.168.1.1
          dns=8.8.8.8;
          dns-search=
          method=manual

  links:
    # Set timezone
    - path: /etc/localtime
      target: /usr/share/zoneinfo/xxx/yyy

systemd:
  units:
    # iSCSI for Longhorn
    - name: iscsid.service
      enabled: true
```

I also tried a minimal config:

```yaml
variant: fcos
version: 1.3.0

passwd:
  users:
    - name: root
      ssh_authorized_keys:
        - ssh-ed25519 xxx
```

Then I use Butane to produce JSON files with the following options `butane --pretty --strict`

**Additional information**

GRUB config for PXE boot (rootfs.img extracted from the ISO):

```
set timeout=1

menuentry 'CoreOS (Live)' {
    linux vmlinuz \
        ip=dhcp \
        ignition.platform.id=metal \
        coreos.live.rootfs_url=http://192.168.1.19/CoreOS/images/pxeboot/rootfs.img \
        coreos.inst.install_dev=/dev/sda \
        coreos.inst.ignition_url=http://192.168.1.19/ignition/${net_default_mac}.json
    initrd initrd.img ignition.img
}
```

Screenshot with the default log level (DEBUG):

![image](https://user-images.githubusercontent.com/27996771/122335318-47e88780-cf65-11eb-85a6-d97e07dd3fe9.png)

Screenshot with WARNING log level:

![image](https://user-images.githubusercontent.com/27996771/122335429-78302600-cf65-11eb-86a7-ecd20f9daac7.png)

Failed services (on the machines that booted successfully):

```
Fedora CoreOS 34.20210529.3.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/

[systemd]
Failed Units: 2
  systemd-rfkill.service
  systemd-rfkill.socket
```

`systemctl status systemd-rfkill`

```
× systemd-rfkill.service - Load/Save RF Kill Switch Status
     Loaded: loaded (/usr/lib/systemd/system/systemd-rfkill.service; static)
     Active: failed (Result: exit-code) since Thu 2021-06-17 10:29:25 +07; 1h 21min ago
TriggeredBy: × systemd-rfkill.socket
       Docs: man:systemd-rfkill.service(8)
    Process: 957 ExecStart=/usr/lib/systemd/systemd-rfkill (code=exited, status=238/STATE_DIRECTORY)
   Main PID: 957 (code=exited, status=238/STATE_DIRECTORY)
        CPU: 1ms

Jun 17 10:29:25 metal0 systemd[1]: Starting Load/Save RF Kill Switch Status...
Jun 17 10:29:25 metal0 systemd[957]: systemd-rfkill.service: Failed to set up special execution directory in /var/lib: Read-only fil>
Jun 17 10:29:25 metal0 systemd[957]: systemd-rfkill.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-rfkill>
Jun 17 10:29:25 metal0 systemd[1]: systemd-rfkill.service: Main process exited, code=exited, status=238/STATE_DIRECTORY
Jun 17 10:29:25 metal0 systemd[1]: systemd-rfkill.service: Failed with result 'exit-code'.
Jun 17 10:29:25 metal0 systemd[1]: Failed to start Load/Save RF Kill Switch Status.
Jun 17 10:29:25 metal0 systemd[1]: systemd-rfkill.service: Start request repeated too quickly.
Jun 17 10:29:25 metal0 systemd[1]: systemd-rfkill.service: Failed with result 'exit-code'.
Jun 17 10:29:25 metal0 systemd[1]: Failed to start Load/Save RF Kill Switch Status.
```

`systemctl status systemd-rfkill.socket`

```
× systemd-rfkill.socket - Load/Save RF Kill Switch Status /dev/rfkill Watch
     Loaded: loaded (/usr/lib/systemd/system/systemd-rfkill.socket; static)
     Active: failed (Result: service-start-limit-hit) since Thu 2021-06-17 10:29:25 +07; 1h 31min ago
   Triggers: ● systemd-rfkill.service
       Docs: man:systemd-rfkill.socket(8)
     Listen: /dev/rfkill (Special)

Jun 17 10:29:25 metal0 systemd[1]: Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
Jun 17 10:29:25 metal0 systemd[1]: systemd-rfkill.socket: Failed with result 'service-start-limit-hit'.
```

This is a lab environment so I can tear it down and try again to get any missing logs (if needed).

Thanks in advance.

**Comment by jlebon** [comment]
> Failed to set up special execution directory in /var/lib: Read-only fil

Hmm, `/var` read-only sounds like the `/var` mount failed. What does `systemctl status var.mount` say?
Is there any way you could post the full journal logs from the boot?

**Comment by khuedoan** [comment]
Hi @jlebon, `var.mount` on the one that booted successfully looks good:

`systemctl status var.mount`

```
● var.mount - /var
     Loaded: loaded (/run/systemd/generator/var.mount; generated)
     Active: active (mounted) since Sat 2021-06-19 20:47:59 UTC; 18min ago
      Where: /var
       What: /dev/sda4
       Docs: man:ostree(1)
      Tasks: 0 (limit: 18977)
     Memory: 0B
        CPU: 2ms
     CGroup: /system.slice/var.mount

Jun 19 20:47:59 localhost systemd[1]: Mounting /var...
Jun 19 20:47:59 localhost systemd[1]: Mounted /var.
```

However `var.mount` service is not found using the emergency shell on the failed one.

I get the journal log through the emergency shell on the failed machine and boot to a live USB to get it, here's the full [journal.log](https://github.com/coreos/fedora-coreos-tracker/files/6681342/journal.log).

**Comment by khuedoan** [comment]
Update: if I go to the emergency shell on first boot (without reboot), the journal looks different 
[journal.log](https://github.com/coreos/fedora-coreos-tracker/files/6681384/journal.log) and `ostree-remount.service` is failed:

![image](https://user-images.githubusercontent.com/27996771/122656377-36c99180-d184-11eb-9cf8-0b14c3740677.png)

Looks similar to this one https://github.com/coreos/fedora-coreos-tracker/issues/867, although I'm on x86_64.

**Comment by jlebon** [comment]
OK yup, this looks like the same issue as https://github.com/coreos/fedora-coreos-tracker/issues/746. Closing as dupe.
