### ISSUE TITLE
F35: CHANGE: CompilerPolicy Change

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#872]
In https://github.com/coreos/fedora-coreos-tracker/issues/856 (a result of the [video community meeting on 06/02/2021](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/CWOBSRG7B7PNRQHQ3F5VWGX55Q6TBWM5/)) we went over the proposed changes for Fedora 35. We decided to discuss further the following change:

- DISCUSS [CompilerPolicy Change](https://fedoraproject.org/wiki/Changes/CompilerPolicy)
    - Fedora has historically forced packages to build with GCC unless the upstream project for the package only supported Clang/LLVM. This change proposal replaces that policy with one where, given a good technical reason, a packager may:
    - Tracking bug: [#1960295](https://bugzilla.redhat.com/1960295)
    - rpm-ostree may benefit from [cross-language LTO](https://blog.llvm.org/2019/09/closing-gap-cross-language-lto-between.html) if using clang

**Comment by jlebon** [comment]
@JaimeMagiera said he'll take this one.

**Comment by dustymabe** [comment]
We discussed this in the [community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/DMJDZWOXQTFOTNSXVTXAVUFFRWDXXR54/). This is about changing it so that tools that prefer Clang/LLVM have more flexibility to do so. In our Fedora CoreOS space none of the tools that we know of use Clang/LLVM. For the tools outside of our space (in the rest of Fedora Linux) we'll open bugs if we find issues.
