### ISSUE TITLE
F35: CHANGE: DNS Over TLS

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#873]
In https://github.com/coreos/fedora-coreos-tracker/issues/856 (a result of the [video community meeting on 06/02/2021](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/CWOBSRG7B7PNRQHQ3F5VWGX55Q6TBWM5/)) we went over the proposed changes for Fedora 35. We decided to discuss further the following change:

- DISCUSS [DNS Over TLS](https://fedoraproject.org/wiki/Changes/DNS_Over_TLS)
    - Fedora will attempt to use DNS over TLS (DoT) if supported by configured DNS servers.
    - Tracking bug: [#1889901](https://bugzilla.redhat.com/1889901)

**Comment by darkmuggle** [comment]
After researching this, this won't affect anything. The default is try to use DNS over HTTP if the resolver supports the protocol, otherwise fall back to good 'ole UDP. The upstream debates about DNS over TLS and support over DNSSec for some of the resolvers are really unrelated to how FCOS will use DNS.

**Comment by dustymabe** [comment]
Thanks @darkmuggle!

**Comment by rugk** [comment]
> The default is try to use DNS over HTTP if the resolver supports the protocol, otherwise fall back to good 'ole UDP. 

Hmm, but [if I read the change correctly](https://fedoraproject.org/wiki/Changes/DNS_Over_TLS), this is different to what Fedora proposes there?
I.e. the upstream change wants to use DoT and you say here CoreOS will use DoH by default – or was this a mistake?

**Comment by bgilbert** [comment]
I think @darkmuggle probably misspoke, and meant to say DNS over TLS rather than DNS over HTTP.
