### ISSUE TITLE
F35: CHANGE: "Fedora Linux" in /etc/os-release

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#874]
In https://github.com/coreos/fedora-coreos-tracker/issues/856 (a result of the [video community meeting on 06/02/2021](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/CWOBSRG7B7PNRQHQ3F5VWGX55Q6TBWM5/)) we went over the proposed changes for Fedora 35. We decided to discuss further the following change:

- DISCUSS ["Fedora Linux" in /etc/os-release](https://fedoraproject.org/wiki/Changes/Fedora_Linux_in_os-release)
    - "Fedora" is the name of our project. Our general-purpose Linux distribution is "Fedora Linux". Let's refer to it that way in the OS itself.
    - Tracking bug: [#1944428](https://bugzilla.redhat.com/1944428)
    - walters: Is it Fedora Linux CoreOS?

**Comment by jlebon** [comment]
The change where this happened is https://src.fedoraproject.org/rpms/fedora-release/c/b1eda072639e23d7c857f2d6ac7b4f946aa1c28b?branch=rawhide. Though it doesn't seem to be in the latest rawhide FCOS builds yet.

That said, for generating the `coreos` variant, the spec does [a sed like this](https://src.fedoraproject.org/rpms/fedora-release/blob/rawhide/f/fedora-release.spec#_936):

```
sed -i -e 's|PRETTY_NAME=.*|PRETTY_NAME="Fedora CoreOS %{dist_version}"|'
```

which means that the `PRETTY_NAME` shouldn't actually change. Though `NAME` will.

To be revisited once that change is in a rawhide build.

**Comment by dustymabe** [comment]
`fedora-release-35-0.11.noarch.rpm` is now in rawhide, should include that change.
