### ISSUE TITLE
F36: CHANGE: OpenSSL3.0

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#876]
In https://github.com/coreos/fedora-coreos-tracker/issues/856 (a result of the [video community meeting on 06/02/2021](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/CWOBSRG7B7PNRQHQ3F5VWGX55Q6TBWM5/)) we went over the proposed changes for Fedora 35. We decided to discuss further the following change:

- RELEVANT [OpenSSL3.0](https://fedoraproject.org/wiki/Changes/OpenSSL3.0)
    - The OpenSSL package is rebased to version 3.0 and the dependent packages are rebuilt.
    - Tracking bug: [#1825937](https://bugzilla.redhat.com/1825937)
    - Affects e.g. `rpm-ostree` and `coreos-installer`, https://gitlab.com/redhat/centos-stream/rpms/rpm-ostree/-/merge_requests/2

**Comment by lucab** [comment]
For rpm-ostree, https://github.com/coreos/rpm-ostree/pull/2921 landed as part of release `2021.6`.

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/D4U4Q7JM2FTZPV5J7CWH4OXPI7TOQ2ZQ/).

```
#info lucab is tracking all changes for openssl and we should be able to close out #876 soon
```

When all of the linked changes in https://github.com/coreos/fedora-coreos-tracker/issues/876#issuecomment-871579160 merge and are packaged we can close this out. According to Luca: "golang things are not concerned, and the only C things are ostree and rpm-ostree which I think are already fine".

**Comment by lucab** [comment]
This has been postponed to F36.

**Comment by lucab** [comment]
The last one on my list was the bootupd, which got completed today.
I'm closing this ticket now, and when the mass update/rebuild happens we can deal with further issues that get discovered (if any).
