### ISSUE TITLE
F35: CHANGE: RPM 4.17

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#877]
In https://github.com/coreos/fedora-coreos-tracker/issues/856 (a result of the [video community meeting on 06/02/2021](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/CWOBSRG7B7PNRQHQ3F5VWGX55Q6TBWM5/)) we went over the proposed changes for Fedora 35. We decided to discuss further the following change:

- INVESTIGATE [RPM 4.17](https://fedoraproject.org/wiki/Changes/RPM-4.17)
    - Update RPM to the 4.17 release.
    - Tracking bug: [#1951105](https://bugzilla.redhat.com/1951105)
    - http://rpm.org/wiki/Releases/4.17.0

**Comment by jlebon** [comment]
Only thing worth noting with this release is:

> Remove Berkeley DB database backend (`%db_backend bdb`)

I.e. no more read-only support even. There's some related work going on in rpm-ostree, but overall I think we're in a good position to handle this.
