### ISSUE TITLE
F35: CHANGE: DNF/RPM Copy on Write enablement for all variants

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#878]
In https://github.com/coreos/fedora-coreos-tracker/issues/856 (a result of the [video community meeting on 06/02/2021](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/CWOBSRG7B7PNRQHQ3F5VWGX55Q6TBWM5/)) we went over the proposed changes for Fedora 35. We decided to discuss further the following change:

- DISCUSS [DNF/RPM Copy on Write enablement for all variants](https://fedoraproject.org/wiki/Changes/RPMCoW)
    - RPM Copy on Write provides a better experience for Fedora Users as it reduces the amount of I/O and offsets CPU cost of package decompression. RPM Copy on Write uses reflinking capabilities in btrfs, which is the default filesystem in Fedora 33 for most variants.
    - Tracking bug: [#1915976](https://bugzilla.redhat.com/1915976)
    - walters: Needs validation it doesn't break rpm-ostree

**Comment by cgwalters** [comment]
This didn't land in Fedora AFAICS.  I think their current focus is CentOS Stream: https://blog.centos.org/2021/06/centos-hyperscale-sig-quarterly-report-for-2021q2/
