### ISSUE TITLE
New Package Request: oci-seccomp-bpf-hook

### ISSUE THREAD

**Issue by jhrozek** [coreos/fedora-coreos-tracker#887]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)
  bcc-0.20.0-2.fc34.x86_64
  clang-libs-12.0.0-2.fc34.x86_64
  clang-resource-filesystem-12.0.0-2.fc34.x86_64
  libbpf-2:0.3.0-2.fc34.x86_64
  llvm-libs-12.0.0-2.fc34.x86_64
  oci-seccomp-bpf-hook-1.2.2-0.1.git4e42394.fc34.x86_64

2. What is the size of the package and its dependencies?
results of `rpm -q $name --queryformat='%{size}\n'`:
bcc 2152868
clang-libs 90235858
clang-resource-filesystem 6
libbpf 254052
llvm-libs 96675248
oci-seccomp-bpf-hook 3537618

3. What problem are you trying to solve with this package? Or what functionality does the package provide?
We want to enable people to generate seccomp profiles for their workloads (see e.g. [this blog post](https://podman.io/blogs/2019/10/15/generate-seccomp-profiles.html). This is especially in the context of the security profiles operator for OCP, although I guess this functionality might be useful for FCOS users as well.

4. Can the software provided by the package be run from a container?  Explain why or why not.
No, OCI hooks need to be installed on the container host.

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?
Not directly container runtime issues, but enabling more secure use of containers.

6. Can the tool(s) provided by the package be helpful in debugging networking issues?
Not really

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.
Yes, it is. The main consumer we're thinking about is the [security profiles operator](https://github.com/openshift/enhancements/pull/745) we're trying to include in OCP. For OCP purposes, it would actually be OK if the seccomp bpf hook was included as an extension, but I don't know what is the process for a new extension, I only know our team requested usbguard as an extension, but that was while extensions were being developed and usbguard was iirc the first consumer.

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?
N/A

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)
I don't think so

10. Does the software provided by the package have a history of CVEs?
I don't think so, at least a  cursory look at their git log and a quick search doesn't show anything

For easier evaluation, here is an FCOS config repo with the package added: https://github.com/jhrozek/fcos-with-seccomp-bpf
Note that the dependencies of several packages were trimmed quite recently in fedora, so you'd have to use fairly new package versions. I used FCOS's testing-devel.

**Comment by jlebon** [comment]
The dependencies make this a really tough sell. Could be interesting to investigate a kind of priming mechanism which allows compiling the filter inside a container which the hook could then use. That should allow dropping most of the deps there.

I suspect in a cluster context it'd make sense to build the profile on one host before propagating to the whole cluster. So I think this would be a good candidate for an `rpm-ostree install --transient` where it installs the package but only for the current boot so that you can build the profile.

**Comment by cgwalters** [comment]
I also think it'd be technically possible to have this oci hook itself run as a privileged container (that should not be traced of course).  That would avoid dragging llvm etc. into the host.

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/D4U4Q7JM2FTZPV5J7CWH4OXPI7TOQ2ZQ/).

```
2021-07-21 13:09:46  dustymabe  #agreed Given the required dependencies and the specifics of the
                                use case we think this is a good candidate for package layering/extensions
                                and not for inclusion in the base OSTree. The seccomp profiles can also be
                                generated offline and included via Ignition, which will remove the need to
                                have it installed at all.
```

@jhrozek - maybe we can coordinate with the OKD community to see if we can get this easily added as an extension there?

**Comment by LorbusChris** [comment]
naive question due unfamiliarity with this: Is it possible to package the pre-generated profile in an RPM, or is there some system/machine specific config required to generate it?

We should put this on the OKD WG call agenda. cc @vrutkovs @travier

**Comment by vrutkovs** [comment]
Indeed, that seems to fit OKD (and Typhoon?) better.

**Comment by jhrozek** [comment]
> Indeed, that seems to fit OKD (and Typhoon?) better.

Right, an extension is totally fine with me (see the opening comment :-))

I just didn't know how to request one -- feel free to point me to the right direction and I'll create an issue or whatever else is needed.

Thanks everyone for the input!

**Comment by jhrozek** [comment]
> naive question due unfamiliarity with this: Is it possible to package the pre-generated profile in an RPM, or is there some system/machine specific config required to generate it?
> 

I guess you could, but the main use-case at least for me is [the security profiles operator](https://github.com/kubernetes-sigs/security-profiles-operator) where you'd create the profiles as k8s objects and the operator would take care of writing them to the disk. Similarly the other way around (which is the point of the bpf hook...), once recorded, the operator takes care of grabbing the profile from the disk and creating a k8s object

> We should put this on the OKD WG call agenda. cc @vrutkovs @travier

Thank would be nice, please let me know if I should do something from my end

**Comment by miabbott** [comment]
> I just didn't know how to request one -- feel free to point me to the right direction and I'll create an issue or whatever else is needed.

We don't have a well defined process for requesting a new extension for OCP/RHCOS, but there are two parts:

1. shipping the bits in RHCOS/machine-os-content
2. supporting the extension in MCO

You can start by opening a PR for your proposed extension with changes to [extensions.yaml](https://github.com/openshift/os/blob/master/extensions.yaml)

**Comment by jhrozek** [comment]
> > I just didn't know how to request one -- feel free to point me to the right direction and I'll create an issue or whatever else is needed.
> 
> We don't have a well defined process for requesting a new extension for OCP/RHCOS, but there are two parts:
> 
>     1. shipping the bits in RHCOS/machine-os-content
> 
>     2. supporting the extension in MCO
> 
> 
> You can start by opening a PR for your proposed extension with changes to [extensions.yaml](https://github.com/openshift/os/blob/master/extensions.yaml)

Done: https://github.com/openshift/os/pull/596

I'm going to close this issue, then. Thanks again for the discussion.
