### ISSUE TITLE
Flock to Fedora 2021 (5th to 7th August 2021) - CFP closes 23rd July

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-tracker#894]
[Nest with Fedora](https://flocktofedora.org/)
> Flock is the Fedora Project's annual contributor-focused conference. It typically alternates between European and North American locations. The conference provides a venue for face to face meetings and conversations. It is also a place to celebrate our community.
> 
> Due to COVID-19, we will not have an in-person Flock this year. But we still want to do something fun, so we're bringing back Nest With Fedora! The safety of our community is the most important thing, and we look forward to getting everyone together in 2022.

Nest with Fedora 2021 is from 5th to 7th August 2021. The CFP closes 23rd of July: https://communityblog.fedoraproject.org/update-nest-with-fedora-cfp-registration-open/

Submissions should be at https://pagure.io/flock/issues

Is anyone interested in submitted a session about Fedora CoreOS?

**Comment by jdoss** [comment]
I just submitted this [CfP](https://pagure.io/flock/issue/322) to talk about using Ansible to drive the deployment of a single node FCOS install using my company's [selfhost installer](https://github.com/forem/selfhost).

**Comment by dustymabe** [comment]
thanks @jdoss!

FYI, All, the CFP has [been extended](https://lists.fedoraproject.org/archives/list/devel-announce@lists.fedoraproject.org/thread/AK42WP2CHGTXEIOZA6ILRO7ITXP4KYOX/) to July 23rd.

**Comment by dustymabe** [comment]
CFP is closed.. Should we close this?

**Comment by travier** [comment]
Both talks got accepted!

**Comment by travier** [comment]
https://fedoraproject.org/wiki/Nest_with_Fedora_2021_Schedule
