### ISSUE TITLE
Dependency failure for ignition completion on IBMCloud

### ISSUE THREAD

**Issue by gnavgire** [coreos/fedora-coreos-tracker#899]
**Describe the bug**
Not able to boot the latest stable fedora-coreos-34.20210611.3.0-ibmcloud.x86_64.qcow2 image in IBM Cloud

**Reproduction steps**
1. Followed the instructions given in https://docs.fedoraproject.org/my/fedora-coreos/provisioning-ibmcloud/ for latest stable image.
2. Create a VM using the image, I created a bx2-2x8 instance with the standard 100GB boot volume.
3. Not able to ssh into the VM and VNC Console shows logs showing Dependency failure for ignition completion 

**Expected behavior**
Should have been able to successfully boot the image 

**Actual behavior**
The instance enters into maintenance mode

**System details**
 - IBMCloud
 - fedora-coreos-34.20210611.3.0-ibmcloud.x86_64

**Ignition config**
NA

**Additional information**
NA

**Comment by gnavgire** [comment]
there is no .ign for ibmcloud in the image and the cidata is also not getting mounted

**Comment by lucab** [comment]
Thanks for the report. Console logs should give you a better idea of what is failing.
If you are using a custom Ignition configuration, please run it through [ignition-validate](https://github.com/coreos/ignition#config-validation) upfront to make sure that it is valid.

**Comment by gnavgire** [comment]
The console logs show "There is no config directory at /usr/lib/ignition/base.platform.d/ibmcloud' and Later gives message "Dependency failed for Ignition Completion"

**Comment by gnavgire** [comment]
I was using a ignition file as user-data that was trying to set hostname already set from vendor-data causing the system to fail to rewrite the hostname and hence instance failure.
