### ISSUE TITLE
Goals for build tools

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/fedora-coreos-tracker#9]
We should decide on goals (and anti-goals) for what we want from the FCOS build system. We should use them to decide what tools we can use already, what needs to be modified to meet them, and what needs to be built.

This is meant more as "I want to be able to do X" not "I want to use project Y".

**Comment by ajeddeloh** [comment]
Things I would like:
 - Distro independence: I should be able to build a FCOS image on any modern distro (not just rpm based ones). Having some sort of chroot/container image is fine as long as tooling makes it not-painful. This also has the advantage of ensuring the same version of the tools are used to build the image.
 - Developer workflow should be as close to release workflow as possible. Ideally the only difference should be any signing that happens for official builds
 - Builds should be as reproducable as possible
 - Builds shouldn't _require_ external infrastructure (aside from hosting source, tools), but should utilize it whenever possible. I should be able to build everything locally (including RPMs) if I want, but should use prebuilt artifacts whenever possible (i.e. don't build an rpm locally if I can download it)
 - External infrastructure should exist to build images, but should be the same as the local infrastructure, just running somewhere else.
 - A way to toggle between building official released sources and local sources (like `cros_workon` from the Container Linux SDK)

**Comment by glevand** [comment]
I'd like to have the build system in a container with no dependencies on the host.  With that the only thing needed on the host would be an account that has docker privileges.  CI systems could easily use generic compute resources to do the work.  Also, having a self-contained build system makes things easier to trace back.  We need to be able to trace back from a file on a running system to its source, what tools were used to build the file, and what were the sources of the tools.

How are non-x86 builds done?  Can the build system do cross builds?

**Comment by ajeddeloh** [comment]
One of the things I like about the CL SDK is that the contents of the chroot were visible, not hidden away. You could worked `cork enter`'d or not. But that's a relatively minor thing.
I also like the fact that if you understand the build process you don't need to go through the whole process every time (i.e. you can `emerge-arch-usr <package>` and rerun just `build_image`/`image_to_vm`). That's something I'd like to keep (either that or make sure the builds are _fast_. Nothing is worse waiting 20 minutes for a build.

**Comment by cgwalters** [comment]
See also https://github.com/cgwalters/coreos-assembler/issues/13

How about if we made a `quay.io/coreos/mantle` container that was sort of like my prototype coreos-assembler today?  Although it's tricky, as so far we're mostly carrying forward `kola` and `ore`, whereas a bit part of mantle too is `cork` and `plume`.

**Comment by ajeddeloh** [comment]
I think we've settled on the CoreOS Assembler approach, so I'm going to close this out. Feel free to reopen if anyone has more input.
