### ISSUE TITLE
coordinating default hostname with other Fedora editions

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#902]
Back in Fedora 33 the default hostname in the Fedora ecosystem [was changed](https://github.com/coreos/fedora-coreos-tracker/issues/649) to `fedora` from `localhost`. The default hostname is the hostname that gets set when no hostname information can be found from any other source:

- set manually
- DHCP
- reverse DNS lookup

At the time we decided to [freeze on systemd](https://github.com/coreos/fedora-coreos-tracker/issues/649#issuecomment-743219353) with the fallback hostname change reverted and then later (once the feature was added) we unfroze systemd and [started](https://github.com/coreos/fedora-coreos-config/pull/868) setting the `DEFAULT_HOSTNAME` in `/etc/os-release` to `localhost`.

Now (f35+) we are at a point where NetworkManager has [fixed upstream](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/601#note_992080) to handle rDNS cases properly and Fedora CoreOS itself no longer needs the `DEFAULT_HOSTNAME` to be set to `localhost`, but maybe our users scripts/configuration/automation do need it still.

Depending on the answer to that question our options include:

0. remove the `DEFAULT_HOSTNAME=localhost` entry, default hostname reverts to `fedora`
1. keep this `DEFAULT_HOSTNAME=localhost` delta forever only in FCOS (not ideal)
2. convince a subset of Fedora editions to change (non workstation use cases)
3. convince the entirety of Fedora editions to change (not likely)

It was [suggested by @jlebon](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/601) that we go for `2.`, which I would assume we'd need to try to talk to FESCO about.

**Comment by jlebon** [comment]
Previous discussions on this subject with other maintainers in https://bugzilla.redhat.com/show_bug.cgi?id=1892235.

**Comment by dustymabe** [comment]
We discussed this in the [meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/D4U4Q7JM2FTZPV5J7CWH4OXPI7TOQ2ZQ/).

```
2021-07-21 13:24:34  dustymabe  #agreed we start a discussion with FESCO about potentially updating
                                the default hostname to be localhost for server like editions. If that
                                is rejected then we re-visit if we want to carry the delta just in FCOS
                                or not.
```

**Comment by dustymabe** [comment]
After talking with bcotton about it I'm going to discuss this with the other Editions/Working Groups that we think would find this useful first to do some temperature taking. On the list:

- Fedora IoT
- Fedora Cloud
- Fedora Server

**Comment by dustymabe** [comment]
Here's my pitch to the other working groups:

---

Back in Fedora 33 the default hostname was changed from `localhost` to `fedora` on instances that didn't get the hostname set in any other way (i.e. it's the fallback if it's not set anywhere else). As far as I know this change came in in systemd and was never proposed as a change in Fedora itself.

Here's the original enablement upstream https://github.com/systemd/systemd/pull/5175 and the BZ requesting the change in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1392925

Unfortunately, this initiallly caused us in FCOS some pain because setting the hostname via reverse DNS lookups (via NetworkManager) stopped working along with breaking 3rd party tools that set the hostname. The NM problem was subsequently fixed, but it still remains that a lot of third party software will check to see if an instance's hostname is "unset" by checking the current hostname against the string "localhost".

The open question is, what do we think the fallback hostname should be for server like instances? And.. Should we do anything to change it for a subset of Editions/Working Groups in Fedora?

**Comment by dustymabe** [comment]
Talked with the IoT working group today and they seemed receptive and willing to work together on the change. I opened https://pagure.io/fedora-iot/issue/49 with all details and to raise awareness among any interested parties that weren't at the meeting.

**Comment by dustymabe** [comment]
Talked with the Cloud working group today. Opened https://pagure.io/cloud-sig/issue/376

**Comment by dustymabe** [comment]
Talked with the Server working group today. Opened https://pagure.io/fedora-server/issue/84

Seems like the next step is make a change proposal for Fedora.

**Comment by dustymabe** [comment]
Started on a change proposal draft in https://fedoraproject.org/wiki/Changes/FallbackHostname - I'll be meeting with co-sponsors next week to finalize and submit.

**Comment by dustymabe** [comment]
I have updated the [change page](https://fedoraproject.org/wiki/Changes/FallbackHostname) with updates from the working group and have marked the change as `ChangeReadyForWrangler`.

**Comment by dustymabe** [comment]
The change was accepted! See https://pagure.io/fesco/issue/2804

Tracking BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2104276

**Comment by dustymabe** [comment]
This was implemented in the `fedora-release` and `systemd` RPMs (see [the BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2104276)) and has made it into Fedora 37 RPM builds.

We also added [a test](https://github.com/coreos/fedora-coreos-config/commit/6fdf9349a7accafd3c2d9a71eafab02bb715065f) to make sure we don't regress.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20220910.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20221106.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20221106.3.0`.
