### ISSUE TITLE
kola testiso iso-install scenario is failing

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#908]
This isn't covered by CI currently but we have a `iso-install` scenario for testiso that is failing:

```
cosa kola testiso --scenarios iso-install
<snip>
kola -p qemu-unpriv --output-dir tmp/kola testiso --scenarios iso-install
Testing scenarios: [iso-install]
Error: scenario iso-install: timed out after 10m0s
2021-07-22T20:52:02Z cli: scenario iso-install: timed out after 10m0s
```

The `tmp/kola/iso-install/console.txt` shows: 

```
[FAILED] Failed to start TestISO CoreOS Installer.
See 'systemctl status coreos-installer.service' for details.
[DEPEND] Dependency failed for Reboot after CoreOS Installer.
```

followed later by landing me in `emergency.target`:

```
You are in emergency mode.
```

I was operating on a local dev build of `34.20210722.dev.0`

**Comment by jlebon** [comment]
One way to help debug this is to use `kola testiso --console`. That way when you're in the emergency shell, you can type e.g. `systemctl status coreos-installer.service`.

But the journal should've still been collected at least normally.

**Comment by jlebon** [comment]
@dustymabe Unless you're signing your development builds, it's likely failing because the build isn't signed. You have to use `-S` in that case.

**Comment by gursewak1997** [comment]
I successfully tested scenario iso-install for 34.20210727.dev.0 after using -S argument.

**Comment by dustymabe** [comment]
Interesting. I wonder if we could make that more obvious to the user running the test or possibly flip the default and have the pipeline pass a new argument.

**Comment by dustymabe** [comment]
Alternatively we could have it dynamically default to test signing or not based on if it's a development build or not (i.e. `.dev` in the build ID).

**Comment by jlebon** [comment]
> Alternatively we could have it dynamically default to test signing or not based on if it's a development build or not (i.e. `.dev` in the build ID).

I'd prefer that over flipping the default.

**Comment by dustymabe** [comment]
@gursewak1997 does that make sense to you? ^^ could you maybe implement that?
