### ISSUE TITLE
AWS Image fails to import

### ISSUE THREAD

**Issue by sfxworks** [coreos/fedora-coreos-tracker#914]
**Describe the bug**
Can't import the AWS image to govcloud

```json
{
    "ImportImageTasks": [
        {
            "Description": "fcos",
            "ImportTaskId": "import-ami-00e32193edd133644",
            "SnapshotDetails": [
                {
                    "Description": "fcos",
                    "DeviceName": "/dev/sdf",
                    "DiskImageSize": 786865152.0,
                    "Format": "VMDK",
                    "Status": "completed",
                    "UserBucket": {
                        "S3Bucket": "fcos",
                        "S3Key": "fedora-coreos-34.20210711.3.0-aws.x86_64.vmdk"
                    }
                }
            ],
            "Status": "deleted",
            "StatusMessage": "ClientError: Unknown OS / Missing OS files.",
            "Tags": []
        }
    ]
}
```
**Reproduction steps**
1.  Upload https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/34.20210711.3.0/x86_64/fedora-coreos-34.20210711.3.0-aws.x86_64.vmdk.xz extracted to a public s3 bucket
2. Upload the image using `aws ec2 import-image --description "fcos" --disk-containers Description="fcos",Format="vmdk",UserBucket="{S3Bucket="fcos",S3Key="fedora-coreos-34.20210711.3.0-aws.x86_64.vmdk"}"`
3. Note the failure status message using the AMI ID `aws ec2 describe-import-image-tasks --import-task-ids import-ami-IDHERE`

**Expected behavior**
It imports
**Actual behavior**
A clear and concise description of what actually happened.
It does not
**System details**
 - AWS
 
**Ignition config**
NA

**Additional information**
Gov cloud

**Comment by lucab** [comment]
I believe that this exact question is covered by the FAQ entry at https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_how_do_i_upload_fedora_coreos_to_private_aws_ec2_regions - did you try that?

**Comment by sfxworks** [comment]
Ah, I did not see that. Thanks!
