### ISSUE TITLE
tracker: becoming a top-level Fedora Edition

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#915]
This ticket will track work related to Fedora CoreOS becoming a top-level Fedora Edition.

The original proposal (with links to other places of discussion) is at https://pagure.io/fesco/issue/2516

**Comment by dustymabe** [comment]
Change proposal submitted for Fedora 37: https://fedoraproject.org/wiki/Changes/FedoraCoreOS

There is still some work to do to map some of the release criteria to things we already do. We'll work with QA over the coming months to fill out the mapping and update the release criteria. This ticket helps track that: https://github.com/coreos/fedora-coreos-tracker/issues/1239

**Comment by travier** [comment]
I've posted to the mailing list but it makes more sense to track it here: We also probably need a new FESCO ticket. The current one still points to the one from the F34 change request.

**Comment by dustymabe** [comment]
The proposal was [accepted by FESCO](https://pagure.io/fesco/issue/2823).

We're still working through https://github.com/coreos/fedora-coreos-tracker/issues/1239 with the QA team.

I guess now we need to start thinking about website structure and whatnot. I don't think much needs to change, we probably just need to move up on the main https://getfedora.org page.

**Comment by dustymabe** [comment]
We are now on the main getfedora.org site at the toplevel. We are still working through making our processes more integrated with QA, but we'll track the remaining work there over in https://github.com/coreos/fedora-coreos-tracker/issues/1239
