### ISSUE TITLE
Setting static routes in ignition file

### ISSUE THREAD

**Issue by takyon77** [coreos/fedora-coreos-tracker#921]
# Feature Request #

I would like to be able to set static routes in the ignition file. This is maybe already possible but I can't find any doc/example on how to do it. I tried different methods like setting route1/route2 parameters in the section [ipv4] of the file /etc/NetworkManager/system-connections/nic0.nmconnection but this is apparently ignored or deleted once the VM is up.
Is there a way to do this already?

## Environment ##

VM runnig on qemu-kvm with Fedora cores 34

**Comment by dustymabe** [comment]
Hey @takyon77. In the future questions like this "How do I do X?" are more appropriate for [our discussion forum](https://discussion.fedoraproject.org/c/server/coreos/5).

That being said, what examples are you following today? What Butane/Ignition config are you using that's not working? 

The example from Table 3 in [the documentation](https://networkmanager.dev/docs/api/latest/nm-settings-keyfile.html) shows something like `route1=8.8.8.0/24,10.1.1.1` under the [`ipv4`] setting in an `.nmconnection` file where `10.1.1.1` is the gateway for the route. Seems to work for me.

**Comment by takyon77** [comment]
Hi @dustymabe,

Thanks for your reply.

I did more tests today and you're right this is working. I realized there was a stupid mistake in the test I did before... sorry about that.
