### ISSUE TITLE
Rootless containers within a created network can't DNS resolve external domains anymore

### ISSUE THREAD

**Issue by drobakowski** [coreos/fedora-coreos-tracker#923]
**Describe the bug**
After the stable update from `34.20210711.3.0` to `34.20210725.3.0` my rootless podman containers within a created network can't DNS resolve external domains anymore.

**Reproduction steps**
1. `podman network create testnetwork`
2. `podman run --rm -it --network=testnetwork amouat/network-utils`
3. `nslookup google.com`

**Expected behavior**
Before the upgrade to `34.20210725.3.0` I got a successful DNS resolution:

```sh
~ ⋊> nslookup google.com
...
Name:	google.com
Address: 142.251.45.14
```

**Actual behavior**
When trying to nslookup an external domain I get now:

```sh
~ ⋊> nslookup google.com
...
server can't find XXX: REFUSED"
```

**System details**
 - AWS EC2
 - Fedora CoreOS 34.20210725.3.0

**Ignition config**
EC2 instance originally launched from official AMI.

**Additional information**
```sh
~ ⋊> podman network ls
NETWORK ID    NAME        VERSION     PLUGINS
...  testnetwork     0.4.0       bridge,portmap,firewall,tuning,dnsname
```
**Previously working version**: 34.20210711.3.0

**Comment by dustymabe** [comment]
Thank you for the report. I'm able to reproduce.

**Comment by dustymabe** [comment]
I ran an `rpm-ostree-bisect` against our `testing-devel` stream (it has more granular commits) and the results came back:

```
BISECT TEST RESULTS:
Last known good commit:
  5f19a0f : 34.20210721.20.2 : 2021-07-23T21:16:28Z
First known bad commit:
  f45b731 : 34.20210723.20.0 : 2021-07-23T23:19:05Z
libostree HTTP error from remote fedora-compose for <https://kojipkgs.fedoraproject.org/compose/ostree/repo/objects/4d/1bc437545d2b431ce8c31c18235cb11012df7374ec3457425329bc8e0b3bd3.commit>: Server>
libostree pull from 'fedora-compose' for fedora/x86_64/coreos/testing-devel complete
security: GPG: disabled
security: SIGN: disabled http: TLS
non-delta: meta: 801 content: 0
transfer: secs: 23 size: 7.0 MB
801 metadata, 0 content objects fetched; 6883 KiB transferred in 23 seconds; 0 bytes content written
ostree diff commit from: 5f19a0fc5cf48fa8025bba12b9dd8f95f9bdc0dbdd163f2462f6c9b99b02e93d
ostree diff commit to:   f45b73199aa8be3480afe8e208347018331504d7e37ccb681854146960cab82b
Upgraded:
  audit-libs 3.0.2-1.fc34 -> 3.0.3-1.fc34
  curl 7.76.1-4.fc34 -> 7.76.1-7.fc34
  libcurl 7.76.1-4.fc34 -> 7.76.1-7.fc34
  libipa_hbac 2.5.1-2.fc34 -> 2.5.2-1.fc34
  libsss_certmap 2.5.1-2.fc34 -> 2.5.2-1.fc34
  libsss_idmap 2.5.1-2.fc34 -> 2.5.2-1.fc34
  libsss_nss_idmap 2.5.1-2.fc34 -> 2.5.2-1.fc34
  libsss_sudo 2.5.1-2.fc34 -> 2.5.2-1.fc34
  podman 3:3.2.2-1.fc34 -> 3:3.2.3-1.fc34
  podman-plugins 3:3.2.2-1.fc34 -> 3:3.2.3-1.fc34
  sssd-ad 2.5.1-2.fc34 -> 2.5.2-1.fc34
  sssd-client 2.5.1-2.fc34 -> 2.5.2-1.fc34
  sssd-common 2.5.1-2.fc34 -> 2.5.2-1.fc34
  sssd-common-pac 2.5.1-2.fc34 -> 2.5.2-1.fc34
  sssd-ipa 2.5.1-2.fc34 -> 2.5.2-1.fc34
  sssd-krb5 2.5.1-2.fc34 -> 2.5.2-1.fc34
  sssd-krb5-common 2.5.1-2.fc34 -> 2.5.2-1.fc34
  sssd-ldap 2.5.1-2.fc34 -> 2.5.2-1.fc34
Removed:
  libmetalink-0.1.3-14.fc34.x86_64
Finished RPM-OSTree Bisect Testing.
```

Here's the test script I was running:

```
#!/bin/bash
cat <<'EOF' > /tmp/testscript
podman network rm testnetwork || true
podman network create testnetwork
if ! podman run --rm -it --network=testnetwork registry.fedoraproject.org/fedora:34 getent hosts google.com ; then
    echo "DNS in rootless podman testnetwork failed. Test Fails"
    exit 1
else
    echo "DNS in rootless podman testnetwork Suceeded. Test Passes"
    exit 0
fi
EOF
su - core -c "/bin/bash /tmp/testscript"
```

**Comment by dustymabe** [comment]
I can verify it was the `podman 3:3.2.2-1.fc34 -> 3:3.2.3-1.fc34` upgrade that introduced the problem.

**Comment by dustymabe** [comment]
The issue is not observed in our rawhide stream (F35). I believe this is some combination of a change in podman AND how we have dns resolution set up in F34 based FCOS.

Right now we are not using the systemd stub resolver in F34 FCOS. In F35 (rawhide) we are using the systemd stub resolver (see https://github.com/coreos/fedora-coreos-tracker/issues/834).

There was probably a change in podman regressed on this particular setup.

**Comment by dustymabe** [comment]
opened https://github.com/containers/podman/issues/11222 to track the bug/fix.

**Comment by drobakowski** [comment]
Thanks for the fast reply and looking into it, @dustymabe! 👍🏻

**Comment by dustymabe** [comment]
Fixed upstream in https://github.com/containers/podman/pull/11230 - will update when that flows into FCOS.

**Comment by dustymabe** [comment]
backported to podman 3.3.0 in containers/podman@15fff7d

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `34.20210821.3.0`.

**Comment by drobakowski** [comment]
Works as expected again, thanks @dustymabe for keeping me updated. 👍🏻
