### ISSUE TITLE
rawhide: 20210814: ext.config.toolbox test failing

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#926]
This is because there is no toolbox container for f36 yet.

```
[core@cosa-devsh ~]$ toolbox create --assumeyes
Pulling registry.fedoraproject.org/fedora-toolbox:36: | Error: failed to pull image registry.fedoraproject.org/fedora-toolbox:36
If it was a private image, log in with: podman login registry.fedoraproject.org
Use 'toolbox --verbose ...' for further details.
```

This is based on the `20210814` rawhide rpm content set.

**Comment by dustymabe** [comment]
Let's snooze this test for a few weeks and hopefully the container will exist in the registry then: https://github.com/coreos/fedora-coreos-config/pull/1163

**Comment by dustymabe** [comment]
Hey @HarryMichal  @debarshiray - can we make `registry.fedoraproject.org/fedora-toolbox:36` exist?

**Comment by debarshiray** [comment]
@juhp already made an [attempt](https://src.fedoraproject.org/container/fedora-toolbox/c/ae16371775b71c687626187aabc3ae06c67c23e7) to build an image for F36/Rawhide. Unfortunately, it failed due to a [problem](https://pagure.io/fedora-infrastructure/issue/10145) with the Fedora infrastructure that @olivergs filed a bug about.

**Comment by juhp** [comment]
Right, what I am doing as a workaround is just to [roll](https://github.com/toolbox-images/toolbox-images/blob/main/images/fedora/make-toolbox.sh) my own image. (I do kind of wish toolbox had an option to do that out of the box.)

Note fedora-toolbox:35 is also very out of date (it predates branching) for the same reason: we can't build it either.

**Comment by dustymabe** [comment]
[The issue](https://pagure.io/fedora-infrastructure/issue/10145) is now fixed and the toolbox containers are in the registry.
