### ISSUE TITLE
NetworkManager and UDEV race condition

### ISSUE THREAD

**Issue by cyrus-mc** [coreos/fedora-coreos-tracker#929]
**Describe the bug**

I believe I am running into a race condition between udev and Network Manager as described in the following relevant issues:

* https://github.com/openshift/sriov-network-operator/issues/414
* https://bugzilla.redhat.com/show_bug.cgi?id=1896866#c19

When using Fedora CoreOS as a worker node for AWS EKS. With this setup PODs will boot-up but their network stack will not be fully initialized because NetworkManager has taken over management of the link and is defaulting to a "Wired Connection" and attempting to perform DHCP. This causes the link to go up and down.

**Reproduction steps**

This issue is a little difficult to produce since it is a race condition situation.

1.  Create a large number of PODs (say 5) at one time on a EKS worker node
2. PODs will come up and show healthy indicating that nothing is wrong
3. SSH into the node in question and run nmcli you will see some of the ENI interfaces are unmanaged while others are managed

**Expected behavior**

Due to the specified udev rules in /usr/lib/udev/rules.d/85-nm-unmanaged.rules all interfaces with driver "veth" should be unmanaged.

**Actual behavior**

veth interfaces end up being managed by NetworkManager. This causes the interface to go up/down and prevents the container/POD from establishing any network connectivity.

**System details**
 - Running on AWS
 - Fedora CoreOS version 34.20210626.3.2

**Additional information**

This issue presented itself between version 33.20210217.3.0 and 34.20210626.3.2.

**Comment by cyrus-mc** [comment]
The udev rules specified in /usr/lib/udev/rules/85-nm-unmanaged.rules are defined as such

```
# Do not modify this file, it will get overwritten on updates.
# To override or extend the rules place a file in /etc/udev/rules.d

SUBSYSTEM!="net", GOTO="nm_unmanaged_end"
ACTION!="add|change", GOTO="nm_unmanaged_end"

...

# Virtual Ethernet device pair. Often used to communicate with a peer interface
# in another net namespace and managed by libvirt, Docker or the like.
ENV{ID_NET_DRIVER}=="veth", ENV{NM_UNMANAGED}="1"

# USB gadget device. Unmanage by default, since whatever created it
# might want to set it up itself (e.g. activate an ipv4.method=shared
# connection).
ENV{DEVTYPE}=="gadget", ENV{NM_UNMANAGED}="1"

LABEL="nm_unmanaged_end"
```

This rule applies to only add or change events. For AWS EKS, the VPC CNI plugin (at a high level) operates as such (code, https://github.com/aws/amazon-vpc-cni-k8s/blob/6361ced8dfb7b07c616e4a0a450d9b55089161dc/cmd/routed-eni-cni-plugin/driver/driver.go#L95)

* setup container namespace
* create veth pair within container namespace
* bring interfaces up and configure routing
* move host side of veth pair to host namespace

When looking at the output of `udevadm monitor --environemtn --udev` two events actually end up firing as the host side of the `veth` pair is moved to the host namespace:

```
UDEV  [1127314.824189] add      /devices/virtual/net/veth1 (net)
ACTION=add
DEVPATH=/devices/virtual/net/veth1
SUBSYSTEM=net
INTERFACE=veth1
IFINDEX=43
SEQNUM=3268
USEC_INITIALIZED=1127314815706
ID_NET_DRIVER=veth
ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
ID_NET_NAME=veth1
NM_UNMANAGED=1
SYSTEMD_ALIAS=/sys/subsystem/net/devices/veth1
TAGS=:systemd:
CURRENT_TAGS=:systemd:

UDEV  [1127314.826254] move     /devices/virtual/net/veth1 (net)
ACTION=move
DEVPATH=/devices/virtual/net/veth1
SUBSYSTEM=net
DEVPATH_OLD=/devices/virtual/net/veth1
INTERFACE=veth1
IFINDEX=43
SEQNUM=3269
USEC_INITIALIZED=1127314815706
ID_NET_DRIVER=veth
ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
ID_NET_NAME=veth1
SYSTEMD_ALIAS=/sys/subsystem/net/devices/veth1
TAGS=:systemd:
CURRENT_TAGS=:systemd:
```

The first event matches the rule (since it is an add) and therefore `NM_UNMANAGED` is set to 1. But on the move event that flag isn't set as a move operation is not listed in the actions for that rule.

Compare this with the situation in which you create the host side of the  `veth` pair directly in host namespace (rather than move it):

```
ip link add veth1 netns 1 type veth peer name veth2 netns net1

UDEV  [1128438.998296] add      /devices/virtual/net/veth1 (net)
ACTION=add
DEVPATH=/devices/virtual/net/veth1
SUBSYSTEM=net
INTERFACE=veth1
IFINDEX=46
SEQNUM=3294
USEC_INITIALIZED=1128438988889
ID_NET_DRIVER=veth
ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
ID_NET_NAME=veth1
NM_UNMANAGED=1
SYSTEMD_ALIAS=/sys/subsystem/net/devices/veth1
TAGS=:systemd:
CURRENT_TAGS=:systemd:
```

This generates a single udev event for the ADD and looking at the details has set `NM_UNMANAGED` to 1. 

I believe the race condition happens when the first ADD event fires, before NetworkManager sets up the initial device the MOVE event fires and updates the details, clearing out the `NM_UNMANAGED` flag and thus NM ends up managing the device.

**Comment by dustymabe** [comment]
Thank you @cyrus-mc for the very detailed bug report and for working upstream to get the issue fixed!

This should be fixed upstream by [b57c1af](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/b57c1af81448a8e7b57f56d910d2354e2a247c87) (backported to `nm-1-32` branch in [b1a7c71](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/b1a7c71da75fb3c332c46aca910f248b6424ce3e)).

**Comment by cyrus-mc** [comment]
@dustymabe no problem. Was sort of a interesting/fun troubleshooting exercise. With containers I don't often spend time within the OS like I did when I was more of a classical system admin.

**Comment by dustymabe** [comment]
The fix made it into the 1.32.10 release of NetworkManager. Fedora Linux 35 has been updated to 1.32.10 a month ago. This will be fixed when F35 is released and FCOS is rebased to it.

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `35.20211029.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `35.20211029.3.0`.
