### ISSUE TITLE
F35: CHANGE: Third-party Software Mechanism

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#932]
In https://github.com/coreos/fedora-coreos-tracker/issues/856#issuecomment-904078512 we evaluated and decided to discuss further the following change:

- [Third-party Software Mechanism](https://fedoraproject.org/wiki/Changes/Third_Party_Software_Mechanism)
    - Update mechanism for opting-in to "Third-Party Software Repositories" so that the repositories are immediately enabled.
    - Tracking bug: [#1982749](https://bugzilla.redhat.com/1982749)

**Comment by dustymabe** [comment]
Thanks @cgwalters for volunteering to look into this issue and track any necessary fixes.

**Comment by cgwalters** [comment]
At this time we have no plans to ship `fedora-third-party` in Fedora CoreOS; there isn't a driving need.

**Comment by dustymabe** [comment]
We discussed this at [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/FPGOECGLPTFVCBW4FM3REIQS7DVPQW4F/).

```
13:35:52*  dustymabe | #agreed we don't plan to ship the fedora-third-party package because
                     | the  desired use is that people run software in podman or docker
                     | containers and not install extra packages on the host
```

and

```
13:35:44   dustymabe | #action jaimelm to write documentation on fedora-third-party rpm for
                     | our FAQ

```
