### ISSUE TITLE
F35: CHANGE: Remove authselect-compat package

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#933]
In https://github.com/coreos/fedora-coreos-tracker/issues/856#issuecomment-904078512 we evaluated and decided to discuss further the following change:

- [Remove authselect-compat package](https://fedoraproject.org/wiki/Changes/RemoveAuthselectCompatPackage)
    - Authselect replaced authconfig tool in Fedora 28. To enable some level of backwards compatibility, it ships the authconfig command as a wrapper around authselect calls in package "authselect-compat". Authselect is now well adopted and the shim compatibility layer should be removed by removing the authselect-compat package. 
    - Tracking bug: [#1979622](https://bugzilla.redhat.com/1979622)

**Comment by dustymabe** [comment]
thanks @jlebon for volunteering to look into this for us

**Comment by jlebon** [comment]
Can confirm no authselect getting pulled into FCOS.
