### ISSUE TITLE
Failure to boot the Live ISO on bare metal hardware in UEFI mode

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#953]
**Describe the bug**

We're [seeing reports](https://bugzilla.redhat.com/show_bug.cgi?id=1999577) of not being able to boot the Live ISO (after `dd` to a USB key) in UEFI mode on bare metal.

When booting you get dropped to a grub prompt. I'm able to reproduce the issue myself on a local intel NUC.

**Reproduction steps**
1. dd fcos.iso to USB key
2. insert USB key into bare metal hardware
3. boot hardware and select UEFI USB key entry to boot from

**Expected behavior**
Grub menu is able to load and continue to boot FCOS.

**Actual behavior**
dropped to grub shell

```
grub>
```

**System details**
 - Bare Metal UEFI boot on intel NUC
 - `fedora-coreos-34.20210808.3.0-live.x86_64.iso`

**Comment by dustymabe** [comment]
This also seems like it could be related to https://github.com/coreos/fedora-coreos-tracker/issues/724, but I recall at the time not being able to reproduce. I am clearly able to reproduce now.

**Comment by bgilbert** [comment]
Fix in https://github.com/coreos/coreos-assembler/pull/2404.

**Comment by miabbott** [comment]
Folks may try a fixed ISO from here - https://miabbott.fedorapeople.org/fedora-coreos-34.20210902.dev.0-live.x86_64.iso

**Comment by dustymabe** [comment]
The fix for this went into testing stream release `34.20210904.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into stable stream release `34.20210821.3.0`.
