### ISSUE TITLE
console defaults for x86_64 qemu platform

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#954]
With the work in https://github.com/coreos/coreos-assembler/pull/2400 we'll soon be able to configure console defaults on each platform individually. After a notice period, the x86_64 qemu images will revert to no `console=` entry on the kernel command line, which means it will default to VGA console by default, which is what some users expect and will welcome the change.

For me (I suspect I'm not alone, but maybe), I use a lot of scripting to run various tests and I typically use the qemu qcow to pull that off. In a lot of cases I use the serial console output to debug, go through scrollback, etc.. In my cases I typically don't offer a graphical console to the machine at all (i.e. `virt-install --graphics=none`).

It would be nice if either the kernel would choose the serial console when there was no VGA console OR we set console defaults for QEMU that would **fallback** to serial console if VGA **isn't available**. From preliminary testing setting `console=ttyS0 console=tty0` does that.

**Comment by bgilbert** [comment]
`console=ttyS0 console=tty0` will still use `ttyS0` as a secondary console, the way we're doing for VGA now.  If we did that in the metal images, it'd still risk boot failures if the platform serial port doesn't work, and boot slowdowns if it does.  But those concerns might not apply to QEMU.

**Comment by jlebon** [comment]
I think it might be worth trying to dig into the kernel auto-detection logic here some more and/or chat with the relevant kernel folks. I quoted the relevant kernel docs in https://github.com/coreos/fedora-coreos-tracker/issues/567#issuecomment-656753678 which seem to express exactly the semantics we'd want for kola/`virt-install --graphics=none`. But both @bgilbert and I tested this and we're not getting that result.

So either we're missing something, or the docs are wrong, or there's a bug in the kernel (non-exclusive :) ).

**Comment by bgilbert** [comment]
AFAICT if virtual consoles are enabled, they're always assumed to be present, so the kernel never falls back to serial.  This is sort-of documented [in Kconfig](https://github.com/torvalds/linux/blob/a2b28235335fee2586b4bd16448fb59ed6c80eef/drivers/tty/Kconfig#L65-L70).

**Comment by bgilbert** [comment]
Testing shows that `console=ttyS0 console=tty0` doesn't behave as desired.  If there's no VGA console, the serial console stays secondary, so it only gets kernel messages.

**Comment by lucab** [comment]
From last meeting:
```
  * AGREED: for now, we will continue to add `console=tty0
    console=ttyS0,115200` to the QEMU image.  we will investigate having
    the initramfs e-shell print some info to secondary consoles, and
    possibly start additional shells on them.  (bgilbert, 17:29:11)
```

**Comment by dustymabe** [comment]
> we will investigate having the initramfs e-shell print some info to secondary consoles

- https://github.com/coreos/fedora-coreos-config/pull/1769


> and possibly start additional shells on them.

Looks like that is already the case today (see dracutdevs/dracut@32f68c1). At least I just verified on a qemu qcow2 with `console=tty0 console=ttyS0,115200` that I get a shell on both consoles.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `36.20220605.2.0`. Please try out the new release and report issues.
