### ISSUE TITLE
[F35] Fedora CoreOS Test Day - week of 2021-10-11

### ISSUE THREAD

**Issue by sumantro93** [coreos/fedora-coreos-tracker#973]
It's time to schedule a CoreOS test day. The `next` stream release will be rebased to Fedora 35 the week that it goes Beta:

The focus of the test day will be:

    Bugs not caught by the CI
    File editors properly handling the new extensions
    Documentation
    Raise Awareness about Fedora CoreOS

Fedora QA ticket will be forthcoming, once the F35 Beta release date is finalized.

**Comment by dustymabe** [comment]
- [Fedora QA ticket](https://pagure.io/fedora-qa/issue/674)

**Comment by dustymabe** [comment]
We discussed this in [the community meeting today](https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/message/QCJDYZR26SFCF5UKNSEOUWI5F7A5QNS4/).

```
12:41:59*   dustymabe | #action dustymabe to talk to sumantro to try to get FCOS testing on the week of oct 11
```

and

```
12:46:18*   dustymabe | #action dustymabe to schedule some time on Monday to identify docs test cases and prepare for F35 test day
```

**Comment by dustymabe** [comment]
> ```
> 12:41:59*   dustymabe | #action dustymabe to talk to sumantro to try
>                         to get FCOS testing on the week of oct 11
> ```

Talked to @sumantro93 - we're good with the week of 2021-10-11 for testing. We should encourage involvement the whole week but maybe schedule some time for a large group of us to get together to kick it off and maybe divide up the tests.

**Comment by dustymabe** [comment]
>```
> 12:46:18*   dustymabe | #action dustymabe to schedule some time on Monday
>                         to identify docs test cases and prepare for F35 test day
> ```

Scheduled some time on Monday (10AM Eastern) for us to get together and talk about strategy for the test day and test cases. The meeting details are at https://calendar.fedoraproject.org/meeting/10091/

**Comment by dustymabe** [comment]
badges coming soon to those who participated: https://pagure.io/fedora-badges/issue/849#comment-758501
