### ISSUE TITLE
Support armhf

### ISSUE THREAD

**Issue by Ludea** [coreos/fedora-coreos-tracker#980]
**Describe the enhancement**
Since fcos supports aarch64, it would be awesome if it can support armhf.
(My goal is to install fcos on Rpi2) 

**System details**
 - Bare Mental
 - armv7 (hf) 

**Additional information**
Fedora Workstation / server already support it
https://fedoraproject.org/wiki/Architectures/ARM
https://arm.fedoraproject.org/

**Comment by lucab** [comment]
Thanks for the report. `armhf` is a 32bits architecture and Fedora CoreOS explicitly does not target that.
If you are looking for a Fedora-based OS for constrained environments, please have a look at https://getfedora.org/en/iot/ (still rpm-ostree based).
