### ISSUE TITLE
rawhide: 20210928 containers-common causing toolbox test fail

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#981]
It looks like `containers-common-1-30.fc36` is causing toolbox tests to fail. A simple toolbox create doesn't work:

```
[core@cosa-devsh ~]$ toolbox create --assumeyes                                                                                              
Creating container fedora-toolbox-36: - Error: failed to create container fedora-toolbox-36
```

We can pin on `containers-common-1-28.fc36` for now.

**Comment by dustymabe** [comment]
Any volunteers for chasing down this issue and corresponding with the related upstream(s) to get it fixed? Help is badly needed!

**Comment by JaimeMagiera** [comment]
Rawhide is now using 1-31.fc36, which is still failing. Kola output attached. I'll take a deeper look myself and notify the Podman folks of this issue. 

[containers-common-1-31.fc36-failure.tar.gz](https://github.com/coreos/fedora-coreos-tracker/files/7272555/containers-common-1-31.fc36-failure.tar.gz)

**Comment by JaimeMagiera** [comment]
[Issue created in the containers toolbox repo.](https://github.com/containers/toolbox/issues/892)

**Comment by dustymabe** [comment]
This was fixed. See https://github.com/coreos/fedora-coreos-config/commit/9283e482a4de951d1feae671dbce37ea9ad4d8d7
