### ISSUE TITLE
New Package Request: lldpd

### ISSUE THREAD

**Issue by dmunne** [coreos/fedora-coreos-tracker#986]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)

The dependencies of the package are the following:
- mariadb-connector-c
- mariadb-connector-c-config
- net-snmp-agent-libs
- net-snmp-libs

2. What is the size of the package and its dependencies?

Complet list of packages and size:
- lldpd (183 k)
- mariadb-connector-c (200 k)
- mariadb-connector-c-config (15 k)
- net-snmp-agent-libs (748 k)
- net-snmp-libs (824 k)

3. What problem are you trying to solve with this package? Or what functionality does the package provide?

LLDP is an industry standard protocol designed to supplant proprietary Link-Layer protocols such as EDP or CDP. The goal of LLDP is to provide an inter-vendor compatible mechanism to deliver Link-Layer notifications to adjacent network devices.

4. Can the software provided by the package be run from a container?  Explain why or why not.

Yes, it can be run as a container: https://github.com/lldpd/lldpd#installation-docker

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

No.

6. Can the tool(s) provided by the package be helpful in debugging networking issues?

Yes, it can help to debug a network issue.

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.

No.

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?

No, it needs to create the daemon lldpd.service to be able to receive and send LLDP frames

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)

No.

10. Does the software provided by the package have a history of CVEs?

Yes, all CVEs can be consulted in the following URLs:
- https://lldpd.github.io/security.html
- https://access.redhat.com/security/security-updates/#/cve?q=lldpd&p=1&sort=cve_publicDate%20desc&rows=10&documentKind=Cve

**Comment by jlebon** [comment]
>> Is it possible to layer the package onto the base OS as a day 2 operation? Explain why or why not.
>
> No.

That answer is missing the "Explain why or why not." part. :)

Is this part of a higher-level OCP effort? Why wouldn't this be appropriate as an extension? (Noticed you also mentioned it can be run in a container, but yeah... building and shipping our own is non-trivial work.)

**Comment by dustymabe** [comment]
hey @dmunne - thanks for the request. I've added the `meeting` label to this issue so we can bring it up and discuss at one of our upcoming community meetings.

There's a few things we should clarify in your answers above:



> 1. What is the size of the package and its dependencies?
> 
> Complete list of packages and size:
> 
> * lldpd (183 k)
> * mariadb-connector-c (200 k)
> * mariadb-connector-c-config (15 k)
> * net-snmp-agent-libs (748 k)
> * net-snmp-libs (824 k)

I see something slightly different. We have to include dependencies of dependencies here. I've included some snipped output below of package layering `lldpd`:

```
[core@cosa-devsh ~]$ sudo rpm-ostree install lldpd
...
Resolving dependencies... done
Will download: 66 packages (10.4?MB)
...
Added:
  gdbm-libs-1:1.19-2.fc34.x86_64
  groff-base-1.22.4-7.fc34.x86_64
  lldpd-1.0.4-6.fc34.x86_64
  lm_sensors-libs-3.6.0-8.fc34.x86_64
  mariadb-connector-c-3.1.13-1.fc34.x86_64
  mariadb-connector-c-config-3.1.13-1.fc34.noarch
  net-snmp-agent-libs-1:5.9.1-4.fc34.x86_64
  net-snmp-libs-1:5.9.1-4.fc34.x86_64
  perl-AutoLoader-5.74-477.fc34.noarch
  perl-B-1.80-477.fc34.x86_64
  perl-Carp-1.50-458.fc34.noarch
  perl-Class-Struct-0.66-477.fc34.noarch
  perl-Data-Dumper-2.174-460.fc34.x86_64
  perl-Digest-1.20-1.fc34.noarch
  perl-Digest-MD5-2.58-2.fc34.x86_64
  perl-DynaLoader-1.47-477.fc34.x86_64
  perl-Encode-4:3.12-460.fc34.x86_64
  perl-Errno-1.30-477.fc34.x86_64
  perl-Exporter-5.74-459.fc34.noarch
  perl-Fcntl-1.13-477.fc34.x86_64
  perl-File-Basename-2.85-477.fc34.noarch
  perl-File-Path-2.18-2.fc34.noarch
  perl-File-Temp-1:0.231.100-2.fc34.noarch
  perl-File-stat-1.09-477.fc34.noarch
  perl-FileHandle-2.03-477.fc34.noarch
  perl-Getopt-Long-1:2.52-2.fc34.noarch
  perl-Getopt-Std-1.12-477.fc34.noarch
  perl-HTTP-Tiny-0.078-1.fc34.noarch
  perl-IO-1.43-477.fc34.x86_64
  perl-IO-Socket-IP-0.41-3.fc34.noarch
  perl-IO-Socket-SSL-2.070-2.fc34.noarch
  perl-IPC-Open3-1.21-477.fc34.noarch
  perl-MIME-Base64-3.16-2.fc34.x86_64
  perl-Mozilla-CA-20200520-4.fc34.noarch
  perl-NDBM_File-1.15-477.fc34.x86_64
  perl-Net-SSLeay-1.90-2.fc34.x86_64
  perl-POSIX-1.94-477.fc34.x86_64
  perl-PathTools-3.78-459.fc34.x86_64
  perl-Pod-Escapes-1:1.07-458.fc34.noarch
  perl-Pod-Perldoc-3.28.01-459.fc34.noarch
  perl-Pod-Simple-1:3.42-2.fc34.noarch
  perl-Pod-Usage-4:2.01-2.fc34.noarch
  perl-Scalar-List-Utils-4:1.56-459.fc34.x86_64
  perl-SelectSaver-1.02-477.fc34.noarch
  perl-Socket-4:2.032-1.fc34.x86_64
  perl-Storable-1:3.21-458.fc34.x86_64
  perl-Symbol-1.08-477.fc34.noarch
  perl-Term-ANSIColor-5.01-459.fc34.noarch
  perl-Term-Cap-1.17-458.fc34.noarch
  perl-Text-ParseWords-3.30-458.fc34.noarch
  perl-Text-Tabs+Wrap-2021.0726-1.fc34.noarch
  perl-Time-Local-2:1.300-5.fc34.noarch
  perl-URI-5.09-1.fc34.noarch
  perl-base-2.27-477.fc34.noarch
  perl-constant-1.33-459.fc34.noarch
  perl-if-0.60.800-477.fc34.noarch
  perl-interpreter-4:5.32.1-477.fc34.x86_64
  perl-libnet-3.13-2.fc34.noarch
  perl-libs-4:5.32.1-477.fc34.x86_64
  perl-mro-1.23-477.fc34.x86_64
  perl-overload-1.31-477.fc34.noarch
  perl-overloading-0.02-477.fc34.noarch
  perl-parent-1:0.238-458.fc34.noarch
  perl-podlators-1:4.14-458.fc34.noarch
  perl-subs-1.03-477.fc34.noarch
  perl-vars-1.05-477.fc34.noarch
```



> 7.  Is it possible to layer the package onto the base OS as a day 2 operation? Explain why or why not.
>
> No.

Why did you answer "No" here? It at least works from a trivial perspective (see above output), but there may be some technical detail I'm not aware of.

**Comment by dmunne** [comment]
Hi @jlebon and @dustymabe, thank you for your quick answer.
My answers below:

- it can be done as day-2 op but the use case I'm working on is based in a bare-metal disconnected environment where tasks related to the OS itself are not easy to achieve. Apart from that, I think that this functionality can be useful to have out-of-the-box.
- you're right regarding the dependencies, that's the complete list and size for each package

**Comment by travier** [comment]
* That's a lot of Perl packages to get rid of.
* What are the challenges in using that from a privileged container? If this is just about not using the image from the DockerHub or in a disconnected network then I would suggest you host your own disconnected container registry.

**Comment by dmunne** [comment]
Hi @travier , the option to run the service in a container is not a challenge itself but it will not have the same support as if the package is included in the OS.

**Comment by travier** [comment]
We have the lldpd package in Fedora, CentOS Stream & RHEL so we should be able to build container images with this package included to run as privileged containers.

**Comment by dmunne** [comment]
I understood that you were mentioning using an image with the GitHub code directly, like the example provided in their documentation.
Now I get it, what you're saying could work as well.
