### ISSUE TITLE
Produce official ppc64le architecture artifacts

### ISSUE THREAD

**Issue by mkumatag** [coreos/fedora-coreos-tracker#987]
**Describe the enhancement**

This issue for requesting ppc64le platform support for the Fedora CoreOS. Recently arm64 support has been added via https://github.com/coreos/fedora-coreos-tracker/issues/13, this issue forked from the https://github.com/coreos/fedora-coreos-tracker/issues/13#issuecomment-932137590 discussion.

cc @travier

**Comment by dustymabe** [comment]
crosslinking https://github.com/coreos/coreos-assembler/issues/2473 here since there is some good discussion there about some challenges ahead.

**Comment by dustymabe** [comment]
enablement for this has landed in a few PRs:

- https://github.com/coreos/fedora-coreos-pipeline/pull/597
- https://github.com/coreos/fedora-coreos-pipeline/pull/601
- https://github.com/coreos/coreos-assembler/pull/3033
- https://github.com/coreos/fedora-coreos-browser/pull/38
- https://github.com/coreos/fedora-coreos-pipeline/pull/609

and some pending:
- https://github.com/coreos/fedora-coreos-cincinnati/pull/84

**Comment by dustymabe** [comment]
Marking this as complete as it should land in next week's releases.

**Comment by dustymabe** [comment]
Actually, we probably need to try to make sure we get https://github.com/coreos/fedora-coreos-config/pull/1844 in on Monday before we start the releases. On my existing builder I'm short on space in `/boot`:

```
[core@buildvm-ppc64le-fcos01 srv]$ rpm-ostree status 
State: idle
Deployments:
● ostree-unverified-image:oci-archive:/srv/fedora-coreos-36.20220809.20.3-ostree.ppc64le.ociarchive
                   Digest: sha256:98ed9b1277677bff0455a937c85816ebd3431d38dcebe2bfbdfb66ee7646c0e0
                  Version: 36.20220809.20.3 (2022-08-10T20:09:39Z)

  ostree-unverified-image:oci-archive:/srv/fedora-coreos-36.20220711.dev.0-ostree.ppc64le.ociarchive
                   Digest: sha256:44122282e785ad742350b3862ebbffb5d60a1c8ab4168237c27d4d1efaeb94c3
                  Version: 36.20220711.dev.0 (2022-07-11T08:20:40Z)
[core@buildvm-ppc64le-fcos01 srv]$ 
[core@buildvm-ppc64le-fcos01 srv]$ df -kh /boot/
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda3       362M  248M   92M  74% /boot
[core@buildvm-ppc64le-fcos01 srv]$ 
[core@buildvm-ppc64le-fcos01 srv]$ sudo du -sh /boot/ostree/*
121M    /boot/ostree/fedora-coreos-4629dab1861e40544bb601f84b5fd6ab6fc20a223e76df751bb67d3a2620bbaf
121M    /boot/ostree/fedora-coreos-49d9a2f5d0cc617e86c58c895447654c1c5d563384ee96affba8ad5a1bc019e4
```

**Comment by jlebon** [comment]
> ```
> [core@buildvm-ppc64le-fcos01 srv]$ df -kh /boot/
> Filesystem      Size  Used Avail Use% Mounted on
> /dev/vda3       362M  248M   92M  74% /boot
> [core@buildvm-ppc64le-fcos01 srv]$ 
> [core@buildvm-ppc64le-fcos01 srv]$ sudo du -sh /boot/ostree/*
> 121M    /boot/ostree/fedora-coreos-4629dab1861e40544bb601f84b5fd6ab6fc20a223e76df751bb67d3a2620bbaf
> 121M    /boot/ostree/fedora-coreos-49d9a2f5d0cc617e86c58c895447654c1c5d563384ee96affba8ad5a1bc019e4
> ```

Right, this is worse on ppc64le (one of the reasons https://github.com/coreos/fedora-coreos-tracker/issues/1247 was filed was for that arch, where nides actually did hit `ENOSPC`). Although we'll have to deal with that in RHCOS for existing machines, for FCOS we have an opportunity to start off ppc64le with a larger `/boot` already (and we really should've done that for the recently added arches too).

Maybe let's add support for configuring it via `image.yaml`? We'll need a knob like that anyway to ratchet changing the boot partition size.

**Comment by dustymabe** [comment]
> for FCOS we have an opportunity to start off ppc64le with a larger `/boot` already (and we really should've done that for the recently added arches too).

yeah I'm fine with that as long as we have some concensus on what we want things to look like for all architectures before we make any changes here.

I'll try to hold this until we make that decision.

**Comment by dustymabe** [comment]
Update: https://github.com/coreos/fedora-coreos-config/pull/1844 landed. Here is what I see on our ppc64le builder now (after deploying `36.20220916.20.1`

```
$ pwd
/boot/ostree
$ sudo du -sh ./* 
112M    ./fedora-coreos-39dc2f20c9a2c1a9a427fd7a0bc456956f3d90c6ed96beeb946c24779e0af338
121M    ./fedora-coreos-d02361e161cc8b1bc393f3686b403f3d5f4fb587853234e1139c1f0d9db38aba
```

```
$ file ./fedora-coreos-39dc2f20c9a2c1a9a427fd7a0bc456956f3d90c6ed96beeb946c24779e0af338/initramfs-5.19.8-200.fc36.ppc64le.img 
./fedora-coreos-39dc2f20c9a2c1a9a427fd7a0bc456956f3d90c6ed96beeb946c24779e0af338/initramfs-5.19.8-200.fc36.ppc64le.img: Zstandard compressed data (v0.8+), Dictionary ID: None


$ file ./fedora-coreos-d02361e161cc8b1bc393f3686b403f3d5f4fb587853234e1139c1f0d9db38aba/initramfs-5.18.19-200.fc36.ppc64le.img 
./fedora-coreos-d02361e161cc8b1bc393f3686b403f3d5f4fb587853234e1139c1f0d9db38aba/initramfs-5.18.19-200.fc36.ppc64le.img: gzip compressed data, max compression, from Unix, original size modulo 2^32 1024
```

**Comment by dustymabe** [comment]
Here's a summary of what's blocking this right now: https://github.com/coreos/fedora-coreos-tracker/issues/1247#issuecomment-1261286872

**Comment by dustymabe** [comment]
As a group we have decided to ultimately [increase the size of our /boot partition](https://github.com/coreos/fedora-coreos-tracker/issues/1465). We should consider releasing `ppc64le` with the new partition size (once we know what that will be) from the start.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `38.20230609.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `38.20230609.2.1`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `38.20230625.3.0`.
