### ISSUE TITLE
Change EFI-System partition format from fat16 to fat32

### ISSUE THREAD

**Issue by buckaroogeek** [coreos/fedora-coreos-tracker#993]
# Bug #
Raspberry Pi 4 will not boot Fedora CoreOS if the EFI-System partition is FAT16. Convert to FAT32 and the RPi4 boots. The coreos-installer appears to use FAT16 for the EFI system partition. I could not see an option to change this at coreos-installer run time.

## Host Operating System Version ##
Fedora 34

## Target Operating System Version ##
Fedora CoreOS 34

## coreos-installer Version ##
coreos-installer-0.10.0-2.fc34.x86_64

## Expected Behavior ##
Use coreos-installer to create a bootable USB mass storage device for Raspberry Pi 4. CoreOS should boot once coreos-installer completes without error and the USB device is plugged into the RPi4 and powered on.

## Actual Behavior ##
FCOS will not boot on the RPi4 until the EFI-System partition is reformatted as FAT32. It appears that coreos-installer formats the partition as FAT16.
The RPi4 displays a message: Trying partition 0. Trying  to read partition as fat. (with other text), This message block repeats blocking the boot process.

## Reproduction Steps ##

  1. Install FCOS to usb (e.g. sudo coreos-installer install /dev/sdh -i ./fc1.ign -f fedora-coreos-34.20210919.3.0-etal.aarch64.raw --offline --insecure)
  2. Dismount USB from Fedora workstation
  3. Mount USB on RPi4 (usb3 port).
  4. Power on.
  5. RPi4 cannot read partition.

## Other Information ##
I am using v 1.31 of the pftp/uefi firmware. I can manually reformat the partition to FAT32 and FCOS boots as expected.

**Comment by buckaroogeek** [comment]
Thanks for the information about the specification and updates. I should spell check before I submit!  I recall that during my initial efforts to install and run FCOS on RPi4 hardware last February (see https://forums.raspberrypi.com/viewtopic.php?t=304318 for a write up if interested), this was not an issue I ran into. The USB disk I uses is a KINGSTON SA400S37120G (120 GB). Please let me know if I can provide any more information and/or testing.

**Comment by buckaroogeek** [comment]
Glad to help.

**Comment by bgilbert** [comment]
Yeah.  Added meeting label.

**Comment by lucab** [comment]
```
  * AGREED: For now, we will document workarounds for systems that can't
    boot from a FAT16 ESP, including older Raspberry Pi firmware.  Next
    time we change the partition layout, we will switch the ESP to FAT32
    in both the 512b and 4Kn images, selecting a size of at least 257 MB
    to fit a valid FAT32 filesystem.
```

**Comment by bgilbert** [comment]
I've filed https://github.com/coreos/fedora-coreos-docs/issues/326 to track the docs issue.  Let's leave this open, though, since we'd still like to switch to FAT32 in the future.

For the record, there's a lot of good discussion in the [meeting logs](https://meetbot.fedoraproject.org/teams/fedora_coreos_meeting/fedora_coreos_meeting.2021-10-13-16.30.log.html).  pjones pointed out that we're not _violating_ the UEFI spec here because the spec isn't binding on us; we're just depending on firmware behavior which is apparently not mandated by the spec.

**Comment by dustymabe** [comment]
For at least the RPi4 part of this I added a section to the docs in https://github.com/coreos/fedora-coreos-docs/pull/336 that talks about how to update the EEPROM. The docs URL is: https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-raspberry-pi4/#_updating_eeprom_on_raspberry_pi_4

**Comment by cgwalters** [comment]
This intersects with the UKI bits - with UKIs, we don't need a separate `/boot` partition, so we could use that space at least to expand the ESP.
