### ISSUE TITLE
FCOS with 5.14+ kernel fails to boot on xen instances 

### ISSUE THREAD

**Issue by DonaldKellett** [coreos/fedora-coreos-tracker#997]
### Description

Fedora CoreOS 35.20211003.1.0 on AWS (architecture: x86\_64) fails instance reachability check when initialized through the Web interface with SSH key pair (no custom Ignition config), and attempts to connect to the instance via SSH times out.

### Reproduction steps

1. Launch an instance of **fedora-coreos-35.20211003.1.0-x86_64** (`ami-08a2a4f6f7a90e59f`) with default options from the AWS web interface. Select or create an SSH key pair when prompted near the end of the process.
1. Wait a few minutes for the instance to stabilize. Make sure that the instance status is "Running" at the very least.
1. Inspect the status checks. AWS should perform two by default: (1) system reachability check and (2) instance reachability check
1. Connect to the instance via SSH with the appropriate private key: `ssh -i private-key.pem core@instance-public-ip`

### Expected behavior

Both status checks should pass. The SSH connection should be successful.

### Actual behavior

Instance reachability check fails. SSH gives a timeout error.

### System details

- Platform: AWS
- AMI: `ami-08a2a4f6f7a90e59f`
- Fedora CoreOS version: 35.20211003.1.0
- Ignition config: none
- SSH client: `openssh-client` version `1:8.2p1-4ubuntu0.3` on Ubuntu 20.04.3 LTS

### Ignition config

Not applicable

### Additional information

- 16/10/2021: Issue persists with **fedora-coreos-35.20211010.1.0-x86_64** (`ami-0f374d0d2c93f6a46`)

**Comment by bgilbert** [comment]
Please post the console log from the boot attempt.  You may need to either wait 5 minutes after instance boot, or stop the instance, to get AWS to return a non-empty log.

**Comment by dustymabe** [comment]
Also might be really nice to know what ec2 instance type you're using and what type of SSH key you're using.

**Comment by dustymabe** [comment]
`t2.micro` only has 1GiB of RAM and 1vCPU, which is likely the reason we weren't seeing it anywhere else. Do we have defined or should we define some minimum requirements?

**Comment by dustymabe** [comment]
This bug never made it into the `stable` stream.

**Comment by colewhite** [comment]
Experiencing the same symptoms with next/35.20211025.1.0 using the qemu qcow2 image and Vagrant+LibVirt. Speculating around virtio-blk?

[fcos_35.20211025.1.0_boot.txt](https://github.com/coreos/fedora-coreos-tracker/files/7447435/fcos_35.20211025.1.0_boot.txt)

**Comment by bgilbert** [comment]
@colewhite This week's releases on the `testing` and `next` channels will have a more comprehensive fix for this problem.  Please try next 35.20211029.1.0 or testing 34.20211031.2.0 once they're out, and let us know if you're still seeing the issue.

**Comment by colewhite** [comment]
@bgilbert Thanks for replying!

I experimented with the qemu virtualization setup described in the fcos docs and found they worked fine.  Turns out my disk was 8gb and versions 34 and 35 need a disk 10gb or greater.

I think the partitioner failed at some point and gave no indication except the error that led me to this task.
