### ISSUE TITLE
Include new `podman` with `quadlet` functionality

### ISSUE THREAD

**Issue by deuill** [coreos/fedora-coreos-tracker#998]
Please try to answer the following questions about the package you are requesting:

1. **What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)**
Requires `podman` and `crun`, both of which are provided in base already.

2. **What is the size of the package and its dependencies?**
Unsure, though likely less that 50kB.

3. **What problem are you trying to solve with this package? Or what functionality does the package provide?**
Integrating Podman with systemd requires that either `podman generate systemd` is used (which presupposes a Podman container, isn't as configurable, and produces files that aren't intended for further editing), or that equivalent integration is done manually and in a repeated manner. Quadlet solves the issue of integration with systemd as a starting point in a much more elegant way.

4. **Can the software provided by the package be run from a container?  Explain why or why not.**
This is intended to be used on the base system itself, and generates service files that themselves orchestrate Podman containers.

5. **Can the tool(s) provided by the package be helpful in debugging container runtime issues?**
Likely not, though they will likely help alleviate issues with misconfigured integrations.

6. **Can the tool(s) provided by the package be helpful in debugging networking issues?**
I don't believe so.

7. **Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.**
It's possible, though unwieldy for such a small utility.

8. **In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?**
This will likely only provide a binary and related support files for systemd generators.

9. **Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)**
I don't believe so.

10. **Does the software provided by the package have a history of CVEs?**
It does not, though it's a fairly young project.

**Comment by travier** [comment]
I'm +1 for including quadlet once we have confidence that the interface will be relatively stable going forward. I would have preferred to not add more C code to FCOS (Rust or Go would be great here) but this should not be security critical so this would be OK.

**Comment by dustymabe** [comment]
Would be nice to sync up with quadlet devs and podman team again on future here. @travier could you reach out?

**Comment by travier** [comment]
Clearing assignee as I'm not actively working on this

**Comment by LorbusChris** [comment]
It looks like work to port quadlet to go, and add it to podman, is on its way: https://github.com/containers/quadlet/pull/41

**Comment by ibotty** [comment]
This is now obsolete because it's part of the next podman release.   This issue can be closed.

**Comment by travier** [comment]
https://github.com/containers/podman/pull/16035 > This has been merged 🎉 So this will likely come in the next podman release (might still be a sub package).

**Comment by lukasmrtvy** [comment]
quadlet is now included in 4.4.0 https://github.com/containers/podman/releases/tag/v4.4.0-rc3

**Comment by travier** [comment]
podman 4.4.0 has been released: https://github.com/containers/podman/releases/tag/v4.4.0
Now waiting for it to land in F37: https://bodhi.fedoraproject.org/updates/FEDORA-2023-cfd20af4dc

**Comment by travier** [comment]
We have to make a PR to add the `-quadlet` subpackage: https://src.fedoraproject.org/rpms/podman/blob/rawhide/f/podman.spec#_314

**Comment by travier** [comment]
Would be great if folks interested by this functionality would make a test for it.

**Comment by travier** [comment]
Hum, I'm trying it in https://github.com/coreos/fedora-coreos-config/pull/2216 but got:

```
warning: Couldn't find locked package 'podman-5:4.4.0-1.fc37'
  Packages matching NEVRA: 0; Mismatched checksums: 0
  Packages matching name and arch (18):
  podman-3:4.0.1-2.fc36.x86_64 (fedora-coreos-pool)
  podman-3:4.0.1-2.fc37.x86_64 (fedora-coreos-pool)
  podman-3:4.0.2-1.fc36.x86_64 (fedora-coreos-pool)
  podman-3:4.0.3-1.fc36.x86_64 (fedora-coreos-pool)
  podman-3:4.1.0-1.fc36.x86_64 (fedora-coreos-pool)
  podman-3:4.1.0-8.fc36.x86_64 (fedora-coreos-pool)
  podman-3:4.1.1-1.fc36.x86_64 (fedora-coreos-pool)
  podman-3:4.1.1-2.fc36.x86_64 (fedora-coreos-pool)
  podman-4:4.1.1-3.fc36.x86_64 (fedora-coreos-pool)
  podman-4:4.2.0-2.fc36.x86_64 (fedora-coreos-pool)
  podman-4:4.2.0-2.fc37.x86_64 (fedora-coreos-pool)
  podman-4:4.2.1-2.fc36.x86_64 (fedora-coreos-pool)
  podman-4:4.2.1-2.fc37.x86_64 (fedora-coreos-pool)
  podman-4:4.3.0-2.fc36.x86_64 (fedora-coreos-pool)
  podman-4:4.3.0-2.fc37.x86_64 (fedora-coreos-pool)
  podman-4:4.3.1-1.fc37.x86_64 (fedora-coreos-pool)
  podman-4:4.2.1-2.fc37.x86_64 (fedora)
  podman-4:4.3.1-1.fc37.x86_64 (fedora-updates)
warning: Couldn't find locked package 'podman-quadlet-5:4.4.0-1.fc37'
  Packages matching NEVRA: 0; Mismatched checksums: 0
  No packages matched name: podman-quadlet arch: 
error: Packages not found: podman, podman-quadlet
```

Looks like it's not looking at the testing repo.

**Comment by dustymabe** [comment]
> Trying this in [coreos/fedora-coreos-config#2216](https://github.com/coreos/fedora-coreos-config/pull/2216).

Since `4.4.0` just got released and our next round of FCOS releases is approximately next Tuesday, I'm thinking maybe we should hold this until at least the RPM has passed bodhi stable before we ship it in `testing`.

Of course, we should run it through our CI to get any early feedback on it (as is already being done in https://github.com/coreos/fedora-coreos-config/pull/2216).

WDYT?

**Comment by travier** [comment]
Definitely agree not to fast-track this one. My PR is doing that only in order to be able to test it now.

**Comment by dustymabe** [comment]
> Definitely agree to not fast-track this one. My PR is doing that only in order to be able to test it now.

Now that this week's releases are out of the way I propose we go ahead and get this in `testing-devel` for more testing.

It won't ship in `testing` until the 21st anyway.

**Comment by dustymabe** [comment]
The fix for this went into `next` stream release `37.20230218.1.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `testing` stream release `37.20230218.2.0`. Please try out the new release and report issues.

**Comment by dustymabe** [comment]
The fix for this went into `stable` stream release `37.20230218.3.0`.
